### ISSUE TITLE
[Filebeat/Metricbeat] Update autodiscover docs to mention availability of docker host config option

### ISSUE THREAD

**Issue by a-abella** [elastic/beats#10065]
The docs for the `add_docker_metadata` processor clearly define a `host` configuration option that allows the user to specify alternate socket paths or TCP endpoints for communication with the docker daemon API. The Autodiscover docs define no such option, but it works.

This is a valid configuration (using Filebeat 6.4.0) that correctly communicates with dockerd via `tcp://127.0.0.1:2375`:
```
filebeat.autodiscover:
  providers:
    - type: docker
      host: "tcp://127.0.0.1:2375"
      templates:
        - condition:
            contains.docker.container.image: nginx
          config:
            - module: nginx
              access:
                input:
                  type: docker
                  containers.ids:
                    - ${data.docker.container.id}
```

It would be useful to have this option provided in the docs for future users, along with any other undocumented config options should they exist. I was lucky enough to find this one when I needed it by guessing.
