### ISSUE TITLE
Filebeat and Logstash using SSL

### ISSUE THREAD

**Issue by Desjeunf** [elastic/beats#1007]
Hello everyone. 

I'm facing a doubt with my configuration of Filebeat - Logstash and I hope you'll be able to solve my problem.

I've a Filebeat on 192.168.8.36 with this configuration file:
```
filebeat:
  prospectors:
    -
      paths:
        - "/var/log/apache2/access.log"
        - "/var/log/apache2/error.log"
   
      input_type: log
      document_type: log
      registry_file: /var/lib/filebeat/registry

output:
  logstash:
    hosts: ["192.168.8.49:5044"]
    tls:
      certificate_authorities: ["/etc/filebeat/log.crt"]
      certificate: "/etc/filebeat/log.crt"
      certificate_key: "/etc/filebeat/log.key"

logging:
  to_files: true

  files:
    path: /var/log/filebeat
    name: filebeat.log
    rotateeverybytes: 10485760
    keepfiles: 7
    level: debug
```

and a Logstash on 192.168.8.49 with this configuration:
```
input {

   beats {
	port => "5044"
	type => "logs"
	ssl => true
	ssl_certificate => "/etc/logstash/log.crt"
	ssl_key => "/etc/logstash/log.key"
	} 
}

output {

    elasticsearch{
        hosts => ["localhost:9200"]
        index => "test_filebeat-%{+YYYY.MM.dd}"
    }
}
```

My question is: is that a good configuration to make filebeat and logstash exchanging with SSL? 
I have a doubt because when I capture traffic with wireshark, I don't see any SSL negociation paquet. 

My certificates are auto signed by the way. 

Thank you for your attention and for your help. And sorry for bad English ^^' you know... French... :)
