### ISSUE TITLE
Prospector config improvement

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#1033]
# Prospector configuration defaults

The current filebeat prospecto configuration is somehow confusing as people forget the - for the prospectors. To make it easier to understand and less error prone, the intention is to place one configuration directly behind the -. Below are 2 options, I suggest to go with the input_type option.

## Current version

```
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    # Each - is a prospector. Below are the prospector specific configurations
    -
      # Paths that should be crawled and fetched. Glob based paths.
      # To fetch all ".log" files from a specific level of subdirectories
      # /var/log/*/*.log can be used.
      # For each file found under this path, a harvester is started.
      # Make sure not file is defined twice as this can lead to unexpected behaviour.
      paths:
        - /var/log/*.log

      # Type of the files. Based on this the way the file is read is decided.
      # The different types cannot be mixed in one prospector
      #
      # Possible options are:
      # * log: Reads every line of the log file (default)
      # * stdin: Reads the standard in
      input_type: log


    # Additional prospector
    #-
      # Configuration to use stdin input
      #input_type: stdin
```

## input_type option

This is my preferred option, as input_type must exist for each prospector. The default prospector is log and it would also work without it, but I think it is good to get people to have it in.

The part I don't like yet is the way the documentation looks. It would be nice to get some ideas here.

```
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    # Each - is a prospector. Below are the prospector specific configurations
	
      # Type of the files. Based on this the way the file is read is decided.
      # The different types cannot be mixed in one prospector
      #
      # Possible options are:
      # * log: Reads every line of the log file (default)
      # * stdin: Reads the standard in
    - input_type: log
	
      # Paths that should be crawled and fetched. Glob based paths.
      # To fetch all ".log" files from a specific level of subdirectories
      # /var/log/*/*.log can be used.
      # For each file found under this path, a harvester is started.
      # Make sure not file is defined twice as this can lead to unexpected behaviour.
      paths:
        - /var/log/*.log


    # Additional prospector

	   # Configuration to use stdin input
    #- input_type: stdin
      
```

## paths option

As most people use the log type and paths are required, this one makes it obvious how to define paths.

Concerning comments it has the same issues as the input_type option. 

For a different input_type either input_type could be put on a new line or we mix the different options (as below).

```
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    # Each - is a prospector. Below are the prospector specific configurations
    
      # Paths that should be crawled and fetched. Glob based paths.
      # To fetch all ".log" files from a specific level of subdirectories
      # /var/log/*/*.log can be used.
      # For each file found under this path, a harvester is started.
      # Make sure not file is defined twice as this can lead to unexpected behaviour.
    - paths:
        - /var/log/*.log

      # Type of the files. Based on this the way the file is read is decided.
      # The different types cannot be mixed in one prospector
      #
      # Possible options are:
      # * log: Reads every line of the log file (default)
      # * stdin: Reads the standard in
      input_type: log


    # Additional prospector

      # Configuration to use stdin input
    #- input_type: stdin
```
