### ISSUE TITLE
Filebeat + docker input - cannot drop events according to container name?

### ISSUE THREAD

**Issue by nicokruger** [elastic/beats#10393]
I cannot for the life of me figure out why the following is not working:

This is using the elastic Filebeat 6.5.2 docker container:

```
filebeat.inputs:
- type: docker
  containers.ids: '*'
  combine_partial: true
  processors:
    - dissect:
        tokenizer: "%{stack}-%{service}.%{key}"
        field: "docker.container.name"
        target_prefix: "swarm"
    - drop_event:
        when:
          equals:
            docker.container.name: "filebeat"
```

I literally want to not log anything related to the ELK stack. I've tried many combinations of getting an OR to work, using a regexp etc. but maybe someone can spot what I'm doing wrong with this simple example?

I expect the above to drop all log messages from the "filebeat" container.

**Comment by nicokruger** [comment]
Anyone have any ideas?

**Comment by ruflin** [comment]
For questions please use discuss: https://discuss.elastic.co/c/beats/filebeat Happy to answer there. If we find it's a bug, we can reopen this issue.

**Comment by lawniczek-piotr** [comment]
@nicokruger did you find solution to that ?

**Comment by shubham2508** [comment]
Any solution for this ?

**Comment by ragrahari** [comment]
I found a working solution for something similar based on what is recommended [here-discuss.elasticsearch.co](https://discuss.elastic.co/t/processor-drop-event-not-dropping-events/72186/8)
```
      - drop_event.when.not.or:
          - equals.kubernetes.namespace: "my-app-namespace1"
          - equals.kubernetes.namespace: "my-app-namespace2"
          - equals.kubernetes.namespace: "my-app-namespace3"
```
I wanted to drop events coming from all the namespaces that don't match my application namespaces. Combined the field `kubernetes.namespace` with `equals` and it worked.
