### ISSUE TITLE
Winlogbeat Missing Events

### ISSUE THREAD

**Issue by neu5ron** [elastic/beats#10435]
When collecting windows logs (specifically from the Application Channel) there will be missing event source_name's which is usually a subset of a larger Channel.

comparison notes to NXLog:
https://gist.github.com/neu5ron/6899ac2de9103cc6db1a2a0fd6eb0f14

winlogbeat config:
```
winlogbeat.event_logs:
  - name: Application
  - name: Security
  - name: System
  - name: "Microsoft-Windows-Sysmon/Operational"
  - name: "Microsoft-Windows-WLAN-AutoConfig/Operational"
output.kafka:
  enabled: true
  hosts: ["bobsbigwheel.local:909,"bobsbigwheel.local:9093"]
  topic: "winlogbeat"
 max_message_bytes: 1000000
```
- Version: 
6.5.4
- Operating System: 
win 7
- Steps to Reproduce: 
collect windows logs... especially from Application (channel)
