### ISSUE TITLE
[Filebeat] Make Suricata module append to destination.domain list

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#10510]
**Describe the enhancement:**
Enhance the Suricata pipeline to append to the `destination.domain` field if it already exists (make it into an array).

I'm using a processor setup like this so I can enrich events with my local network's hostnames.

```
processors:
    - dns:
        type: reverse
        fields:
          source.ip: source.domain
          destination.ip: destination.domain
          # Suricata Module
          json.src_ip: source.domain
          json.dest_ip: destination.domain
```

But this causes a cascading failure in the pipeline. The pipeline fails at setting the `destination.domain` field and bails out. I was expecting to be able to see the error in the indexed event as `error.message`, but what actually happened was an indexing failure because the pipeline's final `remove` processor had not run which causes `{"type":"mapper_parsing_exception","reason":"failed to parse","caused_by":{"type":"illegal_argument_exception","reason":"Cannot write to a field alias [suricata.eve.event_type]."}}`.

**Describe a specific use case for the enhancement or feature:**

To be able to use the `dns` processor with the `suricata` module in order to do reverse DNS enrichment on events.
