### ISSUE TITLE
[CM] Reload not reloading always 

### ISSUE THREAD

**Issue by ph** [elastic/beats#10547]
I have been testing elastic/beats#10491 and I have saw cases where the reload of configuration did not happen correctly. At first, I thought It was because of an aggressive reload period or fixed for the leaks but this is not the case. I can reproduce the issue all the time with the 6.6 branch.

Steps:

1. Edit the `api/configurations.go` and make sure that equals always return false, this will force the manager to reload the on each fetch.

2. Use a simple log generator to create an infinite file.

```ruby
LOG_FILE = "/tmp/super.log"
File.delete(LOG_FILE) if File.exist?(LOG_FILE)
File.open(LOG_FILE, "w+") do |f|
  loop do
    print "."
    f.write("hello world\n")
  end
end
```

3. Use the following configuration:

```yaml
configok: true
configs:
- type: filebeat.inputs
  blocks:
  - raw:
      paths:
      - /tmp/super.log
- type: output
  blocks:
  - raw:
      elasticsearch:
        hosts:
        - 127.0.0.1
        password: changeme
        username: elastic
      output: elasticsearch
```

4. set a 30s or less for the `management.period` option.

5. start filebeat with the following command:

```
./filebeat -v -e -d "centralmgmt,elasticsearch,harvester"    
```

You should see Filebeat read the file and send events to ES on startup, it will periodically fetch and reload the configuration and then it will stop sending events.
