### ISSUE TITLE
Metricbeat - does not collect metrics on network drives in Windows

### ISSUE THREAD

**Issue by Yelliny** [elastic/beats#10664]
Hi,
After working with Metricbeat for a while I have noticed that it does not collect metrics on network drives (NFS) in Windows (in Linux it does). 
It would be great if they were.

Thanks!

**Comment by narph** [comment]
hi @Yelliny, what are the exact operating systems you are transferring files between using the NFS protocol?
Also, what is the metricbeat configuration you are testing with at the moment (modules/metricsets etc), it will help us narrow down any issues here.

**Comment by qwinkler** [comment]
Hi there! Looks like it wasn't fixed. I also faced this problem.

- Version: 7.6.1
- Operating System: Windows
- Discuss Forum URL (also more details here): https://discuss.elastic.co/t/metricbeat-filesystem-metrics-does-not-include-remote-network-drives/252346
- Steps to Reproduce:
Attach any(I guess any, like NFS or something else, but I used S3 bucket with TntDrive(https://tntdrive.com/)) network device and run **metricbeat** > 6.3.0 with the following configuration file:
```yml
metricbeat.modules:
- module: system
  enabled: true
  period: 60s
  processes: ['.*']
  filesystem.ignore_types: []
  metricsets:
    - process
    - filesystem # is required
  processors:
    - drop_event.when.regexp.mount_point: '^/(sys|cgroup|proc|dev|etc|host)($|/)'
```

Metricbeat will only collect the data from local drives, not the remote ones.
