### ISSUE TITLE
Nested (recursive) escaping in Filebeat's log when Filebeat is configured to ship its own logs

### ISSUE THREAD

**Issue by to-bar** [elastic/beats#10691]
- Version: 6.5.4
- Operating System: Red Hat 7.5
- Steps to Reproduce: 
1) In /etc/filebeat/filebeat.yml:
```
- type: log
  include_lines: ['ERROR', 'WARN']
  paths:
    - /var/log/filebeat/filebeat*
```
2) Switch Elasticsearch to read only mode (this happens when disk space is low):
`curl -X PUT '${ES_HOST_IP}:9200/_all/_settings' -H 'Content-Type: application/json' -d'{ "index.blocks.read_only_allow_delete" : true } }'`

3) Check /var/log/filebeat/filebeat, there is a lot of slashes, like:
FileStateOS:file.StateOS{Inode:0x1297222, Device:0x802}}}, Flags:0x1} (status=403): {\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"type\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"cluster_block_exception\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\",\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"reason\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\":\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];

[filebeat.log](https://github.com/elastic/beats/files/2855271/filebeat.log)

**Comment by longzl2015** [comment]
I follow the instructions on the [page](https://www.elastic.co/guide/en/beats/filebeat/master/running-on-kubernetes.html).
I meet the same problem too.

docker image:
- elastic/filebeat:7.2.0
- logstash:7.2.0

filebeat.conf:

```
    filebeat.inputs:
    - type: container
      paths:
        - /var/lib/docker/containers/*/*.log
      include_lines: ['spring-boot-app']
    processors:
      - drop_fields:
          fields: ["host","ecs","input","stream","agent","log"]
    output.logstash:
      hosts: ["elk.elastic:9260"]
```

logstash.conf:

```
    input {
      tcp {
        port => 9250
        codec => json_lines
      }
      beats {
        port => 9260
      }
    }

    output {
      stdout {}
    }
```
