### ISSUE TITLE
[Heartbeat] HTTP 302 redirect behavior

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#10823]
I'm monitoring an HTTP endpoint that returns a 302 redirect to send clients to the HTTPS site. Heartbeat is making 10 requests for each check instead of just one. It's a lot more HTTP requests than I expected to see.

Ideally for this use case Heartbeat would not follow redirects. I didn't find anything in the documentation that describes Heartbeat's redirect following behavior. But the Go HTTP client's default behavior is: 

> 	// If CheckRedirect is nil, the Client uses its default policy,
>	// which is to stop after 10 consecutive requests.

- Version: Heartbeat 6.6.0
- Operating System: Centos 6
- Steps to Reproduce: Here's the config that I'm using:

```
heartbeat.monitors:
    - 
      check.response.status: 302
      tags: 
        - internal
        - redirect
      schedule: "@every 30s"
      type: http
      mode: all
      urls: 
        - "http://va.crowbird.com:80"
```

The DNS response returns a single private IP address.

```
$ dig va.crowbird.com
;; ANSWER SECTION:
va.crowbird.com.	3600	IN	A	10.x.y.z
```

This screenshot shows two consecutive checks from Heartbeat as captured by Packetbeat. Each row represents one HTTP requests made by Heartbeat.

<img width="1273" alt="screen shot 2019-02-19 at 12 51 50 am" src="https://user-images.githubusercontent.com/4565752/53021894-2ffda900-3428-11e9-848f-672fe1b7dcab.png">
