### ISSUE TITLE
Handle NaNs in prometheus metrics

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#10849]
Prometheus metrics can contain `NaN/+Inf/-Inf` values, they fail to be serialized for outputs.

Seen at least with file and kafka outputs with metricbeat 6.6.0.

**Comment by pawelprazak** [comment]
Can confirm for v6.7.2 and v7.0.1 with this settings:
```
    - module: prometheus
      period: 10s
      host: ${NODE_NAME}
      hosts: ["prometheus.monitoring.svc.cluster.local:9090"]
      namespace: monitoring
      metrics_path: '/federate'
      query:
        'match[]': '{__name__!=""}'
```
