### ISSUE TITLE
Missing docs for add_fields, add_labels, add_tags processors

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#10879]
We recently added some new processors but we don't have documentation for them.

- add_fields - https://github.com/elastic/beats/pull/10119
- add_tags, add_labels - https://github.com/elastic/beats/pull/9973

And once we add documentation I think we can close out:

- #7350
- #4518

**Comment by andrewkroh** [comment]
Here's something to get us started.

## add_fields

Parameters

- fields - Required.
- target - Optional. Defines where to add the fields. Default is `fields`. Use empty string to write to the root of the event.

```
processors:
- add_fields:
    fields:
      hello: world
```
This would create.
```
{
  "fields": {"hello": "world"}
}
```
This add fields to the root.
```
processors:
- add_fields:
    fields:
      hello: world
    target: ""
```
And creates:
```
{"hello": "world"}
```

## add_labels

Parameters
- labels: Required. Labels to add to the event.

```
processors:
- add_labels:
    labels:
      co.elastic.application: webserver
```

## add_tags

Parameters
- tags: Required. List of tags to append. The processor does not deduplicate tags.
- target: Optional. Default value is `tags`

```
processors:
- add_tags:
    tags: ["foo", "bar"]
```
