### ISSUE TITLE
[heartbeat] Incorrectly saying site is down when it is up

### ISSUE THREAD

**Issue by jamiesmith** [elastic/beats#10903]
Working with Heartbeat, I have a config like this: 
```
- type: http
  schedule: '@every 5s'
  urls:
    - "https://discuss.elastic.co/"
```
A curl against that domain works every time:

`curl -sI https://discuss.elastic.co/ | head -1`
```HTTP/1.1 200 OK```

However, when heartbeat hits it, it always gets `received status code 403 expecting 200` - I even connected to the container which heartbeat is running in and curl still gets the correct 200.

For confirmed bugs, please report:
- Version:  
    - 6.7.0-SNAPSHOT
- Operating System: 
    - Docker version 18.09.2, build 6247962
- Steps to Reproduce: 
    - launch heartbeat with the above configuration
