### ISSUE TITLE
[Metricbeat] Access Kubernetes metrics from somewhere other than the read-only kublet port

### ISSUE THREAD

**Issue by dpankros** [elastic/beats#10937]
Currently, it appears that metricbeat fetches metrics for kubernetes from the read-only http-metrics port (10255).  [Using this port is now deprecated](https://github.com/kubernetes/kubeadm/issues/732).  Kubernetes metrics need to be fetched through some other mechanism in the **near** future.

To make matters worse, the AWS EKS AMI has [dropped support for the readonly port](https://github.com/awslabs/amazon-eks-ami/issues/128) in recent versions.  Out of the box, **metricbeat no longer works on EKS** without doing some custom work to the kubelet on the node.  We upgraded recently to gain the benefit of other fixes implemented in the recent AMIs (like logrotate) and now we don't see **any** pod metrics.

This is somewhere between a bug and an enhancement.

**Comment by odacremolbap** [comment]
Hi @dpankros ,

metricbeats do not enforce the read only kubelet port, you can use the commented settings here 

https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-kubernetes.html#_example_configuration_17

if executing as a daemonset something like this should work on a regular kubernete cluster
```
    - module: kubernetes
      metricsets:
        - node
        - system
        - pod
        - container
        - volume
      period: 10s
      host: ${NODE_NAME}
      hosts: ["https://${NODE_NAME}:10250"]
      enabled: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      ssl.verification_mode: none
      ssl.certificate_authorities:
        - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```
