### ISSUE TITLE
Jolokia module failed to parse response for some metrics with GET method

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#11071]
Jolokia module fails to parse some responses fetched using the GET method with the error:
```
json: cannot unmarshal number into Go struct field Entry.Value of type map[string]interface {}
failed to unmarshal jolokia JSON response '{"request":{"mbean":"java.lang:type=Runtime","attribute":"Uptime","type":"read"},"value":88622,"timestamp":1551739190,"status":200}'
```

For confirmed bugs, please report:
- Version: >= 6.6.0 (only seems to affect GET method)
- Steps to Reproduce: 
Use this config with the jolokia module:
```
  http_method: 'GET'
  jmx.mappings:
    - mbean: 'java.lang:type=Runtime'
      attributes:
         - attr: Uptime
           field: uptime
```

Reproduced also adding this case to the Jolokia integration tests:
```
                                {
                                        "mbean": "java.lang:type=Runtime",
                                        "attributes": []map[string]string{
                                                {
                                                        "attr":  "Uptime",
                                                        "field": "uptime",
                                                },
                                        },
                                },
```
