### ISSUE TITLE
FileBeat Ignores enabled setting in prospector config

### ISSUE THREAD

**Issue by cawoodm** [elastic/beats#11108]
FileBeat 6.6.1 / Windows (ES 6.5)

FileBeat is watching folders which we have disabled by setting enabled: false in the prospector's .yml configuration.

This may not be a BUG per se but it's confusing for users who copy their.

### filebeat.yml:
```
filebeat.config.prospectors:
  enabled: true
  path: D:\elk\filebeat\config\*access_prod.yml
```

### config\filebeat_access_prod.yml:
```
# Parse app02 apache tomcat "access" log
- type: log
  enabled: false
  paths:
    - D:\app02-logs\tomcat\access.*.log
```

As we can see it is watching the disabled folder:
![image](https://user-images.githubusercontent.com/498834/53871683-04b8b380-3ffd-11e9-9f09-1a4c19580747.png)

And picking up files there:
![image](https://user-images.githubusercontent.com/498834/53871698-0c785800-3ffd-11e9-9f47-d81df3fdb655.png)

**Comment by AndrewMcQuerry** [comment]
Seeing the same thing in filebeat version 6.5.4.  We're setting the `enabled` field to `false` within a `- type: log` or `- type: docker` and it seems to be ignoring that setting and starting up those harvesters regardless.

**Comment by peterpramb** [comment]
Unfortunately this issue still exists in 7.5.2 (Linux).

- `filebeat.yml`
```
filebeat.config.inputs:
  enabled: true
  path: "${APP_CONF}/inputs/*.yml"
  reload.enabled: true
  reload.period: 60s
```
- `inputs/log-cim-es.yml`
```
- type: log
  enabled: false
  paths:
  - "/app/cim-es/logs/gc.log.[0-9]*"
  - "/app/cim-es/logs/gc.log"

  exclude_files: ['\.gz$', '\.bz2$', '\.xz$']
  exclude_lines: ["^(OpenJDK|Java HotSpot).* Server VM ", "^CommandLine flags: ", "^Memory: ", " GC log file "]

  multiline:
    pattern: '^\[?[0-9]{4}-[0-9]{2}-[0-9]{2}'
    negate: true
    match: after

  fields_under_root: true
  fields:
    event:
      dataset: "elasticsearch.gc"
      module: "log"
    service:
      name: "elasticsearch.cim-es"
      type: "elasticsearch"
      version: "7.5.2"
```
- `filebeat.log`
```
2020-02-14T22:41:32.771+0100    INFO    log/input.go:152        Configured paths: [/app/cim-es/logs/gc.log.[0-9]* /app/cim-es/logs/gc.log]
2020-02-14T22:41:32.771+0100    INFO    input/input.go:114      Starting input of type: log; ID: 15245997374363375058 
2020-02-14T22:41:32.773+0100    INFO    log/harvester.go:251    Harvester started for file: /app/cim-es/logs/gc.log
2020-02-14T22:41:32.774+0100    INFO    log/harvester.go:251    Harvester started for file: /app/cim-es/logs/gc.log.27
```
