### ISSUE TITLE
[7.0 upgrade] Metricbeat BWC index template rejected because rabbitmq.node.name alias refers to itself

### ISSUE THREAD

**Issue by cjcenizal** [elastic/beats#11275]
To reproduce:

1. Set up multi-node 6.7 cluster. Perform rolling upgrade to 7.0.
2. Set `migration.enabled: true` in metricbeat config.
3. Run `sudo ./metricbeat setup --template -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["localhost:9200"]'`

Elasticsearch rejects the request with error:

```json
{
  "error":{
    "root_cause":[
      {
        "type":"remote_transport_exception",
        "reason":"[2][127.0.0.1:9301][indices:admin/template/put]"
      }
    ],
    "type":"illegal_argument_exception",
    "reason":"Invalid [path] value [rabbitmq.node.name] for field alias [rabbitmq.node.name]: an alias cannot refer to itself."
  },
  "status":400
}
```

CC @bhavyarm I think you were seeing this error at some point, too.

**Comment by cjcenizal** [comment]
I just tried doing this with a 7.0 stack to set a baseline, and ran into the same error. Here's my metricbeat config:

```yaml
setup.dashboards.enabled: true

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.kibana:
  host: "localhost:5601"

output.elasticsearch:
  hosts: ["localhost:9200"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

migration.enabled: true
```

Here's what I ran in the command line: `sudo ./metricbeat setup --template -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["localhost:9200"]' -E setup.template.settings.index.number_of_shards=5`.

The result was an identical error to the one above. Possibly something misconfigured in the index template?
