### ISSUE TITLE
Add ability to override configuration settings using environment variables.

### ISSUE THREAD

**Issue by mingfang** [elastic/beats#114]
I'm trying to deploy the packetbeat agent to a cluster of machines using kubernetes.
However the ElasticSearch hostname needs to be configurable at deployment time.
I would like the ability to set that using environment variables, 
e.g. 
```
export PACKETBEAT_ELASTICSEARCH_HOST=dynamic-host
```

**Comment by tsg** [comment]
Good suggestion, we'll add it.

**Comment by albanm** [comment]
+1

How about using [viper](https://github.com/spf13/viper) for a more complete config system ?

If you lack the time but are ok with the idea I am willing to attempt a pull request (total go newbie here, but this should not be too difficult).

**Comment by yoanisgil** [comment]
I think this an excellent idea. I have a config file which looks like this:

```yml
filebeat:
  prospectors:
    -
      paths:
        - "/var/log/supervisor/nginx*.log"
      input_type: log
      fields:
        source: nginx
        level: info
        environment: development
output:
    console:
        pretty: true
    logstash:
        hosts: ["logstash.mpl.ninja:5044"]
```
and I would like to be able to configure the list of logstash `hosts` as well as the `environment` setting. The reason I need to do so is because I need to provide support for dev/staging/production environments the later 2 being AWS Beanstalk environments which are updated via Jenkins.

Anyone working on this? I could give a try if this is something you're willing to implement.
