### ISSUE TITLE
Metricbeat - Monitor Stopped Processes

### ISSUE THREAD

**Issue by Gunnerva** [elastic/beats#11404]
**Describe the enhancement:**
Add the ability to report if a process is not running in addition to its current process state.  Possibly add an additional flag so that in additional to returning running or sleeping it will also report "not running" or "stopped" if the process is not part of the process list.

**Describe a specific use case for the enhancement or feature:**
The ability to report if a process is not running regardless of why it stopped, when it stopped and if it never started.  This can be used for alerting on processes that can't use heartbeat.

Example system.yml:

- module: system
  period: 10s
  metricsets:
    - process
    - report-not-running
  processes: ['kibana']

In the above scenario metricbeat would check every 10s and report the process state if it is running or sleeping, but it would also report that the process is not running if Metricbeat cannot find it in the running process list.

**Comment by beyondmars3** [comment]
I do this but it not work. 
```
- module: system
  period: 5s
  metricsets:
    - cpu
    # - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
    #- entropy
    #- core
    - diskio
    # - socket
    - report-not-running
  # process.include_top_n:
  #   by_cpu: 5      # include top 5 processes by CPU
  #   by_memory: 5   # include top 5 processes by memory
  cpu.metrics: [percentages, normalized_percentages, ticks]
  processes: ['mysql*']
```

```
2019-08-15T19:21:27.897+0800	ERROR	instance/beat.go:877	Exiting: 1 error: metricset 'system/report-not-running' not found

```

**Comment by simioa** [comment]
@ruflin I'm interested in implementing this, can I give it a try?
I thought about creating a new `system.process_state` metricset where one can define multiple processes to check.
Configuration could look like:
```
module: system
metricsets:
  - process_state
process_state.processes:
  - cmdline: ".*metricbeat.*" # regex that matches cmdline
    alias: "metricbeat" # alias assigned to check for easier identification
```

Output could then look like:
```
    "system": {
        "process_state": {
            "process": {
                "name": "metricbeat",
                "command_line": "/usr/share/metricbeat/bin/metricbeat -c metricbeat.yml"
            },
            "cmdline": ".*metricbeat.*",
            "alias": "metricbeat",
            "running": true
        }
    }
```
where the process object containing information about the matched process is only added when "running" is true
