### ISSUE TITLE
Feature - Resolve DNS Enrichment (Forward Lookup)

### ISSUE THREAD

**Issue by morro91** [elastic/beats#11416]
It would be great if WinlogBeat's DNS processor could resolve IP addresses given a hostname (Forward Lookup).

Especially useful in Windows world, caching would be necessary.

An extension to #7770, similar to Logstash's DNS filter (https://www.elastic.co/guide/en/logstash/current/plugins-filters-dns.html).

To add 'resolve' to Winlogbeat (and/or others) to DNS processor.

**Comment by andrewkroh** [comment]
Do you have a specific use case you could provide?

**Comment by morro91** [comment]
The main use case is Windows Event Forwarding, and then putting Winlogbeat on the collector device. As the collector has logs of X machines, it would be good to enrich with the IP address as the log only has computer_name.

**Comment by BenB196** [comment]
I'd like to add another use case here, it is slightly more of an edge case, but still a valid one I believe.

If, I am using an integration/module, which pulls/collects data from a remote point, but this remote point also pulls data from somewhere to get the data, then the "host" information is actually the middle point. In theory, if the actual data contains the final target, then you can get the name of the target and set it correctly in the event, but you can't get the IP of the target, which makes things somewhat difficult.

Example:

For SNMP monitoring, Elastic doesn't really have a good solution, but Prometheus does with the [snmp_exporter](https://github.com/prometheus/snmp_exporter). So, a weird solution is to use the SNMP exporter to handle then SNMP stuff, then use the Metricbeat [Prometheus collector](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-prometheus-collector.html) module, to scrape the SNMP exporter to collect the data.

This has a few weird side effects though.

1. To be able to use the SNMP exporter, the "host" isn't actually the host you want to scrape metrics from, instead it is the SNMP exporter (example: `localhost:9116`)
    - The "real" host is stored as a URL query parameter called `target`.
    - So, a request looks like: `http://localhost:9116/snmp?module=<your_snmp_module>&target=host.example.com`
2. The above causes a few different issues:
    1. `host` field information gets set to either the Prometheus SNMP exporter (if both Metricbeat and SNMP Exporter are part of the same Kubernetes pod) or doesn't get set at all.
    2. `prometheus.labels.instance` just shows up as `localhost:9116` as technically that is the "host"/"target"
    3. The real information is contained in the field `service.address` (`http://localhost:9116/snmp?module=<your_snmp_module>&target=host.example.com`)

You can somewhat work around this issue, by using processors that:

1. Drop `host`:
```yaml
- drop_fields:
    fields:
      - "host"
    ignore_missing: true
```
2. Set `host.name` correctly:
```
- dissect:
    tokenizer: ""
    field: "service.address"
    target_prefix: '%{}/snmp?module=%{}&target=%{host.name}'
    overwrite_keys: true
    trim_values: 'all'
```
3. Set `host.hostname` correctly:
```
- copy_fields:
    fields:
      - from: host.name
        to: host.hostname
```

**But**, you can never set `host.ip` correctly, as there is no way to perform a forward lookup on `host.name`
