### ISSUE TITLE
[Metricbeat] module HTTP server: Add TLS

### ISSUE THREAD

**Issue by xeraa** [elastic/beats#11457]
**Describe the enhancement:**

The [Metricbeat module for HTTP server](https://github.com/elastic/beats/tree/master/metricbeat/module/http/server) currently doesn't support TLS. This is less of an issue for connections on the same host, but to be able to collect data over the network this would be a good improvement.

**Describe a specific use case for the enhancement or feature:**

[Logstash has an HTTP input that supports TLS](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http.html). To be a lightweight alternative the Metricbeat module would need to add TLS, otherwise it's mainly useful on localhost. This started off from a discussion with @loekvangool.

**Comment by leopucci** [comment]
go net/http already have https. it is just a matter of adjusting it. 

Let me grab a coffee and play with this one :)

**Comment by andrewkroh** [comment]
@leopucci Take a look at `tlscommon.ServerConfig` and how it's used. I think some of this can be reused.

https://github.com/elastic/beats/blob/dba0f7c6d7ed584f1ddb448832e9f2f63f7cb66f/filebeat/inputsource/tcp/config.go#L38

**Comment by leopucci** [comment]
@andrewkroh HttpHelper already have it! Thanks for the tip!

**Comment by leopucci** [comment]
@andrewkroh, ListenAndServeTLS dos not acept certificate object, only certificate path... i will not be able to reuse config:ssl.... it was so beautiful
![giphy (3)](https://user-images.githubusercontent.com/38509299/55030495-47155500-4feb-11e9-9c26-f6ceb93de068.gif)

**Comment by leopucci** [comment]
Tadah!

![capture-26](https://user-images.githubusercontent.com/38509299/55032079-e1c36300-4fee-11e9-9cbf-d323cac878a9.gif)

**Comment by leopucci** [comment]
How to use:
add ssl config on http.yml

```
- module: http
  metricsets:
    - server
  host: "localhost"
  port: "8080"
  enabled: true
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]
  ssl.certificate: "/etc/pki/client/cert.pem"
  ssl.key: "/etc/pki/client/cert.key"
  paths:
    - path: "/foo"
      namespace: "foo"
  #    fields: # added to the the response in root. overwrites existing fields
  #      key: "value"

```
