### ISSUE TITLE
[Filebeat] Empty "filebeat-version-date" indices get created when using ingest processor

### ISSUE THREAD

**Issue by R0ky** [elastic/beats#11504]
Filebeat version: 6.6.2

Elasticsearch version: 6.6.2

OS version: Ubuntu 16.04

Original install method (e.g. download page, yum, from source, etc.): .tar.gz

Describe the bug:
It looks like filebeat creates empty indices called `filebeat-6.6.2-date` when `Date index name` ingest processor is used to point documents to the right time based index. Please note that behaviour remains the same as well if other ingest processors are used that change the name of the index. I've tested with and without running `./filebeat setup` and results remain the same: 

Steps to reproduce: 

1. Deploy a new ES 6.6.2 cluster
2. Configure ingest pipeline:
```
PUT _ingest/pipeline/test
{
  "processors" : [
    {
        "date_index_name" : {
          "field" : "@timestamp",
          "index_name_prefix" : "pipeline-test-",
          "date_rounding" : "M",
          "index_name_format" : "yyyy.MM"
        }
    }
]
      }
```

3. Configure filebeat.yml:
```
filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /logs/*.log

processors:
 - decode_json_fields:
     fields: ['message']
     target: ''
     overwrite_keys: true

 - drop_fields:
     fields: ["message", "prospector", "beat", "source", "offset"]

setup.template.enabled: false

output.elasticsearch:
  hosts: ["https://localhost:9200"]
  username: "elastic"
  password: "password"
  document_type: "_doc"
  bulk_max_size: 1000
  pipeline: "test"
```

4. Run `./filebeat -e` 
5. `GET _cat/indices` (just a part):
```
yellow open filebeat-6.6.2-2017.09.01 STDPscbSSNy57x6ODLMU5g 5 1    0 0   1.1kb   1.1kb
yellow open filebeat-6.6.2-2017.06.03 oVmR8HF7S8mJ4GRiHSzA9A 5 1    0 0   1.1kb   1.1kb
yellow open filebeat-6.6.2-2017.05.21 IjVCH3dzQGyIVmpj7c82hA 5 1    0 0   1.1kb   1.1kb
yellow open filebeat-6.6.2-2017.08.31 BYd53TtERNGcK84iC2lPdA 5 1    0 0   1.1kb   1.1kb
yellow open filebeat-6.6.2-2017.05.07 KlKUBN24STaBdO7i3ioQLw 5 1    0 0   1.1kb   1.1kb
yellow open filebeat-6.6.2-2017.05.25 qCaAovlGSyyhvqHKCf9elQ 5 1    0 0   1.1kb   1.1kb
yellow open pipeline-test-2017.06            VIr4TkhMTTaEW_O8-VFkNA 5 1  603 0 665.7kb 665.7kb
```

6. After that I deleted all the filebeat and failed indices from ES, and removed filebeat registry and meta.json from data directory. 

7. Run `./filebeat setup` (kibana error is expected):
```
rok@node-1:~/filebeat-6.6.2-linux-x86_64$ ./filebeat setup
Loaded index template
Loading dashboards (Kibana must be running and reachable)
Exiting: fail to create the Kibana loader: Error creating Kibana client: Error creating Kibana client: fail to get the Kibana version: HTTP GET request to /api/status fails: fail to execute the HTTP GET request: Get http://localhost:5601/api/status: dial tcp [::1]:5601: connect: connection refused. Response: .
```

8. Run `./filebeat -e` 
9. GET _cat/indices (just the relevant part of result):
```
yellow open filebeat-6.6.2-2017.05.03 cq65Ba_fQvyduPpXLyPivw 5 1    0 0   1.1kb   1.1kb
yellow open filebeat-6.6.2-2017.05.11 Y64ls7EgThavpQFJK9mCSA 5 1    0 0    460b    460b
yellow open filebeat-6.6.2-2017.07.09 yOT6yacKReWEtxoX40R8rQ 5 1    0 0    460b    460b
yellow open filebeat-6.6.2-2017.08.21 OdXBoc2RTlaxWECo_ppJaw 5 1    0 0    460b    460b
yellow open filebeat-6.6.2-2017.05.23 epi5jpvGR4CL8tS8XGb_0w 5 1    0 0    460b    460b
yellow open filebeat-6.6.2-2017.07.19 Cpwlx9F0QDyCIPTrMSrycg 5 1    0 0   1.1kb   1.1kb
yellow open pipeline-test-2017.03            IVrN7G60SrqbUJhOvgb8YQ 5 1   17 0  85.2kb  85.2kb
```
