### ISSUE TITLE
Provide a fuller example in modules.d/elasticsearch.yml.disabled

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#11548]
Currently, the out of the box modules.d/elasticsearch.yml.disabled file shows just the following:

```
# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/6.7/metricbeat-module-elasticsearch.html

- module: elasticsearch
  #metricsets:
  #  - node
  #  - node_stats
  period: 10s
  hosts: ["http://localhost:9200"]
  #username: "user"
  #password: "secret"
```

Will be nice if we improve the above to the following:

```
# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/6.7/metricbeat-module-elasticsearch.html


- module: elasticsearch
  metricsets:
    - ccr
    - cluster_stats
    - index
    - index_recovery
    - index_summary
    - ml_job
    - node
    - node_stats
    - shard
  period: 10s
  hosts: ["http://localhost:9200"] 
  username: "user"
  password: "secret"
  xpack.enabled: true
```

The above will be consistent with the documentation.  Some of the above flags are important (such as xpack.enabled; if missed the monitoring UI will not show any data because the ES module metrics would be indexed to metricbeat* indices instead of .monitoring* by default).

Speaking of [documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-metricbeat.html), Step 3c is missing `- node` btw.
