### ISSUE TITLE
[CM] Make the monitoring reloadable and configurable by CM.

### ISSUE THREAD

**Issue by ph** [elastic/beats#11576]
The beats can be configured to send the collected monitoring information to Elasticsearch, this option is globally set in the YAML config with the following:

```
xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["https://example.com:9200", "https://example2.com:9200"]
    username: beats_system
    password: somepassword
```

We have to do the following changes:

- Allow a beat to enable monitoring from CM.
- Allow to reconfigures monitoring in a running process. (Previously monitoring is set once at boot time.)
- Add a new type of config block to allow to reconfigure the monitoring from the manager.

**Notes:** The monitoring uses an internal pipeline so we may be able to reuse existing logic.
