### ISSUE TITLE
add_docker_metadata false positive

### ISSUE THREAD

**Issue by hholst80** [elastic/beats#11684]
The following log entry is populated erroneously with docker metadata.
My assumption is that journalbeat looks at the unit and finds "docker" in the string and therefore assumes it is log entry from inside a container. There is really no need to do that logic if journald is used as a log driver in docker it will say explicitly what logs that comes from a container. Just expose the information that is there. Example attached in the end.

Journal entry:
```
{
        "_EXE" : "/usr/lib/systemd/systemd",
        "MESSAGE" : "var-lib-docker-containers-a34010a7c0ac153e46318ba05e865a7753a6a6523f939011f132b29cc7d021fe-mounts-shm.mount: Succeeded.",
        "_PID" : "1",
        "_GID" : "0",
        "__CURSOR" : "s=9d5f42767d6641ed88fd402aed15dfca;i=905015;b=76232f86194c4353be9a3b46aee4e60b;m=255e5f3d4;t=584ee6c5c1f77;x=9345d20b3d6610f4",
        "_HOSTNAME" : "puff",
        "_UID" : "0",
        "SYSLOG_FACILITY" : "3",
        "__REALTIME_TIMESTAMP" : "1553534438612855",
        "_SYSTEMD_SLICE" : "-.slice",
        "_MACHINE_ID" : "b52ee41f2ace4198adfe01a971521a0d",
        "PRIORITY" : "6",
        "_SYSTEMD_CGROUP" : "/init.scope",
        "MESSAGE_ID" : "7ad2d189f7e94e70a38c781354912448",
        "_CMDLINE" : "/sbin/init",
        "_COMM" : "systemd",
        "_SOURCE_REALTIME_TIMESTAMP" : "1553534438612833",
        "_SYSTEMD_UNIT" : "init.scope",
        "_BOOT_ID" : "76232f86194c4353be9a3b46aee4e60b",
        "__MONOTONIC_TIMESTAMP" : "10031068116",
        "UNIT" : "var-lib-docker-containers-a34010a7c0ac153e46318ba05e865a7753a6a6523f939011f132b29cc7d021fe-mounts-shm.mount",
        "INVOCATION_ID" : "d3d87e303b21484db60bba05e2631595",
        "CODE_FUNC" : "unit_log_success",
        "CODE_FILE" : "../systemd-stable/src/core/unit.c",
        "_TRANSPORT" : "journal",
        "CODE_LINE" : "5496",
        "SYSLOG_IDENTIFIER" : "systemd",
        "_CAP_EFFECTIVE" : "3fffffffff"
}
```

The complete output in ES is as follows
```
{
  "_index": "journalbeat-6.7.1-2019.03.25",
  "_type": "doc",
  "_id": "jGih9GkBvLolRgt0LWNc",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2019-03-25T17:20:38.612Z",
    "systemd": {
      "unit": "init.scope",
      "cgroup": "/init.scope",
      "slice": "-.slice",
      "transport": "journal"
    },
    "beat": {
      "version": "6.7.1",
      "name": "puff",
      "hostname": "puff"
    },
    "journald": {
      "code": {
        "file": "../systemd-stable/src/core/unit.c",
        "line": 5496,
        "func": "unit_log_success"
      }
    },
    "read_timestamp": "2019-04-06T21:49:55.983Z",
    "process": {
      "pid": 1,
      "executable": "/usr/lib/systemd/systemd",
      "name": "systemd",
      "uid": 0,
      "capabilites": "3fffffffff",
      "cmd": "/sbin/init"
    },
    "syslog": {
      "identifier": "systemd",
      "priority": 6,
      "facility": 3
    },
    "docker": {
      "container": {
        "id": "a7e942190a47f3997ce8e6e70afaf454e035f6692e7bdd536bfab6f11262224b",
        "labels": {
          "org": {
            "label-schema": {
              "build-date": "20190305",
              "schema-version": "1.0",
              "name": "journalbeat",
              "license": "GPLv2",
              "vcs-ref": "1d55b4bd9dbf106a4ad4bc34fe9ee425d922363b",
              "vcs-url": "github.com/elastic/beats",
              "version": "6.7.1",
              "vendor": "Elastic",
              "url": "https://www.elastic.co/products/beats/journalbeat"
            }
          },
          "com": {
            "docker": {
              "compose": {
                "project": "log",
                "version": "1.24.0",
                "oneoff": "False",
                "config-hash": "5b98565d425a986b55aa1b95164247391612c2ab8c2b0bcd3b69cc882d1cce83",
                "container-number": "1",
                "service": "journalbeat"
              }
            }
          },
          "description": "Journalbeat ships systemd journal entries to Elasticsearch or Logstash.",
          "license": "Elastic License"
        },
        "image": "docker.elastic.co/beats/journalbeat:6.7.1",
        "name": "log_journalbeat_1"
      }
    },
    "host": {
      "id": "b52ee41f2ace4198adfe01a971521a0d",
      "ip": [
        "192.168.86.111",
        "fe80::2aaa:e66e:cab0:8353",
        "192.168.1.5",
        "172.18.0.1",
        "169.254.183.107",
        "fe80::42:2aff:fe23:9fb6",
        "172.19.0.1",
        "169.254.144.12",
        "fe80::1cbe:dfff:fe11:685b",
        "169.254.160.155",
        "fe80::4c49:51ff:fe59:faa2"
      ],
      "mac": [
        "38:d5:47:aa:c1:2a",
        "02:42:d5:1a:1e:e5",
        "02:42:2a:23:9f:b6",
        "02:42:7b:1c:68:ce",
        "1e:be:df:11:68:5b",
        "4e:49:51:59:fa:a2"
      ],
      "architecture": "x86_64",
      "os": {
        "version": "",
        "family": "",
        "name": "Arch Linux",
        "build": "rolling",
        "platform": "arch"
      },
      "containerized": true,
      "boot_id": "76232f86194c4353be9a3b46aee4e60b",
      "name": "puff"
    },
    "message": "var-lib-docker-containers-a34010a7c0ac153e46318ba05e865a7753a6a6523f939011f132b29cc7d021fe-mounts-shm.mount: Succeeded.",
    "custom": {
      "unit": "var-lib-docker-containers-a34010a7c0ac153e46318ba05e865a7753a6a6523f939011f132b29cc7d021fe-mounts-shm.mount",
      "message_id": "7ad2d189f7e94e70a38c781354912448",
      "invocation_id": "d3d87e303b21484db60bba05e2631595"
    }
  },
  "fields": {
    "@timestamp": [
      "2019-03-25T17:20:38.612Z"
    ]
  },
  "highlight": {
    "message": [
      "@kibana-highlighted-field@var@/kibana-highlighted-field@-@kibana-highlighted-field@lib@/kibana-highlighted-field@-@kibana-highlighted-field@docker@/kibana-highlighted-field@-@kibana-highlighted-field@containers@/kibana-highlighted-field@-@kibana-highlighted-field@a34010a7c0ac153e46318ba05e865a7753a6a6523f939011f132b29cc7d021fe@/kibana-highlighted-field@-@kibana-highlighted-field@mounts@/kibana-highlighted-field@-@kibana-highlighted-field@shm.mount@/kibana-highlighted-field@: @kibana-highlighted-field@Succeeded@/kibana-highlighted-field@."
    ]
  },
  "sort": [
    1553534438612
  ]
}
```

Example journal entry from a container:
```
{
        "_EXE" : "/usr/bin/dockerd",
        "CONTAINER_TAG" : "a7e942190a47",
        "_TRANSPORT" : "journal",
        "_MACHINE_ID" : "b52ee41f2ace4198adfe01a971521a0d",
        "_PID" : "7893",
        "_SYSTEMD_CGROUP" : "/system.slice/docker.service",
        "__CURSOR" : "s=9d5f42767d6641ed88fd402aed15dfca;i=c70ae1;b=a820b511fd2a434b87a5e27dda81ffb4;m=82fd8b26c;t=585e3b983439a;x=267490a0d8cf7a41",
        "_SYSTEMD_INVOCATION_ID" : "6e8c014e4f104ea5942dca15add5d9fb",
        "SYSLOG_IDENTIFIER" : "a7e942190a47",
        "_CAP_EFFECTIVE" : "3fffffffff",
        "MESSAGE" : "2019-04-06T22:00:00.010Z\tINFO\t[input]\tinput/input.go:133\tjournalbeat successfully published 50 events\t{\"id\": \"e5cc492d-ddd8->
        "CONTAINER_ID_FULL" : "a7e942190a47f3997ce8e6e70afaf454e035f6692e7bdd536bfab6f11262224b",
        "_BOOT_ID" : "a820b511fd2a434b87a5e27dda81ffb4",
        "_HOSTNAME" : "puff",
        "__REALTIME_TIMESTAMP" : "1554588000011162",
        "CONTAINER_NAME" : "log_journalbeat_1",
        "CONTAINER_ID" : "a7e942190a47",
        "__MONOTONIC_TIMESTAMP" : "35162468972",
        "_COMM" : "dockerd",
        "_SYSTEMD_UNIT" : "docker.service",
        "PRIORITY" : "3",
        "_UID" : "0",
        "_GID" : "0",
        "_SOURCE_REALTIME_TIMESTAMP" : "1554588000011115",
        "_CMDLINE" : "/usr/bin/dockerd -H fd:// --default-runtime=nvidia --node-generic-resource gpu=GPU-9cbe0570",
        "_SYSTEMD_SLICE" : "system.slice"
}
```

**Comment by exekias** [comment]
Thank you for your feedback @hholst80, could you please share the configuration you are using?

**Comment by hholst80** [comment]
journalbeat.yml

```
journalbeat.inputs:
- paths: []
  seek: cursor

processors:
- add_host_metadata:
    netinfo.enabled: true
- add_cloud_metadata: ~
- add_docker_metadata: ~

setup.kibana.host: 'http://localhost:5601'
setup.dashboards.enabled: true
setup.dashboards.retry.enabled: false

output.elasticsearch:
  hosts: ['localhost:9200']
```

deployed with docker-compose.yml

```
version: '2.4'
volumes: { esdata: {}, jbdata: {} }
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    restart: unless-stopped
    environment:
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
    volumes:
      - 'esdata:/usr/share/elasticsearch/data'
    network_mode: host
    logging:
      driver: json-file
  kibana:
    image: docker.elastic.co/kibana/kibana:6.7.1
    restart: unless-stopped
    volumes:
      - './kibana.yml:/usr/share/kibana/config/kibana.yml:ro'
    network_mode: host
    logging:
      driver: json-file
  journalbeat:
    image: docker.elastic.co/beats/journalbeat:6.7.1
    restart: unless-stopped
    # Skip permission checks on config since it is mounted from host
    command: '-e -strict.perms=false'
    user: root
    volumes:
      - './journalbeat.yml:/usr/share/journalbeat/journalbeat.yml:ro'
      - '/var/log/journal:/var/log/journal:ro'
      - '/etc/machine-id:/etc/machine-id:ro'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/etc/os-release:/etc/os-release:ro'
    logging:
      driver: json-file
```
