### ISSUE TITLE
[Docs] Metricbeat Redis Key metricset example incorrectly references name field.

### ISSUE THREAD

**Issue by ajoliveira** [elastic/beats#11733]
For confirmed bugs, please report:
- Version: 6.7+
- Operating System: N/A
- Documentation link: https://www.elastic.co/guide/en/beats/metricbeat/6.7/metricbeat-metricset-redis-key.html

Documentation correctly notes that `pattern` is the required field under `keys.patterns` but the example provided incorrectly shows `names` which results in failure similar to:

Exiting: 1 error: 1 error: failed to read configuration for 'key' metricset: missing required field accessing '0.key.patterns.0.pattern' (source:'/.../modules.d/redis.yml')

Example should be updated to:
```
- module: redis
  metricsets: ['key']
  key.patterns:
    - pattern: 'pipeline-*'
      limit: 20
```
