### ISSUE TITLE
Heartbeat exits when autodiscover fields are used for id

### ISSUE THREAD

**Issue by gingerwizard** [elastic/beats#11747]
- Version: 7.0.0-SNAPSHOT
- Operating System: Docker image

The following config causes a segmentation fault:

```
    heartbeat.monitors:
    - type: icmp
      schedule: '*/10 * * * * * *'
      hosts: ["github.com","elastic.co","bbc.com","demo.elastic.co"]
    - type: http
      schedule: '@every 10s'
      urls: ["https://github.com","https://www.bbc.com","https://www.elastic.co","https://demo.elastic.co/status"]
      check.response.status: 200
    heartbeat.autodiscover:
      providers:
        - type: kubernetes
          templates:
            - condition.equals:
                kubernetes.labels.heartbeat_type: http
              config:
                - type: http
                  urls: ["http://${data.host}:${data.kubernetes.labels.heartbeat_port}/${data.kubernetes.labels.heartbeat_url}"]
                  id: "${data.kubernetes.pod.name}"
                  check.response.status: 200
                  schedule: "@every 1s"
                  timeout: 2s
            - condition.equals:
                kubernetes.labels.heartbeat_type: tcp
              config:
                - type: tcp
                  hosts: ["${data.host}:${data.kubernetes.labels.heartbeat_port}"]
                  schedule: "@every 1s"
                  timeout: 2s
    name: heartbeat-infra
    setup.dashboards.enabled: false
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_PROTO}://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}']
      username: ${ELASTICSEARCH_USERNAME}
      password: ${ELASTICSEARCH_PASSWORD}
    processors:
      - add_cloud_metadata:
      - add_docker_metadata:
      - add_host_metadata:
    xpack.monitoring.enabled: true

```

It appears the line:

`id: "${data.kubernetes.pod.name}"`

is responsible here. Removing this and the http services are correct pinged.
