### ISSUE TITLE
Journalbeat 7.0.0 setup dashboard

### ISSUE THREAD

**Issue by hholst80** [elastic/beats#11751]
Elasticsearch & Kibana 7.0.0 deployment with Journalbeat.

```
version: '2.4'
volumes: { esdata: {}, kbdata: {} }
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0
    restart: unless-stopped
    environment:
      - 'ES_JAVA_OPTS=-Xms512m -Xmx512m'
      - 'discovery.type=single-node'
    volumes:
      - 'esdata:/usr/share/elasticsearch/data'
    network_mode: host
    logging:
      driver: json-file
  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0
    restart: unless-stopped
    volumes:
      - 'kbdata:/usr/share/kibana/data'
    environment:
    - SERVER_NAME=puff
    - ELASTICSEARCH_HOSTS=http://localhost:9200/
    network_mode: host
    logging:
      driver: json-file
```

```
docker run --net="host" docker.elastic.co/beats/journalbeat:7.0.0 setup --dashboards
```
![image](https://user-images.githubusercontent.com/6200749/55911174-5b0ea880-5be0-11e9-9ca5-887a97cf1a75.png)
