### ISSUE TITLE
Support network monitoring in Kubernetes with Canal (Calico + flannel)

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#11837]
Usually network monitoring in Kubernetes can be done by using the docker network metricset, that uses the docker stats API to collect this information.

It seems that with some network configurations docker stats always report zero network metrics, we should find other ways to collect this information for this environment.

It was reported with a bare-metal deployment using Canal: https://discuss.elastic.co/t/docker-network-at-kubernetes/165203/16

Related:
* [Write-up on traffic shaping with Calico](https://github.com/projectcalico/calico/issues/797#issuecomment-493210584)

**Comment by eedugon** [comment]
quick question around this @jsoriano... does it make sense to use the `docker` module in the daemonset if for example the following modules are configured? (from Elastic default manifest)

```
   - module: system
      period: 10s
      metricsets:
        - cpu
        - load
        - memory
        - network
        - process
        - process_summary
        #- core
        #- diskio
        #- socket
```

and:
```
   - module: kubernetes
      metricsets:
        - node
        - system
        - pod
        - container
```

As far as I know, the `system.module` and `kubernetes.*` metricsets are going to provide a lot of networking metrics (at system/node level and at pod / container level).

What benefit or extra information would be added by the `docker.network` metricset in a Kubernetes environment? And if it's really useful... should we add it to the default proposal?
