### ISSUE TITLE
[Filebeat] The field "agent.type" has disappeared when I use the autodiscover feature

### ISSUE THREAD

**Issue by mguggi** [elastic/beats#11838]
I've changed our config from filebeat.input to filebeat.autodiscover and now the field "agent.type" is gone. 

We use the docker image of filebeat in the Version 6.7.1. Our config looks like this:

```yaml
filebeat.autodiscover:
  providers:
    - type: kubernetes
       templates:
         - config:
             - type: docker
                ingore_older: 10m
                tail_files: true
                containers.ids:
                  - "${data.kubernetes.container.id}"
```

The output containts no nested object "agent" .

Before this change we used the following config:  

```yaml
filebeat.inputs:
    - type: docker
      containers.ids:
        - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
        - drop_event:
            when:
              equals:
                kubernetes.container.name: "filebeat"
      tail_files: true
```

With the old configuration we saw the nested object "agent" in the output.

```json
    "agent": {
      "type": "filebeat"
    },
```
 

Is this an expected behaviour or a bug?  I know I can set a custom field for input, but I don't want to duplicate fields unnecessarily.
