### ISSUE TITLE
[Metricbeat]System/process metricset - WmiPrvSE.exe seems to utilize more CPU on  v 7.0.0

### ISSUE THREAD

**Issue by narph** [elastic/beats#11840]
- Version: Compared Metricbeat 6.7.1 with 7.0.0
- Operating System: Windows Server 2016
- Steps to Reproduce: 
Enabled only the system process metricset:
```
- module: system
  period: 10s
  metricsets:
    #- cpu
    #- load
    #- memory
    #- network
    - process
    #- process_summary
    #- socket_summary
    #- core
    #- diskio
    #- socket
  enabled: true
  processes: ['.*']
  ```
When running Metricbeat v6.7.1 we see the following in the Performance Monitor tool:

![671](https://user-images.githubusercontent.com/1900090/56218975-3c883180-6066-11e9-999a-5097e0082a6e.PNG)

![6711](https://user-images.githubusercontent.com/1900090/56219004-4447d600-6066-11e9-9b2e-80afe53dcc93.PNG)

When running with the  v 7.0.0:
![700](https://user-images.githubusercontent.com/1900090/56218992-401bb880-6066-11e9-8c5e-67bbcaef80e3.PNG)

![7001](https://user-images.githubusercontent.com/1900090/56219009-4742c680-6066-11e9-9693-d23c9a2ad6fc.PNG)

We notice the WMI provider host process is using more CPU when running Metricbeat v 7.0.0 than while running earlier versions of Metricbeat
