### ISSUE TITLE
Multi-Line Patterns avoided when using configs vs prospects in filebeat.yml 

### ISSUE THREAD

**Issue by waynetaylor** [elastic/beats#11863]
Per my report in discussion forums it appears that any multi-line pattern added in the main filebeat.yml file is ignored when using filebeat.configs.inputs vs prospects. 

e.g. the following multi-line pattern was in the filebeat.yml file:
```
multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
multiline.negate: true
multiline.match: after
```
When filebeat was started I had observed log lines such as stack traces format over multiple messages instead of one larger block message. It was only when I moved the multi-line configuration outside of the main configuration did the multi-line messages get handled correctly.  e.g. when one of my configs looks like this:

```
- type: log
  paths:
    - /opt/tomcat/logs/*.log
    - /opt/tomcat/logs/*.gc*
    - /opt/tomcat/logs/*.out
  scan_frequency: 10s
  exclude_files:
    - '^/opt/tomcat/logs/*json*.log'
  tags: ["tomcat"]
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
```

- Version: Observed in any version from 6.3.2 and above
- Operating System: Mac OS 10.13.6 (17G6030)
- Discuss Forum URL: https://discuss.elastic.co/t/solved-multi-line-help/175741
- Steps to Reproduce: See above
