### ISSUE TITLE
[Winlogbeat] Workaround to have more than 22 event ids seems to be broken in 7.0.0 - drop_event.when.not.or not working as expected

### ISSUE THREAD

**Issue by ismael-hasan** [elastic/beats#11916]
**Version**: 7.0.0 

**Operating System**: Windows 10 and Windows Server 2016 

**Description**: 
There is a documented workaround for when we want to have more than 22 event ids in a single `name` - https://www.elastic.co/guide/en/beats/winlogbeat/current/configuration-winlogbeat-options.html#_literal_event_logs_event_id_literal . The workaround is based on setting them in the processors section: 
```
winlogbeat.event_logs:
  - name: Security
    event_id: ...
    processors:
      - drop_event.when.not.or:
        - equals.event_id: 903
        - equals.event_id: 1024
        - equals.event_id: 4624
```

It works in `6.7.1`, it does not work in `7.0.0`.

I am not sure if this is something related to Winlogbeat, or in general to some change in processors.

**Steps to Reproduce**: 
Choose a common event id, `4624`

Using the normal approach works fine in both `6.7` and `7.0` : 
```
  event_logs:
    - name: Security
      ignore_older: 168h
      tags: sometag
      event_id: 4624
```

Changing it to the processors approach, it works in `6.7` but it does not work in `7.0`
```
    - name: Security
      ignore_older: 168h
      tags: sometag
      processors:
        - drop_event.when.not.or:
          - equals.event_id: 4624
```

In this last option, in `7.0` no events are sent to the output. 

It follows a full configuration to reproduce it, sending events to a file: 
```
winlogbeat:
  registry_file: C:/tmp/.winlogbeat.yml221
  shutdown_timeout: '0'
  event_logs:
    - name: Security
      ignore_older: 168h
      tags: sometag
      processors:
        - drop_event.when.not.or:
          - equals.event_id: 4624
          
setup.template.settings:
  index.number_of_shards: 3
  
setup.kibana:

#output.console:
#  pretty: true
output.file:
  path: "C:/tmp"
  filename: winlogbeat7.output
  
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
```

**Comment by urso** [comment]
Documentation id outdated. Depending on data source the new fields are `event.code` or `winlog.event_id`. See: https://www.elastic.co/guide/en/beats/winlogbeat/current/exported-fields-winlog.html

**Comment by magnuslarsen** [comment]
Can confirm that this works :+1: 
```
processors:
  - drop_event.when.not.or:
  - equals.winlog.event_id: 550
  ....
```
