### ISSUE TITLE
Dropping event: no topic could be selected

### ISSUE THREAD

**Issue by icoolchn** [elastic/beats#11988]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version:  kubernetes docker image : filebeat-oss:6.5.0  logstash-oss:6.5.0  cp-kafka:4.0.1-1
- Operating System:  Centos 7  kubernetes v1.12.5
- Discuss Forum URL:
- Steps to Reproduce: 

filebeat chart deploy ，autodiscover kubernetes log . find ERROR:   kafka/client.go:131     Dropping event: no topic could be selected

filebeat.yml：
 ```
    fields:
      kubernetes.cluster.name: testcluster
    fields_under_root: true
    filebeat.autodiscover:
      providers:
      - hints.enabled: true
        templates:
        - condition.and:
          - not.has_fields:
            - kubernetes.labels.log-index
          - not.equals.kubernetes.container.name: filebeat
          config:
          - containers.ids:
            - ${data.kubernetes.container.id}
            exclude_lines:
            - ^\s+[\-`('.|_]
            fields:
              log_topic: testcluster-${data.kubernetes.namespace}
            type: docker
        type: kubernetes
    filebeat.config:
      inputs:
        path: ${path.config}/inputs.d/*.yml
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    http.enabled: true
    http.port: 5066
    output.kafka:
      compression: gzip
      hosts:
      - kafka.testcluster.com:31090
      - kafka.testcluster.com:31091
      - kafka.testcluster.com:31092
      max_message_bytes: 1000000
      partition.round_robin: null
      reachable_only: false
      required_acks: 1
      topic: '%{[fields.log_topic]}'
    processors:
    - add_cloud_metadata: null
```
