### ISSUE TITLE
Filebeat does not preserve `log.level` field of the event

### ISSUE THREAD

**Issue by flexoid** [elastic/beats#12040]
After switching to Elastic Cloud 7 we changed our logging schema to conform to Elastic Common Schema. Specifically, the original log level from the application goes to `log.level` instead of `level` (according to https://www.elastic.co/guide/en/ecs/current/ecs-log.html).

But looks like Filebeat completely replaces `log` object with the following and doesn't leave `log.level`.

```
log.file.path
log.offset
```

- Version: filebeat 7.0.1, elastic cloud 7.0.1
- Operating System: debian stretch
- Steps to Reproduce: 
  1. Log event with `log.level`, e.g. 
    ```json
    { 
      "log":  { 
        "level": "DEBUG" 
      }
    }
    ```
  2. Find this document in ES - no `log.level` inside.
  ```json
    { 
      "log":  { 
        "offset": 123456,
        "file": {
          "path": "/home/some/path.log"
        } 
      }
    }
    ```

**Comment by ruflin** [comment]
As we have here a "DeepUpdate" I would not expect this to happen: https://github.com/elastic/beats/blob/master/filebeat/input/log/harvester.go#L319 

@flexoid Could you share your Filebeat config and an example log line?

**Comment by flexoid** [comment]
@ruflin 
Just reproduced on simplified config:

```yml
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

cloud.id: ***
cloud.auth: ***

filebeat.inputs:
- type: log
  enabled: true
  paths:
    - "/tmp/logs/*"
  fields_under_root: true
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: message
  json.ignore_decoding_error: true

setup.ilm.enabled: false

output.elasticsearch:
  enabled: true

logging.level: debug
```

Example log line:
```shell
echo '{"message":"hello elk","log":{"level": "debug"}}' >> /tmp/logs/test.log
```

Here is the part of filebeat log:

```json
2019-05-04T11:38:25.007+0300	DEBUG	[processors]	processing/processors.go:183	Publish event: {
  "@timestamp": "2019-05-04T08:38:25.007Z",
  "@metadata": {
    "beat": "",
    "type": "_doc",
    "version": ""
  },
  "host": {
    "name": "***.local",
    "id": "E58FEE39-67C8-5276-816E-C56687B535EF",
    "hostname": "***.local",
    "architecture": "x86_64",
    "os": {
      "name": "Mac OS X",
      "kernel": "18.5.0",
      "build": "18E226",
      "platform": "Darwin",
      "version": "10.14.4",
      "family": "darwin"
    }
  },
  "agent": {
    "hostname": "***.local",
    "id": "89e0661e-3ed5-4a99-8f73-7056d637db33",
    "version": "7.0.1",
    "type": "filebeat",
    "ephemeral_id": "5f117ff0-881e-4abd-bb12-1c43b7a6b800"
  },
  "log": {
    "offset": 0,
    "file": {
      "path": "/tmp/logs/test.log"
    }
  },
  "message": "hello elk",
  "input": {
    "type": "log"
  },
  "ecs": {
    "version": "1.0.0"
  }
}
```
