### ISSUE TITLE
failed to unmarshal jolokia JSON response

### ISSUE THREAD

**Issue by javierdompablo** [elastic/beats#12070]
Jolokia module fails to parse some responses fetched using the GET method with the error:

```
failed to unmarshal jolokia JSON response '{"request":{"mbean":"java.lang:type=OperatingSystem","attribute":"ProcessCpuLoad","type":"read"},"value":2.519526329050139E-4,"timestamp":1557157281,"status":200}': json: cannot unmarshal number into Go struct field Entry.Value of type map[string]interface {}
```

For confirmed bugs, please report:

Version: >= 6.6.2 (only seems to affect GET method)

Steps to Reproduce:
Use this config with the jolokia module:
```
http_method: 'GET'
jmx.mappings:
  - mbean: 'java.lang:type=OperatingSystem'
    attributes:
    - attr: ProcessCpuLoad
      field: jvm.process.cpu.load
```
