### ISSUE TITLE
Multiline JSON filebeat support

### ISSUE THREAD

**Issue by devinrsmith** [elastic/beats#1208]
(Copying my comment from #1143) 

I see in #1069 there are some comments about it.

IMO a new `input_type` is the best course of action.

I think one of the primary use cases for logs are that they are human readable. The first thing I usually do when an issue arrises is to open up a console and scroll through the log(s). Filebeats provides `multiline` support, but it's got to be configured on a log by log basis.

Using pretty printed JSON objects as log "lines" is nice because they are human readable.

Limiting the input to single line JSON objects limits the human usefulness of the log.

For example, here is a real-ish log line that I just grabbed:

```
{
    "primaryType": "ACTION",
    "diagnosticType": "com.example.server.endpoints.MyEndpoint",
    "requestTimestamp": "2016-03-22T20:18:25.281Z",
    "path": "actions/FD0IjHbzKoAkCz_NHr9bB___/messages",
    "method": "POST",
    "queryParams": {},
    "requestHeaders": {
        "Accept": [
            "application/json"
        ],
        "X-Forwarded-Proto": [
            "https",
            "https"
        ],
        "User-Agent": [
            "MyApp Debug/15 (iPhone; iOS 9.2.1; Scale/2.00)"
        ],
        "Host": [
            "v3-test.example.com",
            "v3-test.example.com"
        ],
        "Accept-Language": [
            "en-CA;q=1"
        ],
        "Content-Length": [
            "17"
        ],
        "Content-Type": [
            "application/json; charset=UTF-8"
        ]
    },
    "userId": "FDxnF4enX8EV1mIxwujCSv__",
    "profileId": "FDxnF4ezX8DV1mIxwujCS___",
    "actions": [],
    "responseTimestamp": "2016-03-22T20:18:25.287Z",
    "status": 204,
    "responseHeaders": {}
}
```

vs

```
{"primaryType":"ACTION","diagnosticType":"com.example.server.endpoints.MyEndpoint","requestTimestamp":"2016-03-22T20:18:25.281Z","path":"actions/FD0IjHbzKoAkCz_NHr9bB___/messages","method":"POST","queryParams":{},"requestHeaders":{"Accept":["application/json"],"X-Forwarded-Proto":["https","https"],"User-Agent":["MyApp Debug/15 (iPhone; iOS 9.2.1; Scale/2.00)"],"Host":["v3-test.example.com","v3-test.example.com"],"Accept-Language":["en-CA;q=1"],"Content-Length":["17"],"Content-Type":["application/json; charset=UTF-8"]},"userId":"FDxnF4enX8EV1mIxwujCSv__","profileId":"FDxnF4ezX8DV1mIxwujCS___","actions":[],"responseTimestamp":"2016-03-22T20:18:25.287Z","status": 204,"responseHeaders":{}}
```

The pretty printed JSON is much more human readable than the single line format :)

**Comment by tsg** [comment]
Thanks for creating this as an enhancement request. We'll monitor the interest on this.

**Comment by McStork** [comment]
+1

**Comment by rohitshrivastava04** [comment]
+1

**Comment by tutukar** [comment]
+1

**Comment by toddbfz** [comment]
+1

**Comment by intsco** [comment]
+1

**Comment by netanel246** [comment]
+1

**Comment by cherkovskiyandrey** [comment]
+1

**Comment by PhaedrusTheGreek** [comment]
+1 adding a new input type for JSON.

I'm getting errors all over the place trying to do JSON processing on multiline data.

```
  "json": {
    "json_error": "Error decoding JSON: invalid character '}' looking for beginning of value",
    "message": "{ \n \"key\": \"another thing\"\n}"
  },
```

**Comment by andrewkroh** [comment]
With 5.2.0 you should be able to process multiline JSON using the mutliline feature followed by the [`decode_json_fields`](https://www.elastic.co/guide/en/beats/filebeat/master/decode-json-fields.html) processor. You need 5.2.0 because it supports the `target` config option. For example:

```
filebeat.prospectors:
- paths:
    - input.json
  multiline.pattern: '^{'
  multiline.negate: true
  multiline.match:  after

processors:
- decode_json_fields:
    fields: ['message']
    target: json

output.console.pretty: true
```

**Comment by bfgoodrich** [comment]
This doesn't fix multiline JSON issues if keys are not nested under "source" or "message"

**Comment by tomrade** [comment]
does this only apply globally with the processor? not at prospector level?

**Comment by andrewkroh** [comment]
As configured in my example above the processor would apply globally. So if you wanted to limit it to a single file you could use a conditional.

```
processors:
- decode_json_fields:
    fields: ['message']
    target: json
    when.regexp.source: 'input.json$'
```

If you are using 6.0 you can specify the processor local to the prospector. This will be better from a CPU standpoint because it does not get applied to all events and does not require a conditional.

```
filebeat.prospectors:
- paths:
    - input.json
  multiline.pattern: '^{'
  multiline.negate: true
  multiline.match:  after
  processors:
  - decode_json_fields:
      fields: ['message']
      target: json

```

**Comment by dtungbmw** [comment]
Hi, 
I use 6.0+ and set exactly the same configuration to read json file. All I need is to be able to read as json file and forward to kafka. I found the above config by @andrewkroh works for some of my json, it misses last line for some other json files. It seems to do with new line in the end of file. Any workaround?
Thanks

**Comment by jakommo** [comment]
Still working in 7.x, syntax change a little though. 
Here is an updated example for anyone interested:
```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /path/to/file.json
  multiline.pattern: '^{'
  multiline.negate: true 
  multiline.match: after
  processors:
  - decode_json_fields:
      fields: ["message"]
      target: "json"
```

**Comment by woniuzhang** [comment]
> Still working in 7.x, syntax change a little though.
> Here is an updated example for anyone interested:
> 
> ```
> filebeat.inputs:
> - type: log
>   enabled: true
>   paths:
>     - /path/to/file.json
>   multiline.pattern: '^{'
>   multiline.negate: true 
>   multiline.match: after
>   processors:
>   - decode_json_fields:
>       fields: ["message"]
>       target: "json"
> ```

thanks, it works.
But when multiple rows are merged, JSON is no longer available

**Comment by Kosmonafft** [comment]
> Still working in 7.x, syntax change a little though. Here is an updated example for anyone interested:
> 
> ```
> filebeat.inputs:
> - type: log
>   enabled: true
>   paths:
>     - /path/to/file.json
>   multiline.pattern: '^{'
>   multiline.negate: true 
>   multiline.match: after
>   processors:
>   - decode_json_fields:
>       fields: ["message"]
>       target: "json"
> ```

This solution does not work (anymore?), because of this error:

`When using the JSON decoder and multiline together, you need to specify a message_key value accessing config`

Not sure what this "`message_key`" should be ....

**Comment by andrewkroh** [comment]
Are you sure that's exactly the config you are using? `message_key` is only involved if you're using the `json` options in the input (see https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#filebeat-input-log-config-json). That error should not come into play when using only `decode_json_fields` with the log input as quoted above. If it is then something broke (what version).

**Comment by Kosmonafft** [comment]
> Are you sure that's exactly the config you are using? `message_key` is only involved if you're using the `json` options in the input (see https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#filebeat-input-log-config-json). That error should not come into play when using only `decode_json_fields` with the log input as quoted above. If it is then something broke (what version).

I am trying to use [hints based autodiscover](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html#configuration-autodiscover-hints) for filebeat, which is collecting logs in my kubernetes cluster.

These are my annotations:

```
podAnnotations:
  co.elastic.logs/multiline.pattern: '^{'
  co.elastic.logs/multiline.negate: true
  co.elastic.logs/multiline.match: after
  co.elastic.logs/processors.decode_json_fields.fields: ["message"]
  co.elastic.logs/processors.decode_json_fields.target: "json"
  co.elastic.logs/processors.decode_json_fields.add_error_key: true
  co.elastic.logs/processors.decode_json_fields.overwrite_keys: true
```
This is an example log line (coming from an elastic pod btw.), which I aim to have as one single document in elasticsearch:

```
{"type": "server", "timestamp": "2022-01-25T17:32:55,967Z", "level": "WARN", "component": "r.suppressed", "cluster.name": "elasticsearch", "node.name": "elasticsearch-master-0", "message": "path: /_cluster/health, params: {wait_for_status=green, timeout=1s}", 
"stacktrace": ["org.elasticsearch.discovery.MasterNotDiscoveredException: null",
"at org.elasticsearch.action.support.master.TransportMasterNodeAction$AsyncSingleAction$2.onTimeout(TransportMasterNodeAction.java:297) [elasticsearch-7.16.2.jar:7.16.2]",
"at org.elasticsearch.cluster.ClusterStateObserver$ContextPreservingListener.onTimeout(ClusterStateObserver.java:345) [elasticsearch-7.16.2.jar:7.16.2]",
"at org.elasticsearch.cluster.ClusterStateObserver$ObserverClusterStateListener.onTimeout(ClusterStateObserver.java:263) [elasticsearch-7.16.2.jar:7.16.2]",
"at org.elasticsearch.cluster.service.ClusterApplierService$NotifyTimeout.run(ClusterApplierService.java:660) [elasticsearch-7.16.2.jar:7.16.2]",
"at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:718) [elasticsearch-7.16.2.jar:7.16.2]",
"at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]",
"at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]",
"at java.lang.Thread.run(Thread.java:833) [?:?]"] }
```

After applying the above mentioned annotations my filebeat pod reports:

```
won't start runner: When using the JSON decoder and multiline together, you need to specify a message_key value accessing config
2022-01-25T17:31:01.532Z	ERROR	[autodiscover]	autodiscover/autodiscover.go:235	Auto discover config check failed for config '{
  "docker-json": {...},
  "multiline": {
    "match": "after",
    "negate": "true",
    "pattern": "^{"
  },
  "processors": [
    {
      "decode_json_fields": {
        "add_error_key": "true",
        "fields": "[message]",
        "overwrite_keys": "true",
        "target": "json"
      }
    }
  ],
...
```
