### ISSUE TITLE
Winlogbeat and sysmon

### ISSUE THREAD

**Issue by Sinagot** [elastic/beats#12196]
Hi all !

I have a Windows Event Collector installed on my network, which gathers event logs from computers running sysmon (all Win2012R2). Forwarded events are "Security", "System", "Applications" and "Sysmon". Next, these logs are forwarded from the WEC to a Graylog server using Winlogbeat 6.4.1. Here is the Winlogbeat conf file : 
```
winlogbeat:
  event_logs:
  - name: System
  - name: ForwardedEvents
  forwarded: false
  include_xml: true
```
The issue is : Sysmon logs (and only these ones) are displayed with a "null" message field in Graylog. WEC is configured with "RenderedText" option, so I have no other solutions...

Maybe I'm missing something.
