### ISSUE TITLE
Filebeat: variables not expanded in rollover_alias

### ISSUE THREAD

**Issue by fpompermaier** [elastic/beats#12233]
- Version: Filebeat 7.0.1 and 7.1.0
- Operating System: Ubuntu 18.04 LTS

From [documentation](https://www.elastic.co/guide/en/beats/filebeat/master/ilm.html#setup-ilm-rollover_alias-option) rollover_alias is by default filebeat-{agent.version} but if I set

setup.ilm.enabled: true
setup.ilm.rollover_alias: "filebeat-**{agent.version}**"
setup.ilm.pattern: "{now/d}-000001"

the index name is not the expected one (i.e. **filebeat-7.1.0-2019.05.21-000001**) but the index is created with name **filebeat-{agent.version}**.

Is it a problem of the documentation or is it a bug?

**Comment by exekias** [comment]
I'm guessing a `$` is missing? perhaps something like this could work?:
```
setup.ilm.rollover_alias: "filebeat-${agent.version}"
```

pinging @simitt @urso

**Comment by simitt** [comment]
Agree, that the `$` is missing.

**Comment by fpompermaier** [comment]
If I do that I get the following error when starting the filebeat:

Exiting: missing field accessing 'setup.ilm.rollover_alias' (source:'filebeat.yml')

**Comment by simitt** [comment]
I can confirm there is a bug. Beats exit with an error on startup or when trying to run the `setup` cmd whenever `setup.ilm.rollover_alias`  is configured to include variables to expand. 

As a workaround, @fpompermaier could you specify the version in the configuration until this is fixed?

**Comment by fpompermaier** [comment]
Fortunately commenting out setup.ilm.rollover_alias just works for me (I was going to use filebeat-{agent.version} anyway) so there's no problem right now in my setup.

**Comment by simitt** [comment]
Update: the configuration would actually be `%{[agent.version]}`. The issue we saw was due to the `$` sign. 
Nevertheless, according to the [docs](https://www.elastic.co/guide/en/beats/filebeat/master/ilm.html#setup-ilm-rollover_alias-option) adding an `agent.version` should not be necessary: 

> The index lifecycle write alias name. The default is filebeat-{agent.version}. Setting this option changes the prefix in the alias name. It doesn’t remove agent.version from the alias name.

I would assume that independent of the config for `setup.ilm.rollover_alias` the alias always gets prefixed with the beat version. This is not the case (since 7.0.0) for custom config, which is indeed a bug (but a different one than originally expected).

**Comment by simitt** [comment]
@ph when working on this, you could modify the [existing system test](https://github.com/elastic/beats/blob/master/libbeat/tests/system/test_cmd_setup_index_management.py#L134) to pass in an alias without the version and check that an alias with the version is created.

**Comment by ph** [comment]
There are actually two distinct problem here, the rolloverAlias doesn't support the fieldref syntax, but to be constant with the documentation, I've decided to automatically appends the version, I did not make the rolloverAlias accepts a fieldref.

**Comment by gboddin** [comment]
I've been changing the index names depending on the log source for a long time, it became a natural feature to have filebeat handle multiple log sources to different indices.

Beat was never used to create the templates, rather, we have a separate CI process to maintain pipelines and templates ( and now ILM ). 

With ILM enabled in beat there's no more way to do it and you have to spawn 1 filebeat per indices you need to populate. Not ideal at all.

This 
```
filebeat.inputs:
- type: log
  paths: ["/logs/internal/[0-9]*.log"]
  json.message_key: message
  json.keys_under_root: true
  json.overwrite_keys: true
  fields:
    hostname: ${HOSTNAME}
    location: ${LOCATION}
    log_index: applog-internal
- type: log
  paths: ["/logs/external/[0-9]*.log"]
  json.message_key: message
  json.keys_under_root: true
  json.overwrite_keys: true
  fields:
    hostname: ${HOSTNAME}
    location: ${LOCATION}
    log_index: applog-external

output.elasticsearch:
  hosts: ["http://es-ingest001:9200", "http://es-ingest002:9200"]

processors:
  - rename:
      fields:
        - from: "@timestamp"
          to: "received"
        - from: "timestamp"
          to: "@timestamp"
      ignore_missing: false
      fail_on_error: true

setup.template.enabled: false
setup.ilm.enabled: true
setup.ilm.rollover_alias: "{fields.log_index}"
setup.ilm.pattern: "{now/d}-000001"
```

Is not working anymore ( using index_name worked before ).

Did I miss something ?
