### ISSUE TITLE
output.elasticsearch.indices matching not working in 7.0.1

### ISSUE THREAD

**Issue by pa-jberanek** [elastic/beats#12258]
See https://discuss.elastic.co/t/output-elasticsearch-indices-matching-not-working-in-7-0-1/

Just upgraded from Elastic Stack 6.7.1 to 7.0.1 and filebeat configuration I had to dynamically change the index name appears to have stopped working.

My simple config:

```
setup.ilm.enabled: false

filebeat.inputs:
- type: log
  paths:
    - /syslogs/f5.log
  pipeline: f5-requestlog-pipeline
  fields:
    service: f5-requestlogs

output.elasticsearch:
  indices:
    - default: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"
    - index: "filebeat-14day-%{[beat.version]}-%{+yyyy.MM.dd}"
      when.equals:
        fields.service: "f5-requestlogs"

```
Data is being put in filebeat-7.0.1-2019.05.23 rather than the expected filebeat-14day-7.0.1-2019.05.23

- Version: filebeat-7.0.1-1.x86_64
- Operating System: CentOS 7.6
