### ISSUE TITLE
Fix misleading message when protocol is not set

### ISSUE THREAD

**Issue by dadoonet** [elastic/beats#12304]
In 7.1.0, when configuring a monitor like this:

```
heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - 'elasticsearch:9200'
```

It fails with this error message:

```
2019-05-27T10:52:35.556Z	ERROR	instance/beat.go:802	Exiting: could not create monitor: job err missing port in address
Exiting: could not create monitor: job err missing port in address
```

I found it misleading as the port is there obviously. Actually the problem is coming from the protocol which is missing. It should have been:

```
heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - 'http://elasticsearch:9200'
```
