### ISSUE TITLE
Filebeat autodiscover hints fail to create inputs

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#12346]
Filebeat autodiscover hints don't create valid inputs on 7.2 branch, possibly related to #12162 and/or #12272.

For confirmed bugs, please report:
- Version: 7.2 branch
- Operating System: Linux
- Steps to Reproduce: Use filebeat with hints-based autodiscover

This error appears continuously in filebeat log:
```
2019-05-29T15:40:46.071Z	ERROR	[autodiscover]	cfgfile/list.go:96	Error creating runner from config: each input must have at least one path defined
```

Tested configuration:
```
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
```

There is a workaround with the new possibility of adding a different default config (#12272), this works:
```
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - /var/log/containers/*${data.container.id}.log
```
