### ISSUE TITLE
rabbitmq.yml.disabled in filebeat has all lines commented out 

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#12347]
I'm not sure if this is a bug or enhancement or this is the new/correct way to add *.yml.disabled file. 
Unlike other modules in filebeat or metricbeat, rabbitmq in filebeat has the default yml config file all commented out. 
```
# Module: rabbitmq
# Docs: https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-module-rabbitmq.html

 #- module: rabbitmq
  # All logs
  #log:
    #enabled: true

     # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths: ["/var/log/rabbitmq/rabbit@localhost.log*"]

     # Convert the timestamp to UTC. Requires Elasticsearch >= 6.1.
    #var.convert_timezone: false
```

In this case, when I was testing rabbitmq module, I ran `./filebeat modules enable rabbitmq` and then started filebeat. But no filebeat data was collected. I went back to check `rabbitmq.yml` under `modules.d` and realized all the lines in this file are commented out. After removing `#` from rabbitmq.yml file, everything works fine.

By looking at other filebeat/metricbeat module's config file, I think `rabbitmq.yml.disabled` should look like:
```
# Module: rabbitmq
# Docs: https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-module-rabbitmq.html

 - module: rabbitmq
  # All logs
  log:
    enabled: true

     # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths: ["/var/log/rabbitmq/rabbit@localhost.log*"]

     # Convert the timestamp to UTC. Requires Elasticsearch >= 6.1.
    #var.convert_timezone: false
```
