### ISSUE TITLE
Specify index in module / input

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#12421]
Today in Beats the elasticsearch index can be specified through patterns like described [here](https://www.elastic.co/guide/en/beats/metricbeat/current/elasticsearch-output.html#index-option-es): 

```
output.elasticsearch:
  hosts: ["http://localhost:9200"]
  index: "%{[fields.log_type]}-%{[agent.version]}-%{+yyyy.MM.dd}"
```

This requires that the above fields exist in each event. Instead I suggest that the index and input should send data to can be directly specified in the module or input:

```
filebeat.inputs:
- type: log
  paths:
    - /var/log/*.log
  index: my-logs-index
```

or in Metricbeat:

```
metricbeat.modules:
- module: apache
  hosts: ["http://127.0.0.1"]
  index: apache-index
```

Having the index specified per input / module would overwrite the default index setting specified at the Elasticsearch output.

Users using the above would have to ensure that the index templates etc. still apply to the indices they specify.
