### ISSUE TITLE
Filebeat with AWS, Azure and Google

### ISSUE THREAD

**Issue by Nimdy** [elastic/beats#12493]
I've tested filebeat on AWS, Azure and Google for piping Suricata logs to ELK from network shares.  I still receive "File was truncated. Begin reading file from offset 0".  

Each setup has Suricata jsons are rotating every 6 hours and the filebeat.yml is the following:

```
filebeat:

prospectors:

    - type: log
      paths:
       - /mnt/log/*.json

output:
  logstash:
    hosts:
    - 10.1.0.6:5044
```

What can I do to prevent the truncation errors?  It is painful to see 5-10 duplicated entries and missing possible data logging. 

Maybe different filebeat configurations to help? 

Thank you in advance.
