### ISSUE TITLE
Error when ES output and Monitoring use separate certs for PKI auth

### ISSUE THREAD

**Issue by kostasb** [elastic/beats#12559]
**Beats version**: v7.1.1 (possibly affects earlier versions as well)
**Affected components**: `output.elasticsearch` , `xpack.monitoring.elasticsearch`

**Description**:
When using PKI authentication between Beats and Elasticsearch, it isn't possible to configure different certificates for the Elasticsearch output and X-Pack monitoring.

Since the PKI realm extracts the username from the certificate DN, this is a blocker in utilizing different users for datafeed and monitoring.

According to [Beats GH11368](https://github.com/elastic/beats/issues/11368) this should already be supported per the available [Monitoring SSL settings](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-monitor.html#_literal_ssl_literal_5) which provide the relevant [config options](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html#_configuration_options_15).

**Repro steps**:

Configure the ES output and Xpack monitoring to use different certificates and keys:

```
output.elasticsearch.hosts: ["https://instance:9200"]
output.elasticsearch.ssl.enabled: true
output.elasticsearch.ssl.certificate_authorities:  ["/etc/filebeat/elastic-stack-ca.crt.pem"]
output.elasticsearch.ssl.certificate: "/etc/filebeat/elastic-certificates.crt.pem"
output.elasticsearch.ssl.key: "/etc/filebeat/elastic-certificates.key.pem"

xpack.monitoring:
  enabled: true
  elasticsearch:
    ssl.enabled: true
    ssl.certificate_authorities: ["/etc/filebeat/elastic-stack-ca.crt.pem"]
    ssl.certificate: "/etc/filebeat/elastic-certificates2.crt.pem"
    ssl.certificate.key: "/etc/filebeat/elastic-certificates2.key.pem"
```

fails on startup with:

> Jun 14 12:40:43 localhost.localdomain filebeat[5521]: Exiting: error loading config file: duplicate key accessing 'ssl.certificate' (source:'/etc/filebeat/filebeat.yml')
