### ISSUE TITLE
Multiline messages goes undetected with docker hints based autodiscover and with the multiline.pattern specified as a docker label

### ISSUE THREAD

**Issue by astraios** [elastic/beats#12673]
With filebeat autodiscover's docker provider, multilined message go undetected when the multiline.pattern is specified as a hint within a `co.elastic.logs/multiline.pattern` docker label.

- Version: filebeat 6.7.1
- Operating System: Ubuntu 18.04.2 LTS 

### Steps to reproduce

1. Configure filebeat with autodiscover

    ```
    filebeat.autodiscover:
      providers:
        - type: docker
          hints.enabled: true
          templates:
            - config:
              - type: docker
                containers.ids:
                  - "${data.docker.container.id}"
   ```

1. Start a container, with docker-compose, that produces multi-lined events to stdout with
   labels `co.elastic.logs/multiline.pattern: '^\['`, `co.elastic.logs/multiline.negate: true` and 
  `co.elastic.logs/multiline.match: after`

  Events should look like this
  ```
   [some-random-ui] some message title
   some stack trace
   or debug lines
  ```
