### ISSUE TITLE
How to use packetbeat to monitor mysql of docker container?

### ISSUE THREAD

**Issue by lemonl2** [elastic/beats#12711]
Mysql and packetbeat be installed on the same machine!

Mysql is started in docker container, and the packetbeat is installed on local machine. Local machine's 3306 is mapping mysql of container's 3306, i use packetbeat to monitor mysql protocol, config the 3306, but can't get any data. 

```
packetbeat.interfaces.device: any
packetbeat.flows:
  enabled: false
  timeout: 30s
  period: 10s

packetbeat.protocols:
- type: mysql
  ports: [3306]

output.console:
   enabled: true
   pretty: true
```
