### ISSUE TITLE
Redis key metricset doesn't use db number if set in the host url

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#12874]
Redis `key` metricset allows to select a [keyspace per key pattern](https://www.elastic.co/guide/en/beats/metricbeat/7.3/metricbeat-metricset-redis-key.html). Since elastic/beats#12408 it is possible to set the keyspace as the db-number in the url (`redis://127.0.0.1:6379/7`, to select the 7th keyspace), but this is ignored by the `key` metricset because it always selects its selected keyspace, defaulting to 0 if no keyspace is set.

Redis `key` metricset shouldn't select a keyspace if no keyspace is set, so the one in the host url can be used.

For confirmed bugs, please report:
- Version: 7.3 
- Steps to Reproduce: Use the redis key metricset, but set the keyspace in the url, the following configuration collects the keys from db 0 instead of from db 1 as set in the url.
```
  - module: redis
    metricsets: [key]
    key.patterns:
    - pattern: '*'
    hosts:
    - 'redis://127.0.0.1:6379/1'
```
