### ISSUE TITLE
[Metricbeat] Cloudwatch metricset failed to collect all metrics

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#12933]
When I was testing collecting EC2 metrics using aws module cloudwatch metricset, I realized some of the metrics are missing.  Turned out when there is a metricname specified but no dimensions, cloudwatch metricset assumed to collect metrics from AWS Cloudwatch with only the namespace and metricname. What it suppose to do is, to collect metrics that matches the namespace and metricname and with _any_ dimensions.

```
- module: aws
  period: 300s
  metricsets:
    - cloudwatch
  access_key_id: '${AWS_ACCESS_KEY_ID:""}'
  secret_access_key: '${AWS_SECRET_ACCESS_KEY:""}'
  session_token: '${AWS_SESSION_TOKEN:""}'
  default_region: '${AWS_REGION:us-west-1}'
  cloudwatch_metrics:
    - namespace: AWS/EC2
      metricname: CPUUtilization
      tags.resource_type_filter: ec2
```
