### ISSUE TITLE
Winlogbeat: Multiple file processing for archived .evtx files

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#13064]
We added the ability to read from archived .evtx files in 7.2+ (https://www.elastic.co/guide/en/beats/winlogbeat/7.2/faq.html#reading-from-evtx).

It looks like this new feature can only read 1 EVTX_FILE at a time which means that admins will have to write a custom script to loop over files in a directory and call `.\winlogbeat.exe -e -c .\winlogbeat-evtx.yml -E EVTX_FILE=<specific_evtx_file_path>` against each file.

If there is actually a way to batch process these files, please document accordingly.  If not, it will be nice if we can provide a feature to read from a directory of multiple .evtx files.

**Comment by andrewkroh** [comment]
You can read from more than one file simultaneously. There's no wildcard expansion or any active monitoring of the directory for new .evtx files that match.

```
winlogbeat.event_logs:
  - name: a.evtx
    no_more_events: stop

  - name: b.evtx
    no_more_events: stop
```
