### ISSUE TITLE
Add ingest node test case

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#1307]
Add a test case using ingest node to validate our configuration.

```
output:
  elasticsearch:
    hosts: [localhost:9200]
    parameters: {pipeline: my_pipeline_id}
```
