### ISSUE TITLE
output.elasticsearch not using ssl despite `ssl.enabled: true`

### ISSUE THREAD

**Issue by jordansissel** [elastic/beats#13100]
```
output.elasticsearch:  
  hosts: [ "example.com:443" ]
  index: "okta-%{[fields.domain]}"
  ssl:
    enabled: true
    supported_protocols: [ "TLSv1.2" ]
    renegotiation: never
```

The host endpoint is nginx, which reports:

```
The plain HTTP request was sent to HTTPS port
```

One must prefix the host with `https://`. This seems inconsistent and also unexpected compared to other outputs (logstash).

Further, the default port is 9200 when using `https://example.com` when I was expecting 443.
