### ISSUE TITLE
Beats 7.3 decode_base64_field is not working

### ISSUE THREAD

**Issue by guyromb** [elastic/beats#13143]
Seems like key is not readable when using decode_base64_field.

As described here: https://www.elastic.co/guide/en/beats/filebeat/master/decode-base64-field.html

I use the following processor as auto discovery hint:

```
processors:
- decode_base64_field:
    field:
      from: "a.b"
      to: "a.c"
``` 

**Result**: "failed to decode base64 fields in processor: could not fetch value for key: , Error: key not found"
**Expected**: fetching correct value using key field1, and output to field2.
