### ISSUE TITLE
[Winlogbeat] Add new filter option for event_logs

### ISSUE THREAD

**Issue by kogelc** [elastic/beats#13160]
**Describe the enhancement:**

Hello guys,

Is it possible to add a new filter option for the event_logs in WinlogBeat ?
We need to use the task filter instead of the event_id filter.
Do you think you can add this filtering option ? It would be really awesome.

**Describe a specific use case for the enhancement or feature:**

We are trying to import some of our AD Auditing log into Elasticsearch and we want to do something like that :

```
winlogbeat:
  event_logs:
  - name: Security
    tasks: Logoff
```

But today we are stuck with that :

```
winlogbeat:
  event_logs:
  - name: Security
    event_id: 4634
```

Can you help us ? Many thanks :)
