### ISSUE TITLE
[Filebeat] path variables cannot be used in files from modules.d

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#13184]
Using `${path.config}` in files from `modules.d/` causes a somewhat ambiguous error.

> Exiting: 1 error: Error unpacking module config: error unpacking module googlecloud in a dict: missing field accessing ‘0.vpcflow’ 

The error doesn't mention that it failed to expand `${path.config}` in

```
- module: googlecloud
  vpcflow:
    enabled: true
    var.project_id: my-gcp-project-id
    var.topic: googlecloud-vpc-flowlogs
    var.subscription_name: filebeat-googlecloud-vpc-flowlogs-su
    var.credentials_file: ${path.config}/gcp-service-account-xyz.json
```
