### ISSUE TITLE
[DOCS] Improvement to Filebeat docs to add Kubernetes example to Envoy proxy module

### ISSUE THREAD

**Issue by Titch990** [elastic/beats#13238]
@axw has suggested an improvement to the auto-generated file **/beats/filebeat/docs/modules/envoyproxy.asciidoc** (built as docs page https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-envoyproxy.html) to provide an example showing how to configure Filebeat to use the Envoyproxy module, via Istio. 

He says "Given that it's going to be pretty commonly used in k8s, it would probably be helpful to include an example Kubernetes manifest snippet"

Andrew can provide more details shortly.

Incidentally, when this change is actioned, can we also change "filebeat" on this page to "Filebeat", please?

**Comment by axw** [comment]
Thanks for opening this @Titch990 

> Andrew can provide more details shortly.

This came out of a discussion at a conference with the author of https://discuss.elastic.co/t/filebeat-7-2-0-autodiscover-configuration-issues/188168.

Using bits of information in https://github.com/elastic/beats/tree/master/x-pack/filebeat/module/envoyproxy and https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover.html, we came up with something along the following lines (untested, based on memory):

```yaml
filebeat.autodiscover:
  providers:
    - type: kubernetes
      templates:
        - condition:
            equals:
              kubernetes.namespace: kube-system
          config:
            - module: envoyproxy
              log:
                input:
                type: docker
                containers.ids:
                  - "${data.kubernetes.container.id}"
```

The important bit is: input needed to be nested under "log", the one and only Envoyproxy "fileset". This isn't mentioned anywhere on https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-envoyproxy.html. How are users supposed to know what name to use?
