### ISSUE TITLE
Allow inputs / module to define a target index.

### ISSUE THREAD

**Issue by ph** [elastic/beats#13255]
We are currently working on the [agent](https://github.com/elastic/beats/issues/12575) and we require that inputs (or modules depending on the beats) allow a user to define to which index the fetched data must be sent to.

So the high-level requirement is to add a new setting field that the users can specify the index they want to target and the elasticsearch output should take care of reading that value and route the events to the appropriate destination.

I think the configuration for Metricbeat and Filebeat would look like this:

```yaml
filebeat.inputs:
 - type: log
   paths: /var/log/message
   index: mycustomindex
- type: log
  index: anotheindex
```

```yaml
metricbeat.modules:
 - modules: aws
   index: awsevents
- type: docker
  index: dockerevents
```

Tasks:
- [x] Add support in libbeat to select the exact index if set on an event #14010

- [x] Add per input index setting to Filebeat elastic/beats#14010 
- [x] Add per module index setting to Metricbeat elastic/beats#15100
- [x] Add per module index setting to Auditbeat (uses Metricbeat framework) elastic/beats#15100
- [x] Add input index setting to Winlogbeat #15198
- [x] Add input index setting to Journalbeat #15071
- [x] Add function index setting to Functionbeat #15101
