### ISSUE TITLE
Functionbeat 7.1 using setup command failing hard on dashboard loading

### ISSUE THREAD

**Issue by asadzz** [elastic/beats#13276]
Hi,
I'm using 'function-beat' for cloudwatch aws logs integeration. My config looks like 
 ```
- name: cloudwatch
    enabled: true
    type: cloudwatch_logs
    description: "lambda function for cloudwatch logs"
    triggers:
      - log_group_name: /aws/lambda/cloud-watch-aws
      - log_group_name: /aws/lambda/nix-msg
      - log_group_name: /aws/lambda/ssh
      - log_group_name: /aws/lambda/yum

        filter_pattern: i-01_
  - name: sqs
    enabled: false
    type: sqs
    description: "lambda function for SQS events"
    triggers:
      - event_source_arn: arn:aws:sqs:us-east-2:xxxxx:myevents
  - name: kinesis
    enabled: false
    type: kinesis
    description: "lambda function for Kinesis events"
    triggers:
      - event_source_arn: arn:aws:sqs:us-east-1:xxxxx:myevents
setup.template.settings:
  index.number_of_shards: 1
setup.dashboards.enabled: false
setup.kibana:
  host: "illumin8.inboxbiz.com:5601"
  protocol: "https"
  username: "kibana"
  password: "*****"
output.elasticsearch:
  hosts: ["10.27.0.4:9200"]
  protocol: "http"
  username: "function_beat"
  password: "elk#123"
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
```

Please include configurations and logs if available.

For confirmed bugs, please report:
- 7.1: 
- Linux elk1 5.0.0-21-generic #22-Ubuntu SMP Tue Jul 2 13:27:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**- Steps to Reproduce:** 
1. I used exact same step given under kibana portal under ..."/tutorial/cloudwatchLogs?_g"..wiht some minor changes to make the alias be written/ created using "manage" privilege.

2. As i run command ./functionbeat setup I'm getting

> 019-08-16T19:27:01.065Z        ERROR   instance/beat.go:802    Exiting: Failed to import dashboard: The directory /root/functionbeat-7.1.1-linux-x86_64/kibana/7/dashboard is empty, nothing to import
> Exiting: Failed to import dashboard: The directory /root/functionbeat-7.1.1-linux-x86_64/kibana/7/dashboard is empty, nothing to import
> 

In my view not creation of dashboard event should lead to process exiting to shell, it should be bypassed, other option i was thinking (workaround) to use logstash as that would avoid running "setup" command, but in the tutorial section it is advised otherwise. 

Thanks.
