### ISSUE TITLE
None of the elastic setup options are working & poor documentation

### ISSUE THREAD

**Issue by Sjaak01** [elastic/beats#13487]
Filebeat 7.2.0

Hi,

For the past couple of hours I've been struggling to get any of the elastic out setup settings to work.
I want to write to a custom index. This is my config.

```
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["url.found.io:9243"]
  setup.template.name: "AWS-Proxy-Filebeat"
  setup.template.pattern: "AWS-Proxy-Filebeat-*"
  setup.dashboards.index: "AWS-Proxy-Filebeat-*"
  index: "AWS-Proxy-Filebeat-%{[agent.version]}-%{+yyyy.MM}"
```

First problem is that the Docs don't clearly state where to put the configuration. 
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-template.html

It tells you to put it under elastic output but unlike the previous page it doesn't specifically show output.elastic in the config example.

Furthermore I don't think it says where to put `setup.dashboards.index`. I think it should go under setup.kibana because if I put it there, at least filebeat fails with an error `Exiting: setup.template.name and setup.template.pattern have to be set if index name is modified`

But the name and pattern are clearly configured under output.elastic. 

If you follow the Docs you can produce a working filebeat instance using all the default settings but anything beyond that will not work.

**Comment by kvch** [comment]
Github Issues are reserved for verified bugs. Please post your question on Discuss: https://discuss.elastic.co/c/beats

Also, the indentation is incorrect.
```yaml
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["url.found.io:9243"]
  index: "AWS-Proxy-Filebeat-%{[agent.version]}-%{+yyyy.MM}"

setup.template.name: "AWS-Proxy-Filebeat"
setup.template.pattern: "AWS-Proxy-Filebeat-*"
setup.dashboards.index: "AWS-Proxy-Filebeat-*"
```
