### ISSUE TITLE
keep_original is not documented

### ISSUE THREAD

**Issue by Randy-312** [elastic/beats#13574]
I don't see the keep_original flag, noted in several issues [9172](https://github.com/elastic/beats/pull/9172) and [8083](https://github.com/elastic/beats/issues/8083).

As this is not documented for the [docker input](https://www.elastic.co/guide/en/beats/filebeat/7.3/filebeat-input-docker.html) or [container](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-container.html), I'd like to verify I can use it. 

Seems like a simple documentation update miss, so hope you can correct it shortly.

**Comment by jsoriano** [comment]
@Randy-312 thanks for taking the time for opening this issue, but the `keep_original` flag was not merged at the end as you can see in this comment https://github.com/elastic/beats/pull/9172#issuecomment-481121397

Instead, the [copy_fields](https://github.com/elastic/beats/pull/11303) processor can be used:
```
processors:
- copy_fields:
    fields:
      - from: message
        to: event.original
    fail_on_error: false
    ignore_missing: true
```
