### ISSUE TITLE
include_matches not work

### ISSUE THREAD

**Issue by masikmos** [elastic/beats#13645]
- Version: journalbeat version 5.6.9 (amd64), libbeat 5.6.9
- Operating System: Ubuntu 18.04.2 LTS

- config:
```
journalbeat.inputs:
- paths: []
  include_matches:
    - "_EXE=/usr/sbin/sshd"
    - "_COMM=sshd"
  fields:
    appid: redis

setup.template.settings:
  index.number_of_shards: 1
  _source.enabled: true

name: dev02
tags: ["sportsbook"]

fields:
  env: dev
  source: dev02

#setup.kibana:

output.logstash:
  hosts: ["srv01:5044"]

```
and i see in graylog not only SSHD messages

i see ALL Journald messages. Why??? I need only SSH
