### ISSUE TITLE
[Heartbeat] Aws ELB auto discovery won't start runner job err missing port in address

### ISSUE THREAD

**Issue by shahzad31** [elastic/beats#13669]
While testing Heart AWS ELB auto discovery , after setting aws credentials, i tried testing with config copied from docs, in console it's raising an issue

`ERROR    [autodiscover]    autodiscover/autodiscover.go:205    Auto discover config check failed for config &{{<nil> } <nil> 0xc0003288a0}, won't start runner: job err missing port in address`

I am using config like this

```
heartbeat.autodiscover:
  providers:
  - type: aws_elb
    period: 1m
    regions: ["us-east-2"]
    access_key_id: ****
    secret_access_key: ****
    session_token: ***
    templates:
    - condition:
        equals.port: 80
      config:
      - type: http
        urls: ["${data.host}:${data.port}"]
        schedule: "@every 5s"
        timeout: 1s  

```
**Steps to Reproduce:** 

1. setup heartbeat using yml file from x-pack heartbeat folder, build it and run it
2. Run elastic search 
3. Run Kibana, there is no ELB monitor for aws

Debug heartbeat console and you will see above error.
