### ISSUE TITLE
[Filebeat] Can't process fields with a dot in the name

### ISSUE THREAD

**Issue by marcomusso** [elastic/beats#13719]
**Describe the enhancement:**

It seems that a valid config for a processor like this:

```
processors:
      - drop_event:
        when:
          - equals:
            user.name: logstash
```

is not enough to filter  the 'user.name' field.
Is there are way to filter fields with dots in their names?
Full "discussion" here: https://discuss.elastic.co/t/filebeat-and-fields-with-dots-in-name/198620

**Describe a specific use case for the enhancement or feature:**

The default json output of the Elasticsearch 7.x audit log creates fields with a dot in their name (see discussion above for details).
