### ISSUE TITLE
[Metricbeat] - kubernetes metricsets get "connection refused" when querying http://${NODE_NAME}:10250/stats/summary on AWS EKS

### ISSUE THREAD

**Issue by robertgates55** [elastic/beats#13774]
**Beat version:**
metricbeat 7.3.2

**Kubernetes version:**
1.13

**Kubernetes provider:** E.g. GKE (Google Kubernetes Engine)
AWS EKS

(deployed via helm charts, but I don't think that's the core issue here hence double-raising)

**Describe the bug:**
I'm getting "connection refused" errors when the metricbeat module attempts to query from the /stats/summary endpoint.

Basic out of the box configuration is this:
```
    - module: kubernetes
      metricsets:
        - container
        - node
        - pod
        - system
        - volume
      period: 30s
      host: "${NODE_NAME}"
      hosts: ["http://${NODE_NAME}:10250"]
      processors:
      - add_kubernetes_metadata:
          in_cluster: true
```

But I've also tried various configurations/combinations
 - eg from the information specified here https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-kubernetes.html (but I get that the serviceaccount ca crt doesn't exist)
 - Set the ssl.auth to none and removed the ca (ie just using the sa bearer token)
 - multiple others (ie replace http with https, specify IP address instead of hostname, etc)

Given that the :10250 ro endpoint is marked as deprecated (and likely thus not being exposed by my EKS cluster), what _is_ the recommended configuration to scrape these metrics?

**Comment by robertgates55** [comment]
Additional info:
Changing the hosts to `https` rather than `http` like this:
```
    - module: kubernetes
      metricsets:
        - container
        - node
        - pod
        - system
        - volume
      period: 30s
      host: "${NODE_NAME}"
      hosts: ["https://${NODE_NAME}:10250"]
      processors:
      - add_kubernetes_metadata:
          in_cluster: true
```
Gives `error making http request: Get https://ip-10-208-92-73.eu-west-1.compute.internal:10250/stats/summary: x509: certificate signed by unknown authority`


So I updated the config to:
```
- module: kubernetes
          metricsets:
            - container
            - node
            - pod
            - system
            - volume
          period: 30s
          host: "${NODE_NAME}"
          hosts: ["https://${NODE_NAME}:10250"]
          ssl.verification_mode: none
          processors:
          - add_kubernetes_metadata:
              in_cluster: true
```
Which results in `HTTP error 401 in : 401 Unauthorized`


So I updated the config to:
```
- module: kubernetes
          metricsets:
            - container
            - node
            - pod
            - system
            - volume
          period: 30s
          host: "${NODE_NAME}"
          hosts: ["https://${NODE_NAME}:10250"]
          ssl.verification_mode: none
          bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
          processors:
          - add_kubernetes_metadata:
              in_cluster: true
```
Which gives `HTTP error 403 in : 403 Forbidden`
