### ISSUE TITLE
[Metricbeat] Kibana module does not seem to follow 302s and instead errors

### ISSUE THREAD

**Issue by cachedout** [elastic/beats#13809]
When using the Kibana module with Metricbeat, if one does not specify a `basepath` in the configuration, Metricbeat will immediately exit after start with an error that is difficult to understand:

```
2019-09-26T10:45:41.652+0200    INFO    [monitoring]    log/log.go:131  Stopping metrics logging.
2019-09-26T10:45:41.652+0200    INFO    instance/beat.go:440    metricbeat stopped.
2019-09-26T10:45:41.652+0200    ERROR   instance/beat.go:886    Exiting: 1 error: invalid character '<' looking for beginning of value
Exiting: 1 error: invalid character '<' looking for beginning of value
```

The above is displayed when attempting to use Metricbeat with the `kibana-xpack.yml` file with values as follows:

```
10:49 $ cat modules.d/kibana-xpack.yml
# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-kibana.html

- module: kibana
  metricsets:
    - stats
  period: 10s
  hosts: ["localhost:5601"]
  #  basepath: "/lhq"   # <--Note that this is commented out
  username: "elastic"
  password: "changeme"
  xpack.enabled: true
```

If one sets `basepath`, this error does not occur and Metricbeat starts normally.
```
10:49 $ cat modules.d/kibana-xpack.yml
# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-kibana.html

- module: kibana
  metricsets:
    - stats
  period: 10s
  hosts: ["localhost:5601"]
  basepath: "/lhq"   # <--Note that this is no longer commented out
  username: "elastic"
  password: "changeme"
  xpack.enabled: true
```

An HTTP request to Kibana set shows that it is returning a 302 redirect when a request is sent to /:

```
10:28 $ http --auth elastic:changeme http://localhost:5601/
HTTP/1.1 302 Found
Connection: keep-alive
Date: Thu, 26 Sep 2019 08:44:57 GMT
cache-control: no-cache
content-length: 0
content-type: text/html; charset=utf-8
location: /lhq  # <--Note the location field in the response
vary: origin
```
I think that we should do one or the other, with the first option being preferable:

1) If a basepath is not set in the configuration, examine the result of the 302 for the `location` field and use it as the value for `basepath` and continue on without an error.

2) If a `basepath` is not set and we don't want to follow the 302, let's at least return an error that informs the user that we cannot start without an explicit path set in the configuration.
