### ISSUE TITLE
[libbeat] Using env variables in additional fields with numeric values strips leading zeros

### ISSUE THREAD

**Issue by gservat** [elastic/beats#13807]
I'm using Heartbeat 7.3.1 and given a config like the following:

```
heartbeat.config.monitors:
  path: ${path.config}/monitors.d/*.yml
  reload.enabled: true
  reload.period: 30s

output.elasticsearch:
  hosts: "<url>"
  username: "<user>"
  password: "<pass>"

fields:
  foo: '${BAR}'
```

... I found that if I set the env variable `BAR=001`, then `fields.foo` (keyword field) would have the value `1` instead of `"001"`. I didn't expect the leading zeros to be stripped. My workaround is to use:

```
fields:
  foo: '"${BAR}"'
```

Output from using the `console` output with env variable `BAR=001`:

```
{
  [..snip..]
  "summary": {
    "up": 1,
    "down": 0
  },
  "http": {
    "rtt": {
      "write_request": {
        "us": 186
      },
      "response_header": {
        "us": 379444
      },
      "validate": {
        "us": 379478
      },
      "content": {
        "us": 33
      },
      "total": {
        "us": 1539331
      }
    },
    "response": {
      "status_code": 200
    }
  },
  "event": {
    "dataset": "uptime"
  },
  "fields": {
    "foo": 1
  },
  [..snip..]
}
```
