### ISSUE TITLE
problem with metricbeat system.filesystem.mount_point field data when I move docker's default /var/lib/docker to another directory

### ISSUE THREAD

**Issue by qqqasdwx** [elastic/beats#13819]
-  Version: metricbeat 7.3.1 on docker
-  Operating System:  CentOS Linux release 7.6.1810 (Core)
-  Discuss Forum URL: 
-  Steps to Reproduce:   
I  move docker's default /var/lib/docker to another directory
Reference https://linuxconfig.org/how-to-move-docker-s-default-var-lib-docker-to-another-directory-on-ubuntu-debian-linux
metricbeat.docker.yml
```yml
metricbeat.config:

# logging.level: debug

queue.mem:
  events: 40960
  flush.min_events: 1
  flush.timeout: 1s

setup.dashboards.enabled: true
setup.dashboards.index: "monitor-*"
setup.kibana:
  host: "http://${KIBANA_HOST}"

metricbeat.modules:
- module: system
  metricsets:
    - cpu             # CPU usage
    - load            # CPU load averages
    - memory          # Memory usage
    - network         # Network IO
    - diskio          # Disk IO
  enabled: true
  period: 3s
  processes: ['.*']
- module: system
  metricsets:
    - uptime          # System Uptime //1day
    - filesystem     # File system usage for each mountpoint //30m
    - fsstat         # File system summary metrics //30m
  enabled: true
  period: 30m
  processes: ['.*']
- module: system
  metricsets:
    - uptime          # System Uptime //1day
  enabled: true
  period: 1440m
  processes: ['.*']
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "event"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    # - "network" 
  hosts: ["unix:///hostfs/var/run/docker.sock"]
  period: 3s
  enabled: true


output:
  elasticsearch:
    indices:
      - index: "monitor-%{[agent.version]}-%{[event.module]}-%{[metricset.name]}-%{+yyyy.MM.dd}"
    enabled: true
    compression_level: 3
    worker: 3
    bulk_max_size: 1024
    hosts: ["https://${ELASTICSEARCH_NGINX_HOST}"]
    protocol: "**"
    username: "**"
    password: "**"
    ssl:
      verification_mode: none
    timeout: 15
```
docker-compose.yml

```yml
version: '3.2'

services:
  monitor-beat:
    image: metricbeat
    container_name: 'monitor-beat'
    restart: always
    user: root
    command: -e -system.hostfs=/hostfs
    environment: 
      - ELASTICSEARCH_NGINX_HOST=**
      - KIBANA_HOST=**
    cap_add:
      - SYS_PTRACE
      - DAC_READ_SEARCH
    volumes: 
      - type: bind
        source: /proc
        target: /hostfs/proc
        read_only: true
      - type: bind
        source: /sys/fs/cgroup
        target: /hostfs/sys/fs/cgroup
        read_only: true
      - type: bind
        source: /
        target: /hostfs
        read_only: true
      - /var/run/docker.sock:/var/run/docker.sock:ro
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    network_mode: host
```

 host machine run`df -h`  
![image](https://user-images.githubusercontent.com/19298463/65740788-83517b80-e11c-11e9-8b06-2909ac35c6bc.png)
run `docker exec -it monitor-beat df -h`
![image](https://user-images.githubusercontent.com/19298463/65741177-d972ee80-e11d-11e9-8353-bdf27ac5ae25.png)
you can see device /dev/mapper/centos-home mount /home in host machine but mount /etc/hosts in metricbeat container, and see it in kibana:
![image](https://user-images.githubusercontent.com/19298463/65741318-4090a300-e11e-11e9-9cae-2a4f05e1f4c2.png)

I want see mount_point is /hostfs/home but i get /etc/hosts,Is this the expected behavior?
