### ISSUE TITLE
Winlogbeat v7 to NiFi partial messages

### ISSUE THREAD

**Issue by Pavel201909** [elastic/beats#13842]
Hi All,

I ship windows events using ListenBeats in NiFi, however some messages arrive truncated. So far I can't identify a pattern why this happens.

what I get on NiFi is this mess:
![1](https://user-images.githubusercontent.com/55888379/65821583-b63c6200-e237-11e9-804e-e98fcec903d8.jpg)

I can see some non-printable characters in the content of arrived message:
![err2](https://user-images.githubusercontent.com/55888379/65821590-d704b780-e237-11e9-8c62-a745875d61b2.jpg)
![3](https://user-images.githubusercontent.com/55888379/65821607-fef41b00-e237-11e9-8e6d-b778b044df25.jpg)

the original event which I can see in Event Viewer has nothing suspicious though:
```
Log Name:      Security
Source:        Microsoft-Windows-Security-Auditing
Date:          9/26/2019 11:05:45 PM
Event ID:      4627
Task Category: Group Membership
Level:         Information
Keywords:      Audit Success
User:          N/A
Computer:      xxx.corp.yyyyyyy.ru
Description:
Group membership information.

Subject:
	Security ID:		NULL SID
	Account Name:		-
	Account Domain:		-
	Logon ID:		0x0

Logon Type:			3

New Logon:
	Security ID:		SYSTEM
	Account Name:		zzzzzz01$
	Account Domain:		xxx.corp.yyyyyyy.RU
	Logon ID:		0x14303B0E

Event in sequence:		1 of 1

Group Membership:			
		BUILTIN\Administrators
		Everyone
		BUILTIN\Pre-Windows 2000 Compatible Access
		BUILTIN\Users
		BUILTIN\Windows Authorization Access Group
		NT AUTHORITY\NETWORK
		NT AUTHORITY\Authenticated Users
		NT AUTHORITY\This Organization
		CORP\zzzzz01$
		CORP\Domain Controllers
		NT AUTHORITY\ENTERPRISE DOMAIN CONTROLLERS
		Authentication authority asserted identity
		CORP\Denied RODC Password Replication Group
		CORP\RAS and IAS Servers
		Mandatory Label\System Mandatory Level

The subject fields indicate the account on the local system which requested the logon. This is most commonly a service such as the Server service, or a local process such as Winlogon.exe or Services.exe.

The logon type field indicates the kind of logon that occurred. The most common types are 2 (interactive) and 3 (network).

The New Logon fields indicate the account for whom the new logon was created, i.e. the account that was logged on.

This event is generated when the Audit Group Membership subcategory is configured.  The Logon ID field can be used to correlate this event with the corresponding user logon event as well as to any other security audit events generated during this logon session.
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Security-Auditing" Guid="{54849625-5478-4994-A5BA-3E3B0328C30D}" />
    <EventID>4627</EventID>
    <Version>0</Version>
    <Level>0</Level>
    <Task>12554</Task>
    <Opcode>0</Opcode>
    <Keywords>0x8020000000000000</Keywords>
    <TimeCreated SystemTime="2019-09-26T20:05:45.358484000Z" />
    <EventRecordID>20279178</EventRecordID>
    <Correlation />
    <Execution ProcessID="632" ThreadID="7752" />
    <Channel>Security</Channel>
    <Computer>dc01.corp.kraftlab.ru</Computer>
    <Security />
  </System>
  <EventData>
    <Data Name="SubjectUserSid">S-1-0-0</Data>
    <Data Name="SubjectUserName">-</Data>
    <Data Name="SubjectDomainName">-</Data>
    <Data Name="SubjectLogonId">0x0</Data>
    <Data Name="TargetUserSid">S-1-5-18</Data>
    <Data Name="TargetUserName">DC01$</Data>
    <Data Name="TargetDomainName">CORP.KRAFTLAB.RU</Data>
    <Data Name="TargetLogonId">0x14303b0e</Data>
    <Data Name="LogonType">3</Data>
    <Data Name="EventIdx">1</Data>
    <Data Name="EventCountTotal">1</Data>
    <Data Name="GroupMembership">
		%{S-1-5-32-544}
		%{S-1-1-0}
		%{S-1-5-32-554}
		%{S-1-5-32-545}
		%{S-1-5-32-560}
		%{S-1-5-2}
		%{S-1-5-11}
		%{S-1-5-15}
		%{S-1-5-21-900100797-3563623125-4166005187-1000}
		%{S-1-5-21-900100797-3563623125-4166005187-516}
		%{S-1-5-9}
		%{S-1-18-1}
		%{S-1-5-21-900100797-3563623125-4166005187-572}
		%{S-1-5-21-900100797-3563623125-4166005187-553}
		%{S-1-16-16384}</Data>
  </EventData>
</Event>
```
winlogbeat config **winlogbeat.yml** :
```
winlogbeat.event_logs:
  - name: Application
    ignore_older: 168h
    fields_under_root: true
    fields:
      client_name: "region"
    tags: [ "application","windows" ]
  - name: Security
    ignore_older: 168h
    fields_under_root: true
    fields:
      client_name: "region"
    tags: [ "security","windows" ]
    processors:
      - drop_event.when.not.or:
        - range.winlog.event_id: { gte: 4608, lte: 4609 }
        - equals.winlog.event_id: 4616
        - equals.winlog.event_id: 4621
        - range.winlog.event_id: { gte: 4624, lte: 4625 }
        - equals.winlog.event_id: 4627
        - equals.winlog.event_id: 4634
        - range.winlog.event_id: { gte: 4647, lte: 4649 }
        - equals.winlog.event_id: 4656
        - equals.winlog.event_id: 4658
        - range.winlog.event_id: { gte: 4662, lte: 4663 }
        - range.winlog.event_id: { gte: 4672, lte: 4675 }
        - equals.winlog.event_id: 4688
        - equals.winlog.event_id: 4696
        - range.winlog.event_id: { gte: 4698, lte: 4702 }
        - range.winlog.event_id: { gte: 4704, lte: 4707 }
        - range.winlog.event_id: { gte: 4713, lte: 4720 }
        - range.winlog.event_id: { gte: 4722, lte: 4735 }
#        - equals.winlog.event_id: 4724
#        - equals.winlog.event_id: 4728
        - range.winlog.event_id: { gte: 4737, lte: 4764 }
#        - equals.winlog.event_id: 4738
        - equals.winlog.event_id: 4767
        - range.winlog.event_id: { gte: 4774, lte: 4794 }
        - range.winlog.event_id: { gte: 4800, lte: 4803 }
        - range.winlog.event_id: { gte: 4864, lte: 4867 }
        - equals.winlog.event_id: 4902
        - range.winlog.event_id: { gte: 4904, lte: 4908 }
        - equals.winlog.event_id: 4912
        - equals.winlog.event_id: 4964
        - range.winlog.event_id: { gte: 5024, lte: 5025 }
        - range.winlog.event_id: { gte: 5027, lte: 5030 }
        - range.winlog.event_id: { gte: 5032, lte: 5035 }
        - equals.winlog.event_id: 5037
        - range.winlog.event_id: { gte: 5058, lte: 5059 }
        - range.winlog.event_id: { gte: 5136, lte: 5140 }
        - range.winlog.event_id: { gte: 5142, lte: 5144 }
        - range.winlog.event_id: { gte: 5148, lte: 5149 }
        - equals.winlog.event_id: 5168
        - equals.winlog.event_id: 5378
        - range.winlog.event_id: { gte: 5632, lte: 5633 }
        - equals.winlog.event_id: 6416
        - range.winlog.event_id: { gte: 6419, lte: 4624 }
  - name: System
    ignore_older: 168h
    fields_under_root: true
    fields:
      client_name: "region"
    tags: [ "system","windows" ]

output:
  logstash:
    hosts: ["xxxxxxxxxxxxxxxxx:5044"]
    worker: 1
    compression_level: 0
    bulk_max_size: 1
    pipelining: 0
    codec.json:
      pretty: false
      escape_html: true

winlogbeat.shutdown_timeout: 10s
```
