### ISSUE TITLE
[heartbeat] received the dead application heartbeat message

### ISSUE THREAD

**Issue by ZMMWMY** [elastic/beats#13843]
Hi all, i  have deployed application in k8s and deployed heartbeat to monitor them .
although the dead application have been dead for a while,  i found heartbeat still send the dead application info.
this is my configuration
* heartbeat 7.3.0
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: heartbeat-config
  namespace: monitor
  labels:
    k8s-app: heartbeat
data:
  heartbeat.yml: |-
    heartbeat.autodiscover:
      providers:
        - type: kubernetes
          host: ${NODE_NAME}
          templates:
            - condition.and:
                - equals:
                    kubernetes.namespace: "monitor"
                - not:
                    equals:
                      kubernetes.container.name: "heartbeat"
              config:
                - type: http
                  urls: ["http://${data.host}:8080/info"]
                  schedule: "@every 10s"
                  timeout: 1s
                  name: "${data.kubernetes.pod.name}"

      processors:
      - add_kubernetes_metadata:
          in_cluster: true    

   output.kafka:
      hosts: ["kafka:9092"]
      topic: 'heartbeat-dev'
      partition.round_robin:
        reachable_only: false
      required_acks: 1
      compression: gzip
      max_message_bytes: 1000000
    monitoring:
      enabled: true
      elasticsearch:
        hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
        username: ${BEAT_MONITOR_USERNAME}
        password: ${BEAT_MONITOR_PASSWORD}
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: heartbeat
  namespace: monitor
  labels:
    k8s-app: heartbeat
spec:
  template:
    metadata:
      labels:
        k8s-app: heartbeat
    spec:
      serviceAccountName: heartbeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: heartbeat
        image: registry-vpc.cn-hangzhou.aliyuncs.com/elasticstack/heartbeat:7.3.0
        args: [
          "-c", "/etc/heartbeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: 
        - name: ELASTICSEARCH_PORT
          value: ""
        - name: LOGSTASH_HOST
          value: 
        - name: LOGSTASH_PORT
          value: 
        - name: HEARTBEAT_USERNAME
          value:
        - name: HEARTBEAT_PASSWORD
          value: 
        - name: BEAT_MONITOR_USERNAME
          value:
        - name: BEAT_MONITOR_PASSWORD
          value:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
          # If using Red Hat OpenShift uncomment this:
          #privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/heartbeat.yml
          readOnly: true
          subPath: heartbeat.yml
        - name: data
          mountPath: /usr/share/heartbeat/data
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: heartbeat-config
      # data folder stores a registry of read status for all files, so we don't send everything again on a heartbeat pod restart
      - name: data
        hostPath:
          path: /var/lib/heartbeat-data
          type: DirectoryOrCreate
```

thank you
