### ISSUE TITLE
[Heartbeat] Add better config syntax for x-www-form-encoded

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#13938]
Heartbeat supports `x -www-form-encoded` data today, but it's clunky. One must use a config like the following:

```
  check.request:
    method: POST
    headers: 
      'Content-Type': 'application/x-www-form-urlencoded'
    body: "name=first&email=someemail%40someemailprovider.com"
```

Ideally we'd have an option like:

```
check.form_data
  name: first
  email: someemail@blah.com
```

This would set the `Content-type` header appropriately, and encode the body as well.
