### ISSUE TITLE
Filebeat stops writing logs and needs to be restarted to keep on writing

### ISSUE THREAD

**Issue by sergey-stratoscale** [elastic/beats#1396]
Hi,

We're running filebeat to monitor log files on our VMs with output to local file. The configuration:

```
filebeat:
  *spool_size: 12400
  *publish_async: true
  prospectors:
   -
      paths:
        - '/var/log/*.log'
        - '/var/log/stratoscale/mancala/*.log'
      document_type: "log"
      *harvester_buffer_size: 65536
      include_lines: ["ERROR"]
      exclude_files: [".gz$"]
      *ignore-older: "24h"
      force_close_files: true
      fields_under_root: true
      tail_files: false
      fields:
        tags :
          - 'log'

output:
  file:
    path: "/var/log/"
    filename: exceptions.log
```

The problem that I'm facing is that after installing the filebeat, replacing the config file and restarting the filebeat, after a while, some of the files stop being written to the output file.

In the debug mode and lsof of the file I can see that filebeat sees the wanted files. When running something like "echo ERROR >> foo.log" I see file descriptor being opened and file scanned in debug mode normally, and offset of the descriptor moving as i write into it some more.

Another weird thing, is that restart to the service seems to reset it, and the filebeat begins outputting once again to the new output file. However, it doesn't write any lines that were written before the restart (as i presume from what I've written above is because the filebeat assumes the read and filebeat regestry file update the offset accordingly?), but all the consecutive lines that match the pattern are caught.

Another thing, probably worth mentioning (that might be some sort of cause to it), is that we have lots of *.log files (~20), and some of them are outputted to the filebeat output file until a certain point (for like 10 min after installation), and then it stops outputting the lines all together.
Also, all the log files created after filebeat installation.
(the lines marked with * were added later with no effect on the output)

- Version: tried and had similar results on 1.1.1, 1.2.1 and 5.0
- Operating System: CentOS7

Thanks!

**Comment by AtzeDeVries** [comment]
Hi,

I have the same issues here on Ubuntu 14.04. I've also tested on versions 1.0.0 1.1.1 1.2,1. and 5. 

When i use info logging

```
2016-04-18T10:15:52+02:00 INFO Events sent: 3
2016-04-18T10:15:52+02:00 INFO Registry file updated. 2 states written.
2016-04-18T10:15:59+02:00 INFO Events sent: 1
2016-04-18T10:15:59+02:00 INFO Registry file updated. 2 states written.
2016-04-18T10:16:07+02:00 INFO Events sent: 7
2016-04-18T10:16:07+02:00 INFO Registry file updated. 2 states written.
2016-04-18T10:16:23+02:00 INFO Error publishing events (retrying): read tcp 172.16.35.18:39811->145.136.241.15:5875: i/o timeout
2016-04-18T10:16:24+02:00 INFO Events sent: 1
2016-04-18T10:16:24+02:00 INFO Registry file updated. 2 states written.
2016-04-18T10:16:24+02:00 INFO Events sent: 2
2016-04-18T10:16:24+02:00 INFO Registry file updated. 2 states written.
2016-04-18T10:16:29+02:00 INFO Events sent: 1
2016-04-18T10:16:29+02:00 INFO Registry file updated. 2 states written.
2016-04-18T10:16:34+02:00 INFO Events sent: 2
```

The issue seems the same as https://discuss.elastic.co/t/filebeat-stopped-working/41401

It is only in combination of suricata (using eve.json tracking). Other sources don't seem to have this problem. 

```
### GENERATED BY PUPPET ###
--- 
filebeat: 
  prospectors: 
    - paths: 
        - /var/log/suricata/eve.json
      fields: 
        type: idsevent
        geoip_src_field: source_ip_field
        geoip_dest_field: destination_ip_field
    - paths: 
        - /var/log/suricata/suricata.log.json
      fields: 
        type: idslog
        testdata: "true"
output:
  logstash:
    hosts: ["redacted list"]
    loadbalance: false
    bulk_max_size: 10
    timeout: 3
    tls:
      # List of root certificates for HTTPS server verifications
      #certificate_authorities: ["/etc/pki/root/ca.pem"]

      # Certificate for TLS client authentication
      certificate: "/etc/ssl/logstash_cert.crt"

      # Client Certificate Key
      certificate_key: "/etc/ssl/logstash_key.key"

      # Controls whether the client verifies server certificates and host name.
      # If insecure is set to true, all server host names and certificates will be
      # accepted. In this mode TLS based connections are susceptible to
      # man-in-the-middle attacks. Use only for testing.
      insecure: true
logging:
  level: info
  to_files: true
  files:
    path: /tmp
    name: beat.log
    keepfiles: 7
```

logstash input config

```
### MANAGED BY PUPPET ###
input {
  beats {
    port => 5875
    ssl  => true
    ssl_certificate => "/etc/ssl/logstash_cert.crt"
    ssl_key => "/etc/ssl/logstash_key.key"
  }
}
```
