### ISSUE TITLE
[Metricbeat][7.0.0] Parameter setup.dashboards.index is broken

### ISSUE THREAD

**Issue by ppenhouet** [elastic/beats#14019]
Hello, 

I have encountered an issue with setup.dashboards.index parameter in metricbeat conf. 

Here is my metricbeat.yml : 
```sh
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.modules:
- module: kafka
  metricsets: ["consumergroup", "partition"]
  period: 10s
  hosts: ["localhost:9092"]
  enabled: true

fields_under_root: true
fields:
  rep.host.name: localhost
  platform.id: platform
  supervision.level: system
  type: metricbeat

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.ilm.enabled: false
setup.dashboards.enabled: false
setup.dashboards.index: "platform-metricbeat-*"

setup.template.name: "platform-metricbeat-%{[beat.version]}"
setup.template.pattern: "platform-metricbeat-%{[beat.version]}-*"

output.elasticsearch:
  hosts: ["localhost:9200"]
  index: "platform-metricbeat-%{[beat.version]}-%{+yyyy.MM.dd}"
```

After running ./metricbeat setup -c metricbeat.yml --dashboards (with ES and Kibana up), I must have an index pattern platform-metricbeat-* in Kibana but I have default one : metricbeat-*. So metricbeat dasboards are broken due to wrong index pattern 

I encountered this issue since 7.0.0 (also tested in 7.1.0, 7.2.0, 7.3.0) version. No problem with 6.8.2 version.

**Comment by fpompermaier** [comment]
This is true also for filebeat 7.5.0..

**Comment by npac** [comment]
Issue is present in 7.6 branch

**Comment by exZStas** [comment]
Hello,

i've got exactly the same issue on metricbeat 7.9.2.
The only thing is that i use logstash instead of sending it directly to elasticsearch.
Here is my config

```
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.template.name: "test-kafka-%{[beat.version]}"
setup.template.pattern: "test-kafka-%{[beat.version]}-*"
setup.template.overwrite: true
setup.dashboards.index: "test-kafka-*"

setup.ilm.enabled: false
setup.kibana:
  host: "localhost:5601"
setup.dashboards.enabled: true

setup.dashboards.index: "test-kafka-*"
output.logstash:
  hosts: ["localhost:5045"]
```

Please take into account index `test-kafka-*` was created and via kibana i can find data via 'Discover' by adding kafka.* fields which belongs to kafka module. 
I found out that default dashboard still uses `metrocbeat-*` index pattern by exporting dashboard.json. Tried to fix it manually by exporting dashboard -> fixing -> importing so that kibana asks what index i want to use, but no luck with that.

Does anybody experiencing the same issue?
