### ISSUE TITLE
Make kubernetes autodiscover and metadata work for other resources

### ISSUE THREAD

**Issue by exekias** [elastic/beats#14044]
As of today, both `kubernetes` autodiscover provider and `add_kubernetes_metadata` processor only work with Pods. We want to extend their support so we can do both autodiscover and enrichment based on other kinds of resources (for instance, nodes, services, namespaces...).

A configuration like this could be a good fit (up to discussion):

```
metricbeat.autodiscover:
  - providers: kubernetes
    resource: node
    ...
```

This would make autodiscover launch configurations based on cluster nodes.

About `add_kubernetes_metadata`, we need to figure out what's the best approach for the config

cc @vjsamuel @sorantis @odacremolbap @ChrsMark
