### ISSUE TITLE
Introduce a specific error message for invalid processor YAML

### ISSUE THREAD

**Issue by justinkambic** [elastic/beats#14049]
**Is your feature request related to a problem? Please describe.**
We made a mistake when configuring Heartbeat's observer processor. We had something like:

```yaml
processors:
- add_observer_metadata:
  geo:
    name: "NAME"
    location: "39.1242, 75.4352"
```

and further down the file we also had...

```yaml
processors:
- add_observer_metadata
```

This configuration causes Heartbeat to run like normal but without embedding any location data.

**Describe the solution you'd like**
If possible, it would be better if we could alert the user to the misconfiguration, as this kind of thing could easily go unnoticed. An error message when starting up alerting them that the processor will not run in the current configuration would be better.

**Describe alternatives you've considered**
Heartbeat could stop running with an error.

**Additional context**
N/A

**Comment by andrewvc** [comment]
@justinkambic I've moved this to the beats repo since it will require coordination with the beats team, specifically @urso and@ph are the experts in YAML parsing AFAIK.

**Comment by urso** [comment]
I don't think we can do this on the YAML layer. Depending on the processor it might be ok to have multiple instances or not. This is maybe something we can encode in the processor definition in the future.

I think part of the problem is the processor itself. It seems to overwrite the complete namespace, instead of adding fields.

**Comment by andrewvc** [comment]
@urso hmmm, so we should just do merges, I think that makes sense. I'll open a PR that does that.

**Comment by andrewvc** [comment]
@justinkambic I tried replicating this with the following section in my config:

```
processors:
  - add_observer_metadata:
      geo:
        name: my-name


processors:
  - add_observer_metadata:
```

but I the data was still set correctly. Looking at the code, it should merge the processors, not overwrite them.
