### ISSUE TITLE
First collection for `system/process` metricset produces 0 values for cpu fields

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#14042]
Version: `master` / 8.0.0

Operating System: Mac OS X 10.14.6

Steps to Reproduce:

1. Enable only the `system` module in Metricbeat.
2. Configure the `system` module like so:
   ```yml
    - module: system
      period: 10s
      metricsets:
        - process
      process.include_top_n:
        by_cpu: 5
    ```
3. Start Metricbeat.
4. Since `process.include_top_n.by_cpu` is set to 5, 5 events will be produced by the _very first collection_. Observe that the value of the `cpu.total` field for **all** these events looks like this:
   ```
   {"value":0,"pct":0,"norm":{"pct":0}}
   ```
5. However, notice that events produced by _subsequent collections_ produce non-zero values in the `cpu.total` field and, more importantly, the events correspond to the top 5 processes running on the host sorted by CPU usage.

Other potentially interesting observations:

* Even if `process.include_top_n.enabled` is set to `false`, the same behavior as described above is observed.
* The `system.process.memory` fields are not affected in a similar fashion. That is, they have non-zero values in events produced by the first and subsequent collections.
