### ISSUE TITLE
Support SRV record for output host

### ISSUE THREAD

**Issue by Wing924** [elastic/beats#14053]
**Describe the enhancement:**

Currently output host only support A record.
I suggest it support SRV record in addition.

example:
```bash
$ dig SRV _beats._tcp.example.com
...
;; ANSWER SECTION:
_beats._tcp.example.com. 3600 IN SRV	0 0 5044 svr1.example.com.
_beats._tcp.example.com. 3600 IN SRV	0 0 5044 svr2.example.com.
_beats._tcp.example.com. 3600 IN SRV	0 0 5044 svr3.example.com.
...
```
```yml
output.logstash:
  hosts: ['_beats._tcp.example.com']
  loadbalance: true
```
equals to
```yml
output.logstash:
  hosts:
  - svr1.example.com:5044
  - svr2.example.com:5044
  - svr3.example.com:5044
  loadbalance: true
```

**Describe a specific use case for the enhancement or feature:**

Because beats are running on all clients, it's hard to change all the config if outputs are scaleed out or replaced.
SRV record is a good way to discover the outputs.
