### ISSUE TITLE
[Metricbeat] Windows perfmon wildcard queries with multiple brackets show wrong instance name

### ISSUE THREAD

**Issue by peterdkdp** [elastic/beats#14273]
Similar to issue elastic/beats#9835 , but I'm not sure if this should be handled as the same bug.
In the windows/perfmon module, when using a wildcard query with multiple brackets the string between the last brackets is used as instance name.

Module example from **metricbeat.yml**:
```
- module: windows
  metricsets: [perfmon]
  period: 1m
  perfmon.ignore_non_existent_counters: true
  perfmon.group_measurements_by_instance: true
  perfmon.counters:
    - instance_label: sqlserver.database.name
      measurement_label: database.log_file_size
      query: '\SQLServer:Databases(*)\Log File(s) Size (KB)'
      format: "long"
    - instance_label: sqlserver.database.name
      measurement_label: database.log_file_used_size
      query: '\SQLServer:Databases(*)\Log File(s) Used Size (KB)'
      format: "long"
```

Results in the following (example from Kibana discovery):
windows.perfmon.database.log_file_size	73,720
windows.perfmon.database.log_file_used_size	96,447
windows.perfmon.sqlserver.database.name	KB

All database.name are "KB"

Elastic & Metricbeat version: 7.3.2
