### ISSUE TITLE
can't specify pipeline for module

### ISSUE THREAD

**Issue by SlavikCA** [elastic/beats#14348]
pipeline setting in the nginx module has no effect.

Elastic version: 7.4.0
Filebeat versions: 7.4.1
OS: Ubuntu 18.04

I have only one output defined in the "filebeat.yml":
```
#-------------------------- Elasticsearch output ------------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["elk.slavikf.com:9200"]
```

And then I'm trying to use specific pipeline by nginx module, so here is nginx module config:
```
- module: nginx
  # Access logs
  access:
    enabled: true

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths: ["/var/log/nginx/*/*access.log"]

    # Convert the timestamp to UTC
    var.convert_timezone: true

    # The Ingest Node pipeline ID associated with this input. If this is set, it
    # overwrites the pipeline option from the Elasticsearch output.
    output.elasticsearch.pipeline: 'filebeat-nginx-access-default'
    pipeline: 'filebeat-nginx-access-default'
```

that doesn't work.
Here is what I see in the logs:
```
2019-10-31T07:35:32.072Z        INFO    elasticsearch/client.go:743     Attempting to connect to Elasticsearch version 7.4.0
2019-10-31T07:35:32.072Z        DEBUG   [elasticsearch] elasticsearch/client.go:761     GET http://elk.slavikf.com:9200/_xpack?human=false  <nil>
2019-10-31T07:35:32.237Z        DEBUG   [modules]       fileset/pipelines.go:67 Required processors: [{user_agent ingest-user-agent} {geoip ingest-geoip}]
2019-10-31T07:35:32.237Z        DEBUG   [elasticsearch] elasticsearch/client.go:761     GET http://elk.slavikf.com:9200/_nodes/ingest  <nil>
2019-10-31T07:35:32.329Z        DEBUG   [elasticsearch] elasticsearch/client.go:761     GET http://elk.slavikf.com:9200/_ingest/pipeline/filebeat-7.4.1-nginx-access-default  <nil>
2019-10-31T07:35:32.425Z        DEBUG   [modules]       fileset/pipelines.go:120        Pipeline filebeat-7.4.1-nginx-access-default already loaded
2019-10-31T07:35:32.426Z        DEBUG   [modules]       fileset/pipelines.go:67 Required processors: []
2019-10-31T07:35:32.426Z        DEBUG   [elasticsearch] elasticsearch/client.go:761     GET http://elk.slavikf.com:9200/_ingest/pipeline/filebeat-7.4.1-nginx-error-pipeline  <nil>
2019-10-31T07:35:32.520Z        DEBUG   [modules]       fileset/pipelines.go:120        Pipeline filebeat-7.4.1-nginx-error-pipeline already loaded
```
so, it is using `filebeat-7.4.1-nginx-access-default` pipeline instead.

I also tried this options:
- output.elasticsearch.pipeline.id: 'filebeat-nginx-access-default'
- pipeline.id: 'filebeat-nginx-access-default'
But then filebeat is not starting and I'm getting:
```
2019-10-31T07:32:17.651Z        DEBUG   [cfgfile]       cfgfile/cfgfile.go:193  Load config from file: /etc/filebeat/modules.d/nginx.yml
2019-10-31T07:32:17.651Z        ERROR   cfgfile/reload.go:275   Error loading config from file '/etc/filebeat/modules.d/nginx.yml', error invalid config: duplicate key accessing 'output.elasticsearch.pipeline' (source:'/etc/filebeat/modules.d/nginx.yml')
2019-10-31T07:32:17.911Z        INFO    instance/beat.go:432    filebeat stopped.
2019-10-31T07:32:17.911Z        ERROR   instance/beat.go:878    Exiting: 1 error: invalid config: duplicate key accessing 'output.elasticsearch.pipeline' (source:'/etc/filebeat/modules.d/nginx.yml')
Exiting: 1 error: invalid config: duplicate key accessing 'output.elasticsearch.pipeline' (source:'/etc/filebeat/modules.d/nginx.yml')
```

So, is there a way to tell nginx access module to use specific pipeline?

**Comment by consulthys** [comment]
The answer is here: https://stackoverflow.com/a/58726519/4604579

**Comment by SlavikCA** [comment]
> The answer is here: https://stackoverflow.com/a/58726519/4604579

I tried to define global pipeline, as you suggested:
```
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["elk.slavikf.com:9200"]
  pipeline: 'filebeat-nginx-access-default'
```
However, Filebeat still uses default pipeline, as I can see from the default log:
`[elasticsearch]	elasticsearch/client.go:761	GET http://elk.slavikf.com:9200/_ingest/pipeline/filebeat-7.4.2-nginx-access-default  <nil>`

Attaching complete log here:
[debug.log](https://github.com/elastic/beats/files/3818392/debug.log)

**Comment by SlavikCA** [comment]
I tried to use pipeline mapping:
```
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["elk.slavikf.com:9200"]

  pipelines:
  - pipeline: "filebeat-nginx-access-default"
    when.contains:
      type: "nginx"
```
Same results. It's uses it's own pipelines, not the one I'm trying to define.

debug output:
[debug.txt](https://github.com/elastic/beats/files/3818432/debug.txt)

**Comment by consulthys** [comment]
Can you try to set `filebeat.overwrite_pipelines: true` in the global options in `filebeat.yml`?

**Comment by SlavikCA** [comment]
Config:
```
filebeat.overwrite_pipelines: true
output.elasticsearch:
  hosts: ["elk.slavikf.com:9200"]

  pipeline: 'filebeat-nginx-access-default'
  pipelines:
  - pipeline: "filebeat-nginx-access-default"
    when.contains:
      type: "nginx"
```
In the log I can see, that pipeline gets recreated (overwritten) now, but it still uses it's own predefined name `filebeat-7.4.2-nginx-access-default`, not the one I specified in the config.

Log:
[debug_overwrite.txt](https://github.com/elastic/beats/files/3818488/debug_overwrite.txt)

**Comment by SlavikCA** [comment]
The issue still exists: you still can't specify pipeline for module

**Comment by TeTeHacko** [comment]
There is no other solution than owerwriting pipelines after every update? Can anyone from elastic team please look at it and explain to us how to use custom pipelines and not the default ones? I think this is a big issue if you are using custom log format.

**Comment by jpuris** [comment]
Found this as I have similar issue.. we are trying to use a custom pipeline for `service.type : "postgresql"`, not the one that comes with filebeat module.

**Comment by jpuris** [comment]
Seems to be not a problem with Filebeat 7.10.2 and Ubuntu 20.04 LTS
```
filebeat version 7.10.2 (amd64), libbeat 7.10.2 [aacf9ecd9c494aa0908f61fbca82c906b16562a8 built 2021-01-12 23:11:24 +0000 UTC]
```

Enabled modules
```
# filebeat modules list
Enabled:
postgresql
```

`/etc/filebeat/filebeat.yml`
```
output.elasticsearch:
  hosts: ["redacted:9200","redacted:9200","redacted:9200"]
  protocol: "https"
  ssl.certificate_authorities: ["redacted"]
  username: redacted
  password: redacted
  loadbalance: true
  pipelines:
    - pipeline: "postgresql-log-pipeline"
      when.contains:
        type: "postgresql"
```

Ingest pipeline GET /_ingest/pipeline/postgresql-log-pipeline
```
{
    "postgresql-log-pipeline": {
        "description": "Pipeline for parsing PostgreSQL logs.",
        "processors": [
        ...
        ],
...
}
```

**Comment by afeno** [comment]
I see after more than 1 year this issue was marked as a "bug". Does it means that someone will have a look and try to fix it?
What can we use as a workaround? Can someone help me to find a temporarily solution until this bug is fixed?

**Comment by jpuris** [comment]
@afeno I was not able to reproduce this issue when I was working on postgresql ingest pipeline. Please see https://github.com/elastic/beats/issues/14348#issuecomment-770358979 for more detail.

What version of beats are you using?

**Comment by ScubaDrew** [comment]
We are also having this issue when using the suggested:

```
pipelines:
    - pipeline: "mongodb-log-pipeline"
      when.contains:
        type: "mongodb"
```

`2021-07-14T17:58:43.900Z	INFO	[modules]	fileset/pipelines.go:133	Elasticsearch pipeline loaded.	{"pipeline": "filebeat-7.13.3-mongodb-log-pipeline"}`

**Comment by jamiejackson** [comment]
@jpuris , which version(s) of beats is this supposed to work with?  Also, do you have tips for getting insight into which pipeline is actually being used? (Logs, some other forensics, or whatever?)

I'm using Filebeat 6.8.12 with the following config file (in an attempt to process logs that have an x-forwarded-for header instead of the remote host IP).

As far as I can tell, the pipeline specification isn't being respected. (You can ignore the extraneous bits, since the rest seems to work, but I also wouldn't mind if you have tangential notes about the rest of it.)

```yaml
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.modules:
  - module: apache2
    access:
      enabled: true
      var.paths: ["/var/log/apache2/custom_access*"]
    error:
      enabled: true
      var.paths: ["/var/log/apache2/custom_error*"]

filebeat.config.modules:
  reload.enabled: true
  reload.period: 5s

fields:
  docker:
    node_hostname: ${DOCKER_NODE_HOSTNAME}
    node_id: ${DOCKER_NODE_ID}
    service_id: ${DOCKER_SERVICE_ID}
    service_labels: "${DOCKER_SERVICE_LABELS}"
    service_name: ${DOCKER_SERVICE_NAME}
    task_name: ${DOCKER_TASK_NAME}
    task_slot: ${DOCKER_TASK_SLOT}

output.elasticsearch:
  # note the versions at the end, which help us separate indices if we have a
  #  breaking change to beat version (bv) or our own version (mv, which means
  #  monthly version).
  index: filebeat-web~%{[fields.docker.service_name]}~%{+yyyy.MM}~bv%{[beat.version]}~mv1.0
  hosts: ["${ELASTICSEARCH_URL}"]
  # use custom pipeline (with a namespaced suffix for the given environment)
  pipelines:
    - pipeline: "apache_with_optional_x_forwarded_for_${DOCKER_SERVICE_NAME}"
      when.contains:
        type: "apache2"

# todo: setup.template needs to be set up if you have a custom index name
#  which we do. i don't know why this is and the following is just a guess as
#  to what's appropriate.
setup.template:
  name: 'filebeat'
  pattern: 'filebeat-*'
  enabled: true
```
