### ISSUE TITLE
[libbeat] Duplicate keys in YAML config file should be considered errors

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#14358]
If a user accidentally re-states a given key in the beats config, the beat will only consider the last entry. In the config below for example, the first statement gets obliterated. This should be an invalid config file instead, to give the user warning.

```yaml
processors:
  - add_observer_metadata:
      geo:
        name: my-name


processors:
  - add_observer_metadata:
```

Originally from https://github.com/elastic/beats/issues/14049.

**Comment by philippkahr** [comment]
Hi @andrewvc 
hmm, that is gonna be an issue when you are using the add fields processor for private IP address enrichment such as

```yaml
  - add_fields:
    when.network.source.ip: 10.1.0.0/16
    fields:
      source.geo.location:
        lat: 5.377502
        lon: 8.872831
    target: ''
  - add_fields:
    when.network.source.ip: 10.2.0.0/16
    fields:
      source.geo.location:
        lat: 10.377502
        lon: 18.872831
    target: ''
```

That would resolve in an issue, right? <https://www.elastic.co/guide/en/siem/guide/current/conf-map-ui.html#private-network>
