### ISSUE TITLE
[Metricbeat] Cloudwatch metricset config doesn't work with both name and dimensions

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#14376]
With 7.4 Metricbeat, if I run cloudwatch metricset with specified metric names(more than one name) and dimensions, only one specified metric name will be collected. For example, with `aws.yml`:
```
- module: aws
  period: 300s
  metricsets:
    - cloudwatch
  credential_profile_name: test-mb
  metrics:
    - namespace: AWS/RDS
      name: ["CPUUtilization", "FreeableMemory"]
      dimensions:
        - name: DBInstanceIdentifier
          value: database-1
      statistic: ["Average", "Maximum"]
```
Only `FreeableMemory` metric will be collected but not `CPUUtilization` for database-1. 

Workaround for this is to separate the metric names into two parts of the config:
```
- module: aws
  period: 300s
  metricsets:
    - cloudwatch
  credential_profile_name: test-mb
  metrics:
    - namespace: AWS/RDS
      name: ["FreeableMemory"]
      dimensions:
        - name: DBInstanceIdentifier
          value: database-1
      statistic: ["Average", "Maximum"]
    - namespace: AWS/RDS
      name: ["CPUUtilization"]
      dimensions:
        - name: DBInstanceIdentifier
          value: database-1
      statistic: ["Average", "Maximum"]
```
