### ISSUE TITLE
YUM install filebeat,log configuration is not in iffect

### ISSUE THREAD

**Issue by GounGG** [elastic/beats#14386]
filebeat.yml
```yaml
#================================ Logging ======================================

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 1
  permissions: 0640
```

For confirmed bugs, please report:
- Version:  7.3.1

manually create `/var/log/filebeat`，startup filebeat server，no log file。
