### ISSUE TITLE
[Agent] Specify API Key for Elasticsearch output menaged by the Agent.

### ISSUE THREAD

**Issue by ph** [elastic/beats#14485]
## Context

Our Elasticsearch client in libbeat now support specifying an `api_key` as the authentification mechanism. This feature is exposed for both the `monitoring.elasticsearch` and the `output.elasticsearch` and was implemented in elastic/beats#14320 

This means the following configurations now works for beats:

```
monitoring.elasticsearch:
  api_key: TiNAGG4BaaMdaH1tRfuU:KnR6yE41RrSowb0kQ0HWoA
```

```
output.elasticsearch:
  api_key: TiNAGG4BaaMdaH1tRfuU:KnR6yE41RrSowb0kQ0HWoA
```
## Scenario under the agent

When the agent enrolls itself to Fleet it will receive an `API_KEY`, this **key** serves two purposes:

- It allows the agent to authenticate itself to the Fleet API and executes rest calls. 
- The key is also an [Elasticsearch API Key](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html) and can be used to authenticate the agent or any controlled process to connect to Elasticsearch and send their data.

## Expected behavior for the agent

The agent receives the configuration from Fleet, if the **monitoring section** or the **elasticsearch output** section of the configuration doesn't have any defined `api_key` we assume that the agent will use his key as the default authentication key for both monitoring and output.

When the **api_key** is present for either the output or the monitoring section, we will use this specific key.

**Example:** Use default Agent's API Key
```yaml
output.elasticsearch:
  hosts: ["localhost:9200"]
  compression_level: 0
  path: "/"
```

**Example:** Use Elasticsearch output specific key.
```yaml
output.elasticsearch:
  api_key: TiNAGG4BaaMdaH1tRfuU:KnR6yE41RrSowb0kQ0HWoA
  hosts: ["localhost:9200"]

```

## Note

Note that **API KEY* are not static and be changed when permissions changes or we need to send events to a new index, see Fleet [specs](https://github.com/elastic/kibana/tree/feature-make-it-ingest/x-pack/legacy/plugins/fleet/dev_docs/api) for details.
