### ISSUE TITLE
Prometheus collector fails against WildFly 18

### ISSUE THREAD

**Issue by rdicroce** [elastic/beats#14513]
Metricbeat's Prometheus collector doesn't work with WildFly 18's metrics subsystem. I get an error saying "Unable to decode response from prometheus endpoint" and am not sure what causes it. The response looks correct, and enabling debug logging in Metricbeat hasn't provided any additional information.

Version: Metricbeat 7.4.2
Operating System: Ubuntu Server 18.0.3 LTS and Windows 10 1903
Discuss Forum URL: https://discuss.elastic.co/t/prometheus-module-doesnt-work-with-wildfly-18/207559
Steps to Reproduce: 
1. Download WildFly 18. Start it using the standard configuration by running bin/standalone.bat (or standalone.sh if you're on Linux) with no arguments.
2. Create this Metricbeat module:
```
- module: prometheus
  period: 10s
  hosts:
  - 'localhost:9990'
  metrics_path: /metrics
```
3. Execute 'metricbeat test modules'
