### ISSUE TITLE
Suricata Module and DNS Processor / Breaking changes

### ISSUE THREAD

**Issue by 0xtf** [elastic/beats#14528]
Hi,

It seems something might have changed in the Suricata module that ended up breaking a configuration that was dependent on certain fields. 

Previously, the DNS processor had to be configured as:

```
processors:
- add_fields:
    fields:
      processor: working
- dns:
    type: reverse
    action: append
    fields:
      json.src_ip: source.hostname
      json.dest_ip: destination.hostname
...
```
It seems the original name that was being used have changed, even though I can't figure out what the underlying field name is. Also, looking just at the transformation for ECS probably won't help, as I believe the processor acts before ECS transformation. 

For confirmed bugs, please report:
- Version: Cloud 7.4
- Operating System: Cloud / Ubuntu 18.04 on Filebeat machine
- Steps to Reproduce: 
  - Import Suricata module
  - Configure DNS Processor on host
