### ISSUE TITLE
filebeat not working 

### ISSUE THREAD

**Issue by GSL10019** [elastic/beats#1453]
```
filebeat:
  prospectors:
    -
      paths:
        - C:\Users\qa1\Desktop\logs
        - C:\Users\qa1\Desktop\*.logs
      document_type: logs
      input_type: logs
    -
      paths:
		    - "C:\Users\qa1\Desktop\*.logs"
      document_type: logs
  registry_file: "C:/ProgramData/filebeat/registry"
output:
  logstash:
    hosts: ["localhost:5044"]
shipper:

logging:
  files:
    rotateeverybytes: 10485760
```

it worked but not it does not, i am on 1.1.1 fb and when it did work nothing showed up on kibana which i am currently running 4.4.1. Are the versions not compatible?
