### ISSUE TITLE
Add Windows Authentication to Metricbeats MSSQL module

### ISSUE THREAD

**Issue by ErnestoBezanilla** [elastic/beats#14585]
**Describe the enhancement:**

Currently you can connect it using SQL authentication 

```
- module: mssql
  metricsets:
    - "transaction_log"
    - "performance"
  hosts: ["sqlserver://username:password@localhost"]
  period: 10s
```
or using AD credentials in the metricbeat.yml

```
- module: mssql
  metricsets:
    - "transaction_log"
    - "performance"
  hosts: ["sqlserver://localhost"]
  username: domain\username
  password: password
  period: 10s
```
the request is to add support for Windows Authentication so it grabs the credentials from:
1 - the user currently logged on to Windows (if Metribeat is run via command line), or 
2 - the user the Metricbeat Windows Service account is running under

without the need to add the username/password in the metribeat.yml or in the keystore

**Comment by kbering** [comment]
Running metricbeat 7.9.2 on the SQL server, and using the mssql module without specifying an account then the calling account is used.

Config
```
- module: mssql
  metricsets:
    - "transaction_log"
    - "performance"
  hosts: ["sqlserver://localhost"]
  #username: domain\username
  #password: verysecurepassword
  period: 10s
```
So I think this issue can be closed

**Comment by ManojS-shetty** [comment]
Using the mssql module without specifying an account then the calling account is used.

Config
```
- module: mssql
  metricsets:
    - "transaction_log"
    - "performance"
  hosts: ["sqlserver://localhost"]
  #username: domain\username
  #password: verysecurepassword
  period: 10s
```

Hence closing this issue.
