### ISSUE TITLE
[Filebeat] tail_files option doesn't seem to work as specified

### ISSUE THREAD

**Issue by geoffroya** [elastic/beats#1458]
Hi all.

I'm setting up filebeat, and I encounter issues with the ```tail_files``` option: it doesn't work as expected.
Instead of starting from the end of each log file, it starts from the beginning.

I wanted to do as described [here](https://discuss.elastic.co/t/filebeat-needs-to-be-restarted-in-order-to-send-logs-to-logstash-dynamically/39994), ie:
- 1st start with ```tail_files: true```
- Restart filebeat with ```tail_files: false``` (once it saved the current offset of each file).

But with my config, it just starts from the beginning of each file.

I used filebeat 1.2.1 on Ubtuntt 14.04 LTS, and my config is as follows:

Main config file ```/etc/filebeat/filebeat.yml```:

```YAML
filebeat:
  prospectors:
    -

  registry_file: /var/lib/filebeat/registry
  config_dir: /etc/filebeat/conf.d
output:
  logstash:
    hosts: ["logstash-host:5044",]
    worker: 2
    loadbalance: true
shipper:
logging:
  files:
    path: /var/log/filebeat
    name: filebeat.log
    rotateeverybytes: 10485760 # = 10MB
  level: warning
```

In ```/etc/filebeat/conf.d```, I have 1 conf file per domain. Here's 1 example:

```YAML
filebeat:
  prospectors:
    -
      paths:
        - "/var/log/apache2/access.log"
      input_type: log
      fields:
        format: "APACHE"
        application: "Appli1"
        index: "logs"
        kafka_topic: "logs"
      fields_under_root: true
      document_type: Apache
      tail_files: true
``` 

So the ```tail_files``` option is set in the "child" config files. Could this impact the behaviour?

Best regards

Geoff
