### ISSUE TITLE
Strange Topbeat (v1.2.1) Performance (under Windows)

### ISSUE THREAD

**Issue by loms0815** [elastic/beats#1460]
Hi,
I have configured Topbeat with FILE output only:
Test OS is Windows 7 Enterprise and Topbeat version is v1.2.1.
```
input:
  period: 15
  procs: [".*"]
  stats:
    system: true
    process: true
    filesystem: true
    cpu_per_core: false
```
If I specify the "procs"-regex-filter with ".*", then I see no CPU consumption (great). Only every 15secs there is a short spike because of storing to file.

If I configure the "procs"-regex-filter with any other filter (e.g.  ".*Notepad.*" or "Notepad") then I got a permanent CPU consumption over 5%.

So the output of all processes is much faster than to take only one process. But I can't configure all processes because in this case the file size is growing to fast!

Can you help me overcome this issue?
