### ISSUE TITLE
Crashing 5.0.0-alpha1

### ISSUE THREAD

**Issue by LoungeFlyZ** [elastic/beats#1466]
I am hitting a problem where filebeat is crashing 5.0.0-alpha1 like this:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0xa0 pc=0x4bb6a2]
 
goroutine 25 [running]:
panic(0x9b5320, 0xc820018080)
/usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/elastic/beats/libbeat/common.ConvertToGenericEvent(0xc8204012c0, 0x7)
/go/src/github.com/elastic/beats/libbeat/common/event.go:47 +0x252
github.com/elastic/beats/libbeat/publisher.(*client).filterEvent(0xc820148bc0, 0xc8204012c0, 0xc820026e20)
/go/src/github.com/elastic/beats/libbeat/publisher/client.go:184 +0x30
github.com/elastic/beats/libbeat/publisher.(*client).PublishEvents(0xc820148bc0, 0xc8203c0c00, 0x7d, 0x7d, 0xc820419490, 0x2, 0x2, 0x0)
/go/src/github.com/elastic/beats/libbeat/publisher/client.go:134 +0xc6
github.com/elastic/beats/filebeat/beater.(*syncLogPublisher).Start.func1(0xc820149140)
/go/src/github.com/elastic/beats/filebeat/beater/publish.go:103 +0x3bb
created by github.com/elastic/beats/filebeat/beater.(*syncLogPublisher).Start
/go/src/github.com/elastic/beats/filebeat/beater/publish.go:113 +0x58
```

I am playing with 5.0.0-alpha1 for the JSON support.  I am using the same filebeat.yml file as with 1.2 *except* with the added JSON section:

```
filebeat:
  
  prospectors:
    -
      paths:
        - "logs/*.*.log.*"

      document_type: antrea
      
      json:
        message_key: message
        keys_under_root: true
        add_error_key: true
      
output:
  elasticsearch:

    hosts: ["http://REMOVED:9200"]

    username: "REMOVED"
    password: "REMOVED"

    index: "filebeat"
    
logging:
  level: debug
```

Repro'd on OSX and linux (debian:jessie)

Here are the log files i am testing this with that repro this issue:
https://dl.dropboxusercontent.com/u/27238389/logs.zip

Any ideas?
