### ISSUE TITLE
Filebeat modules: Always send message by default

### ISSUE THREAD

**Issue by exekias** [elastic/beats#14708]
Currently Kibana Logs UI needs a mechanism to rebuild the original message from events coming from Filebeat modules. This doesn't scale very well, as every time we add/update a new integration, changes need to happen on the Kibana side to support this.

For this reason, in order to provide a good experience, we can change the current behavior of modules to always send the original log line. This would mean:

- Add a new `keep_message` setting to all modules (default: `false`). If user configures it to `true`, do not drop the original message like we do today: https://github.com/elastic/beats/blob/1db397d2dc3d1b49a1923d219fb84843b8b0186d/filebeat/module/nginx/access/ingest/default.json#L77-L80

- In 8.0 switch the default to true

**Comment by exekias** [comment]
We also have `log.original` which contains the raw original log line, where `message` is the same without the initial timestamp. We need to come up with a solution that contemplates both

**Comment by weltenwort** [comment]
Prior related issues for completeness sake: #8950, #8083

**Comment by exekias** [comment]
I've done some testing, sending the NASA access logs Jul 95 and tweaking apache pipeline to allow for keeping `message` and `log.original` fields. In this example `log.original` is an exact copy of `message`, as timestamp is not located at the beginning:

```
filebeat.inputs:
  # Don't keep anything
  - type: log
    paths:
      - ./bench/NASA_access_log_Jul95.1
    index: filebeat-8.0.0-keep_nothing

  - type: log
    paths:
      - ./bench/NASA_access_log_Jul95.2
    fields:
      keep_message: true
    fields_under_root: true
    index: filebeat-8.0.0-keep_message

  - type: log
    paths:
      - ./bench/NASA_access_log_Jul95.3
    fields:
      keep_message: true
      keep_original: true
    fields_under_root: true
    index: filebeat-8.0.0-keep_all

setup.ilm.enabled: false
filebeat.overwrite_pipelines: true

setup.template.settings:
  index.number_of_shards: 1
  #index.codec: best_compression
  #_source.enabled: false

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]
  pipeline: filebeat-8.0.0-apache-access-default
```

After force merge:
```
yellow open filebeat-8.0.0-keep_all     dGQKyg4TQROa9GvSHlxYhA 1 1 1891714 0 763.5mb 763.5mb
yellow open filebeat-8.0.0-keep_nothing NJinYOw9RYip_bb0nHc_Iw 1 1 1891714 0 310.1mb 310.1mb
yellow open filebeat-8.0.0-keep_message -iL4OMRrTyaO8x9iUmV3QQ 1 1 1891714 0 406.5mb 406.5mb
```

It sounds to me that we should try to do some effort to store only one of `log.original` or `message` if possible.

@weltenwort have we considered in the past using `log.original` + perhaps an offset field that tells you were timestamp ends and the message starts? I'm talking about the general case, taking out the ones where message is actually inside some JSON field or similar.
