### ISSUE TITLE
Unable to set host header using standard HTTP options (metricbeat)

### ISSUE THREAD

**Issue by rcrawf** [elastic/beats#14907]
I'm using the prometheus metricbeat module and i'm trying to set the "Host" HTTP header for my target server. I'm using the [standard http options](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-metricbeat.html#module-http-config-options) to modify the headers. 

Here's a snippet of my config:

```
- module: prometheus
  period: 10s
  hosts: ["http://metrics-host.example.com"]
  metrics_path: /metrics
  headers:
    Host: new-host.example.com
    X-Example-Header: test
```

My expected behaviour is that the "Host" header should be overridden, however that's not happening. The test header "X-Example-Header" works as expected. 

This is a screenshot of the actual headers that come through: 

![headers](https://aws1.discourse-cdn.com/elastic/optimized/3X/9/4/945b5e799ab0b2178dd0756236f58219443ec154_2_690x194.png)

- Version: 7.4.2 
- Operating System: Docker 
- Discuss Forum URL: https://discuss.elastic.co/t/unable-to-set-host-header-using-standard-http-options/21021
- Steps to Reproduce: Reproducible with code snippet above
