### ISSUE TITLE
[Filebeat 7.6.0 module cisco] Field [raw_date] not present as part of path [_temp_.raw_date]

### ISSUE THREAD

**Issue by MarcusCaepio** [elastic/beats#14931]
Hi all,

just installed Filebeat 7.5.0 and using the cisco module. Since 7.5.0, every document got the `error.message: Field [raw_date] not present as part of path [_temp_.raw_date]`
The pipelines for cisco are available. The template was also imported.
![image](https://user-images.githubusercontent.com/7324088/70141041-6c885180-1696-11ea-9bf8-cf264ca0569e.png)

My Filebeat config looks like this:
```
Filebeat.yml
filebeat.inputs:
- type: log
  enabled: false
  paths:
    - /var/log/*.log
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.ilm.enabled: false

output.kafka:
  hosts: ["localhost:9092"]
  topic: 'filebeat'
  version: "2.0.0"
  codec.json:
    pretty: false

processors:
  - drop_fields:
      when:
        equals:
          event.module: "cisco"
      fields: ["agent.ephemeral_id","agent.hostname","agent.id","agent.type","agent.version","host.name"]

cisco.yml
- module: cisco
  asa:
    enabled: true
    var.input: syslog
    var.syslog_host: 0.0.0.0
    var.syslog_port: 9001
```
Logstash getting the logs from kafka via:
```
input {
  kafka {
    bootstrap_servers => "x.x.x.x:9092"
    topics => ["filebeat"]
    codec => json
  }
}

output {
    elasticsearch {
      hosts => "http://localhost:9200"
      manage_template => false
      pipeline => "%{[@metadata][pipeline]}"
      index => "%{[@metadata][beat]}-%{+YYYY.MM.dd}"
      ilm_enabled => false
  }
}
```

Greetings,
Marcus
