### ISSUE TITLE
[Filebeat 7.5.0 module cisco] host.name should not be the "Filebeat Agent Name"

### ISSUE THREAD

**Issue by MarcusCaepio** [elastic/beats#14933]
Hi all,
when you are using the cisco module, the host.name value is always the name of the "log collector". E.g. my cisco devices are 1.1.1.1, 1.1.2.1 and my filebeat runs on 1.1.1.2 the host.name value is always 1.1.1.2, which doesn't make sense, when using the SIEM map. Instead of this, it should be the address given in  log.source.address, as this is the device, where the log comes from.
I wrote an processor to replace the host.name with the correct ip, but it would be nice, to have this implemented in the future releases.

Regards,
Marcus

**Comment by BFLB** [comment]
Hi Marcus,
I am starting to use the CISCO module as well, mainly for IOS devices. What I would like to have is the dns name of the devices in addition or instead of the ip-address. So far I did not find a setting for this. Do you know if this can be done by the beat itself or do I need to implement it on my own?

Regards
Bernhard

**Comment by MarcusCaepio** [comment]
Hi @BFLB 
I wrote a processor in the filebeat.yml:
```
processors:
  - drop_fields:
      when:
        equals:
          event.module: "cisco"
      fields: ["agent.ephemeral_id","agent.hostname","agent.id","agent.type","agent.version","host.name"]
  - dissect:
      when:
        equals:
          event.module: "cisco"
      tokenizer: "%{address}:%{}"
      field: "log.source.address"
      target_prefix: "host"
  - dns:
      when:
        equals:
          event.module: "cisco"
      type: reverse
      fields:
        host.address: host.name
```

drop fields: delete fields, which are unnecessary (imho)
dissect: split the log.source.address, which is shown as "ip:port" into an host.address
dns: resolve host.address and save it in host.name

As I am still testing this whole processor part, I don't know, if this is the elegant or the dirty way :D

Cheers,
Marcus
