### ISSUE TITLE
Check AWS ListMetrics API call without giving namespace

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#14965]
For cloudwatch metricset, check what happens if namespace is not given when making ListMetrics API call. If we can make ListMetrics API call without giving namespace, then we can make cloudwatch metricset to collect metrics for all available resources.

**Comment by kaiyan-sheng** [comment]
@exekias  @sorantis I tried to run cloudwatch metricset with `namespace: "*"` and ListMetrics API did what we expected: it returned all metrics exists in that AWS account and was able to use to obtain statistical data. 
```
- module: aws
  period: 300s
  credential_profile_name: elastic-test
  metricsets:
    - cloudwatch
  metrics:
    - namespace: "*"
      statistic: ["Average"]
```

Here is what cloudwatch metricset collected:
<img width="1314" alt="Screen Shot 2019-12-05 at 1 42 46 PM" src="https://user-images.githubusercontent.com/14081635/70272524-9f4d4b00-1765-11ea-9310-69eb421edf5d.png">

The problem is: `statistic` and `period` are defined for all metrics. For example, AWS/Usage metrics should be collected every 1 minute instead of every 5 minutes(data loss in this case). Also some metrics like AWS/Billing, should be collected every 6 hours or 12 hours instead of every 5 minutes(introduced extra cost in this case).
