### ISSUE TITLE
Update aws.yml for enabling all metricsets by default

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#14964]
For AWS module, enable all metricsets by default in the aws.yml config. This will improve user experience when services user wants to monitor in the AWS account is unknown. 

Maybe the new aws.yml file should look like:
```
- module: aws
  period: 300s
  metricsets:
    - ec2
    - rds
    - elb
    - ebs
    - sqs
- module: aws
  period: 86400s
  metricsets:
    - s3_request
    - s3_daily_storage
```
