### ISSUE TITLE
[Filebeat] Shipped monitoring events are invisible to Monitoring UI when switching from deprecated xpack.monitoring.* to monitoring.* configs if the cluster_uuid isn't correctly set

### ISSUE THREAD

**Issue by geekpete** [elastic/beats#14972]
This probably affects all beats if the monitoring code is shared.
I've reproduced it with:
- Filebeat 7.4.2
- Filebeat 7.5.0
- Metricbeat 7.5.0

Using a Beats -> Logstash -> Elasticsearch config where Beats is shipping monitoring data to a separate monitoring cluster, then if switching from `xpack.monitoring.*` configs to `monitoring.*` configs and not using the required/mandatory `cluster_uuid` monitoring setting then monitoring events will be shipped with a null value for `cluster_uuid` field and will be invisible to the Monitoring UI.

For confirmed bugs, please report:
- Version: Filebeat 7.4.2, Filebeat 7.5.0, Metricbeat 7.5.0
- Operating System: OpenSUSE Tumbleweed
- Discuss Forum URL:
- Steps to Reproduce: 

Run up a stack with:

Beats --> Logstash --> Elasticsearch and a separate monitoring cluster for Beats to ship to.

Set up a monitoring cluster with monitoring enabled and creds for Beats to ship monitoring events with.

So beats shipping events to Logstash which then outputs to Elasticsearch.
Have Beats internal collection for monitoring going to a separate monitoring cluster.
Start with the 6.x style configurations using `xpack.monitoring.*` as you might have after doing a major upgrade like:

```yaml
xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["https://whateverhost1.gcp.elastic-cloud.com:9243"]
    username: elastic
    password: whateverpassword
```

With this config events should still come through to the monitoring cluster as expected.

Users who might note the WARN in the Beats logs for the deprecated setting:

`2019-12-05T18:50:13.305+1000    WARN    [cfgwarn]       monitoring/monitoring.go:95     DEPRECATED: xpack.monitoring.* settings are deprecated. Use monitoring.* instead, but set monitoring.elasticsearch.hosts to monitoring cluster hosts. Will be removed in version: 8.0`

might then go to tweak the config to remove the `xpack.` prefix and use the new config setting of `monitoring.*` to avoid the deprecation:

```yaml
xpack.monitoring:
  enabled: true
  elasticsearch:
    hosts: ["https://whateverhost1.gcp.elastic-cloud.com:9243"]
    username: elastic
    password: whateverpassword
```
If the new `cluster_uuid` is omitted then it will appear as though no monitoring events are coming through when looking back at the Monitoring UI in Kibana.

What's actually occurring is that with the old setting a default value of the target cluster's UUID is being set for the `cluster_uuid` field. When using the new configuration the `cluster_uuid` configuration is expected and if not set causes this field to be set to null by default.
There's no error or warning in the Beats logs and this appears to fail silently to the user.

When using the new settings, the `cluster_uuid` config becomes mandatory, which is documented but seemingly not enforced by Beats.
https://www.elastic.co/guide/en/beats/filebeat/7.5/monitoring-internal-collection.html

 >"If you configured a different output, such as Logstash or you want to send Filebeat monitoring events to a separate Elasticsearch cluster (referred to as the monitoring cluster), you must specify additional configuration options. "

and

 >"This setting identifies the Elasticsearch cluster under which the monitoring data for this Filebeat instance will appear in the Stack Monitoring UI. To get a cluster’s cluster_uuid, call the GET / API against that cluster."

So while we do document it, it's still not a great user experience for this to feel like it's failing silently.

Workarounds are to revert to the previous config of `xpack.monitoring.*` to get the automatically assigned value to the `cluster_uuid` field or to correctly set this field value to the UUID of the target monitoring cluster.

Also to note, if users accidentally set the UUID to their production cluster UUID then the events will also not appear in the monitoring cluster.

For events already indexed, you can update them to use the correct UUID and have those events then appear in the Monitoring UI:

```java
# You might do a count of how many there are first with:
GET /.monitoring-beats-*/_search
{
  "query": {
    "bool": {
      "must_not": [
        {
          "exists": {
            "field": "cluster_uuid"
          }
        }
      ]
    }
  },
  "size": 0
}
```

then to fix them by setting the correct UUID you could use:

```java
# update all the docs missing the cluster_uuid field with the desired UUID
POST /.monitoring-beats-*/_update_by_query
{
  "script": {
    "source": "ctx._source['cluster_uuid'] = 'lNrLs_vSRSuqWC-Sb0kYnQ'",
    "lang": "painless"
  },
  "query": {
    "bool": {
      "must_not": [
        {
          "exists": {
            "field": "cluster_uuid"
          }
        }
      ]
    }
  }
}
```

adjusting the example `lNrLs_vSRSuqWC-Sb0kYnQ` UUID to the desired one.

The fix might be either using the previous behaviour to automatically set the UUID to the target cluster's UUID or to have beats enforce this new mandatory setting.

**Comment by ycombinator** [comment]
Hi @geekpete, I think there is some confusion here about the old (`xpack.monitoring.*`) and the new `(monitoring.*`) settings. 

With the old settings (`xpack.monitoring.*`), `xpack.monitoring.elasticsearch.hosts` must point to the user's **production** Elasticsearch cluster. This will cause the Beat to collect monitoring data internally and ship it to the **production** Elasticsearch cluster, which will then forward (aka export) it to the **monitoring** Elasticsearch cluster.

With the new settings (`monitoring.*`), `monitoring.elasticsearch.hosts` must point to the user's **monitoring** Elasticsearch cluster. This will cause the Beat to collect monitoring data internally and ship it _directly_ to the **monitoring** Elasticsearch cluster. Now, in this scenario, as you've noted, the `cluster_uuid` will be absent in the Beat's monitoring docs if the Beat is using an output other than Elasticsearch (so, e.g. `output.logstash.enabled: true`). Consequently the Beat's monitoring data will show up under a "Standalone" cluster in the Stack Monitoring UI. To make the Beat's monitoring data show up under their production cluster in the Stack Monitoring UI again as it was when using the old `xpack.monitoring.*` settings, users must now also set `monitoring.cluster_uuid` to their **production** cluster's UUID in their Beat's configuration.

**Comment by abraxxa** [comment]
I have one more issue to add: when switching to external monitoring by Metricbeat the cluster_uuid field in Elasticsearch ends up being present but an empty string: `"cluster_uuid" : ""`

Metricbeat has its Elasticsearch output enabled and only its credentials are overridden in the monitoring.elasticsearch section of the config file. Metricbeat uses the internal monitoring which sets the cluster_uuid correctly, only the beat-xpack module which monitors Filebeat doesn't.

I tried both setting monitoring.cluster_uuid in metricbeat.yml as well as filebeat.yml, doesn't change a thing.

**Comment by ycombinator** [comment]
@abraxxa, just want to clarify a couple of things:
- You're using Metricbeat to monitor Filebeat via the `beat-xpack` Metricbeat module? Can you post your `filebeat.yml`, `metricbeat.yml`, and `modules.d/beat-xpack.yml` here, after redacting any sensitive information?
- What versions of Metricbeat, Filebeat, and Elasticsearch (the one configured in `output.elasticsearch` in your `metricbeat.yml`) are you running?

**Comment by abraxxa** [comment]
The versions are 7.6.0.

filebeat.yml:
```
filebeat.inputs:
- type: log
  enabled: false
  paths:
    - /var/log/*.log
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
filebeat.config.inputs:
  enabled: true
  path: inputs.d/*.yml
setup.template.enabled: false
setup.kibana:
output.logstash:
  enabled: true
  hosts: ["fqdn1:5044", "fqdn2:5044", "fqdn3:5044"]
  ssl.certificate_authorities: ["/etc/ssl/certs/Our_CA.pem"]
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - drop_fields:
      fields: ["beat", "prospector", "offset", "source", "@timestamp", "host", "input.type", "log", "agent", "ecs"]
monitoring.enabled: false
http.enabled: true
```

metricbeat.yml
```
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
setup.kibana:
output.elasticsearch:
  enabled: true
  hosts: ["https://fqdn1:9200", "https://fqdn2:9200", "https://fqdn3:9200"]
  ssl.certificate_authorities: ["/etc/ssl/certs/Our_CA.pem"]
  username: "metricbeat"
  password: "foobar"
output.logstash:
  enabled: false
monitoring:
  enabled: true
  elasticsearch:
    username: "beats_system"
    password: "foobar"
```

beat-xpack.yml
```
- module: beat
  metricsets:
    - stats
    - state
  period: 10s
  hosts: ["http://localhost:5066"]
  #username: "user"
  #password: "secret"
  xpack.enabled: true
```

**Comment by MacPower** [comment]
Hi, 

I have exactly the same problem here. 

I use Metricbeat to monitor Filebeat and Logstash and then send monitoring data to ES with Logstash. Do not judge the architecture, it's for testing only :) 


Filebeat ---> Metricbeat ---> Logstash ---> ES <--- Kibana UI 
Metricbeat---^              ^---------------^

filebeat.yml:
```
#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

filebeat.config.modules:
  path: /etc/filebeat/modules.d/*.yml
  reload.enabled: true

filebeat.modules:

- module: logstash
  # logs
  log:
    enabled: true

    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:

  # Slow logs
  slowlog:
   enabled: true
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    #var.paths:

#============================== Metricbeat Monitoring ==========================

http.enabled: true
http.port: 5066
monitoring.enabled: false
monitoring.cluster_uuid: myclusterid

#============================== Logstash Ouput ==========================

output.logstash:
  hosts: ["127.0.0.1:5044"]
```

metricbeat.yml 

```
metricbeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

metricbeat.modules:
- module: logstash
  metricsets:
    - node
    - node_stats
  period: 10s
  hosts: ["localhost:9600"]
  #username: "user"
  #password: "secret"
  xpack.enabled: true
- module: beat
  metricsets:
    - stats
    - state
  period: 10s
  hosts:
    - "http://localhost:5066" # Filebeat 
    - "http://localhost:5067" # Metricbeat
  #username: "user"
  #password: "secret"
  xpack.enabled: true
 
#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

#============================== Metricbeat Monitoring ==========================
# Self monitoring through beat module

http.enabled: true
http.port: 5067 
monitoring.enabled: false
monitoring.cluster_uuid: mycluster_id

  #============================== Logstash Ouput ==========================

output.logstash:
  hosts: ["127.0.0.1:5044"]

```

logstash-beats.conf
```
input {
  beats {
       id => "beatsmon"
       port => 5044
       host => "127.0.0.1"
  }
}

filter {
  # Boilerplate for compatibility across Beats versions
  mutate {
    rename => { "[@metadata][id]" => "[@metadata][_id]" }
  }
}
output {
     if [@metadata][index] =~ /^.monitoring-*/ {
     # route stack monitoring data to monitoring Elasticsearch cluster
          if [@metadata][_id] {
               elasticsearch {
                    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
                    cacert => "/etc/logstash/ca.pem"
                    hosts => ["*****"]
                    user => "${lg_ingest_user}"
                    password => "${lg_ingest_password}"
                    ssl_certificate_verification => false
               }
          } else {
               elasticsearch{
                    id => "stack_monitoring"
                    index => "%{[@metadata][index]}-%{+YYYY.MM.dd}"
                    cacert => "/etc/logstash/ca.pem"
                    hosts => ["*******"]
                    user => "${lg_ingest_user}"
                    password => "${lg_ingest_password}"
                    ssl_certificate_verification => false
               }
          }
    } else {
          rabbitmq {
               *** REDACTED ***

          }
     }
}
```

When this configuration is apply, the logstash xpack monitoring feature is working as expected but not beat xpack feature. Indeed, when looking in .moniotoring-mb-7-* index I can see that there is no cluster_uuid for the beat-xpack module metric. 
Those metrics are then in the Standalone cluster section... 

To solve this I added `cluster_uuid` to the event manually in the logstash filter : 
```
filter {
      mutate {
        replace => { "cluster_uuid" => "_rb-hsVySOCfDj6gPW5dnw" }
      }
}

```

Now every metrics could be seen in the right cluster section 👍 

I hope it helps :)
