### ISSUE TITLE
metricbeat. elasticsearch-xpack module failed to start.

### ISSUE THREAD

**Issue by gray380** [elastic/beats#14984]
Hi,

I've tried to implement cluster monitoring according this [manual](https://www.elastic.co/guide/en/elasticsearch/reference/7.5/configuring-metricbeat.html).

Collection settings:
```
$ curl -k -X GET https://elk-es-00-int:9200/_cluster/settings?pretty
{
  "persistent" : {
    "xpack" : {
      "monitoring" : {
        "elasticsearch" : {
          "collection" : {
            "enabled" : "false"
          }
        },
        "collection" : {
          "enabled" : "true"
        }
      }
    }
  },
  "transient" : { }
}
```
metricbeat version:
```
$ metricbeat version
metricbeat version 7.5.0 (amd64), libbeat 7.5.0 [6d0d0ae079e5cb1d4f224801ac6df926dfb1594c built 2019-11-26 00:09:41 +0000 UTC]
```
enabled modules:
```
$ sudo metricbeat modules list
Enabled:
elasticsearch-xpack
```
/etc/metricbeat/modules.d/elasticsearch-xpack.yml:
```
- module: elasticsearch
  metricsets:
    - ccr
    - cluster_stats
    - index
    - index_recovery
    - index_summary
    - ml_job
    - node_stats
    - shard
  period: 10s
  hosts: ["https://elk-es-02-int:9200"]
  username: "remote_monitoring_user"
  password: "SuperPassword"
  xpack.enabled: true
```
faced error:
```
Dec 06 14:42:14 elk-es-02 metricbeat[4294]: 2019-12-06T14:42:14.148+0200        ERROR        instance/beat.go:916        Exiting: The elasticsearch module with xpack.enabled: true must have metricsets: [ccr enrich cluster_stats index index_recovery index_summary ml_job node_stats shard]
Dec 06 14:42:14 elk-es-02 metricbeat[4294]: Exiting: The elasticsearch module with xpack.enabled: true must have metricsets: [ccr enrich cluster_stats index index_recovery index_summary ml_job node_stats shard]
```

**Comment by kaiyan-sheng** [comment]
Hmm seems like you are missing `enrich` metricset?
```
- module: elasticsearch
  metricsets:
    - ccr
    - cluster_stats
    - enrich
    - index
    - index_recovery
    - index_summary
    - ml_job
    - node_stats
    - shard
  period: 10s
  hosts: ["https://elk-es-02-int:9200"]
  username: "remote_monitoring_user"
  password: "SuperPassword"
  xpack.enabled: true
```
