### ISSUE TITLE
[Metricbeat] Kubernetes Autodiscover Control Plane Static Pods (etcd, controller, scheduler)

### ISSUE THREAD

**Issue by mitchellmaler** [elastic/beats#14997]
I have setup a metricbeat in kubernetes for kube-state-metrics, api server, events, and the rest using using autodiscover. The issue is only CoreDNS is resolved and not the static pods of the control plane like etcd, scheduler, controller manager. 

The biggest difference between CoreDNS and the others is coredns is just a deployment/replicaset pod where the others are all static pod manifests deployed by the kubelet. I can lookup these pods using the label selector and namespace in the conditions using kubectl.

```bash
$ kubectl get pods -n kube-system -l component=etcd,tier=control-plane
NAME                               READY   STATUS    RESTARTS   AGE
etcd-asc-local-k8s-control-plane   1/1     Running   0          17m
```
Here is my setup for the autodiscover:

```yaml
metricbeat.autodiscover:
      providers:
        - type: kubernetes
          templates:
            # CoreDNS Discovery (Works)
            - condition:
                contains:
                  kubernetes.labels.k8s-app: kube-dns
                  kubernetes.namespace: kube-system
              config:
                - module: coredns
                  metricsets:
                    - stats
                  period: 10s
                  hosts: "${data.host}:9153"
                  processors:
                    - add_kubernetes_metadata:
                        in_cluster: true
            # ETCD Discovery (Not Found)
            - condition:
                contains:
                  kubernetes.labels.component: etcd
                  kubernetes.labels.tier: control-plane
                  kubernetes.namespace: kube-system
              config:
                - module: etcd
                  metricsets:
                    - leader
                    - self
                    - store
                  period: 10s
                  hosts: "${data.host}:2379"
                  #TODO: SSL AUTH
                  processors:
                    - add_kubernetes_metadata:
                        in_cluster: true
            # Controller Manager Discovery (Not Found)
            - condition:
                contains:
                  kubernetes.labels.component: kube-controller-manager
                  kubernetes.labels.tier: control-plane
                  kubernetes.namespace: kube-system
              config:
                - module: kubernetes
                  metricsets:
                    - controllermanager
                  period: 10s
                  hosts: "${data.host}:10252"
                  processors:
                    - add_kubernetes_metadata:
                        in_cluster: true
            # Scheduler Discovery (Not Found)
            - condition:
                contains:
                  kubernetes.labels.component: kube-scheduler
                  kubernetes.labels.tier: control-plane
                  kubernetes.namespace: kube-system
              config:
                - module: kubernetes
                  metricsets:
                    - scheduler
                  period: 10s
                  hosts: "${data.host}:10251"
                  processors:
                    - add_kubernetes_metadata:
                        in_cluster: true
```

```json
{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":16200,"time":{"ms":499}},"total":{"ticks":67040,"time":{"ms":2187},"value":67040},"user":{"ticks":50840,"time":{"ms":1688}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":21},"info":{"ephemeral_id":"c52fd06d-d717-4025-885e-a6d825e2926b","uptime":{"ms":990177}},"memstats":{"gc_next":38730240,"memory_alloc":27746464,"memory_total":8512874904},"runtime":{"goroutines":186}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"acked":3408,"batches":75,"total":3408},"read":{"bytes":796550},"write":{"bytes":3539626}},"pipeline":{"clients":5,"events":{"active":0,"published":3408,"total":3408},"queue":{"acked":3408}}},"metricbeat":{"coredns":{"stats":{"events":72,"success":72}},"kubernetes":{"apiserver":{"events":3144,"success":3144},"state_container":{"events":66,"success":66},"state_deployment":{"events":18,"success":18},"state_node":{"events":9,"success":9},"state_pod":{"events":66,"success":66},"state_replicaset":{"events":27,"success":27},"state_statefulset":{"events":6,"success":6}}},"system":{"load":{"1":0.61,"15":1.65,"5":1.34,"norm":{"1":0.1525,"15":0.4125,"5":0.335}}}}}}
```

For confirmed bugs, please report:
- Version: 7.5.0
- Operating System: 
- Discuss Forum URL:
- Steps to Reproduce:

**Comment by mitchellmaler** [comment]
After manually adding them to be processed not using autodiscover the metrics are being pulled in. The next issue I am seeing is the kubernetes metadata is not being applied to those three. Even though they are running as a pod. I have the add_metadata: true and the add_kubernetes_metadata processor. 

Looks like an issue with discovering information about static pods.

**Comment by exekias** [comment]
Thank you for opening this! Problem with discovering static pods through autodiscover is that they are not offered by the API server on Pods watch. Any ideas here @odacremolbap @ChrsMark @vjsamuel ?

**Comment by ChrsMark** [comment]
> Thank you for opening this! Problem with discovering static pods through autodiscover is that they are not offered by the API server on Pods watch. Any ideas here @odacremolbap @ChrsMark @vjsamuel ?

Given that fact, a possible solution here would be to add a second resource in autodiscover to watch for static pods creation?

**Comment by ChrsMark** [comment]
@michael-chiosi hey!

I tried to reproduce the issue with static pods. Here is the static pod I deploy:
```
$ cat /etc/kubernetes/manifests/static-nats.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nats-static
  labels:
    role: main
    app: nats-static
  annotations:
    co.elastic.metrics/module: nats
    co.elastic.metrics/metricsets: stats
    co.elastic.metrics/hosts: '${data.host}:8222'
spec:
  containers:
    - name: natsqueuestatic
      image: nats
      command: ["/nats-server"]
      args: ["-m", "8222"]
      ports:
        - name: web
          containerPort: 8222
          protocol: TCP
```

Watching the Metricbeat's logs I can see that the Pod is discovered by autodiscover:
```
2019-12-18T09:56:30.389Z	DEBUG	[autodiscover]	kubernetes/kubernetes.go:136	Watcher Pod add: &Pod{ObjectMeta:k8s_io_apimachinery_pkg_apis_meta_v1.ObjectMeta{Name:nats-static-minikube,GenerateName:,Namespace:default,SelfLink:/api/v1/namespaces/default/pods/nats-static-minikube,UID:daea330f-6b69-44b5-b4da-fc5fb2c146b0,ResourceVersion:20613,Generation:0,CreationTimestamp:2019-12-18 09:56:30 +0000 UTC,DeletionTimestamp:<nil>,DeletionGracePeriodSeconds:nil,Labels:map[string]string{app: nats-static,role: main,},Annotations:map[string]string{co.elastic.metrics/hosts: ${data.host}:8222,co.elastic.metrics/metricsets: stats,co.elastic.metrics/module: nats,kubernetes.io/config.hash: a9617ba0d0eea41836dbfc8ce0c51fe1,kubernetes.io/config.mirror: a9617ba0d0eea41836dbfc8ce0c51fe1,kubernetes.io/config.seen: 2019-12-18T09:56:30.372405228Z,kubernetes.io/config.source: file,},OwnerReferences:[{v1 Node minikube 968dcd5e-dda4-4208-8644-9ef7047e6125 0xc000aa66d0 <nil>}],Finalizers:[],ClusterName:,ManagedFields:[],},Spec:PodSpec{Volumes:[],Containers:[{natsqueuestatic nats [/nats-server] [-m 8222]  [{web 0 8222 TCP }] [] [] {map[] map[]} [] [] nil nil nil /dev/termination-log File Always nil false false false}],RestartPolicy:Always,TerminationGracePeriodSeconds:*30,ActiveDeadlineSeconds:nil,DNSPolicy:ClusterFirst,NodeSelector:map[string]string{},ServiceAccountName:,DeprecatedServiceAccount:,NodeName:minikube,HostNetwork:false,HostPID:false,HostIPC:false,SecurityContext:&PodSecurityContext{SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:nil,RunAsGroup:nil,Sysctls:[],WindowsOptions:nil,},ImagePullSecrets:[],Hostname:,Subdomain:,Affinity:nil,SchedulerName:default-scheduler,InitContainers:[],AutomountServiceAccountToken:nil,Tolerations:[{ Exists  NoExecute <nil>}],HostAliases:[],PriorityClassName:,Priority:*0,DNSConfig:nil,ShareProcessNamespace:nil,ReadinessGates:[],RuntimeClassName:nil,EnableServiceLinks:*true,PreemptionPolicy:nil,Overhead:ResourceList{},TopologySpreadConstraints:[],EphemeralContainers:[],},Status:PodStatus{Phase:Pending,Conditions:[],Message:,Reason:,HostIP:,PodIP:,StartTime:<nil>,ContainerStatuses:[],QOSClass:BestEffort,InitContainerStatuses:[],NominatedNodeName:,PodIPs:[],EphemeralContainerStatuses:[],},}
```

Also I can see that the respective nats module was initialised properly and the Kubernetes metadata are added to its events:
![Screenshot 2019-12-18 at 12 02 24](https://user-images.githubusercontent.com/11754898/71076496-7d54bf00-218e-11ea-8e4e-16e5f9b27d52.png)


One thing I can see in your configuration that need to be fixed is to remove `in_cluster: true`, since this config option does not exist anymore. Could you try that as a first step?

**Comment by mitchellmaler** [comment]
@ChrsMark Here is my latest config and I have also provided a pastebin link to the autodiscover debug logs. I updated the config removing the in_cluster field, thanks for pointing out that was removed. I still am unable to get the autodiscover to pick up the already running control plane pods. I am wondering if this is an issue with discovery existing pods.

LOGS: https://pastebin.com/XkR6qub0

```yaml
# Sets log level. The default log level is info.
# Available log levels are: error, warning, info, debug
logging.level: debug
# Enable debug output for selected components. To enable all selectors use ["*"]
# Other available selectors are "beat", "publish", "service"
# Multiple selectors can be chained.
logging.selectors: ["autodiscover"]
# Set to true to log messages in JSON format.
#logging.json: false
processors:
- add_fields:
    target: kubernetes
    fields:
      name: test-cluster-name
setup.dashboards.enabled: true
setup.kibana:
  host: "https://kibana-kb-http.elastic-system:5601"
  ssl.verification_mode: none
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
metricbeat.modules:
# Kubernetes Kube-State-Metrics
- module: kubernetes
  enabled: true
  metricsets:
    - state_node
    - state_deployment
    - state_replicaset
    - state_pod
    - state_container
    - state_cronjob
    - state_resourcequota
    - state_statefulset
  add_metadata: true
  period: 10s
  hosts: ["${KUBE_STATE_METRICS_HOSTS}"]
# Kubernetes Events
- module: kubernetes
  enabled: true
  metricsets:
    - event
# Kubernetes API server
- module: kubernetes
  enabled: true
  metricsets:
    - apiserver
  hosts: ["https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}"]
  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  ssl.certificate_authorities:
    - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
metricbeat.autodiscover:
  providers:
    - type: kubernetes
      templates:
        # CoreDNS Discovery
        - condition:
            contains:
              kubernetes.labels.k8s-app: kube-dns
              kubernetes.namespace: kube-system
          config:
            - module: coredns
              metricsets:
                - stats
              period: 10s
              hosts: "${data.host}:9153"
        # ETCD Discovery
        - condition:
            contains:
              kubernetes.labels.component: etcd
              kubernetes.labels.tier: control-plane
              kubernetes.namespace: kube-system
          config:
            - module: etcd
              metricsets:
                - leader
                - self
                - store
                - metrics
              period: 10s
              hosts: "${data.host}:2379"
              ssl.certificate_authorities:
                - /usr/share/metricbeat/certs/etcd/ca.crt
              ssl.certificate: /usr/share/metricbeat/certs/etcd/healthcheck-client.crt
              ssl.key: /usr/share/metricbeat/certs/etcd/healthcheck-client.key
              add_metadata: true
        # Controller Manager Discovery
        - condition:
            contains:
              kubernetes.labels.component: kube-controller-manager
              kubernetes.labels.tier: control-plane
              kubernetes.namespace: kube-system
          config:
            - module: kubernetes
              metricsets:
                - controllermanager
              period: 10s
              hosts: "${data.host}:10252"
              add_metadata: true
        # Scheduler Discovery
        - condition:
            contains:
              kubernetes.labels.component: kube-scheduler
              kubernetes.labels.tier: control-plane
              kubernetes.namespace: kube-system
          config:
            - module: kubernetes
              metricsets:
                - scheduler
              period: 10s
              hosts: "${data.host}:10251"
              add_metadata: true
output.elasticsearch:
  hosts: ['https://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}']
  protocol: "https"
  ssl.verification_mode: none
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
```

Here is the etcd pod manifest that the kubelet is deploying on the control plane node, it is not being found by the autodiscover

```yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: etcd
    tier: control-plane
  name: etcd
  namespace: kube-system
spec:
  containers:
  - command:
    - etcd
    - --advertise-client-urls=https://172.17.0.4:2379
    - --cert-file=/etc/kubernetes/pki/etcd/server.crt
    - --client-cert-auth=true
    - --data-dir=/var/lib/etcd
    - --initial-advertise-peer-urls=https://172.17.0.4:2380
    - --initial-cluster=asc-local-k8s-control-plane=https://172.17.0.4:2380
    - --key-file=/etc/kubernetes/pki/etcd/server.key
    - --listen-client-urls=https://127.0.0.1:2379,https://172.17.0.4:2379
    - --listen-peer-urls=https://172.17.0.4:2380
    - --name=asc-local-k8s-control-plane
    - --peer-cert-file=/etc/kubernetes/pki/etcd/peer.crt
    - --peer-client-cert-auth=true
    - --peer-key-file=/etc/kubernetes/pki/etcd/peer.key
    - --peer-trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    - --snapshot-count=10000
    - --trusted-ca-file=/etc/kubernetes/pki/etcd/ca.crt
    image: k8s.gcr.io/etcd:3.3.10
    imagePullPolicy: IfNotPresent
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -ec
        - ETCDCTL_API=3 etcdctl --endpoints=https://[127.0.0.1]:2379 --cacert=/etc/kubernetes/pki/etcd/ca.crt
          --cert=/etc/kubernetes/pki/etcd/healthcheck-client.crt --key=/etc/kubernetes/pki/etcd/healthcheck-client.key
          get foo
      failureThreshold: 8
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: etcd
    resources: {}
    volumeMounts:
    - mountPath: /var/lib/etcd
      name: etcd-data
    - mountPath: /etc/kubernetes/pki/etcd
      name: etcd-certs
  hostNetwork: true
  priorityClassName: system-cluster-critical
  volumes:
  - hostPath:
      path: /etc/kubernetes/pki/etcd
      type: DirectoryOrCreate
    name: etcd-certs
  - hostPath:
      path: /var/lib/etcd
      type: DirectoryOrCreate
    name: etcd-data
status: {}
```

**Comment by ChrsMark** [comment]
Hey!

In my case I can see that both `kube-controller-manager` and `kube-scheduler` are discovered as static pods too. I'm using the manifests from  [here](https://github.com/elastic/cloud-on-k8s/tree/master/config/recipes/beats), along with ECK so it may worth to have a look there too.

What I would suggest here is to try to remove all the conditions and just have a pure autodiscover configuration and check if this will discover all the pods. This will help us isolate the problem, maybe 🙂  .

**Comment by mitchellmaler** [comment]
I have finally had a chance to get back to this. I have re-deployed beats 7.5.1 to one of our clusters which is then pointed to ECE. This is a bit different than before where I was running KIND locally to test. This time it is unable to autodiscover all control plane pods except for the automatic api server one. 

```yaml
metricbeat.autodiscover:
  providers:
    - type: kubernetes
      templates:
        # CoreDNS Discovery
        - condition:
            contains:
              kubernetes.labels.k8s-app: kube-dns
              kubernetes.namespace: kube-system
          config:
            - module: coredns
              metricsets:
                - stats
              period: 10s
              hosts: ["${data.host}:9153"]
        # https://github.com/elastic/beats/issues/14997
        # ETCD Discovery
        - condition:
            contains:
              kubernetes.labels.component: etcd
              kubernetes.labels.tier: control-plane
              kubernetes.namespace: kube-system
          config:
            - module: etcd
              metricsets:
                - leader
                - self
                - store
                - metrics
              period: 10s
              hosts: ["${data.host}:2379"]
              ssl.certificate_authorities:
                - /usr/share/metricbeat/certs/etcd/ca.crt
              ssl.certificate: /usr/share/metricbeat/certs/etcd/healthcheck-client.crt
              ssl.key: /usr/share/metricbeat/certs/etcd/healthcheck-client.key
              add_metadata: true
        # Controller Manager Discovery
        - condition:
            contains:
              kubernetes.labels.component: kube-controller-manager
              kubernetes.labels.tier: control-plane
              kubernetes.namespace: kube-system
          config:
            - module: kubernetes
              metricsets:
                - controllermanager
              period: 10s
              hosts: ["${data.host}:10252"]
              add_metadata: true
        # Scheduler Discovery
        - condition:
            contains:
              kubernetes.labels.component: kube-scheduler
              kubernetes.labels.tier: control-plane
              kubernetes.namespace: kube-system
          config:
            - module: kubernetes
              metricsets:
                - scheduler
              period: 10s
              hosts: ["${data.host}:10251"]
              add_metadata: true
```

I think we are going to log a ticket since we have support with our ECE deployment to get some more help on this. I will update once I get more information about this.
