### ISSUE TITLE
[Metricbeat][docs] The `namespace` configuration seems to be mandatory in 6.8 in the Prometheus module, but it is commented out in the docs

### ISSUE THREAD

**Issue by ismael-hasan** [elastic/beats#15033]
The documentation for the Prometheus module in 6.8 - https://www.elastic.co/guide/en/beats/metricbeat/6.8/metricbeat-module-prometheus.html - does not indicate that `namespace` is mandatory. It shows it as a commented attribute: 
```
metricbeat.modules:
- module: prometheus
  metricsets: ["stats"]
  enabled: true
  period: 10s
  hosts: ["localhost:9090"]
  #metrics_path: /metrics
  #namespace: example

- module: prometheus
  metricsets: ["collector"]
  enabled: true
  period: 10s
  hosts: ["localhost:9090"]
  #metrics_path: /metrics
  #namespace: example

  # This can be used for service account based authorization:
  #  bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
  #ssl.certificate_authorities:
  #  - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
```

If no namespace is defined in the module, Metricbeat fails at startup with ` Exiting: 1 error: 1 error: missing required field accessing '0.namespace'....`. 

It seems this requirement does not exist in version 7 anymore - https://github.com/elastic/beats/pull/9948 

The docs for version 6 should be more explicit on the parameter being mandatory
