### ISSUE TITLE
[Agent] Kibana protocol is not correctly persisted to disk

### ISSUE THREAD

**Issue by ph** [elastic/beats#15087]
When we serialize the Kibana configuration after we enroll the protocol used to communicate with the remote endpoint is missing in the persisted yaml.

**Comment by michalpristas** [comment]
@ph are you working on this?

**Comment by ph** [comment]
@michalpristas I can take a look, I am in the neighborhood for something else.

**Comment by ph** [comment]
I think its decoupled so, you can take a look that should a small PR.

**Comment by michalpristas** [comment]
@ph content of `fleet.yml`

```yml
agent_info:
  ID: 03660122-f63a-4daf-8440-3fb5fea7ad90
api:
  access_api_key: VjhlSjBXOEJENFFxb3JJeU1kNjQ6U0QwMlZxODRScy1QUUM4cFdxeUtGZw==
  kibana:
    host: localhost:5601
    protocol: http
    timeout: 1m30s
reporting:
  fleet:
    reportingcheckfrequency: 30
    threshold: 10000
  log:
    format: default
```

protocol information is there. or were you referring to `agent.yml` as i see multiple problems with that e.g none of the configuration is preserved and all is replaced with static file.
at least `download` part of the config preserved as it says where download is stored and where pgp is.
