### ISSUE TITLE
Add documentation examples for adding fields to a module

### ISSUE THREAD

**Issue by ErnestoBezanilla** [elastic/beats#15081]
Normally you'd configure `fields` and `fields_under_root` as  

```
- type: log
  paths: 
    - /your_data_path
  fields: 
    field1: aaa
    field2: bbb 
    field3: ccc
  fields_under_root: true
```
However there's no example in the documentation on how to do this when using modules. For example:

```
- module: apache2
  access:
    enabled: true
    var.paths: 
    input:
      fields_under_root: true
      fields.field1: aaa
      fields.field2: bbb
      fields.field3: ccc
  error:
    enabled: true
    var.paths: 
    input:
      fields_under_root: true
      fields.field1: aaa
      fields.field2: bbb
      fields.field3: ccc

```
