### ISSUE TITLE
[Agent] Fail to parse a configuration.

### ISSUE THREAD

**Issue by ph** [elastic/beats#15182]
```
outputs:
   default:
     index_name: general
     pass: xxx
     type: elasticsearch
     url: xxxxx
     username: xxx
streams:
  - output:
      index_name: mysql_access_logs
    path: /xxxx
    type: logmanagement:
  mode: local
  reload:
```
	Failed to read configuration, error: could not emit configuration: fail to extract program configuration: fail to generate configuration for output name default: could not parse configuration into a tree, error: unknown type <nil> for <nil>
```
reported by @michalpristas
