### ISSUE TITLE
[Agent] path related variables are not respected in the Agent yaml configuration.

### ISSUE THREAD

**Issue by ph** [elastic/beats#15328]
Using `${path.data}` or `${path.home}` is not currently working in the agent, this cause problem when you want to define relative path to the executable.

**Comment by ph** [comment]
**NOTE TO SELF (trying to get things out of my mind.**

I am trying to find the best way to link our configuration management in the agent to the existing beat configuration handling. 

In beats is possible to reference other YAML parts like what we do with `path.home`  we use that variable to dynamically generate `${path.data}` and `${path.logs}` This work because we have a unique single configuration but that doesn't work well when we fetch the configuration from fleet. I wonder if we should have a map of variables that could be referenced in the configuration.

**Comment by ph** [comment]
@michalpristas Can you quick your input here, what would be the best way to do it?

**Comment by michalpristas** [comment]
if we stick with spec file, there can be actually way to support it. 

right now we have flow like this
`*.spec` file -> yaml.Unmarshall(&specificStruct) -> appent.To(SpecCollection)

the thing is that resolution needs to happen on program instantiation as each program has unique log path and data path based on pipeline ID (there is a restriction: two beats cannot have same data path) 
so we would need to get Spec for a beat (`app/start.go L54`) make it ucfg, inject paths, make it a spec again.

then we would need different strategy (but same injection and resolution) in case when we target agent config (either from agent.yml or fleet)

**Comment by ph** [comment]
I am not too worried about the spec files because I think at the moment we can decide to only work with absolute path. What Its more important (I think) is all the variable substitution works with _agent.yml_. Today to make the agent work we have to have a configuration that look like this.

```yaml
download:
  sourceURI: "https://artifacts.elastic.co/downloads/beats/"
  target_directory: "/home/ph/agent-8.0.0-linux-x86_64/beats"
  timeout: 30s
  pgpfile: "/home/ph/agent-8.0.0-linux-x86_64/elastic.pgp"
  install_path: "/home/ph/agent-8.0.0-linux-x86_64/install"
```

It would be nice if we could have something like this:

```
download:
  sourceURI: "https://artifacts.elastic.co/downloads/beats/"
  target_directory: "${path.data}/beats"
  timeout: 30s
  pgpfile: "${path.data}/elastic.pgp"
  install_path: "${path.data}//install"
```

Also when we have systemd starting script we also have to start the agent with the appropriately defined path like `-E "path.data=/var/...."`, When we are at the spec level I think we can get away by using absolute path defined by the previously set values?
