### ISSUE TITLE
Palo Alto Module does not provide log.source.address

### ISSUE THREAD

**Issue by strawgate** [elastic/beats#15375]
For confirmed bugs, please report:
- Version: 7.5.0
- Operating System: Any
- Steps to Reproduce: 

1. Setup a Filebeat with a Palo Alto Module
1. Forward logs from the Palo Alto device to the Filebeat
1. Notice that there is no log.source.address populated on the messages parsed through filebeat

**Comment by faec** [comment]
I'm not sure `log.source.address` is supposed to appear on `panw` messages... see the module's [list of exported fields](https://www.elastic.co/guide/en/beats/filebeat/master/exported-fields-panw.html). Is `panw.panos.source.nat.ip` / `panw.panos.source.nat.port` what you're looking for?

**Comment by strawgate** [comment]
nat.ip and nat.port are related to the traffic going through the palo alto.

The palo alto is forwarding Syslog and so i'd expect that log.source.address would be populated similar to any other syslog source.

**Comment by faec** [comment]
Ah, no you're right, I just double checked and that field should be present. Can you share the `filebeat.yml` you're seeing this with?

**Comment by strawgate** [comment]
```
#####################
#
#=========================== Filebeat inputs =============================
filebeat.inputs:
   
#============================= Filebeat modules ===============================
filebeat.config.modules:
  path: ${path.config}/configs/panw/module.yml
  reload.enabled: false
output.logstash:
  hosts: ["172.18.0.1:4060"]
logging.metrics.period: 600
logging.json: true
```
and
```
# Module: panw
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.3/filebeat-module-panw.html
- module: panw
  panos:
    enabled: true
    var.syslog_host: 0.0.0.0
    var.syslog_port: 5060
```
