### ISSUE TITLE
Haproxy module is not able to parse access log

### ISSUE THREAD

**Issue by uday3110** [elastic/beats#15488]
Haproxy modules does not work for me. 

**filebeat version**: filebeat version 7.5.1 (amd64), libbeat 7.5.1 
**operating system**: Ubuntu 16.04

_filebeat.yml config_
```
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
output.console:
  pretty: true
```
_haproxy.yml_
```
- module: haproxy
  log:
    enabled: true

    var.input: "file"
    var.paths: ["/var/log/haproxy.access.log"]
```
_sample log line_
```
Jan 11 02:16:01 dev-matching-lb01 haproxy[14848]: 172.27.88.86:21552 [11/Jan/2020:02:16:01.970] 80 contractorsummarization/contractorsummarization-node1 0/0/0/9/9 404 1283 - - ---- 18/18/0/1/0 0/0 "GET /contractorsummarization/b/v2/10947999/info.json?summarycache=true HTTP/1.1"
```
**output**
```
{
  "@timestamp": "2020-01-11T02:17:52.621Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "7.5.1",
    "pipeline": "filebeat-7.5.1-haproxy-log-pipeline"
  },
  "message": "Jan 11 02:17:50 dev-matching-lb01 haproxy[14848]: 10.250.12.72:56118 [11/Jan/2020:02:17:50.655] 80 80/<NOSRV> -1/-1/-1/-1/0 503 212 - - SC-- 4/4/0/0/0 0/0 \"GET /favicon.ico HTTP/1.1\"",
  "input": {
    "type": "log"
  },
  "agent": {
    "type": "filebeat",
    "ephemeral_id": "d5ea5e2d-58a7-405f-811e-827a893b8b77",
    "hostname": "dev-matching-lb01",
    "id": "84c264b5-6808-4d60-94d5-aa56990b6194",
    "version": "7.5.1"
  },
  "log": {
    "offset": 21549587,
    "file": {
      "path": "/var/log/haproxy.access.log"
    }
  },
  "event": {
    "module": "haproxy",
    "dataset": "haproxy.log"
  },
  "fileset": {
    "name": "log"
  },
  "ecs": {
    "version": "1.1.0"
  },
  "host": {
    "name": "dev-matching-lb01"
  },
  "service": {
    "type": "haproxy"
  }
```
