### ISSUE TITLE
don't run autodiscovery and static module conf at the same time

### ISSUE THREAD

**Issue by fherbin** [elastic/beats#15569]
**Describe the enhancement:**
When configuring the autodiscovey, the module should not be started with the static configuration.
or else, it should be possible to choose the expected behaviour
**Describe a specific use case for the enhancement or feature:**
I have a host machine with multiple containerized nginx servers.
I don't have nginx on the host.
Here is the configuration of the autodiscovery: 
```yaml
metricbeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: "nginx"
          config:
            - module: nginx
              metricsets: ["stubstatus"]
              server_status_path: "nginx-stats"
              hosts: "http://${data.host}"

```
but when you run metricbeat, it still runs a module with the static configuration
if the "hosts" property is empty, metricbeat doesn't run.
