### ISSUE TITLE
[Metricbeat] Googlecloud Module: Error trying to get data from instance 

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#15613]
Error message showed up when testing googlecloud metricbeat module: 
```
2020-01-16T06:45:32.678-0700    ERROR   [googlecloud.compute]   stackdriver/timeseries.go:37    error trying to retrieve ID from metric event 'error trying to get data from instance '8970924285285850010' in zone 'europe-west3-c': error getting instance information for instance with ID '8970924285285850010': googleapi: Error 404: The resource 'projects/elastic-observability/zones/europe-west3-c/instances/8970924285285850010' was not found, notFound'
```

The config I used is:
```
- module: googlecloud
  metricsets:
    - compute
  zone: "europe-west3-a"
  project_id: "elastic-observability"
  credentials_file_path: "/Users/kaiyansheng/Downloads/elastic-observability-d17781618202.json"
  exclude_labels: false
  period: 300s
- module: googlecloud
  metricsets:
    - compute
  zone: "europe-west3-c"
  project_id: "elastic-observability"
  credentials_file_path: "/Users/kaiyansheng/Downloads/elastic-observability-d17781618202.json"
  exclude_labels: false
  period: 300s
```
