### ISSUE TITLE
[Heartbeat] Proposal: Make a group of multiple requests.

### ISSUE THREAD

**Issue by ISKU** [elastic/beats#15689]
I asked the community about the new feature as shown in the link [discuss/196105](https://discuss.elastic.co/t/is-it-possible-to-make-a-new-http-request-with-the-data-in-the-responsebody/196105). But I got an answer that it doesn't support this feature. I need this feature to check my application. So, I propose the ability to make a group of multiple requests and to use data from the response body of each request.

**The Situation**
---
I want to make more than two request. The data from the response body of the previous request must be used in the next request. For example, when a token is received from an authentication server and used for the next request.

Config 1:
``` yaml
name: http
schedule: '* * * * *'
urls: ['http://first.url.com']
check.request:
    method: 'POST'
check.response:
    status: 200
    json:
        condition:
            equals:
                myField: '{token: ABCD-EFGH-IJKL-MNOP}'
```

Config 2:
``` yaml
name: http
schedule: '* * * * *'
urls: ['http://second.url.com']
check.request:
    method: 'POST'
    headers:
        'token': 'ABCD-EFGH-IJKL-MNOP'
check.response:
    status: 200
```

In Config 1, receive the `token` key from the json data of the response body. And I want to use this `token` key for headers in Config 2.

**The Problem**
---
There are some problems to solve for this feature:
1. The config for each request is independent.
2. Multiple requests cannot be processed in order. Each request is related and must be guaranteed to be processed in order.
3. Data from request body or response body is not available. Data should be used like a variable.

**The Proposal**
---
Config 3:
``` yaml
name: http
group:
    name: myGroup
    seq: 1
schedule: '* * * * *'
urls: ['http://first.url.com']
check.request:
    method: 'POST'
check.response:
    status: 200
    json:
        condition:
            equals:
                myField: '{token: ABCD-EFGH-IJKL-MNOP}'
```
Config 3 added the `group` field in Config 1. Meaning of each field of group is as follows:
* name: Name of the group. If each configuration request has the same name, it is the same group.
* seq: The order in which the group will process.

Config 4:
``` yaml
name: http
group:
    name: myGroup
    seq: 2
schedule: '* * * * *'
urls: ['http://second.url.com']
check.request:
    method: 'POST'
    headers:
        'token': 'ABCD-EFGH-IJKL-MNOP'
check.response:
    status: 200
```
When Config 3 completes successfully, Config 4 is performed in the order of the `seq` fields in the group. The `token` in Config 4 was received from the response body in Config 3.

There may be some issues with this proposal:
1. It can have duplicate keys in multiple requests. There are several ways to resolve duplicate keys.
2. Limit the scope of `seq` field.
3. Logging when only some requests are completed in a group.

---
How is it? This is for the Heartbeat.
If possible, I want to contribute to this heartbeat. Can I try this development?
Thanks.
