### ISSUE TITLE
[Filebeat] CEF module missing observer.ip (ECS)

### ISSUE THREAD

**Issue by fpompermaier** [elastic/beats#15774]
**Describe the enhancement:**
Filebeat netflow put the source of logs into observe.ip (ad mandated by ECS). CEF module doesn't.
All other observer fields instead are filled.

**Describe a specific use case for the enhancement or feature:**
When CEF logs are parsed by the CEF module the source of logs is put into log.source.address (as ip:port..). I think it would be better to put the ip address also in observer.ip

I propose to modify CEF input.yml processors to:

```
processors:
  - dissect:
      when:
        has_fields: ['log.source.address']
      tokenizer: "%{ip}:%{port}"
      field: "log.source.address"
      target_prefix: "log.source"
  - drop_fields:
     fields: ["log.source.port"]
     ignore_missing: true
  - rename:
      fields:
        - {from: "message", to: "event.original"}
        - {from: "log.source.ip", to: "observer.ip"}
  - decode_cef:
      field: event.original
  - community_id:

```
