### ISSUE TITLE
[Metricbeat] Add regions support in googlecloud module

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#15780]
Right now in googlecloud module, we can specify a specific zone in each configuration section. For example if I want to collect compute metrics from all three zones under `europe-west1` region, I have to specify three sections:
```
- module: googlecloud
  metricsets:
    - compute
  zone: "europe-west1-b"
  project_id: "test"
  credentials_file_path: "/Users/kaiyansheng/Downloads/test-d17781618202.json"
  exclude_labels: false
  period: 300s
- module: googlecloud
  metricsets:
    - compute
  zone: "europe-west1-c"
  project_id: "test"
  credentials_file_path: "/Users/kaiyansheng/Downloads/test-d17781618202.json"
  exclude_labels: false
  period: 300s
- module: googlecloud
  metricsets:
    - compute
  zone: "europe-west1-d"
  project_id: "test"
  credentials_file_path: "/Users/kaiyansheng/Downloads/test-d17781618202.json"
  exclude_labels: false
  period: 300s
```
It will be useful to add a regions parameter in config which makes this module automatically goes to collect metrics from the zones that belong to the same region. For example:
```
- module: googlecloud
  metricsets:
    - compute
  regions: 
    - europe-west1
  project_id: "test"
  credentials_file_path: "/Users/kaiyansheng/Downloads/test-d17781618202.json"
  exclude_labels: false
  period: 300s
```
