### ISSUE TITLE
[Metricbeat] googlecloud module has potential sensitive data in labels.metadata

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#15782]
When testing googlecloud module, I see in each event there are large amount of metadata included. For example, CA_CERT, KUBELET_CERT, KUBELET_KEY under `googlecloud.labels.metadata.kube-env`.  Should we reconsider the metadata under `googlecloud.labels.metadata.*`?

If you use config below, you should be able to get the metrics that contain these information:
```
- module: googlecloud
  metricsets:
    - compute
  zone: "europe-west1-c"
  project_id: elastic-observability
  credentials_file_path: "<path-to-your-creds-file>"
  exclude_labels: false
  period: 300s
```
