### ISSUE TITLE
Npipe syntax to expose http monitoring is slightly different from consuming the metric

### ISSUE THREAD

**Issue by ph** [elastic/beats#15832]
to consume metric over npipe:

```yaml
- module: beat
  metricsets:
    - stats
    - state
  period: 10s
  hosts: ["http+npipe://./pipe/custom"]
```

To expose over npipe
```yaml
http.enabled: true
http.host: npipe:///custom
```

We should align both to use `http+npipe://./pipe/custom`
