### ISSUE TITLE
Processor if/then/else not working when adding fields using variable

### ISSUE THREAD

**Issue by odacremolbap** [elastic/beats#15886]
Filebeat 7.4 and 7.5

This processor works fine:
```
      providers:
        - type: kubernetes
          host: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log
            processors:
              - if:
                  has_fields: [ 'kubernetes.labels.common_k8s_elastic_co/type' ]
                then:
                  - add_fields:
                      fields:
                        eedugon: "YES"
                else:
                  - add_fields:
                      fields:
                        eedugon: "NO"
```

Replacing the `then` condition with a field does work for the `then` case, but dont execute the `else` case, logging an error instead
```
      providers:
        - type: kubernetes
          host: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log
            processors:
              - if:
                  has_fields: [ 'kubernetes.labels.common_k8s_elastic_co/type' ]
                then:
                  - add_fields:
                      fields:
                        eedugon: ${data.kubernetes.labels.common_k8s_elastic_co/type}
                else:
                  - add_fields:
                      fields:
                        eedugon: "NO"
```

The error is:
```
Error creating runner from config: No paths were defined for input accessing config
```

**Comment by andresrc** [comment]
A possible workaround is to use `copy_to` instead of add_fields processor. As with `copy_to` there's no need to access the value of the variable ${data.kubernetes.xxxx}.

```
            processors:
              - if:
                  has_fields: [ 'kubernetes.labels.common_k8s_elastic_co/type' ]
                then:
                  - copy_fields:
                      fields:
                      - from: kubernetes.labels.common_k8s_elastic_co/type
                        to: fields.eedugon
                      fail_on_error: false
                      ignore_missing: true
                else:
                  - add_fields:
                      fields:
                        eedugon: "NO"
```
