### ISSUE TITLE
Reusable/common snippets of filebeat input config

### ISSUE THREAD

**Issue by Mekk** [elastic/beats#16084]
My filebeat input configs start being very copypastish.
They usually look so:
```
- type: log
  enabled: true
  paths:
    - /some/path/*.log
    - /or/maybe/two.*.log
   exclude_files:
    - _a_few.log$
    - excluded$
    - ^thins
  encoding: latin2
  tags: ["some", "tags"]
  fields:
      some:
          custom: fields
  fields_under_root: true

  ignore_older: 48h
  max_bytes: 10485760
  close_inactive: 24h
  scan_frequency: 5s
  harvester_limit: 1200

  multiline.pattern: …entry pattern …
  multiline.negate: true
  multiline.match: after
  multiline.flush_pattern: …finish pattern ·
  multiline.max_lines: 100000
  multiline.timeout: 5s

- another-section

- and another

- and another

- and another (in record case I have 27 of them and may have 81 soon)
```
where sections differ only by `paths` and (some) `fields` (less frequently `encoding` or `harvester_limit`), and remaning settings remain  the same. Copy. Paste. Copy. Paste. Copy. Paste.

So it would be great if I could write common settings somewhere somehow.

**Comment by Mekk** [comment]
In general, I'd probably like most If I could write sht like
```
- type: config-group
  name: common-bluhbluh-settings
  any: settings
  wha:
    - te
    -ver

- type: log
  import: common-bluhbluh-settings
  cust:
     om: changes
```
(whether conflict between imported settings and those explicitly written generates an error, or is resolved in favor of specific setting, I have no strict opinion, in case of fields would be nice if they were merged)

Such or similar approach would let me have more than one such predefined set in case I watch two log kinds (which need different multiline pattern)

Or mayhaps do it per-file (wherever I use two/three log kinds, I usually end having inputs.d directory with separate file for each), sth like:
```
- type: common
  some: settings
     which: are applied to all logs from this .conf file
```

Or sth else.

I considered templating externally, but this is troublesome considering people happen to patch the file manually on the final machine, or even just look at those files to check the current config.
