### ISSUE TITLE
Error when combining processors autodiscover hint with modules using processors

### ISSUE THREAD

**Issue by exekias** [elastic/beats#16190]
It seems autodiscover `processors` hint produces an error when used with modules that also make use of processors (ie elasticsearch module).

Steps to reproduce it:

Configure Filebeat with hints based autodiscover like this:

```
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

output.console:
  pretty: true
```

Launch a container with the following labels:

```
docker run -l 'co.elastic.logs/processors.add_fields={\"foo\":\"bar\"}' -l co.elastic.logs/module=elasticsearch busybox echo hell
```

This error happens:

```
Error creating input: each processor must have exactly one action, but found 2 actions (add_locale,add_fields)
```

The expected behavior is to get the module launched, with both processors working for it.
