### ISSUE TITLE
[Agent] Use and inject datasource ids from retrieved configuration

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#16209]
With example config as below we need to parse datasource ID and pass it down the stack to respective programs. This should be used for logging and reporting. 

```
outputs:
  default:
    api_key: VuaCfGcBCdbkQm-e5aOx:ui2lp2axTNmsyakw9tvNnw
    hosts: ["localhost:9200"]
    ca_sha256: "7lHLiyp4J8m9kw38SJ7SURJP4bXRZv/BNxyyXkCcE/M="

  long_term_storage:
    api_key: VuaCfGcBCdbkQm-e5aOx:ui2lp2axTNmsyakw9tvNnw
    hosts: ["localhost:9200"]
    ca_sha256: "7lHLiyp4J8m9kw38SJ7SURJP4bXRZv/BNxyyXkCcE/M="

  monitoring:
    api_key: VuaCfGcBCdbkQm-e5aOx:ui2lp2axTNmsyakw9tvNnw
    hosts: ["localhost:9200"]
    ca_sha256: "7lHLiyp4J8m9kw38SJ7SURJP4bXRZv/BNxyyXkCcE/M="

settings.monitoring:
  use_output: monitoring

datasources:
  # use the nginx package
  - id: nginx-x1
    enabled: true # default to true
    use_output: long_term_storage
    inputs:
    ...
```
