### ISSUE TITLE
[Agent] Support for contraints in configuration

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#16210]
With example config as below we need to parse and evaluate constraint for each datasource.
keys used in contraints should be ECS compliant
constraints for each restriction (e.g `os.platform`) are in key value format where
key is operator (one of `>` ,`<`, `==`, `!=`, `<=`, `>=`, `in` `!in` 
value is a value of restriction 

```
outputs:
  default:
    api_key: VuaCfGcBCdbkQm-e5aOx:ui2lp2axTNmsyakw9tvNnw
    hosts: ["localhost:9200"]
    ca_sha256: "7lHLiyp4J8m9kw38SJ7SURJP4bXRZv/BNxyyXkCcE/M="

  long_term_storage:
    api_key: VuaCfGcBCdbkQm-e5aOx:ui2lp2axTNmsyakw9tvNnw
    hosts: ["localhost:9200"]
    ca_sha256: "7lHLiyp4J8m9kw38SJ7SURJP4bXRZv/BNxyyXkCcE/M="

  monitoring:
    api_key: VuaCfGcBCdbkQm-e5aOx:ui2lp2axTNmsyakw9tvNnw
    hosts: ["localhost:9200"]
    ca_sha256: "7lHLiyp4J8m9kw38SJ7SURJP4bXRZv/BNxyyXkCcE/M="

settings.monitoring:
  use_output: monitoring

datasources:
  # use the nginx package
  - id: nginx-x1
    constraints?:
      # Contraints look are not final
      - os.platform: { in: "windows" }
      - agent.version: { ">=": "8.0.0" }
    ...
```
