### ISSUE TITLE
[Winlogbeat] Add Powershell logging module

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#16262]
Add a new Winlogbeat module to collect logs from PowerShell. This will collect information about the scripts and modules that are being executed.

```
# The module will process events based on this config.
winlogbeat.event_logs:
- name: Microsoft-Windows-PowerShell/Operational
  event_ids: 4103, 4104

- name: Windows PowerShell
  event_id: 400, 800
```

- 4103 - module logging
- 4104 - script block logging (first time it runs)
- 4105 - Command started (maybe handle this event?) (not on by default in windows)
- 4106 - Command completed (maybe handle this event?) (not on by default in windows)

References:
- https://devblogs.microsoft.com/powershell/powershell-the-blue-team/

## Module Checklist

* [ ] Supported versions are documented
* [ ] Supported operating systems are documented (if applicable)
* [ ] Automated checks that all fields are documented
* [ ] Documentation
* [ ] Fields follow [ECS](https://github.com/elastic/ecs) and [naming conventions](https://www.elastic.co/guide/en/beats/devguide/master/event-conventions.html)
* [ ] Dashboards to show the data

**Comment by gwsales** [comment]
PowerShell module logging has been working well for me, and for parsing on 4103 and 800 you can pull apart the param fields, I'm currently doing this with a dissect parser.

example:
```
  - name: Microsoft-Windows-PowerShell/Operational
    event_id: 4103
    processors:
      - dissect:
          when:
            has_fields: ['winlog.event_data.ContextInfo']
          tokenizer: "        Severity = %{Severity}\n        Host Name = %{HostName}\n        Host Version = %{HostVersion}\n        Host ID = %{HostID}\n        Host Application = %{HostApplication}\n        Engine Version = %{EngineVersion}\n        Runspace ID = %{RunspaceID}\n        Pipeline ID = %{PipelineID}\n        Command Name = %{CommandName}\n        Command Type = %{CommandType}\n        Script Name = %{ScriptName}\n        Command Path = %{CommandPath}\n        Sequence Number = %{SequenceNumber}\n        User = %{User}\n        Connected User = %{ConnectedUser}\n        Shell ID = %{ShellID}"
          field: "winlog.event_data.ContextInfo"
          target_prefix: "winlog.event_data.powershell"
```

If you added an enhancement here, I'd recommend doing the key-value extraction more efficiently (if possible) and adding in an option to tail powershell transcript directories as a separate module.

Also please don't forget about "Windows PowerShell" event code 400 and 800, they are absolute gold.
```
  - name: Windows PowerShell
    event_id: 400, 800
    processors:
      - dissect:
          when:
            equals.winlog.event_id: 400
          tokenizer: "\tNewEngineState=%{NewEngineState}\n\tPreviousEngineState=%{PreviousEngineState}\n\n\tSequenceNumber=%{SequenceNumber}\n\n\tHostName=%{HostName}\n\tHostVersion=%{HostVersion}\n\tHostId=%{HostId}\n\tHostApplication=%{HostApplication}\n\tEngineVersion=%{EngineVersion}\n\tRunspaceId=%{RunspaceId}\n\tPipelineId=%{PipelineId}\n\tCommandName=%{CommandName}\n\tCommandType=%{CommandType}\n\tScriptName=%{ScriptName}\n\tCommandPath=%{CommandPath}\n\tCommandLine=%{CommandLine}"
          field: "winlog.event_data.param3"
          target_prefix: "winlog.event_data.powershell"
      - dissect:
          when:
            equals.winlog.event_id: 800
          tokenizer: "\tDetailSequence=%{DetailSequence}\n\tDetailTotal=%{DetailTotal}\n\n\tSequenceNumber=%{SequenceNumber}\n\n\tUserId=%{UserId}\n\tHostName=%{HostName}\n\tHostVersion=%{HostVersion}\n\tHostId=%{HostId}\n\tHostApplication=%{HostApplication}\n\tEngineVersion=%{EngineVersion}\n\tRunspaceId=%{RunspaceId}\n\tPipelineId=%{PipelineId}\n\tScriptName=%{ScriptName}\n\tCommandLine=%{CommandLine}"
          field: "winlog.event_data.param2"
          target_prefix: "winlog.event_data.powershell"
```
