### ISSUE TITLE
Upgrade integration's docker-compose files version from 2.3 to 3.x

### ISSUE THREAD

**Issue by mdelapenya** [elastic/beats#16269]
## Describe the enhancement
The project is using version '2.3', which is OK, but I'd like to start using 3.x version in the compose files for integrations

## Describe a specific use case for the enhancement or feature
From testing perspective, we could define more complex scenarios, like:

- adding labels on docker-compose build,
```yaml 
build:
  context: .
  labels:
    - "com.example.description=Accounting webapp"
    - "com.example.department=Finance"
    - "com.example.label-with-empty-value"
```

All changes between 2.x and 3.x are described here: https://docs.docker.com/compose/compose-file/compose-versioning/#version-2x-to-3x

As an example docker-compose v3.4 is available since 17.09.0-ce (2017-09-26), almost 2'5 years ago.
