### ISSUE TITLE
Filebeat running out of memory

### ISSUE THREAD

**Issue by fkelbert** [elastic/beats#16286]
- Version:  7.6.0
- Operating System:  Ubuntu 16.04
- Specs: 16GB RAM, 8 CPU

We are running Filebeat, reading from Google PubSub and ingesting into Elasticsearch. At first, we are getting data into Elasticsearch for a couple of minutes. However, after a while Filebeat runs  out of memory.

`filebeat.yml`:

```
filebeat.inputs:
- type: google-pubsub
  enabled: true
  project_id: data-engineering-151915
  topic: elasitc_test
  subscription.name: elastic-subscriber
  subscription.max_outstanding_messages: 10000000
  credentials_file: /home/xxx/data-engineering-151915-4475dad2342e.json
  json.keys_under_root: true
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 4
output.elasticsearch:
  hosts: ["xxx:9200"]
  protocol: "http"
  username: "elastic"
  password: ""
  index: elastic_dev_job
setup.template.name: "elastic_dev_test"
setup.template.pattern: "elastic_dev-*"
setup.ilm.enabled: false
processors:
  - decode_json_fields:
     fields: ["message" ]
     process_array: false
     max_depth: 10
     target: ""
     overwrite_keys: false
     add_error_key: true
  - drop_fields: 
      fields: ["message", "host", "input", "@timestamp", "agent", "event", "ecs"]
monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["xxx:9200"]
  username: elastic
  password: ---
```

Unfortunately, this is all we have at this point:

```
github.com/elastic/beats/libbeat/publisher/queue/memqueue.(*ackLoop).run(0xc0003acf00)
        /go/src/github.com/elastic/beats/libbeat/publisher/queue/memqueue/ackloop.go:60 +0x107
github.com/elastic/beats/libbeat/publisher/queue/memqueue.NewBroker.func2(0xc00011f500, 0xc0003acf00)
        /go/src/github.com/elastic/beats/libbeat/publisher/queue/memqueue/broker.go:179 +0x61
created by github.com/elastic/beats/libbeat/publisher/queue/memqueue.NewBroker
        /go/src/github.com/elastic/beats/libbeat/publisher/queue/memqueue/broker.go:177 +0x3a2
goroutine 108 [select]:
github.com/elastic/beats/libbeat/publisher/pipeline.(*eventConsumer).loop(0xc0003ad090, 0x3713ba0, 0xc0002733a0)
        /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/consumer.go:190 +0x2c7
created by github.com/elastic/beats/libbeat/publisher/pipeline.newEventConsumer
        /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/consumer.go:77 +0x154
goroutine 109 [select]:
github.com/elastic/beats/libbeat/publisher/pipeline.(*retryer).loop(0xc0003ad0e0)
        /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/retry.go:139 +0x1fd
created by github.com/elastic/beats/libbeat/publisher/pipeline.newRetryer
        /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/retry.go:91 +0x13d
goroutine 110 [runnable]:
github.com/elastic/beats/vendor/go.uber.org/zap.(*Logger).clone(...)
        /go/src/github.com/elastic/beats/vendor/go.uber.org/zap/logger.go:252
github.com/elastic/beats/vendor/go.uber.org/zap.(*Logger).Named(0xc000229f80, 0x32f3eae, 0xd, 0x13c3498)
        /go/src/github.com/elastic/beats/vendor/go.uber.org/zap/logger.go:138 +0x43
github.com/elastic/beats/libbeat/logp.MakeDebug.func1(0x32f7739, 0xf, 0xc1e7e03150, 0x1, 0x1)
        /go/src/github.com/elastic/beats/libbeat/logp/global.go:30 +0x47
github.com/elastic/beats/libbeat/outputs/elasticsearch.(*Connection).Ping(0xc0000b3200, 0x1, 0x1b21872, 0x4b6f64d, 0x45)
        /go/src/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go:733 +0xc8
github.com/elastic/beats/libbeat/outputs/elasticsearch.(*Connection).Connect(0xc0000b3200, 0xc1bf997290, 0xc09375ef20)
        /go/src/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go:712 +0x2f
github.com/elastic/beats/libbeat/outputs/elasticsearch.(*Client).Connect(0xc0000b3200, 0x67, 0x0)
        /go/src/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go:705 +0x2d
github.com/elastic/beats/libbeat/outputs.(*backoffClient).Connect(0xc0004e2f30, 0x10, 0xc09375ef88)
        /go/src/github.com/elastic/beats/libbeat/outputs/backoff.go:48 +0x33
github.com/elastic/beats/libbeat/publisher/pipeline.(*netClientWorker).run(0xc000183540)
        /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/output.go:98 +0x1ed
created by github.com/elastic/beats/libbeat/publisher/pipeline.makeClientWorker
        /go/src/github.com/elastic/beats/libbeat/publisher/pipeline/output.go:48 +0xe0
goroutine 114 [select]:
```
