### ISSUE TITLE
[Filebeat] setup check gives spurious ILM error

### ISSUE THREAD

**Issue by faec** [elastic/beats#16336]
- Version: Filebeat 7.2.0, 7.6.0
- Operating System: confirmed on MacOS
- Discuss Forum URL: https://discuss.elastic.co/t/error-index-management-filebeat-to-logstash/218849
- Steps to Reproduce: Run `filebeat setup -e` with the following configuration:
    ```
    setup.ilm.enabled: false

    filebeat.inputs:
    - type: log
      paths: ["/var/log/*.log"]

    output.logstash:
      hosts: ["192.168.1.104:5044"]
    ```

This gives the result `2020-02-14T12:45:57.733-0500    ERROR   instance/beat.go:921    Exiting: Index management requested but the Elasticsearch output is not configured/enabled` even though ILM is disabled.

This doesn't appear to trigger on a real Filebeat run (`filebeat -e`), only on `setup`.

This seems possibly related to #14589 but is still reproducible at head.
