### ISSUE TITLE
[Agent] Dataset definition when running the Agent in standalone mode.

### ISSUE THREAD

**Issue by ph** [elastic/beats#16344]
I had a discussion with @roncohen concerning the Agent configuration syntax in the context of running the agent in standalone mode and we were trying to find a way to simplify the amount of data that the user would need to enter.  This is a full configuration (generated by fleet)

https://github.com/elastic/beats/blob/32b4ef7b8627ab4ee03837f02d912a391a2d7025/x-pack/agent/docs/agent_configuration_example.yml#L173-L218

Ideally we would like to use a syntax similar to the following with the **id** and the **dataset** removed

```yaml
   streams: 
   - metricset: ccr 
   - metricset: cluster_stats 
```

Could we make the "dataset" part of the default modules definition in the go code? https://github.com/elastic/beats/blob/master/metricbeat/module/elasticsearch/cluster_stats/cluster_stats.go

@ruflin WDYT? Do you think it would be possible, it is required or we are at risk of breaking something?

**Comment by roncohen** [comment]
I think we should strive to make it even simpler. I realize this may require metricbeat specific code in Agent if we can't do it in metricbeat, but i think it's worth it. As an example:

```
- type: elasticsearch/metrics 
   hosts: ["http://localhost:9200"]
   metricsets: ['ccr',  'cluster_stats']
```
or (equivalent result):
```
- type: elasticsearch/metrics 
   hosts: ["http://localhost:9200"]
   metricsets: 
   - ccr
   - cluster_stats
```

could be expanded by Agent (or metricbeat?) into the regular form

**Comment by ruflin** [comment]
I'm on board with both suggestions. The part I prefer in the proposal from @ph is that it is obvious for the user it is different streams. The part I prefer in @roncohen suggestion is that it is simpler and just an input config (reminds me a lot of our module config ;-) ).

@roncohen The part that is not clear to mea in your proposal, how will the metricset specific configs look like with your option? Is what you propose just a magic shortcut and the way it is proposed at the moment would still work if someone needs additional configs?

For the dataset on the metricbeat side: Yes, we should do this. It is already possible today to do this inside the go code as far as I remember (https://github.com/elastic/beats/blob/master/metricbeat/mb/event.go#L140, yes it is called Namespace there for historical reasons ...). Having the dataset on the Metricbeat side will keep the agent code simple.

**Comment by roncohen** [comment]
I was thinking it would just be a magic shortcut. As i see it, most people will not need to change the defaults of a metricset. If they do, they can combine them:

```
- type: elasticsearch/metrics 
   hosts: ["http://localhost:9200"]
   metricsets: 
   - ccr
   - cluster_stats
   streams:
    - id?: {id}
      metricset: enrich 
      dataset: elasticseach.enrich 
      period: 10s
```

anyway, not something we absolutely must do now, but i do think we need to keep the getting-started experience in sight and stay vigilant about not complicating the experience for 95% of the users to let the 5% configure something
