### ISSUE TITLE
[Filebeat] Autodiscovery logs.processors does not convert string into a MapStr

### ISSUE THREAD

**Issue by blakerouse** [elastic/beats#16343]
When using labels on Docker or annotations on Kubernetes to add processors to a container the runner fails to be created because the value of the annotation name is not converted from a `string` to a `common.MapStr` before passing the information to the runner.

Use the follow configuration:

```
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

output.console:
  pretty: true
```

Start the container:

`docker run -l 'co.elastic.logs/processors.add_fields={"fields":{"foo":"bar"}}' busybox echo hello`

Errors with:

`Error creating runner from config: can not convert 'string' into 'object' accessing 'processors.0.add_fields'`
