### ISSUE TITLE
[Filebeat] Ingest node pipeline automatic configuration

### ISSUE THREAD

**Issue by cdalexndr** [elastic/beats#16367]
**Describe the enhancement:**
Allow configuration of ingest node pipelines inside _filebeat.yml_, ex:
```
pipelines:
  - name: test-pipeline1
    description: Test pipeline1
    processors:
      - lowercase:
          field: agent.name
  - name: test-pipeline2
    description: Test pipeline2
    processors:
      - set:
          if: ctx.foo == 'someValue'
          field: found
          value: true

output.elasticsearch:
  hosts: ["localhost:9200"]
  pipeline: "test-pipeline1"
```
Currently it's allowed to specify pipeline name in output configuration, but it must be created with the API before use.

**Describe a specific use case for the enhancement or feature:**
Automatization of ingest node configuration.
Manual configuration using API is error prone, and automatic configuration with init shell scripts is hard (wait until es is running, then run 'curl' commands).
