### ISSUE TITLE
Add some way of parametrization to metricbeat light modules

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#16366]
**Describe the enhancement:**

There are some cases where it would be handy to have some way of parametrization or templatization in light modules, so a value set in the user configuration can later be used in the configuration defined in the manifest.

This would have some benefits:
* Some cases cannot be covered at all without this feature
* Configuration closer to the use case instead of to the underlying input
* Common configuration options between metricsets of mixed modules (modules with light and native metricsets)

Current alternatives are implementing the metricset as a native one, or make the input more generic so it allows this kind of parametrization.

**Use case for parametrization:**
 
For example if we were to implement an IIS metricset, based on the `windows.perfmon` metricset, we may want to expose a configuration setting more familiar with the use case, and consistent with similar settings of other native metricsets in the same module:

From this user configuration:
```
- module: iis
  metricsets:
    - website
  website.name: ["hello"]
```
And this manifest:
```
input:
  module: windows
  metricset: perfmon
  defaults:
    perfmon.filter_by_instance: "${config.website.name}"
  ...
```
We would generate this final configuration:
```
- module: iis
  metricsets:
    - website
  perfmon.filter_by_instance: ["hello"]
```

This would be similar to autodiscover templates, and limited to parametrization.

**Use case for templatization:**

There can be cases where we want to generate multiple configuration blocks based on arrays of settings. For example to monitor several databases in azure we may want something like this:

From this user configuration:
```
- module: azure
  metricsets:
  - database_account
  resource_groups: ["infrastructure", "test"]
```
And _something like_ this manifest:
```
default: true
input:
  module: azure
  metricset: monitor
  defaults:
    resources:
    {{ range $i, $group := .config.resource_groups }}
    - resource_query: "select where group is '{{$group}}' and type is 'db'"
      metrics:
      ...
    {{ end }}
```
Would generate this final configuration:
```
- module: azure
  metricsets:
    - monitor
  resources:
    - resource_query: "select where group is 'infrastructure' and type is 'db'"
      metrics:
      ...
    - resource_query: "select where group is 'test' and type is 'db'"
      metrics:
      ...
```

If we go in this direction for templatization, we may want to use the very same format for modules as filebeat, this would also allow to define ingest pipelines for metricbeat modules.
