### ISSUE TITLE
Filebeat: co.elastic.logs/json.* label hints not working with Docker Compose

### ISSUE THREAD

**Issue by daz1761** [elastic/beats#16383]
`co.elastic.logs/json.*` label not working with Docker-Compose.

I have a Docker-Compose file that uses labels to denote the `json` format my container is outputting via `STDOUT`.  Filebeat processes the logs and sends to elasticsearch, but the `json` formatting is not as it should be.

```
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
```

```
myloggingapp:
    container_name: loggingapp
    image: myloggingapp:docker
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/json.keys_under_root: true
      co.elastic.logs/json.add_error_key: true
      co.elastic.logs/json.overwrite_keys: true
      co.elastic.logs/json.message_key: message
    networks:
      - esnet   
```

I have my entire log as a jsonified string in the `message` key:
`
message:  {\"@timestamp\":\"2020-02-18T13:33:35.3012653+00:00\",\"level\":\"Information\",\"messageTemplate\":\"The value of i is {LoopCountValue}\",\"message\":\"The value of i is 1\",\"fields\":{\"LoopCountValue\":1,\"SourceContext\":\"WebAppLogger.Startup\",\"Environment\":\"Production\",\"ApplicationName\":\"My .NET Core Logging Application\"}}`

For confirmed bugs, please report:
- Version: 7.5.2
- Operating System: OSX (Docker)
- Steps to Reproduce:

**Comment by blakerouse** [comment]
How do you currently have filebeat running? I assume being on OSX that filebeat is also running inside of docker?

I tried to reproduce this issue but was unable to with latest 7.6.0, did you try 7.6.0?

I used the following compose file:

```
version: "3"

services:
  myloggingapp:
    container_name: loggingapp
    image: gnegri/lorem-ipsum.logger
    command: -f JSON -m 10
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/json.keys_under_root: true
      co.elastic.logs/json.add_error_key: true
      co.elastic.logs/json.overwrite_keys: true
      co.elastic.logs/json.message_key: MESSAGE
```

With this filebeat config:

```
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

output.console:
  enabled: true
  pretty: true
```

Filebeat outputted the following events to the console correctly, getting the message body from `MESSAGE`.

**Comment by daz1761** [comment]
> How do you currently have filebeat running? I assume being on OSX that filebeat is also running inside of docker?

Yes I'm running the stack from containers under OSX.

> I tried to reproduce this issue but was unable to with latest 7.6.0, did you try 7.6.0?

Yes I tried the latest 7.6.0.

> command: -f JSON -m 10

Mind you, I don't have this line in my `docker-compose`

**Comment by blakerouse** [comment]
The `command: -f JSON -m 10` was only for the example image I was using to test the feature. Maybe try that image to see if it works? I am currently unable to reproduce the issue you are having.

**Comment by daz1761** [comment]
I've just copied your config and I am now using `output.console` to go *back to basics* instead of the Elasticsearch output and I am getting this bombarding the terminal at a million miles an hour making my computer fan go full speed.

```
{
filebeat        |   "@timestamp": "2020-02-26T10:19:38.543Z",
filebeat        |   "@metadata": {
filebeat        |     "beat": "filebeat",
filebeat        |     "type": "_doc",
filebeat        |     "version": "7.6.0"
filebeat        |   },
filebeat        |   "docker": {
filebeat        |     "container": {
filebeat        |       "labels": {
filebeat        |         "com_docker_compose_oneoff": "False",
filebeat        |         "com_docker_compose_project_config_files": "../docker-compose.yml",
filebeat        |         "org_label-schema_version": "7.6.0",
filebeat        |         "com_docker_compose_container-number": "1",
filebeat        |         "org_label-schema_url": "https://www.elastic.co/products/beats/filebeat",
filebeat        |         "com_docker_compose_project_working_dir": "/Users/daz1761/Developer/elasticstack-lab-master",
filebeat        |         "license": "Elastic License",
filebeat        |         "description": "Filebeat sends log files to Logstash or directly to Elasticsearch.",
filebeat        |         "com_docker_compose_service": "filebeat",
filebeat        |         "org_label-schema_license": "Elastic License",
filebeat        |         "org_label-schema_name": "filebeat",
filebeat        |         "org_label-schema_vcs-ref": "6a23e8f8f30f5001ba344e4e54d8d9cb82cb107c",
filebeat        |         "org_label-schema_schema-version": "1.0",
filebeat        |         "org_label-schema_vendor": "Elastic",
filebeat        |         "org_label-schema_vcs-url": "github.com/elastic/beats",
filebeat        |         "com_docker_compose_version": "1.25.4",
filebeat        |         "org_label-schema_build-date": "2020-02-05T23:06:39Z",
filebeat        |         "com_docker_compose_project": "elasticstack-lab-master",
filebeat        |         "com_docker_compose_config-hash": "b5192b7222d1681e51bf2b3489846a72f13fa3d839e5a5cd2abe29aa595d07a4"
filebeat        |       }
filebeat        |     }
filebeat        |   },
filebeat        |   "container": {
filebeat        |     "id": "ef6eab56acdeb3803bddad5b42114f5fb974d490b30452cd186e60fd27bd2d90",
filebeat        |     "name": "filebeat",
filebeat        |     "image": {
filebeat        |       "name": "myfilebeat:docker"
filebeat        |     },
filebeat        |     "labels": {
filebeat        |       "com_docker_compose_container-number": "1",
filebeat        |       "com_docker_compose_oneoff": "False",
filebeat        |       "com_docker_compose_version": "1.25.4",
filebeat        |       "org_label-schema_vcs-url": "github.com/elastic/beats",
filebeat        |       "description": "Filebeat sends log files to Logstash or directly to Elasticsearch.",
filebeat        |       "org_label-schema_vcs-ref": "6a23e8f8f30f5001ba344e4e54d8d9cb82cb107c",
filebeat        |       "org_label-schema_version": "7.6.0",
filebeat        |       "org_label-schema_schema-version": "1.0",
filebeat        |       "org_label-schema_build-date": "2020-02-05T23:06:39Z",
filebeat        |       "com_docker_compose_project_working_dir": "/Users/daz1761/Developer/elasticstack-lab-master",
filebeat        |       "com_docker_compose_service": "filebeat",
filebeat        |       "org_label-schema_vendor": "Elastic",
filebeat        |       "com_docker_compose_config-hash": "b5192b7222d1681e51bf2b3489846a72f13fa3d839e5a5cd2abe29aa595d07a4",
filebeat        |       "org_label-schema_license": "Elastic License",
filebeat        |       "com_docker_compose_project_config_files": "../docker-compose.yml",
filebeat        |       "org_label-schema_name": "filebeat",
filebeat        |       "com_docker_compose_project": "elasticstack-lab-master",
filebeat        |       "license": "Elastic License",
filebeat        |       "org_label-schema_url": "https://www.elastic.co/products/beats/filebeat"
filebeat        |     }
filebeat        |   },
filebeat        |   "agent": {
filebeat        |     "type": "filebeat",
filebeat        |     "ephemeral_id": "274f80a8-3bb3-4f95-88a7-7fbbd1691d1a",
filebeat        |     "hostname": "ef6eab56acde",
filebeat        |     "id": "171cd323-cf10-4270-9cd1-bcef9d079626",
filebeat        |     "version": "7.6.0"
filebeat        |   },
filebeat        |   "log": {
filebeat        |     "offset": 6164359,
filebeat        |     "file": {
filebeat        |       "path": "/var/lib/docker/containers/ef6eab56acdeb3803bddad5b42114f5fb974d490b30452cd186e60fd27bd2d90/ef6eab56acdeb3803bddad5b42114f5fb974d490b30452cd186e60fd27bd2d90-json.log"
filebeat        |     }
filebeat        |   },
filebeat        |   "stream": "stdout",
filebeat        |   "ecs": {
filebeat        |     "version": "1.4.0"
filebeat        |   },
filebeat        |   "host": {
filebeat        |     "name": "ef6eab56acde"
filebeat        |   },
filebeat        |   "message": "  },",
filebeat        |   "input": {
filebeat        |     "type": "container"
filebeat        |   }
filebeat        | }
```

So, I changed the output to Elasticsearch, and instead of 11 documents (from my logging app), I have over 2K of documents as it looks like its getting every log message from the ELK stack including Portainer?!  This may explain why the console output (even though its not showing us what we should see i.e. log message, log level, etc.) is outputting so much.

However, when I perform this:

```
{
  "query": {
    "term": {
      "level": "Information"
    }
  },
  "from": 0,
  "size": 10
}
```

It seems to be outputting everything to `json` properly this time:

[image](http://imageshack.com/a/img923/6181/hRq3Ul.png)

So, how can I stop Filebeat reading *all* the containers logs?

Also, your command `command: -f JSON -m 10` didn't not have an effect as expected.

**Comment by blakerouse** [comment]
Glad the JSON parsing is now working correctly. I will close this bug being that it is working.

As for preventing it from reading logs from all containers you can do:

```
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config.enabled: false
```

Then on the container set the label `co.elastic.logs/enabled: true` so that its logs will be read.

**Comment by daz1761** [comment]
Thanks for the reply, 

Please don't close this as I still have an issue.

All along I had this:

```
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      # makes no difference to why we are getting 2.1k documents 
      hints.default_config: false
```

So my problem has not been solved.  I've had to explicitly set the `condition` and `contains` to my Docker image, but this is not good once you start creating more services as I can't explicitly list all the images that Filebeat can collect logs from as there will eventually be too many.
