### ISSUE TITLE
[Agent] Simplify the metrics syntax for the Agent configuration.

### ISSUE THREAD

**Issue by ph** [elastic/beats#16385]
The agent configuration is quite [verbose](https://github.com/elastic/beats/blob/feature-ingest/x-pack/agent/docs/agent_configuration_example.yml#L87-L140) when you want to define metrics. This is less than ideal if you want to use the Agent in standalone an only want to have a few metrics. As discussed in https://github.com/elastic/beats/issues/16344 we could do the following.

When you want to use the default configuration for a metrics we could use 

```yaml
- type: elasticsearch/metrics 
   hosts: ["http://localhost:9200"]
   metricsets: ['ccr',  'cluster_stats']
```

If you want to overrides some of the configuration options for some metrics set we would fallback to the more verbose syntax.

```yaml
- type: elasticsearch/metrics 
   hosts: ["http://localhost:9200"]
   metricsets: 
   - ccr
   - cluster_stats
   streams:
    - id?: {id}
      metricset: enrich 
      dataset: elasticseach.enrich 
      period: 10s
```
