### ISSUE TITLE
[Agent] Initial support for constraints 

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#16409]
Configuration constraint is a rule/condition which needs to be met for configuration to be evaluated and applied. 
Evaluation of constraint happens before configuration is send to process.
They are defined at the `datasource` instance level with top level constraints as a followup.

### Format

```yml
datastources:
  - #datasource
    constraints:
      - condition1
      - condition2
```

Conditions are strings in a form of Boolean expressions
e.g
` "${host.architecture} == x86_64"` or 
`"${os.platform} == ‘linux’ OR ${os.platform} == ‘darwin’"`

Full Example:

```yml
datasources:
 - id: nginx-x1
   enabled: true
   namespace: prod
   constraints: 
     - "${host.architecture} == x86_64" 
     - "${os.platform} == ‘linux’ OR ${os.platform} == ‘darwin’" 
     - "validate_version(${agent.version}, ‘^8.0.0’)" 
```

At this stage we will support these operators: `==`, `!=`, `<`, `<=`, `>`, `>=` as provided by `boolexp` package
and implement new `validate_version` function.

Specified operators support only simple types: numbers, floats, strings
Comparison of versions needs to be done with `validate_version`. Using `>`, etc will compare them as strings.

### Validate version
`validate_version` function takes 2 arguments, first one is a variable holding a version string in semver format (`1.2.4`, `6.4`...) second one is a condition it should met.

Conditions supported are described using `-`, `~`, `^ ` version notation described here: https://github.com/Masterminds/semver#tilde-range-comparisons-patch

usage would look like this 
```yml
   constraints: 
     - "validate_version(${agent.version}, ‘8.1.0’)"  # version is equal to 8.1.0
     - "validate_version(${agent.version}, ‘8.1.x’)"  # version major and minor matches
     - "validate_version(${agent.version}, ‘^8.1.0’)"  # version is >= 8.1.0 and < 9.0.0
     - "validate_version(${agent.version}, ‘~8.0.0’)" # version is >= 8.1.0 and < 8.2.0
     - "validate_version(${agent.version}, ‘8.0.0-8.0.15’)" # version is in specified range
```

### Supported variables

All variables used with constraints needs to be ECS compliant.
We will support a fixed set of fields. If we encounter not recognized field validation will fail with `configuration error`.

These fields needs to be supported for first iteration:
- Agent
  - agent.id					
  - agent.version			
- Host
  - host.architecture		
- Operating system
  - os.family		
  - os.kernel			
  - os.platform			
  - os.version
