### ISSUE TITLE
[Agent] Support for sets in constraints

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#16410]
Followup to: #16409

With initial constraints working we need to provide support for sets. User should be enabled to specify a set as an argument and compare sets or evaluate whether or not a specified item is part of the set.

Evaluation
```yml
datasources:
 - id: nginx-x1
   enabled: true
   namespace: prod
   constraints:
     - "${some_set.variable} == ['first', 'second']" 
```

Order does not matter so 
```yml
datasources:
 - #datasource
   constraints:
     - "${some_set.variable} == ['first', 'second']" 
```

is equal to 
```yml
datasources:
 - #datasource
   constraints:
     - "${some_set.variable} == ['second', 'first']" 
```

### Additional operators

To make work with sets even more helpful we will support 2 new operators `IN` and `NOT IN`.
E.g.
```yml
datasources:
 - #datasource
   constraints:
     - "${os.platform} IN ['darwin', 'linux']" 
```

or 

```yml
datasources:
 - #datasource
   constraints:
     - "${host.architecture} NOT IN ['x86', 'x86_64']" 
```
