### ISSUE TITLE
[Agent] Support for maps in constraints

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#16411]
Followup to: #16410

User should be enabled to specify a map as an argument and compare them.

Evaluation
```yml
datasources:
 - id: nginx-x1
   enabled: true
   namespace: prod
   constraints:
     - "${some_map.variable} == {'first': 'foo', 'second': 'bar'}" 
```

Order does not matter so 
```yml
datasources:
 - #datasource
   constraints:
     - "${some_map.variable} == {'second': 'bar', 'first': 'foo'}" 
```

is equal to 
```yml
datasources:
 - #datasource
   constraints:
     - "${some_map.variable} == {'first': 'foo', 'second': 'bar'}" 
```
