### ISSUE TITLE
[Agent] Support for top level constraint

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#16413]
As for now constraints can be defined at the datasource level. 

Enable definition of constraints at the top level with the same format.
If conditions at top level are not met. Whole configuration is discarded without error.

```yml
constraints:
  - "${host.architecture} == x86_64" 
  - "${os.platform} IN [‘linux’, ’darwin’]
  - "validate_version(${agent.version}, ‘^8.0.0’)" 
datasources:
  ...
```
