### ISSUE TITLE
[Agent] Support for HAS operator in constraints

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#16412]
Followup to: #16411

As user is able to work with maps and compare them, enable them to find out whether map has an item specified.

Evaluation
```yml
datasources:
 - id: nginx-x1
   enabled: true
   namespace: prod
   constraints:
     # true if map contains key 'first', value does not matter
     - "${some_map.variable} HAS 'first'" 

     # true if map contains key 'first' with a value 'bar'
     - "${some_map.variable} HAS {'first': 'foo'}" 

     # true if map contains key 'first' with a value 'foo' and key `second` with a value 'bar'
     - "${some_map.variable} HAS {'first': 'foo', 'second': 'bar'}" 
```

This operator should work with list as well

```yml
datasources:
 - id: nginx-x1
   enabled: true
   namespace: prod
   constraints:
     - "${some_set.variable} HAS 'prod'" 
```
