### ISSUE TITLE
Dropping event: no topic could be selected

### ISSUE THREAD

**Issue by plumcraft** [elastic/beats#16458]
Hello,

After some research on current issues, i didn't find any solution.

When i'm using a filebeat version greater than 7.3.2 release, filebeat is throwing the following error message :
`Dropping event: no topic could be selected`

Here the filebeat configuration 

```
    filebeat.yml: |
      fields_under_root: true
      fields:
        cluster: testing 
      filebeat.inputs:
      - type: container
        stream: all
        paths:
          - /var/lib/docker/containers/*/*.log
        processors:
          - add_kubernetes_metadata:
        multiline.pattern: '^[[:space:]]+(at|\.{3})\b|^Caused by:'
        multiline.negate: false
        multiline.match: after

      filebeat.modules:
        - module: system
          auth:
            enabled: true
            var.paths: ["/var/log/secure"]

      output.kafka:
        metadata.full: true
        hosts: ['kafka_ip:9092']
        topic: '%{[kubernetes.container.name]}-%{[kubernetes.namespace]}-%{[cluster]}'
```

I've checked 7.4.0 filebeat breaking change and there is only this that could conflict with (https://github.com/elastic/beats/pull/13051) but my understanding is "in_cluster" is now guessed and no need to add anymore.

Thank you.
