### ISSUE TITLE
Make use of prometheus filter settings on IBM-MQ Metricbeat module

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#16513]
After https://github.com/elastic/beats/issues/15493 is closed/implemented we can refactor `ibmmq` light module introduced with https://github.com/elastic/beats/pull/15301.

We could change [manifest file](https://github.com/elastic/beats/blob/master/x-pack/metricbeat/module/ibmmq/qmgr/manifest.yml), tuning `defaults to look like:

```
defaults:
  metrics_path: /metrics
  metrics_filters:
    include: ["ibmmq_.*"]
```

cc: @mtojek
