### ISSUE TITLE
[Agent] Exposed stream.type, stream.dataset and stream.namespace to every events.

### ISSUE THREAD

**Issue by ph** [elastic/beats#16562]
Some modules define like [Suricata](https://github.com/elastic/beats/pull/16496) a single input where mixed events are generated: metrics, logs or alerts. The identification of the data is often done in the ingest pipeline, where the type is generated from fields or values from the data.

 The way the agent operates it assumes unique type of data would be generated from input. This is normally true, but there is an exception like the Suricata system. To allow the maximun flexibility we should add fields to the event to allow the target **index** to be generated inside an ingest pipeline.

To do so we want to add the following fields to each event.

- stream.dataset
- stream.type
- stream.namespace

The values for `stream.type` and `stream.namespace` are **inherited** from the datasource and the input definition.

So see the following examples for generation rules:

```yaml
datasources: 
   - id: nginx-x1 
     namespace: prod 
     inputs: 
       - type: logs 
         streams: 
           - id: {id} 
             enabled?: true # default to true 
             dataset: nginx.acccess 
             paths: /var/log/nginx/access.log 
```

Will generate an event with the following values:

```yaml
fields:
 type: logs
 namespace: prod
 dataset: nginx.access
```
