### ISSUE TITLE
[libbeat] Disk spool ACKs messages even if there are no valid outputs

### ISSUE THREAD

**Issue by faec** [elastic/beats#16676]
- Version: repo head
- Operating System: MacOS

Steps to Reproduce: 

This can be seen in Filebeat with the Kafka input. With a Kafka topic `acktest` (containing some test messages) and the following `filebeat.yml`:

```
filebeat.inputs:
- type: kafka
  hosts: ["localhost:9092"]
  topics: ["acktest"]
  group_id: "filebeat"

queue.spool: ~

output.elasticsearch:
  hosts: ["localhost:9200"]
```

Filebeat will read all the messages from the topic and ACK / commit the reads to Kafka, even if the output configuration is invalid (in my test configuration I had no elasticsearch running at all).

The intention seems to have been that commiting the events to the disk spool is a sort of "handoff" that lets the input release them, but considering how easy it is to run a Filebeat instance with bad output settings and how hard it is to tell where the data's gone from anywhere outside that particular Filebeat directory, we should probably rethink this policy -- it _doesn't_ provide the "end-to-end ACK" that was the intention with the Kafka input. (It's also very different from how we handle ACKs with the in-memory queue, which may be unexpected.)
