### ISSUE TITLE
Change spacing in processor examples

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#16696]
**Describe the enhancement:**
Current processor docs show different spacing than what we show in the docs. It's a minor thing, but annoying when you copy/paste examples from the docs because you need to adjust the spacing.

~It would be easier to fix the yml files than the docs, so let's fix it there.~
REVISED: Sounds like it would be better to fix the docs.

Change the docs to match the yaml. Here's what we have right now:

beatname.yml: 

```
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
```

docs and reference.yml: 
```
processors:
- add_host_metadata: ~
- add_cloud_metadata: ~
- add_docker_metadata: ~
- add_kubernetes_metadata: ~
```
Also make sure the docs all follow the same convention (most except `dissect` do, I think).
