### ISSUE TITLE
Getting elasticsearch license expiration error from filebeat and metricbeat

### ISSUE THREAD

**Issue by suresh447** [elastic/beats#16725]
For confirmed bugs, please report:
- Version: 7.6.0 
- Operating System: Ubuntu 16.04
I have installed metricbeat 7.6.0 and filebeat 7.6.0 on ubuntu machine. Initially i am able to send logs and metrics from metricbeat and filebeat but from the past 2 days i am getting 

Exiting: Couldn't connect to any of the configured Elasticsearch hosts. Errors: [Error connection to Elasticsearch http://30.18.0.101:9200: Connection marked as failed because the onConnect callback failed: cannot retrieve the elasticsearch license from the /_xpack endpoint, Filebeat requires the default distribution of Elasticsearch. Please make the endpoint accessible to Filebeat so it can verify the license.: could not extract license information from the server response: unknown state, received: 'expired']

Please help me how can i resolve this issue and how can i extend my license.

**Comment by TuXbOy06** [comment]
having same problem here with metricbeat

**Comment by boosnadal** [comment]
please help , i'm facing this issue

**Comment by AvinavaBasu** [comment]
This is because the latest versions are having some compatibility issues 
I spent a lot of time, but there's no proper documentation regarding this.
Downloading the rpm for 6.4.0:

curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.4.0-x86_64.rpm
sudo rpm -vi filebeat-6.4.0-x86_64.rpm

Make the necessary changes in /etc/filebeat/filebeat.yml

Now let Filebeat set up its indexes and dashboards with

sudo filebeat setup --pipelines --template --dashboards

sudo filebeat test output ==> Now it will work fine
sudo service filebeat start
journalctl -f

**Comment by Sauerbrei** [comment]
I've came across the same issue in a docker-swarm environment, while I want to store the data on an elasticsearch-service configured with AWS. 
So I changed first the image version from 7.9.3 to 6.4.0 like this

```
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.4.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - path/to/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
      - path/to/docker.yml:/usr/share/metricbeat/modules.d/docker.yml
    user: root
```
make sure (in your docker.yml), you only load metricsets which are available in 6.4.0, like this
```
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
#    - "event"
    - "healthcheck"
    - "info"
#    - "image"
    - "memory"
    - "network"
```
anyway, metricbeat is actually sending something and has a connection to the aws-service. but I still see no data incoming.
