### ISSUE TITLE
Using both processors script and drop_event at the same time

### ISSUE THREAD

**Issue by cmiscloni** [elastic/beats#16794]
Hey all,

I can't get it to work WinlogBeat when i want to use drop_event and - script at the same time.
The process start but it seems that my filter is ignored.

 **Is the script processor is the first executing ?**

**or maybe this is the normal behaviour that it doesn't work together ?**

Thanks

Conf:

```
 winlogbeat.event_logs:
 
   - name: Security
     ignore_older: 72h
     processors:
     - script:
           lang: javascript
           id: security
           file: ${path.home}/module/security/config/winlogbeat-security.js                
       drop_event.when.or:
              - equals.process.executable: 'C:\Windows\System32\conhost.exe'
               - equals.process.executable: 'C:\Windows\System32\RuntimeBroker.exe'
```

I tried like that too:

```
 winlogbeat.event_logs:
 
   - name: Security
     ignore_older: 72h
     processors:
     - script:
           lang: javascript
           id: security
           file: ${path.home}/module/security/config/winlogbeat-security.js                
       drop_event.when.or:
              - equals.event_data.process.executable: 'C:\Windows\System32\conhost.exe'
               - equals.event_data.process.executable: 'C:\Windows\System32\RuntimeBroker.exe'
```
