### ISSUE TITLE
Metricbeat Kubernetes module: labels.dedot needed in some metricsets

### ISSUE THREAD

**Issue by eedugon** [elastic/beats#16845]
Tested in Metricbeat 7.6 with K8s 1.15 and 1.16.

In order to make all `state_*` metricsets to work I had to add `labels.dedot: true` to my configuration. Otherwise I was getting indexing problems (mapping parsing exceptions) at Elasticsearch side. This was happening in some documents only, so not applied to all metricsets.

The same happened with `container / pod / node / system / volume` metricsets (I don't know which one exactly). Without `labels.dedot` there was problems when indexing some content into Elasticsearch.

The final config I had to use was:
```
    - module: kubernetes
      metricsets:
        - node
        - system
        - pod
        - container
        - volume
      labels.dedot: true
      annotations.dedot: true
      period: 10s
      host: ${NODE_NAME}
      hosts: ["https://${HOSTNAME}:10250"]
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      ssl.verification_mode: none
```

And
```
  kubernetes.yml: |-
    - module: kubernetes
      metricsets:
        - state_node
        - state_deployment
        - state_replicaset
        - state_pod
        - state_container
        - state_cronjob
        - state_resourcequota
        # Uncomment this to get k8s events:
        - event
      period: 10s
      host: ${NODE_NAME}
      hosts: ["kube-state-metrics:8080"]
      labels.dedot: true
      annotations.dedot: true
      include_creator_metadata: false
```

Based on a conversation with @exekias , `labels.dedot` should be the default behavior of the module.

Could we check if this is really a bug?

Notes:
- I'm not totally sure why I added `include_creator_metadata: false` in my working configuration or if it's related with the issue, just in case.
- Linking this issue where apparently something similar was reported and closed: https://github.com/elastic/beats/issues/13409
