### ISSUE TITLE
regex  not work with `"^\\{"`

### ISSUE THREAD

**Issue by bigpigeon** [elastic/beats#16896]
Docker Image

    docker.elastic.co/beats/filebeat:7.6.1

Problem

    I have log file continuous output below log:
    $ kc  logs microservice-sample 
    {"level":"info","ts":1583748924.6115315,"caller":"v3@v3.1.0/default.go:34","msg":"test log","svcName":"XXX"}
    ...
    
I use grep command tool to filter it normally

    $ kubectl  logs microservice-sample |grep "^\\{"
     {"level":"info","ts":1583748924.6115315,"caller":"v3@v3.1.0/default.go:34","msg":"test log","svcName":"XXX"}
    ...

but use filebeat cannot collect it,here it my filebeat config

```
filebeat.autodiscover:
    providers:
    - type: kubernetes
        templates:
        - condition:
            equals:
                kubernetes.labels.kind: microservice
            config:
            - type: container
                paths:
                - /var/log/containers/*-${data.kubernetes.container.id}.log
                max_bytes: 1048576 # 1M
                include_lines: ["^\\{"] # remove it is normal
                json.keys_under_root: false
                json.overwrite_keys: false
                json.add_error_key: true
                json.message_key: msg
                json.ignore_decoding_error: true
                # fields_under_root: true
                tail_files: true
                # close_removed: true
                # clean_removed: true 
                # ignore_older: 12m
                close_inactive: 10m
                processors: 
                - add_tags:
                    tags: [json-scan,microservice]
                    target: "jobs"
```
