### ISSUE TITLE
[Heartbeat] Multiple TCP ports cause map concurrency error

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#16917]
TCP monitors that specify multiple ports cause concurrent access issues. The following config will run for a short (<1m) period then fail due to concurrent map access

```
# Configure monitors inline
heartbeat.monitors:
- type: tcp
  hosts: ["127.0.0.1"]
  ports: [9200, 5601, 123, 456]
  schedule: '@every 10s'
```

We should fix the internal code to not share datastructures.
