### ISSUE TITLE
why include_lines/exclude_lines filter after json parse

### ISSUE THREAD

**Issue by bigpigeon** [elastic/beats#16919]
When my log has the two formats of log as below:

```
{"level":"info","ts":1583821714.455572,"caller":"v3@v3.1.0/default.go:34","msg":"test log","svcName":"XXX"}
panic: panic after 60 seconds

goroutine 13 [running]:
main.main.func1.2()
	/builds/microservices/sample/main.go:39 +0xce
created by main.main.func1
	/builds/microservices/sample/main.go:37 +0x306
```

and then I want to scan it with two collector

```
- type: container
             config:
                - type: container
                  paths:
                    - /var/log/containers/*-${data.kubernetes.container.id}.log
                  max_bytes: 1048576 # 1M
                  include_lines: ["\\A^\\{"]
                  json.keys_under_root: false
                  json.overwrite_keys: false
                  json.add_error_key: false
                  json.message_key: msg
                  json.ignore_decoding_error: true
                  fields_under_root: true
                  tail_files: false
                  close_removed: true
                  clean_removed: true 
                  ignore_older: 12m
                  close_inactive: 10m
                  processors: 
                    - add_tags:
                        tags: 
                          - json-scan
                          - microservice
                        target: "jobs"
                - type: container
                  paths:
                    - /var/log/containers/*-${data.kubernetes.container.id}.log
                  exclude_lines: 
                    - "\\A\\{"
                  multiline.pattern: "\\Apanic"
                  multiline.negate: true
                  multiline.match: after
                  multiline.flush_pattern: '\\A[\\{\\[]'
                  fields_under_root: true
                  tail_files: true
                  # close_removed: true
                  # clean_removed: true 
                  # ignore_older: 12m
                  close_inactive: 10m
     
                  processors: 
                    - add_tags:
                        tags: [multiline-scan,microservice-stack]
                        target: "jobs"
```

but the json collector will never collector any log, because json parse before the include_lines/exclude_lines filter, the message field is "test log"
