### ISSUE TITLE
[Functionbeat] manager should handle certificates

### ISSUE THREAD

**Issue by timdev** [elastic/beats#16969]
**Describe the enhancement:**

`package`, `deploy`, and `update` should be handle packaging certificates and keys mentioned in the configuration file.

While packaging for deployment, the manager should include configured certificate/key files, and rewrite the paths in `functionbeat.yml`.  So if in my hand-edited `functionbeat.yml` I have `output.logstash.ssl.key: /local/path/to/functionbeat.key`, the packages should include that key file in the zip (at, say, `ssl/functionbeat.key`), and rewrite that path in the functionbeat.yml that is included in the zip file.

**Describe a specific use case for the enhancement or feature:**

My current use case is as follows: I have functionbeat shipping logs to logstash running on a server.  I want mutual TLS.  In configese:

```
output.logstash:
  hosts: ["logs.example.com:5044"]
  ssl.certificate_authorities: ["my-root-ca.crt"]
  ssl.certificate: functionbeat.crt
  ssl.key: functionbeat.key
```

My current dance looks like:

* Figure out if I'm deploying or updating (see #14414)
* Deploy or update functionbeat.  Now I've got a broken function because the TLS-related files weren't included.
* Run `./functionbeat package` to generate a `package-aws.zip` deployment package.  (deploy/update don't leave such an artifact anyplace obvious).
* `zip -u package-aws.zip functionbeat.crt functionbeat.key my-root-ca.crt` to add the certs
* Use the AWS CLI to update my function with the new deployment payload (`aws lambda update-function-code --function-name my-functionbeat-fn --zip-file fileb://package-aws.zip`)
