### ISSUE TITLE
Filebeat has the problem of repeatedly collecting the entire contents of the log file

### ISSUE THREAD

**Issue by xiongjunkun** [elastic/beats#17144]
My application has a strange log file scrolling strategy: Assume that the threshold for the number of log file scrolls is 1000, and the threshold for the log file scroll size is 500M. When the threshold for the log file scroll size is exceeded, the file f999 is renamed to the file f1000, File f998 is renamed to file f999, ..., file f1 is renamed to file f2. Then a new file f is created, and the application continues to write logs to file f.
On the other hand, we collect these log files by using filebeat v6.6.1 and write them to another file output.log (this is to avoid factors such as network jitter). By analyzing the contents of the file output.log , We found that filebeat repeatedly collects logs, and filebeat always collects the entire content of a log file, not part of it.
After a lot of experiments, we found that the reasons that led to filebeat repeatedly collecting logs are:
1. Assume that at time t0, input performs a scan operation and the obtained file list is [f, f1, ..., f998, f999, f1000];
2, Assume that at time t1, input performs CleanRemoved operation. If the file f998 is renamed to f999, but f997 is not renamed to f998, then there is no file f998 in the file system, filebeat thinks that file f998 has been deleted, so filebeat Will delete its state (in fact, filebeat deletes the state of file f999).
3. Assume that at time t2, input performs a scan operation. If the obtained file list includes the file f999 (perhaps another name, but the inode and device have not changed), then filebeat considers this to be a new file and will recollect this file. Content, which leads to the problem of repeated collection of filebeat.

Excuse me, for the above situation, if there is any other way to disable the CleanRemoved configuration?

The code causing the above problem is:
```
	if p.config.CleanRemoved {
		for _, state := range p.states.GetStates() {
			// os.Stat will return an error in case the file does not exist
			stat, err := os.Stat(state.Source)
			if err != nil {
				if os.IsNotExist(err) {
					p.removeState(state)
					logp.Debug("input", "Remove state for file as file removed: %s", state.Source)
				} else {
					logp.Err("input state for %s was not removed: %s", state.Source, err)
				}
			} else {
				// Check if existing source on disk and state are the same. Remove if not the case.
				newState := file.NewState(stat, state.Source, p.config.Type, p.meta)
				if !newState.FileStateOS.IsSame(state.FileStateOS) {
					p.removeState(state)
					logp.Debug("input", "Remove state for file as file removed or renamed: %s", state.Source)
				}
			}
		}
	}
```
The filebeat.yaml file content is:
```
filebeat.inputs:
- type: log
  paths:
    - /home/xxx/log/*.log
  clean_removed: false

output.file:
  path: "/home/xxx/filebeat"
  filename: output.log
  rotate_every_kb: 1073741824
  number_of_files: 16
  permissions: 0600

logging.level: debug
logging.selectors: []
logging.to_stderr: false
logging.to_syslog: false
logging.to_eventlog: false
logging.to_files: true
logging.files:
  path: /home/xxx/filebeat_log/
  name: filebeat_log.log
  rotateonstartup: true
  rotateeverybytes: 104857600 
  keepfiles: 64
  permissions: 0600
```
We observe debug information as described below:
```
2020-03-18T23:09:59.230+0800	DEBUG	[input]	log/input.go:174	Start next scan
2020-03-18T23:09:59.243+0800	DEBUG	[input]	log/input.go:255	lstat(/home/xjk/log/demo.921.log) failed: lstat /home/xjk/log/demo.921.log: no such file or directory
```
The above two lines of logs tell us that this is indeed the case.
And the following line of code proves that our thinking is correct.
```
2020-03-18T22:52:01.341+0800	DEBUG	[input]	log/input.go:207	Remove state for file as file removed: /home/xxx/log/f.583.log
```
