### ISSUE TITLE
Metricbeat fails to collect kubernetes system metrics due to lacking privileges

### ISSUE THREAD

**Issue by babadofar** [elastic/beats#17168]
For confirmed bugs, please report:
- Version: 
7.6.1
- Operating System: 
Amazon EKS, kubernetes version 1.15
- Discuss Forum URL: https://discuss.elastic.co/t/metricbeat-kubernetes-fails-to-collect/217414/5

- Steps to Reproduce: 
Install elastic helm chart for metricbeat with default settings
this error is logged: 

     Error fetching data for metricset kubernetes.node: error doing HTTP request to fetch 'node' 
     Metricset data: HTTP error 403 in : 403 Forbidden

- Steps to fix:
Add the `  - nodes/stats` resource, to make the list of  clusterrolerules like this:

```
rules:
- apiGroups:
  - extensions
  - apps
  - ""
  resources:
  - namespaces
  - pods
  - events
  - deployments
  - nodes
  - nodes/stats
  - replicasets
  verbs:
  - get
  - list
  - watch
```
