### ISSUE TITLE
[Agent] Enable post install hooks

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#17197]
As this default magic does not have any index specified it then falls into default index specified in ES output and is in form `metricbeat-version-date`. This behavior is not wanted as beats should do what agent asks them to do. 

I suggest we enhance our `spec/{beat}.yml` (files we are baking in on compile time and are not coming from fleet) with additional field `post_install`. 
This field would look exactly like `rules` collection but with different rule set. 

Sample should look like this

```yaml
name: Metricbeat
cmd: metricbeat
args: ["-E", "setup.ilm.enabled=false"]
configurable: grpc
post_install:
- remove: 
    path: some/tricky/file
- chown:
    path: this/is/executable
    perms: 0770
rules:
- extract_list_items:
    path: datasources
    item: inputs
    to: inputsstreams
```

Benefit of having it here is that this is the single point of our codebase which is beats specific, solution is flexible enough to support different kind of crazy things and we can even introduce pre-run section as well when we need it with the same rule set (e.g cleanup data before run...)
