### ISSUE TITLE
Support Filebeat Kafka input events to one or more module pipelines

### ISSUE THREAD

**Issue by dcode** [elastic/beats#17254]
**Describe the enhancement:**
Currently, users can use the Kafka input plugin to stream events from Kafka to Elasticsearch and apply the normal beat-local transformations and connect to an Elasticsearch ingest pipeline. It would be great if we could connect Kafka inputs to existing beats pipelines in a generic way. Further, for particular datasets, it would be helpful to allow a filter to be applied in order to activate, allowing the Kafka input to potentially feed more than one module/dataset.

**Describe a specific use case for the enhancement or feature:**
Zeek has a [community provided plugin](https://github.com/apache/metron-bro-plugin-kafka) for Kafka output that is commonly used in high-scale scenarios or cases where multiple different consumers may way to ingest the same data in a pub/sub manner. The default behavior of this plugin streams all log types to a single topic (e.g. conn, dns, http logs all are written to a topic of "zeek-logs"). To connect existing Zeek modules in Filebeat to these inputs, currently, one would have to perform one of the following:

a) Change the default (and most common) configuration from all to a topic to a user-maintained configuration for every log type zeek generates, then modify the Zeek module for each dataset to use that Kafka topic as an input
b) Consume all the logs from the single topic, modify the Zeek module for each dataset to consume from that topic, then filter out all logs that do not apply to that dataset.

Both of these approaches are less than ideal for efficiency. In the first case you have N consumer processes making network connections to the Kafka broker to consume data. In the second case, you're potentially transferring each log entry N times, but dropping logs on the floor.

**Proposal**
I haven't student the harvester side of filebeat, so this could be way off architecturally, but currently you can set the output pipeline in the input stanza, if the event is parsed prior to passing from the Kafka harverster, maybe you could specify the module/dataset at input time.

```yaml
filebeat.inputs:
- type: kafka
  hosts:
    - kafka-broker-1:9092
    - kafka-broker-2:9092
  topics: ["my-topic"]
  group_id: "filebeat"
  
  module: "zeek"
# path or stream is the name used in Zeek scripts for log types
# logs exported from Corelight put the log type in this field for instance
  dataset: "%{@path}" 
```

**Final note**
If this was done in some sort of generic way, filebeat would be a great option for larger enterprises that need to ship logs that are commonly centralized into a central Kafka broker into Elasticsearch while re-using the modules shipped with the product. Today, the best options to do this are Logstash (which does this quite well, but sometimes more overhead than needed just to ship logs) or Kafka Connect (or similar).

@andrewkroh @peasead @spartan782 @kwbyron
