### ISSUE TITLE
[auditbeat][windows] file changes events are generated although no changes

### ISSUE THREAD

**Issue by fixed77** [elastic/beats#17347]
auditbit generates change events for some files, although there were no file changes. 
Below is an example of an event. 
The time it takes to create and modify the file is different from the time of the event. I found the initial_scan event of this file in logs. All fields are completely identical, including the sha1 hash of the file.

Created event:
```
{
  "_index": "auditbeat-xxx_log-2020.03.28",
  "_type": "_doc",
  "_id": "v6l0HnEBt3RRCzaXyPfB",
  "_score": 1,
  "_source": {
    "@timestamp": "2020-03-28T00:05:00.922Z",
    "fields": {},
    "@version": "1",
    "service": {
      "type": "file_integrity"
    },
    "file": {
      "ctime": "2019-07-12T12:50:34.645Z",
      "owner": "NT SERVICE\\TrustedInstaller",
      "mtime": "2019-03-06T12:24:00.000Z",
      "size": 5296128,
      "type": "file",
      "uid": "S-1-5-80-956008885-3418522649-1831038044-1853292631-2271478464",
      "inode": "562949953792977",
      "path": "C:\\Windows\\assembly\\GAC_64\\System.Web\\2.0.0.0__b03f5f7f11d50a3a\\System.Web.dll"
    },
    "hash": {
      "sha1": "f2aa8ee7aeb421ff2723ae6a428b235f75e57898"
    },
    "event": {
      "module": "file_integrity",
      "dataset": "file",
      "action": [
        "updated"
      ]
    },
    "host": {
      "name": "win1"
    }
  },
  "fields": {
    "@timestamp": [
      "2020-03-28T00:05:00.922Z"
    ],
    "file.mtime": [
      "2019-03-06T12:24:00.000Z"
    ],
    "file.ctime": [
      "2019-07-12T12:50:34.645Z"
    ]
  }
}
```
Auditbeat configuration:
```
auditbeat.modules:
- module: file_integrity
  paths:
  - C:/windows
  - C:/windows/system32
  - C:/Program Files
  - C:/Program Files (x86)
  recursive: true
- module: system
  datasets:
    - process 
  state.period: 12h


#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["x.x.x.x:5044"]
```

Versions:
- auditbeat version 7.6.1 (amd64), libbeat 7.6.1 [c1c49432bdc53563e63e9d684ca3e9843626e448 built 2020-02-28 23:09:20 +0000 UTC]
- Windows 10 Version 1909 (OS Build 18363.720)
