### ISSUE TITLE
[Metricbeat] Cloudwatch metricset does not collect S3 tags correctly

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#17419]
- Version: master and previous branches
- Discuss Forum URL: https://discuss.elastic.co/t/aws-cloudwatch-cant-collect-s3-tags-from-aws-s3-namespace/225930
- Steps to Reproduce: 
1. Make sure the AWS account you use for testing has S3 buckets(with tags).
2. Enable Metricbeat aws module: `./metricbeat modules enable aws`
3. Change `modules.d/aws.yml` to:
```
- module: aws
  period: 86400s
  metricsets:
    - cloudwatch
  metrics:
    - namespace: AWS/S3
      tags.resource_type_filter: s3
```
4. Start Metricbeat `./metricbeat -e`
5. You should see events in Kibana but no `aws.tags.*` field.
