### ISSUE TITLE
Regression: system/services pattern_filter not working

### ISSUE THREAD

**Issue by urso** [elastic/beats#17414]
Testing 7.7.0bc the `service.pattern_filter` is not filtering out any services on CentOS 7. When using `ssh*`, or even a pattern that does not match `abcdefgh`, all services are still collected.

Centos7 setup Vagrantfile:

```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
end
```

modules.d/system.yml:

```
- module: system
  period: 10s
  metricsets:
    - service
  service.state_filter: ["active"]
  service.pattern_filter: ["ssh*"]
```

Expected output: only report `sshd.service`.
Actual output: All active services have been reported
