### ISSUE TITLE
Policy name for beats not working anymore in 7.6.1 

### ISSUE THREAD

**Issue by phlegx** [elastic/beats#17433]
In packetbeat.yml I used to have this configuration to map all indices to my default ilm policy:

```
setup: 
  ilm:
    enabled: auto
    overwrite: true
    policy_name: default-metric-beats-ilm
```

Actually this was working but after upgrading to 7.6.1 the new indices of packetbeat (and my other beats) are no more linked to this policy.

Has there something changed. Do I need to set this differently now?

**Comment by ChrsMark** [comment]
cc: @elastic/beats

**Comment by phlegx** [comment]
@ChrsMark Is this ah known bug If I may ask? If yes, is there a workaround?

**Comment by ChrsMark** [comment]
Not sure @phlegx . This will require investigation.

**Comment by phlegx** [comment]
Hello again. May I ask if somebody had some time to look at this issue?

**Comment by ChrsMark** [comment]
Hey @phlegx I was not able to reproduce it with `7.6.2`.

Using:
```
setup.ilm:
  enabled: auto
  overwrite: true
  policy_name: default-metric-beats-ilm-42-test
```

Running:
```
./metricbeat -e -d "*" setup 
```

Then going to Kibana Index Management page and here what I see:
![Screenshot 2020-04-09 at 12 53 56](https://user-images.githubusercontent.com/11754898/78882932-79acb700-7a61-11ea-99a1-74573756d911.png)

So I guess that it works on my end? I use `7.6.2` for the whole stack (es, kibana, beats)

Let me know if that helps.
