### ISSUE TITLE
[Winlogbeat] Winlogbeat can't keep up with the EPS value of our Windows Event Collector

### ISSUE THREAD

**Issue by macEar** [elastic/beats#17680]
# Winlogbeat version

```
PS C:\temp\winlogbeat> .\winlogbeat.exe version

winlogbeat version 7.6.2 (amd64), libbeat 7.6.2 [d57bcf8684602e15000d65b75afcd110e2b12b59 built 2020-03-26 05:32:51 +0000 UTC]
```

# Operating System

```
PS C:\temp\winlogbeat> (Get-WMIObject win32_operatingsystem).name

Microsoft Windows Server 2016 Standard...
```

# Bug Info

We have Windows Server used as a Windows Event Collector. With a help of `perfmon.exe` we checked our EPS for WEC. The average value is equal to `1224`, but of course it changes during the day and sometimes is up to 6000 events per second.

Winlogbeat configuration:

```yml
winlogbeat.registry_file: .winlogbeat.yml
winlogbeat.shutdown_timeout: 15s
winlogbeat.event_logs:
  - name: ForwardedEvents
    forwarded: true
    batch_read_size: 1024
    ignore_older: 24h
queue:
  mem:
    events: 65472
    flush.min_events: 0
output.console:
  enabled: true
  codec.json:
    pretty: false
    escape_html: false
path.config: ${path.home}
setup.template.enabled: false
setup.template.name: "winlogbeat-%{[agent.version]}"
setup.template.pattern: "winlogbeat-*"
setup.template.fields: "${path.config}/fields.yml"
setup.template.overwrite: true
setup.template.settings:
  index:
    number_of_shards: 1
    codec: best_compression
    number_of_routing_shards: 30
    number_of_replicas: 0
setup.ilm.enabled: false
logging.level: debug
logging.to_files: true
logging.files:
http.enabled: true
http.host: localhost
http.port: 5066
```

With a help of a simple powershell script we scraped our winlogbeat http endpoint for some metrics to evaluate approximate value of events processed for 30s.

```powershell
$headers = New-Object "System.Collections.Generic.Dictionary[[String],[String]]"
$headers.Add("Accept", 'application/json')
For ($i = 0; $i -lt 5; $i++) { 
$response = Invoke-RestMethod 'http://localhost:5066/stats?pretty' -Headers $headers -Method GET
$result =@{}
$result["№"] = $i.toString()
$result["Total"] = $response[0].libbeat.output.events.total
$result | Format-Table
Start-Sleep -s 30
}
```

The output is as follows:

```
Name                           Value
----                           -----
Total                          241521
№                              0

Name                           Value
----                           -----
Total                          241521
№                              1

Name                           Value
----                           -----
Total                          261888
№                              2

Name                           Value
----                           -----
Total                          261888
№                              3

Name                           Value
----                           -----
Total                          261888
№                              4
```

Quick/rough math:
1. 261888 - 241521 = 20367
Events which has been processed by winlogbeat for 150s (30s * 5)
2. 20367 / 150 = 135,78 
Events per second for winlogbeat
3. Compare it to WEC EPS:

![image](https://user-images.githubusercontent.com/47277788/79095406-82183100-7d84-11ea-8762-11b3dafda2d2.png)

**135,78 is much too less than 778,298**..

We tried to increase `batch_read_size`, but as it is written on your web-site, Windows API returns the error for any value greater than 1024:

```
2020-04-13T12:04:03.658+0700	INFO	service/service_windows.go:101	Attempted to register Windows service handlers, but this is not a service. No action necessary
2020-04-13T12:04:03.660+0700	DEBUG	[eventlog]	eventlog/wineventlog.go:181	WinEventLog[ForwardedEvents] using subscription query=<QueryList>
  <Query Id="0">
    <Select Path="ForwardedEvents">*[System[TimeCreated[timediff(@SystemTime) &lt;= 86400000]]]</Select>
  </Query>
</QueryList>
2020-04-13T12:04:03.661+0700	DEBUG	[winlogbeat]	beater/eventlogger.go:131	EventLog[ForwardedEvents] opened successfully
2020-04-13T12:04:03.661+0700	WARN	eventlog/wineventlog.go:312	WinEventLog[ForwardedEvents] EventHandles returned error The parameter is incorrect.
2020-04-13T12:04:03.661+0700	WARN	beater/eventlogger.go:148	EventLog[ForwardedEvents] Read() error: The parameter is incorrect.
2020-04-13T12:04:03.661+0700	INFO	beater/eventlogger.go:123	EventLog[ForwardedEvents] Stop processing.
```

Is it possible to configure winlogbeat to be able to process all events on time? We are losing a lot of events due to this issue.

**Comment by andrewkroh** [comment]
You can try out the new reader implementation if you like. It should be faster. It's not released yet.

- Docs: https://www.elastic.co/guide/en/beats/winlogbeat/7.7/configuration-winlogbeat-options.html#_event_logs_api
- Download: https://beats-ci.elastic.co/job/elastic+beats+7.7+multijob-package-linux/gcsObjects/

**Comment by macEar** [comment]
@andrewkroh thanks for your reply!

I'll try to upgrade winlogbeat up to 7.7.0 downloaded through the abovementioned link. In `winlogbeat.yml` configuration file I'll add this:

```yml
winlogbeat.event_logs:
  - name: ForwardedEvents
    api: wineventlog-experimental
    forwarded: true
    batch_read_size: 1024
    ignore_older: 24h
```

After that I'll monitor how winlogbeat copes with our volume of events per second. Then I'll write back about results.
