### ISSUE TITLE
[Filebeat] Kubernetes autodiscovery timeout on K8s API (AKS), silently ships no logs

### ISSUE THREAD

**Issue by mirzmaster** [elastic/beats#17689]
We're seeing the following problem using a Filebeat daemonset deployed to a managed AKS cluster:  After a Filebeat pod is restarted (perhaps due to node maintenance or some other factor, doesn't seem to matter), Kubernetes autodiscovery times out trying to query for pod information.

> 2020-04-11T03:00:07.998Z	ERROR	kubernetes/util.go:85	kubernetes: Querying for pod failed with error: Get https://10.85.16.1:443/api/v1/namespaces/core-beats/pods/filebeat74-j67nt: dial tcp 10.85.16.1:443: i/o timeout

Following the timeout, Filebeat silently operates while shipping no logs (harvester reports 0 open files).  It also does not connect to an Elastic monitoring cluster to report its status.

> 2020-04-11T17:35:07.985Z	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":49940,"time":{"ms":24}},"total":{"ticks":88870,"time":{"ms":49},"value":88870},"user":{"ticks":38930,"time":{"ms":25}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":11},"info":{"ephemeral_id":"c3998888-f3bd-4c01-9e5d-8f47f536f10f","uptime":{"ms":52530067}},"memstats":{"gc_next":12264080,"memory_alloc":11099472,"memory_total":2757293664},"runtime":{"goroutines":43}},"filebeat":{**"harvester":{"open_files":0,"running":0}**},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":0,"events":{"active":0}}},"registrar":{"states":{"current":0}},"system":{"load":{"1":0.56,"15":0.39,"5":0.42,"norm":{"1":0.07,"15":0.0488,"5":0.0525}}}}}}

- Version: Filebeat 7.4.1
- Operating System: Linux (off-the-shelf Docker image)
- Discuss Forum URL: https://discuss.elastic.co/t/filbeat-on-kubernetes-autodiscover-stops-sending-logs/157571
- Steps to Reproduce: Run FB daemonset on AKS with very low CPU/mem limits to force a pod restart.

Filebeat configuration:
```
filebeat.autodiscover:
  providers:
    - type: kubernetes
      templates:
        - condition:
            equals:
              kubernetes.labels.myapp-filebeat-logging: "true"
          config:
            - type: docker
              containers.ids:
                - "${data.kubernetes.container.id}"
              combine_partial: true
              multiline:
                pattern: '^\\['
                negate:  true
                match:   after
        - condition:
            not:
              equals:
                kubernetes.labels.myapp-filebeat-logging: "true"
          config:
            - type: docker
              containers.ids:
                - "${data.kubernetes.container.id}"
              combine_partial: true

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

setup.template.settings:
  setup.ilm.enabled: false
  setup.template.enabled: false
setup.kibana:
  host: "kibana.domain.com:443"
  protocol: "https"
output.elasticsearch:
  hosts: ["elastic.domain.com:443"]
  protocol: "https"
  pipeline: all_logs
  username: elastic
  password: "${ES_PASS}"
  bulk_max_size: 3200
  worker: 2
template:
  name: "filebeat"
  path: "fields.yml"
  overwrite: true
monitoring:
  enabled: true
  elasticsearch:
    username: elastic
    password: "${ES_PASS}"
```
