### ISSUE TITLE
[Heartbeat] Hints based autodiscover ports settings 

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#17771]
Hints based autodiscover seems to require an [explicit port](https://github.com/elastic/beats/blob/master/heartbeat/autodiscover/builder/hints/monitors.go#L184) which is confusing. We should investigate ways to improve the experience here, at a minimum improving the error message.

**Comment by neidiom** [comment]
Related to #17674

**Comment by captnbp** [comment]
Hi guys,

Do you have any ETA ? We'd like to use Kubernetes hints to discover the public URL in the Pod hosts annotation.

This check on ${data.host} / ${data.port} is a blocking issue for us...

Thanks !

**Comment by thenickfish** [comment]
I'm using (abusing?) Heartbeat the the same way, adding annotations to monitor uptime on a public facing service, rather than the internal Kubernetes Service objects or pods. FWIW, I've been working around this port check by appending a junk parameter to the end of the public url:

```yaml
annotations:
    co.elastic.monitor/type: http
    co.elastic.monitor/hosts: https://example.site.com/some-api/healthcheck?ignore=${data.port}
    co.elastic.monitor/schedule: "@every 5s"
```

I'm not sure of the history of why the ${data.port} check is being done beyond [this PR comment](https://github.com/elastic/beats/pull/13119#discussion_r319727659). If fixing this is as simple as allowing hosts through without having the port present, I could probably open a PR to do that.
