### ISSUE TITLE
Can I use Conditional Processors in Functionbeat

### ISSUE THREAD

**Issue by chipzzz** [elastic/beats#17776]
From functionbeat reference, it looks like only a few are allowed. However, would I be able to use something like 

```
processors:
  - add_cloud_metadata: ~
  - canary-log:
    when:
      equals:
        log_group: "random_log"
    - add_fields:
        fields:
          index_name: "canary-log"
```

I package the functionbeat template file and push it to the cloud. Upon trying to generate the template file. Filebeat barks 

> Output: error loading config file: yaml: line 42: did not find expected key

line 42 refers to "log_group" key, as log_group will be a field derived from the events processed and it doesn't exist at functionbeat template packaging time.

Can I avoid this and if I avoid this would this work ?
