### ISSUE TITLE
Journalbeat add_kubernetes_metadata unreliably detects K8s PODs

### ISSUE THREAD

**Issue by timp87** [elastic/beats#17792]
I have several K8s clusters (1.15 and 1.13) with journalbeat running as a daemonset which pulls all journald events from a worker/master.
I set docker log-driver to journald to have containers and host log in one place - in journal. 
The OS is CentOS 7.7 with 4.19 kernel.
Here is our config:

```
    fields:
      cluster_name: {{ .Values.cluster_name }}
      component_type: kbm
      env_name: {{ .Values.env_name }}
      location: {{ .Values.location }}
      log_format: plain
      log_type_initial: kubernetes-journalbeat
      hostname: ${NODE_NAME}
    fields_under_root: true

    journalbeat.inputs:
      - paths: []
        seek: cursor
        cursor_seek_fallback: head
        include_matches:
          - "_COMM=dockerd"
          - "_COMM=kubelet"
          - "_COMM=containerd"
          - "_TRANSPORT=kernel"
          - "_SYSTEMD_UNIT=docker.service"
          - "_SYSTEMD_UNIT=kubelet.service"
          - "_SYSTEMD_UNIT=containerd.service"

        processors:
        ...
          - add_kubernetes_metadata:
              in_cluster: true
              labels.dedot: true
              annotations.dedot: true
              default_indexers.enabled: false
              default_matchers.enabled: false
              indexers:
                - container:
              matchers:
                - fields:
                    lookup_fields: ["container.id"]
        ...


    output.logstash:
      hosts:
        - "logstash:1999"

    http.enabled: {{ .Values.http.enabled }}
    http.port: {{ .Values.http.port }}

    logging.to_stderr: true
    logging.level: warning
```

I run journalbeat 6.8.8 now. It's more or less OK.

I've recently tried to upgrade to latest journalbeat 7.6.2 and noticed increased amount of logs in ELK processed by journalbeat which are missing kubernetes metadata. So events which are definitely from 8s pods are not enriched with their pod metadata.
I tried to investigate it and it turns out 7.6.2 detects pods much worse than 6.8.8. I have no idea why and how it works, but here are my observations:
- "pause" containers are never enriched with pod metadata using both journalbeat 6.8 and 7.6. It's OK for me.
- 7.6 detects pods much slower than 6.8: i. e. some very first events from a container didn't have pod metadata attached, but events one second later did. I've never seen this with 6.8
- 7.6 was not able to detect some long- and still running daemonset pods at all. 
- 7.6 was not able to detect some short living Job pods. 6.8 was OK with that.

How I check? I look at kibana, at amount of events from containers which do not have kubernetes.pod.uid field (container.id_truncated: exists, kubernetes.pod.uid: not exsists), see attached journalbeat_upgrade.png screenshot.
![journalbeat_upgrade](https://user-images.githubusercontent.com/13275598/79569723-d42cbf80-80c0-11ea-8019-daa56c55b348.png)

I rolled back to 6.8.8

I'm ready to provide more info, but don't know which one.
