### ISSUE TITLE
Elastic-Agent: Create and document a docker image

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#17826]
I'm developing the testing environment for Integrations and will need a dedicated Docker image for the Elastic Agent.
I plan to run the container as part of the cluster (alongside ES, Kibana and EPR) and enroll to the Kibana fleet (I can write this orchestration).

**Comment by ruflin** [comment]
@michalpristas ^

**Comment by michalpristas** [comment]
@mtojek docker image is part of packaging output, if you want to just run  basic docker image which connects to running kibana use `mage demo` this will prepare docker image and runs it with shared network.

you can tweak beahavior of the image by providing some env vars descirbed here https://github.com/elastic/beats/blob/master/dev-tools/packaging/templates/docker/docker-entrypoint.elastic-agent.tmpl#L5

**Comment by mtojek** [comment]
Thank you for the information, but actually I need a more concise solution, a similar one to e.g. Kibana:

```yaml
  kibana:
    image: docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601/login"]
      retries: 600
      interval: 1s
    volumes:
      - ./kibana.config.yml:/usr/share/kibana/config/kibana.yml
```

I assume that the goal `mage demo` is to present the running agent and connect to the cluster. My goal is to run a boot up entire environment (ES, Kibana, EPR, enrolled Agent) with a single command.

@michalpristas @ruflin I'm looking forward to hear input on that.
