### ISSUE TITLE
[Metricbeat] Allow to specify more than one regions in googlecloud module

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#17835]
Right now googlecloud module only accept `region` parameter for one specific region, not a list of regions, which means if you want to collect metrics from more than one region, you need to repeat the config like below:
```
- module: googlecloud
  metricsets:
    - compute
  region: "europe-west1"
  project_id: elastic-observability
  credentials_file_path: "/Users/kaiyansheng/Downloads/elastic-observability-d17781618202.json"
  exclude_labels: false
  period: 300s
- module: googlecloud
  metricsets:
    - compute
  region: "europe-west3"
  project_id: elastic-observability
  credentials_file_path: "/Users/kaiyansheng/Downloads/elastic-observability-d17781618202.json"
  exclude_labels: false
  period: 300s
- module: googlecloud
  metricsets:
    - compute
  region: "us-central1"
  project_id: elastic-observability
  credentials_file_path: "/Users/kaiyansheng/Downloads/elastic-observability-d17781618202.json"
  exclude_labels: false
  period: 300s
```

It will be nice introduce a config parameter called `regions` to accept a list of strings:
```
- module: googlecloud
  metricsets:
    - compute
  regions:
    - us-central1
    - europe-west3
    - europe-west1
  project_id: elastic-observability
  credentials_file_path: "/Users/kaiyansheng/Downloads/elastic-observability-d17781618202.json"
  exclude_labels: false
  period: 300s
```
