### ISSUE TITLE
Kube-proxy support for Openshift

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#17863]
**Describe the enhancement:**
Right now [`proxy` metricseat](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-kubernetes-proxy.html)  does not work out of the box on Openshift installations. It would be nice to investigate how this can happen.

**Extra info**

Logs collected while trying to deploy on Openshift:

```2020-04-06T11:35:37.554Z        INFO    module/wrapper.go:252   Error fetching data for metricset kubernetes.proxy: error getting processed metrics: error making http request: Get http://localhost:10249/metrics: dial tcp 127.0.0.1:10249: connect: connection refused```
Notes:

`kube-proxy` pod runs on `kube-proxy` namespace and not `kube-system`. Not that it would be the issue since we are trying to access host's network.

What is actually running in this pod:
```
kubectl -n kube-proxy exec -it kube-proxy-hj5zb /bin/bash           
[root@minishift origin]# curl http://0.0.0.0:10249/metrics
curl: (7) Failed connect to 0.0.0.0:10249; Connection refused
[root@minishift origin]# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.1  0.6 475736 28220 ?        Ssl  10:04   0:10 openshift start network --enable=proxy --listen=https://0.0.0.0:8444 --config=/etc/origin/node/node-config.yaml
root      5784  0.4  0.1  20244  7036 ?        Ss   11:55   0:00 /bin/bash
root      5831  0.0  0.0  55184  1844 ?        R+   11:55   0:00 ps aux
Info:
```

Container image: `openshift/origin-control-plane:v3.11.0`

Info: https://github.com/openshift/sdn

**Comment by exekias** [comment]
This one is still valid, please don't close it 🙂

**Comment by Protopopys** [comment]
@exekias, i have some problem with my OpenShift cluster. 
I have read the documentation and it looks like _Namespace: openshift-sdn configmaps: sdn-config --> metricsBindAddress: 0.0.0.0:29101_  is the solution to the problem. I am currently testing an elastic-agent configuration with the following settings:

```
          - data_stream:
              dataset: kubernetes.proxy
              type: metrics
            metricsets:
              - proxy
            hosts:
              # Kubernetes
              # - 'localhost:10249'
              # Openshift
              - 'localhost:29101'
            period: 10s
```
