### ISSUE TITLE
Clarification about settings like "exclude_files" which require to be under "input"

### ISSUE THREAD

**Issue by toby-sutor** [elastic/beats#17873]
It would be great if we could clarify that settings like `exclude_files:` need to be configured under an `input:` section. This is barely documented somewhere.

For example, for the mssql module, the following does not work:
````
# Module: mssql
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.6/filebeat-module-mssql.html
- module: mssql
  # Fileset for native deployment
  log:
    enabled: true
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths:
    - C:\Microsoft SQL Server\MSSQL13.MSSQLSERVER\*
    exclude_files: ['\.trc$']
````
This, however works:
````
# Module: mssql
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.6/filebeat-module-mssql.html
- module: mssql
  # Fileset for native deployment
  log:
    enabled: true
    input:
    exclude_files: ['\.trc$']
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths:
    - C:\Microsoft SQL Server\MSSQL13.MSSQLSERVER\*
````

This is neither documented at:
https://www.elastic.co/guide/en/beats/filebeat/7.6/filebeat-module-mssql.html
nor https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#filebeat-input-log-exclude-files or in the reference configuration at https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-reference-yml.html.
The only reference I could find is at https://www.elastic.co/guide/en/beats/filebeat/master/advanced-settings.html and it is not very enlightening from my perspective.

Would you please review and check if this can be mentioned somewhere in the docs? Thank you.
