### ISSUE TITLE
SSL certificate files abandoned during deploy

### ISSUE THREAD

**Issue by NicketUttarwar** [elastic/beats#17885]
### Summary + Recreation Steps
Following the exact documentation found [here](https://www.elastic.co/guide/en/beats/functionbeat/current/configuration-ssl.html) I was able to create a cloudformation stack that manages a lambda function, however the lambda kept failing and when I dug through the cloudwatch logs the error:
 `2020-04-19T18:21:04.805Z ERROR tlscommon/tls.go:51 Failed reading certificate file <path to file>/applogs.crt: open <path to file>/applogs.crt: no such file or directory`

I verified this by going to the lambda, clicking the **Actions** dropdown, selecting **Export function**, and then hitting **Download deployment package** which downloaded a zip file containing only the functionbeat executable and my functionbeat.yml configuration file. There was no sign of the certificate files.

From there I realized the lambda doesn't have the certificate files in its deployment package, so I tried setting the [directory structure](https://www.elastic.co/guide/en/beats/functionbeat/current/directory-layout.html) and using the flag `--path.data /Users/nicketuttarwar/<...>/functionbeat/rds-error-cloudwatch-elk/data` during an update, though I got the same error as above. (I also adjusted the config files to source its certificates relative to the /data directory)
At this point the ssl part of the config looked like
```
output.elasticsearch.ssl.certificate_authorities: ["<absolute path to path.home>/data/elastic-ca-cert.pem"]
output.elasticsearch.ssl.certificate: "<absolute path to path.home>/data/applogs.crt"
output.elasticsearch.ssl.key: "<absolute path to path.home>/data/applogs.key"
```

Similarly, I verified that the lambda deployment package didn't contain the certificate files. 

### Successful Workaround
Finally I tried the "workaround" in [this open issue](https://github.com/elastic/beats/issues/16969) and it worked! I manually added the certificate files to my package-aws.zip created through the `./functionbeat package` command and uploaded it to S3 and seeded that link in the lambda. 

Though I wish this worked right out of the box the way it worked in the [documentation](https://www.elastic.co/guide/en/beats/functionbeat/current/configuration-ssl.html)

### Version & OS 
`functionbeat version 7.6.2 (amd64), libbeat 7.6.2 [d57bcf8684602e15000d65b75afcd110e2b12b59 built 2020-03-26 05:16:14 +0000 UTC]`
MacOS Mojave; Version 10.14.5

### Config File
```
functionbeat.provider.aws.endpoint: "s3.amazonaws.com"
functionbeat.provider.aws.deploy_bucket: "<bucket name>"
functionbeat.provider.aws.functions:
  - name: rds-error-cloudwatch-elk
    enabled: true
    type: cloudwatch_logs
    description: "lambda function for RDS error logs"
    role: arn:aws:iam::<account id>:role/FunctionBeatCloudWatchRole
    triggers:
      - log_group_name: /aws/rds/cluster/<...>
      - log_group_name: /aws/rds/cluster/<...>
      - log_group_name: /aws/rds/cluster/<...>

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~

output.elasticsearch.hosts: ["https:<host and port>"]
output.elasticsearch.ssl.certificate_authorities: ["elastic-ca-cert.pem"]
output.elasticsearch.ssl.certificate: "applogs.crt"
output.elasticsearch.ssl.key: "applogs.key"
output.elasticsearch.username: "<username>"
output.elasticsearch.password: "<password>"
output.elasticsearch.ssl.enabled: true
```
