### ISSUE TITLE
[Metricbeat] Discrepancy in graphs when using Prometheus query metricset 

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#17931]
When using Prometheus `query` metricset with queries like `rate(node_cpu_seconds_total{mode="system", cpu="7"}[1m])` sometimes a corresponding graph visualized in Kibana is different from what Prometheus server shows:

Kibana:
![image](https://user-images.githubusercontent.com/1685068/80093464-d2ea0f80-8564-11ea-9fec-29077444c9e6.png)

Prometheus:
![image](https://user-images.githubusercontent.com/1685068/80093477-dbdae100-8564-11ea-8c74-02a5886063ae.png)

From these graphs it's clear that some spikes/sinks are not visualized in Kibana.

cc: @exekias @ChrsMark

**Comment by ChrsMark** [comment]
Hey @sorantis , what kind of visualisation/aggregation do you use? Could it be that Prometheus plots the rate directly but on Kibana we have an extra aggregation on it like `avg`?

**Comment by ChrsMark** [comment]
Tried to reproduce and move it forward:
<img width="1364" alt="Screenshot 2022-02-17 at 1 52 54 PM" src="https://user-images.githubusercontent.com/11754898/154476200-c0b3a000-c5b7-42af-9b20-288bca5758d2.png">
<img width="1617" alt="Screenshot 2022-02-17 at 1 52 41 PM" src="https://user-images.githubusercontent.com/11754898/154476215-11d03519-cea8-4be2-90dd-5f48a9730895.png">



It's clear that we cannot completely replicate what we see in Prometheus graphs since we lack a way to represent the absolute values of the metrics and instead we are only able to plot based on specific aggregations like `avg`, `max`, `rate`. 
In this regard I'm not sure if we can evaluate this further and I would expect that waiting for TSVB improvements (https://github.com/elastic/elasticsearch/issues/74660) is the only option at the moment.

For future reference I'm posting a configuration to re-produce the environment:

`metricbeat/modules.d/prometheus.yml`:
```
- module: prometheus
  metricsets: ["query"]
  hosts: ["0.0.0.0:9090"]
  period: 10s
  queries:
  - name: "instant_vector"
    path: "/api/v1/query"
    params:
      query: 'rate(node_cpu_seconds_total{cpu="7",instance="nodeexporter:9100",job="nodeexporter",mode="system"}[1m])'
```

Prometheus setup: [docker-prometheus-playground](https://github.com/ChrsMark/docker-prometheus-playground)

@jsoriano since we were involved in metrics efforts feel free to comment here!

cc: @akshay-saraswat @masci
