### ISSUE TITLE
Beat name is always overridden by hostname

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#18043]
For confirmed bugs, please report:
- Version: 8.0.0 / `master` but also seen in 7.6.2.
- Operating System: Mac OS X
- Steps to Reproduce: 
1. Create a minimal Filebeat configuration as follows.
   ```
   ## filebeat.test.yml
   name: fb1

   filebeat.inputs:
     - type: stdin
       enabled: true

   output.console:
     enabled: true

   http.enabled: true
   ```
2. Start up an instance of Filebeat with above configuration.
   ```
   ./filebeat -c filebeat.test.yml
   ```
3. Visit http://localhost:5066/. Notice that the `name` field is set to the hostname, instead of the value of the `name` setting from the Filebeat configuration.
   ```
   curl -s 'http://localhost:5066/' | jq
   {
     "beat": "filebeat",
     "hostname": "Shaunaks-MacBook-Pro-Work.local",
     "name": "Shaunaks-MacBook-Pro-Work.local",
     "uuid": "ef61dc4a-8be0-404a-8e8a-d1a8d8bb17d8",
     "version": "7.6.0"
   }
   ```
- Impact:
   One of the places where this information is used is in the Stack Monitoring UI. So if you have two Beats running on the same host but with different `name` settings, they incorrectly show up with the same name (the hostname instead of their respective `name`s) in the UI:

   <img width="1744" alt="Screen Shot 2020-04-28 at 4 54 31 AM" src="https://user-images.githubusercontent.com/51061/80484885-4e551380-890d-11ea-96cb-eb809310ed94.png">
