### ISSUE TITLE
Winlogbeat sets host.name to fqdn

### ISSUE THREAD

**Issue by johncollaros** [elastic/beats#18056]
Comparing beats output in 7.6.2 release:
metricbeat, filebeat: host.name = host.hostname, which is the plain hostname of the machine.
winlogbeat: host.name != host.hostname; host.name = FQDN, host.hostname = plain hostname

This causes Kibana apps such as metric explorer to show two instances of the host.

It's not clear which field should be used, and the beats do not seem to use host.name field consistently.

_Originally posted by @johncollaros in https://github.com/elastic/ecs/issues/498#issuecomment-620346489_

**Comment by MorrieAtElastic** [comment]
I think there are 2 different issues being raised and I am not sure if they should be discussed together: 

(1) winlogbeat assigns FQDN to host.name where as all of the other beats assign the local hostname. There does need to be a consistent policy about this.  

(2) whether host.name should be the same as host.hostname: in the case where the event originates in some other server than the host where the beat is residing, this distinction can be important.

**Comment by MorrieAtElastic** [comment]
https://github.com/elastic/beats/issues/1070 has been open on the FQDN question for several years.

**Comment by drewboswell** [comment]
I use the following as winlogbeat is the only one that does the fqdn thing:

```
# inside winlogbeat.yml
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_fields:
        target: '' # this makes it override the top-level, otherwise it gets inserted into fields.host.name
        fields: 
            host.name: "${COMPUTERNAME}"
```
