### ISSUE TITLE
Beats fail to connect to Elasticsearch with ping

### ISSUE THREAD

**Issue by dahendel** [elastic/beats#1805]
Ping is disabled in my environment and causes errors with beats trying to connect to elasticsearch. I have es http port accessable through a haproxy config and can successfully do a curl and get the following:
```
[user@server]$ curl http://es.haproxy.host:80
{
  "name" : "Fury",
  "cluster_name" : "Clustername",
  "version" : {
    "number" : "2.3.3",
    "build_hash" : "218bdf10790eef486ff2c41a3df5cfa32dadcfde",
    "build_timestamp" : "2016-05-17T15:40:04Z",
    "build_snapshot" : false,
    "lucene_version" : "5.5.0"
  },
  "tagline" : "You Know, for Search"
}
```
However when packetbeat and filebeat try to connect I get the below:
```
2016/06/06 20:40:18.687528 single.go:126: INFO Connecting error publishing events (retrying): 503 Service Unavailable
```

This is on the same box I run the curl command from. The ES cluster is a separate environment. Is there a way to configure beats to test the es connection other than ping?

Output Config:
```
output:

  ### Elasticsearch as output
  elasticsearch:
    # Array of hosts to connect to.
    # Scheme and port can be left out and will be set to the default (http and 9200)
    # In case you specify and additional path, the scheme is required: http://localhost:9200/path
    # IPv6 addresses should always be defined as: https://[2001:db8::1]:9200
    hosts: ["es.haproxy.host:80"]

    # Optional protocol and basic auth credentials.
    #protocol: "https"
    #username: "admin"
    #password: "s3cr3t"

    # Number of workers per Elasticsearch host.
    #worker: 1

    # Optional index name. The default is "packetbeat" and generates
    # [packetbeat-]YYYY.MM.DD keys.
    #index: "packetbeat"

    # A template is used to set the mapping in Elasticsearch
    # By default template loading is disabled and no template is loaded.
    # These settings can be adjusted to load your own template or overwrite existing ones
    template:

      # Template name. By default the template name is packetbeat.
      #name: "packetbeat"

      # Path to template file
      path: "/etc/packetbeat/packetbeat.template.json"

      # Overwrite existing template
      overwrite: true

    # Optional HTTP Path
    #path: "/elasticsearch"
```
