### ISSUE TITLE
filebeat: syslog input TLS client auth not enforced

### ISSUE THREAD

**Issue by hazcod** [elastic/beats#18087]
- Version:  7.6.2
- Operating System: Red Hat Linux 7 
- Steps to Reproduce: 
```yaml
filebeat.inputs:
- type: syslog
  protocol.tcp:
    host: "0.0.0.0:8001"
  ssl:
    enabled: true
    certificate: "foo.crt"
    key: "foo.key"
    client_authentication: true
    verification_mode: true

output.elasticsearch:
  hosts: ["http://localhost:9200"]
```

This works:
`openssl s_client -connect server:8001`, circumventing any mTLS configuration.
I followed https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-syslog.html, which states: `ssledit
Configuration options for SSL parameters like the certificate, key and the certificate authorities to use.

See SSL for more information.

`.
