### ISSUE TITLE
Metricbeat Autodiscover Hints Via Labels Does Not Work - Docker

### ISSUE THREAD

**Issue by daz1761** [elastic/beats#18184]
I am trying to use Docker labels in conjunction with autodiscover hints.  I have already been on the Elastic forums and Stack Overflow and my issue is not resolved.

Here is my docker-compose.  To note, the configuration is copied into the container:

```
version: '2'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - cluster.name=docker-
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - esnet
  metricbeat:
    container_name: metricbeat
    user: root
    image: mymetricbeat:docker
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
    - esnet
  myloggingapp:
    container_name: loggingapp
    image: loggingapp:latest
    environment: 
      - ASPNETCORE_URLS=http://+:8101
    labels:
      "co.elastic.metrics/enabled": "true"
      "co.elastic.metrics/module": "docker"
      "co.elastic.metrics/metricsets": "cpu"
      "co.elastic.metrics/hosts": "$${data.host}:8101"
      "co.elastic.metrics/period": "1m"
    networks:
    - esnet      
  elastichq:
    container_name: elastichq
    image: elastichq/elasticsearch-hq
    ports:
      - 8080:5000
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200
      - HQ_ENABLE_SSL=False
      - HQ_DEBUG=FALSE
    networks:
      - esnet
networks:
  esnet:
```

Let me provide some history in terms of my configuration.  To note, the first two attempts are with the labels from the docker-compose omitted as they are not required.

First I tried this and it works, but the problem is that is fetches all the stats for all containers which is not really what I want:

```
metricbeat.modules:
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 1m
  enabled: true
```

Then I tried this as a second solution, which works, but the problem with this solution is that you have to specifically tell it which docker image to use:

```
metricbeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: "loggingapp"
          config:
            - module: docker
              metricsets: ["cpu", "info"]
              period: 1m
              hosts: ["unix:///var/run/docker.sock"]
              enabled: true
```

Now my third attempt with hints in the docker-compose labels, which is the solution I would like to use.

```
metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
```

This did indeed work on the logging app container, but I get this error on the error message key:

> failed to get docker stats: Cannot connect to the Docker daemon at tcp://172.19.0.2:8101. Is the docker daemon running?

So, I posted this issue on Stack Overflow and I was told I needed to mount more volumes:

```
- "/sys/fs/cgroup:/hostfs/sys/fs/cgroup"
- "/proc:/hostfs/proc"
- "/:/hostfs"
```

Because I am working on Windows, I switched to a Ubuntu VM and ran my stack to see if this made a difference, and it does not.  I still get the same error key.  

If these extra volumes are needed in some way, I am confused as to why I don't need them on my first two attempts.

I also tried changing the `hosts` label in my docker-compose to use the Unix Sock, but this results in no index being created at all in Elasticsearch.
