### ISSUE TITLE
[Filebeat] Add OAuth support to the httpjson input

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#18415]
As user of the Filebeat httpjson input, I would like to be able to pull data from a REST API that requires authentication via OAuth.

An example would be collecting logs from GSuite. For that an OAuth token is required.

**Comment by marc-gr** [comment]
To start with, implementing [the client credentials flow](https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/) seems to be a nice choice, since it is the one allowing server-to-server authorization with no client intervention.

For this the config needs to be extended with something like:

```yaml
filebeat.inputs:
- type: httpjson
  interval: 10s
  oauth2:
    token_url: http://localhost:8282/access/token/request
    client_id: dummy-client-id
    client_secret: dummy-client-secret
  url: http://localhost:8282/foobar
```

There are some providers, that we might want to handle but do not offer support for this flow, like Gsuite, which instead of the `client_id` and `client_secret` [provides a credentials file](https://developers.google.com/identity/protocols/oauth2/service-account). To handle these specific cases we might want to have a specific config object inside the `oauth2`, for example:

```yaml
- type: httpjson
  interval: 10s
  oauth2:
    google:
        credentials_file: /path/to/file
  url: http://localhost:8282/foobar
```

or 

```yaml
- type: httpjson
  interval: 10s
  oauth2:
    provider: google
    credentials_file: /path/to/file
  url: http://localhost:8282/foobar
```

And do different checks based on the provider. An example of how google auth works with the credentials file can be found [in the googlepubsub input](https://github.com/elastic/beats/blob/master/x-pack/filebeat/input/googlepubsub/config.go#L55)

Other specific provider we might want to support is AzureAD, for example.

Also allowing for an optional `scopes` option to let users define specific scopes would be nice.

```yaml
filebeat.inputs:
- type: httpjson
  interval: 10s
  oauth2:
    token_url: http://localhost:8282/access/token/request
    client_id: dummy-client-id
    client_secret: dummy-client-secret
    scopes:
    - scope1
    - scope2
  url: http://localhost:8282/foobar
```

Is there any other consideration you think might be good for the initial implementation?

cc @P1llus

**Comment by P1llus** [comment]
> To start with, implementing [the client credentials flow](https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/) seems to be a nice choice, since it is the one allowing server-to-server authorization with no client intervention.
> 
> For this the config needs to be extended with something like:
> 
> ```yaml
> filebeat.inputs:
> - type: httpjson
>   interval: 10s
>   oauth2:
>     token_url: http://localhost:8282/access/token/request
>     client_id: dummy-client-id
>     client_secret: dummy-client-secret
>   url: http://localhost:8282/foobar
> ```
> 
> There are some providers, that we might want to handle but do not offer support for this flow, like Gsuite, which instead of the `client_id` and `client_secret` [provides a credentials file](https://developers.google.com/identity/protocols/oauth2/service-account). To handle these specific cases we might want to have a specific config object inside the `oauth2`, for example:
> 
> ```yaml
> - type: httpjson
>   interval: 10s
>   oauth2:
>     google:
>         credentials_file: /path/to/file
>   url: http://localhost:8282/foobar
> ```
> 
> or
> 
> ```yaml
> - type: httpjson
>   interval: 10s
>   oauth2:
>     provider: google
>     credentials_file: /path/to/file
>   url: http://localhost:8282/foobar
> ```
> 
> And do different checks based on the provider. An example of how google auth works with the credentials file can be found [in the googlepubsub input](https://github.com/elastic/beats/blob/master/x-pack/filebeat/input/googlepubsub/config.go#L55)
> 
> Other specific provider we might want to support is AzureAD, for example.
> 
> Also allowing for an optional `scopes` option to let users define specific scopes would be nice.
> 
> ```yaml
> filebeat.inputs:
> - type: httpjson
>   interval: 10s
>   oauth2:
>     token_url: http://localhost:8282/access/token/request
>     client_id: dummy-client-id
>     client_secret: dummy-client-secret
>     scopes:
>     - scope1
>     - scope2
>   url: http://localhost:8282/foobar
> ```
> 
> Is there any other consideration you think might be good for the initial implementation?
> 
> cc @P1llus

I think this sounds nice, I think the second choice looked the best personally:

```
- type: httpjson
  interval: 10s
  oauth2:
    provider: google
    credentials_file: /path/to/file
  url: http://localhost:8282/foobar
```

If we are planning to use the provider list from the oauth2 lib (don't know if this is updated?), then we might be able to add the tokenURL for the user and all they would need is minimum provider, client-id, secret and URL.

From what we saw, when authentication as an app towards AzureAD we could not define scope, as it was defined when generating the ID and secret.

Maybe scope should be optional and if tokenurl is not set we should try to retrieve based on provider?
