### ISSUE TITLE
[filebeat] provision ILM policy by code

### ISSUE THREAD

**Issue by MaxymVlasov** [elastic/beats#18479]
**Describe the enhancement:**
I'd like to have mechanism to provision ILM policy that will manage indexes created by filebeat in filebeat configutation, as [it exist in APM-server](https://github.com/elastic/apm-server/blob/c0f47670caa543889907501d1c26820311912991/apm-server.yml#L393-L411), for instance

**Describe a specific use case for the enhancement or feature:**

TL;DR: "Something" as Code case.
If you up and run many EFK for many clients or create temporary environments just for load testing propose etc. you'd like apply your configuration, wait 5 minutes and ready to go without any manual provisioning.

Now I provision ILM policy for filebeat by APM-server. It's ~a crutch~ non-intuitive solution.

**Comment by andresrc** [comment]
Hi @MaxymVlasov,

Thanks for creating the issue. Currently the plan is not to include those features in the beats, I'm afraid, so I'm closing this issue for now.

Anyway, I would be curious to know which kinds of ILM policies do you want to provision for file beats indices.

Thanks!

**Comment by MaxymVlasov** [comment]
All :slightly_smiling_face: 

I use next fields: ([apm-server config syntax](https://github.com/elastic/apm-server/blob/c0f47670caa543889907501d1c26820311912991/apm-server.yml#L393-L411))

```yaml
            - name: "filebeat-dev"
              policy:
                phases:
                  hot:
                    actions:
                      rollover:
                        max_size: "5gb"
                        max_age: "3d"
                      set_priority:
                        priority: 100
                  delete:
                    min_age: "3d"
                    actions:
                      delete: {}
```

But someone else maybe need to use `warm` and `freeze` phases and it settings.
