### ISSUE TITLE
[libbeat] output.file ignores permissions

### ISSUE THREAD

**Issue by vaclavms** [elastic/beats#18563]
Hello,
I found in latest auditbeat version 7.7.0 that auditbeat output file is created with permission 640 even if I set output file permission to 644.

I have this configuration in auditbeat.yml
```
output.file:
  path: "/var/auditbeat/logs"
  filename: auditbeat
  rotate_every_kb: 20000
  number_of_files: 2
  permissions: 0644
```
but output file have permission 640
```
ubuntu:/var/auditbeat/logs# ls -alF
total 184
drwxr-xr-x 2 root root   4096 May 14 05:12 ./
drwxr-xr-x 3 root root   4096 May 14 05:11 ../
-rw-r----- 1 root root 177590 May 14 05:12 auditbeat
```
Get response from Andrew that there was change in umask:
https://github.com/elastic/beats/pull/14119

I have same problem as tomrade reported here:
https://github.com/elastic/beats/pull/14119#issuecomment-587104463

writing audit events in json file on disk and than send this messages to central server, but file is owned by root:root and with permission 640 my forwarder is not able to read the auditbeat file

For confirmed bugs, please report:
- Version: 7.7.0
- Operating System:  ubuntu
- Discuss Forum URL: https://discuss.elastic.co/t/auditbeat-output-file-ignores-permissions/232637/3
- Steps to Reproduce: put output.file config which is above in auditbeat configuration file
