### ISSUE TITLE
[filebeat]add_field processor to add  field to @metadata

### ISSUE THREAD

**Issue by sophiaxu8** [elastic/beats#18599]
**Describe the enhancement:**
It would be nice to have the add_fields processor in filebeat to add field to @metadata. 
So it could be passed to logstash. Currently it result in two metadata set, same as in https://github.com/elastic/beats/issues/7351#issuecomment-414547853. 
**Describe a specific use case for the enhancement or feature:**

The use case is to have filebeat to collect some logs which tell logstash to go to a specific index . 

processors:
  - add_fields:
      target: '@metadata'
      fields:
        index: "customize-indexname"

this results in output similar to below:
{
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "7.7.0",
    "pipeline": "filebeat-7.7.0-default"
  },
  "@metadata": {
    "index": "customize-indexname"
  }
}

**Comment by mtherreault** [comment]
Here's a hack that can uses to be able to set a metadata field:
```yaml
- add_fields:
    target: ''
    fields:
      _index: '"customize-indexname"'
- decode_json_fields:
    target: "@metadata.index"
    fields: [_index]
    overwrite_keys: true
- drop_fields:
    fields:
    - _index
```
