### ISSUE TITLE
[Metricbeat - elastic module] Can't monitor more than 10 elastic  nodes

### ISSUE THREAD

**Issue by aalemanq** [elastic/beats#18619]
Hello, something weird is happens in my new cluster dockerized in swarm.

When I add 10 machine on:
`
```
metricbeat.modules:
- module: elasticsearch
  metricsets:
    - ccr
    - cluster_stats
    - enrich
    - index
    - index_recovery
    - index_summary
    - ml_job
    - node_stats
    - shard
  period: 10s
  hosts: ["elasticsearch-client-01:9200", "elasticsearch-client-02:9200", "elasticsearch-master-01:9200", "elasticsearch-master-02:9200", "elasticsearch-master-03:9200", "elasticsearch-ssd-01:9200", "elasticsearch-ssd-02:9200", "elasticsearch-ssd-03:9200", "elasticsearch-ssd-04:9200", "elasticsearch-sata-01:9200"]
  username: "XXXXXX"
  password: "XXXXX" 
  xpack.enabled: true
```
`

Everything is right, and in kibana-monitoring tab, you can see 10 nodes monitoring with metricbeat.

The issue starts when I add 1 or n nodes more. Metricbeat monitorig max 10 hosts and rest is monitoring by itself. Changing every X period of time node that metricbeat is monitoring.

`  hosts: ["elasticsearch-client-01:9200", "elasticsearch-client-02:9200", "elasticsearch-master-01:9200", "elasticsearch-master-02:9200", "elasticsearch-master-03:9200", "elasticsearch-ssd-01:9200", "elasticsearch-ssd-02:9200", "elasticsearch-ssd-03:9200", "elasticsearch-ssd-04:9200", "elasticsearch-sata-01:9200", "elasticsearch-sata-02:9200", "elasticsearch-sata-03:9200", "elasticsearch-sata-04:9200"]
`

![image](https://user-images.githubusercontent.com/37634573/82230872-9ecbf980-992c-11ea-9528-5f30f0b1a49d.png)

Do you know if exist some limitation like redis module (maxcon) ? Do you know how to avoid this limitation and monitor more than 10 hosts in elasticsearch module?
