### ISSUE TITLE
[Filebeat] Add source.as.organization.name to cloudtrail fileset

### ISSUE THREAD

**Issue by leehinman** [elastic/beats#18644]
**Describe the enhancement:**
Add source.as.organization.name to cloudtrail fileset
``` yaml
- geoip:
    database_file: GeoLite2-ASN.mmdb
    field: source.ip
    target_field: source.as
    properties:
    - asn
    - organization_name
    ignore_missing: true
- rename:
    field: source.as.organization_name
    target_field: source.as.organization.name
    ignore_missing: true
- rename:
    field: destination.as.asn
    target_field: destination.as.number
    ignore_missing: true
```

**Describe a specific use case for the enhancement or feature:**

** Backport
7.6, 7.7, 7.8, 7.x
