### ISSUE TITLE
[Filebeat] fortinet firewall module wrong type for source.bytes & destination.bytes

### ISSUE THREAD

**Issue by leehinman** [elastic/beats#18707]
source.bytes & destination.bytes are currently being parsed as strings, that is causing problems with:
```
- script:
    lang: painless
    source: ctx.network.bytes = ctx.source.bytes + ctx.destination.bytes
    if: "ctx?.source?.bytes != null && ctx?.destination?.bytes != null"
    ignore_failure: true
```
because we get string concatenation instead of addition.  It looks like all fields are strings so should go through whole module and make sure the types are correct (for example source.port is also a string instead of a number).
