### ISSUE TITLE
timeformat in json logs 

### ISSUE THREAD

**Issue by freeseacher** [elastic/beats#1886]
For confirmed bugs, please report:
- Version: 5.0.0-alpha3
- Steps to Reproduce: 
```
filebeat:
  prospectors:
    -
      paths:
        - /var/log/nginx/noc.access.log
      tail_files: true
      backoff: 1s
      json.keys_under_root: true
      json.add_error_key: true
      json.overwrite_keys: true
  idle_timeout: 5s
  registry_file: /var/lib/filebeat/registry
output:
  elasticsearch:
    hosts: ["http://localhost:9200"]
    index: "filebeat"
  console:
   pretty: true
```
nginx log format
```
log_format noc_format '{ "@timestamp": "$time_iso8601", '
                         '"@fields": { '
                         '"remote_addr": "$remote_addr", '
                         '"remote_user": "$remote_user", '
                         '"body_bytes_sent": "$body_bytes_sent", '
                         '"request_time": "$request_time", '
                         '"status": "$status", '
                         '"request": "$request", '
                         '"request_method": "$request_method", '
                         '"http_referrer": "$http_referer", '
                         '"request_time": "$request_time", '
                         '"upstream_addr": "$upstream_addr",'
                         '"upstream_response_time": "$upstream_response_time", '
                         '"http_user_agent": "$http_user_agent" } }';

```
i got 
```
{
  "@fields": {
    "body_bytes_sent": "104",
    "http_referrer": "-",
    "http_user_agent": "Go-http-client/1.1",
    "remote_addr": "10.36.129.4",
    "remote_user": "-",
    "request": "GET /ng_stats HTTP/1.1",
    "request_method": "GET",
    "request_time": "0.000",
    "status": "200",
    "upstream_addr": "-",
    "upstream_response_time": "-"
  },
  "@timestamp": "2016-06-18T15:10:59.484Z",
  "beat": {
    "hostname": "host01",
    "name": "host01"
  },
  "input_type": "log",
  "json_error": "@timestamp not overwritten (parse error on 2016-06-18T18:09:00+03:00)",
  "offset": 4468524,
  "source": "/var/log/nginx/noc.access.log",
  "type": "log"
}
```
how can i specify timestamp for filebeat json input?
