### ISSUE TITLE
[Filebeat][httpjson] Documented scroll example doesn't work

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#18919]
I tried the example from the [docs](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-httpjson.html#filebeat-input-httpjson) and it doesn't pass config validation. Then after fixing the validation issues it doesn't work.

From docs:
```yaml
filebeat.inputs:
- type: httpjson
  http_method: POST
  json_objects_array: hits.hits
  pagination: |-
  {
    "enabled": true,
    "extra_body_content": {
      "scroll": "5m"
    },
    "id_field": "_scroll_id",
    "req_field": "scroll_id",
    "url": "http://localhost:9200/_search/scroll"
   }
   url: http://localhost:9200/filebeat-test/_search?scroll=5m
```

This isn't valid YAML and results in `Exiting: error loading config file: yaml: line 7: could not find expected ':'`.

So I corrected the YAML to provide valid config:

```yaml
filebeat.inputs:
- type: httpjson
  http_method: POST
  json_objects_array: hits.hits
  url: http://localhost:9200/_search?scroll=5m
  pagination:
    enabled: true
    extra_body_content:
      scroll: 5m
    id_field: _scroll_id
    req_field: scroll_id
    url: http://localhost:9200/_search/scroll
```

It runs, but it never finds `hits.hits`.

`
2020-06-02T17:46:53.619-0400	INFO	[httpjson]	httpjson/input.go:118	httpjson input worker has started.	{"url": "http://localhost:9200/_search?scroll=5m"}
2020-06-02T17:46:53.628-0400	ERROR	[httpjson]	httpjson/input.go:123	key not found	{"url": "http://localhost:9200/_search?scroll=5m"}
2020-06-02T17:46:53.628-0400	INFO	[httpjson]	httpjson/input.go:124	httpjson input worker has stopped.	{"url": "http://localhost:9200/_search?scroll=5m"}
`

Here's what's in Elasticsearch:

```
curl http://localhost:9200/_search?scroll=5m | jq .
{
  "_scroll_id": "FGluY2x1ZGVfY29udGV4dF91dWlkDXF1ZXJ5QW5kRmV0Y2gBFGowRUNkM0lCTnlSUUJOZXZzQkdsAAAAAAAAABUWdGhSSzJGNWJRSEtOZXlnTTd1bnBmZw==",
  "took": 2,
  "timed_out": false,
  "_shards": {
    "total": 1,
    "successful": 1,
    "skipped": 0,
    "failed": 0
  },
  "hits": {
    "total": {
      "value": 1881,
      "relation": "eq"
    },
    "max_score": 1,
    "hits": [
      {
        "_index": "auditbeat-7.7.1-2020.06.02-000001",
        "_type": "_doc",
        ...
```
