### ISSUE TITLE
Prevent (file)beat modules with built-in processors from clashing with user-defined processors

### ISSUE THREAD

**Issue by joostdecock** [elastic/beats#18925]
**Describe the enhancement:**
Properly concat module and user processors arrays so that things *just work* when both module and user define processors.

**Describe a specific use case for the enhancement or feature:**

Here's a filebeat config snippet that I would expect to work:

```yaml
- module: system
  syslog:
    enabled: true
    var.paths:
      - /var/log/messages
    input:
      processors:
        - add_fields:
            target: pulse
            fields:
              module:
                name: system
```

> By the way, adding a processor to filebeat module is [described in the docs](https://www.elastic.co/guide/en/beats/filebeat/current/defining-processors.html#where-valid) as *Similarly, for Filebeat modules, you can define processors under the `input` section of the module definition.*
>
> Is it me, or is that a bit terse? 

If you use the configuration above, you get the following error:

```json
{
  "level": "error",
  "timestamp": "2020-06-03T12:52:45.815+0200",
  "caller": "instance/beat.go:933",
  "message": "Exiting: each processor must have exactly one action, but found 2 actions (add_locale,add_fields)"
}
```

I had a quick look at the code for the filebeat `system` module, and sure enough, it adds its own `add_locale` processor.

Turns out I can work around it by configuring this:

```yaml
- module: system
  syslog:
    enabled: true
    var.paths:
      - /var/log/messages
    input:
      processors:
        -
        - add_fields:
            target: pulse
            fields:
              module:
                name: system
```

Note the empty entry in the processors list, which pushes my processor to array index 1, thereby avoiding a clash with the module's processor at array index 0.

It seems like I wouldn't have to jump through such hoops to add a processor to a module that already has a processor in it.

If nothing else, people facing similar issues might find this workaround helpful.
