### ISSUE TITLE
[Metricbeat] GoogleCloud Dashboards using wrong fields

### ISSUE THREAD

**Issue by LucaWintergerst** [elastic/beats#18962]
The GoogleCloud Dashboards are using field names like `googlecloud.compute.instance.cpu.utilization`, while Metricbeat is sending fields like `googlecloud.compute.instance.cpu.utilization.value`. Note the `.value` at the end. This causes all visualizations to break.

For confirmed bugs, please report:
- Version:  `7.8.0-0dba676b`
- Operating System: MacOs
- Discuss Forum URL:
- Steps to Reproduce: 

Setup Metricbeat with the GoogleCloud module
```
- module: googlecloud
  metricsets:
    - compute
  region: "us-central1"
  project_id: "elastic-foobar"
  credentials_file_path: "foobar.json"
  exclude_labels: false
  period: 1m
```
setup Dashboards `./metricbeat setup --dashboards` 
start Metricbeat `./metricbeat -e`
try to load Dashboard
Kibana will error with `Error fetching fields for index pattern metricbeat-*`
