### ISSUE TITLE
Timezone parsing error in pipeline of Fortinet module

### ISSUE THREAD

**Issue by usp-npe** [elastic/beats#19010]
The Fortinet module (#13245) seems to have issues with parsing timezone information from source logs. The issue being that the timezone is not formatted according to the standard expected by the (Java-based) timezone parser.

While parsing fortinet logs which are received via syslog (as described in https://www.elastic.co/guide/en/beats/filebeat/master//filebeat-module-fortinet.html), the following error is repored by the pipeline processor:

> Invalid ID for ZoneOffset, non numeric characters found: +2:00

The original log line starts as follows:

> <189>logver=60` timestamp=1591368557 tz="UTC+2:00" devname="....

From [Java's documentation about the timezone parser](https://docs.oracle.com/javase/8/docs/api/java/time/ZoneId.html), it becomes clear that timezones must always be two-digits, meaning that single-digit timezones like the one in my case would need to be prepended with a 0 to become UTC+02:00

**Proposed solution** 
In [module/fortinet/firewall/ingest/pipeline,yml](https://github.com/elastic/beats/blob/master/x-pack/filebeat/module/fortinet/firewall/ingest/pipeline.yml), add a processor to update the `fortinet.firewall.tz` value and prepend a 0 if needed, before all other processors are executed.

..

**Comment by usp-npe** [comment]
Also worth noting that the date format strings should be extended to accept both RFC 822 time zone and general time zone formats, using a capital `Z` and a lowercase `z` (see https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html):

```
- date:
    field: _temp.time
    target_field: "@timestamp"
    formats:
    - yyyy-MM-dd HH:mm:ss
    - yyyy-MM-dd HH:mm:ss Z
    - yyyy-MM-dd HH:mm:ss z
    - ISO8601
    timezone: "{{fortinet.firewall.tz}}"
    if: "ctx.fortinet?.firewall?.tz != null"
- date:
    field: _temp.time
    target_field: "@timestamp"
    formats:
    - yyyy-MM-dd HH:mm:ss
    - yyyy-MM-dd HH:mm:ss Z
    - yyyy-MM-dd HH:mm:ss z
    - ISO8601
    if: "ctx.fortinet?.firewall?.tz == null"
```
