### ISSUE TITLE
[Elastic Agent] Change structure of Elastic Agent across the Stack

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#19082]
In https://github.com/elastic/beats/issues/18758 the decision was made to change the config structure of the Elastic Agent. This issue is to track the changes needed across all parts of the Stack. It is split up in different phases so the changes can be done in small chunks and it can be tested everything still works as expected.

# Phase 1 - Remove data source

In Phase 1, the datasources array is removed from the config and all the configs on the datasource level are moved to the input level. 
Before: 
```
datasources:
  - namespace: default
    use_output: default
    inputs:
      - type: system/metrics
        streams:
          - metricset: cpu
            dataset: system.cpu
```

After:
```
inputs:
 - namespace: default
   use_output: default
   type: system/metrics
   streams:
     - metricset: cpu
       dataset: system.cpu
```

Changes to be made:

* [x] Update config processing in Elastic Agent #19128
* [x] Update config generation in Ingest Manager (Kibana). Datasources on saved object level should not be removed, only what is generated for the Agent is changed. elastic/kibana#69226

# Phase 2 - Adjust dataset naming

Based on https://github.com/elastic/package-registry/issues/482 configs related to datasets should be adjusted

Before

```
inputs:
 - namespace: default
   use_output: default
   type: system/metrics
   streams:
     - metricset: cpu
       dataset: system.cpu
```

After

```
inputs:
 - dataset.namespace: default
   use_output: default
   type: system/metrics
   streams:
     - metricset: cpu
       dataset.name: system.cpu
```

* [x] Add support for renamed configs on the Elastic Agent side #19128
* [x] Update Kibana generation of configs accordingly elastic/kibana#69226
* [x] Adjust packages in package-storage
* [x] Adjust package-registry and manifest 
* [x] Update integrations package generation if needed

# Phase 3 - Remove datasources

The naming of datasources should be renamed in Kibana, the package-registry and the packages.

* [x] Rename datasources (SO) in Kibana https://github.com/elastic/kibana/pull/70259
* [x] Rename `datasources` list in package manifest to `config_templates`https://github.com/elastic/package-registry/pull/514
* [x] Update packages in package-storage to new format
* [x] Update integrations repositories to the new structure https://github.com/elastic/package-registry/pull/514
* [x] Update Kibana to support package registry changes https://github.com/elastic/kibana/pull/69864

# Phase 4 - Add support for dataset.type

Currently the dataset.type is inherited from the input.type but this might not always correct. In the future it should be possible to set the dataset.type independently. Below is an example on how this could look (example does not make much sense):

```
inputs:
 - dataset.namespace: default
   use_output: default
   type: system/metrics
   streams:
     - metricset: cpu
       dataset.name: system.cpu
       dataset.type: logs
```

* [x] Add support for it on the Elastic Agent side #19128
* [x] Adjust package-registry and manifest as needed https://github.com/elastic/package-registry/pull/514
* [x] Add `dataset.type` to Kibana config generation https://github.com/elastic/kibana/pull/69864
