### ISSUE TITLE
[Filebeat] Add unix socket input support to Suricata module

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#19109]
As a user of Suricata I would like to use Filebeat to collect the [Eve log](https://suricata.readthedocs.io/en/suricata-5.0.2/output/eve/eve-json-output.html) from a unix socket.

The configuration would probably look something like this:

```
# suricata.yaml
outputs:
  # Extensible Event Format (nicknamed EVE) event log in JSON format
  - eve-log:
      enabled: yes
      filetype: unix_stream
      filename: /var/run/suricata.sock
```

```
filebeat.modules:
- module: suricata
  eve:
    var.input: unix
    var.path: /var/run/suricata.sock
