### ISSUE TITLE
[Elastic Agent] Discuss: Cleanup Agent Config

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#19104]
The agent config has grown over time. From my perspective there are 3 main sections in our config:

* outputs: Everything related to configuring where to send data
* datasources: Configurations for the processes the agent runs on how to collect data (soon to be inputs)
* settings: Everything needed to configure the agent itsel

There are few more sections on the top level like `management`, `download`, `process` etc. which this issue is here to discuss.

In summary the suggestion is to move all these to level items under settings. We already have `settings.monitoring` today. Lets discuss each top level config separately.

## Download

Download contains all the settings around from where to fetch binares and where to put them. It is a combination of how to download things and which paths to be used. It is a bit a mixed box and not sure if everything really fits under the same section, but these could go under `settings.download` for now.

## Path (missing?)

There is usage of `{path.data}` in the config but I couldn't find where these can be configured at the moment?

## Process

Process is around how the processes should be run. This could go under `settings.process`.

## Retry

What are these retry configs for? Are these related to fleet / enrollment?

## Logging

Logging settings could go under `settings.logging`.

## Management

Management is a mixed box of many things.

There are few parts in here:

* mode: I wonder if we could have `fleet.enabled` true instead?
* fleet: Do we ever expect users to manually configure this or should the data always com from Fleet for this?
* reporting: This is again a mixed bag. It seems to have configs around logging inside (should this go under logging) and update how to report things to fleet. The Fleet part should go under fleet I assume?
* reload: Is this only related to fleet? If yes, should it go under `fleet`?

## Summary

I plan to update this issue in the end of the discussion with a specific proposal or create a new issue with the proposal we came up with.

**Comment by michalpristas** [comment]
we indeed packed a bunch of configuration options over time and refactor is needed, 
ad `retry` this is to control retriable operations such as downloading unless fatal error is returned, in case corrupted artifact is downloaded and verification fails.

**Comment by ruflin** [comment]
@blakerouse Could you take a lead on proposing a final version. Perhaps we can do the changes in multiple steps? Not sure how much it effects Kibana/Fleet. Would be nice to be able to fully validate it (besides inputs).

**Comment by michalpristas** [comment]
@ruflin priority wise, where are we with this issue?

**Comment by blakerouse** [comment]
Been looking at this today and I have the following proposal. I have broken it into two sections, one for fleet mode, one for standalone mode, and settings which is shared between both modes.

## Fleet Mode
This only represents from a user frontend point of view, the config that is sent from Fleet to Agent with `outputs` and `inputs` is not documented here.

### Basic w/ Fleet connection in `fleet.yml`
```
fleet:
  enabled: true

settings:
  ... see settings below ...
```

### All in Fleet (no `fleet.yml`)
```
fleet:
  access_token: ""
  kibana:
    # kibana minimal configuration
    host: "localhost:5601"
    ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

    # optional values
    #protocol: "https"
    #username: "elastic"
    #password: "changeme"
    #path: ""
    #ssl.verification_mode: full
    #ssl.supported_protocols: [TLSv1.0, TLSv1.1, TLSv1.2]
    #ssl.cipher_suites: []
    #ssl.curve_types: []
  
  # optional reporting overrides (Fleet specific)
  reporting:
    # Reporting threshold indicates how many events should be kept in-memory before reporting them to fleet.
    reporting_threshold: 10000
    # Frequency used to check the queue of events to be sent out to fleet.
    reporting_check_frequency_sec: 30

settings:
  ... see settings below ...
```
  
## Standalone Mode
The missing of `fleet.enabled: true` or `fleet.{access_token,kibana}` will place Elastic Agent into standalone mode. In standalone mode the `outputs` and `inputs` are defined as top level keys.

```
outputs:
  default:
    type: elasticsearch
    hosts: [127.0.0.1:9200]
    username: elastic
    password: changeme

inputs:
  - type: system/metrics
    dataset.namespace: default
    use_output: default
    streams:
      - metricset: cpu
        dataset.name: system.cpu
      - metricset: memory
        dataset.name: system.memory
      - metricset: network
        dataset.name: system.network
      - metricset: filesystem
        dataset.name: system.filesystem

settings:
  ... see settings below ...
```

## Settings
Represents the settings of the Elastic Agent running on the host, this is shared between both modes.

```
settings:
  # Allow fleet to reload his configuration locally on disk.
  # Notes: Only specific process configuration will be reloaded.
  reload:
    # enabled configure the Elastic Agent to reload or not the local configuration.
    #
    # Default is true
    enabled: true
    # period define how frequent we should look for changes in the configuration.
    period: 10s
  
  download:
    # source of the artifacts, requires elastic like structure and naming of the binaries
    # e.g /windows-x86.zip
    sourceURI: "https://artifacts.elastic.co/downloads/beats/"
    # path to the directory containing downloaded packages
    target_directory: "${path.data}/downloads"
    # timeout for downloading package
    timeout: 30s
    # file path to a public key used for verifying downloaded artifacts
    # if not file is present agent will try to load public key from elastic.co website.
    pgpfile: "${path.data}/elastic.pgp"
    # install_path describes the location of installed packages/programs. It is also used
    # for reading program specifications.
    install_path: "${path.data}/install"
  
  process:
    # timeout for creating new processes. when process is not successfully created by this timeout
    # start operation is considered a failure
    spawn_timeout: 30s
    # timeout for stopping processes. when process is not stopped by this timeout then the process.
    # is force killed
    stop_timeout: 30s
  
  grpc:
    # listen address for the GRPC server that spawned processes connect back to.
    address: localhost
    # port for the GRPC server that spawned processes connect back to.
    port: 6789
  
  retry:
    # Enabled determines whether retry is possible. Default is false.
    enabled: true
    # RetriesCount specifies number of retries. Default is 3.
    # Retry count of 1 means it will be retried one time after one failure.
    retriesCount: 3
    # Delay specifies delay in ms between retries. Default is 30s
    delay: 30s
    # MaxDelay specifies maximum delay in ms between retries. Default is 300s
    maxDelay: 5m
    # Exponential determines whether delay is treated as exponential.
    # With 30s delay and 3 retries: 30, 60, 120s
    # Default is false
    exponential: false
  
  monitoring:
    # enabled turns on monitoring of running processes
    enabled: false
    # enables log monitoring
    logs: false
    # enables metrics monitoring
    metrics: false
  
  # Sets log level. The default log level is info.
  # Available log levels are: error, warning, info, debug
  logging.level: trace
```
