### ISSUE TITLE
[Agent] Metricbeat crashes with default configuration

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#19165]
### Steps to reproduce
1. Start up ES, Kibana, and EPM using [this `docker-compose.yml`](https://github.com/elastic/integrations/blob/6819dff888019993d7f9cc81391caee6da7deb5c/testing/environments/snapshot.yml).
2. Once the services spin up, visit the Kibana > Ingest Manager > Fleet UI and grab the command to enroll an agent.
3. Download Elastic Agent 8.0.0-SNAPSHOT from https://snapshots.elastic.co/8.0.0-e588f883/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64.tar.gz and install it.
4. Enroll the Agent with the command from Kibana.
5. Run the Agent.

### Observed
Agent logs display repeated messages like this:
```
2020-06-12T08:57:03-07:00 ERROR reporter.go:47  2020-06-12T08:57:03-07:00: type: 'ERROR': sub_type: 'CONFIG' message: Application: metricbeat[5cd0813e-344e-4a38-9301-9a7158bf9d6a]: application 'metricbeat--8.0.0-SNAPSHOT' crashed: /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/core/plugin/app/app.go[214]: unknown error
```

**Comment by ph** [comment]
This might be related to the recent change in the gRPC?

**Comment by michalpristas** [comment]
can you include metricbeat logs if available?

**Comment by ycombinator** [comment]
I was able to repro this by building the latest `master` (96d24e73858d1e26bb32aef909523869b0425f9b) from source. I was able to repro the issue.

Then I tried building from a few commits prior (3c0eeab2f3095578aebcec131fe7154367b06206). I was **not** able to repro the issue.

**Comment by blakerouse** [comment]
I think the latest GRPC with the ability for metricbeat to report errors, is why this is now being caught. In the metricbeat logs I see:

```
2020-06-12T16:08:45.749-0400	ERROR	[centralmgmt.fleet]	fleet/manager.go:239	6 errors: Error creating runner from config: 1 error: invalid cpu.metrics value 'percentages,normalized_percentages' (valid options are percentages, normalized_percentages, and ticks) accessing config; Error creating runner from config: 1 error: metricset 'system/entropy' not found; Error creating runner from config: 1 error: metricset 'system/users' not found; Error creating runner from config: 1 error: could not read /proc: stat /proc: no such file or directory; Error creating runner from config: 1 error: error connecting to dbus: dial unix /opt/local/var/run/dbus/system_bus_socket: connect: no such file or directory; Error creating runner from config: 1 error: metricset 'system/socket' not found
```

**Comment by blakerouse** [comment]
This is the full config that is being passed to metricbeat when using the system module from Fleet:

```
metricbeat:
  modules:
  - core:
      metrics: percentages
    id: system/metrics-system.core
    index: metrics-system.core-default
    metricsets:
    - core
    module: system
    processors:
    - add_fields:
        fields:
          name: system.core
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.core
          namespace: default
          type: metrics
        target: stream
  - core:
      metrics: percentages
    cpu:
      metrics: percentages,normalized_percentages
    id: system/metrics-system.cpu
    index: metrics-system.cpu-default
    metricsets:
    - cpu
    module: system
    period: 10s
    process:
      include_top_n:
        by_cpu: 5
        by_memory: 5
    processes: .*
    processors:
    - add_fields:
        fields:
          name: system.cpu
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.cpu
          namespace: default
          type: metrics
        target: stream
  - id: system/metrics-system.diskio
    index: metrics-system.diskio-default
    metricsets:
    - diskio
    module: system
    processors:
    - add_fields:
        fields:
          name: system.diskio
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.diskio
          namespace: default
          type: metrics
        target: stream
  - id: system/metrics-system.entropy
    index: metrics-system.entropy-default
    metricsets:
    - entropy
    module: system
    processors:
    - add_fields:
        fields:
          name: system.entropy
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.entropy
          namespace: default
          type: metrics
        target: stream
  - id: system/metrics-system.filesystem
    index: metrics-system.filesystem-default
    metricsets:
    - filesystem
    module: system
    period: 1m
    processors:
    - drop_event:
        when:
          regexp:
            system:
              filesystem:
                mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
    - add_fields:
        fields:
          name: system.filesystem
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.filesystem
          namespace: default
          type: metrics
        target: stream
  - id: system/metrics-system.fsstat
    index: metrics-system.fsstat-default
    metricsets:
    - fsstat
    module: system
    period: 1m
    processors:
    - drop_event:
        when:
          regexp:
            system:
              filesystem:
                mount_point: ^/(sys|cgroup|proc|dev|etc|host|lib|snap)($|/)
    - add_fields:
        fields:
          name: system.fsstat
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.fsstat
          namespace: default
          type: metrics
        target: stream
  - core:
      metrics: percentages
    cpu:
      metrics: percentages,normalized_percentages
    id: system/metrics-system.load
    index: metrics-system.load-default
    metricsets:
    - load
    module: system
    period: 10s
    process:
      include_top_n:
        by_cpu: 5
        by_memory: 5
    processes: .*
    processors:
    - add_fields:
        fields:
          name: system.load
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.load
          namespace: default
          type: metrics
        target: stream
  - core:
      metrics: percentages
    cpu:
      metrics: percentages,normalized_percentages
    id: system/metrics-system.memory
    index: metrics-system.memory-default
    metricsets:
    - memory
    module: system
    period: 10s
    process:
      include_top_n:
        by_cpu: 5
        by_memory: 5
    processes: .*
    processors:
    - add_fields:
        fields:
          name: system.memory
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.memory
          namespace: default
          type: metrics
        target: stream
  - core:
      metrics: percentages
    cpu:
      metrics: percentages,normalized_percentages
    id: system/metrics-system.network
    index: metrics-system.network-default
    metricsets:
    - network
    module: system
    period: 10s
    process:
      include_top_n:
        by_cpu: 5
        by_memory: 5
    processes: .*
    processors:
    - add_fields:
        fields:
          name: system.network
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.network
          namespace: default
          type: metrics
        target: stream
  - id: system/metrics-system.network_summary
    index: metrics-system.network_summary-default
    metricsets:
    - network_summary
    module: system
    processors:
    - add_fields:
        fields:
          name: system.network_summary
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.network_summary
          namespace: default
          type: metrics
        target: stream
  - core:
      metrics: percentages
    cpu:
      metrics: percentages,normalized_percentages
    id: system/metrics-system.process
    index: metrics-system.process-default
    metricsets:
    - process
    module: system
    period: 10s
    process:
      include_top_n:
        by_cpu: 5
        by_memory: 5
    processes: .*
    processors:
    - add_fields:
        fields:
          name: system.process
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.process
          namespace: default
          type: metrics
        target: stream
  - core:
      metrics: percentages
    cpu:
      metrics: percentages,normalized_percentages
    id: system/metrics-system.process_summary
    index: metrics-system.process_summary-default
    metricsets:
    - process_summary
    module: system
    period: 10s
    process:
      include_top_n:
        by_cpu: 5
        by_memory: 5
    processes: .*
    processors:
    - add_fields:
        fields:
          name: system.process_summary
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.process_summary
          namespace: default
          type: metrics
        target: stream
  - id: system/metrics-system.raid
    index: metrics-system.raid-default
    metricsets:
    - raid
    module: system
    processors:
    - add_fields:
        fields:
          name: system.raid
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.raid
          namespace: default
          type: metrics
        target: stream
  - id: system/metrics-system.service
    index: metrics-system.service-default
    metricsets:
    - service
    module: system
    processors:
    - add_fields:
        fields:
          name: system.service
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.service
          namespace: default
          type: metrics
        target: stream
  - id: system/metrics-system.socket
    index: metrics-system.socket-default
    metricsets:
    - socket
    module: system
    processors:
    - add_fields:
        fields:
          name: system.socket
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.socket
          namespace: default
          type: metrics
        target: stream
  - core:
      metrics: percentages
    cpu:
      metrics: percentages,normalized_percentages
    id: system/metrics-system.socket_summary
    index: metrics-system.socket_summary-default
    metricsets:
    - socket_summary
    module: system
    period: 10s
    process:
      include_top_n:
        by_cpu: 5
        by_memory: 5
    processes: .*
    processors:
    - add_fields:
        fields:
          name: system.socket_summary
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.socket_summary
          namespace: default
          type: metrics
        target: stream
  - core:
      metrics: percentages
    cpu:
      metrics: percentages,normalized_percentages
    id: system/metrics-system.uptime
    index: metrics-system.uptime-default
    metricsets:
    - uptime
    module: system
    period: 10s
    processes: .*
    processors:
    - add_fields:
        fields:
          name: system.uptime
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.uptime
          namespace: default
          type: metrics
        target: stream
  - id: system/metrics-system.users
    index: metrics-system.users-default
    metricsets:
    - users
    module: system
    processors:
    - add_fields:
        fields:
          name: system.users
          namespace: default
          type: metrics
        target: dataset
    - add_fields:
        fields:
          dataset: system.users
          namespace: default
          type: metrics
        target: stream
output:
  elasticsearch:
    api_key: VkvhrXIBe9Ywt9TdhTBC:3In_gkxDRqm8lC_YqN2qqw
    hosts:
    - http://localhost:9200
```
