### ISSUE TITLE
journalbeat exits with success

### ISSUE THREAD

**Issue by chrissound** [elastic/beats#19183]
```
[root@XenonKiloCranberry:~]# /nix/store/lfcgbj5s5iwd4fa6dcs2lmrkryy03a9s-journalbeat-6.8.3-bin/bin/journalbeat -c /nix/store/9g135rj3vz502l03iy08567nyl22iirm-journalbeat.yml -path.data /var/lib/journalbeat/data -path.logs /var/lib/journalbeat/logs

[root@XenonKiloCranberry:~]# echo $? 
0
```

The config file:
```
[root@XenonKiloCranberry:~]# cat /nix/store/9g135rj3vz502l03iy08567nyl22iirm-journalbeat.yml
name: journalbeat
tags: []



journalbeat:
  seek_position: cursor
  cursor_seek_fallback: tail
  write_cursor_state: true
  cursor_flush_period: 5s
  clean_field_names: true
  convert_to_numbers: false
  move_metadata_to_field: journal
  default_type: journal
output.elasticsearch:
  hosts: ["localhost:9200"]
```

My expectation is this program would run as continuously running daemon, and if not, it would at least output an error if something goes wrong.

Version:
```
[root@XenonKiloCranberry:~]# /nix/store/lfcgbj5s5iwd4fa6dcs2lmrkryy03a9s-journalbeat-6.8.3-bin/bin/journalbeat version
journalbeat version 6.8.3 (amd64), libbeat 6.8.3 [unknown built unknown]
```
