### ISSUE TITLE
Filebeat copy_fields processor can recurse, leading to crash

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#19206]
It's possible for the `copy_fields` processor to fall into infinite recursion if we point at two fields with the same root:

```
                    - copy_fields:
                        fields:
                          - from: message
                            to: message.original
```
The `from` and `to` fields will point to the same root, leading an eventual crash. It appears `copy_fields` doesn't do an _actual_ copy and just moves references. @urso discovered the root cause here.
