### ISSUE TITLE
Agent 7.8.0-SNAPSHOT: invalid ApiKey value

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#19218]
I'm using a docker-compose setup (based on @mtojek 's) to test fleet, and I'm running into an enroll failure:

```
elastic-agent_1     | 2020-06-16T15:05:50Z DEBUG	client.go:178	Request method: POST, path: /api/ingest_manager/fleet/agents/enroll
elasticsearch_1     | {"type": "server", "timestamp": "2020-06-16T15:05:50,835Z", "level": "WARN", "component": "o.e.x.s.a.AuthenticationService", "cluster.name": "docker-cluster", "node.name": "2e727e51936f", "message": "Authentication using apikey failed - invalid ApiKey value", "cluster.uuid": "G8OcOApcTIK2EpgrOArb6g", "node.id": "FpDR6jCeTtKfEPwDqm_aRA" ,
elasticsearch_1     | "stacktrace": ["java.lang.IllegalArgumentException: invalid ApiKey value",

kibana_1            | {"type":"log","@timestamp":"2020-06-16T15:05:50Z","tags":["info","plugins","security","authentication"],"pid":7,"message":"Authentication attempt failed: [security_exception] missing authentication credentials for REST request [/_security/_authenticate], with { header={ WWW-Authenticate={ 0=\"ApiKey\" & 1=\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\" } } }"}

elastic-agent_1     | fail to enroll: fail to execute request to Kibana: Status code: 401, Kibana returned an error: Unauthorized, message: [security_exception] missing authentication credentials for REST request [/_security/_authenticate], with { header={ WWW-Authenticate={ 0="ApiKey" & 1="Basic realm=\"security\" charset=\"UTF-8\"" } } }

```

The files used by `docker-compose` : 

```
version: '2.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0-SNAPSHOT
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "elastic:changeme", "http://127.0.0.1:9200/"]
      retries: 300
      interval: 1s
    environment:
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    - "network.host="
    - "transport.host=127.0.0.1"
    - "http.host=0.0.0.0"
    - "indices.id_field_data.enabled=true"
    - "xpack.license.self_generated.type=trial"
    - "xpack.security.enabled=true"
    - "xpack.security.authc.api_key.enabled=true"
    - "ELASTIC_PASSWORD=changeme"
    ports:
      - "0.0.0.0:9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0-SNAPSHOT
    depends_on:
      elasticsearch:
        condition: service_healthy
      package-registry:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://127.0.0.1:5601/login | grep kbn-injected-metadata 2>&1 >/dev/null"
      retries: 600
      interval: 1s
    volumes:
      - ./kibana.config.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "0.0.0.0:5601:5601"

  package-registry:
    image: docker.elastic.co/package-registry/package-registry:master
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080"]
      retries: 300
      interval: 1s
    volumes:
      - ../../build/public:/registry/public
    ports:
      - "127.0.0.1:8080:8080"

```

```

version: '2.3'
services:
  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent:7.8.0-SNAPSHOT
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    environment:
    - "FLEET_ENROLL=1"
    - "FLEET_SETUP=1"
    - "KIBANA_HOST=http://kibana:5601"
```

This seems to be fairly new. Any ideas?
