### ISSUE TITLE
[filebeat][netflow] copy ipv6 addresses to ECS fields

### ISSUE THREAD

**Issue by immon** [elastic/beats#19210]
**Describe the enhancement:**

IPv6 addresses are not copied to `destination.ip` and `source.ip` fields. As a consequence visualizations for ipv6 netflows "do not work".

IPv4 addresses are correctly handled in [convert.go#L190](https://github.com/elastic/beats/blob/v7.7.1/x-pack/filebeat/input/netflow/convert.go#L190) and [convert.go#L202](https://github.com/elastic/beats/blob/v7.7.1/x-pack/filebeat/input/netflow/convert.go#L202).

A workaround at this moment is to modify netflow input like this:

```
  input:
    processors:
    - copy_fields:
      when:
        has_fields: ['netflow.destination_ipv6_address']
      fields:
        - from: netflow.destination_ipv6_address
          to: destination.ip
    - copy_fields:
      when:
        has_fields: ['netflow.source_ipv6_address']
      fields:
        - from: netflow.source_ipv6_address
          to: source.ip
```
