### ISSUE TITLE
Is there an alternative to env. variables object substitution?

### ISSUE THREAD

**Issue by orhantoy** [elastic/beats#19272]
As of version 7.7 the ability to substitute objects into the config via env. variables were removed. We're currently relying on that ability in Enterprise Search, for instance to set custom ES headers:

```
output.elasticsearch:
  # ...
  hosts: ["${ELASTICSEARCH_HOST}"]
  # ...
  headers: ${ELASTICSEARCH_HEADERS}
```

https://github.com/elastic/go-ucfg/pull/139 is the PR that removed support for this, I think.

Is there an alternative to this other than setting a command line argument like
```
-E output.elasticsearch.headers='{ "X-Custom-Header": "..." }'
```
?
