### ISSUE TITLE
Auditbeat Paths Support Wildcards (Windows)

### ISSUE THREAD

**Issue by mgovolt** [elastic/beats#19301]
**Describe the enhancement:**
Something like this should be supported:
- module: file_integrity
  paths:
  - C:\Windows\System32\*.exe
  - C:\Windows\System32\*.dll
Currently that errors with WARN	[file_integrity]	file_integrity/metricset.go:192	Failed to resolve	{"file_path": "C:\\Windows\\System32\\*.dll", "error": "CreateFile C:\\Windows\\System32\\*.dll: The filename, directory name, or volume label syntax is incorrect."}
**Describe a specific use case for the enhancement or feature:**
Different Windows versions have different system32 exe's and dll's. Rather than know what each of them are, a simple wildcard would make this way easier.

**Comment by adriansr** [comment]
The `file_integrity` module doesn't expect files in the `paths:` option, but directories.

What you want is something like:
```yaml
- module: file_integrity
  paths:
    - C:/windows/system32
  include_files: [ '(?i)\.dll$', '(?i)\.exe$' ]
```

and optionally add the `recursive: true` flag in you also want to monitor files in subdirectories.

```
