### ISSUE TITLE
Logs written to stderr instead of stdout

### ISSUE THREAD

**Issue by cdalexndr** [elastic/beats#19320]
All filebeat logs are writted to `stderr` instead of `stdout` disregarding entry log level.
Confirmed that WARN and INFO level logs are written to `stderr`. Didn't found an ERROR log level to test.

All logs should be written to `stdout` or only ERROR level logs should be written to `stderr`.

Configuration:
Using filebeat with ingest pipelines. 
filebeat.yml:
```
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "log-%{[docker][container][labels][app]}"
  pipeline: pipeline_logs
  ilm.enabled: false

setup.ilm.enabled: false
setup.template.name: "log"
setup.template.pattern: "log-*"
setup.kibana.host: http://kibana:5601

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
```

For confirmed bugs, please report:
- Version: 7.8.0
- Operating System: docker

related: https://github.com/moby/moby/issues/41139
