### ISSUE TITLE
Filebeat 7.8 Kubernetes Autodiscovery Memory Leak

### ISSUE THREAD

**Issue by lystor** [elastic/beats#19368]
Hello

Filebeat 7.8.0 still has a memory leak with enabled Kubernetes autodiscovery
and Kubernetes kills the container on memory limit reached.

We have the issue on all Kubernetes nodes (14x).

- Filebeat Version: 7.8.0
- Kubernetes Version: 1.15.3
- Operating System: Official Docker Image
- Steps to Reproduce: 

```
# helm upgrade \
    filebeat \
    stable/filebeat \
    --install \
    --namespace=filebeat \
    --values=filebeat/values.yaml \
    --version=3.1.0
```

values_override.yaml:
```
data:
  hostPath: "/var/lib/filebeat"

image:
  tag: "7.8.0"

monitoring:
  enabled: false

privileged: true

resources:
  limits:
    memory: 600Mi
  requests:
    memory: 600Mi

tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule

overrideConfig:
  filebeat.autodiscover:
    providers:
      - type: kubernetes
        templates:
          - config:
              - type: container
                clean_inactive: "25h"
                clean_removed: false
                close_eof: false
                close_inactive: "5m"
                close_renamed: false
                close_removed: false
                close_timeout: "6h"
                exclude_lines:
                  - "Using deprecated option"
                ignore_older: "24h"
                max_bytes: 1048576
                paths:
                  - "/var/log/containers/*-${data.kubernetes.container.id}.log"
                processors:
                  - decode_json_fields:
                      fields:
                        - "message"
                      max_depth: 1
                      process_array: false
                      overwrite_keys: true
                      target: ""
                scan_frequency: "10s"

  filebeat.registry.flush: "60s"

  monitoring.enabled: true
  monitoring.elasticsearch:
    hosts:
      - "http://elk-nova-1.local:9200"
      - "http://elk-nova-2.local:9200"
      - "http://elk-nova-3.local:9200"

  output.elasticsearch:
    bulk_max_size: 1
    hosts:
      - "http://elk-nova-1.local:9200"
      - "http://elk-nova-2.local:9200"
      - "http://elk-nova-3.local:9200"
    indices:
      - index: "filebeat-k80s-game01-%{[kubernetes.container.name]}-%{+xxxx.ww}"
        when:
          and:
            - contains:
                kubernetes.labels.type: "game01"
            - not.regexp:
                kubernetes.container.name: "^(istio-proxy|redis)$"
      - index: "filebeat-k80s-lds-%{+xxxx.ww}"
        when.equals:
          kubernetes.namespace: "lds"
      - index: "filebeat-k80s-thirdparty-%{[kubernetes.container.name]}-%{+xxxx.ww}"
        when.has_fields:
          - "kubernetes.container.name"
    worker: 1

  setup.dashboards.enabled: false
  setup.ilm.enabled: false
  setup.template.enabled: false
```
![image](https://user-images.githubusercontent.com/7275333/85569699-7033f380-b63b-11ea-8fd6-e893c1db0d4a.png)
![image](https://user-images.githubusercontent.com/7275333/85569714-74601100-b63b-11ea-9daa-d95b3012a5a5.png)
![image](https://user-images.githubusercontent.com/7275333/85569727-76c26b00-b63b-11ea-9a34-4df47ee3034d.png)
![image](https://user-images.githubusercontent.com/7275333/85569736-7924c500-b63b-11ea-86c3-695645f635c9.png)
![image](https://user-images.githubusercontent.com/7275333/85569748-7b871f00-b63b-11ea-9728-24d11fc4cd5e.png)

Please fix the bug.
Thank you

--
Mykola
