### ISSUE TITLE
[Metricbeat] Add support for IAM Roles for Service Accounts (EKS)

### ISSUE THREAD

**Issue by Dudssource** [elastic/beats#19393]
**Describe the enhancement:**

It would be really nice to be able to use this additional authentication mechanism when running metricbeat inside Elastic Kubernetes Service (specially when using the [AWS Module](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-aws.html)).

**Describe a specific use case for the enhancement or feature:**

I tried to configure metricbeat following the AWS official documentation [Specifying an IAM role for your service account](https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html) (we use this approach successfully with other components like ALB Ingress Controller, External DNS, Fluxcd and so on) and even if I change the container permissions to be able to read the token file (fsGroup: 472) metricbeat insists to use the worker node role (which is not what we want).

We are using metricbeat version 7.8.0.

This feature would enable more flexibility and security since metricbeat requires some additional permissions that may not be desirable to share with all pods running on the same cluster.

Follow the configuration we tried to use on metricbeat deployment (setting fsGroup to 472 works for other deployments):

```yaml
securityContext:
  fsGroup: 472
  runAsGroup: 472
  runAsUser: 0
```
We don't manually specify any AWS auth related env because AWS does that for us (when using IRSA) and with that the AWS SDK should detect the injected environments (AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE).

Thanks.

**Comment by kaiyan-sheng** [comment]
Hi! Thanks for opening this issue. Have you tried using `[role_arn](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-aws.html#aws-credentials-config)` config in `aws` module? If so, what's the error you see in the log file? Thanks!

**Comment by Dudssource** [comment]
Hi @kaiyan-sheng 
Thank you for quick reply!

Sure, when I tried to directly configure the `role_arn` attribute I get an error about the worker node not being able to assume the informed role.

My module configuration:

```yaml
aws.yml: |-
  - module: aws
    period: 86400s
    metricsets:
      - s3_request
      - s3_daily_storage
    role_arn: arn:aws:iam::REDACTED:role/metricbeat-2dcb05e3ec36c34e
  - module: aws
    period: 300s
    metricsets:
      - cloudwatch
    metrics:
      - namespace: AWS/EBS
      - namespace: AWS/ELB
      - namespace: AWS/EC2
    role_arn: arn:aws:iam::REDACTED:role/metricbeat-2dcb05e3ec36c34e
  - module: aws
    period: 12h
    metricsets:
      - billing
  - module: aws
    period: 300s
    metricsets:
      - ec2
      - ebs
      - elb
      - rds
      - sqs
      - lambda
      - natgateway
      - usage
      - transitgateway
      - vpn
    role_arn: arn:aws:iam::REDACTED:role/metricbeat-2dcb05e3ec36c34e
```

The error:

```plaintext
2020-06-25T15:16:56.653Z	ERROR	instance/beat.go:958	Exiting: 2 errors: error creating aws metricset: failed to retrieve aws credentials, please check AWS credential in config: AccessDenied: User: arn:aws:sts::REDACTED:assumed-role/eksworker-REDACTED/i-02b67703d5184bafd is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::REDACTED:role/metricbeat-2dcb05e3ec36c34e
	status code: 403, request id: 4acd0566-31b2-4043-a6b1-99d5b19aa60d; error creating aws metricset: failed to retrieve aws credentials, please check AWS credential in config: AccessDenied: User: arn:aws:sts::REDACTED:assumed-role/eksworker-REDACTED/i-02b67703d5184bafd is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::REDACTED:role/metricbeat-2dcb05e3ec36c34e
	status code: 403, request id: 7c662cbb-4fbd-4b41-930d-8da3e64797ad
Exiting: 2 errors: error creating aws metricset: failed to retrieve aws credentials, please check AWS credential in config: AccessDenied: User: arn:aws:sts::REDACTED:assumed-role/eksworker-REDACTED/i-02b67703d5184bafd is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::REDACTED:role/metricbeat-2dcb05e3ec36c34e
	status code: 403, request id: 4acd0566-31b2-4043-a6b1-99d5b19aa60d; error creating aws metricset: failed to retrieve aws credentials, please check AWS credential in config: AccessDenied: User: arn:aws:sts::REDACTED:assumed-role/eksworker-REDACTED/i-02b67703d5184bafd is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::REDACTED:role/metricbeat-2dcb05e3ec36c34e
```

It seems that in order to be able to use the IRSA feature, another kind of credential provider need to be used (for go aws-sdk I believe that the right one is [NewWebIdentityRoleProvider](https://godoc.org/github.com/aws/aws-sdk-go-v2/aws/stscreds#NewWebIdentityRoleProvider))
