### ISSUE TITLE
Capture Docker Service Labels

### ISSUE THREAD

**Issue by danielwrayois** [elastic/beats#19431]
**Describe the enhancement:**

Capture Docker service labels as defined under the "deploy" key in a stack / compose file. These are service-level labels that are associated with the service definition, whereas the root-level "labels" keyword is associated with the task (containers) that are spawned by Docker.

**Describe a specific use case for the enhancement or feature:**

Currently only the bottom most label is captured via Filebeat and appears:

```yaml
"docker.container.labels.uk.co.example.task.type": "web-server"
```
```yaml
version: "3.7"

services:
  example-web-server:
    image: "nginx:latest"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role == worker"
      resources:
        limits:
          cpus: "0.50"
          memory: "512M"
        reservations:
          cpus: "0.25"
          memory: "256M"
      labels:
        - "uk.co.example.environment=development"
        - "uk.co.example.project.id=aaaabbbcccc"
        - "uk.co.example.pipeline.id=abc123"
        - "uk.co.example.name=example-web-server"
        - "uk.co.example.maintainer=developers@example.co.uk"
        - "uk.co.example.type=web-server"
        - "uk.co.example.product=super-cool-product"
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: 10
    healthcheck:
      test: ["CMD", "echo", "fake-test"]
      interval: "10s"
      timeout: "5s"
      start_period: "10s"
      retries: 5
    labels:
      - "uk.co.example.task.type=web-server"
```
This would result in the following new keys:

```yaml
"docker.container.labels.uk.co.example.service.environment": "development"
"docker.container.labels.uk.co.example.service.project.id": "aaaabbbcccc"
"docker.container.labels.uk.co.example.service.pipeline.id": "abc123"
"docker.container.labels.uk.co.example.service.name": "web-server"
"docker.container.labels.uk.co.example.service.maintainer": "developers@example.co.uk"
"docker.container.labels.uk.co.example.service.type": "web-server"
"docker.container.labels.uk.co.example.service.product": "super-cool-product"
```
or

```yaml
"docker.service.labels.uk.co.example.environment": "development"
"docker.service.labels.uk.co.example.project.id": "aaaabbbcccc"
"docker.service.labels.uk.co.example.pipeline.id": "abc123"
"docker.service.labels.uk.co.example.name": "web-server"
"docker.service.labels.uk.co.example.maintainer": "developers@example.co.uk"
"docker.service.labels.uk.co.example.type": "web-server"
"docker.service.labels.uk.co.example.product": "super-cool-product"
```
