### ISSUE TITLE
`perfmon.queries` config option not being picked up by elastic agent

### ISSUE THREAD

**Issue by narph** [elastic/beats#19493]
Adding support for the windows package and generated the following manifest file for the perfmon metricset:
```
title: Windows perfmon metrics
release: experimental
type: metrics
streams:
- input: windows/metrics
  vars:
  - name: perfmon.group_measurements_by_instance
    type: bool
    title: Perfmon Group Measurements By Instance
    multi: false
    required: true
    show_user: true
    default: false
  - name: perfmon.ignore_non_existent_counters
    type: bool
    title: Perfmon Ignore Non Existent Counters
    multi: false
    required: true
    show_user: true
    default: false
  - name: perfmon.queries
    type: yaml
    title: Perfmon Queries
    multi: false
    required: true
    show_user: true
    default: |
      - object: 'Process'
        instance: ["*"]
        counters:
         - name: "% Processor Time"
           field: cpu_perc
           format: "float"
         - name: "Working Set"
  - name: period
    type: text
    title: Period
    multi: false
    required: true
    show_user: true
    default: 10s
  title: Windows perfmon metrics
  description: Collect Windows perfmon metrics
```

Configuration option is visible in Kibana:

![image](https://user-images.githubusercontent.com/1900090/86016192-c8e00380-ba22-11ea-915d-556d5f67c863.png)

Getting the following error in the metricbeat logs:

```
2020-06-29T16:09:39.431+0200	ERROR	[centralmgmt]	cfgfile/list.go:95	Error creating runner from config: 1 error: no perfmon counters or queries have been configured accessing config
```
which means perfmon.queries was not configured.

Also, running `elastic-agent inspect output -o default -p metricbeat`

returns:
```
metricbeat:
  modules:
  - id: windows/metrics-windows.perfmon
    index: metrics-windows.perfmon-default
    metricsets:
    - perfmon
    module: windows
    name: windows-1
    package:
      name: windows
      version: 0.0.1
    perfmon:
      group_measurements_by_instance: true
      ignore_non_existent_counters: false
    period: 10s
    processors:
    - add_fields:
        fields:
          name: windows.perfmon
          namespace: default
          type: metrics
        target: dataset
  - id: windows/metrics-windows.service
...
```
The `service` dataset works just fine.

Blocking https://github.com/elastic/integrations/issues/77

cc @michalpristas
