### ISSUE TITLE
Does filebeats support output type to create multi es index ?

### ISSUE THREAD

**Issue by xiocode** [elastic/beats#1953]
Can i define multi-document-out-type for different index?

like:
```yaml
filebeat:
  prospectors:
    -
      paths:
        - /data/m*.log
      input_type: log
      document_type: m-log
    -
      paths:
        - /data/n*.log
      input_type: log
      document_type: n-log

output:
  elasticsearch:
    hosts: ["localhost:9200"]
    indexes:
      -
        document_type: m-log
        index: "m-log"
      -
        document_type: m-log
        index: "m-log"
```
