### ISSUE TITLE
Pipeline doesn't work in Filebeats Alpha 3

### ISSUE THREAD

**Issue by petercort** [elastic/beats#1962]
Running Filebeats Alpha 3 passing directly to an Elasticsearch Alpha 3 installation. See the discussion on the forums: https://discuss.elastic.co/t/pipeline-not-working-filebeats-elasticsearch-5-0-0-alpha-3/54197/10

The same configuration works fine with a Filebeats Alpha 2 installation, but not 3.

**Comment by tsg** [comment]
@petercort I couldn't reproduce this with either alpha3 or alpha4. This is the config I used:

```
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]

  parameters:
    pipeline: alpha3
```

And this is what I see with ngrep:

```
T ::1:64353 -> ::1:9200 [AP]
  POST /_bulk?pipeline=alpha3 HTTP/1.1..Host: localhost:9200..User-Agent: Go-http-client/1
  .1..Content-Length: 17291..Accept: application/json..Accept-Encoding: gzip....{"index":{
  "_index":"filebeat-2016.07.13","_type":"log"}}.{"@timestamp":"2016-07-13T09:47:26.611Z",
  "beat":{"hostname":"Tudors-MacBook-Pro.local","name":"Tudors-MacBook-Pro.local"},"input_
  type":"log","message":"\t`
```

Can you perhaps post your full config and steps to reproduce?

**Comment by urso** [comment]
Also tested with master.

My pipeline config:
```
{
    "description": "Test pipeline",
    "processors": [
        {
            "lowercase": {
                "field": "beat.name"
            }
        }
    ]
}
```

and filebeat config:
```
filebeat.prospectors:
- input_type: log
  paths:
    - tmp/nasa/*.log

output.elasticsearch:
  hosts: ["192.168.99.100"]
  parameters.pipeline: "test-pipeline"

name: ABC
```

The `beat.name` is correctly modified by elasticsearch:
```
{
        "_source" : {
          "@timestamp" : "2016-07-13T14:10:17.818Z",
          "offset" : 5598,
          "beat" : {
            "hostname" : "X",
            "name" : "abc"
          },
          "input_type" : "log",
          "source" : "tmp/nasa/access.log",
          "message" : "205.212.115.106 - - [01/Jul/1995:00:01:13 -0400] \"GET /shuttle/missions/sts-71/images/images.html HTTP/1.0\" 200 7634",
          "type" : "log"
        }
      },
```
