### ISSUE TITLE
Possible auditbeat 7.8.0 memory leak if es host is unreachable

### ISSUE THREAD

**Issue by wdoekes** [elastic/beats#19644]
- Version: 7.8.0 (from `https://artifacts.elastic.co/packages/7.x/apt stable/main amd64`)
- Operating System: `Ubuntu 18.04.4 LTS`
- Steps to Reproduce:

I noticed excessive memory usage on one of our hosts. Turns out this started on the same date that auditbeat had been installed. Also it tunred out that the elasticsearch host was not reachable. The relevant auditbeat logs looked like these:
```
jul 01 00:00:36 INFO  [monitoring] log/log.go:145        Non-zero metrics in the last 30s {"monitoring": {"metrics": {"auditd":{"kernel_lost":7},"beat":{"cpu":...
jul 01 00:01:06 INFO  [monitoring] log/log.go:145        Non-zero metrics in the last 30s {"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":405060,"...
jul 01 00:01:08 INFO  [auditd]     auditd/audit_linux.go:364  kernel lost events: 4 (total: 172642)
jul 01 00:01:36 INFO  [monitoring] log/log.go:145        Non-zero metrics in the last 30s {"monitoring": {"metrics": {"auditd":{"kernel_lost":4},"beat":{"cpu":...
jul 01 00:02:06 INFO  [monitoring] log/log.go:145        Non-zero metrics in the last 30s {"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":405060,"...
jul 01 00:02:08 INFO  [auditd]     auditd/audit_linux.go:364  kernel lost events: 3 (total: 172645)
jul 01 00:02:34 ERROR [publisher_pipeline_output]        pipeline/output.go:106  Failed to connect to backoff(elasticsearch(https://es.log...:30920)): Get https..
jul 01 00:02:34 INFO  [publisher_pipeline_output]        pipeline/output.go:99   Attempting to reconnect to backoff(elasticsearch(https://es.log...:30920)) ..
  .. with 22431 reconnect attempt(s)
jul 01 00:02:34 INFO  [publisher]  pipeline/retry.go:196 retryer: send unwait-signal to consumer
jul 01 00:02:34 INFO  [publisher]  pipeline/retry.go:198  done                 
jul 01 00:02:34 INFO  [publisher]  pipeline/retry.go:173 retryer: send wait signal to consumer
jul 01 00:02:34 INFO  [publisher]  pipeline/retry.go:175  done                 
```
(repeat forever)

According to Zabbix, we lost about 2+GB of memory during period of 30+ days (and more than 22K reconnects).

We have just now fixed access to the ES node, so I hope the memory leak is gone. (If it isn't, then something else is going on.)

This might be something worth looking into. I'll report back if the unreachable host was _not_ the cause.

**Comment by jsoriano** [comment]
Hey @wdoekes,

Thanks for your report. We use to keep Github for confirmed bugs and enhancement requests, could you please open a topic on https://discuss.elastic.co/c/elastic-stack/beats/28 to continue with the investigation of this case?
I will close this on the meantime, till a possible bug is confirmed.

For this case, the used configuration, and a memory dump can help to diagnostic the problem.

**Comment by wdoekes** [comment]
Thanks for the response, Jaime. I won't be going to the discuss board just yet, as the only interest I have in auditbeat right now, is that it shouldn't eat my memory. If that changes, I'll find the discuss board :+1:

**Comment by jsoriano** [comment]
> Thanks for the response, Jaime. I won't be going to the discuss board just yet, as the only interest I have in auditbeat right now, is that it shouldn't eat my memory. If that changes, I'll find the discuss board +1

Yeah, it shouldn't actually take all the memory. Could you share the configuration you are using? and a memory dump?

**Comment by wdoekes** [comment]
I added --httpprof yesterday (18 hours ago). And copied the auditbeat to a similar server that did not have access to see if it was indeed easily reproducable.

See this screenshot, where ns1 _has_ access to elastic, and ns2 _does not_:

![image](https://user-images.githubusercontent.com/1225014/86759711-ff320a00-c044-11ea-90da-c3f96acf02f6.png)

It looks like ns1 uses 5MB and ns2 (with connection failures) uses 31MB already.

As mentioned, auditbeat is taken from the elastic repo:
```
# apt-cache policy auditbeat
auditbeat:
  Installed: 7.8.0
  Candidate: 7.8.0
  Version table:
 *** 7.8.0 500
        500 https://artifacts.elastic.co/packages/7.x/apt stable/main amd64 Packages
        100 /var/lib/dpkg/status
```
Changed config consists of an replaced auditbeat.yml and /var/lib/auditbeat.keystore.

```console
/etc/auditbeat# cat auditbeat.yml | sed -e '/^ *#/d;/^$/d;s/^  hosts: [[].*/  hosts: ["hidden:30920"]/'
```
```
auditbeat.modules:
- module: auditd
  audit_rule_files: [ '${path.config}/audit.rules.d/*.conf' ]
  audit_rules: |
    -w /etc/group -p wa -k identity
    -w /etc/passwd -p wa -k identity
    -w /etc/gshadow -p wa -k identity
- module: file_integrity
  paths:
  - /bin
  - /usr/bin
  - /sbin
  - /usr/sbin
  - /etc
- module: system
  datasets:
    - package # Installed, updated, and removed packages
  period: 2m # The frequency at which the datasets check for changes
- module: system
  datasets:
    - host    # General host information, e.g. uptime, IPs
    - login   # User logins, logouts, and system boots.
    - process # Started and stopped processes
    - user    # User information
  state.period: 12h
  user.detect_password_changes: true
  login.wtmp_file_pattern: /var/log/wtmp*
  login.btmp_file_pattern: /var/log/btmp*
setup.template.settings:
  index.number_of_shards: 1
output.elasticsearch:
  hosts: ["hidden:30920"]
  protocol: "https"
  username: ${ES_USER}
  password: ${ES_PWD}
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
```
Anything more I can get you?

**Comment by jsoriano** [comment]
@wdoekes thanks for your analysis.

I have tried the scenario you mention and I could actually reproduce an increase of memory usage, but I think this can be expected, let me explain.

Beats have an internal memory queue, this queue is used to prepare batches to send events to outputs in a more efficient way. It also helps preserving events in case the output is not available during some time, to avoid data loss. You can read more about this queue here: https://www.elastic.co/guide/en/beats/auditbeat/7.8/configuring-internal-queue.html
I think that the memory increase you see is caused by the events stored on this internal queue.

I tried some things to speed-up the experiment:
1. Reducing the maximum backoff delay, so retries happen much more frequently:
```
output.elasticsearch:
  ...
  backoff.init: 100ms
  backoff.max: 500ms
```
2. Reducing the collection periods in auditbeat modules (`period: 10s` and `state.period: 30s`)

Retrying much faster doesn't increase the memory usage, this would discard any leak caused by these reconnection attempts.

Reducing the collection period by itself does increase the memory usage. But, on my experiment, this memory is returned if Elasticsearch is recovered, so it seems that something is being stored in memory while Elasticsearch is down. This leads to the memory queue.

I tried then to reduce a lot the size of the memory queue, so it keeps much less events, and then I saw that the memory doesn't increase. You can try that with the following config:
```
queue.mem:
  events: 32
  flush.min_events: 16
```

So I would discard a leak if the memory usage is corrected after Elasticsearch is up again. If long downtimes can be expected in your deployment, and the internal queue is taking a lot of memory, you can consider alternatives as [spooling to disk](https://www.elastic.co/guide/en/beats/auditbeat/7.8/configuring-internal-queue.html#configuration-internal-queue-spool).

In any case 2GB seems too much for an internal queue, there may be some area of improvement in how memory is managed on these cases, but I wonder if it worth optimizing for the case of having an output down for so long :slightly_smiling_face:
