### ISSUE TITLE
use processor in filebeat modules 

### ISSUE THREAD

**Issue by mdiehm** [elastic/beats#19649]
I have asked this in the forum but no useful answers so I suspect it might be a bug in beats...

I try to filter messages in the _filebeat module section_ and with that divide a single logstream coming in through syslog into system and iptables parsed logs (through these modules).
Syslog is received from our linux based (openwrt to be specific) devices over the network and stored to file locally with rsyslog. Filebeat picks up the local logs and should preparse them through system and iptables modules.

An example per device logfile looks like this.

```
May 21 14:27:11 tom-tel netifd: wan (1075): udhcpc: sending renew to 192.168.0.1
May 21 14:27:11 tom-tel netifd: wan (1075): udhcpc: lease of 192.168.0.136 obtained, lease time 3600
May 21 14:39:00 tom-tel crond[931]: USER root pid 29994 cmd /usr/sbin/nw-signal
May 21 14:39:21 tom-tel kernel: [756813.361341] REJECT wan in: IN=eth0.2 OUT= MAC=ff:ff:ff:ff:ff:ff:d4:81:d7:7a:0b:06:08:00:45:00:01:68 SRC=0.0.0.0 DST=255.255.255.255 LEN=360 TOS=0x00 PREC=0x00 TTL=64 ID=25352 PROTO=UDP SPT=68 DPT=67 LEN=340

```
My config for the system module looks like this. Unfortunately no success so far.

Logline:

```
Jun 25 08:35:33 kandern-wifi2wifi-a100m kernel: [312555.373278] REJECT wan in: IN=wlan0 OUT= MAC=94:83:c4:02:7c:2c:38:10:d5:4a:a2:f3:08:00 SRC=192.168.178.1 DST=192.168.178.68 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=26962 DF PROTO=TCP SPT=472
96 DPT=80 WINDOW=14600 RES=0x00 SYN URGP=0

```
Config:

```
- module: system
  # Syslog
  syslog:
    enabled: true
    var.paths: ["/var/log/filebeat/narrowin/*"]

    input.processors:
      - drop_event.when.contains.message: "REJECT"
```

filebeat debug log:

```
2020-06-25T08:35:42.106+0200    DEBUG   [publisher]     pipeline/client.go:220  Pipeline client receives callback 'onFilteredOut' for event: {Timestamp:2020-06-25 08:35:37.105491598 +0200 CEST m=+41.850465821 Meta:{"pipeline":"filebeat-7.8.0-system-syslog-pipeline"} Fields:{"ecs":{"version":"1.5.0"},"event":{"dataset":"system.syslog","module":"system","timezone":"+02:00"},"fileset":{"name":"syslog"},"input":{"type":"log"},"log":{"file":{"path":"/var/log/filebeat/narrowin/kandern-wifi2wifi-a100m.log"},"offset":11690382},"message":"Jun 25 08:35:33 kandern-wifi2wifi-a100m kernel: [312555.373278] REJECT wan in: IN=wlan0 OUT= MAC=94:83:c4:02:7c:2c:38:10:d5:4a:a2:f3:08:00 SRC=192.168.178.1 DST=192.168.178.68 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=26962 DF PROTO=TCP SPT=47296 DPT=80 WINDOW=14600 RES=0x00 SYN URGP=0","service":{"type":"system"}} Private:{Id: Finished:false Fileinfo:0xc00079add0 Source:/var/log/filebeat/narrowin/kandern-wifi2wifi-a100m.log Offset:11690663 Timestamp:2020-06-25 08:34:58.981880341 +0200 CEST m=+3.726854576 TTL:-1ns Type:log Meta:map[] FileStateOS:98042187-64768} TimeSeries:false}
2020-06-25T08:35:42.106+0200    DEBUG   [acker] beater/acker.go:64      stateful ack    {"count": 1}
2020-06-25T08:35:42.106+0200    DEBUG   [registrar]     registrar/registrar.go:356      Processing 1 events
2020-06-25T08:35:42.106+0200    DEBUG   [registrar]     registrar/registrar.go:326      Registrar state updates processed. Count: 1
2020-06-25T08:35:42.106+0200    DEBUG   [registrar]     registrar/registrar.go:411      Write registry file: /var/lib/filebeat/registry/filebeat/data.json (10)
2020-06-25T08:35:42.172+0200    DEBUG   [reader_multiline]      multiline/multiline.go:177      Multiline event flushed because timeout reached.
2020-06-25T08:35:42.172+0200    DEBUG   [add_docker_metadata]   add_docker_metadata/add_docker_metadata.go:206  Container not found: cid=kandern-wifi2wifi-a100m.log
2020-06-25T08:35:42.172+0200    DEBUG   [processors]    processing/processors.go:187    Publish event: {
  "@timestamp": "2020-06-25T06:35:37.171Z",
  "@metadata": {
```

In kibana I still see the REJECT line appear under the system logs. Any idea why this is not dropped?

**Comment by andresrc** [comment]
Hi! Can you add the link to the discuss conversation? Thanks!

**Comment by fredtj** [comment]
`2020-06-25T08:35:42.106+0200    DEBUG   [publisher]     pipeline/client.go:220  Pipeline client receives callback 'onFilteredOut' for event: {Timestamp:2020-06-25 08:35:37.105491598 +0200 CEST m=+41.850465821 Meta:{"pipeline":"filebeat-7.8.0-system-syslog-pipeline"} Fields:{"ecs":{"version":"1.5.0"},"event":{"dataset":"system.syslog","module":"system","timezone":"+02:00"},"fileset":{"name":"syslog"},"input":{"type":"log"},"log":{"file":{"path":"/var/log/filebeat/narrowin/kandern-wifi2wifi-a100m.log"},"offset":11690382},"message":"Jun 25 08:35:33 kandern-wifi2wifi-a100m kernel: [312555.373278] REJECT wan in: IN=wlan0 OUT= MAC=94:83:c4:02:7c:2c:38:10:d5:4a:a2:f3:08:00 SRC=192.168.178.1 DST=192.168.178.68 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=26962 DF PROTO=TCP SPT=47296 DPT=80 WINDOW=14600 RES=0x00 SYN URGP=0","service":{"type":"system"}} Private:{Id: Finished:false Fileinfo:0xc00079add0 Source:/var/log/filebeat/narrowin/kandern-wifi2wifi-a100m.log Offset:11690663 Timestamp:2020-06-25 08:34:58.981880341 +0200 CEST m=+3.726854576 TTL:-1ns Type:log Meta:map[] FileStateOS:98042187-64768} TimeSeries:false}`

isn't this just a debug message saying the event was filtered out? does the event get published in elastic?

**Comment by mdiehm** [comment]
https://discuss.elastic.co/t/filebeat-drop-event-module-input/238610

> Hi! Can you add the link to the discuss conversation? Thanks!

https://discuss.elastic.co/t/filebeat-drop-event-module-input/238610

**Comment by mdiehm** [comment]
> `2020-06-25T08:35:42.106+0200 DEBUG [publisher] pipeline/client.go:220 Pipeline client receives callback 'onFilteredOut' for event: {Timestamp:2020-06-25 08:35:37.105491598 +0200 CEST m=+41.850465821 Meta:{"pipeline":"filebeat-7.8.0-system-syslog-pipeline"} Fields:{"ecs":{"version":"1.5.0"},"event":{"dataset":"system.syslog","module":"system","timezone":"+02:00"},"fileset":{"name":"syslog"},"input":{"type":"log"},"log":{"file":{"path":"/var/log/filebeat/narrowin/kandern-wifi2wifi-a100m.log"},"offset":11690382},"message":"Jun 25 08:35:33 kandern-wifi2wifi-a100m kernel: [312555.373278] REJECT wan in: IN=wlan0 OUT= MAC=94:83:c4:02:7c:2c:38:10:d5:4a:a2:f3:08:00 SRC=192.168.178.1 DST=192.168.178.68 LEN=60 TOS=0x00 PREC=0x00 TTL=64 ID=26962 DF PROTO=TCP SPT=47296 DPT=80 WINDOW=14600 RES=0x00 SYN URGP=0","service":{"type":"system"}} Private:{Id: Finished:false Fileinfo:0xc00079add0 Source:/var/log/filebeat/narrowin/kandern-wifi2wifi-a100m.log Offset:11690663 Timestamp:2020-06-25 08:34:58.981880341 +0200 CEST m=+3.726854576 TTL:-1ns Type:log Meta:map[] FileStateOS:98042187-64768} TimeSeries:false}`
> 
> isn't this just a debug message saying the event was filtered out? does the event get published in elastic?

the event gets published but no prosecessor filtering is applied. Which means all iptables rules also are send as syslog which is not what was intended. 

The goal is to separate one log into parts which match the corresponding filebeat modules - e.g. syslog and iptables

**Comment by mdiehm** [comment]
Is there anything I can provide to get some more clarification in this issue? Can you reconstruct the problem? Is it a problem at all or a configuration issue?

**Comment by urso** [comment]
The system/syslog module has a list of processors, which might clash with your setup. This is due to processors configs from different source not getting 'appended', but might overwrite each other. Checking its definition the syslog module has 2 processors pre-configured. you might want to add your processor after the existing processors at index 2. e.g.

```
...
input.processors.2:
  drop_event:
    when.contains.message: "REJECT"
```

**Comment by mdiehm** [comment]
With this configuration I get the following error:
```
Jul 21 14:33:59 pub filebeat[24859]: 2020-07-21T14:33:59.218+0200        ERROR        fileset/factory.go:103        Error creating input: each processor must have exactly one act
ion, but found 0 actions ()
```

**Comment by urso** [comment]
That's interesting. Can you share the complete configuration you are using?

**Comment by mdiehm** [comment]
Sure:

filebeat.yml
```
filebeat.inputs:
- type: log
  enabled: false
  paths:
    - /var/log/*.log
- type: syslog
  enabled: false
  protocol.udp:
    host: "195.201.59.197:5514"
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:
  host: "192.168.122.12:5601"
output.elasticsearch:
  hosts: ["192.168.122.12:9200"]
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
```
modules.d/system.yml
```
- module: system
  syslog:
    enabled: true
    var.paths: ["/var/log/filebeat/narrowin/testfilebeat"]
    input.processors.2:
     - drop_event:
         when.contains.message: "REJECT"
```

**Comment by urso** [comment]
Which beats version are you using. Checking the definition for 7.8+ there are 2 processors predefined. Using Filebeat 7.7 for example the index must be `1`, not `2`.

**Comment by mdiehm** [comment]
```
root@pub:/etc/filebeat# /usr/bin/filebeat version
filebeat version 7.8.0 (amd64), libbeat 7.8.0 [f79387d32717d79f689d94fda1ec80b2cf285d30 built 2020-06-14 18:15:37 +0000 UTC]
```

**Comment by mdiehm** [comment]
@urso any news on this topic?

**Comment by urso** [comment]
Checking the code in 7.8 it looks like the outstanding bug for appending processor has been fixed. Using your test file, this minimal config removes the 'REJECT' line for me:

```
filebeat.modules:
- module: system
  syslog:
    enabled: true
    var.paths: ["testfilebeat"]
    input.processors:
    - drop_event.when.contains.message: "REJECT"

output.console:
  codec.format.string: "%{[message]}"
```

this configuration directly prints the original log message as is to the console. Please note, that I removed the configured inputs, in order to create a more minified test case.

I'm testing filebeat using this command:

```
rm -fR data; ./filebeat -e  -c test.yml
```

This reports the log line (the REJECT line was removed):

```
Jul 22 09:20:00 testfilebeat narrowin: /usr/sbin/nw-system-info: Error: zone wan not found
Jul 22 09:20:35 testfilebeat ulogd[876]: [DESTROY] ORIG: SRC=127.0.0.1 DST=127.0.0.1 PROTO=UDP SPT=58664 DPT=53 PKTS=2 BYTES=124 , REPLY: SRC=127.0.0.1 DST=127.0.0.1 PROTO=UDP SPT=53 DPT=58664 PKTS=2 BYTES=168
```

I noticed you have the syslog input configured as well. With your configuration you have one input collecting from `/var/log/*.log`, one syslog server, and one input collecting from whatever path you have configured. Is there a chance that the line to be removed as collected by one of the other inputs, instead of the system module?
