### ISSUE TITLE
Add or/and/not in processors

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#1977]
This meta issue has the scope of documenting how to add support for `and`, `or` and `not` support in the condition associated to the processors.

Let's start with a bit of overview of the `processors` configuration option.

The general definition of `processors` is the following:
```
processors:
   - <processor>:
       when:
         <condition>
       <parameters>
```

where:
`<processor>` can be one of: `drop_event`, `drop_fields`, `include_fields`.
`<condition>` contains the definition of the condition that needs to be fulfilled in order for the processor to be executed. If no condition is present, the processor is always executed.
and `<parameters>` is the list of parameters that are executed by the processor when the condition is fulfilled.

The signature for `or`, `and` and `not` is:

```
processors:
  - <processor>:
     when:
       or/and/not:
         - <condition>
         - <condition>
         - <condition>
```

As an example, the condition `a1 or a2 and a3` translates to:
```
processors:
   - <processor>:
     when:
        or:
          - a1
          - and:
             - a2
             - a3
```
