### ISSUE TITLE
Filebeat & Metricbeat fail to restart after being stopped by an empty config

### ISSUE THREAD

**Issue by michaelolo24** [elastic/beats#19813]
When enrolling an agent with the `system` integration enabled, `filebeat` and `metricbeat` successfully run. When an empty config is passed (no integrations), they are successfully stopped. When trying to reapply the `system` only config, `filebeat` and `metricbeat` fail to restart.

Logs:

[elastic-agent.txt](https://github.com/elastic/beats/files/4899363/elastic-agent.txt)
[metricbeat.txt](https://github.com/elastic/beats/files/4899365/metricbeat.txt)
[filebeat.txt](https://github.com/elastic/beats/files/4899366/filebeat.txt)

Empty Yaml:

```
id: 87a56de0-c21c-11ea-ba0c-033943e6532a
revision: 1
settings:
  monitoring:
    enabled: true
    use_output: default
    logs: true
    metrics: true
outputs:
  default:
    type: elasticsearch
    hosts:
      - 'http://10.0.0.85:9200'
inputs: []
```

SystemOnly Yaml

```
id: fe9187b0-c21a-11ea-ba0c-033943e6532a
revision: 2
settings:
  monitoring:
    enabled: true
    use_output: default
    logs: true
    metrics: true
outputs:
  default:
    type: elasticsearch
    hosts:
      - 'http://10.0.0.85:9200'
inputs:
  - id: 001eb760-c21b-11ea-ba0c-033943e6532a
    name: system-1
    type: logs
    use_output: default
    meta:
      package:
        name: system
        version: 0.3.0
    dataset:
      namespace: default
    streams:
      - id: logs-system.auth
        dataset:
          name: system.auth
          type: logs
        paths:
          - /var/log/auth.log*
          - /var/log/secure*
        exclude_files:
          - .gz$
        multiline:
          pattern: ^\s
          match: after
        processors:
          - add_locale: null
          - add_fields:
              target: ''
              fields:
                ecs.version: 1.5.0
      - id: logs-system.syslog
        dataset:
          name: system.syslog
          type: logs
        paths:
          - /var/log/messages*
          - /var/log/syslog*
        exclude_files:
          - .gz$
        multiline:
          pattern: ^\s
          match: after
        processors:
          - add_locale: null
          - add_fields:
              target: ''
              fields:
                ecs.version: 1.5.0
  - id: 001eb760-c21b-11ea-ba0c-033943e6532a
    name: system-1
    type: system/metrics
    use_output: default
    meta:
      package:
        name: system
        version: 0.3.0
    dataset:
      namespace: default
    streams:
      - id: system/metrics-system.cpu
        dataset:
          name: system.cpu
          type: metrics
        metricsets:
          - cpu
        core.metrics: null
        cpu.metrics:
          - percentages
          - normalized_percentages
        period: 10s
      - id: system/metrics-system.diskio
        dataset:
          name: system.diskio
          type: metrics
        metricsets:
          - diskio
      - id: system/metrics-system.load
        dataset:
          name: system.load
          type: metrics
        metricsets:
          - load
        core.metrics: null
        cpu.metrics: null
        period: 10s
        process.include_top_n.by_cpu: null
        process.include_top_n.by_memory: null
        processes: null
      - id: system/metrics-system.memory
        dataset:
          name: system.memory
          type: metrics
        metricsets:
          - memory
        core.metrics: null
        cpu.metrics: null
        period: 10s
        process.include_top_n.by_cpu: null
        process.include_top_n.by_memory: null
        processes: null
      - id: system/metrics-system.network
        dataset:
          name: system.network
          type: metrics
        metricsets:
          - network
        core.metrics: null
        cpu.metrics: null
        period: 10s
        process.include_top_n.by_cpu: null
        process.include_top_n.by_memory: null
        processes: null
      - id: system/metrics-system.process
        dataset:
          name: system.process
          type: metrics
        metricsets:
          - process
        period: 10s
        process.include_top_n.by_cpu: 5
        process.include_top_n.by_memory: 5
        processes:
          - .*
      - id: system/metrics-system.process_summary
        dataset:
          name: system.process_summary
          type: metrics
        metricsets:
          - process_summary
        core.metrics: null
        cpu.metrics: null
        period: 10s
        process.include_top_n.by_cpu: null
        process.include_top_n.by_memory: null
        processes: null
      - id: system/metrics-system.socket_summary
        dataset:
          name: system.socket_summary
          type: metrics
        metricsets:
          - socket_summary
        core.metrics: null
        cpu.metrics: null
        period: 10s
        process.include_top_n.by_cpu: null
        process.include_top_n.by_memory: null
        processes: null
      - id: system/metrics-system.uptime
        dataset:
          name: system.uptime
          type: metrics
        metricsets:
          - uptime
        core.metrics: null
        cpu.metrics: null
        period: 10s
        processes: null
```

actions_store YAML:

```
action_id: 2664484e-89d3-4369-8d93-1dd67ccc5b12
action_type: CONFIG_CHANGE
config:
  id: fe9187b0-c21a-11ea-ba0c-033943e6532a
  inputs:
  - dataset:
      namespace: default
    id: 001eb760-c21b-11ea-ba0c-033943e6532a
    meta:
      package:
        name: system
        version: 0.3.0
    name: system-1
    streams:
    - dataset:
        name: system.auth
        type: logs
      exclude_files:
      - .gz$
      id: logs-system.auth
      multiline:
        match: after
        pattern: ^\s
      paths:
      - /var/log/auth.log*
      - /var/log/secure*
      processors:
      - add_locale: null
      - add_fields:
          fields:
            ecs.version: 1.5.0
          target: ""
    - dataset:
        name: system.syslog
        type: logs
      exclude_files:
      - .gz$
      id: logs-system.syslog
      multiline:
        match: after
        pattern: ^\s
      paths:
      - /var/log/messages*
      - /var/log/syslog*
      processors:
      - add_locale: null
      - add_fields:
          fields:
            ecs.version: 1.5.0
          target: ""
    type: logs
    use_output: default
  - dataset:
      namespace: default
    id: 001eb760-c21b-11ea-ba0c-033943e6532a
    meta:
      package:
        name: system
        version: 0.3.0
    name: system-1
    streams:
    - core.metrics: null
      cpu.metrics:
      - percentages
      - normalized_percentages
      dataset:
        name: system.cpu
        type: metrics
      id: system/metrics-system.cpu
      metricsets:
      - cpu
      period: 10s
    - dataset:
        name: system.diskio
        type: metrics
      id: system/metrics-system.diskio
      metricsets:
      - diskio
    - core.metrics: null
      cpu.metrics: null
      dataset:
        name: system.load
        type: metrics
      id: system/metrics-system.load
      metricsets:
      - load
      period: 10s
      process.include_top_n.by_cpu: null
      process.include_top_n.by_memory: null
      processes: null
    - core.metrics: null
      cpu.metrics: null
      dataset:
        name: system.memory
        type: metrics
      id: system/metrics-system.memory
      metricsets:
      - memory
      period: 10s
      process.include_top_n.by_cpu: null
      process.include_top_n.by_memory: null
      processes: null
    - core.metrics: null
      cpu.metrics: null
      dataset:
        name: system.network
        type: metrics
      id: system/metrics-system.network
      metricsets:
      - network
      period: 10s
      process.include_top_n.by_cpu: null
      process.include_top_n.by_memory: null
      processes: null
    - dataset:
        name: system.process
        type: metrics
      id: system/metrics-system.process
      metricsets:
      - process
      period: 10s
      process.include_top_n.by_cpu: 5
      process.include_top_n.by_memory: 5
      processes:
      - .*
    - core.metrics: null
      cpu.metrics: null
      dataset:
        name: system.process_summary
        type: metrics
      id: system/metrics-system.process_summary
      metricsets:
      - process_summary
      period: 10s
      process.include_top_n.by_cpu: null
      process.include_top_n.by_memory: null
      processes: null
    - core.metrics: null
      cpu.metrics: null
      dataset:
        name: system.socket_summary
        type: metrics
      id: system/metrics-system.socket_summary
      metricsets:
      - socket_summary
      period: 10s
      process.include_top_n.by_cpu: null
      process.include_top_n.by_memory: null
      processes: null
    - core.metrics: null
      cpu.metrics: null
      dataset:
        name: system.uptime
        type: metrics
      id: system/metrics-system.uptime
      metricsets:
      - uptime
      period: 10s
      processes: null
    type: system/metrics
    use_output: default
  outputs:
    default:
      api_key: YXkzNXMBenOyhN8KBJ7f:3a4HisHsRp2LUNNK_VxS3g
      hosts:
      - http://10.0.0.85:9200
      type: elasticsearch
  revision: 2
  settings:
    monitoring:
      enabled: true
      logs: true
      metrics: true
      use_output: default
```

For confirmed bugs, please report:
- Version: 7.9
- Operating System: Windows 10 Pro (VM)

- Steps to Reproduce:

1. Enroll an agent with a `system` integration
2. Change configuration without any integrations
3. Reapply config with `system` integration
4. `filebeat` and `metricbeat` fail to restart
