### ISSUE TITLE
FileBeat: decode_json_fields processor max_depth option not working 

### ISSUE THREAD

**Issue by vitaliy-kravchenko** [elastic/beats#19830]
To prevent creating tons of document fields in an Elasticsearch log index I want to control nested JSON parsing depth.

Related discussion post: https://discuss.elastic.co/t/filebeat-decode-json-fields-processor-max-depth-option-not-working/240948

Filebeat version 7.8.0 (also tested on 6.8.10 and result is the same)

/tmp/filebeat.conf:

```
filebeat.inputs:
- type: log
  paths:
    - /tmp/filebeat.input

processors:
  - decode_json_fields:
      fields: ["message"]
      max_depth: 1
      target: "parsed"

output.console:
  pretty: true
```

/tmp/filebeat.input:

```
{"top": "top_value", "top_obj": {"level_1": "level_1_value", "level_1_obj": {"level_2": "level_2_value", "level_2_obj": {"level_3": "level_3_value"}}}}
```

Command:

```
filebeat  -e -c /tmp/filebeat.conf
```

Result:

```
"parsed": {
  "top_obj": {
    "level_1_obj": {
      "level_2": "level_2_value",
      "level_2_obj": {
        "level_3": "level_3_value"
      }
    },
    "level_1": "level_1_value"
  },
  "top": "top_value"
}
```

Expected result:

```
"parsed": {
  "top_obj": {
    "level_1_obj": "{\"level_2\": \"level_2_value\", \"level_2_obj\": {\"level_3\": \"level_3_value\"}}",
    "level_1": "level_1_value"
  },
  "top": "top_value"
}
```

**Comment by KhaledSakr** [comment]
It works properly. It just doesn't do what you're expecting.

Your json input doesn't have nested json. If you parse it in the browser with `JSON.parse`, you'll find the following:
![image](https://user-images.githubusercontent.com/15192797/91447103-93b42e00-e878-11ea-8e93-4f9ccfaa0483.png)

To get your desired effect, your `level_1_obj` value itself will have to be stringified first
```json
"level_1_obj":"{\"level_2\":\"level_2_value\",\"level_2_obj\":{\"level_3\":\"level_3_value\"}}"
```

What `max_depth` does is recursively trying to decode the underlying fields until the `max_depth` is hit. So if you set it to `2`, it will still be able to decode `"level_1_obj":"{\"level_2\":\"level_2_value\",\"level_2_obj\":{\"level_3\":\"level_3_value\"}}"`

**Comment by vitaliy-kravchenko** [comment]
Anyway, the documentation is not clear enough for me. And I suppose not only for me but for many other users.
The `max_depth` option behaves more like a limit option to prevent stack overflow but not for parsing JSON to N level depth and leave all next levels as an unparsed string.
I implemented the functional with logstash + ruby plugin. And did all necessary parsing logic with the ruby script. Now I have only the first 2 levels as document fields in Elasticsearch indexes. All next subfields stored as a string value of the fields.

**Comment by milesich** [comment]
I understood it exactly as @vitaliy-kravchenko. The `max_depth` option behaves as a limit to prevent mapping explosion.

**Comment by caiobegotti** [comment]
I have tons of respect for Filebeat and I use it in multiple projects but I just spent 3 days trying to debug this until I found this issue and I agree it looks like the documentation is not clear at all about this. While we're at it, I'm not sure expecting `message` to be stringfied so this can work properly is reasonable. I've never seen logs that are like that. Right now I'm trying to fix this problem by doing some Elasticsearch's ingest pipeline trickery but it's depressing as Filebear is so much better than ES pipelines despite of this issue... 😢

**Comment by eedugon** [comment]
@sayden : I guess this issue is important to provide a reliable way to prevent mapping explosions.

I'm creating some configuration references to index our own beats logs (running on Kubernetes) in Elasticsearch. With the `json` logging support (`logging.json: true`) this is very straight forward and the logs can be "enriched" just by using the `decode_json_fields`.

With `max_depth: 1` the objective should be to have only the first level of fields decoded (`level`, `timestamp`, `logger`, `caller`, `message`, `monitoring`, etc), and if any of these are json objects they shouldn't be expanded to fields.

As you know, the `monitoring` part of our log messages (in Filebeat or Metricbeat for example) is a big json object with a lot of sub-objects. Expanding them always makes very difficult to index our own logs in a nice way in Elasticsearch (we definitely don't want to create all monitoring sub-fields in a filebeat index, as it doesn't make any sense, but keeping the long `monitoring` strings as references makes sense).

I don't know if this is considered a bug or not (@adriansr might have a different view), but just for your consideration!

**Comment by dennybaa** [comment]
same behaviour
```
filebeatConfig:
  filebeat.yml: |
    ## Hints based autodiscover
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true

    processors:
      - if:
          equals:
            kubernetes.labels.app/logs_json: "true"
        then:
        - decode_json_fields:
            fields: ["message"]
            process_array: false
            max_depth: 1
            target: "zigi"
            overwrite_keys: true
            add_error_key: true
```

Neither `process_array` nor `max_depth` has any effect on nesting and json parsing.

**Comment by dennybaa** [comment]
same behavior:

```yaml
filebeatConfig:
  filebeat.yml: |
    ## Hints based autodiscover
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true

    processors:
      - if:
          equals:
            kubernetes.labels.app/logs_json: "true"
        then:
        - decode_json_fields:
            fields: ["message"]
            process_array: false
            max_depth: 1
            target: "foo"
            overwrite_keys: true
            add_error_key: true
```

Both `process_array` and `max_depth` have no effect on nesting and json parsing :(
