### ISSUE TITLE
Filebeat setup error on machine-learning 

### ISSUE THREAD

**Issue by liza-mae** [elastic/beats#19964]
- Version: 7.9.0 BC1 
- Operating System: Ubuntu 16
- Steps to Reproduce: 
Install and run ES/Kibana. 
Install Filebeat. 
Run 
```
./filebeat setup 
Setting up ML using setup --machine-learning is going to be removed in 8.0.0. Please use the ML app instead.
See more: https://www.elastic.co/guide/en/machine-learning/current/index.html
Exiting: 1 error: Error setting up ML for nginx_ecs: cannot set up ML with prefix: filebeat-nginx_ecs-access-
```
Not sure if this related to another issue I opened elastic/beats#12998 and it is now just throwing a different error in 7.9 or if it is a new error.

**Comment by kvch** [comment]
`--setup` has been removed from Beats 1.5 years ago: https://github.com/elastic/beats/pull/10138

I have also downloaded the latest BC for 7.9, but the binary does not provide a `--setup` flag. Are you sure you are running 7.9?

**Comment by liza-mae** [comment]
@kvch that was a typo in my description it's not --setup it's filebeat setup.

**Comment by kvch** [comment]
Have you modified the configuration files? If yes, could you please share it?
Are you connecting to an OSS version of ES and Kibana?

I have tried reproducing the issue multiple times with different configurations. So far no success.

**Comment by liza-mae** [comment]
@kvch it is with security enabled, machine learning is not part of OSS maybe that is why it is not seen there?  I have not tried it.  The config only has my security settings, as follows:

```
output.elasticsearch:
  username: elastic
  password: changeme
  protocol: https
  hosts: ["10.0.2.15:9200"]
  ssl.certificate_authorities: /home/vagrant/filebeat-7.9.0-linux-x86_64/ca/ca.crt
  ssl.certificate: /home/vagrant/filebeat-7.9.0-linux-x86_64/node/node.crt
  ssl.key: /home/vagrant/filebeat-7.9.0-linux-x86_64/node/node.key
setup.kibana:
  host: "10.0.2.15:5601"
  protocol: https
  ssl.certificate_authorities: /home/vagrant/filebeat-7.9.0-linux-x86_64/ca/ca.crt
  ssl.certificate: /home/vagrant/filebeat-7.9.0-linux-x86_64/node/node.crt
  ssl.key: /home/vagrant/filebeat-7.9.0-linux-x86_64/node/node.key

```
