### ISSUE TITLE
Verify and improve syslog input ECS compatibility

### ISSUE THREAD

**Issue by urso** [elastic/beats#20029]
The syslog input in Filebeat reports similar fields for the different sources UDP, TCP, and Unix Socket. The docs state that `logs.syslog` namespace is used, but from testing the input it seems like the inputs still use the top-level namespace `syslog`. The priority and facility labels also don't seem to be in line with ECS.

We should double check fields for equivalents in ECS and update the input accordingly.

**Comment by andrewkroh** [comment]
I can confirm that the syslog input does not follow the ECS. I noticed this when Elastic Agent with a package was producing the fields.

| Field                 	| ECS                      	| Notes                                                                                                                                                                           	|
|-----------------------	|--------------------------	|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|
| hostname              	| host.name                	|                                                                                                                                                                                 	|
| process.pid           	| ✅                        	|                                                                                                                                                                                 	|
| message               	| ✅                        	|                                                                                                                                                                                 	|
| process.program       	| process.name             	|                                                                                                                                                                                 	|
| syslog.priority       	| log.syslog.priority      	|                                                                                                                                                                                 	|
| syslog.severity       	| log.syslog.severity.code 	|                                                                                                                                                                                 	|
| syslog.severity_label 	| log.syslog.severity.name 	|                                                                                                                                                                                 	|
| syslog.facility       	| log.syslog.facility.code 	|                                                                                                                                                                                 	|
| syslog.facility_label 	| log.syslog.facility.name 	|                                                                                                                                                                                 	|
| event.sequence        	| ✅                        	| Not part of any syslog RFC. Cisco invention IIRC.                                                                                                                               	|
|                       	|                          	|                                                                                                                                                                                 	|
|                       	| event.original           	| The raw bytes from the wire should go here.                                                                                                                                     	|
| log.source.address    	| log.source.ip *          	| For selecting logs from one device I have always found having the source IP in its own field far more useful than the IP and port combined since the port is usually ephemeral. 	|
| log.source.address    	| log.source.port *        	|                                                                                                                                                                                 	|


`*` Not part of ECS.

**Comment by dgknuth** [comment]
Has this received any additional work? unfortunately without log severity code, it makes monitoring _extremely_ difficult to quickly catch problems.

**Comment by andrewkroh** [comment]
Instead of changing the syslog input we have created a `syslog` processor (this avoids breaking changes for existing users and is a better design). This is decoupled from the input so that it can be used on data from any input. The processor does follow ECS conventions. It will be released in 8.2.0.

You can preview the docs at https://github.com/elastic/beats/blob/main/libbeat/processors/syslog/docs/syslog.asciidoc.

Relates: https://github.com/elastic/beats/pull/30541

**Comment by hrak** [comment]
For those that ended up here in hopes of finding ECS compatible syslog input fixes, you can work around the lack of ECS compatibility by using some filebeat processors:

```yaml
- type: syslog
  format: auto
  protocol.unix:
    path: "/var/run/fb-syslog.sock"
    socket_type: datagram
    group: "syslog"
    mode: "0660"
    pipeline: "syslog"
  processors:
  - copy_fields:
      fields:
        - from: "event.severity"
          to: "log.syslog.severity.code"
      ignore_missing: false
      fail_on_error: true
  - rename:
      fields:
        - from: "hostname"
          to: "host.name"
      ignore_missing: false
      fail_on_error: true
  - rename:
      fields:
        - from: "process.program"
          to: "process.name"
      ignore_missing: false
      fail_on_error: true
  - rename:
      fields:
        - from: "syslog.priority"
          to: "log.syslog.priority"
      ignore_missing: false
      fail_on_error: true
  - rename:
      fields:
        - from: "syslog.severity_label"
          to: "log.syslog.severity.name"
      ignore_missing: false
      fail_on_error: true
  - rename:
      fields:
        - from: "syslog.facility"
          to: "log.syslog.facility.code"
      ignore_missing: false
      fail_on_error: true
  - rename:
      fields:
        - from: "syslog.facility_label"
          to: "log.syslog.facility.name"
      ignore_missing: false
      fail_on_error: true
```
