### ISSUE TITLE
Metricset can't handle consecutive dollar signs in password

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#20075]
( I'm aware of https://www.elastic.co/guide/en/beats/libbeat/master/config-file-format-tips.html#dollar-sign-strings )

For a password that contains consecutive dollar signs: `fantastic$$`

```
output.elasticsearch:
  hosts: ["http://127.0.0.1:9200"]
  username: "elastic"
  password: "fantastic$$$$" # <--- WORKS

metricbeat.modules:
 - module: elasticsearch
   metricsets:
    - index
   period: 10s
   hosts: ["http://127.0.0.1:9200"]
   username: "elastic"
   password: "fantastic$$$$" # <--- DOESN'T WORK
   xpack.enabled: true
```

Also fails when using the keychain or an environment variable.

Looks a bit similar to https://github.com/elastic/beats/issues/19849
