### ISSUE TITLE
[Metricbeat] Prometheus relabel / multi-targets

### ISSUE THREAD

**Issue by genofire** [elastic/beats#20096]
**Describe the enhancement:**
Short: relabel the hosts so it become a get parameter (`target`) and it use another (single) exporter address for it. 

An example config with new paramters (multitarget_proxy and multitarget_query):
```yml
- module: prometheus
  period: 10s
  metricsets: ["collector"]
  hosts: ["http://prometheus.io","https://prometheus.io", "http://example.com:8080"]
  metrics_path: /metrics
  multitarget_proxy: "127.0.0.1:9115" 
  multitarget_query: "target"
```

See: https://prometheus.io/docs/guides/multi-target-exporter/#running-multi-target-exporters

Example from prometheus:
```yml
scrape_configs:
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.io    # Target to probe with http.
        - https://prometheus.io   # Target to probe with https.
        - http://example.com:8080 # Target to probe with http on port 8080.
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115 
```

**Describe a specific use case for the enhancement or feature:**
Usefull if you have a proxy like exporter.
an example is the blackbox-exporter:
https://github.com/prometheus/blackbox_exporter#prometheus-configuration
