### ISSUE TITLE
Filebeat missing first character in file lines

### ISSUE THREAD

**Issue by sayden** [elastic/beats#20280]
It seems that Filebeat since version 7.8.1 (maybe earlier, I haven't tried) and in Snapshot is missing the first character of each line when reading. At least with some specific config:

### How to reproduce

`filebeat.yml`
```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /tmp/input/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.kibana:

output.console:
  pretty: true
```
1.- Create a folder in `/tmp/input` and open & create a file in `/tmp/input/hello.log`.
2.- Launch filebeat (it will read from `/tmp/input/*log`)
3.- Write `hello` insert a new line and save. Message is ok:
```json
{
  "@timestamp": "2020-07-28T14:30:54.647Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "7.9.0"
  },
  "input": {
    "type": "log"
  },
  "ecs": {
    "version": "1.5.0"
  },
  "host": {
    "name": "mcastro"
  },
  "agent": {
    "hostname": "mcastro",
    "ephemeral_id": "8d10a1a8-fa45-4cc2-b6db-4233012ae5a9",
    "id": "9a667709-feb4-4a78-b534-7b59db6ff818",
    "name": "mcastro",
    "type": "filebeat",
    "version": "7.9.0"
  },
  "log": {
    "offset": 0,
    "file": {
      "path": "/tmp/input/hello2.log"
    }
  },
  "message": "hello"
}
```
4.- Write `world`, newline and save. Message lacks the first `w`
```json
{
  "@timestamp": "2020-07-28T14:31:09.649Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "7.9.0"
  },
  "host": {
    "name": "mcastro"
  },
  "agent": {
    "ephemeral_id": "8d10a1a8-fa45-4cc2-b6db-4233012ae5a9",
    "id": "9a667709-feb4-4a78-b534-7b59db6ff818",
    "name": "mcastro",
    "type": "filebeat",
    "version": "7.9.0",
    "hostname": "mcastro"
  },
  "log": {
    "offset": 7,
    "file": {
      "path": "/tmp/input/hello2.log"
    }
  },
  "message": "orld",
  "input": {
    "type": "log"
  },
  "ecs": {
    "version": "1.5.0"
  }
}
```
