### ISSUE TITLE
[Filebeat] 7.8 Filebeat output elasticsearch pipeline broken

### ISSUE THREAD

**Issue by Bernhard-Fluehmann** [elastic/beats#20342]
I have opened a [discussion](https://discuss.elastic.co/t/filebeat-output-elasticsearch-pipeline-not-working/240167) some time ago about a potential bug I found in filebeat 7.8.

Due to lack of response and since there seem to be at least one other person having the same issue, I decided to create an issue. 

The problem description can be found in the [discussion](https://discuss.elastic.co/t/filebeat-output-elasticsearch-pipeline-not-working/240167). In short words, starting with version 7.8, pipelines configured in output.elasticsearch are not applied in elasticsearch anymore 

For confirmed bugs, please report:
- Version: 7.8.0
- Operating System: CentOS 
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-output-elasticsearch-pipeline-not-working/240167
- Steps to Reproduce: https://discuss.elastic.co/t/filebeat-output-elasticsearch-pipeline-not-working/240167

**Comment by fredtj** [comment]
I'm using filebeat 7.8 with an ingest pipeline and it's working OK - could you try with:

`parameters.pipeline: 'yourpipeline'` underneath `output.elasticsearch`?

**Comment by Bernhard-Fluehmann** [comment]
What input are you using? I have repeated the tests with the following result:
`pipeline: "test"`
input  log: OK
input udp: NOK This looks very odd to me since we are talking about an output config

`parameters.pipeline: "test1"`
input log: OK
input udp: OK

It is easily reproducible in my setup by changing the setting back and forth

Now that the parameters.pipeline seems to do the trick, I did some other tests. What I would like to achieve is to use pipelines with conditions. The reason is that filebeat is used with multiple udp inputs, each of them for another product with another dataset and pipeline. This is what I tried:

`parameters.pipelines:
    - pipeline: "test1"`

Unfortunately this forces filebeat to crash at startup.

Please let me know if you are able to reproduce the problem with the documented/standard config as well and let me know how to proceed

**Comment by fredtj** [comment]
I set up a test filebeat with the below config, these route to the correct ingest pipelines on ES.

`filebeat.inputs:
- type: log
  paths:
   - /root/test1.txt
  pipeline: "test1-pipeline"

- type: log
  paths:
  - /root/test2.txt
  pipeline: "test2-pipeline"
`

**Comment by Bernhard-Fluehmann** [comment]
@fredtj So you are using pipelines in inputs. Just tried and works for me as well, both log and udp.
I would still apreciate if you could let me know the reason why pipeline in output in combination with udp input got broken.

I'm asking this since the manual does not mention anything about pipelines in the input, but it does for the output.
Again, please let me know if you can confirm this as a bug.

**Comment by Bernhard-Fluehmann** [comment]
BTW, this is how I tested udp

    - type: udp
      host: "localhost:8080"
      fields:
        event.dataset: test1udp
      fields_under_root: true

...

And then from terminal:
echo -n "testmessage" | nc -4u localhost 8080

**Comment by fredtj** [comment]
i'm using `parameters.pipeline: 'yourpipeline'` in `output.elasticsearch`, as per my first comment. i suppose it makes sense specifying the pipeline in the input for multiple inputs, because otherwise you'd have to tag the document then add conditionals as to which pipeline to use in the output. i don't know if what you mention is a bug or not, perhaps somebody at elastic will read this :+1:

**Comment by Bernhard-Fluehmann** [comment]
@fredtj Thanks for the hint and your help. Now I have checked the manual again and found it documented in all specific inputs. I will configure pipelines in inputs from now on and leave output.elasticsearch alone.

**Comment by alexroussel** [comment]
Hello,

I'm using Filebeat 7.9.1 and I just got the same issue...

As @fredtj said, if I put `parameters.pipeline: my-pipeline` below `output.elasticsearch` or `pipeline: my-pipeline` below the `- type` of inputs it works fine !

However if I follow the documentation, it means put `pipeline: my-pipeline` below `output.elasticsearch`, at indexing the pipeline on ingest node is just **ignored**.
I found some people on the elastic forum who had probably the same issue.

If needed, I can share my `filebeat.yml`, pipeline and data I try to index, just let me know.

Thx

**Comment by Bernhard-Fluehmann** [comment]
@alexroussel Thank you very much for your information. With your hint I will be able again to use pipeline definition in outputs again in recent versions of filebeat. I would still appreciate to see this fixed or at least properly documented. As @dedemorton  mentioned in #20673, a fix would be preferred to have the same behavior on all beats. With the introduction of elastic-agent this may be even more important.

**Comment by TheRiffRafi** [comment]
Issue still persists on version 7.10.1 of filebeat.
The pipeline needs to be specified on the "Input" section of the filebeat.yml file in order for the syslog input type to be able to use an ingest pipeline.

**Comment by Bernhard-Fluehmann** [comment]
@TheRiffRafi Thanks for bringing this up.
BTW, have you tried to use
`output:
  parameters.pipeline: ...
`
instead?
This seems to be the actual behavior as mentioned in #20637. Still, for most of the cases, configuring it in the input section makes the most sense.

**Comment by Camilleli** [comment]
Issue persists on 7.10.2.
I believe the current workaround:

1. multiple inputs with multiple pipelines:
```
filebeat.inputs:
- type: udp
  host: "localhost:2514"
  pipeline: "up"
- type: udp
  host: "localhost:2515"
  pipeline: "down"

```
2. parameters.pipeline

I have tested the following but they are not working.
```
output.elasticsearch:
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.contains:
        message: "WARN"
      parameters.pipeline: "up"
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.contains:
        message: "ERR"
      parameters.pipeline: "down"

```
```
output.elasticsearch:
  indices:
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.contains:
        message: "WARN"
      pipeline: "up"
    - index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}"
      when.contains:
        message: "ERR"
      pipeline: "down"

```
