### ISSUE TITLE
fix filebeat config example yaml indentation

### ISSUE THREAD

**Issue by LeeDr** [elastic/beats#20367]
I'm not an expert on this configuration but I think this doc is wrong;
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration.html

It shows this in two places;
```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
```

And I think that caused my error on 7.9.0 like;
`error initializing beat: error loading config file: yaml: line 30: did not find expected '-' indicator`

I think should have the second line indented like this (my VS Code editor auto-corrected it to this);
```
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/*.log
```

I think this change would make it match this more general doc;
https://www.elastic.co/guide/en/beats/libbeat/7.8/config-file-format.html

For confirmed bugs, please report:
- Version: 7.9.0
- Operating System: docker
- Discuss Forum URL:
- Steps to Reproduce:
