### ISSUE TITLE
Filebeat 5.0.0-alpha4 losing messages

### ISSUE THREAD

**Issue by tsg** [elastic/beats#2041]
On test done by @robin13 it seems that filebeat can drop lines when it's stopped with ^C during processing. The test does:

* a setup with filebeat and logstash with minimal configs (see below)
* start filebeat to read a file with 10k lines
* in the middle of filebeat processing, kill it with ^C
* restart filebeat, wait for it to process the whole file
* look at the output written by LS, sometimes it has less then 10k lines

Config files:

```
filebeat:
  prospectors:
    -
      paths:
        - /home/rclarke/elastic/cases/90209/source.json
      input_type: log

output:
  logstash:
    hosts: ["localhost:17046"]
```

and LS:

```
input {
    beats {
        port => 17046
        codec => json
    }
}


output {
    file {
        codec => json_lines
        path => "/home/rclarke/elastic/cases/90209/output.json"
    }
    stdout {
        codec => dots
    }
}
```
