### ISSUE TITLE
[Metricbeat] Metricbeat.autodiscover: Jolokia module  does not work

### ISSUE THREAD

**Issue by ZMMWMY** [elastic/beats#20438]
I tried to use jolokia to get the JVM information, and I succeeded, but it was all on a stand-alone basis. When I tried to use auto discovery mode to get the result, I didn't get the expected result
I tried to ask questions in the forum, but no one answered
This is my configuration file, please help me look at this problem, thank you very much
```
logging.level: debug

# To enable hints based autodiscover uncomment this:
metricbeat.autodiscover:
  providers:
    - type: jolokia
      templates:
      - config:
        - module: jolokia
          metricsets: ["jmx"]
          hosts: ["http://${data.host}:8080/jolokia"]
          namespace: sxc
          period: 10s
          jmx.mappings:
           - mbean: "java.lang:type=Memory"
             attributes:
               - attr: HeapMemoryUsage
                 field: memory.heap_usage
               - attr: NonHeapMemoryUsage
                 field: memory.non_heap_usage
          

processors:
  - add_cloud_metadata:
  - add_host_metadata:
  - add_kubernetes_metadata:
      host: ${NODE_NAME}

output.elasticsearch:
  hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
  username: ${ELASTICSEARCH_USERNAME}
  password: ${ELASTICSEARCH_PASSWORD}
```
