### ISSUE TITLE
Auditbeat `file.path` field does not contain the absolute paths.

### ISSUE THREAD

**Issue by simmol1997** [elastic/beats#20451]
#### Environment
- OS: The output of `uname -a`:
`Linux blueprint-energetic-bear 5.3.0-1031-gcp #33~18.04.1-Ubuntu SMP Fri Jul 3 10:21:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Output of `auditbeat version`: `auditbeat version 7.8.1 (amd64), libbeat 7.8.1 [94f7632be5d56a7928595da79f4b829ffe123744 built 2020-07-21 15:07:37 +0000 UTC]`
However, the problem is also found for Auditbeat version 7.5.1 which is the only other version I have tested.

#### Steps to Reproduce
  1. Add an auditbeat rule that watches for `openat` syscalls in /etc/auditbeat/audit.rules.d/blueprint-energetic-bear.conf. E.g. `-a exit,always -F arch=b64 -S openat -F dir=/root -F euid=root -k flag-capture`
  2. Add a file to the `root` directory. E.g. `touch flag{abc}`
  3. Use Linux `find` command: `find / -name flag{* 2>&1 | grep flag`.
  4. Query Elasticsearch for the document using e.g. the `tags` field.

My Auditbeat config file is as follows:
```
---
auditbeat:
  modules:
  - audit_rule_files:
    - /etc/auditbeat/audit.rules.d/*.conf
    module: auditd
http:
  enabled: true
  host: 10.0.18.128
  port: '5067'
logging:
  level: warning
  metrics:
    enabled: false
  to_eventlog: false
  to_files: false
  to_stderr: true
  to_syslog: false
monitoring:
  cluster_uuid: ZK15biAITP-jB5O8Y5XuQQ
  enabled: false
name: blueprint-energetic-bear-auditbeat
output:
  elasticsearch:
    enabled: true
    hosts:
    - https://35.206.159.154:9200
    - https://35.210.163.90:9200
    - https://35.210.170.219:9200
    password: ${OUTPUT_PASS}
    ssl:
      certificate: /etc/auditbeat/certs//beats.crt
      certificate_authorities: /etc/auditbeat/certs//ca.crt
      enabled: true
      key: /etc/auditbeat/certs//beats.p1
      key_passphrase: ${OUTPUT_CERT_KEY_PASSPHRASE}
      verification_mode: none
    username: ${OUTPUT_USER}
path:
  config: /etc/auditbeat
  data: /var/lib/auditbeat
  home: /usr/share/auditbeat
  logs: /var/log/auditbeat
processors:
- add_id: null
- add_locale: null
- community_id: null
- add_process_metadata:
    match_pids:
    - system.process.ppid
    overwrite_keys: true
    restricted_fields: true
- add_fields:
    fields:
      world: blueprint
    target: ''
- add_observer_metadata:
    geo:
      name: blueprint
setup:
  ilm:
    check_exists: false
    enabled: true
    overwrite: false
    pattern: '{now/d}-000001'
    rollover_alias: auditbeat-%{[agent.version]}
  template:
    enabled: false
    settings:
      index:
        number_of_shards: 1
```

#### Expected Behavior

Only the opening of files within the `/root` directory should be captured and pushed to elasticsearch by the auditbeat rules in place. Also, the `file.path` field should contain the absolute path to the file that has been opened.

#### Current Behavior

There are many documents that are pushed that contain strange `file.path` field. Below is an example document which was pushed by Auditbeat. It references the path `.local` and has the `/tmp` directory as a working directory. However, there is no file in the `/tmp` directory named `.local` and it certainly is not an absolute path.
```
      {
        "_index" : "auditbeat-7.8.1-2020.07.29-000001",
        "_type" : "_doc",
        "_id" : "jcKjvnMBFCvzJdFmeqcY",
        "_score" : 0.0,
        "_source" : {
          "@timestamp" : "2020-08-05T12:40:51.474Z",
          "tags" : [
            "cuiteur",
            "73cb43",
            "flag-captured"
          ],
          "auditd" : {
            "result" : "success",
            "data" : {
              "exit" : "5",
              "a1" : "55cd05f1d338",
              "a0" : "7",
              "syscall" : "openat",
              "a2" : "30900",
              "arch" : "x86_64",
              "a3" : "0",
              "tty" : "pts0"
            },
            "session" : "7677",
            "summary" : {
              "object" : {
                "type" : "file",
                "primary" : ".local"
              },
              "how" : "/usr/bin/find",
              "actor" : {
                "primary" : "printer",
                "secondary" : "root"
              }
            },
            "paths" : [
              {
                "cap_frootid" : "0",
                "dev" : "08:01",
                "name" : ".local",
                "cap_fver" : "0",
                "mode" : "040755",
                "ogid" : "0",
                "ouid" : "0",
                "rdev" : "00:00",
                "nametype" : "NORMAL",
                "cap_fe" : "0",
                "cap_fi" : "0",
                "cap_fp" : "0",
                "inode" : "785303",
                "item" : "0"
              }
            ],
            "message_type" : "syscall",
            "sequence" : 706293
          },
          "ecs" : {
            "version" : "1.5.0"
          },
          "event" : {
            "category" : "audit-rule",
            "action" : "opened-file",
            "outcome" : "success",
            "module" : "auditd",
            "timezone" : "+00:00"
          },
          "user" : {
            "name" : "root",
            "filesystem" : {
              "group" : {
                "id" : "0",
                "name" : "root"
              },
              "name" : "root",
              "id" : "0"
            },
            "effective" : {
              "group" : {
                "name" : "root",
                "id" : "0"
              },
              "id" : "0",
              "name" : "root"
            },
            "saved" : {
              "id" : "0",
              "name" : "root",
              "group" : {
                "id" : "0",
                "name" : "root"
              }
            },
            "audit" : {
              "id" : "1001",
              "name" : "printer"
            },
            "group" : {
              "id" : "0",
              "name" : "root"
            },
            "id" : "0"
          },
          "file" : {
            "group" : "root",
            "path" : ".local",
            "device" : "00:00",
            "inode" : "785303",
            "mode" : "0755",
            "uid" : "0",
            "gid" : "0",
            "owner" : "root"
          },
          "agent" : {
            "name" : "blueprint-energetic-bear-auditbeat",
            "type" : "auditbeat",
            "version" : "7.8.1",
            "hostname" : "blueprint-energetic-bear",
            "ephemeral_id" : "c511b79d-e610-4e11-b9a4-470ccdf9f8eb",
            "id" : "3966fa21-f393-5aee-80b0-914283ba53c6"
          },
          "process" : {
            "name" : "bash",
            "executable" : "/bin/bash",
            "pid" : 6145,
            "ppid" : 6143,
            "start_time" : "2020-08-05T12:36:22.470Z",
            "working_directory" : "/tmp",
            "title" : "bash",
            "args" : [
              "bash"
            ],
            "env" : { }
          },
          "service" : {
            "type" : "auditd"
          },
          "host" : {
            "name" : "blueprint-energetic-bear-auditbeat"
          },
          "observer" : {
            "hostname" : "blueprint-energetic-bear",
            "ip" : [
              "10.0.18.128",
              "10.0.2.128",
              "fe80::4001:aff:fe00:1280"
            ],
            "mac" : [
              "42:01:0a:00:12:80"
            ],
            "geo" : {
              "name" : "blueprint"
            }
          },
          "container" : {
            "id" : ""
          },
          "world" : "blueprint"
        }
      }
```
