### ISSUE TITLE
Converting types in FunctionBeat's tokenizer results in mangled field

### ISSUE THREAD

**Issue by dominikborkowski** [elastic/beats#20473]
According to https://www.elastic.co/guide/en/beats/functionbeat/master/dissect.html we should be able to convert datatypes by using the tokenizer pattern. Instead of a converted value we get a key/field with `|datatype` in its name. Using single or double quotes doesn't seem to have any effect either. 

Example: 

```
      - dissect:
          when:
            contains:
              message: " - Executed "
          tokenizer: '%{fields.event_created} %{fields.log_level}: %{fields.event_id} - %{trace.id} - Executed %{fields.handler} [%{fields.handler_execution_time_in_ms|integer}ms]'
          field: "message"
          target_prefix: ""
```

Or 

```
      - dissect:
          when:
            contains:
              message: " - Response - "
          tokenizer: '%{fields.event_created} %{fields.log_level}: %{fields.event_id} - %{trace.id} - Response - %{user.id}- %{http.response.status_code|integer} - %{http.response.body.content}'
          field: "message"
          target_prefix: ""
```

And here are our results:

```
    "fields": {
      "group": "XXX",
      "handler": "XXX",
      "handler_execution_time_in_ms|integer": "0",
      "event_created": "2020-08-06T12:50:43.031Z",
      "log_level": "Trace",
      "event_id": "f4feed2d-d457-4a90-bd78-3ca94fb70307"
    },
```
```
    "http": {
      "response": {
        "status_code|integer": "204",
        "body": {
          "content": "\n"
        }
      }
    },
```

Is this an issue of syntax, or a bug? We're using FunctionBeat 7.8.1. 

Any hints would be greatly appreciated!
