### ISSUE TITLE
[Auditbeat v6.8.10] / Windows / File intergrity module / kafka output / files' attributes info not sent

### ISSUE THREAD

**Issue by komajaro** [elastic/beats#20495]
Hello everyone

I think auditbeat has a bug and is not sending all of the information it should (to kafka in this example).

- Auditbeat version: 6.8.10
- Operating System: Windows Server 2012 R2
- Discuss Forum URL: https://discuss.elastic.co/t/auditbeat-6-8-10-windows-file-intergrity-kafka-output-changing-file-attrubutes-info/240166

- Steps to Reproduce:
  1. install and configure auditbeat
  2. configure properly and enable debug
  3. change proper file attributes (add ReadOnly for example)
  4. verify logs (file mode changes in local debug logs, but information about changed file attribute isn't sent further to kafka, only an event informing that an attribute has been changed but without any details)

event sent to kafka (file mode missing):
`{"@timestamp":"2020-07-07T12:57:46.722Z","@metadata":{"beat":"auditbeat","type":"doc","version":"6.8.10","topic":"topic-name-json"},"tags":["auditbeat"],"fields":{"type":"auditbeat","env":"dev"},"beat":{"name":"AuditBeat","hostname":"hostname","version":"6.8.10"},"host":{"name":"AuditBeat"},"hash":{"sha256":"asd"},"file":{"path":"C:\\Program` `Files\\AuditBeat_6810\\D1\\F1.txt","inode":"15762598696055111","mtime":"2020-06-26T12:44:04.005Z","ctime":"2020-06-26T12:44:04.005Z","size":0,"type":"file","uid":"S-1-5-21-631068067-1468795310-178543940-699263","owner":"user"},"event":{"action":["updated"],"module":"file_integrity","dataset":"file"}}`

local auditbeat logs (file mode present):
`2020-07-07T15:07:04.985+0200	DEBUG	[file_integrity]	file_integrity/metricset.go:224	File changed since it was last seen	{"file_path": "C:\\Program Files\AuditBeat_6810\\D1\F1.txt", "took": 0, "event": {"old": {"timestamp":"2020-07-07T13:06:55.0034521Z","path":"C:\\Program Files\\AuditBeat_6810\\D1\\F1.txt","info":{"inode":15762598696055111,"uid":0,"gid":0,"sid":"S-1-5-21-631068067-1468795310-178543940-699263","owner":"","group":"","size":0,"mtime":"2020-06-26T12:44:04.0052507Z","ctime":"2020-06-26T12:44:04.0052507Z","type":"file","mode":438,"setuid":false,"setgid":false,"origin":null},"source":"scan","action":"none","hash":{"sha256":"asd"}}, "new": {"timestamp":"2020-07-07T13:07:04.9850248Z","path":"C:\\Program Files\\AuditBeat_6810\\D1\\F1.txt","info":{"inode":15762598696055111,"uid":0,"gid":0,"sid":"S-1-5-21-631068067-1468795310-178543940-699263","owner":"user","group":"","size":0,"mtime":"2020-06-26T12:44:04.0052507Z","ctime":"2020-06-26T12:44:04.0052507Z","type":"file","mode":292,"setuid":false,"setgid":false,"origin":null},"source":"fsnotify","action":"updated","hash":{"sha256":"asd"}}}}`

CONFIG FILE:
```
auditbeat.modules:
- module: file_integrity
  enabled: true
  paths:
  - C:/Program Files/AuditBeat/D1

  scan_at_start: true
  scan_rate_per_sec: 50 MiB
  max_file_size: 1000 MiB
  hash_types: [sha256]
  recursive: true

name: AuditBeat
tags: ["auditbeat"]
fields:
  type: auditbeat
  env: dev

output.kafka:
  hosts:
    ["host1:9092", "host2:9092",  "host3:9092",  "host4:9092"]

  topic: topic-name
  partition.round_robin:
    reachable_only: true

  required_acks: 1
  compression: gzip
  max_message_bytes: 10000000

logging.level: debug
logging.selectors: ["*"]
```
