### ISSUE TITLE
Possible memory leak? [sustained high memory consumption despite no traffic]

### ISSUE THREAD

**Issue by rshriram** [elastic/beats#205]
When running packebeat, memory usage is extremely high and does not seem to be going down. Normally, the Go garbage collector would have kicked in after 2 minutes, but when monitoring memory consumption, memory continues to remain high for 5+ minutes.

For example, when runnning packetbeat on a server with nginx+haproxy, the load driver fetching a 32kb static file from the server constantly, packetbeat's resident memory size grows quickly to 1.3GB (and more). Even after the load driver is killed, the memory consumption remains the same, showing no signs of going down (waited 6 minutes). All the related log entries from packetbeat reach the redis server, FYI.

This is with go version 1.4.2 linux/amd64, vanilla packetbeat and no other tuning of Go.
Any idea why this is happening? This high memory consumption makes it impossible to keep it deployed on a machine in unmonitored fashion. 

Load driver is from ha-proxy website (http://1wt.eu/tools/inject/inject-64)

command: inject-64 -u 100 -R -d 30 -G 10.11.0.4:8000/file_32k_1.txt

**Comment by tsg** [comment]
Hi, can you try running Packetbeat like this to generate a memory profile:

     sudo ./packetbeat -e -memprofile out.prof

Let it running for a while and then kill it. Note that after sending the SIGINT/SIGTERM signal, Packetbeat will sleep for ~30 seconds to let all active streams expire first. After that, it should create the `out.prof` file. Please either post it somewhere so we can have a look or you can have a look yourself with `go tool pprof`.

Thanks!

**Comment by rshriram** [comment]
Here is the memory profile. http://pastebin.com/FdTgC5TY
Please let me know if you need more information.

**Comment by tsg** [comment]
@rshriram Yes, how did you install packetbeat? Did you compile it yourself? If yes, from which branch? If not, which package did you use? It's because I need the matching binary to make sense of the profile file.

**Comment by tsg** [comment]
Also, can you post your packetbeat configuration, please?

**Comment by rshriram** [comment]
I compiled it from source, by pulling the elastic/packetbeat repo from github.com. I used the standard make command to build the binary.

system: ubuntu 14.04.2
kernel: 3.16.0-30-generic
libpcap0.8 (v 1.5.3-2) - installed directly from ubuntu packages. Although this shouldn't matter since I was using AF_PACKET

I ran the command in two ways (same result): sudo taskset -c 0 ./packetbeat -c ./packetbeat.yml
and once without taskset.

```
branch: master
commit 38aa9610a5163a67e18521d5c3a5bd2dbebb225e
Author: Tudor Golubenco <tudor@packetbeat.com>
Date:   Thu Aug 20 11:52:43 2015 +0200

    gofmt
```

My packetbeat.yml config file:
```
agent:
 name:
interfaces:
 ##This is a 10Gbps interface.                         
 device: p1p1
 type: af_packet
 buffer_size_mb: 256
 filter: "tcp"
 snaplen: 1500

protocols:
  http:
    ports: [8000]
  mysql:
  pgsql:
  redis:
  thrift:
  mongodb:
output:
  redis:
    enabled: true
    host: 10.12.0.5
    port: 6380
    save_topology: false
```
