### ISSUE TITLE
Docs reference a setting incorrectly

### ISSUE THREAD

**Issue by nerophon** [elastic/beats#20637]
Version: 7.8.1

The following docs have an incorrect reference:
https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html
https://www.elastic.co/guide/en/beats/filebeat/7.8/configuring-ingest-node.html

They show:
```
output:
  pipeline:
```

Whereas they should show:
```
output:
  parameters.pipeline:
```

If the incorrect reference is used, it results in unexpected behaviour.

**Comment by bmorelli25** [comment]
Related to https://github.com/elastic/beats/issues/20342 and https://discuss.elastic.co/t/filebeat-output-elasticsearch-pipeline-not-working/240167.

**Comment by dedemorton** [comment]
This looks like a product bug, not a documentation bug. The documented configuration works correctly on Metricbeat. Since the output settings for all the beats are essentially the same, I would expect them to use the same config syntax.

**Comment by kvch** [comment]
@dedemorton is correct, it is a product problem if the configuration snippets in the reference doc pages do not work in this case.

@nerophon What is the exact configuration which leads to issues? None of the configurations you have shared is supposed to work with Beats.

The supported configurations are the following:
```yaml
output.elasticsearch:
  hosts: ["your-host:9200"]
  pipeline: your-pipeline
```

```yaml
output.elasticsearch:
  hosts: ["your-host:9200"]
  pipelines:
    - pipeline: your-pipeline-1
      when.contains:
        message: something
    - pipeline: your-pipeline-2
      when.contains:
        message: anything
```
