### ISSUE TITLE
[FileBeat] [ Kubernetes ] [ Windows ]: kubernetes_metadata does not work

### ISSUE THREAD

**Issue by iusergii** [elastic/beats#20708]
Hi Team, 

I'm evaluating moving our Windows workloads to Kubernetes and would like to use filebeat for logs shipment.  I've created DaemonSet where I mounted hostPathes:
 - /var/log
 - /ProgramData/docker/containers

My filebeat configuration looks like:

```yaml
filebeat.autodiscover:
  providers:
  - type: kubernetes
    hints:
      enabled: true
      default_config:
        type: container
        paths:
          - "C:\\var\\log\\containers\\*"
output.console:
  pretty: true
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_kubernetes_metadata: ~
logging:
  level: debug
```
I can confirm that I can read from logs file from container context, but `add_kubernetes_metadata` processor is failing with following errors:

```bash
2020-08-19T13:10:37.084Z  DEBUG [input] log/input.go:494  Start harvester for new file: C:\var\log\containers\open-app-8fd9f9fcb-htbs8_default_open-app-09c468ee2146e47ec601e37dccbbabca246ee52dff196b2e573965225149b3ea.log
2020-08-19T13:10:37.138Z  ERROR [kubernetes]  add_kubernetes_metadata/matchers.go:91  Error extracting container id - source value does not contain matcher's logs_path 'C:\ProgramData\Docker\containers\'.
```

For confirmed bugs, please report:
- Version: `filebeat version 7.8.1 (amd64), libbeat 7.8.1 [94f7632be5d56a7928595da79f4b829ffe123744 built 2020-07-21 15:12:43 +0000 UTC]`
- Operating System:  `Windows Server 2019 10.0.17763 N/A Build 17763`
- Discuss Forum URL:  https://discuss.elastic.co/t/kubernetes-metadata-does-not-work-on-kubernetes-windows/245617
- Steps to Reproduce: 

1. My Dockerfile:
```yaml
FROM mcr.microsoft.com/windows/servercore:ltsc2019
COPY filebeat-7.9.0-windows-x86_64 /app
ENTRYPOINT ["c:\\app\\filebeat.exe", "-c", "c:\\etc\\filebeat\\filebeat.yml", "-e"]
```
2. Kubernetes objects:
```yaml
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging
apiVersion: v1
data:
  filebeat.yml: |
    filebeat.autodiscover:
      providers:
      - type: kubernetes
        hints:
          enabled: true
          default_config:
            type: container
            paths:
              - "C:\\var\\log\\containers\\*"
    output.console:
      pretty: true
    processors:
      - add_host_metadata: ~
      - add_cloud_metadata: ~
      - add_kubernetes_metadata: ~
    logging:
      level: debug
--- 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: logging
--- 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: filebeat
  namespace: logging
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - list
  - watch
--- 
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: filebeat
  namespace: logging
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: logging
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: filebeat
  name: filebeat
  namespace: logging
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
          type: Directory
      - name: programdatadockercontainers
        hostPath:
          path: /ProgramData/docker/containers
          type: Directory
      - name: filebeat-config
        configMap:
          name: filebeat-config   
      containers:
      - name: filebeat
        image: isergii/windows-filebeat-test:7.9.0
        volumeMounts:
        - mountPath: /var/log
          name: varlog
        - mountPath: /ProgramData/docker/containers
          name: programdatadockercontainers
        - mountPath: /etc/filebeat
          name: filebeat-config 
      nodeSelector:
        kubernetes.io/os: windows
```
