### ISSUE TITLE
[Filebeat] "add_kubernetes_metadata" causes KubeAPIErrorsHigh alert

### ISSUE THREAD

**Issue by yogeek** [elastic/beats#20723]
Hi,

2 days ago, after upgrading filebeat (7.5.0 -> 7.8.1) on our K8S cluster we began to regularly receive the "KubeAPIErrorsHigh" alert (definition of the alert [here](https://github.com/kubernetes-monitoring/kubernetes-mixin/blob/release-0.4/alerts/kube_apiserver.libsonnet#L75-L89)).

To try to find the cause, we looked at the API server logs and saw the following error messages on `kube-apiserver` pods : 

```
$ stern kube-apiserver -n kube-system | grep -v "TLS handshake error" | grep -i error

kube-apiserver-ip-10-XX-XX-XX.eu-central-1.compute.internal kube-apiserver I0820 17:13:14.022460       1 log.go:172] http2: server: error reading preface from client 10.XX-XX-XX:55385: read tcp 10.XX-XX-XX:6443->10.XX-XX-XX:55385: read: connection reset by peer
kube-apiserver-ip-10-XX-XX-XX.eu-central-1.compute.internal kube-apiserver E0820 17:14:23.539314       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
kube-apiserver-ip-10-XX-XX-XX.eu-central-1.compute.internal kube-apiserver E0820 17:14:23.895988       1 status.go:71] apiserver received an error that is not an metav1.Status: &errors.errorString{s:"context canceled"}
```

After looking at our components one by one to find the culprit, we found that it was our filebeat 7.8.1 daemonset that was reponsible of these errors.
And then, after many config tests on filebeat config, we concluded that the errors disappeared if we remove the `add_kubernetes_metadata:` field from the `filebeat.yml` config.

And our API server grafana dashboard clearly showed the disappearance of the 5xx errors after we removed this option :

![Capture](https://user-images.githubusercontent.com/9500406/90824173-434c4600-e337-11ea-9234-96c04fdb9ecd.PNG)

Here is the config file we used in our chart deployment :
```
---
filebeatConfig:
  filebeat.yml: |
    logging.metrics.enabled: false
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          templates:
            
            ## Metadata namespace
            - condition.contains:
                kubernetes.namespace: metadata
              config:
                - type: container
                  paths:
                    - /var/lib/docker/containers/${data.kubernetes.container.id}/*.log
                  exclude_lines: ["^\\s+[\\-`('.|_]"]  # drop asciiart lines

    processors:
      # Add config here to drop events
      - add_cloud_metadata:
	
      # ******************************** THIS LINE CAUSE API SERVER ERROR
      - add_kubernetes_metadata:

      # Drop all events
      #- drop_event:
      #    when.has_fields: ["kubernetes.namespace"]
      # Drop filebeat events
      - drop_event:
          when.equals:
            kubernetes.container.name: "filebeat"
  
    output.logstash:
      hosts: ["logstash.url"]
```

- Filebeat Version: 7.8.1 and 7.9.0
- Kubernetes Version : 1.17.6
- Operating System: Ubuntu 18.04
- Discuss Forum URL: https://discuss.elastic.co/t/add-kubernetes-metadata-causes-kubeapierrorshigh-alert/245806

*Additionnal info : we did not have the problem with our previous 7.5.0 filebeat version. The errors appeared after the 7.5.0 => 7.8.1 upgrade.*

*(maybe related question : is there a compatibility matrix between filebeat versions and kubernetes versions please ?)*

**Comment by yogeek** [comment]
Any news on that please ?

**Comment by ChrsMark** [comment]
Hi!

Maybe it's because Filebeat is trying, and more specifically the `add_kuberntes_metadata` processor, is trying to reach Kubernetes api without success and then it keeps retrying. 
Could you check the logs and look for messages that indicate anything related to `add_kubernetes_metadata` processor initialisation?
Also you may need to add the `host` parameter to the configuration as it is proposed at https://github.com/elastic/beats/blob/ecb2a248a61579e990a16bde21cd6726dc0f3a7a/deploy/kubernetes/filebeat-kubernetes.yaml#L17.

**Comment by yogeek** [comment]
@ChrsMark In the example you provided, the `${NODE_NAME}` is in the provider directly included under `filebeat.inputs`. 
In my case (autodiscover), your example has the `${NODE_NAME}` under the `type: kubernetes` provider only... 
Should I set it both under the `type: kubernetes` autodiscover provider and under the `add_kubernetes_metadata` processor ?

```
filebeatConfig:
  filebeat.yml: |
    logging.metrics.enabled: false
    filebeat.autodiscover:
      providers:
        - type: kubernetes
		  host: ${NODE_NAME} ## <------------- only here ... ?
          templates:
            [...]

    processors:
      # Add config here to drop events
      - add_cloud_metadata:
	
      # ******************************** THIS LINE CAUSE API SERVER ERROR
      - add_kubernetes_metadata:
		  host: ${NODE_NAME} ## <------------- or here also ... ?
```
