### ISSUE TITLE
tomcat module doesn't allow to set mbean (or mbean domain)

### ISSUE THREAD

**Issue by dagwieers** [elastic/beats#20773]
@jsoriano We are looking into why the **tomcat** module is not working for us, and the issue is that the domain should be `Tomcat` instead of `Catalina`. I tried to override the mbean from its configuration file _tomcat.yml_, however it doesn't seem possible to set e.g. `cache.mbean` or `requests.mbean` ourselves.

_Originally posted by @dagwieers in https://github.com/elastic/beats/pull/13491_

**Comment by dagwieers** [comment]
As a workaround, the following configuration as e.g. `tomcat.yml` provides a complete drop-in replacement for the **tomcat** module using the **jolokia* module.

```yaml
# Ansible managed
# Module: jolokia
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.9/metricbeat-module-jolokia.html

- module: jolokia
  period: 10s
  metricsets:
  - jmx
  hosts:
  - localhost:8778
  path: /jolokia/?ignoreErrors=true&canonicalNaming=false

  namespace: tomcat
  jmx.mappings:
  # Reimplementation of tomcat/cache
  - mbean: Tomcat:context=*,host=*,name=Cache,type=WebResourceRoot
    attributes:
    - attr: hitCount
      field: cache.hit.total
    - attr: size
      field: cache.size.total.kb
    - attr: maxSize
      field: cache.size.max.kb
    - attr: lookupCount
      field: cache.lookup.total
    - attr: ttl
      field: cache.ttl.ms

  # Reimplementation of tomcat/memory
  - mbean: java.lang:type=Memory
    attributes:
    - attr: HeapMemoryUsage
      field: memory.heap.usage
    - attr: NonHeapMemoryUsage
      field: memory.other.usage

  # Reimplementation of tomcat/requests
  - mbean: Tomcat:name=*,type=GlobalRequestProcessor
    attributes:
    - attr: requestCount
      field: requests.total
    - attr: bytesReceived
      field: requests.bytes.received
    - attr: bytesSent
      field: requests.bytes.sent
    - attr: processingTime
      field: requests.processing.ms
    - attr: errorCount
      field: requests.errors.total

  # Reimplementation of tomcat/threading
  - mbean: Tomcat:name=*,type=ThreadPool
    attributes:
    - attr: currentThreadsBusy
      field: threading.busy
    - attr: maxThreads
      field: threading.max
    - attr: currentThreadCount
      field: threading.current
    - attr: keepAliveCount
      field: threading.keep_alive.total
    - attr: keepAliveTimeout
      field: threading.keep_alive.timeout.ms

  - mbean: java.lang:type=Threading
    attributes:
    - attr: TotalStartedThreadCount
      field: threading.started.total
    - attr: CurrentThreadUserTime
      field: threading.user.time.ms
    - attr: CurrentThreadCpuTime
      field: threading.cpu.time.ms
    - attr: ThreadCount
      field: threading.total
    - attr: PeakThreadCount
      field: threading.peak
```
