### ISSUE TITLE
Custom Metric not Adding Host.geo.country_name

### ISSUE THREAD

**Issue by mhassaanmughal** [elastic/beats#20796]
```
processors:
  - add_host_metadata:
       geo:
          name: server-1
          country_name: PK
          country_iso_code: PK
          city_name: Karachi
```

after providing add_host_metadata as per document  still country_name is not adding below is output of beat 

`{
	"@timestamp": "2020-08-24T10:15:47.394Z",
	"@metadata": {
		"beat": "strongswan",
		"type": "_doc",
		"version": "8.0.0"
	},
	"strongswan": {
		"strongswan": {
			"counter": 1
		}
	},
	"event": {
		"dataset": "strongswan.strongswan"
	},
	"host": {
		"hostname": "inspiron-15-3567",
		"geo": {
			"country_iso_code": "PK",
			"city_name": "Karachi",
			"name": "server-1"
		},
		"platform": "ubuntu"
	}
}`

**Comment by jsoriano** [comment]
Hi @mhassaanmughal,

You are right, this field should be added, I have opened a PR to fix this issue https://github.com/elastic/beats/pull/20811.
As a workaround on the meantime, you can manually add this field with the `add_fields` processor:
```
processors:
  - add_host_metadata:
      geo:
        name: server-1
        country_name: PK
        country_iso_code: PK
        city_name: Karachi
  - add_fields:
      target: geo
      fields:
        geo.country_name: PK
```

Thanks for reporting!
