### ISSUE TITLE
docker compose cannot obtain the cluster uuid for beats monitoring

### ISSUE THREAD

**Issue by 111andre111** [elastic/beats#20803]
I have played a bit around with docker and monitoring:

```
version: '2.2'
services:
  elasticsearch:
    restart: unless-stopped
    image: elasticsearch:${VERSION}
    environment:
      - discovery.type=single-node
      - cluster.name=${COMPOSE_PROJECT_NAME}
      - bootstrap.memory_lock=true
      - xpack.monitoring.collection.enabled=true
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - xpack.security.enabled=true
      - xpack.ml.enabled=false
      - "ES_JAVA_OPTS=-Xms${ELASTIC_HEAPSIZE} -Xmx${ELASTIC_HEAPSIZE}"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    labels:
      co.elastic.logs/module: "elasticsearch"
      project.env: "demo"
    healthcheck:
      test: curl -s http://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
  provisioner:
    image: elasticsearch:${VERSION}
    depends_on: {"elasticsearch": {"condition": "service_healthy"}}
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "${ELASTIC_PASSWORD}"
  kibana:
    restart: unless-stopped
    depends_on: {"elasticsearch": {"condition": "service_healthy"}}
    image: kibana:${VERSION}
    ports:
    - 5601:5601
    environment:
      SERVER_NAME: ${COMPOSE_PROJECT_NAME}
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: "kibana"
      ELASTICSEARCH_PASSWORD: "${ELASTIC_PASSWORD}"
      STATUS_ALLOWANONYMOUS: "true"
      TELEMETRY_ENABLED: "false" # causes optimize run
      XPACK_SECURITY_ENCRYPTIONKEY: "wB4AzFe5RxZa0zuLnmorvvBYmVnKmaAdNsakMqlj-${COMPOSE_PROJECT_NAME}"
      XPACK_LICENSE_MANAGEMENT_ENABLED: "false"
      XPACK_ML_ENABLED: "false" # causes optimize run
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 332fd23af367a8d76a7293ad73827f37
    labels:
      co.elastic.logs/module: "elasticsearch"
      project.env: "demo"
    healthcheck:
      test: curl -sIf http://localhost:5601 >/dev/null
      interval: 30s
      timeout: 10s
      retries: 5
  filebeat:
    restart: unless-stopped
    depends_on: {"elasticsearch": {"condition": "service_healthy"}}
    image: elastic/filebeat:${VERSION}
    environment:
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: "elastic"
      ELASTICSEARCH_PASSWORD: "${ELASTIC_PASSWORD}"
    command: "--strict.perms=false -v -e -d autodiscover,docker"
    user: root
    labels:
      co.elastic.logs/module: "elasticsearch"
      project.env: "demo"
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  esdata:
    labels:
      project.name: "${COMPOSE_PROJECT_NAME}"
      project.env: "demo"
```

And then let's bring it up:
`COMPOSE_PROJECT_NAME=test1 ELASTIC_HEAPSIZE=1024m VERSION=7.9.0 ELASTIC_PASSWORD=changeme docker-compose up`

Normally in the case of internal monitoring I would need to set setting `monitoring.cluster_uuid`
https://www.elastic.co/guide/en/beats/filebeat/current/monitoring-internal-collection.html

At the moment this is not possible with this particular docker compose.

It would be possible using the workaround to start all services, then stop filebeat, obtain the cluster uuid from elasticsearch, inject the environment variable `MONITOR_CLUSTER_UUID` and start filebeat again.

But this doesn't seem an easy way, and I assume there would be other edge cases possible too, where a certain API is needed as a dependency of another docker service, so would be good if we could have  a better approach for that.
