### ISSUE TITLE
how to rename field like this?

### ISSUE THREAD

**Issue by xizhimen** [elastic/beats#20814]
Background:
      packetbeat:6.8
      http protocol

Demands：
    rename http.request.body to "http.request.body":
        from:{"http":{"request":{"body":"aaaa}}}
        to: {"http.request.body":"aaaa"}

try following (not effect):
```
    processors:
     - rename:
          fields:
            - from: "http.request.params"
              to: "http\.request\.params"

```
```
    processors:
     - rename:
          fields:
            - from: "http.request.params"
              to: "http\\.request\\.params"

```

can you give me same suggestion
