### ISSUE TITLE
[beats] Live reloading causes delay sending data based on reload.period if enabled

### ISSUE THREAD

**Issue by mark54g** [elastic/beats#20847]
Various beats seem to have an issue where `reload.enabled` being set to true will cause a delay that is roughly equal to the `reload.period`

Confirmed with master branch of metricbeat per @kaiyan-sheng

**Comment by PresGas** [comment]
@mark54g , @kaiyan-sheng . This is still a problem and I'm hoping this ticket gets reopened by a human.

**Comment by kaiyan-sheng** [comment]
Hi @PresGas, could you post with more info on this issue please? Thanks!!

**Comment by PresGas** [comment]
I opened a case that created this ticket. Details here:
https://support.elastic.co/cases/5004M00000eisAyQAI - Case #00601459
It is still impacting filebeat version 7.10.x and likely newer since this was auto closed without any human interaction.
Thanks for reopening!

**Comment by PresGas** [comment]
Please let me know if I can provide anything. The key bits for reproducing the issue is generally to have the filebeat.yml configed with this snippet:

```
filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 30m
```

And then you should see some delays either going to logstash/kibana or putting filebeat to debug mode and watching the logs there.
