### ISSUE TITLE
[Heartbeat] Unable to build kubernetes clientset: no Auth Provider found

### ISSUE THREAD

**Issue by ghost** [elastic/beats#20846]
We are using Kubernetes on Azure (AKS) with AAD integration and for some reason Heartbeat **7.9.0** chokes on my kubeconfig:

```
2020-08-28T15:13:42.452+0200	ERROR	instance/beat.go:951	Exiting: error in autodiscover provider settings: error setting up kubernetes autodiscover provider: unable to build kubernetes clientset: no Auth Provider found for name "azure
```

Kubeconfig:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: redacted
    server: redacted
  name: redacted
contexts:
- context:
    cluster: redacted
    namespace: default
    user: redacted
  name: redacted
current-context: redacted
kind: Config
preferences: {}
users:
- name: redacted
  user:
    auth-provider:
      config:
        access-token: redacted
        apiserver-id: redacted
        client-id: redacted
        config-mode: "1"
        environment: AzurePublicCloud
        expires-in: "redacted"
        expires-on: "redacted"
        refresh-token: redacted
      name: azure
```

Relevant heartbeat configuration:

```
heartbeat.autodiscover:
  providers:
    - type: kubernetes
      kube_config: /etc/heartbeat/.kube/config
      resource: pod
      scope: cluster
      node: aks-agentpool*
      hints.enabled: true
```
