### ISSUE TITLE
[Elastic Agent] The inspect subcommand doesn't seems to work.

### ISSUE THREAD

**Issue by ph** [elastic/beats#20876]
I have tested the following  configuration on master

```yaml
inputs:
  - id: cd8256b0-e86a-11ea-9199-e12923f35450
    name: synthetics-1
    type: synthetics/http
    use_output: default
    meta:
      package:
        name: synthetics
        version: 0.1.3
    data_stream:
      namespace: default
    streams:
      - name: fwae
        type: http
        data_stream:
          dataset: synthetics.monitor
          type: logs
        urls: feaw
        schedule: 10s
```

I wanted to see how the Elastic Agent was transforming that configuration so I've run the following command:

```
./elastic-agent inspect output -p Heartbeat
```

But I haven't seen any output?

**Comment by ph** [comment]
cc @andrewvc

**Comment by blakerouse** [comment]
I have tried adding `-o default` also to the command.

**Comment by michalpristas** [comment]
running 
```
$ ./elastic-agent inspect output
default
```
it shows we have one output called default

inspecting default:
```
$ ./elastic-agent inspect output -o default
[default] heartbeat:
inputs:
- data_stream:
    namespace: default
  id: cd8256b0-e86a-11ea-9199-e12923f35450
  meta:
    package:
      name: synthetics
      version: 0.1.3
  name: synthetics-1
  streams:
  - data_stream:
      dataset: synthetics.monitor
      type: logs
    name: fwae
    schedule: 10s
    type: http
    urls: feaw
  type: synthetics/http
  use_output: default
output:
  elasticsearch:
    hosts:
    - 127.0.0.1:9200
    password: changeme
    username: elastic

---
[default] FLEET_MONITORING:
output:
  elasticsearch:
    hosts:
    - 127.0.0.1:9200
    password: changeme
    type: elasticsearch
    username: elastic
programs:
- heartbeat
```

to heartbeat it looks like this
```
$ ./elastic-agent inspect output -o default -p heartbeat
[default] heartbeat:
inputs:
- data_stream:
    namespace: default
  id: cd8256b0-e86a-11ea-9199-e12923f35450
  meta:
    package:
      name: synthetics
      version: 0.1.3
  name: synthetics-1
  streams:
  - data_stream:
      dataset: synthetics.monitor
      type: logs
    name: fwae
    schedule: 10s
    type: http
    urls: feaw
  type: synthetics/http
  use_output: default
output:
  elasticsearch:
    hosts:
    - 127.0.0.1:9200
    password: changeme
    username: elastic

```

on the side note
my config looks like this:
```
outputs:
  default:
    type: elasticsearch
    hosts: [127.0.0.1:9200]
    username: elastic
    password: changeme

inputs:
  - id: cd8256b0-e86a-11ea-9199-e12923f35450
    name: synthetics-1
    type: synthetics/http
    use_output: default
    meta:
      package:
        name: synthetics
        version: 0.1.3
    data_stream:
      namespace: default
    streams:
      - name: fwae
        type: http
        data_stream:
          dataset: synthetics.monitor
          type: logs
        urls: feaw
        schedule: 10s
agent.logging.to_stderr: true

```

Agent cannot transform configuration without outputs.

@ph please let me know if you have troubles on latest master as well or it was not recognizing synthetics input at the time of raising issue
