### ISSUE TITLE
heartbeat: Error in executing monitor with a secret in json body in check.request.body

### ISSUE THREAD

**Issue by pawarrchetan** [elastic/beats#21035]
We encounter an error while executing the runner using heartbeat 7.9.1
The issue is while using a keystore secret as a value in the json body for `check.request.body`

```
2020-09-09T10:00:56.157Z	DEBUG	[reload]	cfgfile/list.go:63	Starting reload procedure, current runners: 15
2020-09-09T10:00:56.158Z	DEBUG	[reload]	cfgfile/list.go:81	Start list: 1, Stop list: 0
2020-09-09T10:00:56.158Z	ERROR	[reload]	cfgfile/list.go:95	Error creating runner from config: job err can not convert 'object' into 'string' accessing 'check.request.body' (source:'/etc/heartbeat/monitors.d/test-auth-staging-sls-epilot-io.yml')
```
We tried changing the monitor config to include the key name with and without quotes and double quotes, however the error still persists.

- Version: heartbeat 7.9.1
- Operating System: Amazon Linux 2
- Discuss Forum URL: https://discuss.elastic.co/t/heartbeat-use-json-with-secret-store-in-check-request-body/247869

- Steps to Reproduce: 
1. Create heartbeat keystore
2. Add a secret in with sensitive value in the keystore with key name - USER_PASSWORD
3. Use the secret key in the json body for check.request.body
4. Monitor configuration :
```
- type: http
  name: test-xyz-abc-io
  enabled: true
  schedule: '@every 1m'  # every 1 minute from start of beat
  hosts: ["https://xyz.abc.io/v1/uri"]
  ipv4: true
  ipv6: true
  mode: any
  check.request:
    method: POST
    headers:
      'Content-Type': 'application/json'
    body: "{"org_id": "0", "email": "user@gmail.com", "password": "${USER_PASSWORD}"}"
  check.response:
    status: 200
  fields:
    env: test
```
The endpoint which needs to be tested should accept json body with sensitive value.
