### ISSUE TITLE
Beats DNS processor examples are not ECS compliant

### ISSUE THREAD

**Issue by BenB196** [elastic/beats#21171]
The DNS processor provides the following two examples:

```
processors:
  - dns:
      type: reverse
      fields:
        source.ip: source.hostname
        destination.ip: destination.hostname
```

```
processors:
- dns:
    type: reverse
    action: append
    fields:
      server.ip: server.hostname
      client.ip: client.hostname
```

As per https://github.com/elastic/ecs/issues/166 server, client, source, and destination no longer have a ECS field hostname, instead it appears that domain should be used instead.

```
processors:
  - dns:
      type: reverse
      fields:
        source.ip: source.domain
        destination.ip: destination.domain
```

```
processors:
- dns:
    type: reverse
    action: append
    fields:
      server.ip: server.domain
      client.ip: client.domain
```

For confirmed bugs, please report:
- Version: 7.9
- Operating System: N/A
- Discuss Forum URL: N/A
- Steps to Reproduce: N/A
