### ISSUE TITLE
[Filebeat] Autodiscover enabling when Pods are already running in the cluster

### ISSUE THREAD

**Issue by thernstig** [elastic/beats#21293]
**Describe the enhancement:**
The documentation for autodiscover and the Kubernetes provider states (https://www.elastic.co/guide/en/beats/filebeat/7.x/configuration-autodiscover.html):

> The Kubernetes autodiscover provider watches for Kubernetes nodes, pods, services to start, update, and stop.

If the cluster is already up and running when updating the filebeat config to include autodiscover, the docs do not indicate that it will start checking the already running Pods. Either the documents needs to be updated to indicate this, or if that is not the case, this is a feature request to add such functionality for autodiscover.

Here is an example config I use that does not work (i.e. does not capture the logs of these pods) when adding this to an already running cluster:

```yaml
filebeat.autodiscover:
  providers:
  - type: kubernetes
    include_annotations: ["test"]
    templates:
      - condition:
          has_fields: ['kubernetes.annotations.test']
        config:
          - type: log
            paths:
              - "/var/log/containers/${data.kubernetes.pod.name}_*.log"
            tags: ["testing"]
            fields:
              test: ${data.kubernetes.annotations.test}
              pod_name: ${data.kubernetes.pod.name}
              namespace: ${data.kubernetes.namespace}
              container_name: ${data.kubernetes.container.name}
              container_id: ${data.kubernetes.container.id}
            fields_under_root: true
            symlinks: true
            json.add_error_key: true
            close_timeout: 5m
```

**Describe a specific use case for the enhancement or feature:**

Enabling autodiscover in an already running cluster.
