### ISSUE TITLE
Compute fingerprint from all fields

### ISSUE THREAD

**Issue by szandala** [elastic/beats#21335]
I would like to use `fingerprint` processor for Metricbeat and others later on.
Is there any way I could use wildcard to compute fingerprint from all fields?

I have tried something like this, but appears to not working.
```yaml
processors:
  - fingerprint:
      fields: ['.*']
```
