### ISSUE TITLE
Ingest pipeline is ignored in elasticsearch output

### ISSUE THREAD

**Issue by ramon-garcia** [elastic/beats#21548]
Hello,

Filebeat, being used to process syslog messages, is ignoring the configuration of the ingest pipeline

Here is a simple configuration

```
- type: udp
  enabled: true
  host: "0.0.0.0:514"


setup.template.enabled: false
setup.ilm.enabled: false

setup.dashboards.enabled: false

setup.kibana.enabled: false

output.elasticsearch:
     # Array of hosts to connect to.
     hosts: ["localhost:9200"]
     index: "ciscosyslog-%{+YYYY.MM}"
     pipeline: ciscosyslog
```

The pipeline is not used at all, as one can check inspecting the HTTP traffic between Filebeat and Elasticsearch.

The problem is workarounded using instead, in the output:
```
     parameters:
             pipeline: syslog
```

This has been tested with Filebeat 7.9.1 OSS under Linux
