### ISSUE TITLE
Filebeat runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by dosullivan** [elastic/beats#2163]
When running the alpha4 build of filebeat 5 with a fairly minimal configuration, I am running into what seems to be a bug. Filebeat is failing to start, and produces the following output:
```
panic: runtime error: slice bounds out of range

goroutine 31 [running]:
panic(0xa009c0, 0xc8200100b0)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/elastic/beats/filebeat/input/file.(*States).Cleanup(0xc8201c87c0, 0x4e94914f0000)
	/go/src/github.com/elastic/beats/filebeat/input/file/state.go:93 +0x487
github.com/elastic/beats/filebeat/prospector.(*ProspectorLog).Run(0xc820137960)
	/go/src/github.com/elastic/beats/filebeat/prospector/prospector_log.go:53 +0x8f
github.com/elastic/beats/filebeat/prospector.(*Prospector).Run(0xc82013edc0)
	/go/src/github.com/elastic/beats/filebeat/prospector/prospector.go:120 +0x1b9
github.com/elastic/beats/filebeat/crawler.(*Crawler).Start.func1(0xc820125130, 0x0, 0xc82013edc0)
	/go/src/github.com/elastic/beats/filebeat/crawler/crawler.go:71 +0x13a
created by github.com/elastic/beats/filebeat/crawler.(*Crawler).Start
	/go/src/github.com/elastic/beats/filebeat/crawler/crawler.go:72 +0x539
```

- Version: filebeat-5.0.0-alpha4
- Operating System: ubuntu 14.04.4 LTS
- Steps to Reproduce: start filebeat with following configuration:

```
filebeat:
  prospectors:
    -
      paths:
        - /var/log/auth.log
        - /var/log/syslog
      input_type: log
      document_type: syslog
      ignore_older: 24h
      scan_frequency: 10s
      backoff: 1s
      max_backoff: 10s
      backoff_factor: 2
      force_close_files: false
      fields_under_root: false

  registry_file: /var/lib/filebeat/registry

output:
  logstash:
    hosts: ["shipper1:5044", "shipper2:5044"]
    worker: 2
    loadbalance: true
    index: filebeat

shipper:

logging:
  files:
    rotateeverybytes: 10485760 # = 10MB
```
