### ISSUE TITLE
[Metricbeat][statsd] runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#21733]
It looks like there is a bug in `statsd` module causing a panic, when the host is not provided:

```
2020-10-12T11:43:08.892-0400	ERROR	runtime/panic.go:212	recovered from panic while fetching 'statsd/server' for host ''. Recovering, but please report this.	

{"panic": "runtime error: invalid memory address or nil pointer dereference", "stack": "github.com/elastic/beats/v7/libbeat/logp.Recover\n\t/go/src/github.com/elastic/beats/libbeat/logp/global.go:101\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:969\nruntime.panicmem\n\t/usr/local/go/src/runtime/panic.go:212\nruntime.sigpanic\n\t/usr/local/go/src/runtime/signal_unix.go:695\ngithub.com/elastic/beats/v7/metricbeat/helper/server/udp.(*UdpServer).Stop\n\t/go/src/github.com/elastic/beats/metricbeat/helper/server/udp/udp.go:122\ngithub.com/elastic/beats/v7/x-pack/metricbeat/module/statsd/server.(*MetricSet).Run\n\t/go/src/github.com/elastic/beats/x-pack/metricbeat/module/statsd/server/server.go:102\ngithub.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).run\n\t/go/src/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:203\ngithub.com/elastic/beats/v7/metricbeat/mb/module.(*Wrapper).Start.func1\n\t/go/src/github.com/elastic/beats/metricbeat/mb/module/wrapper.go:147"}
```

**Comment by tugwitt** [comment]
This happened by including both `metricbeat.config.modules` and `metricbeat.modules`:

```
metricbeat.config.modules:

  # Glob pattern for configuration reloading
  path: ${path.config}/modules.d/*.yml

  # Period on which files under path should be checked for changes
  reload.period: 10s

  # Set to true to enable config reloading
  reload.enabled: false


metricbeat.modules:
- module: statsd
  host: "localhost"
  port: "8125"
  enabled: true
```

It goes away by just using `metricbeat.modules`:
```
metricbeat.modules:
- module: statsd
  host: "localhost"
  port: "8125"
  enabled: true
```
