### ISSUE TITLE
Support more resources in Kubernetes composable provider

### ISSUE THREAD

**Issue by exekias** [elastic/beats#21844]
Kubernetes composable provider supports discovering Pods, we should extend this to other resources, starting with Nodes and Services, to match what Beats can do today. This issue is to discuss the possible approach for this.

I don't see a big technical challenge (perhaps fixing https://github.com/elastic/beats/issues/21842) as this is a problem we have solved before, this is mostly about the user experience we want to provide. This is my initial proposal on how things would look for the `kubernetes` composable provider, I focused on the common use cases:

Note: this is also tied to the "Running Agent on Kubernetes discussion"

```
providers.kubernetes:
  unique_election: true  # Enables leader election between all Agent pods (we could decide hiding this and making it always true)
  ...
  resources:   # List of resources to watch
   # logs & metrics common use case, scoped to the current node, watch all Pods (and their containers)
   - resource: pod
     scope: node
     namespaces: []

   # Single team without cluster wide permissions, they normally want to have a deployment that watches a whole namespace (for metrics only)
   - resource: pod
     scope: cluster
     namespaces: ["myapp"]

   # hearbeat monitoring the whole cluster
   - resource: service
     scope: cluster
     unique: true   # Flag to emit events only from the leader

# kube-state-metrics
input:
 condition:
   - {{kubernetes.unique}} == true  # Launch this input only in the leader, different from the Heartbeat case 
```
