### ISSUE TITLE
Docker input module doesn't register log from restarted container (under some circumstances)

### ISSUE THREAD

**Issue by itsx** [elastic/beats#21948]
**Problem description:**

**Docker input module** doesn't register a newly created log file from a restarted docker container. Docker file is on the disk in the 
right folder, but docker module doesn't register it. After restart of the filebeat, this new logfile is correctly registered and processed.

We had encountered this problem with a celery-beat container running on three different computers and on all these three machines log was not registered as we checked in the filebeat registry file. Unfortunately were using loglevel INFO in filebeat, and there were no unusual information in the filebeat logs. Before this particular restart of the container, filebeat registered correctly all docker logs, event in the case of restarting of containers.

**Addition info:**
For more info I am attaching a link to a forum post (below), which we have created a month ago (which is now closed without a response).

Unfortunately we were not able to reproduce this problem so far.

I apologize that this is not a confirmed bug yet. We are quite confident about our observations, so we chose creating this as another step. Thanks for any suggestion on this topic.

Our filebeat config file:
```
logging.files:
  permissions: 0644

http:
  enabled: true
  host: ccc.ddd.cz
  port: 5066

filebeat.inputs:
- type: log
  enabled: true
  ignore_older: 24h
  close_inactive: 30s
  clean_inactive: 48h
  clean_removed: true
  paths:
    - /var/log/celery/beat.log*
  exclude_files: ['\.gz$']
  fields:
    service: celery-beat
  fields_under_root: true
  multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
- type: log
  enabled: true
  ignore_older: 24h
  close_inactive: 30s
  clean_inactive: 48h
  clean_removed: true
  paths:
    - /var/log/celery/worker-*.log*
  exclude_files: ['\.gz$']
  fields:
    service: celery-worker
  fields_under_root: true
  multiline.pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
- type: log
  enabled: true
  ignore_older: 24h
  close_inactive: 30s
  clean_inactive: 48h
  clean_removed: true
  paths:
    - /var/log/filebeat/filebeat*
  fields:
    service: filebeat
  fields_under_root: true
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
  multiline.negate: true
  multiline.match: after
  exclude_lines: ['DEBUG']
- type: docker
  enabled: true
  ignore_older: 24h
  close_inactive: 1m
  clean_inactive: 48h
  clean_removed: true
  containers.ids: '*'
  combine_partial: true
  cri.parse_flags: true
  processors:
    - add_docker_metadata:
        labels.dedot: true
  fields:
    service: docker
    loglevel: DEBUG
  fields_under_root: true

output.logstash:
  hosts: ["xxx.yyy:5044"]

```
- Version: 
`filebeat/stable 6.8.6 amd64 `

- Operating System: 
```
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

```
- Discuss Forum URL:
https://discuss.elastic.co/t/logfile-from-restarted-docker-container-is-not-scanned-and-written-to-registry/248177?u=tomas_bartek

- Steps to Reproduce: 
  Not reproduced yet. Supposed way to reproduce it is to restart docker containers under some additional condition, which we have not spotted yet.
