### ISSUE TITLE
Filebeat: the last line of the log with multiple lines on is repeatedly collected

### ISSUE THREAD

**Issue by CodyGuo** [elastic/beats#21949]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.
```yml
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - config:
            - type: log
              close_inactive: 2h
              paths:
                - /opt/logs/${data.docker.container.name}/*access.log
              fields:
                log_source: "file"
                log_topics: ${data.docker.container.name}
                log_host: "${HOST}"
                log_env: "${ENV}"

    - type: docker
      templates:
        - config:
            - type: container
              close_inactive: 2h
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              stream: "all"
              fields:
                log_topics: ${data.docker.container.name}
                log_source: "console"
                log_host: "${HOST}"
                log_env: "${ENV}"

            - type: log
              close_inactive: 2h
              paths:
                - /opt/logs/${data.docker.container.name}/*.log
              exclude_files: ['access\.log$']
              fields:
                log_topics: ${data.docker.container.name}
                log_source: "file"
                log_host: "${HOST}"
                log_env: "${ENV}"

      appenders:
        - type: config
          condition:
            or:
              - regexp:
                  container.name: "xxx-*"
          config:
            multiline:
              pattern: '^\[?(?:\d\d){1,2}[-\/](?:0?[1-9]|1[0-2])[-\/](?:(?:0[1-9])|(?:[12][0-9])|(?:3[01])|[1-9])[T ](?:2[0123]|[01]?[0-9]):(?:[0-5][0-9]):(?:(?:[0-5]?[0-9]|60)(?:[:.,][0-9]+)?)\s*(?:[0-9]+.[0-9]+)?\]?'
              negate: true
              match: after
              max_lines: 500
              timeout: 10s

```

For confirmed bugs, please report:
- Version: 
7.4.0
- Operating System: 
CentOS Linux release 7.3.1611 (Core)
- Discuss Forum URL:
- Steps to Reproduce: 
The log output time interval is 1 minute, and the last line of the log will be repeated for more than 6 times. The log.offset kibana sees is the same.
