### ISSUE TITLE
[Elastic-Agent] Monitoring should not use logstash output configuration to configure itself

### ISSUE THREAD

**Issue by ph** [elastic/beats#22051]
Monitoring is on by default on the _Elastic Agent_, when there is no configuration explicit set for the monitoring option it will use by default use the options defined in the output. 

The problem is the logic in place doesn't check the output type, this means it will use the logstash, redis or kafka host. We need to have distinct logic depending on the output type.

**Comment by ph** [comment]
In the current beats implementation the internal monitoring can only send to Elasticsearch, this is done because we need to massage the document in a specific way and send documents into a specific bulk api to add metadata, this endpoint is different from the normal indexing.

In Elastic Agent we do not use internal monitoring but instead  we are using external monitoring to collect metrics on the different, this allow us to use the normal bulk indexing endpoint.

Now by default when you start Elastic Agent in standalone, monitoring will be turned on and will use the "default" output as the destination. If you are using Elasticsearch as the default output the monitoring information will be send to the same endpoint.

If we add Kafka or Logstash should we also send our monitoring information through theses system, since Logstash and the ES connector will use the **data stream** fields to generate the destination it should send them to the appropriate destination.

@mostlyjason Do we want to send monitoring data through Logstash or even kafka?

**Comment by mostlyjason** [comment]
This sounds like a need for environments where there is a proxy between elastic agent and elasticsearch. This often occurs when there are secure networks and operators do not trust the agent or any host in that network to connect directly to ES. Perhaps we could make a case that monitoring data is less sensitive, but itd still be a pain to get firewall exceptions for it. It'd be easier if all data went through a single proxy like Logstash.

Btw, bonus points if monitoring data could use a separate named output if that makes routing to separate cluster easier. We don't support this today from Fleet but I'm not sure about standalone mode.

**Comment by ph** [comment]
@mostlyjason I am taking the following as a **Yes** :)

> It'd be easier if all data went through a single proxy like Logstash. 

For you second to support a separate named output., let's do that in another issue.

**Comment by mostlyjason** [comment]
CCing @ravi-elastic for input on the stack monitoring perspective. Do you agree that support for sending monitoring data through Logstash should be a requirement?

**Comment by mostlyjason** [comment]
@ravikesarwani

**Comment by ravikesarwani** [comment]
Sending Elastic Agent monitoring data directly to Elasticsearch (to the one and only Elasticsearch cluster) is ideal from monitoring perspective. Think about a scenario where logstash is backed up or having issues and we are sending everything via it, including monitoring data. Users will not see latest integration data and also won't see anything regarding Agent monitoring data. This will make debugging difficult. This applies to both self managed and Cloud environments.

Now a separate use case. User is using ESS. It's a bank or large enterprise with layers of security.
The user wants to use logstash (installed in their environment) and wants all integration data (from its networks) to go via it. For this Agent to be centrally managed, they do have to have connections to the Fleet server that's running in the Elastic Cloud.
Here they may say that they will be okay with degraded monitoring experience but cannot make more changes in their security for the Agents(that's sitting on their secure networks) to be able to make direct connections to the outside world (in this case Elasticsearch running in Elastic Cloud).

In my opinion we need to satisfy the first option as a must have where Agent is sending its monitoring data directly to the Elasticsearch cluster (to the one and only Elasticsearch cluster where the integration data rests as well) even when it maybe using logstash as an intermediary to send its integrations data.

For the second use case (more secure environments) they can configure the monitoring data to go via logstash but in this case they will get a little degraded monitoring experience.

**Comment by mostlyjason** [comment]
Thanks @ravikesarwani for raising this use case! It seems reasonable to me that we could ship two outputs  in the agent policy, one for the integration data (logstash) and one for the monitoring data (ES). 

@ph If we implement the option Ravi suggested, would that impact our ability to ship the logstash output by GA? If so, it'd be nice to consider what we can ship in that timeframe.

**Comment by ph** [comment]
looking at @ravikesarwani comment, if we fix the current problem with Logstash all the scenarios he stated should be possible.

**Comment by ravikesarwani** [comment]
@ph I don't think I understand the comment "if we fix the current problem with Logstash all the scenarios should be possible".
Can you expand. I know I coming in the mix recently so don't know the full background on this and the related issues. If there are docs/issues I should review please do let me know.

**Comment by ph** [comment]
lets me use configuration to illustrate how this work. 

By default the Elastic Agent use the "default" monitoring output as the destination.

```yaml

agent.monitoring:
   enabled: true
   logs: true 
   metrics: true
outputs:
  default:
     type:  elasticsearch
     hosts: 127.0.0.1
inputs:
  type: logfile
  streams:
   -...

```

If you want to use logstash
```yaml
agent.monitoring:
   enabled: true
   logs: true 
   metrics: true

outputs:
  default:
    type: logstash
    hosts 127.0.0.1
inputs:
  type: logfile
  streams:
   -...
```

If you want to send monitoring information to Elasticsearch but sent normal data to Logstash the following is possible too.

```
agent.monitoring:
   enabled: true
   logs: true 
   metrics: true
   use_output: monitoring
outputs:
  default:
     type:  elasticsearch
     hosts: 127.0.0.1
  monitoring:
    type: logstash
    hosts: 127.0.0.1
inputs:
  type: logfile
  streams:
   -...
```
If you want to send monitoring to another cluster this could be possible in **standalone**.

```
agent.monitoring:
   enabled: true
   logs: true 
   metrics: true
   use_output: monitoring
outputs:
  default:
     type:  elasticsearch
     hosts: 127.0.0.1
  monitoring:
    type: elasticsearch
    hosts: 127.0.0.2
inputs:
  type: logfile
  streams:
   -...
```

I am going to do more testing on my side for all the above scenario, but I have a PR open that fixes the main issue for Logstash https://github.com/elastic/beats/pull/24305
