### ISSUE TITLE
[Elastic Agent] Filebeat registry collisions when an integration is used twice

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#22054]
It seems like the `id` values assigned to log input streams are not sufficiently unique. The `id` assigned to input streams is what gets used by Filebeat to store data in the registry. So if you configure two streams with the same `id` then you get registry collisions. This will happen if you have two integrations consuming data from the same journal or event log (usually with different filters or pipelines in place to process a subset of the data from that source).

For example the FB registry would use a key like `winlog::winlog-windows.security::Security` when the `id` from Ingest Manager / Agent config is `winlog-windows.security`. And if you configure two instances of a package then you have registry collisions.

It looks like the Agent config has an UUID based `id` for each input. Perhaps that value could be used as part of the stream ID to make it unique? Here's a select view of an agent config with two instances of integration enabled. I'm using the winlog input as an example, but I think a similar case could happen with journald and possibly other inputs.

```
inputs:
  - id: 6dd5f750-13a6-11eb-aee6-bdad233908c2
    name: windows-logs
    type: winlog
    streams:
      - id: winlog-windows.security
        name: Security
  - id: f74c1200-13b8-11eb-aee6-bdad233908c2
    name: windows-2
    type: winlog
    streams:
      - id: winlog-windows.security
        name: Security
```

**Comment by urso** [comment]
Depending on your config filebeat uses a 2 or 3 tuple for keys in the registry. With the ID set it is 3 a tuple of `ID`, `input type` (in this case `winlog`), and `path` (in this case 'Security').

We have 2 inputs with differing ID. But inputs can have multiple streams. The Input ID and stream ID should also be added to logs and health-checks/reports. That is each stream must become uniquely identifieable, as the 'Stream' is the actual 'input' doing the data collection. The stream ID seems to be the data stream name, is this correct? If so, why don't we use data_stream and create an unique ID for the stream config. If the stream is reconfigured we can either keep the ID, or consider to rename the ID (so we can correlate logs to the entity that has been used to configure Beat).

When sending configs to the log, filestream, or winlog input in filebeat we at least need to merge input ID and stream ID during the translation. When introducing the collector, the 'merge' would automatically happen in the collector.

The configuration here seems to translate into:

```
filebeat.inputs:
- type: winlog
  id: winlog-windows.security
  ...
- type: winlog
  id: winlog-windows.security
  ...
```

Due to having the same ID the 2 inputs can't be distinguished. We should generate this configuration:

```
filebeat.inputs:
- type: winlog
  id: winlog-windows.security.6dd5f750-13a6-11eb-aee6-bdad233908c2
  ...
- type: winlog
  id: winlog-windows.security.f74c1200-13b8-11eb-aee6-bdad233908c2
  ...
```

Now the 2 inputs are independent.

Heartbeat might have a similar need.
