### ISSUE TITLE
Wrong behavior using UDP input and conditional pipelines in output

### ISSUE THREAD

**Issue by psanz-estc** [elastic/beats#22062]
Component: filebeat
Version: 7.9.1

When using UDP input plus conditional pipelines in elasticsearch output, it seems the behavior is not the same as when using file input

Given this pipeline
```
PUT _ingest/pipeline/test_pipeline
{
"processors" : [
{
"append" : {
"field" : "check",
"value" : "ok"
}
}
]
}
```

And this configuration:

```
filebeat.inputs:

- type: log
  enabled: true
  paths:
    - /var/log/ECE/test.log
  fields_under_root: true
  fields:
    tech: pipelinetest
  json:
    keys_under_root: true

- type: udp
  enabled: true
  host: "localhost:9003"
  tags: ["test"]
  fields_under_root: true
  fields:
    tech: pipelinetest

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml

  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1

setup.template.name: "test-pipeline"
setup.template.pattern: "test-pipeline-*"
setup.ilm.enabled: false

setup.kibana:
  host: "192.168.64.3:5601"

output.elasticsearch:
  hosts: ["192.168.64.3:9200"]

  index: "test-pipeline-%{+yyyy.MM.dd}"
  username: "elastic"
  password: "pass"
  pipelines:
   - pipeline: test_pipeline
     when.equals.tech: "pipelinetest"

logging.level: debug

logging.selectors: ["*"]
```

We would expect documents coming from both UDP and `/var/log/ECE/test.log`to be routed through the `test_pipeline`, but it doesn't happen.

Looking at the tcpdump traces, when using UDP input there is no mention to the pipeline in the json document being sent to ES:

![image](https://user-images.githubusercontent.com/44199691/96768765-82058780-13de-11eb-9614-36826e2bbf84.png)
