### ISSUE TITLE
Filebeat Processors - make uppercase and lowercase processors (as in ES ingest nodes) available to filebeat

### ISSUE THREAD

**Issue by ccmsi** [elastic/beats#22254]
Greetings and thanks for this software.

I would like to request for adding the two processors uppercase and lowercase to filebeat input processing.

Besides being useful, adds to making things consistent.

Thanks for your time and attention

**Comment by andresrc** [comment]
We are encouraging the use of ingest-node processors. What's the driving use case to have them available in the beats themselves?

**Comment by ccmsi** [comment]
The question seems like asking about personal taste. And as there are 2 options thats in a way how it is.

However, its filebeat that offers that option to begin with. There are processors. So one question in return is, why then does it exist if that is your question? IMO filebeat team by implementing processors that has already expressed that interest for it to be there and as such that question seems awkward.

For support, i appreciate that decision of the filebeat team to provide processors. I think central management is nice, but distributing load is advantageous performance wise and offers flexibility.

My request though is about why not having those two simple ones, where the more complex ones, even script, are available.

**Comment by trnl** [comment]
I would double that. 

Now we have hideous rename block with a lot of boilerplate because of casing:
```yaml
          - from: header.x-request-id
            to: x-request-id
          - from: headers.x-request-id
            to: x-request-id
          - from: headers.X-Request-ID
            to: x-request-id
          - from: headers.X-Request-Id
            to: x-request-id
          - from: headers.X-request-Id
            to: x-request-id
```
