### ISSUE TITLE
[O365] Update docs for Teams support

### ISSUE THREAD

**Issue by jamiehynds** [elastic/beats#22293]
@P1llus recently tested ingestion of MS Teams audit events via our existing O365 module and confirmed it works fine. Can we update the existing [O365 module doc](https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-module-o365.html) to reflect support for Teams?

**Comment by radoondas** [comment]
Hey @jamiehynds and @P1llus , would you be able to share the basic configuration you had to use to access the events? On both sides, beats and also Azure o365. This would be great for users trying to setup MS teams data ingestion.
Thanks

**Comment by eyekelly** [comment]
+1 at least, this would be very helpful info

**Comment by P1llus** [comment]
Hello @radoondas and @eyekelly . As you might know, the O365 Beats module uses this API: https://docs.microsoft.com/en-us/office/office-365-management-api/office-365-management-activity-api-reference

Now when it comes to Teams, the logging there is not very well documented, and its enabled per default, there is no changes that I know off that has to be done to enable this logging.

A few pointers though:
1. Microsoft Team Audit events is actually Azure AD audit events, so they would appear under `Audit.AzureActiveDirectory`.
2. The general Microsoft Teams logging, which is already a bit limited under this 365 Management API, will appear under `Audit.General`

When I tested I simply ran with the defaults, because all content types are subscribed to if you look at `var.content_type` here: https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-module-o365.html#_configuration_options_34

So in the end the configuration file for beats would look like this:
```
  audit:
    enabled: true
    var.application_id: "<My Azure AD Application ID>"
    var.tenants:
      - id: "<My Tenant ID>"
        name: "mytenant.onmicrosoft.com"
    var.client_secret: "<My client secret>"
```
