### ISSUE TITLE
[publisher_pipeline_output]	pipeline/output.go:180	failed to publish events: temporary bulk send failure

### ISSUE THREAD

**Issue by reckless-huang** [elastic/beats#22408]
good  morning teacher
           i just get a error log while i start filebeat like“[publisher_pipeline_output]	pipeline/output.go:180	failed to publish events: temporary bulk send failure” ，and here is my configfile 
```
filebeat.inputs:
- type: log
  paths:
    - /opt/logs/*
  fields:
    log_type: '${log_name}'
    pod_name: '${pod_name}'
    pod_ip: '${pod_ip}'
    pod_ns: '${pod_namespace}'
    node_name: '${node_name}'
  fields_under_root: true
processors:
- drop_fields:
        fields:
        - agent.ephemeral_id
        - agent.hostname
        - host.name
        - agent.name
        - agent.id
        - agent.type
        - agent.version
        - ecs.version
        - input.type
        - log.offset
        - _id
- decode_json_fields:
        fields:
        - message
        max_depth: 1
        overwrite_keys: true
output.elasticsearch:
  hosts: ["10.110.231.223:9200"]
  index: "%{[fields.log_type]}-%{[agent.version]}-%{[fields.pod_name]}"
setup.template.name: "yyb"
setup.template.pattern: "yyb-*"
setup.template.overwrite: true
```
 i can not clear what problem with this, can you help me

Looking forward to your reply& thank you
