### ISSUE TITLE
Filebeat is sending low log (missing log) than normal in rush-hour

### ISSUE THREAD

**Issue by AkatsukiPain** [elastic/beats#22476]
**Problem/Reality:**

- I have used Filebeat to send logs to ElasticSearch. It's OK in the day time with the number of logs is around 800k ~ 1,5 million rows / 15 mins.
- In the rush hour (evening time), the number of logs is more than 2 million rows / 15 mins => Filebeat stuck at this time.
- After evening time to the morning, Log is still missing until I restart filebeat to make it run like normal in the day time.

**My Filebeat Config**
```
filebeat.inputs:


#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false
  harvester_buffer_size: 300000000
  max_bytes: 10000000
#============================= Elastic Cloud ==================================
filebeat.spool_size: 8192
bulk_max_size: 3096
flush_interval: 1s
compression_level: 3
worker: 4
#force_close_files: true
#close_older: 10m
close_inactive: 45m
ignore_older: 30m
registry: /var/lib/filebeat/registry
cloud.id: xxxx
cloud.auth: "fxxx"

setup.template.name: "nginx-7.3.2"

setup.template.pattern: "nginx-7.3.2-*"

setup.template.enabled: true

setup.template.overwrite: false

setup.ilm.enabled: auto

setup.ilm.rollover_alias: "nginx-7.3.2"

setup.ilm.pattern: "{now/d}-000001"

logging.metrics.period: 20s

scan_frequency: 3s
```

I used logrotate to rotate log every 100MB ( every 5-mins in crontab) but sometimes it reaches 300-500MB in rush hour.
My filebeat version: **filebeat version 7.3.2 (amd64), libbeat 7.3.2 [5b046c5a97fe1e312f22d40a1f05365621aad621 built 2019-09-06 13:49:32 +0000 UTC]**

**This is my graph**
![image](https://user-images.githubusercontent.com/14358073/98429350-ad73bc00-20d8-11eb-8394-c14aef811ebd.png)

![image](https://user-images.githubusercontent.com/14358073/98429432-1c511500-20d9-11eb-84c4-ae3454a430b5.png)

Please help me check this problem. The information above is what I have collected
