### ISSUE TITLE
Can't run metricbeat as a Docker sidecar for Prometheus

### ISSUE THREAD

**Issue by loganmc10** [elastic/beats#22477]
I have 2 docker containers. One is called "metricbeat" and the other is called "prom". They are created using docker-compose, and share an internal docker network.

prometheus.yml:
```
remote_write:
  - url: "http://prom:9201/write"
```

metricbeat.yml
```
metricbeat.modules:
- module: prometheus
  metricsets: ["remote_write"]
  host: "localhost"
  port: "9201"
```

The problem is that if I use ```host: "localhost"``` for metricbeat, it binds to localhost, and the ```prom``` container can't access it on ```http://prom:9201``` (connection refused). If I do ```host: "0.0.0.0"```, still connection refused. If I do ```host: "prom"```, I get "cannot bind to address" from the metricbeat container.

All the examples use "localhost" as the host, but you can't use localhost when you are communicating between 2 docker containers like this.
