### ISSUE TITLE
drop_event does not work in a Metricbeat module filter

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#2249]
- Version: 5.0.0-alpha5
- Operating System: Any
- Steps to Reproduce: 

```
metricbeat:
  modules:
    - module: system
      metricsets: [filesystem]
      period: 15s 
      filters:
        - drop_event:
            when:
              regexp:
                mount_point: '/dev'
output.console:
  pretty: true
```

When the event is published this is what you get. Notice the `null`. What should happen is the whole event is dropped.

```
{
  "@timestamp": "2016-08-11T23:03:34.988Z",
  "beat": {
    "hostname": "myhost",
    "name": "myhost"
  },
  "metricset": {
    "module": "system",
    "name": "filesystem",
    "rtt": 197
  },
  "system": {
    "filesystem": null
  },
  "type": "metricsets"
}
```
