### ISSUE TITLE
Enrich Filebeat on k8s docs with json parsing settings

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#22516]
It is common case that applications running on k8s log in json format. In this regard it would be helpful to provide examples in our docs about how one can leverage Filebeat's json specific settings in order to json parse logs coming from Pods running on k8s.

These examples could be part of https://www.elastic.co/guide/en/beats/filebeat/master/running-on-kubernetes.html

json settings that could be used:
- https://www.elastic.co/guide/en/beats/filebeat/current/decode-json-fields.html ([example](https://github.com/elastic/observability-test-environments/blob/master/ansible/roles/k8s-beats/files/k8s/beats/filebeat/filebeat-configmap.yaml#L186-L209))
- https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#filebeat-input-log-config-json

**Comment by graphaelli** [comment]
In particular, examples that demonstrate parsing json logs from some pods and not from others.

**Comment by felixbarny** [comment]
The examples should ideally use ECS-JSON structured logs. See also https://github.com/elastic/ecs-logging and an example Filebeat config here: https://github.com/elastic/ecs-logging-java#step-3-filebeat-configuration

And potentially even demonstrating parsing a mix of JSON and non-JSON for the same pod. This can happen when different sub-components have different logging settings.

**Comment by ChrsMark** [comment]
Hi again!

Parsing json logs conditionally can only be achieved with autodiscover conditions.
Below I'm posting an example with 1 pod containing 2 containers (one logs in json format and the other logs in plaintext):


```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-ingest-management
  namespace: kube-system
  labels:
    app: kibana-ingest-management
    group: ingest-management
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec:
  selector:
    matchLabels:
      app: kibana-ingest-management
  template:
    metadata:
      labels:
        app: kibana-ingest-management
        group: ingest-management
    spec:
      volumes:
        - name: kibana-yaml-config
          configMap:
            defaultMode: 420
            name: kibana-yaml-storage
      containers:
        - name: test
          image: ubuntu:latest
          command:
            - bash
            - -c
            - |
              #!/bin/bash
              echo "$(date): started the process"

              while :
              do
                     echo "$(date): sleeping 5 seconds"
                     sleep 5
              done
        - name: kibana-ingest-management
          image: docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /usr/share/kibana/config
              name: kibana-yaml-config
          ports:
            - containerPort: 5601
              name: ui
              protocol: TCP
```

The autodiscover template I need in order to handle the logs of these 2 containers is the one following:

```
    filebeat.autodiscover:
      providers:
          - type: kubernetes
            node: ${NODE_NAME}
            templates:
              - condition:
                  contains:
                    kubernetes.container.name: "test"
                config:
                  - type: container
                    paths:
                      - "/var/log/containers/*-${data.kubernetes.container.id}.log"
              - condition:
                  contains:
                    kubernetes.container.name: "kibana-ingest-management"
                config:
                  - type: container
                    paths:
                      - "/var/log/containers/*-${data.kubernetes.container.id}.log"
                    processors:
                      - decode_json_fields:
                          fields:
                            - message
                          target: ""
                          overwrite_keys: true
                          add_error_key: true
```

The result looks like this:
kibana's json logs:
<img width="1224" alt="Screenshot 2020-11-11 at 13 10 27" src="https://user-images.githubusercontent.com/11754898/98804850-66aafc80-241f-11eb-80ce-f4ca71b6b404.png">

test container's plaintext logs:
<img width="1138" alt="Screenshot 2020-11-11 at 13 12 22" src="https://user-images.githubusercontent.com/11754898/98804948-8e9a6000-241f-11eb-838f-8e04386277f7.png">


@graphaelli @felixbarny is this what you had in mind? Let's keep the discussion in this issue and when we are settled I will update the docs.

cc-ing @exekias who might also have additional comments.

**Comment by graphaelli** [comment]
The resulting docs looks exactly as I'd expect, this is great.  This example is exactly why we need this documentation - I came up with a similar solution but used `json.*`, including `json.keys_under_root` instead of the `decode_json_fields` processor.

**Comment by exekias** [comment]
Thanks @ChrsMark!, a hints based solution would also be good, right? [Hints support the `json`](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html#_co_elastic_logsjson) options, so adding an annotation like `co.elastic.logs/json.keys_under_root=true` would just work. It can be scoped to a single container in the Pod, like `co.elastic.logs.<container_name>/json.keys_under_root=true`.

About `decode_json_fields` vs `json.*`, there is no strong preference here, but `json.*` is slightly better, as the decoding happens before line filtering and multiline rules, so you have more power to mangle the data inside the JSON.

**Comment by ChrsMark** [comment]
@exekias the equivalent using `json.*` works but need a `format: "json-file"` setting in my case.

This makes me think if [json with hints](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html#_co_elastic_logsjson) will work as expected in that case. Note that we explicitly mention about json decoding at hints' docs:

```
  co.elastic.logs/json.keys_under_root: true
  co.elastic.logs/json.add_error_key: true
  co.elastic.logs/json.message_key: log
```

**Comment by ChrsMark** [comment]
Also working with what @exekias proposed:

autodisocer config:

```
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - /var/log/containers/*${data.kubernetes.container.id}.log
```

pod example:

```
apiVersion: v1
kind: Pod
metadata:
  name: two-containers-json
  annotations:
    co.elastic.logs.kibana-ingest-management/json.keys_under_root: "true"
    co.elastic.logs.kibana-ingest-management/json.add_error_key: "true"
    co.elastic.logs.kibana-ingest-management/json.message_key: "message"
spec:
  containers:
    - name: test
      image: ubuntu:latest
      command:
        - bash
        - -c
        - |
          #!/bin/bash
          echo "$(date): started the process"

          while :
          do
                 echo "$(date): sleeping 5 seconds"
                 sleep 5
          done
    - name: kibana-ingest-management
      image: docker.elastic.co/kibana/kibana:8.0.0-SNAPSHOT
      resources:
        limits:
          cpu: 1000m
        requests:
          cpu: 100m
      ports:
        - containerPort: 5601
          name: ui
          protocol: TCP
```
