### ISSUE TITLE
Filebeat NGINX module 7.10.0 Upgrade Errors

### ISSUE THREAD

**Issue by christophercutajar** [elastic/beats#22567]
For confirmed bugs, please report:
- Version: 7.10.0
- Operating System: ECK 1.3 
- Steps to Reproduce: Upgrade `filebeat` with `nginx` module from `7.9.3` to `7.10.0`

While upgrading `filebeat` from `7.9.3` to `7.10.0` which leverage a `nginx` module the deployment was failing. After checking the log file I had the below errors:

```
2020-11-12T11:04:12.865Z        ERROR   instance/beat.go:951    Exiting: 1 error: Error setting up ML for nginx_ecs: 10 errors: ; ; ; ; ; ; ; ; ; 
Exiting: 1 error: Error setting up ML for nginx_ecs: 10 errors: ; ; ; ; ; ; ; ; ;
```

```
2020-11-12T11:37:14.792Z        ERROR   instance/beat.go:951    Exiting: 1 error: Error setting up ML for nginx_ecs: cannot set up ML with prefix: filebeat-nginx_ecs-access-, response: 
Exiting: 1 error: Error setting up ML for nginx_ecs: cannot set up ML with prefix: filebeat-nginx_ecs-access-, response:
```

**Comment by christophercutajar** [comment]
`filebeat.yml` looks like this:

```
setup.dashboards.enabled: true
setup.template.enabled: true
setup.template.overwrite: true
setup.kibana:
host: "xxxxxx-kb-http:5601"
username: ${ELASTIC_USERNAME}
password: ${ELASTIC_PASSWORD}
protocol: https
ssl:
  enabled: true
  certificate_authorities: /usr/share/filebeat/pki/kibana.crt
  supported_protocols: ["TLSv1.2"]
  renegotiation: never

filebeat.modules:
- module: elasticsearch
- module: logstash
- module: kibana
- module: nginx
- module: okta
- module: o365
- module: googlecloud
- module: gsuite

output.elasticsearch:
  hosts: ["xxxxxx-es-http:9200"]
  loadbalance: true
  max_retries: 0 # retry forever
  username: ${ELASTIC_USERNAME}
  password: ${ELASTIC_PASSWORD}
  protocol: https
  ssl:
    enabled: true
    certificate_authorities: /usr/share/filebeat/pki/elasticsearch.crt
    supported_protocols: ["TLSv1.2"]
    renegotiation: never
```

**Comment by christophercutajar** [comment]
Linking some issues provided by @sophiec20  in relation to this issue: 

- https://github.com/elastic/sdh-beats/issues/460
- https://github.com/elastic/beats/issues/11349

Using the `elastic` user still keeps getting the same error logs.

**Comment by christophercutajar** [comment]
@kvch By adding `--dashboards --index-management` to the `filebeat -e setup` in our Helm configuration and leaving the modules configured in the yml file, did the job! 

What now I'm not sure is how to load the ML jobs for nginx, unless they are pre-loaded!

**Comment by EvgeniGordeev** [comment]
@christophercutajar `filebeat setup -e --modules nginx --dashboards --index-management` didn't help in our case (Kubernetes 1.16 cluster), actually also tried to upgrade to `7.10.1`  but without luck. Checking in Discover I don't see any hits with `event.module:nginx` as they used to be in 7.9.3. 

`filebeat.yml`: 

```yaml
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
      filebeat.config.modules:
        path: ${path.config}/modules.d/*.yml
      fields:
        logtype: kubernetes
        kubernetes.cluster.name: '${EKS_CLUSTER_NAME:undefined}'
        k8s.cluster.name: '${EKS_CLUSTER_NAME:undefined}'
      setup.kibana:
        host: "elastic-stack-kibana:5601"
        protocol: "http"
      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
      # setup custom index name since we use a single ES for multiple clusters
      setup.ilm:
        rollover_alias: 'filebeat-${EKS_CLUSTER_NAME:undefined}-%{[agent.version]}'
        overwrite: true
      setup.template.settings:
        index:
          max_docvalue_fields_search: 200
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            templates:
              - condition:
                  equals:
                    kubernetes.labels.app: ingress-nginx
                config:
                  - module: nginx
                    error:
                      enabled: true
                    ingress_controller:
                      enabled: true
                      input:
                        type: container
                        containers.ids:
                          - "${data.kubernetes.container.id}"
```
