### ISSUE TITLE
Correct way to drop syslog events with filebeat

### ISSUE THREAD

**Issue by dudubis** [elastic/beats#22585]
Hi, I'm trying to drop some events from syslog but not sure the correct condition and path:
(the below processor is not working for me with a confirmed regex)    

```
    filebeat.modules:
      - module: system
        syslog:
          enabled: true
          #var.paths: ["/var/log/syslog*"]          
        auth:
          enabled: false
          #var.paths: ["/path/to/log/auth.log*"]  

    processors:
    - add_kubernetes_metadata: 
        in_cluster: true
    - drop_event:        
        when:
          or:
            - regexp:
                system.syslog.message: ".*IPv4: martian source.*"
            - regexp:
                system.syslog.message: ".*ll header: 00000000:.*"
```

Can someone assist with the correct way or point to the relevant documentation? 

Thanks,
Dudu.
