### ISSUE TITLE
Filebeat high disk usage when reboot server. How fix it?

### ISSUE THREAD

**Issue by arpsyapathy** [elastic/beats#22656]
Hi all!
Filebeat on server send many events from logs of exchange (windows) server to logstash.
When we reboot server filebeat make high disk usage. Other services can't load for a long time.
How can i fix it? Thank you

my config:
```
setup.ilm.enabled: false
setup.template.name: "exchange"
setup.template.pattern: "exchange*"
setup.template.overwrite: true
setup.template.settings:
  index.number_of_shards: 3
  index.number_of_replicas: 0
tags: ["exchange-transport"]
output.logstash:
  ssl.enabled: true
  hosts: ["elk-server:5044"]
  index: "exchange-%{+YYYY.MM.dd}"
logging.level: info
logging.to_files: true
logging.files:
  path: C:\Program Files\Filebeat\logs
  name: Filebeat.log
  keepfiles: 7
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - C:\Program Files\Microsoft\Exchange Server\V15\TransportRoles\Logs\MessageTracking\MSGTRK*.LOG
  exclude_lines: ["^#"]
  document_type: exchange           
  ignore_older: 47h  
  fields:
    type: exchange
  fields_under_root: true
```
