### ISSUE TITLE
Redis Module: Metricbeat 7.10.0 service object host parsing errors

### ISSUE THREAD

**Issue by berglh** [elastic/beats#22705]
- Version: 7.10.0
- Operating System: Oracle Enterprise Linux 7.8
- Docker: 19.03.9

## Description

The generation of the service object in Redis is no longer handling the parsing of redis module configuration for each host. Below is the configuration, along with service object outputs for Metricbeat 7.9.3 where the output is generated correctly, and 7.10 where the redis URI protocol seems to be detected as the host name and the port is incorrectly detected.

Reverting back to 7.9.3 resolves the issue. I had a quick look at 7.10 documentation and didn't see that any changes to this configuration were expected. I did try specifying the "db" parameter as `?db=1`, but the similar problem occurred.

## Metricbeat Redis Configuration
```yaml
metricbeat.modules:
- module: redis
  metricsets: ['info','keyspace']
  key.patterns:
    - pattern: '*'
      limit: 20
  period: 10s
  hosts: ["redis://host1:6378","redis://host1:6378/1"]
- module: redis
  metricsets: ['info','key','keyspace']
  key.patterns:
    - pattern: '*'
      limit: 20
  period: 10s
  hosts: ["redis://host1:6379","redis://host2:6379","redis://host3:6379","redis://host4:6379","redis://host5:6379"]
```

### Metricbeat 7.9.3 Output
```json
    "service": {
      "type": "redis",
      "host": "host1",
      "port": "6379",
      "address": "host1:6379"
    }
```

### Metricbeat 7.10 Output
```json
    "service": {
      "address": "redis://host1:6378/1",
      "type": "redis",
      "host": "redis",
      "port": "//host1:6378/1"
    }
```
