### ISSUE TITLE
Metric Kafka Broker Module collected JMX/Jolokia metrics

### ISSUE THREAD

**Issue by gquintana** [elastic/beats#22735]
As of Kafka 2.6, this metric doesn't exist however it's collected:
```
 - mbean: 'kafka.log:type=LogFlushStats,name=LogFlushRateAndTimeMs'
        attributes:
          - attr: MeanRate
            field: log.flush_rate
```
Then the same metric is collected twice with 2 different names:
```
    - mbean: 'kafka.server:name=FailedProduceRequestsPerSec,type=BrokerTopicMetrics'
        attributes:
          - attr: MeanRate
            field: request.produce.failed_per_second
      - mbean: 'kafka.server:name=FailedProduceRequestsPerSec,type=BrokerTopicMetrics'
        attributes:
          - attr: MeanRate
            field: request.produce.failed
```
Finally it would make sense to collect ReplicaManager related metrics:
* `kafka.server:type=ReplicaManager,name=OfflineReplicaCount`
* `kafka.server:type=ReplicaManager,name=UnderReplicatedPartitions`
* `kafka.server:type=ReplicaManager,name=UnderMinIsrPartitionCount`
* etc.
