### ISSUE TITLE
Unable to drop fields using filebeat [7.10]

### ISSUE THREAD

**Issue by seddikalaouiismaili** [elastic/beats#22774]
hello, 

I have installed filebeat 7.10 for just forwarding log file from twice sources , and output them to another file . 
My goal is to drop  some fields like `@timestamp,  @metadata,  host, agent, type, hostname , log ` . 

See below my configuration file : 

```
filebeat.inputs:
- type: log
  paths:
    - /logs-nfs/syslog-ng/XX-01/Log01.log
    - /logs-nfs/syslog-ng/XX-02/Log02.log

output.file:
  path: "/logs-nfs/syslog-ng/"
  filename: all.log
  permissions: 0600

processors:
  - drop_fields:
        #fields: ["log.offset", "input.type", "fileset.name", "log.source.address", "log.flags"]
        fields: ["agent.name", "agent.id", "beat.name", "timeseries.instance"]
```

filebeat works, but i still show the fields values on my output !! 

is it a bug? , or i have not configured correctly filebeat ? 

Regards
sai
