### ISSUE TITLE
[filebeat][o365]  Mapping problem on o365.audit.Parameters

### ISSUE THREAD

**Issue by willemdh** [elastic/beats#22780]
- Version: 7.9.2
- Operating System:  CentOS 8
- Discuss Forum URL: https://discuss.elastic.co/t/ingesting-o365-logs-but-having-issues-with-specific-mappings/256081
- Steps to Reproduce: Ingest lots of o365 audit logs some with o365.audit.Parameters and some without o365.audit.Parameters

Error:

`Cache:publisher.EventCache{m:common.MapStr(nil)}} (status=400): {"type":"mapper_parsing_exception","reason":"object mapping for [o365.audit.Parameters] tried to parse field [Parameters] as object, but found a concrete value"}`

Workaround:

```
- drop_fields:
    when:
      equals:
        event.module: 'o365'
    fields: ["o365.audit.Parameters"]
```

**Comment by cakarlen** [comment]
Bump on this issue as I experienced this exact error as OP described above when turning up o365 logging. Verified my Azure app has the correct permissions and manually tested API creds to verify

**Comment by willemdh** [comment]
@cakarlen The workaround works fine for me, but we shouldnt have to do this..

**Comment by P1llus** [comment]
Some quick updates on this, sorry for the silence here.
The 7.13.2 filebeat module has an update for this: https://github.com/elastic/beats/pull/26164

For the package(fleet version), it will come out with a requirement of 7.14, as the package has some features that it is required for. This can be followed here: https://github.com/elastic/integrations/pull/1136

The current implementation will copy the Parameters field to Parameters._raw if its a string. This is to make sure that ingestion works.
A later version we might want to come back and build more parsers for these string fields, but the current issue is that the string values in the parameters field does not follow a specific format, and varies quite a lot, so this will have to be the initial change.

**Comment by kh31r0n** [comment]
- Version: 7.15.2
- Running on: kubernetes
Error: 
   ` object mapping for [o365audit.ModifiedProperties] tried to parse field [null] as object, but found a concrete value`
Workaround:
```
processors:
  - drop_fields:
      when:
        equals:
          event.module: 'o365'
      fields: ["o365audit.ModifiedProperties"]
```
      
 Same problem but with different field.
