### ISSUE TITLE
Add option to preserve event.original

### ISSUE THREAD

**Issue by jamiehynds** [elastic/beats#22856]
Some of our security integration modules preserve event.original, while others do not (e.g. Winlogbeat). Preserving event.original has a significant impact on the storage size of an event, in some cases doubling the size of the event. 

Some users may have a requirement to preserve event.original but this should be optional. Could we add a switch to our modules (disabled by default) to allow some optionality on the preservation of event.original at the fileset level?

**Comment by NeilADesai** [comment]
This should also go for original event fields (i.e. CEF module). We should not have duplicate fields by default.

**Comment by leehinman** [comment]
We currently use a tag of "forwarded" to control if host info is
disabled:

https://github.com/elastic/integrations/blob/19c8c76a3f04ba9a02e61d8c693bd87cd5c3dcfd/packages/okta/data_stream/system/agent/stream/httpjson.yml.hbs#L41

This "feels" similar, we could use a tag to represent
"preserve_original_event".

We don't have to use tags, but either way I think it would be nice to
have one way in which we add data to an event to control it's
processing.  I also think it would be good to preserve this value so
the data could be re-indexed and get the same effect.

One other thing I thought of, want to make sure we don't accidentally
increase network bandwith by copying to event.original before we send
to ingest node.

**Comment by andrewkroh** [comment]
I like the idea of making it easy to reindex data from event.original.

> I also think it would be good to preserve this value so
> the data could be re-indexed and get the same effect.

With our pipelines all expecting the original value to be contained in `message`, using `_reindex` won't work as expected since the `message` value taken from _source will be the modified non-original value. It would be nice if Filebeat always set `event.original` rather than `message`. I guess pipelines could be made to use `event.original` if it exists, otherwise use `message`, but I would prefer invariant logic.

**Comment by P1llus** [comment]
I agree with both as well, just to try to sum it up:

- Change is only to be applied to packages, this includes all packages from both Observability and Security.
- This does not include special packages like endpoint and APM.
- The field to be used to preserve the event, is `event.original`.
- Instead of copying `message` to `event.original`, for reindex purposes the pipelines should be rewritten to use `event.original` instead. This makes the reindex experience much smoother.
- Each package will have a configuration option in the Fleet menu, asking for `Preserve original event`, which defaults to off.
- If `Preserved original event` is set to true by the user, a tag is applied which is called `preserve_original_event`
- If the tag is set, the ES Ingest Pipeline will be used to preserve the event, instead of local processing by the beat/agent, as that will be removed.
- `event.original` should not be a indexed field.

Example on adding the configuration option to the UI:
```
    vars:
      - name: preserve_original_event
        required: true
        show_user: true
        title: Preserve original event
        description: Preserves a raw copy of the original event, added to the field event.original
        type: bool
        multi: false
        default: false
```

In the agent configuration, to send the configuration object, we will use the tag preserve_original_event
```
tags:
{{#if preserve_original_event}}
- preserve_original_event
{{/if}}
{{#each tags as |tag i|}}
 - {{tag}}
{{/each}}
```

In ingest pipelines, depending on which source field we use, let's say currently is `message` that we want to preserve
```
  - set:
      field: event.original
      copy_from: message
      if: "ctx?._conf?.keep_original_message == true"
```
