### ISSUE TITLE
SQS metricset reports misleading error message

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#22946]
User reports when running `sqs` metricset with config that specifies a `endpoint`, error message is still showing endpoint with `amazonaws`:
```
- module: aws
  period: 5m
  metricsets:
    - sqs
  #endpoint: "c2s.ic.gov"
  endpoint: "google.com"
  #endpoint: "askdlfjalsk.com"
  regions: "us-iso-east-1"
  access_key_id: "kasfdlkjasdflkasdjflkasdjf"
```
error message:
```
2020-12-03T15:20:58.405-0500    ERROR   [aws.sqs]       sqs/sqs.go:85   Error ListQueues: RequestError: send request failed
caused by: Post https://sqs.us-iso-east-1.amazonaws.com/: dial tcp: lookup sqs.us-iso-east-1.amazonaws.com on 192.168.1.1:53: no such host
```
