### ISSUE TITLE
AJP protocol support in Heartbeat to test Apache JServ Protocol access

### ISSUE THREAD

**Issue by dagwieers** [elastic/beats#22949]
**Describe the enhancement:**
We would like to have support for AJP in Heartbeat to test the AJP protocol from a monitor, just like we currently test the HTTP protocol.

**Describe a specific use case for the enhancement or feature:**
Since AJP is a binary protocol and it has some performance benefits over HTTP, this is what is usually used if you have a load-balancer or proxy in front of your application.

A basic test could perform just a simple ping test:
> You would transmit and expect the following hexadecimal-formatted data: 
> - Transmit (AJP CPing): \x12\x34\x00\x01\x0A
> - Expected response (AJP CPong): \x41\x42\x00\x01\x09

And this already works using a tcp test:
```yaml
  - type: tcp
    id: ajp-ping
    name: AJP ping
    hosts:
    - tcp://localhost:8009
    check:
      send: "\x12\x34\x00\x01\x0A"
      receive: "\x41\x42\x00\x01\x09"
    schedule: '@every 15s'
```

But it would be even better if it could target the application, e.g. status/health page and handle response codes accordingly. This is currently not possible using the tcp monitor (since the `check.receive` requires an exact match). So the below does not work (as `send.receive` is only the start of the response, not the complete response).

```yaml
  - type: tcp
    id: ajp-signin
    name: AJP signin
    hosts:
    - tcp://localhost:8009
    check:
      send: "\x12\x34\x00\x4F\x02\x02\x00\x08HTTP/1.1\x00\x00\x07/signin\x00\x00\x09127.0.0.1\x00\x00\x09localhost\x00\x00\x09localhost\x00\x00\x50\x00\x00\x01\xa0\x0b\x00\x09localhost\x00\xff\x00"
      receive: "\x41\x42\x02\xff\x04\x00\xc8\x00\x03200\x00\x00"
    schedule: '@every 15s'
```

References:
- https://tomcat.apache.org/connectors-doc/ajp/ajpv13a.html
- https://github.com/alexmadon/ajpclient/blob/master/ajprequest.py
- https://github.com/hdanniel/ajpclient
