### ISSUE TITLE
Filebeat Fortinet log file input

### ISSUE THREAD

**Issue by fadjar340** [elastic/beats#23087]
**Filebeat Fortinet input log grok pattern:**

**Need improvement in Fortinet ingest node pipeline for log file input:**
In the pipeline: filebeat-7.10.0-fortinet-firewall-pipeline need modification in the Grok processor if use file log input as follow:
```
%{SYSLOG5424PRI}%{GREEDYDATA:syslog5424_sd}$|%{SYSLOGTIMESTAMP} %{SYSLOGHOST} %{GREEDYDATA:syslog5424_sd}$
```
This modification will hanlde SYSLOGHOST in the syslog file that not yet added into the pipeline.
Before add this, I have error in the error.message about grok pattern.

Below, my config `/etc/filebeat/modules.d/fortinet.yml`
```
# Module: fortinet
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.10/filebeat-module-fortinet.html
- module: fortinet
  firewall:
    enabled: true

    # Set which input to use between tcp, udp (default) or file.
    var.input: file

    # The interface to listen to syslog traffic. Defaults to
    # localhost. Set to 0.0.0.0 to bind to all available interfaces.
    #var.syslog_host: 0.0.0.0

    # The port to listen for syslog traffic. Defaults to 9004.
    #var.syslog_port: 9004

    # Set paths for the log files when file input is used.
    var.paths: ["/path/to/log/*.log"]

    # Toggle output of non-ECS fields (default true).
    var.rsa_fields: true

    # Set custom timezone offset.
    # "local" (default) for system timezone.
    # "+02:00" for GMT+02:00
    var.tz_offset: +07:00

  clientendpoint:
    enabled: false

    # Set which input to use between udp (default), tcp or file.
    var.input: file
    # var.syslog_host: localhost
    # var.syslog_port: 9510

    # Set paths for the log files when file input is used.
    # var.paths: 

    # Toggle output of non-ECS fields (default true).
    # var.rsa_fields: true

    # Set custom timezone offset.
    # "local" (default) for system timezone.
    # "+02:00" for GMT+02:00
    # var.tz_offset: +07:00

  fortimail:
    enabled: false

    # Set which input to use between udp (default), tcp or file.
    var.input: file
    # var.syslog_host: localhost
    # var.syslog_port: 9529

    # Set paths for the log files when file input is used.
    #var.paths:
  
    # Toggle output of non-ECS fields (default true).
    # var.rsa_fields: true

    # Set custom timezone offset.
    # "local" (default) for system timezone.
    # "+02:00" for GMT+02:00
    # var.tz_offset: +07:00

  fortimanager:
    enabled: false

    # Set which input to use between udp (default), tcp or file.
    var.input: file
    # var.syslog_host: localhost
    # var.syslog_port: 9530

    # Set paths for the log files when file input is used.
    # var.paths:
 
    # Toggle output of non-ECS fields (default true).
    var.rsa_fields: true

    # Set custom timezone offset.
    # "local" (default) for system timezone.
    # "+02:00" for GMT+02:00
    # var.tz_offset: +07:00
```

Regards,
Fadjar340
