### ISSUE TITLE
[DOC] [Filebeat] Add note that `co.elastic.logs/enabled` needs to be a string

### ISSUE THREAD

**Issue by a03nikki** [elastic/beats#23117]
I have seen multiple users struggle with this a few times now.  They do not know or forget that annotations need to be strings.  I tried to find this requirement in the actual Kubernetes (K8s) documentation but all I could find is answers in forums.  It is also not obvious to new K8s users that in this case the quotes around the `string` value are required unlike other values in the YAML.

[Filebeat Reference > Configure Filebeat > Autodiscover > Hints based autodiscover](https://www.elastic.co/guide/en/beats/filebeat/7.10/configuration-autodiscover-hints.html#_co_elastic_logsenabled)

> co.elastic.logs/enabled
>
> Filebeat gets logs from all containers by default, you can set this hint to false to ignore the output of the container. Filebeat won’t read or send logs from it. If default config is disabled, you can use this annotation to enable log retrieval only for containers with this set to true.

For example, if this (a `Boolean`) is used in the K8s manifest

```yaml
spec:
  podTemplate: 
    metadata: 
        co.elastic.logs/enabled: true
```

instead of this (a `string` with quotes)

```yaml
spec:
  podTemplate: 
    metadata: 
        co.elastic.logs/enabled: "true"
```

the following error message is generated

```
reflector.go:153] pkg/mod/k8s.io/client-go@v0.17.2/tools/cache/reflector.go:105: Failed to list *v1.Elasticsearch: v1.ElasticsearchList.Items: []v1.Elasticsearch: v1.Elasticsearch.Spec: v1.ElasticsearchSpec.NodeSets: []v1.NodeSet: v1.NodeSet.PodTemplate: v1.PodTemplateSpec.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|enabled":true},"labe|..., bigger context ...|adata":{"annotations":{"co.elastic.logs/enabled":true},"labels":{"stack-monitoring.elastic.co/type":|...
```

**Comment by exekias** [comment]
This looks like a bug to me, I wonder if we can do better to also allow boolean values, WDYT @ChrsMark ?

**Comment by ChrsMark** [comment]
It's not an issue on our side. I guess the provided error is given when try to deploy a k8s manifest right?

Annotation values must be strings.

They tried to fix this at https://github.com/kubernetes/kubernetes/issues/59113 so as to not silently ignore such annotations.


Let's see the following spec:
```yml
apiVersion: v1
kind: Pod
metadata:
  name: nats
  labels:
    role: main
  annotations:
    prometheus.io/scrape: true
spec:
  containers:
    - name: natsqueue
      image: nats
      command: ["/nats-server"]
      args: ["-m", "8222"]
      ports:
        - name: web
          containerPort: 8222
          protocol: TCP
```

This one will fail to be `kubectl apply`ied.

```console
kubectl create -f nats.yaml                                                                                                                               
service/nats created
error: unable to decode "nats.yaml": resource.metadataOnlyObject.ObjectMeta: v1.ObjectMeta.Annotations: ReadString: expects " or n, but found t, error found in #10 byte of ...|/scrape":true},"labe|..., bigger context ...|ic.metrics/module":"nats","prometheus.io/scrape":true},"labels":{"app":"name","role":"main","some":"|...
```

In this, I don't think it is sth we can handle on our side but maybe we can mention it in our docs so as to help our users. I can add this if we agree @exekias :)
