### ISSUE TITLE
[Filebeat Fortinet Module] Include more Grok Pattern

### ISSUE THREAD

**Issue by ylasri** [elastic/beats#23246]
The following UTM log exaple is not supported by the actual module of fortinet 
Can you please enhance the grok with the following example : FortiOS v6.0.11
Related to this [discuss](https://discuss.elastic.co/t/filebeat-fortinet-have-error-message/258261)

```
Dec 22 14:15:18 fg200d date=2020-12-22 time=14:15:17 devname="FG200D4Q26914264" devid="FG200D4Q26914264" logid="1059028704" type="utm" subtype="app-ctrl" eventtype="app-ctrl-all" level="information" vd="root" eventtime=1608639317 appid=16009 srcip=10.10.2.232 dstip=77.75.149.201 srcport=53234 dstport=80 srcintf="port1" srcintfrole="lan" dstintf="port2" dstintfrole="undefined" proto=6 service="HTTP" direction="outgoing" policyid=1 sessionid=380781585 applist="appcontrol_MTU" appcat="Update" app="MS.Windows.Update" action="pass" hostname="2.tlu.dl.delivery.mp.microsoft.com" incidentserialno=1278502712 url="/filestreamingservice/files/3b79c97b-09ea-41fb-92f1-4589f4e2f3c3?P1=1608639938&P2=402&P3=2&P4=OmtIZ1o%2bo5%2bKUyN9lEFm0SjQ4QJ5ebb76H%2fqxg2cJ7iOnOnTCDLJq4yu5i9r%2f9J8yXdoYwZNvQ63qSxQfVqg4A%3d%3d" msg="Update: MS.Windows.Update," apprisk="elevated"
```

**Comment by fadjar340** [comment]
Below are my procedures to make the ingestion pipe line works using input log file:

# Fortinet Configuration

## Filebeat
### Fortinet filebeat module

- Run command `filebeat modules enable fortinet`
- Change the file `/etc/filebeat/modules.d/fortinet.yml` as follow

```
# Module: fortinet
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.10/filebeat-module-fortinet.html

- module: fortinet
  firewall:
    enabled: true

    # Set which input to use between tcp, udp (default) or file.
    var.input: file

    # The interface to listen to syslog traffic. Defaults to
    # localhost. Set to 0.0.0.0 to bind to all available interfaces.
    #var.syslog_host: 0.0.0.0

    # The port to listen for syslog traffic. Defaults to 9004.
    #var.syslog_port: 9004

    # Set paths for the log files when file input is used.
    var.paths: ["/path/to/firewall/log/*.log"]

    # Toggle output of non-ECS fields (default true).
    var.rsa_fields: true

    # Set custom timezone offset.
    # "local" (default) for system timezone.
    # "+02:00" for GMT+02:00
    var.tz_offset: +07:00

  clientendpoint:
    enabled: true

    # Set which input to use between udp (default), tcp or file.
    var.input: file
    # var.syslog_host: localhost
    # var.syslog_port: 9510

    # Set paths for the log files when file input is used.
    var.paths: ["/path/to/clientendpoint/log/*.log"]

    # Toggle output of non-ECS fields (default true).
    var.rsa_fields: true

    # Set custom timezone offset.
    # "local" (default) for system timezone.
    # "+02:00" for GMT+02:00
    var.tz_offset: +07:00

  fortimail:
    enabled: true

    # Set which input to use between udp (default), tcp or file.
    var.input: file
    # var.syslog_host: localhost
    # var.syslog_port: 9529

    # Set paths for the log files when file input is used.
    #var.paths:
    var.paths: ["/path/to/fortimail/log/*.log"

    # Toggle output of non-ECS fields (default true).
    var.rsa_fields: true

    # Set custom timezone offset.
    # "local" (default) for system timezone.
    # "+02:00" for GMT+02:00
    var.tz_offset: +07:00

  fortimanager:
    enabled: true

    # Set which input to use between udp (default), tcp or file.
    var.input: file
    # var.syslog_host: localhost
    # var.syslog_port: 9530

    # Set paths for the log files when file input is used.
    # var.paths:
    var.paths: ["/datalog/192.100.254.68/*.log"]

    # Toggle output of non-ECS fields (default true).
    var.rsa_fields: true

    # Set custom timezone offset.
    # "local" (default) for system timezone.
    # "+02:00" for GMT+02:00
    var.tz_offset: +07:00
```


- Before start/restart filebeat, run this command:
   - `filebeat setup --pipelines --modules fortinet`

# Important
   - In `Kibana` - `Stack Management`, do some changes of `Ingest Node Pipelines` - `filebeat-7.10.0-fortinet-firewall-pipeline` 
   - Edit `filebeat-7.10.0-fortinet-firewall-pipeline` 
   - Find `Grok` in the second line below  `Set`, upper  `Key-value (KV)`
   - Select the `Grok`, `Manage` and `Edit`
   - Find `Patterns`
   - Change the patterns as follow:
   ```
   %{SYSLOG5424PRI}%{GREEDYDATA:syslog5424_sd}$|(?:%{SYSLOGTIMESTAMP:timestamp}|%{TIMESTAMP_ISO8601:timestamp8601}) (?:%{SYSLOGFACILITY} )?%{SYSLOGHOST:logsource}+(?: %{SYSLOGPROG}:|) %{GREEDYDATA:syslog5424_sd}$
   ```
   - Update the `Grok` processor
   - Find 2 `DATE` processor below `SET` upper `GSUB`
   - In the second `DATE` processor where: `Condition (optional)` as follow: `ctx.fortinet?.firewall?.tz == null`, fill the `Timezone (optional)` with your timezone, ie: `+07:00`, as time zone of the syslog server. This value will **Prevent the timestamp not following your timezone but Next 7 hours (in my case)**
   - Update the `Date` Processor
   - Save Pipeline at the bottom of the pipeline page

- Restart filebeat `systemctl restart filebeat`
- Check the index of the filebeat-* index with `Kibana` - `Observer` without any `error.message`
