### ISSUE TITLE
[Filebeat] Kubernetes autodiscover fails if filebeat cannot determine its node name

### ISSUE THREAD

**Issue by smacl** [elastic/beats#23400]
For confirmed bugs, please report:
- Version: 7.9.1
- Operating System: Centos 7 (we use a very lightly modified version of the public docker image)
- Discuss Forum URL: https://discuss.elastic.co/t/kubernetes-autodiscover-fails-if-filebeat-cannot-determine-its-node-name/260375
- Steps to Reproduce: Difficult to orchestrate, but seems to happen if the K8S API server is unavailable when filebeat queries its own pod data to determine the node it's running on.

If the API server is unavailable when filebeat tries to determine which node it's running on, filebeat might report an error like the following:

`{"level":"error","timestamp":"2021-01-05T09:10:12.114Z","logger":"autodiscover.pod","caller":"kubernetes/util.go:117","message":"kubernetes: Querying for pod failed with error: Get \"{API_SERVER}/api/v1/namespaces/monitoring/pods/filebeat-ds-j6tfs\": dial tcp: i/o timeout"}`

After this, no std stream logs are shipped.

Based on some admittedly naive code inspection (apologies if this is down the wrong path), it seems something like the following might be happening:
- The query against the API server fails in [DiscoverKubernetesNode](https://github.com/elastic/beats/blob/9c09f0a2a3f5f3a12703eef28c25f1022863746d/libbeat/common/kubernetes/util.go#L117), which returns "localhost" as a default
- The k8s autodiscover provider uses this as a watch filter (e.g., in [NewPodEventer](https://github.com/elastic/beats/blob/9c09f0a2a3f5f3a12703eef28c25f1022863746d/libbeat/autodiscover/providers/kubernetes/pod.go#L71)
- Since there is no "localhost" node, no events are received

Our autodiscover config is along the lines of:
```
filebeat.autodiscover:
  providers:
    - type: kubernetes
      templates:
        - condition:
             equals:
               kubernetes.container.name: "c1"
          config:
            - type: container
              paths:
                - "/var/lib/docker/containers/${data.kubernetes.container.id}/*.log"
              exclude_lines: ['^\x00']
              close_inactive: 1m
        - <a couple more conditions for other containers plus a general fallback>
```

AFAICT the only indication that filebeat is in this state is the error trace. For our use case, it would be preferable for file beat to either:
- retry the API server query rather than fall back to "localhost"
- shut down on this error so that it can retry on restart
