### ISSUE TITLE
[Metricbeat][windows/perfmon] Mixing counters together when group_measurements_by_instance is true

### ISSUE THREAD

**Issue by marc-gr** [elastic/beats#23489]
It seems that if the option `group_measurments_by_instance` is `true` the object is ignored when grouping, so it will group together all counters with ie. `instance: _Total` together regardless they belong to ie: `Processor Information` or `Memory`.

- Version: master
- Operating System: Windows (tested 10 and server 2019)
- Steps to Reproduce: 

If you want to test it you can do it with the following config:

```
metricbeat.modules:
  - module: windows
    metricsets: [perfmon]
    period: 10s
    perfmon.ignore_non_existent_counters: false
    perfmon.group_measurements_by_instance: true
    perfmon.queries:

    - object: "Processor Information"
      instance: "_Total"
      counters:
      - name: "% Processor Time"

    - object: "PhysicalDisk"
      instance: "_Total"
      counters:
      - name: "Current Disk Queue Length"
      - name: "Disk Read Bytes/sec"
      - name: "Disk Write Bytes/sec"

output.console:
  pretty: true
```

And see the difference when you toggle `perfmon.group_measurements_by_instance` back and forth.

`perfmon.group_measurements_by_instance:true`

```
{
  "@timestamp": "2021-01-13T15:27:09.161Z",
  "@metadata": {
    "beat": "metricbeat",
    "type": "_doc",
    "version": "8.0.0"
  },
  "event": {
    "dataset": "windows.perfmon",
    "module": "windows",
    "duration": 8027600
  },
  "metricset": {
    "name": "perfmon",
    "period": 10000
  },
  "service": {
    "type": "windows"
  },
  "windows": {
    "perfmon": {
      "metrics": {
        "disk_write_bytes_per_sec": 8381.215716061084,
        "%_processor_time": 0.10681524439283274,
        "current_disk_queue_length": 0,
        "disk_read_bytes_per_sec": 0
      },
      "object": "PhysicalDisk",
      "instance": "_Total"
    }
  },
  "host": {
    "name": "vagrant"
  },
  "agent": {
    "type": "metricbeat",
    "version": "8.0.0",
    "ephemeral_id": "e3c6902f-c539-4517-a0be-74d700709309",
    "id": "5159c10f-36f4-4489-9a9b-3a82cbd924d7",
    "name": "vagrant"
  },
  "ecs": {
    "version": "1.7.0"
  }
}
```

As you can see processor time appears in the physical disk metric.
