### ISSUE TITLE
Metrcibeat docker wsl2 zero diskio values

### ISSUE THREAD

**Issue by cdalexndr** [elastic/beats#23556]
ES document:
```
{
  "_index": "metricbeat-7.9.3-2020.12.29-000002",
  "_type": "_doc",
  "_id": "O3eJF3cBDXAhja8VYD1q",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2021-01-18T22:06:52.123Z",
    "ecs": {
      "version": "1.5.0"
    },
    "host": {
      "name": "ff2cdac595b4"
    },
    "agent": {
      "name": "ff2cdac595b4",
      "type": "metricbeat",
      "version": "7.9.3",
      "hostname": "ff2cdac595b4",
      "ephemeral_id": "5796531f-290a-474e-a1ff-106dc7eeed87",
      "id": "0d988131-c303-49c5-9e64-ed8caa5ed884"
    },
    "docker": {
      "diskio": {
        "read": {
          "ops": 0,
          "bytes": 0,
          "rate": 0,
          "service_time": 0,
          "wait_time": 0,
          "queued": 0
        },
        "write": {
          "bytes": 0,
          "rate": 0,
          "service_time": 0,
          "wait_time": 0,
          "queued": 0,
          "ops": 0
        },
        "summary": {
          "service_time": 0,
          "wait_time": 0,
          "queued": 0,
          "ops": 0,
          "bytes": 0,
          "rate": 0
        },
        "reads": 0,
        "writes": 0,
        "total": 0
      },
      "container": {
        "labels": {
          "org_opencontainers_image_title": "CentOS Base Image",
          "description": "Elastic APM Server",
          "com_docker_compose_config-hash": "101f14f034681e00c9bc4cd0c046a27e15364ed317d0bcaea8458ca50103528d",
          "org_label-schema_build-date": "2020-10-16T08:01:24Z",
          "com_docker_compose_project_working_dir": "C:\\Developer\\pse\\source\\build\\docker",
          "org_label-schema_name": "apm-server",
          "app": "apm",
          "com_docker_compose_project": "docker",
          "com_docker_compose_service": "apm",
          "org_label-schema_vcs-ref": "af7b123f289d79c34c9da11471803f457eafa5c0",
          "org_opencontainers_image_created": "2020-08-09 00:00:00+01:00",
          "org_opencontainers_image_licenses": "GPL-2.0-only",
          "org_opencontainers_image_vendor": "CentOS",
          "org_label-schema_license": "Elastic License",
          "org_label-schema_vendor": "Elastic",
          "org_label-schema_url": "https://www.elastic.co/solutions/apm",
          "org_label-schema_version": "7.9.3",
          "com_docker_compose_oneoff": "False",
          "org_label-schema_schema-version": "1.0",
          "com_docker_compose_container-number": "1",
          "com_docker_compose_project_config_files": "docker-compose.yml",
          "com_docker_compose_version": "1.27.4",
          "license": "Elastic License",
          "org_label-schema_vcs-url": "github.com/elastic/apm-server"
        }
      }
    },
    "event": {
      "dataset": "docker.diskio",
      "module": "docker",
      "duration": 2087011100
    },
    "metricset": {
      "period": 60000,
      "name": "diskio"
    },
    "service": {
      "address": "/var/run/docker.sock",
      "type": "docker"
    },
    "container": {
      "id": "c0dd6834e5207fd9dfa0fcdfcdbd3c4124ffbe7eeadb7a7b861e95076a3c753d",
      "name": "docker_apm_1",
      "image": {
        "name": "store/elastic/apm-server:7.9.3"
      },
      "runtime": "docker"
    }
  },
  "fields": {
    "@timestamp": [
      "2021-01-18T22:06:52.123Z"
    ]
  },
  "highlight": {
    "metricset.name": [
      "@kibana-highlighted-field@diskio@/kibana-highlighted-field@"
    ],
    "service.type": [
      "@kibana-highlighted-field@docker@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1611007612123
  ]
}
```

Docker compose service:
```
  metricbeat:
    image: store/elastic/metricbeat:7.9.3
    mem_limit: 64m
    depends_on:
      - kibana #to register dashboards
    volumes:
      - metricbeat-data:/usr/share/metricbeat/data
      - ./config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/hostfs:ro
    user: root #docker sock access
    cap_add:
      - SYS_PTRACE
      - DAC_READ_SEARCH
    labels:
      app: metricbeat
    command: --strict.perms=false -e -system.hostfs=/hostfs
```

metricbeat.yml:
```
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
metricbeat.modules:
  - module: docker
    metricsets: ["container", "cpu", "diskio", "memory", "info", "network"]
    cpu.metrics: ["normalized_percentages"]
    hosts: ["unix:///var/run/docker.sock"]
    period: 60s
  - module: system
    metricsets:
      - cpu
      - memory
      - network
      - uptime
      - diskio
      - fsstat
    period: 60s
    cpu.metrics: ["normalized_percentages"]

metricbeat.autodiscover:
  providers:
    - type: docker
```

For confirmed bugs, please report:
- Version: 7.9.3
- Operating System: Docker Windows 3.0.4 (51218)
- Discuss Forum URL:
- Steps to Reproduce:
