### ISSUE TITLE
Allow multiple module uses for auditbeat file_integrity configuration

### ISSUE THREAD

**Issue by ansell** [elastic/beats#23557]
**Describe the enhancement:**

I have had issues in the past with the flexibility of the `auditbeat` `file_integrity` module configuration. On one hand I want to monitor most changes under `/etc` and similar directories, but on another hand I also want to monitor a few very specific changes under `/home`.

Is there anyway of specifying a primary key for each `auditbeat` module configuration so that they don't conflict when there are multiple module configurations setup?

**Describe a specific use case for the enhancement or feature:**

I would like to benefit from the new detection rule, https://github.com/elastic/detection-rules/issues/753 , for alerting on changes to `~/.ssh/authorized_keys` files but currently I have prioritised monitoring everything under `/etc` because it doesn't seem like there is a way to do both at one time using `auditbeat`.

As an example, I would like the following in a single auditbeat configuration, but it doesn't seem to be supported right now:

```
    # Monitor system paths using exclusions
    - module: file_integrity
      name: "System file monitoring"
      paths:
      - /bin
      - /usr/bin
      - /sbin
      - /usr/sbin
      - /etc
      - /root

      exclude_files:
      - '(?i)\.sw[nop]$'
      - '~$'
      - '/\.git($|/)'

    # Monitor user directories using inclusions to only show .ssh file changes
    - module: file_integrity
      name: "User SSH configuration monitoring"
      paths:
      - /home

      include_files:
      - '/\.ssh($|/)'
```

**Comment by andrewkroh** [comment]
What's stopping you from using the above configuration today? The `name` options are ignored since those not valid config options, but the two  instances of the `file_integrity` module will both execute. You should see output from each instance.

```
2021-02-02T21:44:19.567Z	INFO	[file_integrity]	file_integrity/eventreader_fsnotify.go:95	Started fsnotify watcher	{"file_path": ["/home"], "recursive": false}
2021-02-02T21:44:19.567Z	INFO	[file_integrity]	file_integrity/scanner.go:116	File system scan completed	{"scanner_id": 1, "took": 179136, "file_count": 1, "total_bytes": 4096, "bytes_per_sec": 22865309.03894248, "files_per_sec": 5582.350839585566}
2021-02-02T21:44:25.247Z	INFO	[file_integrity]	file_integrity/eventreader_fsnotify.go:95	Started fsnotify watcher	{"file_path": ["/etc", "/root", "/usr/bin", "/usr/sbin"], "recursive": false}
2021-02-02T21:44:26.175Z	INFO	[file_integrity]	file_integrity/scanner.go:116	File system scan completed	{"scanner_id": 2, "took": 927701351, "file_count": 727, "total_bytes": 48755765, "bytes_per_sec": 52555453.26892598, "files_per_sec": 783.657369062083}
```

**Comment by ansell** [comment]
@andrewkroh I am really embarrassed now! The issue with my test system was that I had not copied the `recursive: true` setting from the production config, so that it didn't detect on files inside of the directory. Closing this as working with the following configuration:

```
    # Monitor system paths using exclusions
    - module: file_integrity
      paths:
      - /bin
      - /usr/bin
      - /sbin
      - /usr/sbin
      - /etc
      - /root

      exclude_files:
      - '(?i)\.sw[nop]$'
      - '~$'
      - '/\.git($|/)'

      recursive: true

    # Monitor user directories using inclusions to only show .ssh file changes
    - module: file_integrity
      paths:
      - /home

      include_files:
      - '/\.ssh($|/)'

      recursive: true
```
