### ISSUE TITLE
Elasticsearch server fileset processes logs of other metricsets

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#23583]
Default paths configuration in the Elasticsearch `server` metricset is too broad, so it harvests files that should be harvested by other metricsets, resulting in incorrectly parsed logs.

Default paths in the `server` metricset include patterns like `/var/log/elasticsearch/*.log`.
Logs that should be managed by other filesets match this pattern, e.g. the GC one: `/var/log/elasticsearch/gc.log`, or the deprecation one: `/var/log/elasticsearch/some-name_deprecation.log`.
So it can happen that the `server` fileset harvests these files, selecting for them an incorrect pipeline.

---
While this is fixed, a possible workaround is to set the paths in the `server` metricset to the actual server logs, something like this:
```
- module: elasticsearch
  server:
    enabled: true
    var.paths:
      - '/var/log/elasticsearch/some-name.log'
      - '/var/log/elasticsearch/some-name.log.*'
  ...
```

Or for JSON logs:
```
- module: elasticsearch
  server:
    enabled: true
    var.paths:
      - '/var/log/elasticsearch/*_server.json'
      - '/var/log/elasticsearch/*_server.json.*'
  ...
```
---
* https://github.com/elastic/beats/issues/16540 can be related
