### ISSUE TITLE
[matcher]is there anyway to change the default log_path for add_kubernetes_metadata matcher?

### ISSUE THREAD

**Issue by metadeng** [elastic/beats#23606]
**Describe the enhancement:**
filebeat version: 7.9
OS: centos 8.2
kubernetes: 1.18.3

when i try to change the default log_path for add_kubernetes_metadata matcher as i change the rootdir for docker, and there is nothing to match the right path for current matcher, as except，there is anyway that i can change the docker's rootdir as well as the path that i configured in filebeat.yml?
**Describe a specific use case for the enhancement or feature:**
some feature may cause us to change the rootdir path for docker, therefor, hope that filebeat support us to custom the input log path for docker.

**Comment by tetianakravchenko** [comment]
Hi @metadeng, here was added some clarifications and documentation on this processor matcher - https://github.com/elastic/beats/pull/28868. If I correctly understood your use case, with this change you should be able to redefine `log_path`. Note that: value defined as a `logs_path` of the matcher must be a subdirectory
of directory defined as a `paths` of filebeat input, example:
```
filebeat.inputs:
    - type: container
      paths:
        - /var/lib/custom/path/*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/lib/custom/path/"
```
