### ISSUE TITLE
Cannot use K8S de-dot-ed labels in processors

### ISSUE THREAD

**Issue by sherifabdlnaby** [elastic/beats#23643]
For confirmed bugs, please report:
- Version: 7.10.1
- Operating System: Official Docker Image

Using this processor is ineffective.
```
      - copy_fields:
          when.has_fields: [ "kubernetes.labels.app_kubernetes_io/name" ]
          fields:
            - from: "kubernetes.labels.app_kubernetes_io/name"
              to: "@metadata.application"
```

Processors can't read "kubernetes.labels.app_kubernetes_io/name" and takes no effects.
Omitting the `when` condition is not effective either. The processor still does not copy values.

It works with any label that is not dedotted.
