### ISSUE TITLE
Hint based autodiscover hosts label not working

### ISSUE THREAD

**Issue by cdalexndr** [elastic/beats#23642]
What is the `co.elastic.metrics/hosts` label format?

1. http://host:81
2. "http://host:81"
3. "\"http://host:81\""
3. "[http://host:81]"
4. "[\"http://host:81\"]"

An example should be added to [documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html#_co_elastic_metricshosts).

I cannot get it working in a `docker-compose.yml` service:
```
services:
  entry:
    labels:
      co.elastic.metrics/module: nginx
      co.elastic.metrics/metricsets: stubstatus
      co.elastic.metrics/hosts: http://entry:81
```
Adding configuration to `metricbeat.yml` works.

For confirmed bugs, please report:
- Version: 7.10.1
- Operating System: docker win
- Discuss Forum URL:
- Steps to Reproduce:
