### ISSUE TITLE
Not possible to use path in logstash URL

### ISSUE THREAD

**Issue by eeijlar** [elastic/beats#23757]
I am trying to ship files from a filebeat instance, to logstash running inside kubernetes. Traffic into kubernetes is routed using the gloo service. Gloo matches on the incoming URL, so if I want to reach the logstash service I would use:

`10.1.103.92:30090/logstash`

Unfortunately, I cannot use this format in the `output.logstash` section of filebeat:

```
output.logstash:
  enabled: true
# bulk_max_size: 5000

  # The Logstash hosts
  hosts: ["10.1.103.92:30090/logstash"]
```
I get the following error:

```
2021-01-28T13:04:37.534Z ERROR [publisher_pipeline_output] pipeline/output.go:154 Failed to connect to backoff(async(tcp://10.1.103.92:30090/logstash/)): dial tcp: lookup tcp/30090/logstash/: Servname not supported for ai_socktype
```
Is there any way to specify a path when constructing the logstash url?

I have also posted on the elastic discussion [board](https://discuss.elastic.co/t/how-to-specify-subpath-to-logstash-host-in-filebeat-yml/262501)
