### ISSUE TITLE
use_types and rate_counters not working in kubernetes hints

### ISSUE THREAD

**Issue by steffen-geissinger-by** [elastic/beats#23852]
We are running many Services on our Kubernetes Cluster (AKS 1.8.10) and they are exposing Prometheus metrics at `/metrics`.

To scrape these metrics we use Kubernetes Annotations:

```
apiVersion: apps/v1
kind: Deployment
...
spec:
 ...
  template:
    metadata:
      annotations:
        co.elastic.metrics/hosts: ${data.host}:8080
        co.elastic.metrics/metrics_path: /metrics
        co.elastic.metrics/module: prometheus
        co.elastic.metrics/period: 10s
        co.elastic.metrics/use_types: "true"
        co.elastic.metrics/rate_counters: "true"
```

The metrics are scraped from the service, but the options `use_types` and `rate_counters` are ignored. We get the same amount of documents with and without these options.

We removed the annotations and changed our metricbeat configuration to:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-config
  labels:
    k8s-app: metricbeat
data:
  metricbeat.yml: |-
    metricbeat.config.modules:
      # Mounted `metricbeat-daemonset-modules` configmap:
      path: ${path.config}/modules.d/*.yml
      # Reload module configs as they change:
      reload.enabled: true

    metricbeat.autodiscover:
      providers:
        - type: kubernetes
          scope: cluster
          node: ${NODE_NAME}
          unique: true
          templates:
            - config:
                - module: prometheus
                  period: 10s
                  metricsets:
                  - "collector"
                  hosts:
                  - "<service>:8080"
                  use_types: true
                  rate_counters: true
                  metrics_path: /metrics
```

Now we receive a lower number of documents with the optimised format.

Metricbeat version: 7.10.1

**Comment by stephan-erb-by** [comment]
@andreadelrio @exekias @ChrsMark is adding support for `use_types` and `rate_counters` planned for K8s annotations at some point in the future?

In the meantime, could this be achieved using `co.elastic.metrics/raw` as another workaround to the one Steffen proposed above?

**Comment by stephan-erb-by** [comment]
In case anyone runs into this, here is a suitable workaround using https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-advanced.html

        - type: kubernetes
          node: ${NODE_NAME}
          hints:
            enabled: true
            default_config: {}
          # Post-process Prometheus config to reduce the number of ingested documents
          appenders:
            - type: config
              config:
                use_types: true
                rate_counters: true

**Comment by ChrsMark** [comment]
@stephan-erb-by hey and sorry for the late reply, it looks like this one got lost in the inbox 😞 .

Great that you have came up with a workaround using appenders :). Using `co.elastic.metrics/raw` should work too. `default_config` is the config that all containers/pods will fall back if there are no hints provided (it is used for container's logs for example to get the default log path if there is no module provided via hints), so I don't think it will help here.

I'm not aware of any plans to support these specific configs as hints, but we could consider it if we see value on this. @exekias @mukeshelastic could you please evaluate this?

**Comment by JonPaz** [comment]
@stephan-erb-by , thanks for your pointers.  I've tried applying it to my solution but no joy, do you know if it is possible to delve in any further to see if these settings are actually being applied?

Many thanks!

**Comment by stephan-erb-by** [comment]
@JonPaz so there are probably better ways to do that, but for debugging I used the following:   
```
  - type: kubernetes
      node: ${NODE_NAME}
      hints:
        enabled: true
        default_config: {}
      # Post-process Prometheus config to reduce the number of ingested documents
      appenders:
        - type: config
          config:
            use_types: true
            rate_counters: true
            # Attache a field to each metric that I can easily filter for all documents that used my appended/updated config
            fields:
              new_prom_format: true
```
