### ISSUE TITLE
Insufficient memory creating DNS sniffer

### ISSUE THREAD

**Issue by inqueue** [elastic/beats#23913]
- Version: 7.9.3
- Operating System: RHEL 6, kernel `2.6.32-754.29.1.el6.x86_64`
- Steps to Reproduce: Attempt to start auditbeat on RHEL 6 with DNS monitoring in the socket module enabled.

<details><summary><strong>Sample Configuration</strong></summary>

```
auditbeat.modules:
    - module: auditd
      audit_rule_files: [ '${path.config}/audit.rules.d/*.conf' ]
      audit_rules: |
    - module: file_integrity
      paths:
      - /bin
      - /usr/bin
      - /sbin
      - /usr/sbin
      - /etc
    - module: system
      datasets:
        - host    # General host information, e.g. uptime, IPs
        - login   # User logins, logouts, and system boots.
        - package # Installed, updated, and removed packages
        - process # Started and stopped processes
        - socket  # Opened and closed sockets
        - user    # User information
      state.period: 12h
      user.detect_password_changes: true
      login.wtmp_file_pattern: /var/log/wtmp*
      login.btmp_file_pattern: /var/log/btmp*
```
</details>

```
2020-08-27T14:56:36.091-0400 ERROR instance/beat.go:958 Exiting: 1 error: unable to create DNS sniffer: failed creating af_packet sniffer: setsockopt packet_rx_ring: cannot allocate memory
Exiting: 1 error: unable to create DNS sniffer: failed creating af_packet sniffer: setsockopt packet_rx_ring: cannot allocate memory
```

### Workaround

- Disable DNS monitoring `socket.dns.enabled: false`, or
- Try `socket.dns.af_packet.snaplen: 512`
