### ISSUE TITLE
Filebeat not closing deleted/rotated files (when output broken)

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/beats#2395]
RHEL 6.7
Filebeat 1.2.3

```
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    -
      paths:
        - /tmp/logs/tester*.log
      input_type: log
      ignore_older: 168h
      close_older: 5m
      document_type: bw
      timeout: 5s
      backoff: 5s
  registry_file: /tmp/filebeat/registry

output:
  logstash:
    hosts: ["unknownhost:5045"]
```

The following utility will just generate logs and rotate them out:  [loggenerator.zip](https://github.com/elastic/beats/files/439910/loggenerator.zip)

To reproduce:
1. `./filebeat -c above-config.yml`
2. `java -Dcom.bmo.elk.loggenerator.logcount=1000000 -Dcom.bmo.elk.loggenerator.sleeptime=2 -jar loggenerator.jar`
3. `watch "lsof | grep filebeat | grep deleted "`

```
Every 2.0s: lsof | grep filebeat | grep deleted                                                                                                              Fri Aug 26 14:48:01 2016

filebeat   9179      root   13r      REG              253,0 20971546    3014698 /tmp/logs/tester11.log.4 (deleted)
filebeat   9179      root   14u      REG              253,0 20971546    3014695 /tmp/logs/tester11.log.4 (deleted)
filebeat   9179      root   15r      REG              253,0 20971562    3014699 /tmp/logs/tester11.log.4 (deleted)
filebeat   9179      root   16u      REG              253,0 20971529    3014700 /tmp/logs/tester11.log.4 (deleted)
```

This only seems to happen when the output is broken.  Behaviour is normal when changed to a working output:

```
output:
  file:
    path: "/tmp/filebeat"
    filename: filebeat
    rotate_every_kb: 1000
    number_of_files: 7
```
