### ISSUE TITLE
docker metricbeat 7.10.2 AWS Module - EBS and ELB configuration with access_key_id yields failed startup

### ISSUE THREAD

**Issue by richardim** [elastic/beats#24073]
When enabling the AWS module, the configurations for access key and secret access key only works for some metricsets. ELB and EBS configuration causes and error:

`2021-02-16T19:23:50.555Z	ERROR	instance/beat.go:956	Exiting: 1 error: module factory for module ‘aws’ failed while creating light metricset ‘aws/ebs’: missing field accessing ‘access_key_id’ (source:‘metricbeat.yml’)`

`- module: aws`
`  period: 300s`
`  metricsets:`
`    - ebs`
`  access_key_id: ‘${AWS_ACCESS_KEY_ID}:“”’`
`  secret_access_key: ‘${AWS_SECRET_ACCESS_KEY}:“”’`
`  regions: us-east-1`
`  enabled: true`

- Version: 7.10.2
- Operating System: 
- Discuss Forum URL:
- Steps to Reproduce:

**Comment by kaiyan-sheng** [comment]
This seems to be a formatting issue still with the quotes around `access_key_id` and `secret_access_key`. The config below works for me:
```
- module: aws
  period: 5m
  access_key_id: '${AWS_ACCESS_KEY_ID:""}'
  secret_access_key: '${AWS_SECRET_ACCESS_KEY:""}'
  metricsets:
    - ebs
```

**Comment by kaiyan-sheng** [comment]
If user uses `credential_profile_name` and `shared_credential_file` for passing credentials, the credential file needs to be provided via a volume mount:

```
docker run -d --name=metricbeat --user=root --volume="$(pwd)/metricbeat.aws.yml:/usr/share/metricbeat/metricbeat.yml:ro" --volume="/Users/kaiyansheng/.aws/credentials:/usr/share/metricbeat/credentials:ro" docker.elastic.co/beats/metricbeat:7.11.1 metricbeat -e -E cloud.auth=elastic:1234 -E cloud.id=test-awsfargate:1234
```

A sample `metricbeat.aws.yml` can be:
```
metricbeat.modules:
- module: aws
  period: 5m
  credential_profile_name: elastic-beats
  shared_credential_file: /usr/share/metricbeat/credentials
  metricsets:
    - ebs
```

**Comment by kaiyan-sheng** [comment]
@richardim For your use case with passing environment variables, here is an example:
```
docker run -e AWS_ACCESS_KEY_ID=abcd -e AWS_SECRET_ACCESS_KEY=abcd -d --name=metricbeat --user=root --volume="$(pwd)/metricbeat.aws.yml:/usr/share/metricbeat/metricbeat.yml:ro" docker.elastic.co/beats/metricbeat:7.11.1 metricbeat -e -E cloud.auth=elastic:1234 -E cloud.id=test-aws:1234
```
Sample `metricbeat.aws.yml` looks like:
```
metricbeat.modules:
- module: aws
  period: 5m
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  session_token: ${AWS_SESSION_TOKEN}
  metricsets:
    - ebs
```
You can also use a file to store all environment variables and then pass it with `--env-file my-env.txt` in your docker run command.
