### ISSUE TITLE
Template not loading in 1.2.3 using documented config

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#2420]
- Version: 1.2.3
- Steps to reproduce: Use config found at https://www.elastic.co/guide/en/beats/topbeat/current/topbeat-template.html

The documentation recommends:

```
output:
  elasticsearch:
    hosts: ["localhost:9200"]

    # A template is used to set the mapping in Elasticsearch
    # By default template loading is disabled and no template is loaded.
    # These settings can be adjusted to load your own template or overwrite existing ones
    template:

      # Template name. By default the template name is topbeat.
      #name: "topbeat"

      # Path to template file
      path: "topbeat.template.json"

      # Overwrite existing template
      #overwrite: false
```

But you must uncomment `name: topbeat` to enable loading because the code checks that [name is not empty](https://github.com/elastic/beats/blob/1.2/libbeat/outputs/elasticsearch/output.go#L159).

```
output:
  elasticsearch:
    hosts: ["localhost:9200"]

    # A template is used to set the mapping in Elasticsearch
    # By default template loading is disabled and no template is loaded.
    # These settings can be adjusted to load your own template or overwrite existing ones
    template:

      # Template name. By default the template name is topbeat.
      name: "topbeat"

      # Path to template file
      path: "topbeat.template.json"

      # Overwrite existing template
      #overwrite: false
```

The comment "By default the template name is topbeat" is wrong since the default value is actually an empty string.
