### ISSUE TITLE
Filebeat httpjson v2 input should set Content-Type header to match to specified encoder

### ISSUE THREAD

**Issue by dcode** [elastic/beats#24331]
Filebeat should match the `Content-Type` header to the encoding selected.

Steps to reproduce: 

1. Configure Filebeat to use `httpjson` v2 input (example configuration below)
2. Try to specify form-encoded parameters
3. Run the configuration with DEBUG logging
4. Observe that the `Content-Type` is still set to `application/json`.

-------

**Example**

Minimum viable config:

```yaml
filebeat.inputs:
  - type: httpjson
    config_version: "2"
    interval: 1m
    enabled: true

    request.method: POST
    request.url: https://mb-api.abuse.ch/api/v1/
    request.encode_as: application/x-www-form-urlencoded

    request.transforms:
    - set:
        target: url.params.query
        value: get_recent
    - set:
        target: url.params.selector
        value: time

    response.split:
      target: body.data

output.console:
  enabled: true

```

Produces the following DEBUG output indicating `Content-Type: application/json` when run as ```./filebeat run -e --d 'input.httpjson-stateless' --once  -c test.yml```

```
2021-03-03T16:44:49.442-0600	DEBUG	[input.httpjson-stateless]	v2/request.go:77	new request: v2.transformable{"header":http.Header{"Accept":[]string{"application/json"}, "Content-Type":[]string{"application/json"}, "User-Agent":[]string{"Elastic-Filebeat/8.0.0 (darwin; amd64; 08602f026af8d120a9e16a5b58fbd38cda07b94d; 2021-03-03 22:16:58 +0000 UTC)"}}, "url":url.URL{Scheme:"https", Opaque:"", User:(*url.Userinfo)(nil), Host:"mb-api.abuse.ch", Path:"/api/v1/", RawPath:"", ForceQuery:false, RawQuery:"query=get_recent&selector=time", Fragment:"", RawFragment:""}}	{"input_url": "https://mb-api.abuse.ch/api/v1/"}
```

---
The workaround is to specify the header directly in a request transform

```yaml
filebeat.inputs:
  - type: httpjson
    config_version: "2"
    interval: 1m
    enabled: true

    request.method: POST
    request.url: https://mb-api.abuse.ch/api/v1/
    request.encode_as: application/x-www-form-urlencoded

    request.transforms:
    - set:
        target: header.Content-Type
        value: application/x-www-form-urlencoded
    - set:
        target: url.params.query
        value: get_recent
    - set:
        target: url.params.selector
        value: time

    response.split:
      target: body.data

output.console:
  enabled: true

```
