### ISSUE TITLE
vSphere module - Percentage for CPU & Mem

### ISSUE THREAD

**Issue by PhilipWhiteside** [elastic/beats#24401]
**Describe the enhancement:**

Provide percentage `%` usage value for vSphere host CPU & Memory.

**Describe a specific use case for the enhancement or feature:**

To create Kibana Alerts based on usage exceeding a percentage of the nodes capability. We have multiple clusters for different workloads, so setting a fixed GHz/byte value of free would not work for them all. Everywhere I have seen has at minimum 2 types of clusters, 1 for management, 1 for workload. Many have multiple workload types, such as SQL, VDI, VSI, etc. 

**Other**

The values to calculate the percentage are already known (`usage`/`capacity`), it just has to be calculated and passed into elastic, no additional API work to vSphere is needed. This has been provided for datastore utilisation here https://github.com/elastic/beats/blob/d38a5d0b11ed0b73aebfc98f5c1a286dfa81ce55/metricbeat/module/vsphere/datastore/datastore.go#L114-L117

**Comment by BenB196** [comment]
In case anyone comes across this issue and wants to implement a temporary fix, you can add the following processors to add these metrics:

`vsphere.host.cpu.used.pct`:

```yaml
processors:
  - if:
      and:
      - has_fields:
        - vsphere.host.cpu.total.mhz
        - vsphere.host.cpu.used.mhz
      - equals:
          event.dataset: vsphere.host
  then:
  - script:
      lang: javascript
      source: >
        function process(event) {
          var cpuTotal = event.Get('vsphere.host.cpu.total.mhz');
          var cpuTotalInt = parseInt(cpuTotal);
          var cpuUsed = event.Get('vsphere.host.cpu.used.mhz');
          var cpuUsedInt = parseInt(cpuUsed);
          var cpuUsedPercentBase1 = cpuUsedInt / cpuTotalInt;
          var old = event.Put('vsphere.host.cpu.used.pct', parseFloat(cpuUsedPercentBase1.toFixed(3)));
        }
```

`vsphere.host.memory.used.pct`:

```yaml
processors:
  - if:
      and:
      - has_fields:
        - vsphere.host.memory.total.bytes
        - vsphere.host.memory.used.bytes
      - equals:
          event.dataset: vsphere.host
  then:
  - script:
      lang: javascript
      source: >
        function process(event) {
          var memoryTotal = event.Get('vsphere.host.memory.total.bytes');
          var memoryTotalInt = parseInt(memoryTotal);
          var memoryUsed = event.Get('vsphere.host.memory.used.bytes');
          var memoryUsedInt = parseInt(memoryUsed);
          var memoryUsedPercentBase1 = memoryUsedInt / memoryTotalInt;
          var old = event.Put('vsphere.host.memory.used.pct', parseFloat(memoryUsedPercentBase1.toFixed(3)));
        }
```

`vsphere.virtualmachine.memory.used.guest.pct`:

```yaml
processors:
  - if:
      and:
      - has_fields:
        - vsphere.virtualmachine.memory.total.guest.bytes
        - vsphere.virtualmachine.memory.used.guest.bytes
      - equals:
          event.dataset: vsphere.virtualmachine
  then:
  - script:
      lang: javascript
      source: >
        function process(event) {
          var vmMemoryGuestTotal = event.Get('vsphere.virtualmachine.memory.total.guest.bytes');
          var vmMemoryGuestTotalInt = parseInt(vmMemoryGuestTotal);
          var vmMemoryGuestUsed = event.Get('vsphere.virtualmachine.memory.used.guest.bytes');
          var vmMemoryGuestUsedInt = parseInt(vmMemoryGuestUsed);
          var vmMemoryGuestUsedPercentBase1 = vmMemoryGuestUsedInt / vmMemoryGuestTotalInt;
          var old = event.Put('vsphere.virtualmachine.memory.used.guest.pct', parseFloat(vmMemoryGuestUsedPercentBase1.toFixed(3)));
        }
```

**Note:** While the `parseFloat()` should produce a float value instead of a string, and the dynamic field should work to detect this, it is possible for some issue where the field could become incorrectly mapped as a `keyword` or `long`. I'd recommend adding static mappings to your index/index templates before adding the fields.
