### ISSUE TITLE
o365 Module + Logstash/kafka

### ISSUE THREAD

**Issue by toddferg** [elastic/beats#24478]
- Version: 7.11.0
- Operating System: na
- Steps to Reproduce: 
Right now when using the o365 module, and using the message field (which is for the email subject etc, and sending the data to logstash to then be sent to elasticsearch logstash grabs the entire message field as the payload, and does not get the information from the email. 

Right now the workaround is to rename the field from message to subject and that works currently.  

Can this be fixed in the module to potentially utilize a different field?

**Comment by inqueue** [comment]
The bug is here: https://github.com/elastic/beats/blob/1d9cced55410003f5d0b4594ff5471d15a4e2900/x-pack/filebeat/module/o365/audit/config/pipeline.js#L295.

The best workaround I have found is to edit `pipeline.js` in the Filebeat installation directory replacing `message` with something better like `subject` since the field actually represents the subject field of an email and not the message-- it's a two for one win since you also avoid conflicts with Logstash.

`./module/o365/audit/config/pipeline.js` modifications:

```
{from: 'o365audit.ExchangeMetaData.Subject', to: 'message'}
```

to

```
{from: 'o365audit.ExchangeMetaData.Subject', to: 'subject'}
```

I believe this is a bug since current behavior is in direct conflict with Logstash.

**Comment by legoguy1000** [comment]
I would just remove the line `{from: 'o365audit.ExchangeMetaData.Subject', to: 'subject'}` all together since subject isn't part of the ECS schema.

**Comment by legoguy1000** [comment]
I can create the PR is thats the way to go.

**Comment by andrewkroh** [comment]
Hi @toddferg, @inqueue, I think I don't understand the problem this is causing with Logstash users. Could you help clarify that part for me. It's pretty common for Beats to parse incoming structured data then set the `message` field to a value extracted from the data while also retaining all the other fields from the structured data. JSON log parsing is probably the most common example. So does this cause problems for Logstash users?

**Comment by legoguy1000** [comment]
I previously had similar issues where logstash uses `message` as the default key for incoming data like from the kafka input. but after doing some testing with logstash using the below config 
```
input {
    stdin {
            codec => json
    }
}

output {
  stdout { codec => json }
}
```
In this case if the data is proper JSON and can be parsed, the data seems to have no issue with a `message` field.
```
{
          "host" => "de1fe82d49ca",
      "@version" => "1",
       "flow_id" => 1805461738637437,
       "message" => {
         "pkts_toclient" => 5,
        "bytes_toserver" => 496,
               "message" => "asdfasdfasfdasdf",
                 "start" => "2021-01-22T23:28:38.673917+0100",
        "bytes_toclient" => 876,
         "pkts_toserver" => 6
    },
        "src_ip" => "52.222.141.99",
    "@timestamp" => 2021-03-25T13:52:52.999Z,
       "dest_ip" => "10.31.64.240"
}
```
but if it doesn't, the input data becomes the message field.
```
{
      "@version" => "1",
          "host" => "de1fe82d49ca",
          "tags" => [
        [0] "_jsonparsefailure"
    ],
       "message" => "gsdfgsdfgsdfgsdfgsdfg",
    "@timestamp" => 2021-03-25T13:56:12.722Z
}
```
so I think its very situational. But since Filebeat is sending structured data and not a string, so I wonder if they are using something in the middle between Filebeat and Logstash like Kafka??

**Comment by legoguy1000** [comment]
I converted the PR to draft while we figure this out.

**Comment by inqueue** [comment]
From the report @toddferg and I were working, the flow is Filebeat -> Logstash.

<details><summary><strong>filebeat.yml</strong></summary>

```
output.logstash:
  hosts: ["localhost:50600"]

  ssl.certificate_authorities: ["/opt/path/to/ca.pem"]

  ssl.verification_mode: none

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~



logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  permissions: 0644
```
</details>

<details><summary><strong>o365.yml</strong></summary>

```
- module: o365
  audit:
    enabled: true

    var.application_id: "XXXXXX"

    var.tenants:
     - id: "XXXX"
       name: "XXXXX"

    var.content_type:
     - "DLP.All"


    var.client_secret: "XXXXXX"


    input:
      processors:
        - add_fields:
            target: ''
            fields:
              device_type: o365
        - rename:   # original user workaround
            fields:
              - from: "message"
                to: "subject"
```
</details>

<details><summary><strong>filebeat2file.conf</strong></summary>

```
input {
  beats {
    port => 50600
    ssl => true
    ssl_certificate => "/opt/path/to/ssl_cert"
    ssl_key => "/opt/path/to/ssl_key"
  }
}
filter {
  mutate {
    add_field => {"device_ip" => "%{[@metadata][ip_address]}"}
    copy => { "@timestamp" => "time_collect" }
    add_field => { "[@metadata][tstamp]" => "%{+YYYY-MM-dd_HH}" }
    add_field => { "log_collector" => "collector_host" }
    rename => {"message" => "msg"}
  }
  prune {
    whitelist_names => [ "device_ip", "time_collect", "log_collector", "device_type", "msg", "device_class", "device_subclass" ]
        remove_field => ["@timestamp"]
  }
}
output {
  file {
    path => "/data1/input/%{device_type}/%{device_ip}/%{device_type}_%{[@metadata][tstamp]}.log"
  }
}
```
</details>

Please let me know if more information is needed from the source or the report.

**Comment by andrewkroh** [comment]
Haven't tested anything, but I suspect that by setting `input.processors` in the module config that this completely disables all of the processing that's built into the module because the module also sets `processors`. If adding fields is needed then maybe setting `input.fields` and `input.fields_under_root` would work, like:

```
input:
  fields:
    device_type: o365
  fields_under_root: true
```

**Comment by legoguy1000** [comment]
> Haven't tested anything, but I suspect that by setting `input.processors` in the module config that this completely disables all of the processing that's built into the module because the module also sets `processors`. If adding fields is needed then maybe setting `input.fields` and `input.fields_under_root` would work, like:
> 
> ```
> input:
>   fields:
>     device_type: o365
>   fields_under_root: true
> ```

On another project we are using the suricata and zeek modules and I have the below in the `filebeat.yml` affecting all data from the Filebeat node instead of under the `<module>.input.processors` and we don't have any issues with the native module processors being disabled. So maybe it adding processors in the different places has different affects??
```
    processors:
      - add_fields:
          target: observer
          fields:
            hostname: ${NODE_NAME}
```
