### ISSUE TITLE
Okta Integration in Filebeat 7.11.1 is Broken - Works in 7.10.2

### ISSUE THREAD

**Issue by mrebeschini** [elastic/beats#24479]
- Version: 7.11.1
- Operating System: Amazon Linux 2
- Steps to Reproduce: 

1. Enable the Okta module in Filebeat. Configuration file looks like the following (API key was redacted):
```
- module: okta
  system:
    enabled: true
    # You must configure the URL with your Okta domain and provide an
    # API token to access the logs API.
    var.url: https://rbx.okta.com/api/v1/logs
    var.api_key: 'xxx'
```
We have verified that the API key is correctly working using a curl command like the following:
```
curl -v -X GET -H "Accept: application/json" -H "Content-Type: application/json" -H "Authorization: SSWS xxxx" https://rbx.okta.com/api/v1/logs
```

2. We get the following error when running `filebeat -e`:
```
2021-03-10T17:51:04.557Z	ERROR	[input.httpjson-cursor]	v2/input.go:129	Error while processing http request: failed to execute http client.Do: failed to execute http client.Do: http request was unsuccessful with a status code 400	{"source": "https://rbx.okta.com/api/v1/logs", "url": "https://rbx.okta.com/api/v1/logs"}
```
We have verified that the issue does not existing using Filebeat 7.10.2.

CC: @untergeek
