### ISSUE TITLE
Validate/Publish Integration with Sophos Central

### ISSUE THREAD

**Issue by mrebeschini** [elastic/beats#24516]
Sophos Central is the Unified Console for managing hosted Sophos products. All the prospects I worked with that wanted to evaluate the Sophos data integration are using Sophos Central, showing that this is a popular log source.

Sophos published [Sophos Central SIEM Integration](https://github.com/sophos/Sophos-Central-SIEM-Integration), a Python scripts that pulls logs using the Sophos Central API. Logs are stored locally using JSON, as a supported format. Information the JSON schema used by Sophos and sample log messages can be found in this [Sophos Support KB article](https://support.sophos.com/support/s/article/KB-000038307?language=en_US).

As part of a POC with a prospect, we developed the integration with Sophos Central, based on an ingest pipeline. We configured Sophos SIEM Integration as follows in the `config.ini` file (API key and header have been redacted):

```
[login]
# API Access URL + Headers
# API token setup steps: https://community.sophos.com/kb/en-us/125169
token_info = url: https://api5.central.sophos.com/gateway, x-api-key: XXXX, Authorization: Basic YYYYY


# format can be json, cef or keyvalue
format = json

# filename can be syslog, stdout, any custom filename
filename = result.txt

# endpoint can be event, alert or all
endpoint = all

# syslog properties
# for remote address use <remoteServerIp>:<port>, for e.g. 192.1.2.3:514
# for linux local systems use /dev/log
# for MAC OSX use /var/run/syslog
address = /var/run/syslog
facility = daemon
socktype = udp
```
Running `python siem.py` will cause the Sophos logs to be downloaded using the API. 

We configured Filebeat as follows:
```
filebeat.inputs:

# Each - is an input. Most options can be set at the input level, so
# you can use different inputs for various configurations.
# Below are the input specific configurations.

- type: log
  enabled: true

  paths:
    - "/home/ec2-user/sophos/Sophos-Central-SIEM-Integration/log/*.txt"
  json.keys_under_root: true
  fields_under_root: true
  fields:
    event:
      dataset: sophos.central
      module: sophos.central
  index: sophos-central
  pipeline: sophos-central
```
and finally we created the following ingest pipeline: [sophos-central-ingest-pipeline.txt](https://github.com/elastic/beats/files/6125851/sophos-central-ingest-pipeline.txt) and dashboard [sophos-central-dashboard.ndjson.txt](https://github.com/elastic/beats/files/6125864/sophos-central-dashboard.ndjson.txt).

I have sample data available for testing if needed. Mapping to ECS fields would have to be double-checked/validated.

Thanks!
