### ISSUE TITLE
[DOCS] Enhancement Request: Add Configuration guide for beats and logstash pods autodiscover 

### ISSUE THREAD

**Issue by hp0620** [elastic/beats#24528]
**Describe the enhancement:**

Currently, the [documentation guide on Autodiscover](https://www.elastic.co/guide/en/beats/metricbeat/7.10/configuration-autodiscover.html#_kubernetes) settings provides some sample configurations on `redis`, `kubernetes`, `prometheus` modules for the **kubernetes** provider. 

Since there will be use cases where users would like to pull metrics from filebeat, logstash or any other beats **pods that are installed on the same node**, users can benefit from additional autodiscover sample configuration on beats modules or logstash modules. 

The configuration guides for beats are scattered around across the documentation guide between standard install and k8s install, and without a good sample on the working configuration specific to autodiscover, it takes significant time for new beats users to collect the right information navigating between standard beats install and k8s install, deduce the plausible configuration and then apply them to k8s and autodiscover configuration, which may discourage some users from using this feature. 

For example, in order to configure a working autodiscover on k8s for metricbeat for beats module, users have to navigate back and forth (minus the learning time) all the urls below at minimum, which is doable, but not ideal in terms of user experience. 

[1] https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-logstash.html
[2] https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-reference-yml.html
[3] https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-logstash-node_stats.html
[4] https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-modules.html
[5] https://www.elastic.co/guide/en/beats/metricbeat/7.10/configuration-autodiscover.html#_kubernetes
[6] https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-beat.html
[7] https://github.com/elastic/beats/blob/master/deploy/kubernetes/filebeat/filebeat-daemonset.yaml

Ideally, if a full working sample configuration per module can be provided in the autodiscover guide, that will provide a better user experience. 

e.g. 
```
metricbeat.autodiscover:
        providers:
          - type: kubernetes
            templates:
              - condition:
                  contains:
                    kubernetes.labels.app: "logstash"
                config:
                  - module: logstash
                    metricsets:
                      - node
                      - node_stats
                    period: 10s
                    xpack.enabled: true
                    hosts: "${data.host}:{data.port}"
```
```
metricbeat.autodiscover:
        providers:
          - type: kubernetes
            templates:
              - condition:
                  contains:
                    kubernetes.labels.app: "filebeat"
                config:
                  - module: beat
                    metricsets:
                      - stats
                      - state
                    period: 10s
                    xpack.enabled: true
                    hosts: "${data.host}:{data.port}"
```

Further, the [sample .yml](https://github.com/elastic/beats/blob/master/deploy/kubernetes/filebeat/filebeat-daemonset.yaml) does not define the port on the pod spec, so if the user use the config above, the install will fail, since there is no data.port to read from.
