### ISSUE TITLE
[filebeat] doesn't work with docker local logging driver

### ISSUE THREAD

**Issue by cdalexndr** [elastic/beats#24531]
For confirmed bugs, please report:
- Version: 7.10.1
- Operating System:  docker
- Discuss Forum URL:
- Steps to Reproduce: 

docker-compose service with:
```
logging:
      driver: local
```
Without the above setting, logs are parsed fine.

filebeat.yml:
```
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "log-%{[docker][container][labels][app]}"
  pipeline: pipeline_logs
  ilm.enabled: false

queue.mem:
  events: 1024
  flush.min_events: 256
  flush.timeout: 1s

setup.ilm.enabled: false
setup.template.name: "log"
setup.template.pattern: "log-*"
setup.kibana.host: http://kibana:5601

filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
```

**Comment by cdalexndr** [comment]
Tried using:
```
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      templates:
        - config:
          - type: container
            paths:
              - /var/lib/docker/containers/${data.docker.container.id}/local-logs/*.log
```
But parsing fails:
`ERROR   [reader_docker_json]    readjson/docker_json.go:204     Parse liINFOrrorlog/harvester.go:335amp:Skipping" as "2006"err►�������■→�☺2021-03-14T12:04:45.567Z      INFO`

Is local logging driver not supported?
