### ISSUE TITLE
period doesn't work as configured.

### ISSUE THREAD

**Issue by zhaoyi0113** [elastic/beats#24553]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version:  elastic/metricbeat:7.11.1
- Operating System:  docker image elastic/metricbeat:7.11.1
- Discuss Forum URL:
- Steps to Reproduce: 

with below configuration, metricbeat queries metrics every 30 seconds which is not what is configured `24 hours` which lead to a high aws bill.

```
- module: aws
      role_arn: xxx
      period: 2400s
      regions:
        - ap-southeast-2
      metricsets:
        - cloudwatch
      metrics:
        - namespace: AWS/DynamoDB
        - namespace: AWS/Lambda
        - namespace: AWS/Events
        - namespace: AWS/AppSync
        - namespace: AWS/ApiGateway
        - namespace: AWS/RDS
```

**Comment by kaiyan-sheng** [comment]
Hello @zhaoyi0113, what's the exact aws.yml config you used for testing? I tried with this below and can not reproduce the problem:
```
- module: aws
  credential_profile_name: elastic-beats
  period: 15m
  metricsets:
    - cloudwatch
  metrics:
    - namespace: AWS/RDS
    - namespace: AWS/DynamoDB
```

With this config, RDS and DynamoDB metrics are collected every 15-minute. I will close this issue for now and if you still having problem configuring Metricbeat, please post on https://discuss.elastic.co/c/beats. Your questions will reach a wider audience there, and if we confirm that there is a bug, then you can reopen this issue or open a new one with more details. Thanks in advance!
