### ISSUE TITLE
S3 Input not working together with logstash output

### ISSUE THREAD

**Issue by buzzdeee** [elastic/beats#24601]
For confirmed bugs, please report:
- Version: 7.11.2
- Operating System: Ubuntu 18.04
- Discuss Forum URL: https://discuss.elastic.co/t/s3-input-getting-stuck-and-not-deleting-sqs-messages/267090
- Steps to Reproduce: 

This is a stripped down version of filebeat.yml

```
filebeat.inputs:
  - type: s3
    enabled: true
    queue_url: "https://sqs.us-west-2.amazonaws.com/ACCOUNTID/SQSNAME"
    access_key_id: "KEY_ID"
    secret_access_key: "SECRET"
    tags: ['guardduty']
    json:
      keys_under_root: False


  - type: s3
    enabled: true
    queue_url: "https://sqs.us-gov-west-1.amazonaws.com/ACCOUNTID/SQSNAME"
    access_key_id: "KEY ID"
    secret_access_key: "SECRET"
    tags: ['guardduty']
    json:
      keys_under_root: False

output.logstash:
  hosts: ["logstashhost:5044"]
  ssl.enabled: true
  ssl.certificate_authorities: ["/etc/filebeat/ca-chain.pem"]

```

above config, it doesn't work, sometimes more, sometimes less of the available messages from the SQS queue change to messages in flight, but they never seem to get deleted. The messages in flight, then switch back to messages available.
As I guess filebeat still thinks it can't deliver these logs to logstash, it's kind of getting stuck, and eventually stops fetching new messages that are available. Running filebeat in debug mode, I do see it fetching logs from S3, parsing them, and also publishing them to Logstash, but only a few messages evenutall end up in ES. 
Restarting filebeat starts the process from the beginning, eventually pushing duplicate logs to ES.

changing the filebeat output section to directly send logs to ES, ingesting logs from S3 works like a charm with following 
output section:

```
output.elasticsearch:
        hosts: ["https://ESCLUSTERNODE:443"]
        username: "USERNAME"
        password: "PASSWORD"
        ssl.verification_mode: none
```

also with the elasticsearch output section, I do see lines in filebeat debug log alike:
````
s3/collector.go:174     Deleting message from SQS: 7412b748-3a01-47e0-9be1-fbeb774235de {"queue_url": "https://sqs.us-gov-west-1.amazonaws.com/ACCOUTID/SQSNAME", "region": "us-gov-west-1"}
and
s3/collector.go:106     no message received from SQS    {"queue_url": "https://sqs.us-gov-west-1.amazonaws.com/ACCOUNTID/SQSNAME", "region": "us-gov-west-1"}
```

which I don't see with the logstash output.
