### ISSUE TITLE
Windows Service won't start after install and enrollment.

### ISSUE THREAD

**Issue by ruant** [elastic/beats#24641]
Elastic-Agent version:  
Binary: 7.11.2 (build: 1d9cced55410003f5d0b4594ff5471d15a4e2900 at 2021-03-06 07:40:32 +0000 UTC)

I'm having issues with the Windows service that was installed by the enrollment command doesn't want to start up.  
The only line I get in the log file is this one when trying to start it:
```
2021-03-18T16:19:46.741+0100	ERROR	cmd/watch.go:61	failed to load markeropen C:\Program Files\Elastic\Agent\data\.update-marker: The system cannot find the file specified.
```
However, running it manually from the commandline `.\elastic-agent.exe run -v -e` it starts up and shows up as unhealthy in the Fleet / Agent overview.
In the command line output it now tries to connect to 0.0.0.0:5601 for some reason.

```
2021-03-18T17:03:00.306+0100    ERROR   application/fleet_gateway.go:168        failed to dispatch actions, error: acknowledge 11 actions '[action_id: 742836c0-87f2-11eb-8b8a-3376130f4587, type: POLICY_CHANGE action_id: 742836c0-87f2-11eb-8b8a-3376130f4587, type: POLICY_CHANGE action_id: 742836c0-87f2-11eb-8b8a-3376130f4587, type: POLICY_CHANGE action_id: 742836c0-87f2-11eb-8b8a-3376130f4587, type: POLICY_CHANGE action_id: 742836c0-87f2-11eb-8b8a-3376130f4587, type: POLICY_CHANGE action_id: 742836c0-87f2-11eb-8b8a-3376130f4587, type: POLICY_CHANGE action_id: 742836c0-87f2-11eb-8b8a-3376130f4587, type: POLICY_CHANGE action_id: 742836c0-87f2-11eb-8b8a-3376130f4587, type: POLICY_CHANGE action_id: 742836c0-87f2-11eb-8b8a-3376130f4587, type: POLICY_CHANGE action_id: 742836c0-87f2-11eb-8b8a-3376130f4587, type: POLICY_CHANGE action_id: 742836c0-87f2-11eb-8b8a-3376130f4587, type: POLICY_CHANGE]' for elastic-agent 'b4556f40-87f4-11eb-8b8a-3376130f4587' failed: fail to ack to fleet: Post "https://0.0.0.0:5601/api/fleet/agents/b4556f40-87f4-11eb-8b8a-3376130f4587/acks?": context canceled
```

fleet.yml
```yml
agent:
  id: b4556f40-87f4-11eb-8b8a-3376130f4587
fleet:
  enabled: true
  access_api_key: <REDACTED>
  kibana:
    protocol: https
    host: kib01.elastic.local:5601
    hosts:
    - kib01.elastic.local:5601                    # THIS WAS SET TO 0.0.0.0:5601 AT FIRST, BUT THE ERROR ABOVE PERSISTS EVEN AFTER CHANGING TO HIS
    timeout: 5m0s
    ssl:
      verification_mode: full
      certificate_authorities:
      - ca.crt
      renegotiation: never
  reporting:
    threshold: 10000
    check_frequency_sec: 30
  agent:
    id: ""

```
