### ISSUE TITLE
[Filebeat] Cisco amp, @metadata._id not sufficiently unique to prevent overwriting

### ISSUE THREAD

**Issue by leehinman** [elastic/beats#24717]
Cisco amp uses `json.data.detection_id` to build `@metadata._id` but that isn't sufficiently unique.  For example in the `cisco_amp4.ndjson.log` data set there are 2 entries with detection_id `6419303565650558977`, this can lead to documents being overwritten.

```
- if:
      has_fields: ["json.data.detection_id"]
    then:
      - fingerprint:
          fields: ["json.data.detection_id"]
          target_field: "@metadata._id"
    else:
      - fingerprint:
          fields: ["json.data.timestamp", "json.data.timestamp_nanoseconds", "json.data.event_type_id", "json.data.connector_guid"]
          target_field: "@metadata._id"
```
