### ISSUE TITLE
[Filebeat] Cisco ASA and UDP - Ignoring Logs

### ISSUE THREAD

**Issue by MarcusCaepio** [elastic/beats#24721]
- Version: 7.11.2
- Operating System: Ubuntu 20.04.1 LTS

Good Morning all,
in the past, I have contributed the Pattern for the Cisco Messages with the ID 734001.
It turns out, that these messages are currently ignored by filebeat. When I run filebeat with

`./filebeat -e -d "*" `

I see all the logs, which are parsed. Having an ngrep running parallel on UDP 9001 I can see, that the logs for 734001 are arriving, but I cannot see this log message in the filebeat debug output. It is hard to reproduce, because this log message belongs to AnyConnect VPN connections. So I give the best information I can here.
For the Cisco ASA Device Syslog settings, I have tested "Legacy Timestamp", "RFC 5424" and "No Timestamp". All three options don't appear in filebeat. E.g.:
```
ngrep -W byline -d eth0 udp and dst port 9001 | grep 734001
<166>Mar 24 2021 09:47:40 devicename : %ASA-6-734001: DAP: User user.name@domain.com, Addr 1.2.3.4, Connection AnyConnect: The following DAP records were selected for this connection: dap_x, dap_y, dap_z

filebeat -e -c /etc/filebeat/filebeat.yml -d "*" 2>&1 >/dev/null | grep '734001'
Result: Nothing
```
You can do this e.g. for other messages like "302014" which then also appears in the filebeat debug:
```
filebeat -e -c /etc/filebeat/filebeat.yml -d "*" 2>&1 >/dev/null | grep '302014'
"message": "<166>Mar 24 09:51:21 devicename : %ASA-6-302014: Teardown TCP connection 123456789 for a.b.c:2.3.4.5/12345 to c.d:6.7.8.9/54321 duration 0:00:20 bytes 4135 TCP FINs from a.b.c\n",
```

So it seems, that filebeat is dropping these messages. But why? The log level of the message is informational. Filebeat is set to log level 7. Additional, I have tested this with the UDP input instead of the cisco module. Same result. 

Cheers,
Marcus

**Comment by adriansr** [comment]
This is odd.

I've tested like this:
```
echo '<166>Mar 24 2021 09:47:40 devicename : %ASA-6-734001: DAP: User user.name@domain.com, Addr 1.2.3.4, Connection AnyConnect: The following DAP records were selected for this connection: dap_x, dap_y, dap_z' | nc -cu localhost 9001
```

Filebeat Cisco happily catches the event and publishes it to ES:

```
2021-03-24T11:07:28.356+0100	DEBUG	[processors]	processing/processors.go:203	Publish event: {
  "@timestamp": "2021-03-24T10:07:28.355Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "8.0.0",
    "truncated": false,
    "pipeline": "filebeat-8.0.0-cisco-asa-asa-ftd-pipeline"
  },
  "ecs": {
    "version": "1.8.0"
  },
  "message": "<166>Mar 24 2021 09:47:40 devicename : %ASA-6-734001: DAP: User user.name@domain.com, Addr 1.2.3.4, Connection AnyConnect: The following DAP records were selected for this connection: dap_x, dap_y, dap_z\n",
  "tags": [
    "cisco-asa",
    "forwarded"
  ],
  "service": {
    "type": "cisco"
  },
  "fileset": {
    "name": "asa"
  },
  "agent": {
    "ephemeral_id": "d49bcb41-fcba-495e-8ff9-bd3b3869b2eb",
    "id": "27f8f183-1fc8-4a6b-b2a8-6af34563bbcc",
    "name": "asrs-MacBook-Pro.local",
    "type": "filebeat",
    "version": "8.0.0"
  },
  "log": {
    "source": {
      "address": "127.0.0.1:54325"
    }
  },
  "input": {
    "type": "udp"
  },
  "event": {
    "timezone": "+01:00",
    "module": "cisco",
    "dataset": "cisco.asa"
  }
}
[...]
2021-03-24T11:07:29.405+0100	INFO	[publisher_pipeline_output]	pipeline/output.go:151	Connection to backoff(elasticsearch(http://localhost:9200)) established
2021-03-24T11:07:29.472+0100	DEBUG	[elasticsearch]	elasticsearch/client.go:230	PublishEvents: 1 events have been published to elasticsearch in 66.802049ms.
```

And the event shows up correctly ingested in Kibana, no errors.

Can you repeat the same test (the cat .... | nc -cu ...) line, and see if your Filebeat ingests it? 

Filebeat doesn't drop UDP packets that it reads, neither it inspects the Message ID field (this is done in the ingest pipeline), so for now I can only imagine that the UDP packet is not reaching Filebeat for one reason or another. It has to be either dropped at kernel before Filebeat reads it or directed to an address/port that Filebeat is not bound to.

Can you compare the destination IP / port from this packet with those from a packet that Filebeat receives successfully, 302014 for example?

I understand that both packets originate from the same ASA device so I don't see how it could be sent to a different IP/port, but it's the only thing I can think of right now.

**Comment by MarcusCaepio** [comment]
Your command is not working, it says -c is an invalid parameter.
But I have done this:
Session 1:
:~# filebeat -e -c /etc/filebeat/filebeat.yml -d "*" 2>&1 >/dev/null | grep '734001'
Session 2:
nc -u localhost 9001
<166>Mar 24 2021 09:47:40 devicename : %ASA-6-734001: DAP: User user.name@domain.com, Addr 1.2.3.4, Connection AnyConnect: The following DAP records were selected for this connection: dap_x, dap_y, dap_z

Filebeat shows nothing. 
Based on your idea, I checked netstat:
:~# netstat -anus
IcmpMsg:
    InType0: 1
    InType3: 40
    InType8: 20
    OutType0: 20
    OutType3: 135
    OutType8: 2
Udp:
    110650 packets received
    142 packets to unknown port received
    1307475 packet receive errors
    99 packets sent
    1307475 receive buffer errors
    0 send buffer errors
    IgnoredMulti: 3
UdpLite:
IpExt:
    InMcastPkts: 2
    InBcastPkts: 6
    OutBcastPkts: 3
    InOctets: 378939586
    OutOctets: 19357649
    InMcastOctets: 72
    InBcastOctets: 2712
    OutBcastOctets: 1728
    InNoECTPkts: 1459660

I have MANY packet receive errors....

**Comment by adriansr** [comment]
Can you share your filebeat.yml  and modules.d/cisco.yml ? Remove any passwords or private information.

**Comment by MarcusCaepio** [comment]
filebeat.yml:
```
filebeat.config.modules.path: /etc/filebeat/modules.d/*.yml
filebeat.registry.path: ${path.data}/registry
filebeat.registry.file_permissions: 0600
filebeat.registry.flush: 0s
filebeat.registry.migrate_file: ${path.data}/registry
filebeat.overwrite_pipelines: false
filebeat.shutdown_timeout: 0
output.elasticsearch:
  enabled: true
  hosts: ["x"]
  compression_level: 9
  protocol: "https"
  username: "elastic"
  password: "x"
  worker: 2
  pipeline: "logs-cisco.asa-0.7.7"
  bulk_max_size: 3200
  ssl.enabled: true
  ssl.verification_mode: full
path.config: /etc/filebeat
setup.dashboards.enabled: false
setup.template.enabled: true
setup.template.settings:
  index:
    number_of_shards: 1
    codec: best_compression
setup.ilm.enabled: auto
setup.ilm.rollover_alias: 'filebeat'
setup.ilm.pattern: "{now/d}-000001"
```

modules.d/cisco.yml:
```
- module: cisco
  asa:
    enabled: true
    var.input: syslog
    var.syslog_host: 0.0.0.0
    var.syslog_port: 9001
    var.log_level: 7
    var.internal_zones: [ "Internal" ]
    var.external_zones: [ "External" ]
  ftd:
    enabled: false

  ios:
    enabled: false

  nexus:
    enabled: false

  meraki:
    enabled: false

  umbrella:
    enabled: false
```

Regarding the pipeline, I first tried to use the elastic-agent and will use it again. I am just using filebeat to find the reason for the missing logs (see https://github.com/elastic/integrations/issues/758) 
But the netstat errors indicate that this could be also a problem outside of filebeat. I already tweaked the Kernel, did not help. As it is a VM, I am currently investigating if this is a host problem, an OS problem, a network problem or an ASA problem.... this could be so much.....

```
netstat -anus
IcmpMsg:
    InType0: 4
    InType3: 40
    InType8: 230
    OutType0: 230
    OutType3: 91
    OutType8: 8
Udp:
    1759437 packets received
    92 packets to unknown port received
->    16824050 packet receive errors
    224 packets sent
->    16824050 receive buffer errors
    0 send buffer errors
    IgnoredMulti: 46
UdpLite:
IpExt:
    InMcastPkts: 2
    InBcastPkts: 92
    OutBcastPkts: 46
    InOctets: 4694472768
    OutOctets: 90585231
    InMcastOctets: 72
    InBcastOctets: 41584
    OutBcastOctets: 26496
    InNoECTPkts: 18906485
```
