### ISSUE TITLE
how to add podip on add_kubernetes_metadata processor?

### ISSUE THREAD

**Issue by dadayoo** [elastic/beats#24758]
Hi  I'm running filebeat daemonset on my k8s cluster
have try different config scenario but do not get the pod ip data
here is my config

```
  processors:
    - add_kubernetes_metadata:
        default_indexers.enabled: true
        default_matchers.enabled: true
        indexers:
          - pod_uid:
```
am i miss something?
