### ISSUE TITLE
[Elastic-Agent] Enrollment URI to Fleet Server is empty when certificate is provided

### ISSUE THREAD

**Issue by simitt** [elastic/beats#24893]
configuring a `fleet_server.cert` and `fleet_server.cert_key` in the `credentials.yml` file leads to the Elastic Agent having an empty URL (`:///`) when trying to enroll itself into Fleet Server. 

## How to reproduce
* start docker container with fleet setup and fleet server enabled and configure certificates
* log the `c.cllient.URI()` of the [enroll_cmd](https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/pkg/agent/cmd/enroll_cmd.go#L357)

**Comment by blakerouse** [comment]
@simitt I see where the issue is. Seems that the code expects that when a certificate and certificate key is provided that a URL will also be provided. This is because that certificate and certificate key is generated for a specific address.

In this case why would you be providing a certificate and a key without providing a URL? Is there a use-case for that? We could make the code path set the URL if the URL is empty, but I would expect communicate to still fall to the Fleet Server being that the URL will most likely not match the certificate.

**Comment by simitt** [comment]
So as soon as a certificate is provided the Elastic Agent needs to enroll via the publicly routable URL, which should be configured? I guess I thought that the agent would still enroll via localhost.

**Comment by blakerouse** [comment]
@simitt The Elastic Agent wants its communicate between itself and the Fleet Server to be encrypted even if its on the same host.

We could change it to use localhost even in that case, but we would have to set SSL verification_mode to none. So the connection would be encrypted but unverified.

If you run Elastic Agent with Fleet Server without any extra parameters then it will generate a certificate/key that uses the hostname of the node and then communicates through that hostname (keep the connection local and SSL verified).

**Comment by simitt** [comment]
> If you run Elastic Agent with Fleet Server without any extra parameters then it will generate a certificate/key that uses the hostname of the node and then communicates through that hostname (keep the connection local and SSL verified). 

So if I configure no `fleet_server.cert` and `fleet_server.insecure_http: false` then the Elastic Agent and Fleet Server are automatically communicating via a TLS connection with each other?
```
# Fleet enrollment of the elastic agent
fleet:
  enroll: true
  insecure: false 
# Start and run a Fleet Server along side this Elastic Agent
fleet_server:
  enable: true
  insecure_http: false 
  #cert: ""
  #cert_key: ""
  elasticsearch:
    host: "<host>"
    username: "<username>"
    password:"<password>"
    ca: "<ca>"

```
