### ISSUE TITLE
elastic-agent: can't pass global env variable

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#24943]
Hi Team,

we'd like to pass the `hosts` parameter in the Kubernetes integration as:

```
    hosts:
      - 'https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}'
 ```

Unfortunately, elastic-agent can't pick it up and boot up metricbeat process. No error is reported in any logs. The config seems to be correct, verified with stripped `$`-opening characters:

```
state/data/logs/default/metricbeat-json.log-2021-04-06-10-148:27:{"log.level":"error","@timestamp":"2021-04-06T10:47:26.984Z","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"fleet/manager.go","file.line":260},"message":"1 error: Error creating runner from config: 1 error: host parsing failed for kubernetes-state_container: error parsing URL: parse \"https://KUBERNETES_SERVICE_HOST:KUBERNETES_SERVICE_PORT\": invalid port \":KUBERNETES_SERVICE_PORT\" after host","ecs.version":"1.6.0"}
```

Kibana's config:

```
id: 84205fd0-96c5-11eb-9df5-95cc2ec42297
revision: 2
outputs:
  default:
    type: elasticsearch
    hosts:
      - 'http://elasticsearch:9200'
output_permissions:
  default:
    _fallback:
      cluster:
        - monitor
      indices:
        - names:
            - logs-*
            - metrics-*
            - traces-*
            - .logs-endpoint.diagnostic.collection-*
          privileges:
            - auto_configure
            - create_doc
agent:
  monitoring:
    enabled: false
    logs: false
    metrics: false
inputs:
  - id: 0fe6e5d9-5708-4914-b117-54e2abf6b518
    name: kubernetes-state_container
    revision: 1
    type: kubernetes/metrics
    use_output: default
    meta:
      package:
        name: kubernetes
        version: 0.4.3
    data_stream:
      namespace: ep
    streams:
      - id: >-
          kubernetes/metrics-kubernetes.state_container-0fe6e5d9-5708-4914-b117-54e2abf6b518
        data_stream:
          dataset: kubernetes.state_container
          type: metrics
        metricsets:
          - state_container
        add_metadata: true
        hosts:
          - 'https://${KUBERNETES_SERVICE_HOST}:${KUBERNETES_SERVICE_PORT}'
        period: 5s
fleet:
  hosts:
    - 'http://kibana:5601'
  kibana:
    protocol: http
    hosts:
      - 'kibana:5601'
```
