### ISSUE TITLE
[Filebeat][O365 Module] client_secret produces error if secret starts with @

### ISSUE THREAD

**Issue by P1llus** [elastic/beats#25058]
Seems like there might be an issue with the configuration mapping (mustache?) for certain fields starting with `@`.

Looking at: https://discuss.elastic.co/t/yaml-found-character-that-cannot-start-any-token-when-value-starts-with/269778

The following example:
```
- module: o365
  audit:
    enabled: true
    var.application_id: "xxx"
    var.tenants:
      - id: "xxx"
        name: "xxx"
    var.client_secret: "@/xxx"
```

Would produce an error like:
`cfgfile/list.go:99 Error creating runner from config: Error getting config for fileset o365/audit: Error reading input config: yaml: line 12: found character that cannot start any token.`

Will update this issue once I have looked into it.
