### ISSUE TITLE
[Filebeat] Annotations dedot is ignored

### ISSUE THREAD

**Issue by Tibo669** [elastic/beats#25078]
**Beats version**: 7.11.2

The dedot functionallity cannot be disabled for annotations, even with `annotations.dedot: false`.
Using this Filebeat configuration we can expect to index documents with fields named like `cls.department`.
```
filebeat.autodiscover:
  providers:
    - type: kubernetes
      include_annotations: ["cls.department", "cls.project", "cls.logsource", "cls.environment"]
      annotations.dedot: false
```

But the document ends up indexed with fields `cls_department` - they are "dedotted" anyway.

According to the code, it is explained by the fact that we ignore `annotations.dedot` and we use `labels.dedot`.
https://github.com/elastic/beats/blob/7729cd751a920f80bd51b0f5fd0a6cc6120c30a5/libbeat/common/kubernetes/metadata/resource.go#L64
