### ISSUE TITLE
How does filebeat collect docker container names

### ISSUE THREAD

**Issue by ktpktr0** [elastic/beats#25100]
Now I use container ID to collect logs, but when I view logs on kibana, I can't know which container name ID corresponds to. So I want to collect container names through filebeat. The current configuration of filebeat is as follows:

```
- type: docker
  containers.ids:
    - '5def7f331a895aeb63aaf76d2083979ab102f1693dc25a096e8057e1582716a1'
    - '48c6ce75dda3852919c8606c12dad8bf2f23465d55808576530fc449556b0f24'
    - 'cfd72902defd5eb523620856cb54883c7079efd1e96f68393e66c435522c67d8'
  tags: ["stf_console"]
  fields:
    service: stf_console_pre
  fields_under_root: true
  tail_files: true
```

I know that there is a function to add docker metadata, but I can't match the container name I want through regular expression (I have multiple containers of multiple businesses on my host).
