### ISSUE TITLE
[elastic-agent] Extend agent.monitoring configuration from elastic-agent.yml.  

### ISSUE THREAD

**Issue by simitt** [elastic/beats#25133]
Moving Feature Request from https://github.com/elastic/kibana/issues/97356 over to the Elastic-Agent:

On top of https://github.com/elastic/beats/pull/25132 also allow to disable elastic-agent internal metrics and logs collection by default when configuring `elastic-agent.yml`. 
```
agent:
  monitoring:
    enabled: false
    logs: false
    metrics: false
```

@michalpristas is it feasible to add these settings in your efforts in https://github.com/elastic/beats/pull/25132 or as a follow up?
