### ISSUE TITLE
[elastic-agent] Filebeat and metricbeat started although monitoring is disabled

### ISSUE THREAD

**Issue by simitt** [elastic/beats#25226]
When creating an agent policy with logs and metrics collection disabled, either via preconfiguration API or via the Fleet policy UI, and then enrolling an agent, the agent still starts the monitoring filebeat and metricbeat. 

<img width="827" alt="Screenshot 2021-04-22 at 10 35 41" src="https://user-images.githubusercontent.com/5555349/115683234-86433b00-a356-11eb-8908-a0da0b975d33.png">

<img width="1015" alt="Screenshot 2021-04-22 at 10 36 15" src="https://user-images.githubusercontent.com/5555349/115683294-95c28400-a356-11eb-8407-ea4e47a83179.png">

The generated `fleet.yml` only contained the `agent.monitoring.http` section, but nothing related to `agent.monitoring.enabled`.

Enabling and disabling the monitoring while the agent is running leads to the agent stopping the monitoring mb and fb.
This manual interaction should not be necessary, and the right configuration should be picked up from the beginning.

**Comment by michalpristas** [comment]
can you verify agent is enrolled to your config? 
i tried it locally and havent seen this behavior. 
what i did was that i updated fleet server config so monitoring is disabled. updated elastic-agent.yml to enable exposing of metrics using http. and enrolled using kibana generated commands. 

and as expected
```
root@Agent $ cat fleet.yml
agent:
  id: 644a8553-2c59-4471-88f2-c61f5521b399
  monitoring.http:
    enabled: true
    host: localhost
    port: 6791
fleet:
  enabled: true
...
```

```
ps aux | grep _monitor
d    21365   0.0  0.0  4268056    808 s002  S+    3:23pm   0:00.00 grep _monitor
```
