### ISSUE TITLE
[elastic-agent] Configuration changes cannot be applied

### ISSUE THREAD

**Issue by simitt** [elastic/beats#25302]
Latest elastic-agent throws following error when trying to enable collecting agent logs and metrics:

```
{"log.level":"info","@timestamp":"2021-04-26T09:01:07.318Z","log.origin":{"file.name":"application/periodic.go","file.line":77},"message":"Configuration changes detected","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2021-04-26T09:01:07.318Z","log.origin":{"file.name":"capabilities/upgrade.go","file.line":150},"message":"expecting map config object but got nil for capability 'multi-upgrade'","ecs.version":"1.6.0"}
```

The agent policy was created via preconfiguration API with the following config:
```
xpack.fleet.packages:
  - name: fleet_server
    version: latest

xpack.fleet.agentPolicies:
  - name: Elastic Agent on Cloud policy
    is_managed: true
    id: elastic-agent-on-cloud
    is_default_fleet_server: true
    monitoring_enabled: []
    package_policies:
      - package:
          name: fleet_server
        name: Fleet Server
        inputs:
          - type: fleet-server
            vars:
            - name: host
              value: 0.0.0.0
              frozen: true

```

**Comment by ruflin** [comment]
@simitt Is logging and metrics afterwards enabled or not?

@michalpristas The above error comes from the upgrade capabilities it seems but the change above should not trigger any upgrade. Is it maybe related to starting mb / fb which somehow assumes it is an upgrade?

**Comment by simitt** [comment]
The status of the internal filebeat and metricbeat was not changed, so there were not running in the container.
I have also seen this error on a simple container restart now, without any configuration changed for enabling/disabling metrics and logs collection.

**Comment by simitt** [comment]
I also observed that fleet-server doesn't get started again when the above mentioned message is logged on a container restart, where the elastic-agent/fleet-server enrollment and setup has happened before already.

**Comment by ph** [comment]
@blakerouse Could you take a look at this issue? @michalpristas is out for a few days

**Comment by blakerouse** [comment]
Looking at it today.

**Comment by blakerouse** [comment]
Is there a `capabilities.yml` defined for the Elastic Agent? If so can you provide the contents of that file?

**Comment by simitt** [comment]
Yes, the content is
```
capabilities:
- rule: allow
  input: fleet-server
- rule: deny
  input: "*"
```
