### ISSUE TITLE
When the filebeat log is output to Kafka, how to configure xpack monitoring?

### ISSUE THREAD

**Issue by ktpktr0** [elastic/beats#25322]
I installed elk7.8.1 and used filebeat to collect log output to Kafka. Now I want to use xpack to monitor my elk cluster. Elk components can be displayed normally, but filebeat cannot be monitored. This is my configuration：
```
output.kafka:
  hosts: ["192.168.1.190:9092"]
  topic: "%{[kafka_topic]}"
  required_acks: 1
  username: "producer"
  password: "xxx"

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
  keepfiles: 3
  permissions: 0644

monitoring:
  enabled: true
  elasticsearch:
    hosts: ["https://192.168.1.191:9200"]
    metrics.period: 120
    backoff.max: 180
    state.period: 600
    backoff.init: 10
    username: "xxx"
    password: "xxxx"
    ssl.certificate_authorities: /etc/filebeat/ssl/ca.crt
```

On kibana, it is shown as follows。I can see the monitoring of filebeat from this entrance, but I don't know why it's not in the cluster below.：

![image](https://user-images.githubusercontent.com/41657218/116187082-6f865500-a757-11eb-8f25-30b6e496940f.png)

When the filebeat log is output to Kafka, how to configure xpack monitoring?
