### ISSUE TITLE
Starting FileBeat causes the system to crash

### ISSUE THREAD

**Issue by EminemJK** [elastic/beats#25370]
System Environment: windows server 2008 R2 Enterprise, 64bit
CPU: Intel (R) eon R) CrU E7- 4820 2.00GHz 2.00 GHz(4 CPU)
Memory: 32GB
Version: filebeat-7.12.0-windows-x86_64
Filebeat.yml: 
```
max_procs: 1
filebeat.inputs:
- type: log
  enabled: true
  encoding: GB2312
  paths:
    - D:/bigData/logs/*.txt
 
output.file:
  path: "D:/bigData/beatLogs"
  filename: filebeat.log
```
D:/bigData/logs/:
![log](https://user-images.githubusercontent.com/33885904/116373754-38d83980-a840-11eb-8b16-50541ef1c017.png)

When I run the Filebeat program:
```
filebeat -e -c filebeat.yml
```
![1](https://user-images.githubusercontent.com/33885904/116373703-2f4ed180-a840-11eb-9989-c3fd3da364c5.png)

After the closing:
![2](https://user-images.githubusercontent.com/33885904/116373727-3544b280-a840-11eb-9aca-ec137e516f12.jpg)

I have uninstalled all the applications, There is no extra applications
![3](https://user-images.githubusercontent.com/33885904/116374201-a84e2900-a840-11eb-9dfd-984e4e9346e9.jpg)

As soon as I run the Filebeat app, the system will suspend or shut down the system immediately. What's goin' on? Nothing similar happened on the other servers.
