### ISSUE TITLE
filebeat don't read new content

### ISSUE THREAD

**Issue by XooR** [elastic/beats#2544]
- Version: filebeat version 5.0.0-alpha5 (amd64), libbeat 5.0.0-alpha5
- Operating System: CentOS release 6.8 (Final)
- Steps to Reproduce:

Run script to fill logs:
```
mkdir -p /tmp/test_filebeat/log; i=0; while true; do echo -e "event $i\n   some_data" >> /tmp/test_filebeat/log/debug.log; done
```

Setup filebeat to read file:
```
filebeat:
  prospectors:
    -
      paths:
        - /tmp/test_filebeat/log/debug.log
      encoding: utf-8
      input_type: log
      fields:
        hostname: world-test
      multiline:
        pattern: '^[[:space:]]'
        negate: false
        match: after
      exclude_files: ['\.gz$']
  registry_file: /tmp/test_filebeat/
output:
  console:
    pretty: true
```

Run filebeat like:
```
./filebeat -c filebeat.yml -e -d '*'
```
This will read only first 4096 events:
```
2016/09/14 12:01:22.926444 logp.go:221: INFO Non-zero metrics in the last 30s: filebeat.harvester.running=1 filebeat.harvester.started=1 publish.events=4096 libbeat.publisher.published_event
s=4095 filebeat.harvester.open_files=1
```
It's strange for me that publish.events and libbeat.publisher.published_event are different. I guess that libbeat.publisher.published_events are confirmed events.

After that there are no new sent events:
```
2016/09/14 12:03:22.926358 logp.go:223: INFO No non-zero metrics in the last 30s
```

Filebeat will stop reading new content, after first 4096 events there are no new reads from file. Only lines like this:
```
2016/09/14 12:02:42.933558 prospector.go:132: DBG  Run prospector
2016/09/14 12:02:42.933664 prospector_log.go:57: DBG  Start next scan
2016/09/14 12:02:42.933829 prospector_log.go:140: DBG  Check file for harvesting: /home/stanislava/log/debug.log
2016/09/14 12:02:42.933858 prospector_log.go:170: DBG  Update existing file for harvesting: /home/stanislava/log/debug.log, offset: 195858
2016/09/14 12:02:42.933879 prospector_log.go:209: DBG  Harvester for file is still running: /home/stanislava/log/debug.log
```

I checked with 1.3.0 version and this doesn't happen.
