### ISSUE TITLE
[filebeat] default owner of output file 

### ISSUE THREAD

**Issue by saibug** [elastic/beats#25455]
hello, 

i have filebeat installed (filebeat-7.10.0) , and configured like this : 

```
filebeat.inputs:
- type: log
  paths:
       - /var/log/file1.log
       - /var/log/file2.log 

output.file:
  path: "/var/log/"
  filename: "all.log"
  permissions: 0644
  rotate_every_kb: 20000
  number_of_files: 2


processors:
  - drop_fields:
        fields: ["fileset.name", "read_timestamp", "input.type", "log.offset", "log.source.address", "agent.ephemeral_id", "agent.name", "agent.type", "agent.version", "ecs.version", "host.name", "fileset.name", "stream", "beat.hostname", "beat.name"]
```

1 - i put 644 permission to file but not working ( OK according to these commits https://github.com/elastic/beats/pull/14119) .
2 - output.file section don't have owner parameter . 

Is there any way to add this option ?

Desired behavior : 
other user can read output file .. 

thxs
