### ISSUE TITLE
Agent sends wrong log level to Endpoint

### ISSUE THREAD

**Issue by ferullo** [elastic/beats#25583]
In [this](https://github.com/elastic/kibana/issues/99030) issue, @muskangulati-qasource found that on a Windows 7 machine Endpoint was being sent a configuration  from Agentthat set the log level to the string `""`. 

Below are key facts from the original [comment](https://github.com/elastic/kibana/issues/99030#issuecomment-832822815) for the bug.

`fleet.yml` contains the below content
```yaml
agent:
  id: 381cc1b0-f772-4a0f-bd20-925610b7d783
  logging.level: info
  monitoring.http:
    enabled: false
    host: ""
    port: 6791
fleet:
  enabled: true
  access_api_key: <redacted>
  protocol: http
  host: <redacted>
  hosts:
  - https://<redacted>
  timeout: 5m0s
  ssl:
    verification_mode: none
    renegotiation: never
  reporting:
    threshold: 10000
    check_frequency_sec: 30
  agent:
    id: ""
```

`elastic-endpoint.yaml`'s `fleet` section is below. Notice that the logging level is `""`. There is no reason this would be changed by Endpoint after its received by Agent. Endpoint just accepts the config and saves the whole thing without modification.
```yaml
fleet:
  access_api_key: <redacted>
  agent:
    id: 381cc1b0-f772-4a0f-bd20-925610b7d783
    logging:
      level: ""
    monitoring:
      http:
        enabled: false
        host: ""
        port: 6791
  enabled: true
  host:
    id: 5064b7d5-80c5-4eff-aeaf-06e85448a222
  hosts:
  - <redacted>
  protocol: https
  reporting:
    check_frequency_sec: 30
    threshold: 10000
  ssl:
    renegotiation: never
    verification_mode: none
  timeout: 5m0s
```

For confirmed bugs, please report:
- Version: 7.13.0 BC3
- Operating System: Windows 7
- Discuss Forum URL: N/A
- Steps to Reproduce: Install Endpoint. No other steps were reported having been taken.
