### ISSUE TITLE
GCP/FunctionBeat Errors [cannot find matching process for pid=1, name version already used]

### ISSUE THREAD

**Issue by stefnestor** [elastic/beats#25596]
Ongoing errors attempting to use Functionbeat in GCP. The current curiosity is to make sure the GCP processes can run consecutively (since they are) & that "pubsub" (only because it shows up right before errors) isn't causing issues.

For confirmed bugs, please report:
- Version: 7.12.0
- Operating System: GCP
- Discuss Forum URL: NA

functionbeat.yml (runs as "task"/something so parallel processes)

```
cloud:
  auth: elastic:PASSWORD
  id: CLOUD_ID
functionbeat:
  provider:
    gcp:
      functions:
      - description: Google Cloud Function for to push logs to elastic search instance from Pub/Sub
        enabled: true
        fields:
          env: prod
        memory_size: 256MB
        name: NAME
        service_account_email: EMAIL
        timeout: 120s
        trigger:
          resource: RESOURCE
        type: pubsub
      location_id: us-central1
      project_id: PROJECT
      storage_name: NAME
keystore:
  path: /tmp/functionbeat.keystore
output:
  elasticsearch:
    pipeline: pge-gcp-function-beat
path:
  config: /Users/.../functionbeat-7.10.2-darwin-x86_64
  data: /tmp
  home: /Users/.../functionbeat-7.10.2-darwin-x86_64
  logs: /tmp/logs
queue:
  mem:
    flush:
      min_events: 10
      timeout: 0.01s
setup:
  template:
    enabled: true
```

Errors flavor 1

```diff
Function execution started
Function execution took 104 ms, finished with status: 'connection error'
Function execution started
2021-05-04T16:58:29.957Z\tWARN\t[cfgwarn]\tpubsub/pubsub.go:25\tBETA: Google Cloud Platform support is in beta
- 2021-05-04T16:58:29.958Z\tFATAL\t[functionbeat]\tinstance/beat.go:164\tFailed due to panic.\t{\"panic\": \"name version already used\", \"stack\": \"pubsub/vendor/github.com/elastic/beats/v7/libbeat/cmd/instance.Run.func1.1 
 /workspace/src/pubsub/vendor/github.com/elastic/beats/v7/libbeat/cmd/instance/beat.go:165runtime.gopanic 
 /usr/local/go/src/runtime/panic.go:679pubsub/vendor/github.com/elastic/beats/v7/libbeat/monitoring.panicErr 
 /workspace/src/pubsub/vendor/github.com/elastic/beats/v7/libbeat/monitoring/registry.go:257pubsub/vendor/github.com/elastic/beats/v7/libbeat/monitoring.(*Registry).doAdd 
 /workspace/src/pubsub/vendor/github.com/elastic/beats/v7/libbeat/monitoring/registry.go:159pubsub/vendor/github.com/elastic/beats/v7/libbeat/monitoring.addVar 
 /workspace/src/pubsub/vendor/github.com/elastic/beats/v7/libbeat/monitoring/metrics.go:225pubsub/vendor/github.com/elastic/beats/v7/libbeat/monitoring.NewString 
 /workspace/src/pubsub/vendor/github.com/elastic/beats/v7/libbeat/monitoring/metrics.go:170pubsub/vendor/github.com/elastic/beats/v7/libbeat/cmd/instance.Run.func1 
 /workspace/src/pubsub/vendor/github.com/elastic/beats/v7/libbeat/cmd/instance/beat.go:175pubsub/vendor/github.com/elastic/beats/v7/libbeat/cmd/instance.Run 
 /workspace/src/pubsub/vendor/github.com/elastic/beats/v7/libbeat/cmd/instance/beat.go:190pubsub.RunPubSub 
 /workspace/src/pubsub/pubsub.go:35reflect.Value.call 
 /usr/local/go/src/reflect/value.go:460reflect.Value.Call 
 /usr/local/go/src/reflect/value.go:321github.com/GoogleCloudPlatform/functions-framework-go/funcframework.runUserFunctionWithContext 
 /workspace/src/github.com/GoogleCloudPlatform/functions-framework-go/funcframework/framework.go:202github.com/GoogleCloudPlatform/functions-framework-go/funcframework.runBackgroundEvent 
 /workspace/src/github.com/GoogleCloudPlatform/functions-framework-go/funcframework/events.go:101github.com/GoogleCloudPlatform/functions-framework-go/funcframework.handleEventFunction 
 /workspace/src/github.com/GoogleCloudPlatform/functions-framework-go/funcframework/framework.go:169github.com/GoogleCloudPlatform/functions-framework-go/funcframework.registerEventFunction.func1 
 /workspace/src/github.com/GoogleCloudPlatform/functions-framework-go/funcframework/framework.go:136net/http.HandlerFunc.ServeHTTP 
 /usr/local/go/src/net/http/server.go:2036net/http.(*ServeMux).ServeHTTP 
 /usr/local/go/src/net/http/server.go:2416net/http.serverHandler.ServeHTTP 
 /usr/local/go/src/net/http/server.go:2831net/http.(*conn).serve 
 /usr/local/go/src/net/http/server.go:1919\"}
Function execution took 32 ms, finished with status: 'connection error'
```

Errors flavor 2

```diff
2021-05-04T16:58:30.364Z INFO instance/beat.go:455 functionbeat start running.
2021-05-04T16:58:30.364Z INFO [monitoring] log/log.go:118 Starting metrics logging every 30s
2021-05-04T16:58:30.364Z INFO [functionbeat] beater/functionbeat.go:94 Functionbeat is running
2021-05-04T16:58:30.364Z INFO [functionbeat] beater/functionbeat.go:100 Functionbeat is configuring enabled functions: elastic-log-functionbeat
2021-05-04T16:58:30.364Z INFO [coordinator.Coordinator] core/coordinator.go:86 The function 'pubsub' is starting
2021-05-04T16:58:30.367Z INFO [coordinator.Coordinator] core/coordinator.go:97 The function 'pubsub' is stopped
2021-05-04T16:58:30.367Z INFO [functionbeat] beater/functionbeat.go:116 Functionbeat stopped running
- 2021-05-04T16:58:30.370Z ERROR instance/metrics.go:98 Error while getting memory usage: error retrieving process stats: cannot find matching process for pid=1
2021-05-04T16:58:30.371Z ERROR instance/metrics.go:142 Error retrieving CPU percentages: error retrieving process stats: cannot find matching process for pid=1
2021-05-04T16:58:30.371Z WARN instance/metrics.go:277 cgroup data collection disabled: cgroups not found or unsupported by OS
2021-05-04T16:58:30.372Z INFO instance/beat.go:461 functionbeat stopped.
2021-05-04T16:58:30.372Z ERROR instance/metrics_file_descriptors.go:39 Error while retrieving FD information: error retrieving process stats: cannot find matching process for pid=1
```
