### ISSUE TITLE
Metricbeat: Add support for ZFS metrics

### ISSUE THREAD

**Issue by Aqualie** [elastic/beats#25725]
**Describe the enhancement:**
As an agent for collecting system and service metrics Metricbeat should by default support ZFS metrics as many other products in this space provide this capability by default (Netdata, collectD, telegraf, node_exporter etc...). This support should cover both implementations on Linux and BSD platforms with the capability of auto-detecting the current platform and retrieving the available metrics(depending on the platform different metrics are available). As well the appropriate dashboards should be created & included which provide a high-level overview. This should help close the gap in-regards to feature parity with similar products.

**Describe a specific use case for the enhancement or feature:**
At minimum can be used to monitor enterprise ZFS systems based on either BSD or Linux platform to provide performance & efficiency monitoring VIA Kibana. Leveraging Kibana's feature-set alerts can be created based on thresholds or ML/AML jobs created based on information retrieved to create advanced alert's or optimize/scale pools based on multiple parameters.

Related to https://github.com/elastic/beats/issues/10848 that was auto-closed by bot.

**Comment by mikagika** [comment]
This would indeed be helpful. We 💕ZFS!
Note for those who might stumble across this. If you are an elastic cloud customer and want filesystem metrics for ZFS you can capture those basic metrics if you manually update state.tml in /opt/Elastic/Agent/data/elastic*
to add the ignore_types line shown below in context:
```
      - data_stream:
          dataset: system.filesystem
          type: metrics
        id: system/metrics-system.filesystem-86aaf98b-edf0-4144-8377-2a90e6763b41
        metricsets:
        - filesystem
        filesystem.ignore_types: [nfs, smbfs, autofs, squashfs, tmpfs, sysfs, proc]

```
However, if you update the agent at all, your change will be wiped out and you will lose your filesystem metrics again. 😒

This isn't a substitute for the full ZFS measurements, but at least will give you a sense for how full the file system is, which is the most critical thing to us.
