### ISSUE TITLE
[Elastic Agent] Setting fleet-server configs is not propagated properly

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#25738]
When setting `server.limits.max_connections` in the Fleet UI for fleet-server, the policy change is shipped down to Elastic Agent but not properly picked up by fleet-server. Running `elastic-agent inspect` I get the following output:

```
inputs:
- data_stream:
    namespace: default
  id: 453727da-7447-467c-b808-7bd3f152017b
  meta:
    package:
      name: fleet_server
      version: 0.2.4
  name: fleet_server-1
  revision: 3
  server:
    host: 0.0.0.0
    limits.max_connections: 200
    port: 8220
  server.limits.max_connections: 50
  type: fleet-server
  use_output: default
```

I tried to set max_connections in the yaml block and config editor, that is why it shows up twice. But the logs from fleet-server do not show max_connections to be picked up.
