### ISSUE TITLE
Modifying filebeat config's autodiscover provider from docker to kubernetes leads to states leaking.

### ISSUE THREAD

**Issue by cocotyty** [elastic/beats#25799]
For confirmed bugs, please report:
- Version:  7.12.1
- Operating System:  ubuntu/kubernetes/docker
- Discuss Forum URL:
- Steps to Reproduce: 

Our clusters filebeat used docker autodiscover provider  before.
After change provider to kubernetes , registry becomes very large  .

-rw------- 1 root  root   25M May 20 13:49 17662020836.json
-rw------- 1 root  root    59 May 20 13:49 active.dat
-rw------- 1 root  root   25M May 20 13:49 checkpoint.new
-rw------- 1 root  root   11M May 20 13:49 log.json
-rw------- 1 root  root    16 May  7 16:59 meta.json

most of files of stats in *.json are no longer exist.

filebeats log shows like:

2021-05-20T05:26:12.741Z	DEBUG	[input]	log/input.go:169	exclude_files: []. Number of states: 59005
...
2021-05-20T05:26:12.653Z	DEBUG	[input]	log/input.go:199	input with previous states loaded: 1

https://github.com/elastic/beats/blob/f1216384703d6ac948d5d443e157c2ea25300f93/filebeat/input/log/input.go#L178

**Comment by cocotyty** [comment]
```yaml
filebeat.inputs:
filebeat.registry.flush: "5s"
filebeat.autodiscover:
  providers:
  - labels: {dedot: false}
    node: ${NODE_NAME}
    scope: node
    templates:
    - condition:
        has_fields:
          - kubernetes.labels.app
          - kubernetes.labels.version
      config:
      - fields: { pod: '${data.kubernetes.pod.name}', unit_name: '${data.kubernetes.labels.app}',
          version: '${data.kubernetes.labels.version}',container_name: '${data.kubernetes.container.name}'}
        fields_under_root: true
        json: {keys_under_root: true, message_key: log, overwrite_keys: true}
        multiline.match: after
        multiline.negate: true
        multiline.pattern: ^\[
        paths: ['/var/log/containers/${data.kubernetes.pod.name}_${data.kubernetes.namespace}_${data.kubernetes.container.name}-*.log']
        scan_frequency: 1s
        clean_removed: true
        clean_inactive: 5m
        close_inactive: 1m
        ignore_older: 3m
        symlinks: true
        type: log
    type: kubernetes
http.enabled: true
http.host: 0.0.0.0
logging.level: info
max_procs: 1
output.kafka:
  compression: none
  hosts: ['kafka:3390']
  max_message_bytes: 1000000
  partition.round_robin: {reachable_only: false}
  required_acks: 1
  topic: log.log-container.stdout
  version: 0.10.0.0
processors:
- drop_fields:
    fields: [offset, kubernetes, beat, host, source, input, prospector, stream, ecs,
      agent, file, container, docker]
```

**Comment by cocotyty** [comment]
```yaml
filebeat.inputs:
   - type: log
     symlinks: true
     paths:
       - "/var/log/containers/*.log"
     fields:
       must_drop: must_drop
processors:
- drop_event:
    when:
      equals:
        must_drop: must_drop
```
I append this to config, temporarily solved my problem.
But I still think this is a bug.
