### ISSUE TITLE
Filebeat 7.13 is not compatible with elastichsearch-oss 7.10.2

### ISSUE THREAD

**Issue by func0der** [elastic/beats#25865]
- Version: Filebeat 7.13 + Elasticsearch-oss 7.10.2
- Operating System: Debian
- Discuss Forum URL: -
- Steps to Reproduce: install both and output directly to elastichsearch from filebeat

filebeat output config:

```
output:
  elasticsearch:
    index: filebeat-%{[agent.version]}-%{[event.module]:default}-%{+yyyy.MM.dd}
    hosts:
    - log1:9200
```

Error log:
```
May 26 10:21:39 server1 filebeat[24814]: 2021-05-26T10:21:39.231+0200        ERROR        [publisher_pipeline_output]        pipeline/output.go:154        Failed to connect to backoff(elasticsearch(http://log1:9200)): Connection marked as failed because the onConnect callback failed: could not connect to a compatible version of Elasticsearch: 400 Bad Request: {"error":{"root_cause":[{"type":"invalid_index_name_exception","reason":"Invalid index name [_license], must not start with '_'.","index_uuid":"_na_","index":"_license"}],"type":"invalid_index_name_exception","reason":"Invalid index name [_license], must not start with '_'.","index_uuid":"_na_","index":"_license"},"status":400}
```
