### ISSUE TITLE
Fix duplicated and missing metrics in kafka.broker metricset

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#26112]
The jolokia mapping for the kafka broker metricset contain some duplicated mbeans and attributes, reported as different names, e.g:
```
      - mbean: 'kafka.server:type=BrokerTopicMetrics,name=FailedFetchRequestsPerSec'
        attributes:
          - attr: OneMinuteRate
            field: request.fetch.failed_per_second
      ...
      - mbean: 'kafka.server:type=BrokerTopicMetrics,name=FailedFetchRequestsPerSec'
        attributes:
          - attr: OneMinuteRate
            field: request.fetch.failed
```
The `OneMinuteRate` of `kafka.server:type=BrokerTopicMetrics,name=FailedFetchRequestsPerSec` is configured to be reported both as `kafka.broker.request.fetch.failed_per_second` and `kafka.broker.request.fetch.failed`. This is probably not intended.

The `failed_per_second` field is not being reported, maybe as a result of this duplication.

Two things to check here:
- [ ] Clarify the duplicated entries, if the different values are available (absolute and per second), collect them. If not, use the per seconds only. Review docs if this is changed.
- [ ] Confirm the behaviour in the jolokia module when the same attribute is requested twice. Should it be also reported twice if the user wants to store the same value in two fields?
