### ISSUE TITLE
Dissect: ignore_failure doesn't work as expected

### ISSUE THREAD

**Issue by fdartayre** [elastic/beats#26147]
Filebeat 7.13.0

The `ignore_failure` setting in the `dissect` processor doesn't seem to work as expected and behaves as if it were `true`.

```yaml
filebeat.inputs:
- type: stdin
output.console:
  pretty: true
processors:
  - add_tags:
      tags: ['before_dissects']
      target: "tags"  
  - dissect:
      tokenizer: "%{word1} %{word2}"
      field: "message"
      target_prefix: "dissect"
      ignore_failure: false
  - dissect:
      tokenizer: "%{word1} %{word2}"
      field: "message"
      target_prefix: "dissect"
      ignore_failure: false
  - add_tags:
      tags: ['after_dissects']
      target: "tags"        
```
When the first `dissect` processor fails, the processor _should_ log an error, preventing execution of other processors if `ignore_failure` is `false` (according to https://www.elastic.co/guide/en/beats/filebeat/current/dissect.html). 

This is not what we see here:
```
{
  "@timestamp": "2021-06-01T07:54:13.072Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "7.13.0"
  },
  "tags": [
    "before_dissects",
    "after_dissects"
  ],
  "log": {
    "offset": 0,
    "file": {
      "path": ""
    },
    "flags": [
      "dissect_parsing_error",
      "dissect_parsing_error"
    ]
  },
  "message": "abc",
  "input": {
    "type": "stdin"
  },
  "ecs": {
    "version": "1.8.0"
  },
  "host": {
    "name": "fred.home"
  },
  "agent": {
    "ephemeral_id": "a18dc3ee-7a5f-440b-a062-870194fb3cf3",
    "id": "fce66f38-e7a3-4bae-aad8-40df579ee1d4",
    "name": "fred.home",
    "type": "filebeat",
    "version": "7.13.0",
    "hostname": "fred.home"
  }
}
```
The two `dissect` processors fail and all the processors are executed nonetheless. 

With `ignore_failure` set to `false` (the default) I would not expect the other processors to be executed and the event to be sent to the output.
