### ISSUE TITLE
Condition not respected when loading config from state

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#26223]
When agent is enrolled it retrieves a configuration and stores it into a state.yml file.

On restart it tries to apply this config before connecting to fleet.
It seems that even though some parts of config have conditions e.g.
```
- condition: ${host.platform} != 'windows'
      data_stream:
        dataset: system.load
        type: metrics
```

this condition is not respected.

Steps to repro:
- create a policy with system integration
- install agent on windows
- restart or change log level (causes reexec)
- look for `Error creating runner from config: 1 error: metricset 'system/load' not found` in metricbeat logs
