### ISSUE TITLE
Error fetching data for metricset elasticsearch.ml_job: HTTP error 400 when ml_job metricset not enabled

### ISSUE THREAD

**Issue by ndtreviv** [elastic/beats#26284]
elasticsearch-xpack.xml config:
```
- module: elasticsearch
  xpack.enabled: true
  period: 10s
  scope: cluster
  hosts: ["http://my-internal-elb-redacted.us-east-1.elb.amazonaws.com:9200"]
  metricsets:
    - node
    - node_stats
    - cluster_stats
    - index
    - index_recovery
    - shard
    - index_summary
    - pending_tasks
  fields: 
    cluster_name: my-cluster
```

Log message:
```
INFO#011module/wrapper.go:259#011Error fetching data for metricset elasticsearch.ml_job: HTTP error 400 in : 400 Bad Request
```

- Version: 7.12.0
- Operating System: Ubuntu 20.04 
- Discuss Forum URL: https://discuss.elastic.co/t/metricbeat-attempting-to-fetch-metrics-for-unlisted-metricset-why/271066
- Steps to Reproduce:

1. Install 7.12.0 as per instructions: 
```
curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.12.0-amd64.deb
sudo dpkg -i metricbeat-7.12.0-amd64.deb
metricbeat setup -e
sudo service metricbeat start
```

2. Enable the elasticsearch-xpack module: `metricbeat modules enable elasticsearch-xpack`

**Comment by ndtreviv** [comment]
Other interesting information is that I only get this error on nodes that are the elected master node.

**Comment by ndtreviv** [comment]
On the discuss forum someone noted that the module config specified an older verison. This was because I had upgraded metricbeat on this node, but I get the same error on fresh installs with the following config:

```
# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.x/metricbeat-module-elasticsearch.html

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["http://localhost:9200"]
  #username: "user"
  #password: "secret"
  metricsets:
    - node
    - node_stats
    - cluster_stats
    - index
    - index_recovery
    - shard
    - index_summary
    - pending_tasks
```

Also this node is not master elected.
