### ISSUE TITLE
elasticsearch-xpack shard metricset not sending metrics

### ISSUE THREAD

**Issue by ndtreviv** [elastic/beats#26314]
I'm trying to ship my monitoring stats to a separate cluster using metricbeat, but the shard metricset isn't being sent:
<img width="1440" alt="Screenshot 2021-06-15 at 09 26 16" src="https://user-images.githubusercontent.com/1530653/122019541-c99cb180-cdbb-11eb-89dc-f1417c00f41c.png">

There are no errors in the logs (follow the link to the discussion forum post and you can see some logs there).

elasticsearch-xpack config (vanilla):
```
# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.9/metricbeat-module-elasticsearch.html

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["http://localhost:9200"]
  #username: "user"
  #password: "secret"
```

metricbeat.yml:
```
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
  index.codec: best_compression

setup.kibana:
  host: "[redacted]:5601"
  ssl.verification_mode: none
  protocol: "http"

output.elasticsearch:
  hosts: ["[redacted]:9200"]
  ssl.verification_mode: none
  protocol: "http"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
  - add_fields:
      target: node
      fields:
        name: "es-live-1"
        display_name: "[redacted]:es-live-1"
        public_hostname: "[redacted]"
        cluster_name: "cluster-live"
```
- Version: 7.12.0
- Operating System: Ubuntu 20.04 LTS
- Discuss Forum URL: https://discuss.elastic.co/t/metricbeat-elasticsearch-xpack-not-reliably-sending-data-to-monitoring-cluster/275842/6
- Steps to Reproduce: 
Install metricbeat as per documented instructions: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-installation-configuration.html (but using 7.12.0)

**Comment by ndtreviv** [comment]
On the discuss forum someone noted that the module config specified an older verison. This was because I had upgraded metricbeat on this node, but I get the same error on fresh installs with the following config:

```
# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.x/metricbeat-module-elasticsearch.html

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["http://localhost:9200"]
  #username: "user"
  #password: "secret"
  metricsets:
    - node
    - node_stats
    - cluster_stats
    - index
    - index_recovery
    - shard
    - index_summary
    - pending_tasks
```
