### ISSUE TITLE
[Filebeat] Getting Unable to hash given config: missing field accessing '0.vpcflow' Error while configuring Filebeat using gcp module

### ISSUE THREAD

**Issue by rahul799** [elastic/beats#26345]
I am trying to setup Filebeat using [this](https://cloud.google.com/architecture/exporting-stackdriver-logging-elasticsearch#configure_the_module) documentation, but whenever I try to start Filebeat, it gives me an error

`Unable to hash given config: missing field accessing '0.vpcflow' `

I have attached my gcp.yaml file below
```
# Module: gcp
# Docs: https://www.elastic.co/guide/en/beats/filebeat/7.x/filebeat-module-gcp.html
- module: gcp
  vpcflow:
    enabled: false
    # Google Cloud project ID.
    var.project_id: skuad-core-dev
    # Google Pub/Sub topic containing VPC flow logs. Stackdriver must be
    # configured to use this topic as a sink for VPC flow logs.
    var.topic: els-logs
    # Google Pub/Sub subscription for the topic. Filebeat will create this
    # subscription if it does not exist.
    var.subscription_name: gcp-els-logs-sub
    # Credentials file for the service account with authorization to read from
    # the subscription.
    var.credentials_file: ${path.config}/gcp-es-service-account.json
    # Set internal networks. This is used to classify network.direction based
    # off of what networks are considered "internal" either base off of a CIDR
    # block or named network conditions. If this is not specified, then traffic
    # direction is determined by whether it is between source and destination
    # instance information rather than IP.
    #
    # For a full list of network conditions see:
    # https://www.elastic.co/guide/en/beats/filebeat/current/defining-processors.html#condition-network
    #var.internal_networks: [ "private" ]
  firewall:
    enabled: false
    # Google Cloud project ID.
    var.project_id: skuad-core-dev
    # Google Pub/Sub topic containing firewall logs. Stackdriver must be
    # configured to use this topic as a sink for firewall logs.
    var.topic: els-logs
    # Google Pub/Sub subscription for the topic. Filebeat will create this
    # subscription if it does not exist.
    var.subscription_name: gcp-els-logs-sub
    # Credentials file for the service account with authorization to read from
    # the subscription.
    var.credentials_file: ${path.config}/gcp-es-service-account.json
    # Set internal networks. This is used to classify network.direction based
    # off of what networks are considered "internal" either base off of a CIDR
    # block or named network conditions. If this is not specified, then traffic
    # is taken from the direction data in the rule_details event payload.
    #
    # For a full list of network conditions see:
    # https://www.elastic.co/guide/en/beats/filebeat/current/defining-processors.html#condition-network
    #var.internal_networks: [ "private" ]
  audit:
    enabled: true
    # Google Cloud project ID.
    var.project_id: skuad-core-dev
    # Google Pub/Sub topic containing firewall logs. Stackdriver must be
    # configured to use this topic as a sink for firewall logs.
    var.topic: els-logs
    # Google Pub/Sub subscription for the topic. Filebeat will create this
    # subscription if it does not exist.
    var.subscription_name: gcp-els-logs-sub
    # Credentials file for the service account with authorization to read from
    # the subscription.
    var.credentials_file: ${path.config}/gcp-es-service-account.json
```
I also executed `sudo filebeat test config -e` and it seems that the configuration is OK.

**Comment by andrewkroh** [comment]
I can reproduce the issue on 7.13.2.

As a workaround it works if you inline the gcp config in the main filebeat.yml as

```
filebeat.modules:
- module: gcp
  vpcflow:
    enabled: false
    var.project_id: skuad-core-dev
    var.topic: els-logs
    var.subscription_name: gcp-els-logs-sub
    var.credentials_file: ${path.config}/gcp-es-service-account.json
  firewall:
    enabled: false
    var.project_id: skuad-core-dev
    var.topic: els-logs
    var.subscription_name: gcp-els-logs-sub
    var.credentials_file: ${path.config}/gcp-es-service-account.json
  audit:
    enabled: true
    var.project_id: skuad-core-dev
    var.topic: els-logs
    var.subscription_name: gcp-els-logs-sub
    var.credentials_file: ${path.config}/gcp-es-service-account.json
```

**Comment by andrewkroh** [comment]
Removing `${path.config}` also appears to fix the problem.

**Comment by andrewkroh** [comment]
So it appears to be an issue resolving the `path.config` variable from separately loaded module.d yaml files. When `HashConfig` executes it cannot resolve `path.config` and you get the error above.

https://github.com/elastic/beats/blob/23e4403ae093fcc8f7905345cad2c7ad256976d8/libbeat/cfgfile/list.go#L157-L164

I tried injecting the variable info the loaded config via `config.SetString("path.config", -1, path.Paths.Config)` and this makes the `HashConfig` work, but then when the module is loaded it fails to resolve `path.config` again. I think that is because a new config is created and the `path.config` variables is lost.

https://github.com/elastic/beats/blob/17bee6a93476a561ef85ded9a47a8af94c536abf/libbeat/cfgfile/list.go#L175-L177

**Comment by wasserman** [comment]
@andrewkroh Same issue when using filebeat inputs.  I'm using the httpjson input type with a script referenced in an external file and encountered the following error:
`Unable to hash given config: missing field accessing '0.processors' `

I suspect the same fix will cover this scenario, but I thought it was worth mentioning.

Here's a sample input:
```
- type: httpjson
  config_version: 2
  request.url: "https://justatest"
  request.method: GET

  processors:
    - script:
        lang: javascript
        file: ${path.config}/justascript.js
```
