### ISSUE TITLE
Improve timestamp processor millis

### ISSUE THREAD

**Issue by SilvM** [elastic/beats#26360]
**Describe the enhancement:**
Improve timestamp processor so that the separator can be characters other than `.` or `,`.
Sometimes other symbols are used to separate milliseconds from seconds (e.g. `:`).

This current limitation should also be made clear in the documentation, that due to the go time package it's not possible ([Ref](https://github.com/golang/go/issues/6189))

**Describe a specific use case for the enhancement or feature:**
```
    - timestamp:
        field: "temp_timestamp"
        layouts:
          - "01/02/2006 15:04:05:999 MST"
        test:
          - "06/17/2021 05:19:48:792 UTC"
```

The only way I think I can parse these logs now is to use the script processor.
