### ISSUE TITLE
[Heartbeat] Fix null pointer in per-monitor SSL setting

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#26391]
Per https://discuss.elastic.co/t/heartbeat-panic-error-using-ssl-verification-mode-none/276396 heartbeat will crash when a config does not explicitly set `enabled: <value>` in a nested SSL block. See the config below for example:

```yaml
heartbeat.monitors:
- type: http
  enabled: true
  id: anId
  name: aName
  urls: ["https//private.fr:59862"]
  schedule: '@every 10s'
  check.response.status: 200
  ssl.verification_mode: none
  #uncommenting the line below is a workaround
  #ssl.enabled: true
```
