### ISSUE TITLE
Filebeat 5.0.0-beta1 not always removing deleted files from registry

### ISSUE THREAD

**Issue by doingitbigdata** [elastic/beats#2646]
- Version: filebeat version 5.0.0-beta1 (amd64), libbeat 5.0.0-beta1
- Operating System: Red Hat Enterprise Linux Server release 6.5 (Santiago)

I'm having an issue where a deleted file is not being removed from the registry. The entry in the registry persists and I can see the timestamp for the entry increasing over time.

I do not have the clean_removed parameter specified in filebeat.yml therefore it should be enabled by default. 

I do have the clean_inactive and ignore_older parameters specified and I am deleting the file before these time periods have been reached. I am able to reproduce this result repeatedly.

I do not see this issue when I don't have the clean_inactive and ignore_older parameters specified.

**Comment by ruflin** [comment]
Can you share your full config file? It would also be very helpful to get the log file from filebeat if available? Can you also share the steps you take to reproduce it?

**Comment by passing** [comment]
having the same issue using filebeat-5.0.0-beta1-linux-x86_64

our configuration is:
```
filebeat.prospectors:
- input_type: log
  paths:
    - /nasdevices/jobs-logs/logs/*/*/*.log
  document_type: application_log
  multiline:
    pattern: ^[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2},[0-9]{3} \[
    negate: true
    match: after
    max_lines: 500
    timeout: 5s
  ignore_older: 24h
  clean_inactive: 25h
  close_removed: true
  clean_removed: true
name: jobs-logs-shipper
tags: ["log4j"]
output.logstash:
  hosts: ["10.0.0.99:5044"]
```

using this script to check for files in the registry that are not on disk any more:
```
#!/bin/bash

total=0
existing=0
missing=0

tempfile=`mktemp`
sed -e "s/},{/\n/g" data/registry | grep -oE "/nas[^\"]*.log" > $tempfile

while read file
do
	if [ -f $file ]
	then
		((existing++))
	else
		((missing++))
	fi
	((total++))
done < $tempfile

rm $tempfile

echo "existing: $existing"
echo "missing:  $missing"
echo "total:    $total"
```
the number of 'missing' files is growing slowly over time
