### ISSUE TITLE
Collect pipeline stats from logstash

### ISSUE THREAD

**Issue by robin13** [elastic/beats#26519]
**Describe the enhancement:**

Currently the metricbeat logstash module collects only the Event Stats under the `node_stats` metric. It would be useful for analysing logstash pipeline performance to also collect the pipeline stats:
https://www.elastic.co/guide/en/logstash/current/node-stats-api.html#pipeline-stats

**Comment by ChrsMark** [comment]
cc: @sayden

**Comment by sayden** [comment]
Hi @robin13 :slightly_smiling_face:  I'm coming a bit late here but the `node_stats` metricset queries `_node/stats` which includes the data from the `/pipelines` that is mention on the link. This should be under any doc fetched with Metricbeat under the path `logstash_stats.pipelines.[].*` where you can see events, reloads, etc.

So I'm assuming I'm understanding something wrong so you can tell me one single metric you are looking for from the response so I double check? It might also be the case that what you mean is that it's visible in the Stack Monitoring UI perhaps?

**Comment by businessbean** [comment]
Currently we have to use the Logstash [http_poller](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http_poller.html) plugin to collect the node stats.
```bash
input {
  http_poller {
    id => "http_poller_${HOSTNAME}"
    urls => {
      logstash => {
        method => get
        url => "http://localhost:9600/_node/stats/pipelines?pretty"
        headers => {
          Accept => "application/json"
        }
     }
    }
    request_timeout => 60
    schedule => { cron => "* * * * * UTC"}
    codec => "json"
    metadata_target => "http_poller_metadata"
    tags => [ "metric", "http_poller" ]
  }
}
```
This is quite a hack and it doesn't follow the Elastic Common Schema. In general it would help if the Beats components out of the box would support all Elastic products. 

@richardgilm fyi...

**Comment by businessbean** [comment]
The [fields](https://github.com/elastic/beats/blob/master/metricbeat/module/logstash/fields.go#L35) definition in the master branch contains that: 
```yaml
- key: logstash
  title: "Logstash"
  description: >
    Logstash module
  release: ga
  settings: ["ssl", "http"]
  short_config: false
  fields:
    - name: logstash_stats
      type: group
      fields:
        - name: timestamp
          type: alias
          path: "@timestamp"
        - name: jvm
          type: group
          fields:
            - name: mem
              type: group
              fields:
                - name: heap_used_in_bytes
                  type: alias
                  path: logstash.node.stats.jvm.mem.heap_used_in_bytes
                - name: heap_max_in_bytes
                  type: alias
                  path: logstash.node.stats.jvm.mem.heap_max_in_bytes
            - name: uptime_in_millis
              type: alias
              path: logstash.node.stats.jvm.uptime_in_millis
        - name: events
          type: group
          fields:
            - name: in
              type: alias
              path: logstash.node.stats.events.in
            - name: out
              type: alias
              path: logstash.node.stats.events.out
            - name: duration_in_millis
              type: alias
              path: logstash.node.stats.events.duration_in_millis
        - name: logstash
          type: group
          fields:
            - name: uuid
              type: alias
              path: logstash.node.stats.logstash.uuid
            - name: version
              type: alias
              path: logstash.node.stats.logstash.version
        - name: pipelines
          type: nested
        - name: os
          type: group
          fields:
            - name: cpu
              type: group
              fields:
                - name: stat
                  type: group
                  fields:
                    - name: number_of_elapsed_periods
                      type: alias
                      path: logstash.node.stats.os.cgroup.cpu.stat.number_of_elapsed_periods
                    - name: time_throttled_nanos
                      type: alias
                      path: logstash.node.stats.os.cgroup.cpu.stat.time_throttled_nanos
                    - name: number_of_times_throttled
                      type: alias
                      path: logstash.node.stats.os.cgroup.cpu.stat.number_of_times_throttled
                - name: load_average
                  type: group
                  fields:
                    - name: 15m
                      type: alias
                      path: logstash.node.stats.os.cpu.load_average.15m
                    - name: 1m
                      type: alias
                      path: logstash.node.stats.os.cpu.load_average.1m
                    - name: 5m
                      type: alias
                      path: logstash.node.stats.os.cpu.load_average.5m
            - name: cgroup
              type: group
              fields:
                - name: cpuacct.usage_nanos
                  type: alias
                  path: logstash.node.stats.os.cgroup.cpuacct.usage_nanos
        - name: process.cpu.percent
          type: alias
          path: logstash.node.stats.process.cpu.percent
        - name: queue.events_count
          type: alias
          path: logstash.node.stats.queue.events_count
    - name: logstash_state
      type: group
      fields:
        - name: pipeline.id
          type: alias
          path: logstash.node.state.pipeline.id
        - name: pipeline.hash
          type: alias
          path: logstash.node.state.pipeline.hash
    - name: logstash
      type: group
      fields:
        - name: node
          type: group
          description: >
            node
          release: ga
          fields:
        - name: node
          type: group
          description: >
            node_stats metrics.
          release: ga
          fields:
            - name: state.pipeline
              type: group
              fields:
                - name: id
                  type: keyword
                - name: hash
                  type: keyword
            - name: host
              type: alias
              path: host.hostname
              migration: true
              description: >
                Host name
            - name: version
              type: alias
              path: service.version
              migration: true
              description: >
                Logstash Version
            - name: jvm
              type: group
              description: >
                JVM Info
              fields:
                - name: version
                  type: keyword
                  description: >
                    Version
                - name: pid
                  type: alias
                  path: process.pid
                  migration: true
                  description: >
                    Process ID
            - name: stats
              type: group
              fields:
                - name: jvm
                  type: group
                  fields:
                    - name: uptime_in_millis
                      type: long
                    - name: mem
                      type: group
                      fields:
                        - name: heap_used_in_bytes
                          type: long
                        - name: heap_max_in_bytes
                          type: long
                - name: events
                  type: group
                  description: >
                    Events stats
                  fields:
                    - name: in
                      type: long
                      description: >
                        Incoming events counter.
                    - name: out
                      type: long
                      description: >
                        Outgoing events counter.
                    - name: filtered
                      type: long
                      description: >
                        Filtered events counter.
                    - name: duration_in_millis
                      type: long
                - name: logstash
                  type: group
                  fields:
                    - name: uuid
                      type: keyword
                    - name: version
                      type: keyword
                - name: os
                  type: group
                  fields:
                    - name: cpu
                      type: group
                      fields:
                        - name: load_average
                          type: group
                          fields:
                            - name: 15m
                              type: long
                            - name: 1m
                              type: long
                            - name: 5m
                              type: long
                    - name: cgroup
                      type: group
                      fields:
                        - name: cpuacct.usage_nanos
                          type: long
                        - name: cpu
                          type: group
                          fields:
                            - name: stat
                              type: group
                              fields:
                                - name: number_of_elapsed_periods
                                  type: long
                                - name: time_throttled_nanos
                                  type: long
                                - name: number_of_times_throttled
                                  type: long
                - name: process.cpu.percent
                  type: double
                - name: pipelines
                  type: nested
                  fields:
                    - name: id
                      type: keyword
                    - name: hash
                      type: keyword
                    - name: queue
                      type: group
                      fields:
                        - name: events_count
                          type: long
                        - name: type
                          type: keyword
                        - name: queue_size_in_bytes
                          type: long
                        - name: max_queue_size_in_bytes
                          type: long
                    - name: events
                      type: group
                      fields:
                        - name: out
                          type: long
                        - name: duration_in_millis
                          type: long
                    - name: vertices
                      type: group
                      fields:
                        - name: duration_in_millis
                          type: long
                        - name: events_in
                          type: long
                        - name: pipeline_ephemeral_id
                          type: keyword
                          description: pipeline_ephemeral_id
                        - name: events_out
                          type: long
                          description: events_out
                        - name: id
                          type: keyword
                          description: id
                        - name: queue_push_duration_in_millis
                          type: float
                          description: queue_push_duration_in_millis
                - name: queue.events_count
                  type: long
```

The `- name: pipelines` section looks promising, but with metricbeat 7.14.2 no pipeline metrics are available
<img width="2764" alt="image" src="https://user-images.githubusercontent.com/43000876/141328789-01d925e7-c198-4ed2-a55c-b3e161e6b8c5.png">

It seems that only a few steps are missing...
