### ISSUE TITLE
Invalid property value doesn't log an error

### ISSUE THREAD

**Issue by n0othing** [elastic/beats#26685]
- Version: `7.13.2`
- Operating System: MacOS 11.4 
- Steps to Reproduce:

Came across a scenario where Metricbeat's module config block had an invalid value of `enabled` for `reload.enabled`:

```YAML
# =========================== Modules configuration ============================

metricbeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: enabled

  # Period on which files under path should be checked for changes
  #reload.period: 10s
``` 

Metricbeat starts fine with the above, but never loads any modules. There's no warning in the logs to indicate a configuration problem.
