### ISSUE TITLE
[Heartbeat] Add tag based filtering support when running synthetic monitors

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/beats#26747]
**Describe the enhancement:**

The synthetics agent already supports both tags based filtering via the `--tags tag-a, tag-b` and other glob based filtering via `--match`. We need the same capability like how tags are used in ICMP based monitors and extend it to the synthetic monitors. 

```yaml
- type: browser
  id: browser-inline
  filter_journeys: 
    tags: ["home", "app"]
    match: ["foo"]
  name: browser-inline
  schedule: "@every 1m"


```

These applied tags would then be mapped under each monitor on the Kibana Uptime UI.
