### ISSUE TITLE
Filebeat RPM installation doesn't seem to honor default log location when started with systemd

### ISSUE THREAD

**Issue by 111andre111** [elastic/beats#26802]
Downloaded RPM package to CentOS7 or RHEL7

Configued a quite default filebeat.yml:
```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/boot.log
- type: filestream
  enabled: false
  paths:
    - /var/log/*.log
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
output.file:
  path: "/tmp"
  filename: filebeat
processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~
```

systemd file looks like this:
```
[Unit]
Description=Filebeat sends log files to Logstash or directly to Elasticsearch.
Documentation=https://www.elastic.co/products/beats/filebeat
Wants=network-online.target
After=network-online.target
[Service]
Environment="GODEBUG='madvdontneed=1'"
Environment="BEAT_LOG_OPTS="
Environment="BEAT_CONFIG_OPTS=-c /etc/filebeat/filebeat.yml"
Environment="BEAT_PATH_OPTS=--path.home /usr/share/filebeat --path.config /etc/filebeat --path.data /var/lib/filebeat --path.logs /var/log/filebeat"
ExecStart=/usr/share/filebeat/bin/filebeat --environment systemd $BEAT_LOG_OPTS $BEAT_CONFIG_OPTS $BEAT_PATH_OPTS
Restart=always
[Install]
WantedBy=multi-user.target
```
ps aux output is like this:
```
root 6169 2.3 6.4 1019804 121284 ? Ssl 4:50 0:05 /usr/share/filebeat/bin/filebeat --environment systemd -c /etc/filebeat/filebeat.yml --path.home /usr/share/filebeat --path.config /etc/filebeat --path.data /var/lib/filebeat --path.logs /var/log/filebeat
```
So the impression of all of this parameter situation `--path.logs /var/log/filebeat` looks like the logs should have its home here `/var/log/filebeat`, but that doesn't happen.
If you start filebeat via normal `systemtl start filebeat` the logs are landing here: `/var/log/message`.

So the question is why exactly does that happen? Seems like a bug.
