### ISSUE TITLE
add_process_metadata fails to parse pid from valid integer fields

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#26830]
For confirmed bugs, please report:
- Version: n/a
- Operating System: any
- Discuss Forum URL: https://discuss.elastic.co/t/add-process-metadata-cannot-parse-pid-in-integer/263380
- Steps to Reproduce: 

Ingest the following JSON document:
`{"pid": 1}`

using Filebeat with this sample config:
```
logging.level: debug
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
filebeat.inputs:
- type: log
  paths:
  - /tmp/document.json
  json.keys_under_root: false
  processors:
  - add_process_metadata:
      match_pids:
      - json.pid
      ignore_missing: false
output.console:
  pretty: true
```

It will fail with an error:

> Fail to apply processor [...] error applying add_process_metadata processor: cannot parse field 'json.pid' (not an integer or string)

A temporary workaround is to convert the field to string with the `convert` processor:

```
- convert:
    fields:
    - {from: "json.pid", to: "pr.pid", type: "string"}
```
