### ISSUE TITLE
[Docs] Clarify source of @timestamp field in Microsoft Defender ATP

### ISSUE THREAD

**Issue by faec** [elastic/beats#26866]
Our [documentation](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-microsoft.html#_defender_atp_ecs_fields) lists the `alertCreationTime` field as the source for the ECS field `@timestamp`, but in the actual pipeline this value seems to be overwritten by `alertUpdateTime`, when present:

```yml
- set:
    field: '@timestamp'
    value: '{{json.alertUpdateTime}}'
    if: ctx.json?.alertUpdateTime != null
```

The documentation should clarify the real source of the `@timestamp` field for Defender ATP.
