### ISSUE TITLE
Cisco ASA Ingress Fixes

### ISSUE THREAD

**Issue by trexx** [elastic/beats#26869]
A small modification to the grok pattern for message-id 106023 to match the message when an IANA protocol number is used in place of the protocol name. For example, for GRE.

Example:
%ASA-4-106023: Deny protocol 47 src outside:100.66.124.24 dst inside:172.31.98.44 by access-group "inbound"

https://github.com/elastic/beats/blob/v7.13.3/x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml#L271

```
+ ^%{NOTSPACE:event.outcome} (protocol )?%{NOTSPACE:network.transport} src %{NOTSPACE:cisco.asa.source_interface}:%{IPORHOST:source.address}(/%{POSINT:source.port})?\\s*(%{GREEDYDATA:_temp_.source_username} )?dst %{NOTSPACE:cisco.asa.destination_interface}:%{IPORHOST:destination.address}(/%{POSINT:destination.port})?%{DATA}by access.group \"%{NOTSPACE:cisco.asa.rule_name}\"
```

**Comment by trexx** [comment]
Another one we came across for message-id 304001.  The grok pattern doesn't expect there to be a source username in the log message.

Example:
USER001@192.168.0.1(LOCAL\USER001) Accessed URL 172.17.6.211:http://testingserver.com/somewebpage.html

https://github.com/elastic/beats/blob/v7.13.3/x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml#L369
```
+ "%{IP:source.address}(\\(%{NOTSPACE:source.user.name}\\))? %{DATA} (%{NOTSPACE}@)?%{IP:destination.address}:%{GREEDYDATA:url.original}"
```

**Comment by legoguy1000** [comment]
Easy to fix.  I should have a PR up shortly.

**Comment by trexx** [comment]
Still going though my grok errors.

Ran in to a problem with IPV6 addresses for message-id 106023
https://github.com/elastic/beats/blob/v7.13.3/x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml#L271

Example:
Deny icmp src OUTSIDE:2a05:d016:add:4002:91f2:a9b2:e09a:6fc6 dst OUTSIDE:fe00:afa0::1 (type 128, code 0) by access-group "OUTSIDE_in"

This results in the src/dst interface including part of the IPv6 address and the resulting address field only containing the last characters after the last colon. It also looks like this particular pattern isn't consistent with others in the pipeline.
Using NOTCOLON, ECSSOURCEIPORHOST, and ECSDESTIPORHOST fixes these for me.

```yml
patterns:
  - ^%{NOTSPACE:event.outcome} %{NOTSPACE:network.transport} src %{NOTCOLON:_temp_.cisco.source_interface}:%{ECSSOURCEIPORHOST}(/%{POSINT:source.port})?\s*(%{GREEDYDATA:_temp_.cisco.source_username} )?dst %{NOTCOLON:_temp_.cisco.destination_interface}:%{ECSDESTIPORHOST}(/%{POSINT:destination.port})?%{DATA}by access.group "%{NOTSPACE:_temp_.cisco.list_id}"
pattern_definitions:
  NOTCOLON: "[^:]*"
  ECSSOURCEIPORHOST: "(?:%{IP:source.address}|%{HOSTNAME:source.domain})"
  ECSDESTIPORHOST: "(?:%{IP:destination.address}|%{HOSTNAME:destination.domain})"
```
