### ISSUE TITLE
Problem with filebeat “failed to add target to root”

### ISSUE THREAD

**Issue by NailBash** [elastic/beats#26908]
Hello, I try to decode escaped_json using "decode_json_fields" processor. I want to add my extracted  json fields to root. But in log I see this error:
```
 DEBUG   [processors]    processing/processors.go:128    Fail to apply processor global{decode_json_fields=message}: failed to add target to root
```
What it can mean?

My filebeat processors config looks like:
```
processors:
  - decode_json_fields:
      fields: ["message"]
      process_array: true
      target: ''
      max_depth: 200
      overwrite_keys: true
```
Message looks like:
```
"message":"[{\"ecs\":{\"version\":\"1.8.0\"},\"rule\":{\"firedtimes\":275,\"pci_dss\":[\"10.2.5\"],\"gpg13\":[\"7.1\",\"7.2\"],\"nist_800_53\":[\"AU.14\",\"AC.7\"],\"hipaa\":[\"164.312.b\"],\"level\":3,\"mail\":false,\"id\":\"60106\",\"tsc\":[\"CC6.8\",\"CC7.2\",\"CC7.3\"],\"mitre\":{\"id\":[\"T1078\"],\"technique\":[\"ValidAccounts\"],\"tactic\":[\"Defense Evasion\",\"Initial Access\",\"Persistence\",\"Privilege Escalation\"]}]"
```
Filebeat versions - 7.9.3, 7.10.0, 7.10.2 - tried all 3 with same result.
