### ISSUE TITLE
Filebeat 5.0.0-beta1 is failing to ship a portion of a file.

### ISSUE THREAD

**Issue by ckmcd** [elastic/beats#2697]
- Version: 5.0.0-beta1
- Operating System: Linux XXXXX  2.6.32-573.12.1.el6.x86_64 #1 SMP Mon Nov 23 12:55:32 EST 2015 x86_64 x86_64 x86_64 GNU/Linu

I discovered an issue where I had missing log messages in Elasticsearch.  I found the missing messages in a local log file.  I found the file in question in the registry and discovered that the file had not been completely shipped.  i.e. the registry offset was less than the file's size.

Here is my config

```
filebeat:
  prospectors:
    -
      paths:
        - /opt/mount1/sa-stats/log/local/fast/*.log
        encoding: plain
      input_type: log
      close_removed: true
      clean_removed: true
      document_type: log4j-itg
      multiline:
        pattern: "^[0-9]{4}-[0-9]{2}-[0-9]{2}T([0-9]{2}:){2}[0-9]{2},[0-9]"
        negate: true
        match: before
```

Note these files are being rotated (renamed) by log4j so we are seeing Filebeat logs like.

```
/usr/local/st/filebeat5/logs/filebeat.log.3:2016-09-30T13:01:36Z INFO File is inactive: /opt/mount1/sa-stats/log/local/fast/fast.log. Closing because close_inactive of 5m0s reached.
/usr/local/st/filebeat5/logs/filebeat.log.3:2016-09-30T15:50:04Z INFO File is inactive: /opt/mount1/sa-stats/log/local/fast/fast.log. Closing because close_inactive of 5m0s reached.
/usr/local/st/filebeat5/logs/filebeat.log.3:2016-09-30T15:55:43Z INFO File is inactive: /opt/mount1/sa-stats/log/local/fast/fast.log. Closing because close_inactive of 5m0s reached.
/usr/local/st/filebeat5/logs/filebeat.log.3:2016-09-30T16:06:23Z INFO File is inactive: /opt/mount1/sa-stats/log/local/fast/fast.log. Closing because close_inactive of 5m0s reached.
```

The weird thing is that I see no new harvesters being started.

Restarting Filebeat caused new harvesters to be created for the renamed files and they were entirely shipped.
- Steps to Reproduce:
