### ISSUE TITLE
7.13.2 sometime will write disk a file that name checkpoint.new

### ISSUE THREAD

**Issue by zt9788** [elastic/beats#27058]
beat:
filebeat
version: 
7.13.2
Modules : None
System: ubuntu

filebeat will Write a new "checkpoint.new" file to the hard disk every few seconds
file content ≈ log.json

yml(simple):

```
  path.data: /data/
  path.logs: /data/
  max_procs: 1                            
  filebeat.inputs:
  
  - type: log  
    enabled: true  
    paths:
      - ....
    fields:
      logResource: "..."
    tags: ["..."]
    tail_files: true  
  
  ignore_older: 48h
  clean_inactive: 72h
  
  filebeat.config.modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
  
 
  setup.template.settings:  
    index.number_of_shards: 1
    #index.codec: best_compression
    #_source.enabled: false
  
  
  setup.kibana:
    host: "...."
  
  tail_files: true                                                                                                                            
  setup.template.settings:                                                                                                                    
    index.number_of_shards: 1                                                                                                                 
    index.number_of_replicas: 1                                                                                                               
  setup.ilm.enabled: true                                                                                                                                                                                                                         
                                                                                                                                              
  output.kafka:                                                                                                                               
    hosts: ...
    topic: "%{[fields.logResource]}"                                                                                                                           
    required_acks: 1  
    keep_alive: 30s   
  
  processors:
    - add_host_metadata: ~
    - add_cloud_metadata: ~
    - add_docker_metadata: ~
    - add_kubernetes_metadata: ~
  
  xpack.monitoring.enabled: true
  xpack.monitoring.elasticsearch.username: ...
  xpack.monitoring.elasticsearch.password: ...
  xpack.monitoring.elasticsearch.hosts: [...]
```
