### ISSUE TITLE
Improve support of kubernetes pod autodiscover with limited permissions

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#27161]
A possible use case of Kubernetes autodiscover is to discover pods in a multi-tenant cluster, where the Beats operator doesn't have any cluster-level permissions.

Despite this limitation, it should be possible to discover pods running in specific namespaces using a node-scope configuration limited to a namespace. This is not possible at the moment because node and namespace metadata enrichment tries to obtain information at the cluster level, and somehow this prevents autodiscover to work in general.

It'd be nice to try to obtain the node and namespace information without cluster-level requests. Or, if this is not possible, keep autodiscover working without enriching with node and namespace metadata.

----

To reproduce the issue, metricbeat can be configured with something like this:
```
    metricbeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          namespace: somenamespace
          resource: pod
          scope: node
          templates:
            ...
```
And a service account with permissions limited to the namespace, like the following one:
```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat
  namespace: somenamespace
  labels:
    k8s-app: metricbeat
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: metricbeat-pods
  namespace: somenamespace
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: metricbeat-pods
  namespace: somenamespace
subjects:
  - kind: ServiceAccount
    name: metricbeat
    namespace: somenamespace
roleRef:
  kind: Role
  name: metricbeat-pods
  apiGroup: rbac.authorization.k8s.io
```

With the previous configuration, errors like the following ones happen:
```
E0730 16:46:06.716656       7 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.4/tools/cache/reflector.go:156: Failed to watch *v1.Node: failed to list *v1.Node: nodes "kind-control-plane" is forbidden: User "system:serviceaccount:alas:metricbeat" cannot list resource "nodes" in API group "" at the cluster scope
```
```
E0730 16:55:08.445618       8 reflector.go:127] pkg/mod/k8s.io/client-go@v0.19.4/tools/cache/reflector.go:156: Failed to watch *v1.Namespace: failed to list *v1.Namespace: namespaces is forbidden: User "system:serviceaccount:alas:metricbeat" cannot list resource "namespaces" in API group "" at the cluster scope
```

Disabling node and namespace enrichment doesn't seem to help:
```
          add_resource_metadata:
            node.enabled: false
            namespace.enabled: false
```

The only way I have found to workaround this problem and keep autodiscover working is to add the following cluster-scope permissions:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat
  labels:
    k8s-app: metricbeat
rules:
- apiGroups: [""]
  resources:
  - nodes
  - namespaces
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: metricbeat
subjects:
- kind: ServiceAccount
  name: metricbeat
  namespace: alas
roleRef:
  kind: ClusterRole
  name: metricbeat
  apiGroup: rbac.authorization.k8s.io
```

----

Related issues:
* https://github.com/elastic/beats/issues/25290
