### ISSUE TITLE
[Elastic Agent] Enrollment via proxy generates invalid fleet.yml (Agent won't start up correctly)

### ISSUE THREAD

**Issue by urso** [elastic/beats#27187]
For confirmed bugs, please report:
- Version: 7.14
- Operating System: Any

When enrolling Agent via proxy using `--proxy-url` the fleet.yml becomes invalid, as the URL is serialized as Object:

```
  proxy_url:
    scheme: http
    opaque: ""
    user: null
    host: 10.1.4.118:3128
    path: ""
    rawpath: ""
    forcequery: false
    rawquery: ""
    fragment: ""
    rawfragment: ""
```

The `proxy_url` must be a string.
