### ISSUE TITLE
Investigate AWS Billing to allow group by with multiple fields

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#27219]
AWS metricbeat module allows for specifying the "query" to be sent to AWS billing api, but then the data returned is static. So if you create 2 querys in the module config lets say "group_by tag:created_by" and "group_by linked_acccount" What happens is you have data returned from 2 queries where you have the cost "grouped by the tag created_by" and you have cost "grouped by linked_account". Now if you wanted to view "all the resources created by X in linked account Y" this filter will not work since there's data indexed by these 2 queries does not reference each other.

Here is the current billing metricset config: 
```
- module: aws
  period: 24h
  metricsets:
    - billing
  cost_explorer_config:
    group_by_dimension_keys:
      - "AZ"
      - "INSTANCE_TYPE"
      - "SERVICE"
      - "LINKED_ACCOUNT"
    group_by_tag_keys:
      - "aws:createdBy"
```

Instead of returning an event per group by key, we should look into the AWS billing API or in Metricbeat to see if we can combine them into one event.
