### ISSUE TITLE
[Elastic Agent] Adding synthetics/tcp input does not work

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#27277]
Adding the synthetics integration with the synthetics/tcp input does not work in 7.14 and throws errors and the Elastic Agent does unhealthy. As the errors are thrown by filebeat I suspect this might be a bug in routing the input type in the Elastic Agent. Further investigation is needed.

**Comment by dominiqueclarke** [comment]
This was also reported in https://discuss.elastic.co/t/elastic-agent-with-synthetics-integration-adding-tcp-monitor-break-the-agent/280651/2.

The TCP monitor appears to "work" in the sense that documents are sent ES and the monitor is visible in Uptime, but the elastic-agent remains unhealthy due to the filebeat error.

**Comment by andrewvc** [comment]
Here's a sample config, which has the proper type `synthetics/tcp`

```
- id: f5cfff1e-b13f-466a-9800-701a8f8a7251
    name: TCP
    revision: 1
    type: synthetics/tcp
    use_output: default
    meta:
      package:
        name: synthetics
        version: 0.17.0
    data_stream:
      namespace: default
    streams:
      - id: synthetics/tcp-tcp-f5cfff1e-b13f-466a-9800-701a8f8a7251
        name: TCP
        type: tcp
        data_stream:
          dataset: tcp
          type: synthetics
        hosts: 'localhost:18278'
        schedule: '@every 3m'
        timeout: 16s
        proxy_use_local_resolver: false
        processors:
          - add_observer_metadata:
              geo:
                name: Fleet managed
          - add_fields:
              target: ''
              fields:
                monitor.fleet_managed: true
```
