### ISSUE TITLE
Allow disabling of Cache within DNS processor

### ISSUE THREAD

**Issue by BenB196** [elastic/beats#27339]
**Describe the enhancement:**

The DNS processor cache settings:

```
success_cache.capacity.initial
success_cache.capacity.max
failure_cache.capacity.initial
failure_cache.capacity.max
```

Must currently have a value >= 1, meaning that there will always be at least 1 record cached.

I'd like to disable caching in the DNS processor, either by setting to 0, or having an additional setting to disable it.

**Describe a specific use case for the enhancement or feature:**

The use case for disabling caching, is for testing/monitoring a DNS server.

Currently Elastic doesn't offer a good way of monitoring DNS servers directly, however, you can kind of do it with a config like so in Heartbeat:

```
      - hosts:
        - 192.168.0.1 #DNS server IP
        id: pdns-dns-check
        name: PDNS DNS TCP Check
        ports:
        - 53
        - dns:
            action: append
            failure_cache:
              capacity.initial: 1
              capacity.max: 1
            fields:
              monitor.ip: url.domain
            nameservers:
            - 192.168.0.1 #DNS server IP
            success_cache:
              capacity.initial: 1
              capacity.max: 1
            tag_on_failure:
            - _dns_reverse_lookup_failed
            timeout: 500ms
            transport: udp
            type: reverse
        schedule: '@every 5s'
        type: tcp
```

You can then look for the tag `_dns_reverse_lookup_failed` to see if the DNS server is having issues.

The problem is that since the cache cannot be disabled, the record could be cached, and if a long TTL is set on the record, it might prevent for the detection of the DNS server having the issue. Therefore it'd be ideal if you could disable the cache on the DNS processor.
