### ISSUE TITLE
[filebeat] How to keep hardware ip instead of filebeat ip

### ISSUE THREAD

**Issue by benbenai7786** [elastic/beats#27690]
Hi guys, need your help.

I deploy filebeat in the kubernetes with helm to recieve cisco asa syslog, and expose udp nodeport to let asa syslog report to it.
Here is my filebeat.yml:
```
deployment:
  enabled: true
  filebeatConfig:
    filebeat.yml: |
      filebeat.modules:
      - module: cisco
        asa:
          var.syslog_host: 0.0.0.0
          var.syslog_port: 9001
          var.log_level: 6
      filebeat.config.modules:
        reload.enabled: true
        path: ${path.config}/modules.d/*.yml

      output.elasticsearch:
        hosts: ["logging-elastic-es-http.elastic-system:9200"]
        username: "elastic"
        password: "XXXXXXXXXXX"
        index: "syslog-asa-%{+yyyy.MM.dd}"
      setup.ilm.enabled: false
      setup.template.overwrite: true
      setup.template.name: "syslog"
      setup.template.pattern: "syslog-asa-*"

      processors:
       - drop_fields:
           when:
             equals:
               event.module: "cisco"
           fields: ["agent.ephemeral_id","agent.hostname","agent.id","agent.type","agent.version","host.name"]
```

But here is the data view in es:
```
host.address  10.126.115.13
host.name  10-126-115-13.kubernetes.default.svc.cluster.local
input.type  udp
log.level  informational
log.source.address  10.126.115.13:49191
```

10.126.115.13 is the node ip which is the filebeat pod in.
This is not my original thought, I want to keep the asa hardware ip for searching, anyone know how to let filebeat not change the host and logsource ip? my filebeat version is filebeat:8.0.0
