### ISSUE TITLE
filebeat kafka output show "retryer: send unwait signal to consumer"

### ISSUE THREAD

**Issue by gigayou** [elastic/beats#27728]
hi everyone,  one of my servers that installed filebeat use kafka output,  and it output anothor server(installed kafka), but result always show retryer: send unwait signal to consumer, confused..

kafka version: 0.10.2 
my filebeat.yml input&output config like this:

input:  
```
filebeat.inputs:

# Each - is an input. Most options can be set at the input level, so
# you can use different inputs for various configurations.
# Below are the input specific configurations.

- type: log

  # Change to true to enable this input configuration.
  enabled: true

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /var/log/test.log
```

output:  
```
# ------------------------------ Kafka Output -------------------------------
output.kafka:
  hosts: ["KAFKA0:9092"]
  topic: "test"
  enabled: true
  version: 0.10.2
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
  codec.json:
    pretty: false
```
