### ISSUE TITLE
Update Nginx module docs to include more thorough Ingress Controller config example

### ISSUE THREAD

**Issue by n0othing** [elastic/beats#27813]
**Describe the enhancement:**

The current Nginx module docs provide an example of how to configure Filebeat to harvest Nginx Ingress Controller logs:

```YAML
- module: nginx
  ingress_controller:
    enabled: true
    var.paths: ["/path/to/log/nginx/ingress.log"]
```

On K8s, users will typically have the Ingress Controller's logs written to the pod's log, and it's reasonable to translate the above config to something like the following `autodiscover` config:

```YAML
config:
- module: nginx
  ingress_controller:
    enabled: true
    input:
      type: container
      paths:
        - "/var/log/containers/*${data.kubernetes.container.id}.log"
```

Unfortunately, this has the potential [1] for `stderr` events to get read in by the `ingress_controller` fileset which won't get parsed correctly. Instead, it'd be helpful to show an example of harvesting the `ingress_controller` fileset from `stdout` + the `error` fileset from `stderr`, all from the same pod log:

```YAML
config:
- module: nginx
  error:
    enabled: true
    stream: stderr
    input:
      type: container
      paths:
        - "/var/log/containers/*${data.kubernetes.container.id}.log"
  ingress_controller:
    enabled: true
    stream: stdout
    input:
      type: container
      paths:
        - "/var/log/containers/*${data.kubernetes.container.id}.log"
```

[1] https://docs.nginx.com/nginx-ingress-controller/logging-and-monitoring/logging/
