### ISSUE TITLE
Metricbeat HTTP module does not support trailing slash or URL parameters in url to monitor

### ISSUE THREAD

**Issue by joostdecock** [elastic/beats#27842]
- Package: metricbeat
- Module: http
- Version: HEAD

There's some issues into how the `http` module in metricbeat constructs the URL to monitor.
Here's the config I'm using:

```yaml
 - module: http
   metricsets: ["json"]
   period: 30s
   hosts: ["localhost:8080"]
   path: "/translation-support-search/api/v1/observability/"
```

Metricbeat will not check  
`/translation-support-search/api/v1/observability/` 
but instead 
`/translation-support-search/api/v1/observability` 
(without the trailing slash).

Those are not the same URL, although many websites might treat them the same.
Not an API though, and in this case the API we are monitoring answers `404` when the trailing slash is missing.

I thought I'd be clever and instead configure:

```yaml
path: "/translation-support-search/api/v1/observability/?keepmehere"
```

Only to see that metricbeat URLencodes the `?` resulting in yet another 404.

That's when I got curious what's going on, and I noticed that the URL is constructed here: https://github.com/elastic/beats/blob/3bb268198463e3de570ac61ea55d95eaf49e58ae/metricbeat/module/http/json/json.go#L49-L54

Notice that it's only passing the scheme, path config key, and default path. Thus url parameters are right out, even thought the method supports them: https://github.com/elastic/beats/blob/3bb268198463e3de570ac61ea55d95eaf49e58ae/metricbeat/mb/parse/url.go#L35-L42

But the cardinal sin are these two: 

https://github.com/elastic/beats/blob/3bb268198463e3de570ac61ea55d95eaf49e58ae/metricbeat/mb/parse/url.go#L92-L93

https://github.com/elastic/beats/blob/3bb268198463e3de570ac61ea55d95eaf49e58ae/metricbeat/mb/parse/url.go#L106-L107

Throwing out the trailing slash of a URL like this is not ok.

This seems like a rather self-explanatory bug. I guess the tricky part is fixing it while remaining backwards compatible.
If that's not possible, can we at least have a way to work around this? Perhaps by taking a config option for URL parameters, and if it's there, `join()` them with the path without stripping the `/`?

**Comment by joostdecock** [comment]
For anyone who landed here via a Google search, you can work around this issue by making the `path` part of the `hosts` entry, and not specifying any path at all.

Working config:

```yaml
 - module: http
   metricsets: ["json"]
   period: 30s
   # See: https://github.com/elastic/beats/issues/27842
   hosts: ["localhost:8080/translation-support-search/api/v1/observability/"]
```

:shrug:
