### ISSUE TITLE
Filters in MISP filebeat module are not working

### ISSUE THREAD

**Issue by stevengoossensB** [elastic/beats#27970]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 7.14
- Operating System: Ubuntu
- Discuss Forum URL:/
- Steps to Reproduce: Setup Threat intel module, connect MISP, enable filters
![image](https://user-images.githubusercontent.com/10197869/133621188-cc44191b-12af-4ef1-a58b-11b7f0cc0900.png)

The default config as described for filtering in the threat intel module is not working for MISP. Enabling the below results in an error message.

```
    # Optional filters that can be applied to the API for filtering out results. This should support the majority of fields in a MISP context.
    # For examples please reference the filebeat module documentation.
    var.filters:
      - threat_level: [4, 5]
      - to_ids: true
```

Could you update the syntax that is required for the filters to work?
