### ISSUE TITLE
filebeat setup with template.type=component doesn't apply shards and replicas to index

### ISSUE THREAD

**Issue by maxifom** [elastic/beats#28009]
- Version: 7.14.1
- Operating System: ubuntu 20.04
- Steps to Reproduce: 

I have this in my filebeat.docker.yml:
```yaml 
setup.template.enabled: true
setup.template.type: component
setup.template.name: "filebeat-%{[agent.version]}"
setup.template.pattern: "filebeat-%{[agent.version]}-*"

setup.template.settings:
  index:
    number_of_shards: 5
    number_of_replicas: 0
```

after 
```bash
docker run -it --rm -v SOME_PATH/.docker/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml docker.elastic.co/beats/filebeat:7.14.1 setup --index-management --strict.perms=false

template is created with 5 shards and 0 replicas, but index is not.

i got an index with 1 shard and 1 replica (default). In Kibana I can see that component template is created, but not in use. So this setup.template is creating template, but its pretty much useless, because I need to manually create index template and apply it to index patterns or whatever. Legacy type works fine
