### ISSUE TITLE
[Auditbeat] auditd not receiving event when outside of host network namespace

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#28063]
While running Auditbeat's `auditd` module in a container it will not receive events unless I put it into the host's network namespace. I believe this used to work because the [docs](https://www.elastic.co/guide/en/beats/auditbeat/current/running-on-docker.html#_special_requirements) don't mention anything about the network namespace requirement.

While doing some brief searching I found a newer flag `NETLINK_F_LISTEN_ALL_NSID` that I wonder if it is related. And some commits like https://github.com/torvalds/linux/commit/7212462fa6fdae61f7f40a4ead048def45bb23cb. This needs more research, but the goal would be to see if we can still run Auditbeat in its own namespace and receive audit events. If we can't, then we should update the docs to mention the requirement to run in the host's network namespace.

Version: 7.14.2
OS: Linux akroh-beats-dev 5.11.0-1018-gcp #20~20.04.2-Ubuntu SMP Fri Sep 3 01:01:37 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
Discuss: https://discuss.elastic.co/t/auditbeat-on-docker-fails-to-run-auditd-module/284399
Config:

```yaml
auditbeat.modules:
- module: auditd
  socket_type: multicast

output.console.enabled: true

logging.level: debug
logging.selectors: [auditd, processors]

seccomp.enabled: false
```
