### ISSUE TITLE
[Filebeat] Add capability to load filebeat docker/kubernetes autodiscover providers from external files

### ISSUE THREAD

**Issue by renzedj** [elastic/beats#28104]
# Use Case

Developers and administrators in our Kubernetes environment primarily use hint-based autodiscovery to trigger logging of containers within pods. However, there are a number of containers that are sufficiently widely-deployed that it makes sense to include a provider specification in our filebeat daemonset (i.e., widely-used sidecar containers). With even a few providers, this leads to an unwieldy size for the `filebeat.yml` file, making it cumbersome to manage. To make this easier to manage, `filebeat.autodiscover.providers` should have the ability to read in providers from external files, similar to `inputs` and `modules`.

# Describe the Enhancement

`filebeat.inputs` and `filebeat.modules` have the ability to load input and module specifications from secondary configuration files outside the `filebeat.yml`, by using the following specification:

```yaml
filebeat:
  config:
    inputs:
      path: '${path.config}/inputs.d/*.yml'
      reload:
        enabled: true
    modules:
      path: '${path.config}/modules.d/*.yml'
      reload:
        enabled: true
```

This enhancement would add the same functionality for autodiscover providers:

```yaml
filebeat:
  config:
    autodiscover:
      providers:
        path: '${path.config}/providers.d/*.yml'
        reload:
          enabled: true
```

This simplifies the maintenance of `filebeat.yml` files by allowing provider files to be moved out of the `filebeat.yml`. Additionally, it would allow additional providers to be specified as a kubernetes secret, to force automatic reloading of the provider files without the need to completely redeploy filebeat.
