### ISSUE TITLE
[Filebeat] system module configuration: failed to publish events: temporary bulk send failure

### ISSUE THREAD

**Issue by cdalexndr** [elastic/beats#28100]
For confirmed bugs, please report:
- Version: 7.14.1
- Operating System:  docker image store/elastic/filebeat:7.14.1
- Discuss Forum URL:
- Steps to Reproduce: 

`docker-compose` service:
```
filebeat:
    image: store/elastic/filebeat:7.14.1
    container_name: filebeat
    mem_limit: 128m
    entrypoint: /usr/share/filebeat/config/init/entry.sh
    volumes:
      - ./config/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./config/filebeat/init:/usr/share/filebeat/config/init:ro
      - ./config/filebeat/pipelines:/usr/share/filebeat/config/pipelines:ro
      - ./config/filebeat/index:/usr/share/filebeat/config/index:ro
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro #read logs from containers
      - /var/run/docker.sock:/var/run/docker.sock:ro #docker daemon listener
      - filebeat-data:/usr/share/filebeat/data
      - entry-data:/config:ro
      - /var/log:/hostfs/var/log:ro
    user: root
    labels:
      app: filebeat
    logging:
      driver: 'json-file'
      options:
        max-size: '20m'
        max-file: '5'
        compress: 'true'
```

Entrypoint script `entry.sh` configures some pipelines and index templates, then runs `filebeat -e --strict.perms=false`

`filebeat.yml`:
```
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "log-%{[docker][container][labels][app]}"
  pipeline: pipeline_logs
  ilm.enabled: false

queue.mem:
  events: 1024
  flush.min_events: 256
  flush.timeout: 1s

setup.ilm.enabled: false
setup.template.enabled: false
setup.kibana.host: http://kibana:5601

filebeat.modules:
  - module: system
    syslog:
      enabled: true
      var.paths: ["/hostfs/var/log/syslog*"]
```

Filebeat config tester shows it's valid:
```
filebeat --strict.perms=false test config
Config OK
```

But filebeat doesn't send logs to elasticsearch and gets stuck in repeating the following log entries:
```
filebeat         | 2021-09-23T15:51:00.185Z     INFO    [esclientleg]   eslegclient/connection.go:273   Attempting to connect to Elasticsearch version 7.14.1
filebeat         | 2021-09-23T15:51:00.202Z     INFO    [publisher_pipeline_output]     pipeline/output.go:151  Connection to backoff(elasticsearch(http://elasticsearch:9200)) established
filebeat         | 2021-09-23T15:51:00.253Z     INFO    [publisher]     pipeline/retry.go:219   retryer: send unwait signal to consumer
filebeat         | 2021-09-23T15:51:00.253Z     INFO    [publisher]     pipeline/retry.go:223     done
filebeat         | 2021-09-23T15:51:01.485Z     ERROR   [publisher_pipeline_output]     pipeline/output.go:180  failed to publish events: temporary bulk send failure
filebeat         | 2021-09-23T15:51:01.485Z     INFO    [publisher_pipeline_output]     pipeline/output.go:143  Connecting to backoff(elasticsearch(http://elasticsearch:9200))
filebeat         | 2021-09-23T15:51:01.486Z     INFO    [publisher]     pipeline/retry.go:219   retryer: send unwait signal to consumer
filebeat         | 2021-09-23T15:51:01.486Z     INFO    [publisher]     pipeline/retry.go:223     done
```

Removing the `filebeat.modules` section solves the problem and filebeat sends logs to elasticsearch:
Working `filebeat.yml`:
```
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "log-%{[docker][container][labels][app]}"
  pipeline: pipeline_logs
  ilm.enabled: false

queue.mem:
  events: 1024
  flush.min_events: 256
  flush.timeout: 1s

setup.ilm.enabled: false
setup.template.enabled: false
setup.kibana.host: http://kibana:5601
```

Configuring modules in `filebeat.yml` is supported, as stated by docs: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-modules.html
System module configuration is similar to that from docs: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-system.html

So, this configuration is reported as valid, and according to docs should work. 

<details>
  <summary>Filebeat log</summary>
  
```
filebeat         | 2021-09-23T16:08:14.902Z     INFO    instance/beat.go:665    Home path: [/usr/share/filebeat] Config path: [/usr/share/filebeat] Data path: [/usr/share/filebeat/data] Logs path: [/usr/share/filebeat/logs]
filebeat         | 2021-09-23T16:08:14.905Z     INFO    instance/beat.go:673    Beat ID: 54bf0491-254f-46a8-b07c-b4f20cb9e8d0
filebeat         | 2021-09-23T16:08:14.906Z     INFO    [seccomp]       seccomp/seccomp.go:124  Syscall filter successfully installed
filebeat         | 2021-09-23T16:08:14.907Z     INFO    [beat]  instance/beat.go:1014   Beat info       {"system_info": {"beat": {"path": {"config": "/usr/share/filebeat", "data": "/usr/share/filebeat/data", "home": "/usr/share/filebeat", "logs": "/usr/share/filebeat/logs"}, "type": "filebeat", "uuid": "54bf0491-254f-46a8-b07c-b4f20cb9e8d0"}}}
filebeat         | 2021-09-23T16:08:14.907Z     INFO    [beat]  instance/beat.go:1023   Build info      {"system_info": {"build": {"commit": "703d589a09cfdbfd7f84c1d990b50b6b7f62ac29", "libbeat": "7.14.1", "time": "2021-08-26T09:12:57.000Z", "version": "7.14.1"}}}
filebeat         | 2021-09-23T16:08:14.907Z     INFO    [beat]  instance/beat.go:1026   Go runtime info {"system_info": {"go": {"os":"linux","arch":"amd64","max_procs":2,"version":"go1.16.6"}}}
filebeat         | 2021-09-23T16:08:14.910Z     INFO    [beat]  instance/beat.go:1030   Host info       {"system_info": {"host": {"architecture":"x86_64","boot_time":"2021-03-14T06:39:35Z","containerized":true,"name":"8c2b1783a3d1","ip":["127.0.0.1/8","172.18.0.8/16"],"kernel_version":"4.9.0-14-amd64","mac":["02:42:ac:12:00:08"],"os":{"type":"linux","family":"redhat","platform":"centos","name":"CentOS Linux","version":"7 (Core)","major":7,"minor":9,"patch":2009,"codename":"Core"},"timezone":"UTC","timezone_offset_sec":0,"id":"00670dbdc5c6c164ebebe9cf7cabb54e"}}}
filebeat         | 2021-09-23T16:08:14.911Z     INFO    [beat]  instance/beat.go:1059   Process info    {"system_info": {"process": {"capabilities": {"inheritable":["chown","dac_override","fowner","fsetid","kill","setgid","setuid","setpcap","net_bind_service","net_raw","sys_chroot","mknod","audit_write","setfcap"],"permitted":["chown","dac_override","fowner","fsetid","kill","setgid","setuid","setpcap","net_bind_service","net_raw","sys_chroot","mknod","audit_write","setfcap"],"effective":["chown","dac_override","fowner","fsetid","kill","setgid","setuid","setpcap","net_bind_service","net_raw","sys_chroot","mknod","audit_write","setfcap"],"bounding":["chown","dac_override","fowner","fsetid","kill","setgid","setuid","setpcap","net_bind_service","net_raw","sys_chroot","mknod","audit_write","setfcap"],"ambient":null}, "cwd": "/usr/share/filebeat", "exe": "/usr/share/filebeat/filebeat", "name": "filebeat", "pid": 76, "ppid": 1, "seccomp": {"mode":"filter"}, "start_time": "2021-09-23T16:08:14.100Z"}}}
filebeat         | 2021-09-23T16:08:14.911Z     INFO    instance/beat.go:309    Setup Beat: filebeat; Version: 7.14.1
filebeat         | 2021-09-23T16:08:14.912Z     INFO    [esclientleg]   eslegclient/connection.go:100   elasticsearch url: http://elasticsearch:9200
filebeat         | 2021-09-23T16:08:14.916Z     INFO    [publisher]     pipeline/module.go:113  Beat name: 8c2b1783a3d1
filebeat         | 2021-09-23T16:08:14.952Z     INFO    beater/filebeat.go:117  Enabled modules/filesets: system (auth, syslog),  ()
filebeat         | 2021-09-23T16:08:14.954Z     INFO    [monitoring]    log/log.go:118  Starting metrics logging every 30s
filebeat         | 2021-09-23T16:08:14.955Z     INFO    instance/beat.go:473    filebeat start running.
filebeat         | 2021-09-23T16:08:14.961Z     INFO    memlog/store.go:119     Loading data file of '/usr/share/filebeat/data/registry/filebeat' succeeded. Active transaction id=0
filebeat         | 2021-09-23T16:08:15.381Z     INFO    memlog/store.go:124     Finished loading transaction log file for '/usr/share/filebeat/data/registry/filebeat'. Active transaction id=14081
filebeat         | 2021-09-23T16:08:15.385Z     INFO    [registrar]     registrar/registrar.go:109      States Loaded from registrar: 13
filebeat         | 2021-09-23T16:08:15.385Z     INFO    [crawler]       beater/crawler.go:71    Loading Inputs: 2
filebeat         | 2021-09-23T16:08:15.390Z     INFO    [input] log/input.go:164        Configured paths: [/var/log/auth.log* /var/log/secure*] {"input_id": "3583a5a1-ec19-4d1f-9a40-c7a0f3f82de3"}
filebeat         | 2021-09-23T16:08:15.390Z     INFO    [crawler]       beater/crawler.go:141   Starting input (ID: 10119875755155676254)
filebeat         | 2021-09-23T16:08:15.393Z     INFO    [input] log/input.go:164        Configured paths: [/hostfs/var/log/syslog*]     {"input_id": "140ae662-2936-4406-82f1-ab0ea1ae3b40"}
filebeat         | 2021-09-23T16:08:15.393Z     INFO    [crawler]       beater/crawler.go:141   Starting input (ID: 1145206035652835668)
filebeat         | 2021-09-23T16:08:15.393Z     INFO    [crawler]       beater/crawler.go:108   Loading and starting Inputs completed. Enabled inputs: 2
filebeat         | 2021-09-23T16:08:15.397Z     INFO    [input.harvester]       log/harvester.go:309    Harvester started for file.     {"input_id": "140ae662-2936-4406-82f1-ab0ea1ae3b40", "source": "/hostfs/var/log/syslog", "state_id": "native::182-2048", "finished": false, "os_id": "182-2048", "old_source": "/hostfs/var/log/syslog", "old_finished": true, "old_os_id": "182-2048", "harvester_id": "5c669447-2851-492a-bfd9-b6d9468b6dcb"}
filebeat         | 2021-09-23T16:08:15.401Z     INFO    [input.harvester]       log/harvester.go:309    Harvester started for file.     {"input_id": "140ae662-2936-4406-82f1-ab0ea1ae3b40", "source": "/hostfs/var/log/syslog.1", "state_id": "native::367-2048", "finished": false, "os_id": "367-2048", "old_source": "/hostfs/var/log/syslog.1", "old_finished": true, "old_os_id": "367-2048", "harvester_id": "7a791d29-189f-415d-95cf-2b98a8fd4fd0"}
filebeat         | 2021-09-23T16:08:15.411Z     INFO    [publisher_pipeline_output]     pipeline/output.go:143  Connecting to backoff(elasticsearch(http://elasticsearch:9200))
filebeat         | 2021-09-23T16:08:15.435Z     INFO    [publisher]     pipeline/retry.go:219   retryer: send unwait signal to consumer
filebeat         | 2021-09-23T16:08:15.436Z     INFO    [publisher]     pipeline/retry.go:223     done
filebeat         | 2021-09-23T16:08:15.437Z     INFO    [esclientleg]   eslegclient/connection.go:273   Attempting to connect to Elasticsearch version 7.14.1
filebeat         | 2021-09-23T16:08:15.478Z     INFO    [esclientleg]   eslegclient/connection.go:273   Attempting to connect to Elasticsearch version 7.14.1
filebeat         | 2021-09-23T16:08:15.485Z     INFO    [publisher_pipeline_output]     pipeline/output.go:151  Connection to backoff(elasticsearch(http://elasticsearch:9200)) established
filebeat         | 2021-09-23T16:08:15.502Z     INFO    [publisher]     pipeline/retry.go:219   retryer: send unwait signal to consumer
filebeat         | 2021-09-23T16:08:15.502Z     INFO    [publisher]     pipeline/retry.go:223     done
filebeat         | 2021-09-23T16:08:16.590Z     ERROR   [publisher_pipeline_output]     pipeline/output.go:180  failed to publish events: temporary bulk send failure
filebeat         | 2021-09-23T16:08:16.590Z     INFO    [publisher_pipeline_output]     pipeline/output.go:143  Connecting to backoff(elasticsearch(http://elasticsearch:9200))
filebeat         | 2021-09-23T16:08:16.590Z     INFO    [publisher]     pipeline/retry.go:219   retryer: send unwait signal to consumer
filebeat         | 2021-09-23T16:08:16.590Z     INFO    [publisher]     pipeline/retry.go:223     done
filebeat         | 2021-09-23T16:08:16.593Z     INFO    [esclientleg]   eslegclient/connection.go:273   Attempting to connect to Elasticsearch version 7.14.1
filebeat         | 2021-09-23T16:08:16.637Z     INFO    [publisher_pipeline_output]     pipeline/output.go:151  Connection to backoff(elasticsearch(http://elasticsearch:9200)) established
filebeat         | 2021-09-23T16:08:16.665Z     INFO    [publisher]     pipeline/retry.go:219   retryer: send unwait signal to consumer
filebeat         | 2021-09-23T16:08:16.665Z     INFO    [publisher]     pipeline/retry.go:223     done
filebeat         | 2021-09-23T16:08:17.675Z     ERROR   [publisher_pipeline_output]     pipeline/output.go:180  failed to publish events: temporary bulk send failure
filebeat         | 2021-09-23T16:08:17.676Z     INFO    [publisher_pipeline_output]     pipeline/output.go:143  Connecting to backoff(elasticsearch(http://elasticsearch:9200))
filebeat         | 2021-09-23T16:08:17.676Z     INFO    [publisher]     pipeline/retry.go:219   retryer: send unwait signal to consumer
filebeat         | 2021-09-23T16:08:17.677Z     INFO    [publisher]     pipeline/retry.go:223     done
```
</details>
