### ISSUE TITLE
Support CRI parsing in Fleet managed agents

### ISSUE THREAD

**Issue by danielharada** [elastic/beats#28140]
**Describe the enhancement:**
To achieve parity with Beats, Fleet managed agents need to support [CRI](https://kubernetes.io/blog/2016/12/container-runtime-interface-cri-in-kubernetes/) format parsing on log inputs from containers such as Kubernetes and Docker.

For example from Filebeat:

- Docker input CRI options:  https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-docker.html#_cri_parse_flags
- Container input format option:  https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-container.html#_format

**Comment by adammike** [comment]
This issue is blocking our adoption of elastic agent and elastic cloud. It's extremely urgent for our team.

Without this, elastic-agent is unusable on IBM Kubernetes Service, Amazon EKS, or any other Kubernetes implementation that uses the containerd container runtime.

**Comment by danielharada** [comment]
Here's an example configuration that has been shown to work on the standalone agent:
```
- name: container-log
  type: logfile
  use_output: default
  meta:
    package:
      name: log
      version: 0.4.6
  data_stream:
    namespace: log_mgmt
  streams:
  - data_stream:
    dataset: kubernetes.container_logs
    cri.parse_flags: true
    cri.force: true
    symlinks: true
    docker-json.partial: true
    docker-json.cri_flags: true
    docker-json.format: cri
    docker-json.stream: all
    paths:
      - /var/log/containers/*${kubernetes.container.id}.log
```
