### ISSUE TITLE
Default AWS config creates two AWS module instances. 

### ISSUE THREAD

**Issue by A-Hall** [elastic/beats#28157]
For confirmed bugs, please report:
- Version: 7.14.0

The default config for the aws module (comments omitted for brevity) contains `- module: aws` twice which can cause a new aws module instance with all 6 filesets enabled but not configured to be created.

```
- module: aws
  cloudtrail:
    enabled: false

  cloudwatch:
    enabled: false

  ec2:
    enabled: false

  elb:
    enabled: false

  s3access:
    enabled: false

  vpcflow:
    enabled: false

- module: aws
  fargate:
    enabled: false
```

This throws a confusing error when the cloudtrail module is actually properly configured:
```
2021-09-28T09:58:32.258-0400    ERROR   [input.aws-s3]  compat/compat.go:122    Input 'aws-s3' failed with: getRegionFromQueueURL failed: QueueURL is not in format: https://sqs.{REGION_ENDPOINT}.{ENDPOINT}/{ACCOUNT_NUMBER}/{QUEUE_NAME}
```
