### ISSUE TITLE
[Heartbeat] Support PlaywrightOptions

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#28197]
Heartbeat counterpart to https://github.com/elastic/synthetics/issues/388, proposes support for a new option for browser monitors

ACs:
* Add a new optional `playwright_options` parameter that defined the JSON to be passed to playwright directly (as added to Synthetics in https://github.com/elastic/synthetics/issues/388)

```yaml
- name: my-monitor
  # ...
  playwright_options:
    an_option
  source: #...
```
