### ISSUE TITLE
Heartbeat: Gzip content-encoding in response is never decoded 

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#28303]
For confirmed bugs, please report:
- Version: <=7.15
- Operating System: any
- Discuss Forum URL:
- Steps to Reproduce: 

HTTP requests from Heartbeat never include an `Accept-Encoding` header. This is due to faulty logic in:

https://github.com/elastic/beats/blob/e96668690b202495271346eb45d0dbde6dc76c7e/heartbeat/monitors/active/http/simple_transp.go#L89-L98

Here the `t.DisableCompression` flag is always false.

When the `Accept-Encoding` header is missing, HTTP servers are free to use any encoding. If a server sends a response with `Content-Encoding: gzip`, Heartbeat will never decode it, as the decoding logic is only triggered when gzip was explicitly requested (which is never the case, due to the logic above):

https://github.com/elastic/beats/blob/e96668690b202495271346eb45d0dbde6dc76c7e/heartbeat/monitors/active/http/simple_transp.go#L194-L209

For some servers a workaround can be to try to force them into delivering uncompressed responses:

```yaml
- type: http
  [...]
  check.request:
    headers:
       'accept-encoding': 'identity'
```

but some servers can be hardcoded to always send a gzip response.

**Comment by justinkambic** [comment]
Having done some investigation, we feel this is somewhere between a missing feature and a bug. Given that the code does not function and it's impossible to decode gzip with Heartbeat as it is today I feel it's a bug. But we also need to determine the best way to enable this functionality.

For example, if we attempt to run a request in `curl`, it doesn't include `"Accept-Encoding: gzip"` by default. Our thinking is we probably shouldn't include that either, so if the user specifies a `compression: gzip`, we should honor that by including the header and decoding the response body. Given the SDH that lead to this, it's clear people are encountering it in practice and not understanding why they're getting gzip data indexed.

**Comment by andrewvc** [comment]
To add to what @justinkambic wrote, I think it's sensible for our use case to automatically detect gzip and decode it. This may be easier said than done in that we only will decode the first fragment of it, which is a little trickier in the code, but should still be doable.

**Comment by lucasfcosta** [comment]
@justinkambic can you confirm that these are the steps I'll need to test this?

1. Create a server which will respond to a particular request with a gzipped response (setting the appropriate header). This response's body should have a string for which we'll check later, like `test-example`.
2. On Heartbeat, create an HTTP monitor which expects the response to have `test-example` in its body
3. Run Heartbeat and wait for that monitor to run
4. Expect the monitor to succeed and the document to have been indexed with the `test-example` string in its body (shown in the document)

**Comment by justinkambic** [comment]
@lucasfcosta there are two main cases we're looking to handle here:

1. The happy path: Heartbeat requests `gzip` encoding from the server, decodes it, and indexes the response body. If you test this one you've essentially covered the desired behavior that resolves this issue, and there's no need to configure a custom server.
  You can easily test this with a real production server; per the instructions on the PR you could do something like: `curl -X GET https://www.google.com -v --http1.1 -H "Accept-Encoding: gzip" -o test.gzip` and `curl -X GET https://www.google.com -v --http1.1 -o test.gzip` to verify the server will encode/not encode based on the inclusion of the header. Then, configure your monitor to include the `Accept-Encoding: gzip` header in its request to that server, and confirm the response body gets indexed.
  Here's an example monitor that I configured:

```yml
- type: http
  name: header-test
  id: header-test
  schedule: "@every 4m"
  hosts: ["https://www.google.com"]
  check.request:
    headers:
      "Accept-Encoding": "gzip"
  check.response:
    body:
      - "Google Search"
```

2. Heartbeat will attempt to decode `gzip` content even if it didn't ask for it. This is an example where the server is configured incorrectly and it responds with `gzip`-encoded data even when the client didn't request it. For this you'd need to either find a misconfigured server to request, or like you mentioned, set up a server to do this on its own. This isn't hard to set up but if you want I have a custom express script I use for testing stuff like this that I could share.

There is one more esoteric case we covered, wherein Heartbeat will not try to decode a `gzip` response body in the absence of the `Content-Encoding` response header. I don't think it's particularly necessary to test this because it is essentially a best-effort kind of assumption where the server isn't behaving appropriately, but if you want to verify it's working you'd need a server to respond with `gzip`, and _without_ the `Content-Encoding: gzip` header. In this case, if Heartbeat is configured to index the response body, you should see raw `gzip` content indexed to your cluster.

**Comment by lucasfcosta** [comment]
@justinkambic I've just tested this and here are the results I've obtained.

# Happy path: decoding `gzip`

1. I first tried to use Heartbeat 7.16 with the monitor you posted above.
    ```yml
    - type: http
      name: header-test
      id: header-test
      schedule: "@every 30s"
      hosts: ["https://www.google.com"]
      check.request:
        headers:
          "Accept-Encoding": "gzip"
      check.response:
        body:
          - "Google Search"
    ```
2. After saving that configuration, I've ran Heartbeat against my `elastic-package stack`
    ```
    docker run -d --name=heartbeat1 --user=heartbeat --volume="/tmp/hb1.yml:/usr/share/heartbeat/heartbeat.yml:ro" --network="elastic-package-stack_default" docker.elastic.co/beats/heartbeat:7.16.0-SNAPSHOT --strict.perms=false -e
    ```
3. That caused the check to fail straight-away because the response body wasn't decoded, as you can see in the screenshot below.
    ![Screenshot 2021-12-17 at 16 14 26](https://user-images.githubusercontent.com/6868147/146575500-41d4708b-5001-46dc-aad2-615cdba4de73.png)
4. I then tried to use the same configuration file to run Heartbeat `8.0.0-SNAPSHOT`.
    ```
    docker run -d --name=heartbeat1 --user=heartbeat --volume="/tmp/hb1.yml:/usr/share/heartbeat/heartbeat.yml:ro" --network="elastic-package-stack_default" docker.elastic.co/beats/heartbeat:8.0.0-SNAPSHOT --strict.perms=false -e
    ```
5. Once I did that, my check started passing, given that Heartbeat could verify the response body and it saw a match.
    ![Screenshot 2021-12-17 at 16 41 00](https://user-images.githubusercontent.com/6868147/146578347-2d16a61d-2464-4319-83f9-62e8ca73d870.png)
6. I then changed the monitor to see it failing:
    ```yml
    - type: http
      name: header-test
      id: header-test
      schedule: "@every 30s"
      hosts: ["https://www.google.com"]
      check.request:
        headers:
          "Accept-Encoding": "gzip"
      check.response:
        body:
          - "It fails now"
    ```
7. After this change, I could see the decoded body in Kibana
![Screenshot 2021-12-17 at 16 40 35](https://user-images.githubusercontent.com/6868147/146578621-44f20c87-aa9a-4d37-9cd0-9ac4f25b8e15.png)

 # Decoding gzip without headers added by the server

1. I created a simple express server which always compresses responses on a particular endpoint.
    ```js
    const compression = require('compression')
    const express = require('express')

    const app = express()

    app.get("/uncompressed", (_req, res) => {
        res.set('Content-Type', 'text/html');
        res.send(("Test Uncompressed").repeat(10000));
    });

    app.use(compression({ filter: () => true, threshold: 0 }))

    app.get("/compressed", (_req, res) => {
        res.set('Content-Type', 'text/html');
        res.set('Content-Encoding', 'gzip');
        res.send(("Match this string").repeat(10000));
        res.flush()
    });
    
    app.get("/compressed-no-header", (_req, res) => {
        res.set('Content-Type', 'text/html');
        res.set('Content-Encoding', 'other');
        res.send(("Match this string").repeat(10000));
        res.flush()
    });


    app.listen(3030);
    ```
2. I confirmed responses were indeed compressed on the `/compressed` endpoint and uncompressed on the `/uncompressed` endpoint.
    ![Screenshot 2021-12-17 at 17 16 25](https://user-images.githubusercontent.com/6868147/146583586-f197fd1a-d883-4935-bc87-d2e9ef3fb8a0.png)
    ![Screenshot 2021-12-17 at 17 15 59](https://user-images.githubusercontent.com/6868147/146583593-8763e9c6-882a-4d5c-af6a-5d653c1a70cf.png)
3. I also confirmed the `/compressed-no-header` endpoint compresses responses but uses the value `other` as the `Content-Encoding` header.
    ![Screenshot 2021-12-17 at 17 29 04](https://user-images.githubusercontent.com/6868147/146584348-a7023d6e-4200-439c-8743-2ea8a30f2f2d.png)
4. I then went on to make Heartbeat check the `/compressed-no-header` route and was able to see the correctly decoded body by looking for a slightly different string than what's in the server's response.
    ```yaml
    - type: http
      name: header-test-local
      id: header-test
      schedule: "@every 30s"
      hosts: ["http://host.docker.internal:3030/compressed-no-header"]
      check.request:
        headers:
          "Accept-Encoding": "gzip"
      check.response:
        body:
          - "Does not match this string"
    ```
    ![Screenshot 2021-12-17 at 17 32 19](https://user-images.githubusercontent.com/6868147/146584893-c74e99b3-8712-49a3-b03d-80b395949a58.png)
5. Using the correct string made it work just fine 😄 
    ```yaml
    - type: http
      name: header-test-local
      id: header-test
      schedule: "@every 30s"
      hosts: ["http://host.docker.internal:3030/compressed-no-header"]
      check.request:
        headers:
          "Accept-Encoding": "gzip"
      check.response:
        body:
          - "Does not match this string"
    ```
    ![Screenshot 2021-12-17 at 17 34 13](https://user-images.githubusercontent.com/6868147/146584960-17d210ef-bca8-4b81-9138-bfd939e5a722.png)
