### ISSUE TITLE
MetricBeat: Jolokia module logging logs no URI

### ISSUE THREAD

**Issue by spinscale** [elastic/beats#28591]
For confirmed bugs, please report:
- Version: 7.15.1
- Operating System:  Linux
- Steps to Reproduce: 

When running metricbeat with verbose logging for jolokia like `metricbeat run -e -v -d jolokia.jmx` the logging message is wrong as it includes an empty path.

By default the jolokia path to query is `/jolokia`, however the logging looks like this

```
2021-10-21T15:48:56.384Z	DEBUG	[jolokia.jmx]	jmx/config.go:484	Jolokia request URI and body	{"host": "localhost:8888", "httpMethod": "POST", "URI": "", "body": "[{\"type\":\"read\",\"mbean\":\"java.lang:type=Memory\",\"attribute\":[\"HeapMemoryUsage\",\"NonHeapMemoryUsage\"],\"config\":{\"canonicalNaming\":true,\"ignoreErrors\":true}},{\"type\":\"read\",\"mbean\":\"java.lang:type=Threading\",\"attribute\":[\"ThreadCount\",\"DaemonThreadCount\"],\"config\":{\"canonicalNaming\":true,\"ignoreErrors\":true}}]", "type": "request"}
```

See above that the `URI` field is empty.

Whereas the request clearly contains `/jolokia`. You can use this python to see the request without having jolokia running

```python
#!/usr/bin/env python3
"""
Very simple HTTP server in python for logging requests
Usage::
    ./server.py [<port>]
"""
from http.server import BaseHTTPRequestHandler, HTTPServer
import logging

class S(BaseHTTPRequestHandler):
    def _set_response(self):
        self.send_response(200)
        self.send_header('Content-type', 'text/html')
        self.end_headers()

    def do_GET(self):
        logging.info("GET request,\nPath: %s\nHeaders:\n%s\n", str(self.path), str(self.headers))
        self._set_response()
        self.wfile.write("GET request for {}".format(self.path).encode('utf-8'))

    def do_POST(self):
        content_length = int(self.headers['Content-Length']) # <--- Gets the size of data
        post_data = self.rfile.read(content_length) # <--- Gets the data itself
        logging.info("POST request,\nPath: %s\nHeaders:\n%s\n\nBody:\n%s\n",
                str(self.path), str(self.headers), post_data.decode('utf-8'))

        self._set_response()
        self.wfile.write("POST request for {}".format(self.path).encode('utf-8'))

def run(server_class=HTTPServer, handler_class=S, port=8888):
    logging.basicConfig(level=logging.INFO)
    server_address = ('', port)
    httpd = server_class(server_address, handler_class)
    logging.info('Starting httpd...\n')
    try:
        httpd.serve_forever()
    except KeyboardInterrupt:
        pass
    httpd.server_close()
    logging.info('Stopping httpd...\n')

if __name__ == '__main__':
    from sys import argv

    if len(argv) == 2:
        run(port=int(argv[1]))
    else:
        run()
```

Configuration to retry

```
metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - core
    - diskio
    - filesystem
    - fsstat
    - memory
    - network
    - process
    - process_summary
    - socket
  enabled: true
  period: 10s
  processes: ['.*']
  cgroups: true
  process.include_top_n:
    enabled: true
    by_cpu: 20
    by_memory: 20
- module: jolokia
  metricsets: ["jmx"]
  hosts: ["http://localhost:8888"]
  namespace: metrics
  jmx.mappings:
    - mbean: "java.lang:type=Memory"
      attributes:
        - attr: HeapMemoryUsage
          field: memory.heap_usage
          event: heap
        - attr: NonHeapMemoryUsage
          field: memory.non_heap_usage
          event: heap
    - mbean: "java.lang:type=Threading"
      attributes:
        - attr: ThreadCount
          field: thread.count
          event: thread
        - attr: DaemonThreadCount
          field: thread.daemon
          event: thread
  jmx.instance: "XYZ"
```
