### ISSUE TITLE
[libbeat] APM Server does not start when running as an arbitrary user ID

### ISSUE THREAD

**Issue by barkbay** [elastic/beats#28617]
https://github.com/elastic/beats/pull/28265 [added a call to `user.Current()`](https://github.com/elastic/beats/pull/28265/files#diff-7892d09d6cd53dcdb72155590e61e694ebea064f17965984cfc22286f02f3e55R194-R197). Unfortunately `user.Current()` fails if the user UID does not exist in `/etc/passwd`, which is likely to be the case on K8S if user sets an arbitrary UID [in the `securityContext`](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod).

A workaround can be to catch this specific error and fall back to `os.Getuid()` and `os.Getgid()`:

```golang
		if u, err := user.Current(); err != nil {
			// UnknownUserIdError may happen if the user UID does not exist in /etc/passwd. It might be the case on K8S
			// if the user set securityContext.runAsUser to an arbitrary value.
			_, ok := err.(user.UnknownUserIdError)
			if !ok {
				return err
			}
			monitoring.NewString(registry, "uid").Set(strconv.Itoa(os.Getuid()))
			monitoring.NewString(registry, "gid").Set(strconv.Itoa(os.Getgid()))
		} else {
			monitoring.NewString(registry, "username").Set(u.Username)
			monitoring.NewString(registry, "uid").Set(u.Uid)
			monitoring.NewString(registry, "gid").Set(u.Gid)
		}
```

Happy to raise the relevant PR if you agree with this approach.

---

For confirmed bugs, please report:
- Version: `7.16.0-SNAPSHOT` (It works as expected with `7.15.x`)
- Related change: https://github.com/elastic/beats/pull/28265
- Operating System: Docker
- Steps to Reproduce: 

Deploy an APM Server using ECK and the following manifest, APM Server fails with message `user: unknown userid 12345` :

```yaml
apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es-apm-sample
spec:
  version: 7.16.0-SNAPSHOT
  nodeSets:
  - name: default
    count: 3
    config:
      node.store.allow_mmap: false
---
apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kb-apm-sample
spec:
  version: 7.16.0-SNAPSHOT
  count: 1
  elasticsearchRef:
    name: "es-apm-sample"
---
apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-apm-sample
spec:
  version: 7.16.0-SNAPSHOT
  count: 1
  elasticsearchRef:
    name: "es-apm-sample"
  kibanaRef:
    name: "kb-apm-sample"
  podTemplate:
    spec:
      securityContext:
        runAsUser: 12345
        runAsGroup: 12345
        fsGroup: 0
```
