### ISSUE TITLE
add_kubernetes_metadata needs to respect logs_path setting

### ISSUE THREAD

**Issue by TomonoriSoejima** [elastic/beats#28629]
Suppose you have this setting in filebeat.yml.

```
    processors:
      #- decode_json_fields:
      #    fields: message
      - add_kubernetes_metadata:
          host: ${NODE_NAME}
          matchers:
            - logs_path:
                logs_path: "/var/log/pods/"
                resource_type: 'pod'
```

Then you have mounted container logs in the given path `/var/log/pods/`, but  add_kubernetes_metadata can not find the match.

`
2021-10-21T16:41:48.474Z	DEBUG	[kubernetes]	add_kubernetes_metadata/matchers.go:88	Incoming log.file.path value: /var/log/pods/openshift-xxxx-logging_mdsd-xxxxxxx/fluentbit/0.log
2021-10-21T16:41:48.474Z	DEBUG	[kubernetes]	add_kubernetes_metadata/kubernetes.go:210	No container match string, not adding kubernetes data	{"libbeat.processor": "add_kubernetes_metadata"}
`

Because the [code](https://github.com/elastic/beats/blob/ec8e0511b2c0d82282ca2d3127d11ac9650467b1/filebeat/processor/add_kubernetes_metadata/matchers.go#L101) expects the path to be the static value `/var/lib/kubelet/pods/`

We should use the passed value in `logs_path` in the code to be more flexible.

![image](https://user-images.githubusercontent.com/25199092/138786926-0dcdd9a7-3f80-402c-89e5-750ebdaf4bc2.png)
