### ISSUE TITLE
[libbeat] Fingerprint processor cannot access @timestamp

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#28683]
The fingerprint processor directly accesses `beat.Event.Fields` to get data for the fingerprint. Therefore it cannot see the `@timestamp` because that is stored separately. It should use `beat.Event.GetValue` and then this would work as expected.

```
processors:
- fingerprint:
    fields: [winlog.computer, winlog.channel, winlog.record_id, '@timestamp']
    method: sha256
    target_field: '@metadata._id'
```

>  "failed applying processor fingerprint=[method=[0x1f460000]]: failed to compute fingerprint: failed to find field [@timestamp] in event: key not found"
