### ISSUE TITLE
Error when using proxy_url in Filebeat aws-s3 input

### ISSUE THREAD

**Issue by kaiyan-sheng** [elastic/beats#28724]
When trying to use Filebeat aws-s3 input with the `proxy_url` config parameter, Filebeat will fail to start with error: 
```
2021-10-29T03:14:40.088Z ERROR instance/beat.go:989 Exiting: Failed to start crawler: starting input failed: Error while initializing input: (assert) value of type 'string' not convertible into unsupported go type 'url.URL' accessing 'filebeat.inputs.2.proxy_url' (source:'/etc/filebeat/filebeat.yml')
```
Here is the config to reproduce this problem:
```
filebeat.inputs:
- type: aws-s3
  queue_url:  https://sqs.us-east-1.amazonaws.com/12345/test-vpcflow
  proxy_url: http://proxy:1234
```
