### ISSUE TITLE
Use filebeat's autodiscover input on Kubernetes. It may happen that only a part of the log is collected.

### ISSUE THREAD

**Issue by AlliotTech** [elastic/beats#28753]
elasticsearch  filebeat version : 7.8.0
k8s version : v1.18.8
daemonSet config:   
``` yml 
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: filebeat
  labels:
    app: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet


      
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:7.8.0
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 800Mi
          requests:
            cpu: 400m
            memory: 200Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        # - name: filebeat-indice-lifecycle
        #   mountPath: /etc/indice-lifecycle.json
        #   readOnly: true
        #   subPath: indice-lifecycle.json
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true

      volumes:
      - name: config
        configMap:
          defaultMode: 0640
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: data
        hostPath:
          # When filebeat runs as non-root user, this directory needs to be writable by group (g+w).
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
```

filebeat config: 
``` yml
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          templates:
            - condition:
                equals:
                  kubernetes.labels.filebeat_harvest: "true"
              config:
                - type: container
                  encoding: utf-8
                  paths: 
                    # - /var/lib/docker/containers/${data.kubernetes.container.id}/*.log
                    - /var/log/containers/*${data.kubernetes.container.id}.log
                  # exclude_lines: ["^\\s+[\\-`('.|_]"]
                  multiline:
                    pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
                    negate: true
                    match: after
                  symlinks: true
    processors:
      - drop_fields:
          fields:
            - "@metadata"
            - "beat"
            #- "kubernetes.labels"
            - "kubernetes.container"
            - "kubernetes.annotations"
            - "host"
            - "prospector"
            - "input"
            - "offset"
            - "stream"
            - "source"
            - "agent.ephemeral_id"
            - "agent.hostname"
            - "agent.id"
            - "agent.name"
            - "agent.type"
            - "agent.version"
            - "host.name"
            - "input.type"
            - "ecs.version"
            - "input.type"
            - "log.offset"
            - "log.flags"
            - "log.file.path"
            - "version"
```

filebeat give me some logs like this:  
``` 
2021-11-02T06:00:37.038Z	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":470,"time":{"ms":4}},"total":{"ticks":1180,"time":{"ms":18},"value":1180},"user":{"ticks":710,"time":{"ms":14}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":9},"info":{"ephemeral_id":"605b97b3-2e24-4639-aa2f-8e9c58e8ce0b","uptime":{"ms":2970025}},"memstats":{"gc_next":15694320,"memory_alloc":8022480,"memory_total":59381784},"runtime":{"goroutines":39}},"filebeat":{"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":0,"events":{"active":0}}},"registrar":{"states":{"current":29}},"system":{"load":{"1":1.15,"15":0.38,"5":0.58,"norm":{"1":0.0719,"15":0.0238,"5":0.0363}}}}}}
```
It's seems the filebeat think my application don't produce logs? but my appliacation do really produced a lot of logs...
I think I may have encountered some bug.
