### ISSUE TITLE
[Heartbeat] Allow running monitors in service

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/beats#28822]
**Describe the enhancement:**

Allow running HB monitors in a central service. 

### Proposal

Heartbeat config would look like this

```yaml
heartbeat.service:
  username: 
  password: // Basic Auth for service
  manifest_url: "manifest.url" // 

heartbeat.monitors:
  - type: browser
    locations:
      - nyc
      - paris
      
cloud.id::  
cloud.auth:  // Auth details required to be push ES docs
```
+ Heartbeat would need to push the configured monitors every configured `update_interval` which is set to `20m` in the above config. 
+ Username and password would be optional ones for now as we want to go with Basic Auth for the current term. Will be changed later on
+ Location list would contain all the locations that we expect the configured monitors to run including GEO details. 

#### POST request to Service

+ Basic Auth should be set for the POST request to the service

The Schema of the POST call would look like this
```json
{
  "monitors": [
    {
      "type": "browser",
      "name": "Elastic Monitor",
      "id": "elastic-monitor",
      "schedule": "@every 10m",
      "source": {
        "inline": {
          "script": "step(\"load homepage\", async () => { await page.goto('https://www.elastic.co') });"
        }
      }
    }
  ],
  "cloud.id": "",
  "cloud.auth": "" // Or output.elasticsearch - Service would support both. 
}
```

#### Validation
+ Config validation must be done to make sure all the monitors meet the criteria of `schedule >= 1 minute`.

#### Enhancements
+ Backoff exponentially if the service is unreachable or when the underlying cluster is at capacity. 
+ If one of the monitors failed to run, Create separate heartbeat summary document with correct error.

**Comment by shahzad31** [comment]
@vigneshshanmugam thanks for putting it up. I think schema will need to be changed a bit 

`heartbeat.service` part looks good , in which essentially we define a list of service regions availalable, in the monitor part we also need to add `service_urls` list attribute, since user can decide in the ui to not run monitor in all the regions, essentially difference monitors can have difference regions based on user choice.


Also after discussion with @andrewvc i think `update_interval` will be a hard coded value. Since it has chcance of abuse. So we want to control this aspect. 

Regarding the schedule part, i think on the UI we can defenitely control that interval should always be greater than 1 min in case of browser monitor, how should we handle the validation from yaml

1. Should we ignore that monitor?
2. Log an error just for that monitor?
3. Stop hearbeat altogther from starting and log an error?

**Comment by vigneshshanmugam** [comment]
> heartbeat.service part looks good , in which essentially we define a list of service regions availalable, in the monitor part we also need to add service_urls list attribute, since user can decide in the ui to not run monitor in all the regions, essentially difference monitors can have difference regions based on user choice.

`hearbeat.service.locations` is a list which would exactly do that.It would look something like this for multiple locations.  Do you still think we need `service.urls`? 

```
heartbeat.service:
  update_interval: "20m" // Pushes the config every 20 minutes
  username: 
  password: // Basic Auth for service
  locations: // Where to run the monitors would run
  - paris:
      url: "https://paris.service.elastic.co/execute"
      geo: ...       
    nyc:
       url: "https://nyc.service.elastic.co/execute"
       geo: ...
```

> Also after discussion with @andrewvc i think update_interval will be a hard coded value. Since it has chance of abuse. So we want to control this aspect.

Hmmm good point. But it wont be configurable on the UI side, I was doing it purely for the DX perspective, but we can hardcode it for now. 

>Regarding the schedule part, i think on the UI we can defenitely control that interval should always be greater than 1 min in case of browser monitor, how should we handle the validation from yaml

The config validation should live in Heartbeat, we can also add some validation to the UI, when users are scheduling monitors to be run on the service, it should not be allowed.

My thinking was to never start HB with invalid monitors.

**Comment by vigneshshanmugam** [comment]
Had a discussion offline with @andrewvc and @shahzad31. This is the final approach that we agreed on

```
heartbeat.service:
  username: 
  password: // Basic Auth for service
  manifest_url: "manifest.url" // 

heartbeat.monitors:
  - type: browser
    locations:
      - nyc
      - paris

```

Will update the description with more details soon.
