### ISSUE TITLE
[DOCS] Document overriding of input in modules (if possible)

### ISSUE THREAD

**Issue by lucabelluccini** [elastic/beats#28844]
**Describe the enhancement:**

In most of our module, we explain how to customize the input options.
E.g. https://www.elastic.co/guide/en/beats/filebeat/master/advanced-settings.html#advanced-settings

We do not describe if we can (and eventually how) change the input type.

E.g. are we allowed to use the following?
```
            - module: elasticsearch
              audit:
                input:
                  type: aws-s3
                  queue_url: https://sqs.ap-southeast-1.amazonaws.com/1234/test-s3-queue
                  credential_profile_name: elastic-beats
                  expand_event_list_from_field: Records
```
