### ISSUE TITLE
Heartbeat not propagating ```number_of_replicas``` settings to index settings

### ISSUE THREAD

**Issue by shahzad31** [elastic/beats#28886]
Heartbeat Version: master

When we set number of replica setting in heartbeat.yml , it always get's reset to 1, for example if we set to 0 or 2 ,

```
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  number_of_replicas: 0
```

I also tried removing the index and running `./heartbeat setup`, but that doesn't make differnce.
