### ISSUE TITLE
filebeat 7.15.2 采集k8s日志标签混乱

### ISSUE THREAD

**Issue by rechardwang** [elastic/beats#29013]
使用最新版本7.15.2部署在k8s中 使用自动发现采集日志，发现采集的日志 k8s lables不是当前日志的，如图：
图1： 这张图是我容器中打印的日志，但是到了es中之后 kubernetes.container.name 就完全不对了
![image](https://user-images.githubusercontent.com/43982436/142202048-ae5b1dd3-7d98-47f0-bfd4-6fc158855004.png)

图2：这张图是我Ingress打印的日志，这里的标签也不对了
![image](https://user-images.githubusercontent.com/43982436/142202247-7d2facab-2674-4ac3-9747-d0b7dc16b26e.png)

#### filebeat使用的配置文件
```
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: elastic
  name: filebeat-config
  labels:
    app: filebeat
data:
  filebeat.yml: |-
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
          hints.default_config:
            type: container
            paths:
              - /var/lib/docker/containers/*/*.log
          appenders:
            - type: config
              config:
                tail_files: true
                close_removed: true
                clean_removed: true

    processors:
      - drop_event:
          when:
            regexp:
              message: "kube-probe"
          when.or:
              - and:
                  - regexp:
                      message: '^\d+\.\d+\.\d+\.\d+ '
                  - equals:
                      fileset.name: error
              - and:
                  - not:
                      regexp:
                          message: '^\d+\.\d+\.\d+\.\d+ '
                  - equals:
                      fileset.name: access
      - add_cloud_metadata:
          in_cluster: true
          matchers:
          - logs_path:
              logs_path: "/var/log/containers/*${data.kubernetes.container.id}.log"

    output.kafka:
      hosts: ['${KAFKA_HOST:kafka}:${KAFKA_PORT:9092}']
      topic: 'k8s-logs-test'
      partition.round_robin:
        reachable_only: false

    setup.ilm:
      policy_file: /etc/indice-lifecycle.json
    logging.level: error
    logging.metrics.enable: false

```

我尝试了很久  发现确实有很多错误的情况，还比如 kubernetes.container.name 为core-dns的日志竟然是我业务日志。
完全乱掉了
