### ISSUE TITLE
Filestream input locks files in Windows

### ISSUE THREAD

**Issue by Sergi-GC** [elastic/beats#29113]
- Version: v7.13.1 and v7.15.1
- Operating System: Windows
- Description: 

When using the [Filestream input](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html) in Windows, Filebeat locks the files it's monitoring and prevents other processes from renaming or moving the files. 

This has been reproduced in **Windows Server 2016**, **Windows 10 Enterprise** and in **Windows 10 Home** environment. 

Error in Windows Server 2016:
![filebeat_filstream_locked_error](https://user-images.githubusercontent.com/56286461/142277181-a8acc5c1-152a-472c-85ef-00be3b9a412f.jpg)

Error in Windows 10 Home:
<img width="449" alt="windows-10-test" src="https://user-images.githubusercontent.com/56286461/142278603-f1f07716-973f-429e-9406-d558b0a73537.png">

This issue does not reproduce in **MacOS**. 
And also does not happen with the [Log input](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html).

- Steps to reproduce: 

**Case 1: Commenting out the close inactive settings for both inputs**

Settings:
```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - C:\logs\this_file_is_not_locked.log

  clean_removed: true
  close_renamed: true
 #close_inactive: 1m
  scan_frequency: 10s

- type: filestream
  enabled: true
  paths:
    - C:\logs\this_file_is_locked.log

  clean_removed: true
  close.on_state_change.removed: true
  close.on_state_change.renamed: true
  #close.on_state_change.inactive: 1m
  prospector.scanner.check_interval: 10s
```

Results:
- The file `this_file_is_not_locked` can be renamed/deleted/moved any time since the moment Filebeat is started. 
- The file `this_file_is_locked` cannot be renamed/deleted/moved since the moment Filebeat is started.

**Case 2: Setting close inactive settings to 1min**

Settings:
```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - C:\logs\this_file_is_not_locked.log

  clean_removed: true
  close_renamed: true
  close_inactive: 1m
  scan_frequency: 10s

- type: filestream
  enabled: true
  paths:
    - C:\logs\this_file_is_locked.log
   
  clean_removed: true
  close.on_state_change.removed: true
  close.on_state_change.renamed: true
  close.on_state_change.inactive: 1m
  prospector.scanner.check_interval: 10s
```

Results:
- The file `this_file_is_not_locked` can be renamed/deleted/moved any time since the moment Filebeat is started. 
- The file `this_file_is_locked` cannot be renamed/deleted/moved for about 1m since the moment Filebeat is started. After 1 min the file can be renamed/deleted/moved. 

**Case 3: Commenting out all the close/clean settings**

Settings:
```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - C:\logs\this_file_is_not_locked.log

  #clean_removed: true
  #close_renamed: true
  #close_inactive: 1m
  scan_frequency: 10s

- type: filestream
  enabled: true
  paths:
    - C:\logs\this_file_is_locked.log
   
  #clean_removed: true
  #close.on_state_change.removed: true
  #close.on_state_change.renamed: true
  #close.on_state_change.inactive: 1m
  prospector.scanner.check_interval: 10s
```

Results:
- The file `this_file_is_not_locked` can be renamed/deleted/moved any time since the moment Filebeat is started. 
- The file `this_file_is_locked` cannot be renamed/deleted/moved for about 1m since the moment Filebeat is started.

- Logs from each scenario:
[filebeat_case_1.log](https://github.com/elastic/beats/files/7591762/filebeat_case_1.log)
[filebeat_case_2.log](https://github.com/elastic/beats/files/7591763/filebeat_case_2.log)
[filebeat_case_3.log](https://github.com/elastic/beats/files/7591764/filebeat_case_3.log)
