### ISSUE TITLE
Getting  x509: certificate signed by unknown authority 

### ISSUE THREAD

**Issue by jainpratik163** [elastic/beats#29144]
I am trying to install metricbeat on my K8s server and  i am getting  **this error  x509: certificate signed by unknown authority**.
and also in values file i mentioned this but still it is checking certificate.

```
ssl:
        verification_mode: "none"
```

i want to know what i am doing wrong or how i can pass my CA certificate 

below is my values file contain

```
daemonset:
  overrideConfig:
    metricbeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false
    processors:
      - add_cloud_metadata:
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9201}']
deployment:
  overrideConfig:
    metricbeat.config.modules:
      path: ${path.config}/modules.d/*.yml
      reload.enabled: false
    processors:
      - add_cloud_metadata:
    output.elasticsearch:
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9201}']
      ssl:
        verification_mode: "none"

```
i am deploying this docker image **metricbeat-oss:6.7.0**
