### ISSUE TITLE
[Heartbeat] Run once mode fails to index all metadata

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/beats#29256]
+ When run in Heartbeat once shot mode which can be configured to run once and exit. Some of the metadata like tags and event dataset are missing. 

```yaml
heartbeat.monitors:
- id: http-monitor
  name: HTTP Monitor
  schedule: '@every 1m'
  tags:
    - "tag1"
    - "tag2"
  type: http
  urls:
  - http://www.elastic.co

output.console: ~
```

+ Tags are not getting indexed properly. When switching off the run_once mode. Everything is properly indexed. 
+ Same happens to event.dataset object.
