### ISSUE TITLE
ndjson parser: json fields are stored not correctly under `target` 

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/beats#29395]
Configuration example:
```
parsers:
- ndjson:
    add_error_key: true
    target: kubernetes.audit
```
I would expect to get it stored like:
```
"kubernetes": {
   "audit": {
      "userAgent": ...,
```
but instead I am getting:
```
"kubernetes.audit": {
   "userAgent": ...
    ...
}
```
