### ISSUE TITLE
[Filebeat] httpjson - Add function to return User-Agent

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#29453]
**Describe the enhancement:**

Adding a Go template function to the httpjson input to allow enriching the built-in User-Agent with additional comments. The function prototype would be something like `func userAgent(comments ...string) string`. Comments are added to the existing UA string and are separated by `; ` (colon + space).

Usage

```
request.transforms:
  - set:
      target: "header.User-Agent"
      value: "[[ userAgent 'integration_name/1.2.3' ]]"
```

This would produce a header

> `User-Agent: Elastic-Filebeat/8.1.0 (darwin; amd64; 9b893e88cfe109e64638d65c58fd75c2ff695402; 2021-12-15 13:20:00 +0000 UTC; integration_name/1.2.3)`

**Describe a specific use case for the enhancement or feature:**

Adding Fleet package metadata to requests.

### Related

- https://github.com/elastic/kibana/issues/121310

### References

- https://datatracker.ietf.org/doc/html/rfc7231#section-5.5.3

**Comment by legoguy1000** [comment]
PR opened and ready for review.  One small thing I found is that in order to completely override the User Agent header, you must first delete the original value.
```
  request.transforms:
    - delete:
        target: "header.User-Agent"
    - set:
        target: "header.User-Agent"
        value: '[[ userAgent "integration_name/1.2.3" ]]'
```
This is due to the `setheader` function appends values to headers so if a value already exists, it will now have 2 values.  See https://github.com/elastic/beats/blob/master/x-pack/filebeat/input/httpjson/transform_set.go#L140.
