### ISSUE TITLE
Can't run pod as user heartbeat because of files permissions

### ISSUE THREAD

**Issue by aleksrosz** [elastic/beats#29465]
- Version: docker.elastic.co/beats/heartbeat:7.16.1
- Operating System: k8s
- Steps to Reproduce: 
I think it should be possible to run this application inside container using:
```
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          runAsGroup: 1000 (heartbeat group)
          runAsNonRoot: true
          runAsUser: 1000 (heartbeat group)
      securityContext: 
        fsGroup: 1000
```
        
but when I use this configuration I got error: 

`2021-12-16T09:09:26.466Z    INFO    instance/beat.go:686    Home path: [/usr/share/heartbeat] Config path: [/usr/share/heartbeat] ││ 2021-12-16T09:09:26.466Z    ERROR    instance/beat.go:1015    Exiting: Failed to create Beat meta file: open /usr/share/heartbeat ││ Exiting: Failed to create Beat meta file: open /usr/share/heartbeat/data/meta.json.new: permission denied`

I think it should be possible by default. Am I wrong?

**Comment by emilioalvap** [comment]
Hi @aleksrosz, 

Thank you very much for creating this issue. 

I'm assuming you're using heartbeat k8s configuration linked in the [official guide](https://www.elastic.co/guide/en/beats/heartbeat/7.16/running-on-kubernetes.html). Docker image relies on `heartbeat (1000)` user belonging to `root (0)` group for permissions to write to output directory `/usr/share/heartbeat/data`. These are the required permissions (taken from inside the container):

```bash
$ ls -al /usr/share/heartbeat/ | grep data
drwxrwxr-x 1 root      root      4096 Jan 29 18:43 data
```

When deploying the kubernetes config, this directory is being mounted inside a volume with the following settings:

```yml
        volumeMounts:
          ...
        - name: data
          mountPath: /usr/share/heartbeat/data
      volumes:
      ...
      - name: data
        hostPath:
          path: /var/lib/heartbeat-data
          type: DirectoryOrCreate
```

By default with `type: DirectoryOrCreate`, target directory is created with `rwxr-x-r-x` permissions if it doesn't already exist, so `root` group has no write permissions. In order to run the container in root-less mode, you can either:
- Remove `data` mounted volume from the configuration, so the directory will retain permissions set inside the container.
- If you have access to k8s host, you can create the target directory in advance and assign required permissions:

```bash
$ mkdir -m 765 /var/lib/heartbeat-data
$ curl -L -O https://raw.githubusercontent.com/elastic/beats/7.16/deploy/kubernetes/heartbeat-kubernetes.yaml
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5048  100  5048    0     0  21299      0 --:--:-- --:--:-- --:--:-- 21299
$ kubectl replace --force -f heartbeat-kubernetes.yaml
...
$ kubectl --namespace=kube-system get pods | grep heartbeat
heartbeat-65455d57b9-9qmcp         1/1     Running   0               48s
```

Let me know if this solves your doubt.
