### ISSUE TITLE
[Metricbeat] gcp module metrics metricset apply aligner to all metric_types 

### ISSUE THREAD

**Issue by kwinstonix** [elastic/beats#29513]
For confirmed bugs, please report:
- Version: 7.16.1 
- Operating System: Macos & Linux
- Discuss Forum URL:
- Steps to Reproduce: 

1. metricbeat config

```yaml
metricbeat.modules:
- module: gcp
  metricsets:
    - metrics
  zone: "asia-east1-c"
  project_id:  GCP PROJECT ID
  credentials_file_path:  CREDENTIALS
  exclude_labels: false
  period: 300s
  metrics:
    - aligner: ALIGN_MEAN
      service: compute
      metric_types:
        - "instance/cpu/utilization"
    - aligner: ALIGN_SUM
      service: compute
      metric_types:
        - "instance/uptime_total"

```

2. metricbeat events

Metricbeat reports four metric with four event log, but `uptime_total.avg` and `utilization.sum` are not expected metrics.

```

  "gcp": {
    "metrics": {
      "instance": {
        "uptime_total": {
          "avg": 437218
        }
      }
    },

-----

  "gcp": {
    "metrics": {
      "instance": {
        "cpu": {
          "utilization": {
            "avg": 0.07700735991259837
          }
        }
      }
    }
  },


---

"gcp": {  
    "metrics": {
      "instance": {
        "uptime_total": {
          "sum": 2186090
        }
      }
    }
  },

----

"gcp": {
    "metrics": {
      "instance": {
        "cpu": {
          "utilization": {
            "sum": 0.38503679956299186
          }
        }
      }
    },

```

3. debug log

`requester.Metrics` may be the cause of the bug.

![image](https://user-images.githubusercontent.com/12824991/146663286-ea01e9c7-ef43-48d1-bb05-c3b8e7ff9fa3.png)
