### ISSUE TITLE
ndjson parser: @timestamp is not being overwritten

### ISSUE THREAD

**Issue by scroodj** [elastic/beats#29531]
Elastic Stack version: 7.16

`ndjson parser of filestream input` does not overwritte @timestamp values coming from the JSON object,
as a result in Elasticsearch i have timestamp when document was indexed. Debug output shows no issues.

**Log example:**
```
{"@timestamp":"2021-12-19T18:09:09.575+01:00","@version":"1","message":"adminRequest http://localhost:4070/","logger_name":"org.keycloak.adapters.PreAuthActionsHandler","thread_name":"http-nio-4070-exec-1","level":"DEBUG","level_value":10000}
```

**Filebeat.yml**
```
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

#Control Templating and ILM Policy Manually
setup.template.enabled: false
setup.ilm.enabled: false

#Fetching Logs
filebeat.inputs:
- type: filestream
  paths: 
     - '/data/nas/ecm_logs/accept/milp/finn-milp-log.json'
  fields_under_root: true
  parsers:
    - ndjson:
      keys_under_root: true
      add_error_key: true
      overwrite_keys: true
  processors:
  - dissect:
      tokenizer: "/data/nas/ecm_logs/%{stage}/%{project}/%{service}-log.json"
      field: "log.file.path"
      target_prefix: ""
  - script:
      lang: javascript
      source: >
        function process(event) {
          event.Put("@metadata.index_prefix", "log"+"-"+event.Get("stage")+"-"+event.Get("project"));
        }

#Push data to Elasticsearch Cluster
output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "%{[@metadata.index_prefix]}"
```

However, there is no problem if i use `Log input`,` json.* `options work as expected and @timestamp field has a value from the log:
```
filebeat.inputs:
- type: log
  paths: 
    - '/data/nas/ecm_logs/accept/milp/finn-milp-log.json'
  json.keys_under_root: true
  json.add_error_key: true
  json.overwrite_keys: true
  processors:
  - dissect:
      tokenizer: "/data/nas/ecm_logs/%{stage}/%{project}/%{service}-log.json"
      field: "log.file.path"
      target_prefix: ""
  - script:
      lang: javascript
      source: >
        function process(event) {
          event.Put("@metadata.index_prefix", "log"+"-"+event.Get("stage")+"-"+event.Get("project"));
        }
```

**Comment by IrakliyBerison** [comment]
hello!
same problem 7.17
is there any solution?

**Comment by duclm2609** [comment]
I have the same issue. This problem is really seriouse as it make the log stream output order on Elasticsearch is not correct anymore, which is very important requirement in log processing.

**Comment by kvch** [comment]
This is not a bug, your configuration is incorrect. In the `ndjson` parser you have to set `target` to `""` to put the fields under the root of the event. See more in the docs: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html#_ndjson

The correct `ndjson` configuration is the following:

```yaml
  parsers:
    - ndjson:
      target: ""
      add_error_key: true
      overwrite_keys: true
```

**Comment by kelunik** [comment]
Please note: Don't forget to indent `target` and the following keys... :see_no_evil:

**Comment by GeorgeGkinis** [comment]
Please reopen,

It still does not work with version 7.17.3:

```
 parsers:
  - ndjson:
      overwrite_keys: true
      add_error_key: true
      expand_keys: true
      target: ""
```

Example row:
```
{"@timestamp":"2023-09-20T11:11:27.678Z","log.level": "INFO","message":"Getting uptime info BLA bLA BLA BLA BAAAAAAAAAT","ecs.version": "1.2.0","service.name":"app-2-java","service.environment":"tst","event.dataset":"app-2-java.CONSOLE","process.thread.name":"http-nio-8080-exec-1","log.logger":"nl.kvk.healthcheck.poc.api.MyController","transaction.id":"b373b2bf23ded653","trace.id":"235ae47594d238b7003e115051672201"}"
```
