### ISSUE TITLE
Kubernetes: missing annotations enrichment

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/beats#29597]
When working on https://github.com/elastic/integrations/issues/2362, I've noticed that events are not enriched with node annotations when used `include_annotations`.
Configuration example:
```
add_resource_metadata:
  namespace:
    include_labels: ["test.label"]
  node:
    include_labels: ["test.node.label", "kubernetes.io/arch"]
    include_annotations: ["test.annotation"]
```
