### ISSUE TITLE
[Filebeat] Nomad Autodiscover Provider - Missing TLS config options

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#29639]
The nomad autodiscover provider is missing a way to specify TLS options. When running in Docker where it's hard to modify the container's CA certs you need to be able to configure the CA cert for the nomad API.

```
filebeat.autodiscover:
  providers:
    - type: nomad
      address: https://foo:4646
      # MISSING SUPPORT FOR THIS:
      ssl:
        certificate_authorities: [/secrets/ca.crt]
```

https://github.com/elastic/beats/blob/1386a04099c81f791b334616437d71c56109e0e9/x-pack/libbeat/common/nomad/util.go#L11-L16
