### ISSUE TITLE
multiple `- module: name` configuration has different behaviour between `modules.d/module.yml` and `filebeat.yml`

### ISSUE THREAD

**Issue by aspacca** [elastic/beats#29649]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: v7.16.1, v7.16.2, master
- Operating System:  n/a
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-multiple-vpc-logs-from-different-s3-buckets-not-working/292711/10
- Steps to Reproduce: 
Define in `filebeat.yml` the following:
```
filebeat.modules:
  - module: aws
    cloudtrail:
      enabled: false
    cloudwatch:
      enabled: false
    ec2:
      enabled: false
    s3access:
      enabled: false
    elb:
      enabled: false
    vpcflow:
      enabled: true
      var.queue_url: "https://sqs.eu-central-1.amazonaws.com/account-id/queue-1"
  - module: aws
    cloudtrail:
      enabled: false
    cloudwatch:
      enabled: false
    ec2:
      enabled: false
    s3access:
      enabled: false
    elb:
      enabled: false
    vpcflow:
      enabled: true
      var.queue_url: "https://sqs.eu-central-1.amazonaws.com/account-id/queue-2"
```

run filebeat and observe how only one of the two modules/queues is actually loaded

configure the same multiple modules in `modules.d/aws.yml`:
```
  - module: aws
    cloudtrail:
      enabled: false
    cloudwatch:
      enabled: false
    ec2:
      enabled: false
    s3access:
      enabled: false
    elb:
      enabled: false
    vpcflow:
      enabled: true
      var.queue_url: "https://sqs.eu-central-1.amazonaws.com/account-id/queue-1"
  - module: aws
    cloudtrail:
      enabled: false
    cloudwatch:
      enabled: false
    ec2:
      enabled: false
    s3access:
      enabled: false
    elb:
      enabled: false
    vpcflow:
      enabled: true
      var.queue_url: "https://sqs.eu-central-1.amazonaws.com/account-id/queue-2"
```

run filebeat and observe how both the two modules/queues are loaded

it's not relevant for the test that the queues actually exist
