### ISSUE TITLE
Filebeat not closing deleted files

### ISSUE THREAD

**Issue by joshuaspence** [elastic/beats#2968]
On an Ubuntu 16.04 host with Filebeat 5.0.0, we experience an issue in which the host ran out of disk space. It seems that Filebeat was keeping file descriptors open well after the original log file had been removed. This might be our own fault, because of the following two facts:

  - We have configured a Filebeat prospector to harvest Filebeat's own logs.
  - Whilst debugging an unrelated issue a few days ago, I set `logging.level` to `debug` on the host which ran out of disk space.

Here is the output of running `sudo lsof | grep filebeat | grep /var/log/filebeat` on the affected host: https://gist.github.com/joshuaspence/82489c5ee34f5c0c63596e0bab844d00

I was able to reproduce this issue with the following Filebeat configuration:

```
filebeat.spool_size: 2048
filebeat.publish_async: false
filebeat.idle_timeout: 5s
filebeat.registry_file: /var/lib/filebeat/registry
filebeat.config_dir: /etc/filebeat/conf.d
filebeat.shutdown_timeout: 0
fields_under_root: true
queue_size: 1000
output.logstash:
  hosts:
    - beats.service.consul:5044
  worker: 3
  loadbalance: true
logging.level: debug
filebeat:
  prospectors:
    - input_type: log
      paths:
        - /var/log/filebeat/filebeat
      encoding: plain
      fields_under_root: false
      document_type: filebeat
      scan_frequency: 10s
      harvester_buffer_size: 16384
      max_bytes: 10485760
      tail_files: false
      backoff: 1s
      max_backoff: 10s
      backoff_factor: 2
```

After around half an hour, this is what I saw:

```
> sudo lsof | grep filebeat | grep /var/log/filebeat | cut -c 81- | sort | uniq
393882 /var/log/filebeat/filebeat.7 (deleted)
411420 /var/log/filebeat/filebeat.7 (deleted)
411421 /var/log/filebeat/filebeat.7 (deleted)
414295 /var/log/filebeat/filebeat.7 (deleted)
414296 /var/log/filebeat/filebeat.7 (deleted)
427793 /var/log/filebeat/filebeat.7 (deleted)
427794 /var/log/filebeat/filebeat.7 (deleted)
427805 /var/log/filebeat/filebeat.7 (deleted)
427806 /var/log/filebeat/filebeat.7 (deleted)
427807 /var/log/filebeat/filebeat.7 (deleted)
427808 /var/log/filebeat/filebeat.7 (deleted)
427809 /var/log/filebeat/filebeat.7 (deleted)
427810 /var/log/filebeat/filebeat.7 (deleted)
427811 /var/log/filebeat/filebeat.7 (deleted)
427812 /var/log/filebeat/filebeat.7 (deleted)
427813 /var/log/filebeat/filebeat.7 (deleted)
427814 /var/log/filebeat/filebeat.7 (deleted)
427815 /var/log/filebeat/filebeat.7 (deleted)
427821 /var/log/filebeat/filebeat.7 (deleted)
427822 /var/log/filebeat/filebeat.7 (deleted)
427823 /var/log/filebeat/filebeat.7 (deleted)
427825 /var/log/filebeat/filebeat.7 (deleted)
427826 /var/log/filebeat/filebeat.7 (deleted)
427828 /var/log/filebeat/filebeat.7 (deleted)
427829 /var/log/filebeat/filebeat.7 (deleted)
427831 /var/log/filebeat/filebeat.7 (deleted)
427832 /var/log/filebeat/filebeat.7 (deleted)
427834 /var/log/filebeat/filebeat.6
427835 /var/log/filebeat/filebeat.5
427836 /var/log/filebeat/filebeat.4
427838 /var/log/filebeat/filebeat.3
427839 /var/log/filebeat/filebeat.2
427840 /var/log/filebeat/filebeat.1
427846 /var/log/filebeat/filebeat
```
