### ISSUE TITLE
[Keystore] parsing with leading `,` leads to an error and exposing the password in clear text in the log

### ISSUE THREAD

**Issue by philippkahr** [elastic/beats#29789]
For confirmed bugs, please report:
- Version: 7.16.2
- Operating System: tested it on windows and macOS
- Discuss Forum URL:
- Steps to Reproduce: 

Tested with filebeat but should apply to every beat.

1. download filebeat 7.16.2
2. configure filebeat.yml

```yml
#password in pwd is ',hello'
output.elasticsearch:
  hosts: ["localhost:9200"]
  username: "demo"
  password: "${pwd}"
```

3. run `./filebeat keystore create`
4. run `./filebeat keystore add pwd` and enter `,hello` as a password
5. run `./filebeat -e` you should get this error

```
2022-01-11T13:13:53.397+0100    ERROR   instance/beat.go:1015   Exiting: error initializing publisher: unexpected ',' when parsing ',hello' accessing 'output.elasticsearch.password' (source:'filebeat.yml')
Exiting: error initializing publisher: unexpected ',' when parsing ',hello' accessing 'output.elasticsearch.password' (source:'filebeat.yml')
```

I only testet it with a leading `,` but I guess more characters can cause an issue.
