### ISSUE TITLE
[Self-managed]: Unable to install Metricbeat from other machine for a self-managed environment on different machine.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#29807]
**Kibana version:**  8.0-rc1-BC-1 Kibana self-managed environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
Build: 48917
Commit: 51f4ded427abb6fd96c7d65e179fb367d450448c
Artifact Link: https://staging.elastic.co/8.0.0-rc1-da1f5893/summary-8.0.0-rc1.html
```

**Preconditions:**
1. 8.0-rc1-BC-1 Kibana self-managed environment should be available.

**Steps to reproduce:**
1. Navigate to different machine.
2. Download and extract metricbeat artifact.
3. Update metricbeat.yml with below changes
```
# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  hosts: ["https://<self-managed-ip>:9200"]
  username: "elastic"
  password: "QcRwtbgcax_YokU9TBRv"
  # If using Elasticsearch's default certificate
  ssl.ca_trusted_fingerprint: "44feaf967da83d56d58539c75211bc46add536cf5048f1c24e6231d1a88e69a2"
setup.kibana:
  host: "https://<self-managed-ip>:5601"
```
4. Run below commands:
.\install-service-metricbeat.ps1
.\metricbeat.exe setup
5. Observe connection error to Kibana.

**Expected Result:**
Metricbeat should be installed from other machine for a self-managed environment on different machine.

**Screenshots:**
![2](https://user-images.githubusercontent.com/77374876/149085095-8ac49fd8-2625-45e0-90bb-0090619fb175.JPG)
- Tried the same with http and https.

**NOTE:**
- We are able to install elastic-agents and standalone agents from different machines to the self-managed environment on different machine.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @jlind23

**Comment by jlind23** [comment]
@amolnater-qasource did you try to curl the url mentioned above? Could it be a proxy issue? Is the Kibana url the same when installing other beats?
@cmacknz I may need your help here.

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
Just to clarify that this issue is related to https://github.com/elastic/beats/issues/28152
Like we installed Multiple elastic-agents from different VMs on a self-managed setup.
We attempted to run the same for standalone agents and beats.
- We were able to setup standalone agents from various VMs.
- However observed errors for Beats setup from different VMs on a different self-managed setup.

>Could it be a proxy issue?

Yes, it could be.

>Is the Kibana url the same when installing other beats?

If we have to install beat on the same VM with the self-managed setup we use below configuration:
```
# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  hosts: ["https://localhost:9200"]
  username: "elastic"
  password: "QcRwtbgcax_YokU9TBRv"
  # If using Elasticsearch's default certificate
  ssl.ca_trusted_fingerprint: "44feaf967da83d56d58539c75211bc46add536cf5048f1c24e6231d1a88e69a2"
setup.kibana:
  host: "https://localhost:5601"
```

As it wasn't working with this, so we have done some configuration changes to test this.

Please let me know if am missing anything.
Thanks!
