### ISSUE TITLE
[Heartbeat][Browser] Heartbeat as a Load Tester

### ISSUE THREAD

**Issue by BenB196** [elastic/beats#29822]
**Describe the enhancement:**

**Note:** I recognize that this request is outside of the scope of monitoring and probably outside the scope of what Heartbeat was probably ever considered for, so feel free to close if it isn't something that will be implemented.

---

I'd like to request the ability to configure Heartbeat with the browser monitor to act as a load tester for applications.

With Heartbeat supporting browser (synthetic) monitoring I thought that if I already have tests written to monitor the functionality of my apps, why not use these same tests to put load on these apps for load testing.

To better explain the concept below is rough idea of what I think the config for it could be:

```yaml
heartbeat.run_once: true # I think you'd want Heartbeat to not continuously run, so setting this would probably be ideal.
heartbeat.monitors:
- type: browser
  id: load-tester
  name: Load Tester
  schedule: '@every 1m'
  source: #...
  params: #...
  screenshots: #...
  #...
  load_testing:
    instances: 100 # The number of `instance` tests heartbeat will spin up for load testing
    ramp: # How to spin up the `instances` used in the load testing
      duration: 100s # The duration that all `instances` should be running within
      distribution: 'even'/`random` # How the `instances` are started within the `duration` time.
                                # `even` Would be `instances`/`ramp.duration`, in this example 1 instance per second.
                                # `random` Heartbeat would randomly choose when to start instance as long as...
                                # they are all started within `ramp.duration` window.
    reporting: # Determines how much data is sent back to Elastic from the tests.
      failures: true/false # If true, all failed `instances` report back their data.
                           # If false, failed `instances` follow regular reporting logic.
      instances: 10/'5%' # How many instances should report back their collected information.
                         # Can either be a hard number (10) or a percentage (5%)
      distribution: 'random'/'duration'/'percentiles' # Determines how heartbeat will select which instance data to send back.
                                                      # `random` Heartbeat chooses instance at random
                                                      # `duration` Hearbeat chooses instances with the highest durations
                                                      # `percentile` Heartbeat chooses instances with durations...
                                                      # within a set of percentile ranges
      percentiles: ['99','95','75','50','25'] # List of percentile ranges heartbeat will use for `percentile` distribution.
```

**Describe a specific use case for the enhancement or feature:**

I have apps which I monitor with Heartbeat browser. I want to use those same tests to load test the apps, and have Heartbeat collect and send the information back to Elastic for analysis.
