### ISSUE TITLE
Inline monitor syntax errors should send errors to ES

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#29897]
Error can be reproduced by running the below monitor. 
```yml
heartbeat.run_once: true
heartbeat.monitors:
- type: browser
  enabled: true
  id: my-monitor
  name: My Monitor
  screenshots: "off"
  source:
    inline:
      script:
        asdas
        step("load homepage", async () => {
            await page.goto('https://www.elastic.co');
        });
  schedule: "@every 1m"

output.console: ~

```

+ The synthetics runner writes the errors back to `stderr` without any JSON marshalling as it cannot get the registered journeys. In these cases, HB cannot write the summary event as there are no acrtive journeys. 

By disabling this check, we get the summary event- https://github.com/elastic/beats/blob/96e393f4e06334db1875fe62fb07a0be701fd3b9/x-pack/heartbeat/monitors/browser/synthexec/execmultiplexer.go#L37

But we need to swallow the error and do it correctly.
