### ISSUE TITLE
[DOCS] [Filebeat] Confusing multiline documentation for filestream

### ISSUE THREAD

**Issue by a03nikki** [elastic/beats#29919]
The logs are confusing for how to configure multiline events with the newer `filesteam` input type.

The Filebeat accepts (aka starts and tries to send logs) with both the old syntax

```yaml
  multiline.type: pattern
  multiline.pattern: '^2022'
  multiline.negate: true
  multiline.match: after
```

and the new parser syntax 

```yaml
  parsers:
    - multiline:
        type: pattern
        pattern: '^2022'
        negate: true
        match: after
```

for multi-line log events.  However, only the new syntax actually creates multiline events.

The documentation does not make clear the difference between (new) filestream input's `parsers` and (old) log input's `multiline` settings.

- <https://www.elastic.co/guide/en/beats/filebeat/7.16/filebeat-input-filestream.html#_multiline_4>
- <https://www.elastic.co/guide/en/beats/filebeat/7.16/multiline-examples.html>
- <https://www.elastic.co/guide/en/beats/filebeat/7.16/filebeat-input-log.html#_multiline_6>

I checked 7.16, 7.17 (unreleased), and master and the documentation does not appear to be updated yet.

I found [this on StackOverflow](https://stackoverflow.com/questions/67784091/multi-line-filebeat-templates-don-t-work-with-filebeat-inputs-type-filestream) of another user who was confused with a link to [this discuss post](https://discuss.elastic.co/t/filebeat-filestream-input-parsers-multiline-fails/290543) related to this configuration change.
