### ISSUE TITLE
provide name for processor.rate_limit monitoring registry 

### ISSUE THREAD

**Issue by bigpigeon** [elastic/beats#29926]
**Describe the enhancement:**

when I access http://filebeat:5066/stats to monitor the processor.rate_limit struct , get just like below data
```
"1": {
  "dropped": 1
},
"2": {
  "dropped": 4
},
"3": {
  "dropped": 5
}
```

This information is so difficult to match  rate_limit processor which define in filebeat.autodiscover

I hope add name field to processors.rate_limit config, and then map the name to rate_limit.metrics

**Describe a specific use case for the enhancement or feature:**

config in filebeat.conf:

```
filebeat.autodiscover:
  enabled: false
  # List of enabled autodiscover providers
  providers:
  - type: kubernetes
    kube_config: /home/jia/.kube/config
    templates:
        processors:
        - rate_limit:
            limit: 100/m
            name: "${data.kubernetes.pod.name}_${data.kubernetes.container.name}_stdlog"
...
```

and then I can view below data in http://nodeip:5066/stats

···
...
 "processor": {
    "rate_limit": {
      "mypod_containerName_stdlog": {
        "dropped": 0
      }
  },
...
···
