### ISSUE TITLE
metricbeat monitoring of Elasticsearch and Kibana broke on recent 7.17.0-SNAPSHOT rpm

### ISSUE THREAD

**Issue by LeeDr** [elastic/beats#29920]
Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 7.17.0-SNAPSHOT
- Operating System: CentOS 7
- Discuss Forum URL:
- Steps to Reproduce: 
1. Install metricbeat and enable modules for monitoring Elasticsearch, Kibana, Logstash, and Beats

Monitoring worked on the 7.17.0-766e7ca2 SNAPSHOT build from Jan 18, 2022 10:02 AM
but fails on the 7.17.0-68da5d12 SNAPSHOT build from Jan 18, 2022 5:38 PM
and also fails on the 7.17.0-1bd53ff7 BC2 build.

I don't find anything of interest in the metricbeat log.  I don't see anything about monitoring in the log with either the passing or failing tests.

All of the configuration is the same between the build that passes and the builds that fail.  I've run the passing and failing builds locally with the same results as on Jenkins.

/etc/metricbeat/metricbeat.yml:
```
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.period: 10s
  reload.enabled: false
metricbeat.max_start_delay: 10s
metricbeat.modules:
- module: system
  enabled: true
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
  processes: ['.*']
- module: system
  enabled: true
  period: 1m
  metricsets:
    - filesystem
    - fsstat
- module: kibana
  metricsets: ["status"]
  enabled: false
  period: 10s
  hosts: ["localhost:5601"]
- module: elasticsearch
  metricsets: ["node", "node_stats"]
  enabled: false
  period: 10s
  hosts: ["localhost:9200"]


output.elasticsearch:
  hosts: ["localhost:9200"]
  protocol: https
  username: "beats_internal"
  password: "changeme"
  ssl.enabled: true
  ssl.certificate_authorities: ["/etc/metricbeat/ca.crt"]
  ssl.certificate: /etc/metricbeat/elasticsearch.crt
  ssl.key: /etc/metricbeat/elasticsearch.key

#setup.dashboards.snapshot: true

setup.kibana:
  protocol: https
  host: localhost:5601
  username: "beats_internal"
  password: "changeme"
  ssl.enabled: true
  ssl.certificate_authorities: ["/etc/metricbeat/ca.crt"]
  ssl.certificate: /etc/metricbeat/elasticsearch.crt
  ssl.key: /etc/metricbeat/elasticsearch.key

xpack.monitoring:
  enabled: false
  elasticsearch:
    url: "https://localhost:9200"
    username: elastic
    password: changeit
http.enabled: true
http.port: 5068
```

```
[root@localhost vagrant]# ls -l /etc/metricbeat/modules.d/ | grep -v disabled
total 272
-rw-r--r-- 1 root root  295 Jan 19 22:31 beat-xpack.yml
-rw-r--r-- 1 root root  456 Jan 19 22:31 elasticsearch-xpack.yml
-rw-r--r-- 1 root root  461 Jan 19 22:31 kibana-xpack.yml
-rw-r--r-- 1 root root  251 Jan 19 22:31 logstash-xpack.yml
-rw-r--r-- 1 root root  956 Jan 19 14:31 system.yml
```

The `beats_internal` user in the config has;
```
curl -k https://elastic:changeit@localhost:9200/_security/user/beats_internal
{"beats_internal":{"username":"beats_internal","roles":["beats_writer","beats_reader","kibana_admin","machine_learning_admin","remote_monitoring_agent"],"full_name":"beats_internal","email":"beats_internal@test.co","metadata":{},"enabled":true}}
```

And `beats_reader` role is;
```
[root@localhost vagrant]# curl -k https://elastic:changeit@localhost:9200/_security/role/beats_reader
{"beats_reader":{"cluster":[],"indices":[{"names":["*beat-*"],"privileges":["read","view_index_metadata"],"allow_restricted_indices":false}],"applications":[],"run_as":[],"metadata":{},"transient_metadata":{"enabled":true}}}
```

And `beats_writer` role is;
```
[root@localhost vagrant]# curl -k https://elastic:changeit@localhost:9200/_security/role/beats_writer
{"beats_writer":{"cluster":["manage_index_templates","monitor","manage_ilm"],"indices":[{"names":["filebeat-*","metricbeat-*","heartbeat-*","packetbeat-*","auditbeat-*","winlogbeat-*",".kibana*"],"privileges":["write","delete","create_index","manage","manage_ilm"],"allow_restricted_indices":false}],"applications":[],"run_as":[],"metadata":{},"transient_metadata":{"enabled":true}}}
```

**Comment by LeeDr** [comment]
The same test passed on  8.0.0-rc2-c0b0e70d which was built today and also on the latest 8.1.0 snapshot build.

**Comment by LeeDr** [comment]
I'm just guessing here but I'm thinking maybe this PR shouldn't have been backported to 7.17?  https://github.com/elastic/beats/pull/29869

But in both the passing and failing cases I can see the legacy templates for monitoring are there.

**Comment by ChrsMark** [comment]
cc: @sayden

**Comment by sayden** [comment]
Those configs show elasticsearch and kibana as `enabled: false`. Usually you just want to add `xpack.enabled: true` like this: 

```yml
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts: ["http://localhost:9200"] 
```

More info https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-metricbeat.html

**Comment by LeeDr** [comment]
I changed those false's to true and restarted metricbeat but still not .monitoring-es index is created.

Is there a way to enable debug logging?  I'm surprised there's nothing in the metricbeat log about which modules it's using.

**Comment by LeeDr** [comment]
I'm back on the earlier 7.17.0-766e7ca2  build now again.  Those values in metricbeat.yml are false;
```
- module: kibana
  metricsets: ["status"]
  enabled: false
  period: 10s
  hosts: ["localhost:5601"]
- module: elasticsearch
  metricsets: ["node", "node_stats"]
  enabled: false
  period: 10s
  hosts: ["localhost:9200"]
```

But I do have monitoring indices created.  Notice I have an index for logstash and beats monitoring but there isn't even a section in the metricbeat.yml for it.  Those work based on the module file being not disabled.
```
green  open .monitoring-beats-7-mb-2022.01.20    i5J1UjhJRY-4dEn23G-lIw 1 0     8    0  98.2kb  98.2kb
green  open .monitoring-logstash-7-mb-2022.01.20 gUqEMkSKQvKEPQuQfl9rzA 1 0    45    0 114.6kb 114.6kb
green  open .monitoring-kibana-7-mb-2022.01.20   SLszlLApQZG80p0pynSArw 1 0    36    0 121.6kb 121.6kb
green  open .monitoring-es-7-mb-2022.01.20       9QEcQ8CEQM68TB3LrG1xgg 1 0   751    0     1mb     1mb
```

**Comment by LeeDr** [comment]
FYI @marius-dr who set some of this up for the Kibana-QA team.

**Comment by LeeDr** [comment]
> Those configs show elasticsearch and kibana as `enabled: false`. Usually you just want to add `xpack.enabled: true` like this:
> 
> ```yaml
>   - module: elasticsearch
>     xpack.enabled: true
>     period: 10s
>     hosts: ["http://localhost:9200"] 
> ```
> 
> More info https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-metricbeat.html

I was a little confused by this too.  But what I see now is that the section in `/etc/metricbeat/metricbeat.yml` looks a lot like the section in `/etc/metricbeat/modules.d/elasticsearch-xpack.yml`.  In the metricbeat.yml that `xpack.enabled:` is false, but in the `elasticsearch-xpack.yml` it's true.

**Comment by sayden** [comment]
It is a bit confusing, without doubt. More in the case of Stack Monitoring, my apologies in advance. The `.monitoring` templates for monitoring are installed exceptionally by elasticsearch itself. The most important metric to check is the number of docs of those indices.

Generally speaking you want to maintain "cluster config" in `metricbeat.yml`: elasticsearch credentials, kibana, security, etc. and modules config on the files you can find in `modules.d`: elasticsearch, logstash and kibana modules ("module" with the same meaning of mysql module for example) because one of them will override the other (I think `metricbeat.yml` overrides everything in `modules.d`).

Maybe give it a try setting a barebones module configuration for elasticsearch in the `elasticsearch-xpack.yml` file on `modules.d` and removing everything related to elasticsearch module from `metricbeat.yml`. If that doesn't work, please share the config you have on the active files in `modules.d`.

Thanks! :slightly_smiling_face:

**Comment by LeeDr** [comment]
When it fails, the templates are there but no indices are created.  I figured out how to turn debug logging on in metricbeat so I'll see if I get more info from that and update here.

**Comment by pebrc** [comment]
I think the ECK operator e2e tests are also seeing this issue https://devops-ci.elastic.co/job/cloud-on-k8s-e2e-tests-snapshot-versions/498//testReport with similar symptoms: the monitoring indices are not created.

**Comment by LeeDr** [comment]
Similar to my case I see that @pebrc had a passing result on Jan 18th and failure on Jan 19th and all jobs since then.

**Comment by sayden** [comment]
I think this is related to the ECK operator, not to Stack Monitoring. I have just done a full test and it works:

`metricbeat.yml`
```yml
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml

  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.kibana:

output.elasticsearch:
  hosts: ["localhost:9200"]

  username: "elastic"
  password: "changeme"
```

`elasticsearch-xpack.yml`
```yml
# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.16/metricbeat-module-elasticsearch.html

- module: elasticsearch
  xpack.enabled: true
  period: 10s
  hosts: ["http://localhost:9200"]
  username: "elastic"
  password: "changeme"
```

`kibana-xpack.yml`
```yml
# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.16/metricbeat-module-kibana.html

- module: kibana
  xpack.enabled: true
  period: 10s
  hosts: ["http://localhost:5601"]
  #basepath: ""
  username: "elastic"
  password: "changeme"
```

Versions deployed:
```sh
CONTAINER ID   IMAGE                                                            COMMAND                  CREATED       STATUS                    PORTS                                NAMES
1737912bed50   docker.elastic.co/beats/elastic-agent-complete:7.17.0-SNAPSHOT   "/usr/bin/tini -- /u…"   2 hours ago   Up 25 minutes (healthy)                                        elastic-package-stack_elastic-agent_1
2e787f3a9475   docker.elastic.co/beats/elastic-agent-complete:7.17.0-SNAPSHOT   "/usr/bin/tini -- /u…"   2 hours ago   Up 25 minutes (healthy)   127.0.0.1:8220->8220/tcp             elastic-package-stack_fleet-server_1
fc1157ca2e73   docker.elastic.co/kibana/kibana:7.17.0-SNAPSHOT                  "/bin/tini -- /usr/l…"   2 hours ago   Up 25 minutes (healthy)   127.0.0.1:5601->5601/tcp             elastic-package-stack_kibana_1
d49b643b7369   elastic-package-stack_package-registry                           "./package-registry …"   2 hours ago   Up 25 minutes (healthy)   127.0.0.1:8080->8080/tcp             elastic-package-stack_package-registry_1
d1298174fc36   docker.elastic.co/elasticsearch/elasticsearch:7.17.0-SNAPSHOT    "/bin/tini -- /usr/l…"   2 hours ago   Up 25 minutes (healthy)   127.0.0.1:9200->9200/tcp, 9300/tcp   elastic-package-stack_elasticsearch_1
```

Cat response:
```sh
sayden➜~» curl -XGET localhost:9200/_cat/indices?v=true -u "elastic:changeme"  | grep monitoring          
                                                                          
green  open   .monitoring-kibana-7-mb-2022.01.26                                BzT8cZ2LTiClQvH-PZsw7A   1   0         60            0      144kb          144kb
green  open   .monitoring-es-7-mb-2022.01.26                                    _FZULYn4QICDaI9_pQrzGQ   1   0       4231            0      3.3mb          3.3mb
```

Metricbeat version:
```sh
sayden➜elastic/beats/metricbeat(7.17✗)» ./metricbeat version                                                                                                                                                                                                                                                       [13:58:27]
metricbeat version 7.17.0 (amd64), libbeat 7.17.0 [unknown built unknown]
```

As you can see, those are default configs are they slightly differ from the ones you posted. If it's something in the config it's probably a problem in libbeat but not in SM and affecting all other modules, which is unlikely but definitely possible.
