### ISSUE TITLE
does autodiscover support reload?

### ISSUE THREAD

**Issue by ascendlin** [elastic/beats#29984]
autodiscover config
```yaml
filebeat.autodiscover:
  providers:
    - type: docker
      labels.dedot: true
      templates:
        - condition:
            contains:
              docker.container.name: kibana
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"
output.console:
  pretty: true

processors:
- add_host_metadata: ~
- add_docker_metadata: ~
```
when i changed the condition “docker.container.name” to "demo1"
```yaml
docker.container.name: demo1
```
filebeat didn't reload
