### ISSUE TITLE
filebeat merged java stack trace information is truncated

### ISSUE THREAD

**Issue by shaxiaozz** [elastic/beats#30020]
filebeat collects java stack trace logs and uses time as a condition for merging lines. But I found that filebeat will not merge the content after more than 465 lines, and truncate the log. I don't know if it's normal

**filebeat configuration:**
```
filebeat.inputs:
- type: log
  enabled: true
  multiline:
      match: after
      negate: true
      pattern: ^[1-9]\d{3}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])\s+(20|21|22|23|[0-1]\d):[0-5]\d:[0-5]\d,\d{3}\s+
  paths:
    - /tmp/info-java-74579bbfcf-fzv5g.log
  fields:
    log_topics: test_java_2

output.kafka:
  enabled: true
  hosts: ["kafka-0-0.kafka-svc:9092,kafka-1-0.kafka-svc:9092,kafka-2-0.kafka-svc:9092"]
  topic: '%{[fields][log_topics]}'
  compression: gzip
```
**logstash configuration:**
```
input {
      kafka {
        bootstrap_servers => "kafka-0-0.kafka-svc:9092,kafka-1-0.kafka-svc:9092,kafka-2-0.kafka-svc:9092"
        topics => "test_java_2"
        codec => "json"
        consumer_threads => 5
        decorate_events => true
      }
    }

    output {
        if [fields][log_topics] == "test_java_2" {
        elasticsearch {
            hosts => ["elasticsearch-0-0.elasticsearch-svc:9200","elasticsearch-1-0.elasticsearch-svc:9200","elasticsearch-2-0.elasticsearch-svc:9200"]
            index => "test_java_2-%{+YYYY.MM.dd}"
            user => "elastic"
            password => "password"
        }
    }
    }
```
This is the log collected from kibana：
![image](https://user-images.githubusercontent.com/43721571/151134578-af816925-b7ac-49d0-9dc1-6094cbe3afa5.png)

This is the content of the source file：
![image](https://user-images.githubusercontent.com/43721571/151135072-5eb9b124-b7ef-4ffb-bab0-4923e381812e.png)

filebeat only merges into the line "at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)", and the subsequent stack trace information is discarded until the next line that has elapsed time appears.

why is that? can you help me
