### ISSUE TITLE
Filebeat fails to start with Norwegian characters in the configuration

### ISSUE THREAD

**Issue by immavalls** [elastic/beats#30053]
**Version**: 7.16.0
**Operating System**: Tested on Windows and MacOS

**Description**:

Hi team,

When using characters like `å` in comments of configuration, Filebeat fails with `Exiting: error loading config file: yaml: invalid trailing UTF-8 octet`:

**Steps to Reproduce**:

Introduce some characters either in the comments or the configuration:

```yaml
# loggområde
```
 
```yaml
- type: log
  enabled: true
  paths:
    - E:\logs\utgående\*
  multiline:
        pattern: ^(ERROR |INFO |DEBUG |WARN )
        negate: true
        match: after
        max_lines: 500
        timeout: 5s
```

And check the configuration (or try to start):

```
➜  filebeat-7.16.0-darwin-x86_64 git:(master) ✗ ./filebeat test config
Exiting: error loading config file: yaml: invalid trailing UTF-8 octet
```

Removing the characters `å` it works. 

Thanks!
