### ISSUE TITLE
Multiple filesets using hints autodiscovery

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/beats#30132]
In [this PR](https://github.com/elastic/beats/pull/27526) was changed the default behavior and now all filesets will be disabled unless explicitly configured.

Cuurrent state:
From documentation it seems that it is possible to set only 1 fileset 
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html#_co_elastic_logsfileset:
```
You can either configure a single fileset like this:

co.elastic.logs/fileset: access
```

Desired state:
be able to provide multiple values of `fileset` configuration, example:
```
annotations:
        co.elastic.logs/enabled: "true"
        co.elastic.logs/module: elasticsearch
        co.elastic.logs/fileset: server,slowlog,audit
```

**Comment by tetianakravchenko** [comment]
Outcome of the discussion:
1. Other option for this issue:
change default behavior in case of using hints-based auto discovery and enable all filesets of the module

2. Try workaround and set multiple modules
https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html#_multiple_sets_of_hints
smth like: (not tested!)
```
annotations:
  co.elastic.logs/1.module: elasticsearch
  co.elastic.logs/1.fileset: server
  co.elastic.logs/2.module: elasticsearch
  co.elastic.logs/2.fileset: slowlog
...
```
