### ISSUE TITLE
Slow processing of SQS queue

### ISSUE THREAD

**Issue by dudumiquim** [elastic/beats#30140]
I'm observing a situation with AWS Module for Filebeat. I read the vpc flow log's messages from the SQS queue and then send them to Logstash. I tried to send the messages directly to ElasticSeach, but the problem persist.
The problem is the number of deleted messages is lower than received by SQS. The In-flight message is always 10, but deleted messages are ~2 in 5 minutes.
This behavior occurs with "Maximum aggregation interval" of vpc-flow-logs in 10 minutes or 1 minute.

I don't know if this behavior is expected or I can do this better.
I checked the EC2 resources of Filebeat, Logstash and ElasticSearch servers, and are low utilization.
I'm using the same architecture to read messages from CloudTrail and ELB, and are working better.

Some vpc-flow logs have ~130Mb unzipped (~10Mb zipped).
I got an error message running in debug mode, but I don't know what happened reading this.

Thanks!

---

For confirmed bugs, please report:
- Version: filebeat-7.16.3-1
- Operating System: Amazon Linux 2 (r5.xlarge)
- Steps to Reproduce: 
1. Configure the AWS account to populate the SQS with log messages
2. Configure the Filebeat to read these SQS queues
3. Check if the number of messages deleted is higher than sent messages

filebeat.yml
```
filebeat.inputs:
- type: aws-s3
  queue_url: url_of_queue
  expand_event_list_from_field: Records
  role_arn: arn_of_role
  enabled: true
  fields:
    tipo_log: "aws.cloudtrail"
  
- type: aws-s3
  queue_url: url_of_queue
  expand_event_list_from_field: Records
  role_arn: arn_of_role
  enabled: true
  fields:
    tipo_log: "aws.elb"

- type: aws-s3
  queue_url: url_of_queue
  expand_event_list_from_field: Records
  role_arn: arn_of_role
  enabled: true
  fields:
    tipo_log: "aws.vpcflow"


filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml

filebeat.spool_size: 65535
queue.mem:
  events: 65535
  flush.min_events: 5
  flush.timeout: 0

setup.template:
  name: "%{[fields.tipo_log]}"
  pattern: "%{[fields.tipo_log]}-*"
  settings:
  index.number_of_shards: 1

output.logstash:
  enabled: true
  hosts: ["logstash-url:5044"]
  ```

aws.yml
```
- module: aws
  cloudtrail:
    enabled: true
    var.queue_url: url_of_cloudtrail_sqs
  elb:
    enabled: true
    var.queue_url: url_of_elb_sqs
  vpcflow:
    enabled: true
    var.queue_url: url_of_vpcflow_sqs
  cloudwatch:
    enabled: false
  ec2:
    enabled: false
  s3access:
    enabled: false
```

VPC Flow Logs Queue

![image](https://user-images.githubusercontent.com/4665519/151984405-ef5e4fd4-01df-43ad-ba64-57c38002b4e8.png)
![image](https://user-images.githubusercontent.com/4665519/151984646-d49465c8-784e-4c77-81c6-a020fa5cb4b3.png)

CloudTrail Logs Queue

![image](https://user-images.githubusercontent.com/4665519/151984873-c4e334bd-82a7-4c55-9bf4-113a76e0aad5.png)
![image](https://user-images.githubusercontent.com/4665519/151984995-c20090bd-b5a7-42cd-82f3-8ea3949a275c.png)

SQS Message example
´´´
{"Records":[{"eventVersion":"2.1","eventSource":"aws:s3","awsRegion":"us-east-1","eventTime":"2022-02-01T00:39:04.086Z","eventName":"ObjectCreated:Put","userIdentity":{"principalId":"AWS:ID:prod.iad.dbs.datafeeds.aws.internal"},"requestParameters":{"sourceIPAddress":"IP"},"responseElements":{"x-amz-request-id":"F03KGD827H8P2CR7","x-amz-id-2":"UEn1qDsTwwM8M0ThHULtNZTkCYsjZZs7Uo9PWjs7YRYmJ7TPG9qXqIsHARqIEH0MMSryzxzu351bTtVY7X2fm8r1ACOiuhpt"},"s3":{"s3SchemaVersion":"1.0","configurationId":"vpcflowlogs","bucket":{"name":"bucket_name","ownerIdentity":{"principalId":"OWNER_ID"},"arn":"ARN_OF_BUCKET"},"object":{"key":"KEY_OF_OBJECT.log.gz","size":6485177,"eTag":"feba68f64684b30161be150b03be7bf3","sequencer":"0061F8812800150AD6"}}}]}
´´´

Error in the log
```
2022-02-01T11:23:50.421-0300	WARN	[input.aws-s3.sqs]	awss3/sqs.go:91	Failed processing SQS message.	{"id": "8002FFF13339378E", "queue_url": "SQS_QUEUE_URL", "error": "failed processing SQS message (it will return to queue after visibility timeout): failed processing S3 event for object key \"VPCFLOW-File-key-1\" in bucket \"BUCKET_NAME\" (object record 1 of 1 in SQS notification): failed reading s3 object (elasped_time_ns=2649846915837): error reading message: context canceled", "errorVerbose": "error reading message: context canceled
failed reading s3 object (elasped_time_ns=2649846915837)
github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*s3ObjectProcessor).ProcessS3Object
/go/src/github.com/elastic/beats/x-pack/filebeat/input/awss3/s3_objects.go:160
github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*sqsS3EventProcessor).processS3Events
/go/src/github.com/elastic/beats/x-pack/filebeat/input/awss3/sqs_s3_event.go:274
github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*sqsS3EventProcessor).ProcessSQS
/go/src/github.com/elastic/beats/x-pack/filebeat/input/awss3/sqs_s3_event.go:117
github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*sqsReader).Receive.func1
/go/src/github.com/elastic/beats/x-pack/filebeat/input/awss3/sqs.go:90
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1581
failed processing S3 event for object key \"VPCFLOW-File-key-2\" in bucket \"BUCKET_NAME\" (object record 1 of 1 in SQS notification)
github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*sqsS3EventProcessor).processS3Events
/go/src/github.com/elastic/beats/x-pack/filebeat/input/awss3/sqs_s3_event.go:275
github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*sqsS3EventProcessor).ProcessSQS
/go/src/github.com/elastic/beats/x-pack/filebeat/input/awss3/sqs_s3_event.go:117
github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*sqsReader).Receive.func1
/go/src/github.com/elastic/beats/x-pack/filebeat/input/awss3/sqs.go:90
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1581
failed processing SQS message (it will return to queue after visibility timeout)
github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*sqsS3EventProcessor).ProcessSQS
/go/src/github.com/elastic/beats/x-pack/filebeat/input/awss3/sqs_s3_event.go:161
github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*sqsReader).Receive.func1
/go/src/github.com/elastic/beats/x-pack/filebeat/input/awss3/sqs.go:90
runtime.goexit
/usr/local/go/src/runtime/asm_amd64.s:1581", "message_id": "7408db49-bc9b-4dc4-9ccb-32c467e23b49", "elapsed_time_ns": 2649847424352}
```

vpcflowlogs example ( I found these "unknown", but I don't know if this can crash the application)
```
version account-id interface-id srcaddr dstaddr srcport dstport protocol packets bytes start end action log-status
2 854447381801 eni-hash IPv4 IPv4 443 35432 6 62 3224 1643673156 1643673187 ACCEPT OK
2 854447381801 eni-hash IPv4 IPv4 443 33488 6 6 922 1643673245 1643673275 ACCEPT OK
...
2 unknown eni-hash - - - - - - - 1643673176 1643673245 - NODATA
2 unknown eni-hash - - - - - - - 1643672990 1643673003 - NODATA
2 unknown eni-hash - - - - - - - 1643673170 1643673183 - NODATA
2 854447381801 eni-hash - - - - - - - 1643673255 1643673286 - NODATA
2 854447381801 eni-hash IPv4 IPv4 44846 33821 6 1 40 1643673056 1643673108 REJECT OK
```
