### ISSUE TITLE
[Beats] Custom configmap for Kubernetes Orchestrator Name

### ISSUE THREAD

**Issue by mholttech** [elastic/beats#30229]
**Describe the enhancement:**
[#26056](https://github.com/elastic/beats/pull/26056) introduced 3 methods to set orchestrator.cluster.name & orchestrator.cluster.url

1) ``kube_config`` file
2) ``kubeadm-config`` configmap
3) GKE Metadata

I would like to see a separate configmap for deployments that aren't managed by kubeadm or GKE. While one can create a simple ``kubeadm-config`` configmap, this may cause other services that key off of the existence of this configmap to not work as expected.

**Describe a specific use case for the enhancement or feature:**
I have an EKS Cluster with Managed Node Groups and utilize Fleet containers in Kubernetes for monitoring. I was able to get the cluster name to populate by creating the ``kubeadm-config`` config map, however when I went to deploy Calico it saw this configmap and it was missing required information, causing Calico to not deploy successfully.

This is the configmap I deployed:
````yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeadm-config
  namespace: kube-system
data:
  ClusterConfiguration: |
    clusterName: cluster-1
    controlPlaneEndpoint: https://abcd1234.gr7.us-west-2.eks.amazonaws.com
````

**Comment by mholttech** [comment]
@bvader Can you please make sure this gets routed to the appropriate team? Thanks!

**Comment by tetianakravchenko** [comment]
Hi @mholttech!

Orchestrator fields are not supposed to be defined "manually" by custom configMap. The proper way here would be to use something similar to the GKE Metadata, but for EKS. I checked it quickly and seems there is nothing similar in EKS now - https://github.com/aws/containers-roadmap/issues/686.

Meanwhile I would suggest to use rather `add_fields` processor and add `orchestrator.cluster` fields explicitly, instead of using `kubeadm-config` to avoid unexpected effects:
```
processors:
  - add_fields:
      target: orchestrator.cluster
      fields:
        name: cluster-1
        url: https://abcd1234.gr7.us-west-2.eks.amazonaws.com
```
