### ISSUE TITLE
Filebeat Loadbalance wrong cert validation

### ISSUE THREAD

**Issue by sepich** [elastic/beats#30240]
We have filebeat v7.17.0 with such output:
```
output.logstash:
  enabled: true
  hosts:
    - es-logs-node1.domain.com:5045
    - es-logs-node2.domain.com:5045
    - es-logs-node3.domain.com:5045
  ssl.certificate_authorities: []
  loadbalance: true
```
Each of those hosts has letsencrypt cert publicly valid only for its single name (No SAN).
In such configuration we see these errors in filebeat logs:
```
2022-02-05T02:01:13.479Z	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(async(tcp://es-logs-node1.domain.com:5045)): x509: certificate is valid for es-logs-node1.domain.com, not es-logs-node2.domain.com
```
Which is correct because each node only has cert for its name, not all other names in the cluster.
If we switch to `loadbalance: false` - such errors are gone. But we want continue to use `loadbalance`, and this error is very confusing.

Also, checked that there is no such issue on v7.16.3
