### ISSUE TITLE
[Filebeat] aws-cloudwatch input log_group_name_prefix only starts one input 

### ISSUE THREAD

**Issue by ghettosamson** [elastic/beats#30255]
I'm running Filebeat 7.17.0 as a Fargate task in my AWS environment and I need it to fetch the logs for all my other Fargate tasks from Cloudwatch. All of the log groups have a prefix of /ecs/ but Filebeat only ever starts one input worker for one log group.

Details:
- Version: 7.17.0
- Operating System: Docker
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-cloudwatch-input-log-group-name-prefix-only-starts-one-input/289168
- Steps to Reproduce: 
```
filebeat.inputs:
  - type: aws-cloudwatch
    log_group_name_prefix: /ecs
    region_name: us-east-1
    scan_frequency: 1m
    access_key_id: ${AWS_ACCESS_KEY_ID}
    secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    start_position: beginning
```

Here is the log from Filebeat<br>
`[aws-cloudwatch] awscloudwatch/input.go:154 aws-cloudwatch input worker for log group: '/ecs/scoring-engine' has started`
All the other matching log groups are ignored.
