### ISSUE TITLE
[Heartbeat] Mixup of TLS certificates on multi-monitor configs

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#30290]
Per [this discuss thread](https://discuss.elastic.co/t/multiple-hosts-per-monitor-confuses-certificate-validation-since-7-17-0/296062/6) it appears there are some odd cases in which a monitor with multiple `url` values mixes up the TLS certs between them.

I've had trouble reproducing this, but according @belimawr , one theory is:

> it looks to be a very specific edge case that involves domains with a common suffix and using non-wildcard certificates.

I'm not 100% on that, since setting up the following monitor did not reproduce the issue. I suspect there's perhaps a race in our cert handling and it's more timing related than anything. Given that this seems to happen more on internal domains I wonder if it only affects endpoints that are super fast to respond vs. public websites. The following config works for me, for instance:

```yaml
heartbeat.monitors:
- type: http
  enabled: true
  id: my-monitor
  name: My Monitor
  urls: ["https://discuss.elastic.co", "https://www.elastic.co"]
  schedule: '@every 10s'
```

This apparently is new in 7.17.0, which is strange, because we haven't changed any of this code.

**Comment by andrewvc** [comment]
@belimawr it seems that this merge commit of yours may be the culprit here? I see that we changed some of the TLS name validation there: https://github.com/elastic/beats/commit/b4314adb38e94075d61d6e579051f16a895cd229 was that intentional?

**Comment by legoguy1000** [comment]
Looks like filebeat is seeing the issue too in #30240

**Comment by belimawr** [comment]
> @belimawr it seems that this merge commit of yours may be the culprit here? I see that we changed some of the TLS name validation there: [b4314ad](https://github.com/elastic/beats/commit/b4314adb38e94075d61d6e579051f16a895cd229) was that intentional?

Those changes were supposed to fix the IP validation that was not working. The field we were using does not pass down IP addresses, so we did it "manually" in the same way we do with the certificate pins.

**Comment by belimawr** [comment]
The conditions I managed to reproduce this issue are:
* two different hosts (hostname and IP address)
* shared hostname suffix (I'm not sure if that's relevant, I didn't test with different ones)
* single host certificates using SNA (certs cannot be shared between hosts)
* using two docker containers running nginx with TLS setup.

something like that (I edited my `/etc/hosts` so those hostnames point to docker containers):
```yaml
- type: http
  id: cicd
  name: CI/CD
  enabled: true
  urls:
    - https://bitbucket.corp.internal
    - https://jira.corp.internal
  check.response.status: [200]
  max_redirects: 3
  schedule: '@every 5s'
  ssl:
    certificate_authorities:
      - /home/tiago/devel/certGen/rootCA.crt
```

I did other tests with a mix of URLs sharing and without sharing any hostname suffix (all remote URLs) and they did not cause any issue.

I'll look more into this.
