### ISSUE TITLE
[Filebeat] Journald input doesn't work in container when host systemd is too recent

### ISSUE THREAD

**Issue by mickymiek** [elastic/beats#30398]
We couldn't make filebeat's journald input work (running in a container managed by k8s).
There was nothing significant in debug logs, the only weird thing was that when we ran `lsof` on the filebeat process, it wasn't opening journal files (mounted from host).
Docker image used:  `docker.elastic.co/beats/filebeat-oss:8.0.0-rc2`
Host systemd version: `249`

We managed to fix this issue by installing a more recent version of `systemd` library in the container (ubuntu jammy -> `249.9-0ubuntu2`).

**Comment by vinzent** [comment]
similiar/same issue here.

If running the official elastic filebeat 8.0.1 container on a Fedora Core 35 host, the journald input just reads nothing without a warning or error.

If  I install the filebeat  8.0.1 rpm inside a fedora 35 container and use this image, the journald input works.

Fedora Core 35 uses systemd 249.7

**Comment by der-eismann** [comment]
Same problem here, although using a Fedora container didn't help. It's a pity there isn't more output to debug, all I have is
```
"message":"Starting input (ID: 15297911848916620766)"
"message":"Loading and starting Inputs completed. Enabled inputs: 1"
"message":"Input journald starting"
```
Host is Flatcar Container Linux which is also using systemd 249. This is my Containerfile:
```dockerfile
FROM fedora:35

RUN dnf install -y https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.1.2-x86_64.rpm systemd-devel

COPY deployment/docker/resources/filebeat.yml /usr/share/filebeat/filebeat.yml

RUN chmod 600 /usr/share/filebeat/filebeat.yml

ENTRYPOINT [ "/usr/share/filebeat/bin/filebeat", "-e", "--path.home", "/usr/share/filebeat", "--path.data", "/usr/share/filebeat/data" ]
```

with the following config
```yaml
name: filebeat

filebeat.inputs:
- type: journald
  id: systemd
  seek: cursor

output.logstash:
  enabled: true
  hosts: ["${LOGSTASH_HOST}"]

logging.to_files: false
logging.level: debug

logging.metrics.enabled: false
```

**Comment by vinzent** [comment]
What we needed to mount to get Filebeat working in a Fedora 35 Container on a Fedora CoreOS 35 host:

```
  --read-only \
  --privileged \
  --user 0 \
  --mount type=bind,src=/var/log/journal,dst=/var/log/journal,readonly=true \
  --mount type=bind,src=/etc/machine-id,dst=/etc/machine-id,readonly=true \
  --mount type=bind,src=/run/systemd,dst=/run/systemd,readonly=true \
  --mount type=bind,src=/etc/hostname,dst=/etc/hostname,readonly=true \
  --mount type=volume,src=filebeat-data,dst=/var/lib/filebeat \
  --mount type=volume,src=filebeat-logs,dst=/var/log/filebeat \
  --mount type=bind,src=/etc/filebeat/filebeat.yml,dst=/etc/filebeat/filebeat.yml,readonly=true \
```

**Comment by zagr0** [comment]
thnx @vinzent! can confirm that this config in addition to defaults of the chart do the trick in kubernetes deployment:
```
extraVolumeMounts:
  - name: runsystemd
    mountPath: /run/systemd
    readOnly: true
  - name: machine-id
    mountPath: /etc/machine-id
    readOnly: true

extraVolumes:
  - name: runsystemd
    hostPath:
      path: /run/systemd
      type: ''
  - name: machine-id
    hostPath:
      path: /etc/machine-id
      type: ''
```
