### ISSUE TITLE
[K8s] cluster metadata not added on all metrics

### ISSUE THREAD

**Issue by emmanuelmathot** [elastic/beats#30425]
**Describe the enhancement:**

The cluster metadata such as `orchestrator.cluster.name` and `orchestrator.cluster.ip` are not added on all kubernetes metrics. From usage and code review, I can see they are added to 

- container
- node
- pod
- state_daemonset
- state_deployment
- state_job
- state_node
- state_pod
- state_replicaset
- state_service
- state_statefulset

but missing to the following metrics where they should be added

- proxy
- system
- volume
- apiserver
- state_daemonset
- state_persistentvolume
- state_persistentvolumeclaim
- state_storageclass
- event

**Describe a specific use case for the enhancement or feature:**

Being able to account the PVC usage for a given cluster.

**Comment by tetianakravchenko** [comment]
@emmanuelmathot could you give more details on your k8s setup? are you using managed kubernetes solutions?

**Comment by emmanuelmathot** [comment]
Yes, we have deployed managed kubernetes as described in https://www.elastic.co/guide/en/fleet/master/running-on-kubernetes-managed-by-fleet.html using fleet policies.
We also added a `kubeadm-config` config map to add the cluster metadata

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubeadm-config
  namespace: kube-system
data:
  ClusterConfiguration: |
    clusterName: {{ .Values.components.kubeadm_config.clusterName }}
    controlPlaneEndpoint: {{ .Values.components.kubeadm_config.controlPlaneEndpoint }}
```

We are using elastic cloud with Elasticsearch 7.15.1 and beats image same version
