### ISSUE TITLE
Multiple prospectors on the same file

### ISSUE THREAD

**Issue by joshuaspence** [elastic/beats#3046]
We are using Filebeat to parse a log file that contains two different types of logs: JSON encoded and PHP logs. We are migrating all of our application code to use the JSON encoded format, but until then we are using the following Filebeat configuration in an attempt to parse the same log file twice, once with a `json` document type and a second with a `php` document type. The Filebeat configuration looks like this:

```
---
filebeat:
  spool_size: 2048
  idle_timeout: '5s'
  prospectors:
    - input_type: 'log'
      paths:
        - '/mnt/logs/php.log'
      encoding: 'plain'
      include_lines:
        - '^{'
      document_type: 'json'
      scan_frequency: '10s'
      harvester_buffer_size: 16384
      max_bytes: 10485760
      tail_files: false
      backoff: '1s'
      max_backoff: '10s'
      backoff_factor: 2
    - input_type: 'log'
      paths:
        - '/mnt/logs/php.log'
      encoding: 'plain'
      exclude_lines:
        - '^{'
      document_type: 'php'
      scan_frequency: '10s'
      harvester_buffer_size: 16384
      max_bytes: 10485760
      multiline:
        pattern: '^(\[[0-9]{2}-(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)-[0-9]{4}|{)'
        negate: true
        match: 'after'
      tail_files: false
      backoff: '1s'
      max_backoff: '10s'
      backoff_factor: 2
output:
  console:
```

I am noticing that sometimes (it doesnt seem to happen consistently), the log formats get mixed up. For example, I saw a message in Kibana that looks like this:

```
PHP Warning: REDACTED
Stack trace:
#0 REDACTED
#1 REDACTED
#2 REDACTED
#3 REDACTED
#4 REDACTED
#5 REDACTED
#6 REDACTED
#7 REDACTED
#8 REDACTED
#9 REDACTED
#10 REDACTED
#11 REDACTED
#12 REDACTED
#13 {main}
{... JSON message ...}
```

Looking at the registry file, it looks like there is only a single entry for `source == "/mnt/logs/php.log"`, which made me wonder... is this supposed to work? It's possible that the problem lies in our multiline regex, but the fact that the registry contains only a single entry, despite there being multiple prospectors for this file.
