### ISSUE TITLE
[Filebeat] httpjson last_response url parameters not correct.

### ISSUE THREAD

**Issue by leehinman** [elastic/beats#30477]
In 7.17.0 the url parameters are stored with incorrect values.

## Steps to Reproduce

Small API server written in Flask

``` python
#!/usr/bin/env python3

from flask import Flask, json

companies = {"id": 1, "name": "Company One"}

api = Flask(__name__)

@api.route('/companies', methods=['GET'])
def get_companies():
  return json.dumps(companies)

if __name__ == '__main__':
    api.run() 
```

## httpjson config

``` yaml
- type: httpjson
  enabled: true
  config_version: "2"
  interval: 5s
  request.method: "GET"
  request.url: http://localhost:5000/companies
  request.transforms:
    - set:
        target: url.params.start
        value: "[[.cursor.last_execution_datetime]]"
        default: '[[formatDate ((now).Add (parseDuration "-5s"))]]'
    - set:
        target: url.params.end
        value: '[[formatDate ((parseDate .cursor.last_execution_datetime).Add (parseDuration "5s"))]]'
        default: '[[formatDate now]]'
  cursor:
    last_execution_datetime:
       value: '[[.last_response.url.params]]'
```

## Results

``` text
2022-02-18T11:14:07.637-0600    DEBUG   [input.httpjson-cursor] v2/cursor.go:56 cursor.last_execution_datetime stored with map[end:[0001-01-01T00:00:05Z] start:[map[end:[2022-02-18T17:14:02Z] start:[2022-02-18T17:13:57Z]]]] {"id": "9A6FE18BC59BB559", "input_source": "http://localhost:5000/companies", "input_url": "http://localhost:5000/companies"}
```

Notice url.params.end has a value that is not the correct date, and
url.params.start contains a map with "end" and "start" values in it
that are correct date times.
