### ISSUE TITLE
filebeat not close delete filehandler

### ISSUE THREAD

**Issue by ly123-liu** [elastic/beats#30472]
filebeat version: 7.10.1

filebeat config add close_inactive: 5m, but filebeat still not close inactive filehandler(deleted filehandler) ,  why ? is there any config can let filebeat automatically close inactive filehandler?

filebeat config:
- type: log
  enabled: true
  paths:
    - /logs/template.log
  fields:
    log_type: nginx-ingress-internal
    container: container
    podname: podname
    namespace: namespace
    podip: podip
    cluster: ${CLUSTER}
    log_topic: log-prod
  scan_frequency: 10s
  close_inactive: 5m
  tail_files: true

lsof partinfo:
filebeat 13609 root   10r      REG 253,16   100000143  2373656 /var/lib/docker/containers/eedd75a596fc0ea9cd6ffffadad274f0e9c599730ea1ca16796792dd27787dae/eedd75a596fc0ea9cd6ffffadad2
74f0e9c599730ea1ca16796792dd27787dae-json.log.9 (deleted)
filebeat 13609 root   18r      REG 253,16   100000154  2373603 /var/lib/docker/containers/eedd75a596fc0ea9cd6ffffadad274f0e9c599730ea1ca16796792dd27787dae/eedd75a596fc0ea9cd6ffffadad2
74f0e9c599730ea1ca16796792dd27787dae-json.log.9 (deleted)
filebeat 13609 root   19r      REG 253,16   100000012  2111138 /var/lib/docker/containers/307f1203cddd937251c66e1abed03dd8370a098dd80d7080ff16ada17b468aee/307f1203cddd937251c66e1abed0
3dd8370a098dd80d7080ff16ada17b468aee-json.log.9 (deleted)
filebeat 13609 root   22r      REG 253,16   100000064  2373676 /var/lib/docker/containers/eedd75a596fc0ea9cd6ffffadad274f0e9c599730ea1ca16796792dd27787dae/eedd75a596fc0ea9cd6ffffadad2
74f0e9c599730ea1ca16796792dd27787dae-json.log.9 (deleted)

# cat filebeat_delete_fd.txt | wc -l
972

**Comment by ly123-liu** [comment]
in our config , close_inactive is at the same indentation level as enabled, but we still found filebeat is holding file handler with deleted files, why this happening ? 

input-config.yml
- type: log
  enabled: true
  paths:
    - /logs/template.log
  fields:
    log_type: nginx-ingress-internal
    container: container
    podname: podname
    namespace: namespace
    podip: podip
    cluster: ${CLUSTER}
    log_topic: log-prod
  scan_frequency: 10s
  close_inactive: 5m
  tail_files: true
  tags: ["nginx-ingress-internal"]

**Comment by mva-verbit** [comment]
@belimawr can confirm this as well
we are running filebeat 6.8.22 with inputs as docker containers and it doesn't release file handlers for deleted files

```
filebeat.inputs:
- type: docker
  close_inactive: 5m
  close_removed: true
  clean_removed: true
  containers:
    ids: "*"
    path: /var/lib/docker/containers
    stream: all
  ignore_older: 36h
  json.message_key: log
  json.keys_under_root: false
  json.ignore_decoding_error: true
  scan_frequency: 60s
  document_type: 'docker-logs'
  processors:
  - add_docker_metadata: ~
```

an example from `ps` output

```
filebeat  27275            root    5r      REG              202,1 100000031  127955205 /var/lib/docker/containers/2839281c157
8e88f15249ba1cad623f48831e7b1972d7ecbb36b1dfc1a0fba69/2839281c1578e88f15249ba1cad623f48831e7b1972d7ecbb36b1dfc1a0fba69-json.l
og.2 (deleted)
```

```
lsof -n|grep filebeat|grep delete|wc -l
285
```

this behavior causes extra disk space on EC2 nodes to be used and not properly cleaned up, and eventually, used space is hitting 100% percent and causing `Out of disks space` errors, affecting other containers running at the same EC2 node

any ideas how to fix it? possible quick workaround can be periodic restart for `filebeat` container, but it seems hacky to me
