### ISSUE TITLE
[Heartbeat] Unresponsive synthetics monitors when providing synthetics_args in heartbeat.yml 

### ISSUE THREAD

**Issue by emilioalvap** [elastic/beats#30563]
**Heartbeat version:** `v7.17.0` -> `v8.2.0-SNAPSHOT`

**Elasticsearch version:** `v8.2.0-SNAPSHOT`

**OS version:** WSL2 on Windows 10.0.19043

**Original install method (e.g. download page, yum, from source, etc.):** Docker

**Describe the bug:** When `synthetics_args` config key is provided inside heartbeat yaml, synthetics command execution becomes unresponsive without producing any result or error message. 

**Steps to reproduce:**
1. Create a simple browser monitor config, specifying `synthetics_args` key inside heartbeat.yml config.
````yaml
heartbeat.monitors:
- type: browser
  id: my-monitor2
  name: My Monitor2
  schedule: "@every 1m"
  throttling: false
  source:
    inline:
      script: |-
        step("load page", async () => {
           await page.goto('https://elastic.co');
        });
  synthetics_args: ["--playwright-options", '{"userAgent": "Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X)"}']
````
2. Run a heartbeat container providing the configuration above:
````bash
docker run --rm --name beat --volume="/tmp/sdh/heartbeat.docker.yml:/usr/share/heartbeat/heartbeat.yml:ro" \
 docker.elastic.co/beats/heartbeat:8.0.0 --strict.perms=false -e -E cloud.id=<cloud id> -E cloud.auth=elastic:<password>
````
3. Notice that synthetics command is executed only once and never returns:
````
...
Running command: /usr/share/heartbeat/.node/node/bin/elastic-synthetics elastic-synthetics --playwright-options {\"userAgent\": \"Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_1 like Mac OS X)\"} --screenshots on --no-throttling --inline --rich-events
...
````

**Expected behavior:** Synthetics should be executed regularly and log the result of the execution to stdout. This is the case if `synthetics_args` is not provided.
````
...
Running command: /usr/share/heartbeat/.node/node/bin/elastic-synthetics elastic-synthetics --screenshots on --no-throttling --inline --rich-events
Command has completed(0): /usr/share/heartbeat/.node/node/bin/elastic-synthetics elastic-synthetics --screenshots on --no-throttling --inline --rich-events
...
````
