### ISSUE TITLE
Libbeat/Filebeat setup ignores user configurations (Missing in CI)

### ISSUE THREAD

**Issue by P1llus** [elastic/beats#30600]
When running `filebeat setup` only the configuration in a modules `manifest.yml` is used.

For example in `mysqlenterprise` it looks like this:

```
module_version: 1.0

var:
  - name: paths
    default:
      - /home/user/mysqlauditlogs/audit.*.log
  - name: tags
    default: [mysqlenterprise-audit]
  - name: input
    default: file

ingest_pipeline:
  - ingest/pipeline.yml
input: config/config.yml
```

The issue is when a default value is not added to `manifest.yml` but only added to a modules `config.yml` like this:
```
- module: mysqlenterprise
  audit:
    enabled: false

    # Sets the input type. Currently only supports file
    #var.input: file

    # Set paths for the log files when file input is used.
    # Should only be used together with file input
    #var.paths:
    #  - /home/user/mysqlauditlogs/audit.*.log
```

When running filebeat setup, when paths are not in manifest.yml, will simply log an error like this:

```
~/filebeat7-17/filebeat-7.17.0-linux-x86_64$ ./filebeat setup --pipelines --modules mysqlenterprise
Exiting: error getting config for fileset mysqlenterprise/audit: Error interpreting the template of the input: template: text:3:22: executing "text" at <.paths>: map has no entry for key "paths"
```

This is quite confusing behavior, and we should update the setup command to also consider using the actual configurations currently applied, or change the debug message somehow to show that a default value is missing.
