### ISSUE TITLE
[Processor][Condition][Network] - Processor Condition Network Support an `any` Check

### ISSUE THREAD

**Issue by BenB196** [elastic/beats#30646]
**Describe the enhancement:**

Currently beats processors have conditional support for validating IPs against different networks.
https://www.elastic.co/guide/en/beats/filebeat/current/defining-processors.html#condition-network

It would be nice to have an option of `any` which just matches any IP and confirms it as valid.

**Describe a specific use case for the enhancement or feature:**

Occasionally, you want to validate that a field value is an IP before doing an action via a processor, this today can be achieved via:

something like:

```yaml
when:
    network:
        url.domain: [loopback, unicast, multicast, interface_local_multicast, link_local_unicast, link_local_multicast, private, public, unspecified]
```

This is somewhat verbose, and it would be nice if you could do something like:

```yaml
when:
    network:
        url.domain: [any]
```

This would just be a small quality of life improvement.

**Comment by jsoriano** [comment]
@BenB196 what kind of processing are you doing only for IPs? Could this be done in an ingest pipeline? There you can use grok to parse IPs.

**Comment by BenB196** [comment]
Hi @jsoriano one of the use cases is copying fields to ECS fields for some beats modules.

Example 1:

Heartbeat TCP monitor, if you put in an IP as the host, by default Heartbeat will only populate `url.domain`, but if I want to expand the event to have even more ECS compliant, by adding something like `host.ip`, I need to validate that the value of `url.domain` is actually an IP before copying it to `host.ip`. To do this I have a processor like:

```yaml
- copy_fields:
  when:
    and:
      - not:
          has_fields:
            - 'resolve.ip'
      - network:
          url.domain: [loopback, unicast, multicast, interface_local_multicast, link_local_unicast, link_local_multicast, private, public, unspecified]
  fields:
    - from: url.domain
      to: host.ip
  fail_on_error: false
  ignore_missing: true
```

Example 2:

Similar to the above, if I want to populate `host.hostname` from the TCP monitor, I need to make sure that the `url.domain` is not an IP.

```yaml
- copy_fields:
  when:
    not:
      - network:
          url.domain: [loopback, unicast, multicast, interface_local_multicast, link_local_unicast, link_local_multicast, private, public, unspecified]
  fields:
    - from: url.domain
      to: host.hostname
  fail_on_error: false
  ignore_missing: true
```

---

While I guess technically these could be done in an Ingest Pipeline, I think this overly complicates what should be a fairly simple process.
