### ISSUE TITLE
Filebeat httpjson pagination creates duplicates when only a single page

### ISSUE THREAD

**Issue by wasserman** [elastic/beats#30693]
I've noticed that with Filebeat 7.16.2 using httpjson pagination that when a next link is not present it still attempts to go to a page 2.  This is causing duplicate events with my configuration.  I traced the code a little and found that the first call to the pagination always returns a `true` that gets passed back into `hasNext`.  This could be the problem.

https://github.com/elastic/beats/blob/237937085a5a7337ba06f1268cfc55cd4b869e31/x-pack/filebeat/input/httpjson/pagination.go#L122

I'm using the Microsoft Graph API, which is why I'm using `@odata.nextLink`.

My config gist is as follows:

```
  request.method: GET


  response.split:
    target: body.value

  response.pagination:
    - set:
        target: url.value
        value: '[[ index .last_response.body "@odata.nextLink"]]'

  request.transforms:
    - set:
        target: url.params.filter
        value: 'receivedDateTime ge [[.cursor.filterTime]]'
        default: 'receivedDateTime gt 2022-02-28T21:11Z'
    - delete:
        target: body.content
  processors:
    ...
  cursor:
    filterTime:
      value: '[[ formatDate ((parseDate .last_event.receivedDateTime).Add (parseDuration "1s")) ]]'
```

**Comment by legoguy1000** [comment]
Have u run in debug mode? If the link is empty is should just fail and end the requests. Are u saying it ends up requesting the same data as the original request?

**Comment by marc-gr** [comment]
To prevent this behavior, you need to introduce the `fail_on_template_error` option in you pagination transform to make it stop instead of defaulting to empty:

```
...
  response.pagination:
    - set:
        target: url.value
        value: '[[ index .last_response.body "@odata.nextLink"]]'
        fail_on_template_error: true
...
```

This will make the pagination stop if nextLink is not found.
