### ISSUE TITLE
CloudTrail module is not fetching other region logs from S3

### ISSUE THREAD

**Issue by 0ccupi3R** [elastic/beats#30701]
Hi Team,

The cloudtrail S3 bucket contains objects across all regions but what I have noticed that it's only fetching the logs from single region for which the bucket was configured. 
For instance : 
The bucket "arn:aws:s3:::cloudtrail.logs" configured for ap-south-1 region.

And here are the  logs from other region (including ap-south-1)

- AWSLogs/12345678/CloudTrail/ap-south-1
- AWSLogs/12345678/CloudTrail/us-east-1
- AWSLogs/12345678/CloudTrail/us-west-1

But in Elasticsearch, I can only see logs for ap-south-1 region.

**Comment by kaiyan-sheng** [comment]
Hi @0ccupi3R , thanks for creating this issue. What does your aws.yml configuration file look like?

**Comment by 0ccupi3R** [comment]
Thanks @kaiyan-sheng for your help .

The configuration looks like below : 

```
- module: aws
  cloudtrail:
    enabled: true
    var.bucket_arn: 'arn:aws:s3:::cloudtrail-events'
    var.bucket_list_prefix: 'AWSLogs/12345678/CloudTrail/'
    var.number_of_workers: 5
```

My bad, don't know why didn't I see them earlier. I have verified the logs with filter (say `aws.s3.object.key: *east*` ) and able to see the events from all the regions.
