### ISSUE TITLE
Metricbeat to monitor kibana is not working fine with more than a pod replica

### ISSUE THREAD

**Issue by gerardgorrion** [elastic/beats#30764]
We are triying to deploy metricbeat to monitor kibana in eck with stack monitoring. The problem is, the monitoring to kibana's module is not working fine. The elasticsearch module is working well.

[Stack monitoring](https://github.com/elastic/cloud-on-k8s/blob/2.0/config/recipes/beats/stack_monitoring.yaml) (metricbeat deployed).

Metricbeat config modules (pointing to elasticsearch and kibana services into kubernetes):
```
            templates:
              - condition:
                  contains:
                    kubernetes.labels.app: elasticsearch
                config:
                  - module: elasticsearch
                    metricsets:
                      - ccr
                      - cluster_stats
                      - enrich
                      - index
                      - index_recovery
                      - index_summary
                      - ml_job
                      - node_stats
                      - shard
                    period: 10s
                    hosts: "https://${data.host}:${data.ports.https}"
                    username: ${MONITORED_ES_USERNAME}
                    password: ${MONITORED_ES_PASSWORD}
                    ssl.verification_mode: "none"
                    xpack.enabled: true
              - condition:
                  contains:
                    kubernetes.labels.app: elasticsearch
                config:
                  - module: kibana
                    metricsets:
                      - stats
                    period: 10s
                    hosts: "https://kibana-kb-http:5601"
                    username: ${KIBANA_ES_USERNAME}
                    password: ${KIBANA_ES_PASSWORD}
                    ssl.verification_mode: "certificate"
                    ssl.certificate_authorities:
                      - /usr/share/metricbeat/cert/tls.crt
                    xpack.enabled: true
```

Kibana overview shows ok:

![image](https://user-images.githubusercontent.com/35425181/157640010-efa1a520-eb14-4160-8147-2c16c3f669fb.png)

Kibana stack monitoring (says that all are monitored but is not working fine).

![image](https://user-images.githubusercontent.com/35425181/157639021-7d774d88-0652-4d53-985c-7855be8a2abc.png)

Last 15 min of a single kibana node (continous monitoring is no working):

![image](https://user-images.githubusercontent.com/35425181/157639103-7caa18b8-93a0-4250-8d02-03243a575453.png)

Example of self monitoring kibana node running ok:

![image](https://user-images.githubusercontent.com/35425181/157639150-7c069af0-392e-40f6-80fc-63d866661364.png)

Test to verify when fails the monitoring (more than a single replica)

Monitoring start: 08:30 with 2 kibana pod replicas.
At 08:31 put 1 replicas of kibana
At 08:38 put 3 replicas of kibana

![image](https://user-images.githubusercontent.com/35425181/157639212-84979846-feee-45f6-a6a2-58cd96587742.png)

Seem like is no possible to get metrics of a sinlge pod qhen there're more than 1.

For confirmed bugs, please report:
- Version: metricbeat 7.16.2 / eck operator 1.9 / kibana 7.16.2
- Operating System: Linux
- Discuss Forum URL: [https://discuss.elastic.co/t/metricbeat-kibana-no-stable/299091](https://discuss.elastic.co/t/metricbeat-kibana-no-stable/299091)
- Steps to Reproduce:  Install eck 1.9 into kubernetes, elasticsearch and kibana 7.16.2 and [metricbeat](https://github.com/elastic/cloud-on-k8s/blob/2.0/config/recipes/beats/stack_monitoring.yaml) 7.16.2 to monitor elasticsearch and kibana. Elasticsearch work fine, but kibana seem like report is not estable.

Some idea to resolve it?

Thanks!
