### ISSUE TITLE
[Metricbeat] Azure module fails to filter for resource_group

### ISSUE THREAD

**Issue by immavalls** [elastic/beats#30782]
- Metricbeat Version: 7.12.1

As discussed with @kaiyan-sheng I'm reporting a failure to filter Azure resources (Azure public subscription) by [resource group](https://www.elastic.co/guide/en/beats/metricbeat/7.12/metricbeat-metricset-azure-compute_vm.html#_config_options_to_identify_resources_3). It seems it's only reproduced when filtering a subscription with hundreds of resource groups, no VMs are returned. Filtering by resource id does.

A configuration similar to:

```yaml
- module: azure
  metricsets:
    - compute_vm
  enabled: true
  period: 300s
  client_id: 'aaa'
  client_secret: 'bbb'
  tenant_id: 'ccc'
  subscription_id: 'ddd'
  refresh_list_interval: 600s
  resources:
    - resource_group: ["RK-GROUP-001"]
```

Will show an ERROR in the logs:

```
2022-03-01T18:05:53.411+0100	ERROR	[azure monitor client]	azure/client.go:71	failed to retrieve resources: No resources returned using the configuration options resource ID [], resource group [RK-GROUP-001], resource type Microsoft.Compute/virtualMachines, resource query 
```

While the request `az resource list --resource-group "RK-GROUP-001" --resource-type "Microsoft.Compute/virtualMachines"` returns 8 VMs. 

The suspicion so far is that the Azure subscription has around 800 virtual machines and contains over 700 resource groups. The filter should return less than 10 VMs in this case, thus it might not be reproducible just adjusting some pagination parameters, but we might need a big subscription to reproduce.
