### ISSUE TITLE
Filebeat encoding problem working on SQL Server

### ISSUE THREAD

**Issue by wizali** [elastic/beats#3079]
the config file is:
```
filebeat.prospectors:
- input_type: log
  paths:
    - D:\SQL_Server\Microsoft SQL Server\MSSQL10.MSSQLSERVER\MSSQL\Log\ERRORLOG
  encoding: gbk
  fields:
    host_ip: "192.168.6.245"
    type: "sql_server_log"
    encoding: "gbk"
  fields_under_root: true
output.logstash:
  # The Logstash hosts
  hosts: ["192.168.6.244:5044"]
```
the encoding of my SQL Server is "gbk"output is:
```
{
       "message" => "\u00002\u00000\u00001\u00006\u0000-\u00001\u00001\u0000-\u00003\u00000\u0000 \u00001\u00007\u0000:\u00000\u00001\u0000:\u00001\u00004\u0000.\u00008\u00003\u0000 \u0000{vU_ \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000 \u0000L\u0000o\u0000g\u0000i\u0000n\u0000 \u0000f\u0000a\u0000i\u0000l\u0000e\u0000d\u0000 \u0000f\u0000o\u0000r\u0000 \u0000u\u0000s\u0000e\u0000r\u0000 \u0000'\u0000s\u0000a\u0000'\u0000.\u0000 \u0000�S�V:\u0000 \u0000�[\u0001x\u000EN@b�c�O�v{vU_\rT\rN9SM�\u00020 \u0000[\u0000�[7b�z:\u0000 \u0000<\u0000l\u0000o\u0000c\u0000a\u0000l\u0000 \u0000m\u0000a\u0000c\u0000h\u0000i\u0000n\u0000e\u0000>\u0000]\u0000\r\u0000",
      "@version" => "1",
    "@timestamp" => "2016-11-30T09:01:19.069Z",
      "encoding" => "gbk",
       "host_ip" => "192.168.6.245",
        "source" => "D:\\SQL_Server\\Microsoft SQL Server\\MSSQL10.MSSQLSERVER\\MSSQL\\Log\\ERRORLOG",
    "input_type" => "log",
        "offset" => 31047,
          "type" => "sql_server_log",
          "beat" => {
            "name" => "WIN-NRAA6OPBI9T",
        "hostname" => "WIN-NRAA6OPBI9T",
         "version" => "5.0.0"
    },
          "host" => "WIN-NRAA6OPBI9T",
          "tags" => [
        [0] "beats_input_codec_plain_applied"
    ]
}
```
is there any way to turn "message" into GBK encoding ?
