### ISSUE TITLE
[metricbeat] windows perfmon missing samples for HyperV counters when in single module file

### ISSUE THREAD

**Issue by marc-gr** [elastic/beats#30794]
- Version: 7.15.0

Samples are lost for HyperV counters when they are configured as part of the same config module file:

```yaml
- module: windows
  enabled: true
  metricsets:
  - perfmon
  processors:
  - drop_event:
      when:
        or:
        - contains:
            error.message: 'failed reading counters: failed querying counter values: No data to return.'
        - contains:
            error.message: no counters to read
  period: 10s
  perfmon.ignore_non_existent_counters: true
  perfmon.group_measurements_by_instance: true
  perfmon.counters:
  - instance_label: Hyper-V Hypervisor Logical Processor
    measurement_label: '% Guest Run Time'
    query: '\Hyper-V Hypervisor Logical Processor(_Total)\% Guest Run Time'
  - instance_label: Hyper-V Hypervisor Logical Processor
    measurement_label: '% Hypervisor Run Time'
    query: '\Hyper-V Hypervisor Logical Processor(_Total)\% Hypervisor Run Time'
  - instance_label: Hyper-V Hypervisor Logical Processor
    measurement_label: '% Total Run Time'
    query: '\Hyper-V Hypervisor Logical Processor(_Total)\% Total Run Time'
  - instance_label: Hyper-V Hypervisor Virtual Processor
    measurement_label: '% Guest Run Time'
    query: '\Hyper-V Hypervisor Virtual Processor(_Total)\% Guest Run Time'
  - instance_label: Hyper-V Hypervisor Virtual Processor
    measurement_label: '% Hypervisor Run Time'
    query: '\Hyper-V Hypervisor Virtual Processor(_Total)\% Hypervisor Run Time'
  - instance_label: Hyper-V Hypervisor Virtual Processor
    measurement_label: '% Total Run Time'
    query: '\Hyper-V Hypervisor Virtual Processor(_Total)\% Total Run Time'
  - instance_label: Hyper-V Hypervisor Virtual Processor
    measurement_label: CPU Wait Time Per Dispatch
    query: '\Hyper-V Hypervisor Virtual Processor(_Total)\CPU Wait Time Per Dispatch'
  - instance_label: Hyper-V Hypervisor Root Virtual Processor
    measurement_label: '% Guest Run Time'
    query: '\Hyper-V Hypervisor Root Virtual Processor(_Total)\% Guest Run Time'
  - instance_label: Hyper-V Hypervisor Root Virtual Processor
    measurement_label: '% Hypervisor Run Time'
    query: '\Hyper-V Hypervisor Root Virtual Processor(_Total)\% Hypervisor Run Time'
  - instance_label: Hyper-V Hypervisor Root Virtual Processor
    measurement_label: '% Total Run Time'
    query: '\Hyper-V Hypervisor Root Virtual Processor(_Total)\% Total Run Time'
  - instance_label: Hyper-V Hypervisor Root Virtual Processor
    measurement_label: CPU Wait Time Per Dispatch
    query: '\Hyper-V Hypervisor Root Virtual Processor(_Total)\CPU Wait Time Per Dispatch'
```

This leads to missing counters:

<img width="406" alt="image" src="https://user-images.githubusercontent.com/15213755/158154919-1ae39b09-8ba3-4553-b6dd-8745059a7010.png">

If we split the config in 3 files
```yaml
- module: windows
  enabled: true
  metricsets:
  - perfmon
  processors:
  - drop_event:
      when:
        or:
        - contains:
            error.message: 'failed reading counters: failed querying counter values: No data to return.'
        - contains:
            error.message: no counters to read
  period: 10s
  perfmon.ignore_non_existent_counters: true
  perfmon.group_measurements_by_instance: true
  perfmon.counters:
  - instance_label: Hyper-V Hypervisor Logical Processor
    measurement_label: '% Guest Run Time'
    query: '\Hyper-V Hypervisor Logical Processor(_Total)\% Guest Run Time'
  - instance_label: Hyper-V Hypervisor Logical Processor
    measurement_label: '% Hypervisor Run Time'
    query: '\Hyper-V Hypervisor Logical Processor(_Total)\% Hypervisor Run Time'
  - instance_label: Hyper-V Hypervisor Logical Processor
    measurement_label: '% Total Run Time'
    query: '\Hyper-V Hypervisor Logical Processor(_Total)\% Total Run Time'
```
```yaml
- module: windows
  enabled: true
  metricsets:
  - perfmon
  processors:
  - drop_event:
      when:
        or:
        - contains:
            error.message: 'failed reading counters: failed querying counter values: No data to return.'
        - contains:
            error.message: no counters to read
  period: 10s
  perfmon.ignore_non_existent_counters: true
  perfmon.group_measurements_by_instance: true
  perfmon.counters:
  - instance_label: Hyper-V Hypervisor Virtual Processor
    measurement_label: '% Guest Run Time'
    query: '\Hyper-V Hypervisor Virtual Processor(_Total)\% Guest Run Time'
  - instance_label: Hyper-V Hypervisor Virtual Processor
    measurement_label: '% Hypervisor Run Time'
    query: '\Hyper-V Hypervisor Virtual Processor(_Total)\% Hypervisor Run Time'
  - instance_label: Hyper-V Hypervisor Virtual Processor
    measurement_label: '% Total Run Time'
    query: '\Hyper-V Hypervisor Virtual Processor(_Total)\% Total Run Time'
  - instance_label: Hyper-V Hypervisor Virtual Processor
    measurement_label: CPU Wait Time Per Dispatch
    query: '\Hyper-V Hypervisor Virtual Processor(_Total)\CPU Wait Time Per Dispatch'
```
```yaml
- module: windows
  enabled: true
  metricsets:
  - perfmon
  processors:
  - drop_event:
      when:
        or:
        - contains:
            error.message: 'failed reading counters: failed querying counter values: No data to return.'
        - contains:
            error.message: no counters to read
  period: 10s
  perfmon.ignore_non_existent_counters: true
  perfmon.group_measurements_by_instance: true
  perfmon.counters:
  - instance_label: Hyper-V Hypervisor Root Virtual Processor
    measurement_label: '% Guest Run Time'
    query: '\Hyper-V Hypervisor Root Virtual Processor(_Total)\% Guest Run Time'
  - instance_label: Hyper-V Hypervisor Root Virtual Processor
    measurement_label: '% Hypervisor Run Time'
    query: '\Hyper-V Hypervisor Root Virtual Processor(_Total)\% Hypervisor Run Time'
  - instance_label: Hyper-V Hypervisor Root Virtual Processor
    measurement_label: '% Total Run Time'
    query: '\Hyper-V Hypervisor Root Virtual Processor(_Total)\% Total Run Time'
  - instance_label: Hyper-V Hypervisor Root Virtual Processor
    measurement_label: CPU Wait Time Per Dispatch
    query: '\Hyper-V Hypervisor Root Virtual Processor(_Total)\CPU Wait Time Per Dispatch'
```

Then the performance is as expected when running the same metricbeat instance.
