### ISSUE TITLE
[Beats output.kafka] Support Kafka 2.8.1 in beats `output.kafka.version` field

### ISSUE THREAD

**Issue by brsolomon-deloitte** [elastic/beats#30937]
It looks like `output.kafka.version` [only formally supports up to 2.8.0](https://www.elastic.co/guide/en/beats/filebeat/8.1/kafka-output.html#kafka-compatibility) whereas 2.8.1 is the latest patch release of Kafka 2.8.x. This might be more of annoyance than anything else, since specifying 2.8.1 will raise a validation error even though there is likely no behavior difference in the .0 -> .1 patch change. Perhaps an easy change on the beats side?

**Comment by jlind23** [comment]
@rdner thoughts on this?

**Comment by rdner** [comment]
@jlind23 I agree, there is no obvious reason to have this limitation.

I ran filebeat with Kafka 3.1.0 as an output in https://github.com/elastic/beats/pull/30369 and it worked just fine, @brsolomon-deloitte do you have an error connecting to Kafka 2.8.1? 

I think it's just the documentation mistake, perhaps we wanted to be on the safe side for future compatibility (last change was made ~7 months ago in https://github.com/elastic/beats/pull/27720) and it's now outdated.

**Comment by brsolomon-deloitte** [comment]
>  @brsolomon-deloitte do you have an error connecting to Kafka 2.8.1?

Yes. With Filebeat 7.17.0 ->

First, test working config using 2.8.0:

```console
$ filebeat test config -c /etc/filebeat/filebeat.yml
Config OK
$ grep -F '2.8.0' /etc/filebeat/filebeat.yml
  version: 2.8.0
```

Now for 2.8.1:

```console
$ cp /etc/filebeat/filebeat.yml /etc/filebeat/filebeat-2.8.1.yml
$ sed -i 's/2.8.0/2.8.1/g' /etc/filebeat/filebeat-2.8.1.yml
$ filebeat test config -c /etc/filebeat/filebeat-2.8.1.yml
Exiting: error initializing publisher: unknown/unsupported kafka version '2.8.1' accessing 'output.kafka.version' (source:'/etc/filebeat/filebeat-2.8.1.yml')
```

Full Kafka config from working file:

```yaml
output.kafka:
  hosts: ["redacted", "redacted", "redacted"]
  version: 2.8.0
  topic: 'redacted'
  key: '%{[@metadata._id]}'
  partition.round_robin:
    reachable_only: false
  codec.json:
    pretty: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
```
