### ISSUE TITLE
[Docs] Add information about connecting to an auto-configured secured Elasticsearch instance

### ISSUE THREAD

**Issue by jkakavas** [elastic/beats#31015]
Since 8.0, Elasticsearch [security features are enabled and configured by default](https://www.elastic.co/guide/en/elasticsearch/reference/current/configuring-stack-security.html).

We should update docs like https://www.elastic.co/guide/en/beats/metricbeat/current/securing-communication-elasticsearch.html to add an example or a hint that either `ssl.certificate_authorities` need to be configured to point to `$ES_HOME/config/certs/http_ca.crt` or that  `ssl.ca_trusted_fingerprint:` needs to be added with a value that matches the value that is printed on Elasticsearch's node first run.

**Comment by 5yanfei** [comment]
@jkakavas  Hello,

I'm using docker-compose to deploy metricbeat 8.1, but it didn't work.

How did you deploy it? Can you provide a reference to the relevant configuration file?

Below is my config file, I don't know where is the problem:

`docker-compose.yml `
```
version: "2"
services:
  metricbeat:
    container_name: metricbeat
    image: docker.elastic.co/beats/metricbeat:8.1.0
    user: root
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /run/docker.sock:/var/run/docker.sock
      - ./ca.crt:/usr/share/metricbeat/data/ca.crt
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
```

`metricbeat.yml`

```
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["https://192.168.xxx.xxx:9200"]
  username: "remote_monitoring_user"
  password: "xxxxxxxxxxx"
  ssl.certificate_authorities: /usr/share/metricbeat/data/ca.crt
```
