### ISSUE TITLE
How to deploy metricbeat 8.1 with docker-compose.

### ISSUE THREAD

**Issue by 5yanfei** [elastic/beats#31037]
Hello,

I'm using docker-compose to deploy metricbeat 8.1, but it didn't work.

The official deployment method of docker-compose is not provided. Can you provide a reference for related configuration files?

Below is my config file, I don't know where is the problem:

`docker-compose.yml`
```
version: "2"
services:
  metricbeat:
    container_name: metricbeat
    image: docker.elastic.co/beats/metricbeat:8.1.0
    user: root
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /run/docker.sock:/var/run/docker.sock
      - ./ca.crt:/usr/share/metricbeat/data/ca.crt
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
```
`metricbeat.yml`
```
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

processors:
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["https://192.168.xxx.xxx:9200"]
  username: "remote_monitoring_user"
  password: "xxxxxxxxxxx"
  ssl.certificate_authorities: /usr/share/metricbeat/data/ca.crt
```
