### ISSUE TITLE
Filebeat Timestamp Processor  UNIX_MS TImezone Not work

### ISSUE THREAD

**Issue by vaxilicaihouxian** [elastic/beats#31116]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 7.4.0 - 7.8.0+
- Operating System: centos 6
- Discuss Forum URL:
- Steps to Reproduce: 

filebeat.yml
```
processors:
  - add_locale:
      format: abbreviation
  - timestamp:
      field: json.optime
      timezone: "Australia/Melbourne"
      ignore_failure: false
      layouts:
        - 'UNIX_MS'
```

Timezone not work.
![image](https://user-images.githubusercontent.com/8603593/161397865-8d34ce51-2c49-4a90-9e2e-831a899f505f.png)

It just return a new time object.
Is it a bug?
