### ISSUE TITLE
We are not seeing metrics for cpu, memory and network

### ISSUE THREAD

**Issue by SonalJain1707** [elastic/beats#31124]
Hi,

We are trying to collect metrics from cloud converge but we are not able to see metrics for cpu , memory and network

 
**kubernetes.node.network.rx.bytes | 0 |  
-- | -- | --
kubernetes.node.network.rx.errors | 0 |  
kubernetes.node.network.tx.bytes | 0 |  
kubernetes.node.network.tx.errors | 0 |**  
kubernetes.node.runtime.imagefs.available.bytes | 21,541,470,208 |  
kubernetes.node.runtime.imagefs.capacity.bytes | 64,100,753,408 |  
kubernetes.node.runtime.imagefs.used.bytes | 65,713,395,269

kubernetes.node.fs.used.bytes | 39,830,368,256 |  
-- | -- | --
kubernetes.node.memory.available.bytes | 67,426,185,216 |  
kubernetes.node.memory.majorpagefaults | 0 |  
kubernetes.node.memory.pagefaults | 0 |  
kubernetes.node.memory.rss.bytes | 0 |  
kubernetes.node.memory.usage.bytes | 0 |  
kubernetes.node.memory.workingset.bytes | 0

**Comment by SonalJain1707** [comment]
Team:SAP

**Comment by sebglon** [comment]
Hi, we have the same issue on metricbeat 8.4.2.
Here are me clusterRoles:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat
  labels:
    k8s-app: metricbeat
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - namespaces
      - events
      - pods
      - services
    verbs: ["get", "list", "watch"]
  # Enable this rule only if planing to use Kubernetes keystore
  #- apiGroups: [""]
  #  resources:
  #  - secrets
  #  verbs: ["get"]
  - apiGroups: ["extensions"]
    resources:
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apps"]
    resources:
      - statefulsets
      - deployments
      - replicasets
    verbs: ["get", "list", "watch"]
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - ""
    resources:
      - nodes/stats
    verbs:
      - get
  - nonResourceURLs:
      - "/metrics"
    verbs:
      - get
```
