### ISSUE TITLE
[filebeat] add_kubernetes_metadata processor stopped working since v7.16 (under a specific condition)

### ISSUE THREAD

**Issue by gpothier** [elastic/beats#31171]
The kubernetes metadata fields are not added anymore since v7.16 if a field named `kubernetes.cluster.name` (or any field that starts with `kubernetes`, I suppose) is statically added to all events with `fields` and `fields_under_root` in the config. It is presumably caused by this PR: https://github.com/elastic/beats/pull/27689.

I understand the rationale of the PR, but I think there is room for improvement:

- First and foremost, nothing appears in the log, which makes the issue really difficult to troubleshoot. It would be great if a warning was logged once, the first time the processor decides to skip adding the metadata (as far as I understand, if logging level is set to `debug`, the skipping would be logged for each event, but one warning in the normal logging level would be nice).

- Second, in this particular case, the add_kubernetes_metadata took the decision not to add the metadata even though it wouldn't output the `kubernetes.cluster.name` field anyway (which is why I add it statically in the first place). Maybe the decision to add the metadata fields should be taken field by field, and not for the whole document, ie. fields that are already present in the document are not overwritten, but fields that are not present are added. Maybe this could be configurable, eg. with an option like `overwrite_existing_metadata: 'always' |  'never' | 'merge'`, default being `never` (current behaviour).

Here is the filebeat.yml config, just in case:
```
      filebeat.inputs:
      - type: container
        paths:
          - /var/log/containers/*.log
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"

      output.elasticsearch:
        protocol: https

      fields_under_root: true
      fields:
        kubernetes.cluster.name: "${KUBERNETES_CLUSTER_NAME}"
        cloud.provider: "o3"
        cloud.availability_zone: "o3"

      processors:
        - add_host_metadata:

      cloud.id: "${ELASTIC_CLOUD_ID}"
      cloud.auth: "${ELASTIC_CLOUD_AUTH}"
```

**Comment by ryan-dyer-sp** [comment]
For those that also stumble across this issue.  Workaround:  remove the kubernetes.* fields from the field object and add an add_fields to your processors.
`      - add_fields:
          # We use the add_fields processor instead of the fields object as add_kubernetes_metadata does not work if it finds any existing kubernetes.* fields on the event.
          # https://github.com/elastic/beats/issues/31171
          target: kubernetes
          fields:
            cluster: <cluster> `
IDK if you can put sub fields(cluster.name) this way or not

**Comment by m-standfuss** [comment]
We just spent hours looking for logs to troubleshoot an issue only to realized that our search parameters were including a k8s field that was no longer being populated after our upgrade to 8.8. This is a bad one for us. 

100% agree with @ryan-dyer-sp 's sentiment 

>>>This is a breaking change which should have been mentioned as such in the release notes. Not just as a bug fix. What bug is this fixing? Its not mentioned in the PR. This behavior does not appear to be documented anywhere on this page: [elastic.co/guide/en/beats/filebeat/current/add-kubernetes-metadata.html](https://www.elastic.co/guide/en/beats/filebeat/current/add-kubernetes-metadata.html)

**Comment by alekc** [comment]
Just got hit by this. For me what's triggering it is the presence of 
```
    filebeat.autodiscover:
        providers:
          - type: kubernetes
            node: $${NODE_NAME}
            hints:
              enabled: true
              default_config:
                type: container
                paths:
                  - /var/log/containers/*$${data.kubernetes.container.id}.log
```
block. With it commented out it works as expected. (the code is from terraform templatefile, so don't mind double $$ and ${})
```
...
  config:
    output.elasticsearch.enabled: false
    output.logstash:
      hosts: ["${stack_name}-ls-beats:5044"]
#    filebeat.autodiscover:
#        providers:
#          - type: kubernetes
#            node: $${NODE_NAME}
#            hints:
#              enabled: true
#              default_config:
#                type: container
#                paths:
#                  - /var/log/containers/*$${data.kubernetes.container.id}.log
    filebeat.inputs:
      - id: containers
        type: container
        paths:
          - /var/log/containers/*.log
        exclude_lines: []
    processors:
      - add_kubernetes_metadata:
          labels.dedot: true
          annotations.dedot: true
          in_cluster: true
          host: $${NODE_NAME}
...
```
