### ISSUE TITLE
Filebeat Azure module base64 error 

### ISSUE THREAD

**Issue by alijahnas** [elastic/beats#31179]
I am using filebeat to get logs from Azure Event Hub using this module https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-azure.html
and following this tutorial: https://www.elastic.co/blog/monitoring-azure-infrastructure-with-filebeat-and-elastic-observability

Whatever the connection string, I always get the following error:
```
{"log.level":"error","@timestamp":"2022-04-05T15:29:13.352Z","log.logger":"azure-eventhub` input","log.origin":
{"file.name":"azureeventhub/input.go","file.line":113},"message":"illegal base64 data at input byte 24",
"service.name":"filebeat","connection `string":"Endpoint=sb://eventhubdmznonprd.servicebus.windows.net/","ecs.version":"1.6.0"}
```

Configuration:
```
- module: azure
  platformlogs:
    enabled: true
    var:
      # eventhub name containing the activity logs, overwrite he default value if the logs are exported in a different eventhub
      eventhub: "insightslogskubeapiserver"
      # consumer group name that has access to the event hub, we advise creating a dedicated consumer group for the azure module
      consumer_group: "$Default"
      # the connection string required to communicate with Event Hubs, steps to generate one here https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-get-connection-string
      connection_string: "Endpoint=sb://eventhubdmznonprd.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=(redacted)"
      # the name of the storage account the state/offsets will be stored and updated
      storage_account: "eventhubdmznonprd"
      # the storage account key, this key will be used to authorize access to data in your storage account
      storage_account_key: 'DefaultEndpointsProtocol=https;AccountName=eventhubdmznonprd;AccountKey=(redacted);EndpointSuffix=c\
ore.windows.net'
```

- Version: filebeat-8.1.1-linux-x86_64
- Operating System: Ubuntu 20.04
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-azure-module-base64-issue/301198

I don't understand what's the problem with base64 encoding. Any thoughts ?

Thanks a lot
