### ISSUE TITLE
[Filebeat][microsoft][m365_defender] Error processing when alerts.entities is an empty list

### ISSUE THREAD

**Issue by leehinman** [elastic/beats#31223]
When `json.alerts.entities` is an empty list, we get the error message:

```
    "error": {
      "message": "Illegal list shortcut value [url]."
    },
```

most likely from

```
- rename:
    field: json.alerts.entities.url
    target_field: url.full
    ignore_missing: true
    if: ctx?.json?.alerts?.entities?.url != null
```
