### ISSUE TITLE
[Filebeat - v7.17.2] Using the close.reader.on_eof: true option always results Error - Read line error: EOF

### ISSUE THREAD

**Issue by sinhagithub** [elastic/beats#31308]
Using the `close.reader.on_eof: true` option always results in the Error at the EOF:
So, am I missing some configuration here, or this a bug (as EOF should not be reported as error):

[log.Errorf("Read line error: %v", err)](https://github.com/elastic/beats/blob/v7.17.2/filebeat/input/filestream/input.go#L322)

> 2022-04-14T18:59:16.106Z        ERROR   [input.filestream]      filestream/input.go:322 Read line error: EOF    {"id": "cdr-dqi", "source": "filestream::cdr-dqi::native::3561807-64769", "path": "/opt/sdf/cdr/ts_20220414_185910.cdr", "state-id": "native::3561807-64769"}

filebeat.yaml

```
# CDR
- type: filestream

  # Change to true to enable this input configuration.
  enabled: true
  id: cdr-dqi

  # Tuning options
  close.reader.on_eof: true
  close_inactive: 5m
  ignore_older: 6m
  clean_inactive: 7m

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /opt/sdf/cdr/ts_[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]_*.cdr

  # Optional additional fields. These fields can be freely picked
  # to add additional information to the crawled log files for filtering
  fields:
    logtype: cdr

  # Exclude lines. A list of regular expressions to match. It drops the lines that are
  # matching any regular expression from the list.
  exclude_lines: ["^CDR Header", "^CDR Footer"]
```

File content:
> [sdfrun@dqi-ssi2-dqi-86654c8476-52ctb cdr]$ tail /opt/sdf/cdr/ts_20220414_185910.cdr
> ...
> DQI,F,1404202218:59:10.639,,unknownIMSI,,43,SOAP:SOAP request type error: start tag not found,0,N/A,N/A,2321,1,10.32.22.15
> DQI,F,1404202218:59:10.639,,unknownIMSI,,43,SOAP:SOAP request type error: start tag not found,0,N/A,N/A,2321,50,200.100.100.100
> CDR Footer
> [sdfrun@dqi-ssi2-dqi-86654c8476-52ctb cdr]$
