### ISSUE TITLE
multiple filestream input not work

### ISSUE THREAD

**Issue by zzq0324** [elastic/beats#31332]
Hi, in my case, i use one filebeat node to collect both nginx and mysql log. But it seems nginx log work correctly, mysql is ignored . When i remove nginx inputs, mysql inputs work correctly.

I use filebeat with 8.1.2 version, `filebeat.yml` as follow:

```yml
filebeat.inputs:
  - type: filestream
    enabled: true
    close_renamed: true
    close_removed: true
    clean_removed: true
    paths:
      - /var/log/test/nginx/nginx_access.log
    fields_under_root: true
    fields:
      service_name: nginx
      log_type: access

  # nginx error log
  - type: filestream
    enabled: true
    close_renamed: true
    close_removed: true
    clean_removed: true
    paths:
      - /var/log/test/nginx/nginx_error.log
    fields_under_root: true
    fields:
      service_name: nginx
      log_type: error

  # mysql error log
  - type: filestream
    enabled: true
    close_renamed: true
    close_removed: true
    clean_removed: true
    paths:
      - /Users/zhengzhq/Downloads/elk/logs/mysql/error.log
    parsers:
      - multiline:
          pattern: "^([0-9]{4}-[0-9]{2}-[0-9]{2}|[0-9]{6})"
          negate: true
          match: after
    fields_under_root: true
    fields:
      service_name: mysql
      log_type: error

  # mysql slow log
  - type: filestream
    enabled: true
    close_renamed: true
    close_removed: true
    clean_removed: true
    paths:
      - /Users/zhengzhq/Downloads/elk/logs/mysql/slow.log
    parsers:
      - multiline:
          pattern: "^(# Time: )"
          negate: true
          match: after
    exclude_lines: ['^[\/\w\.]+, Version: .* started with:.*']
    fields_under_root: true
    fields:
      service_name: mysql
      log_type: slow

processors:
  - drop_fields:
      fields: ["agent"]

output.console:
  enabled: false
  codec.json:
    pretty: true

output.kafka:
  enabled: true
  # initial brokers for reading cluster metadata
  hosts: ["localhost:9092"]
  # message topic selection + partitioning
  topic: "logstash"
  partition.round_robin:
    reachable_only: false
  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000
```

Does it has limit count for inputs?
