### ISSUE TITLE
Add target and remove_field options to decode_json_field

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#3134]
I was trying to use the new `decode_json_field` processor to decode pretty multiline json messages (as in #1208). And without a configurable "target" it's kind of hard to use since the mapping for the `message` field is a string, but decode_json_field makes `message` an object.

So I propose we add a configuration options for `target` and `remove_field` like [Logstash](https://www.elastic.co/guide/en/logstash/current/plugins-filters-json.html#plugins-filters-json-target) has.

For example:

filebeat.yml
```yaml
filebeat.prospectors:
- paths:
    - input.json
  multiline.pattern: '^}'
  multiline.negate: true
  multiline.match: before

output.console.pretty: true

processors:
  - decode_json_fields:
      fields: ['message']
```

input.json
```json
{
  "hello": "world"
}
{
  "hello": "world",
  "foo":   "bar"
}
```

output
```json
{
  "@timestamp": "2016-12-06T17:04:00.892Z",
  "beat": {
    "hostname": "macbook13.local",
    "name": "macbook13.local",
    "version": "6.0.0-alpha1"
  },
  "input_type": "log",
  "message": {
    "hello": "world"
  },
  "offset": 23,
  "source": "input.json",
  "type": "log"
}
{
  "@timestamp": "2016-12-06T17:04:00.892Z",
  "beat": {
    "hostname": "macbook13.local",
    "name": "macbook13.local",
    "version": "6.0.0-alpha1"
  },
  "input_type": "log",
  "message": {
    "foo": "bar",
    "hello": "world"
  },
  "offset": 64,
  "source": "input.json",
  "type": "log"
}
