### ISSUE TITLE
[Functionbeat] Support environment variables in configuration 

### ISSUE THREAD

**Issue by fdartayre** [elastic/beats#31373]
**Describe the enhancement:**

Support environment variables in configuration like `role` or `event_source_arn`:
```yaml
functionbeat.provider.aws.functions:
  - name: sqs
    enabled: true
    type: sqs

    role: arn:aws:iam::${ACCOUNT}:role/MyFunction

    triggers:
    - event_source_arn: arn:aws:sqs:eu-central-1:${ACCOUNT}:${SQS}
```
