### ISSUE TITLE
filebeat conditional checks fail on array fields when it's been parsed by json parser.

### ISSUE THREAD

**Issue by JalehD** [elastic/beats#3138]
- Version: 5.0.2
- Operating System: any
- Steps to Reproduce: Using below sample events and config it is easy to produce below error and the events are not dropped as expected.

`{"@timestamp":"2016-12-06T11:24:13.731+00:00","@version":1,"message":"free text for reference","logger":"test","thread_name":"http-test","level":"INFO","level_value":20000,"HOSTNAME":"Juli-lab","duration":"985","depth":"1","action":"test Request","appPath":"/tmp/test","order":"1","tags":["ELK_TRACE"]}
{"@timestamp":"2016-12-06T11:24:13.788+00:00","@version":1,"message":"free text for reference","logger":"test","thread_name":"http-test","level":"INFO","level_value":20000,"HOSTNAME":"juli-lab","duration":"1060","depth":"0","action":"test response","appPath":"/tmp/test","order":"1","tags":["ELK_TRACE"]}`

With config 

```
filebeat.prospectors:
 - input_type: log
   paths: 
     - /Users/Jaleh/ALL_MY_TESTS/test.log
   json: 
     message_key: message 
     keys_under_root: true 
     fields: 
       debug_app: Y 
     fields_under_root: true
processors: 
 - drop_event: 
    when: 
     contains: 
       tags: "ELK_TRACE"
output.file:
  path: /Users/Jaleh/ALL_MY_TESTS/
  filename: filebeat.test.json
```

And the warnings looks like before the event is published instead of being dropped. 

`2016/12/07 12:38:44.965301 condition.go:292: WARN unexpected type []interface {} in contains condition as it accepts only strings.
2016/12/07 12:38:44.965481 client.go:184: DBG  Publish: 
`
