### ISSUE TITLE
Error on invalid configuration options

### ISSUE THREAD

**Issue by robin13** [elastic/beats#3145]
YAML is a very readable configuration file format, but it is very easy to create invalid configurations simply by incorrect indenting which results in options which were presumed to be enabled not being enabled and silently ignored.

e.g.

In this case the `spool_size` is incorrectly indented, causing this configuration to be silently ignored

```
filebeat:
  prospectors:
    -
      paths:
        - "/var/log/my-app/*.json"
      input_type: log
      spool_size: 8192
```

The correct format would be:
```
filebeat:
  prospectors:
    -
      paths:
        - "/var/log/my-app/*.json"
      input_type: log
  spool_size: 8192
```
This kind of error is easy for humans to make - it would be great if filebeat could (similar to elasticsearch since 5.0) refuse to start with any invalid configuration options and so ensure that every configuration defined is actually used.
