### ISSUE TITLE
Fix input ID uniqueness

### ISSUE THREAD

**Issue by jlind23** [elastic/beats#31512]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 
- Operating System: 
- Discuss Forum URL:
- Steps to Reproduce:

**Comment by belimawr** [comment]
I've been looking into how to solve that from the input side of things, here are my findings.

## Elastic-Agent
The kubernetes autodiscover runs on the Elastic-Agent and generates filestream input configurations that are sent to Filebeat. There is a good description of how it works on a high level [here](https://github.com/elastic/beats/blob/aa264bdf008a9bf309e61744e9ec8c5586593f12/x-pack/elastic-agent/pkg/composable/providers/kubernetes/README.md#high-level-description).

Unfortunately, there isn't a direct connection between the input configuration and the kubernetes provider. The data generated by the autodiscovery event at some point gets converted by [transpiler.RenderInputs](https://github.com/elastic/elastic-agent/blob/main/internal/pkg/agent/application/pipeline/emitter/controller.go#L163) that does not know about any input specifics.

Trying to add any code there to handle a kubernetes exception would be a very ugly hack.

I believe the best fix for the Elastic-Agent case is to update the integration to include `${kubernetes.container.id}` as part of the filestream input ID.

## Filebeat
Filebeat kubernetes autodiscovery at the moment does not suffer from the filestream input ID issue because under the hood it uses the container input that, under the hood, is the log input. For each kubernetes container a new container input is created.

If we ever migrate the container input to filestream or use filestream directly we would face the input ID uniqueness problem, however on Filebeat it is manageable.

The kubernetes autodiscover provider contains a [config](https://github.com/elastic/beats/blob/40b8c5023cded7761e957dc3f247e450576b8e06/libbeat/autodiscover/providers/kubernetes/kubernetes.go#L136) that contains the template used to render the container input. So if needed, we could parse this part of the YAML and endure there is an ID and it's unique. One way for that is to append `${data.kubernetes.container.id}` to the input ID.

**Comment by cmacknz** [comment]
## Elastic-Agent
> I believe the best fix for the Elastic-Agent case is to update the integration to include ${kubernetes.container.id} as part of the filestream input ID.

Which integration? Agent only supports autodiscover in standalone mode.

Looking through the agent autodiscover provider I can see that it is dynamically generating processors with the container metadata: https://github.com/elastic/elastic-agent/blob/a18cfadcd38fef27be0307ae5307b562ceed44fc/internal/pkg/composable/providers/kubernetes/pod.go#L314

Those processors are ultimately going to end up in the input configuration block, so there is already a path to modify the filebeat configuration based on container metadata. Can we just extend the code path used for this to also return an optional input ID in addition to the processors?

## Filebeat

> If we ever migrate the container input to filestream or use filestream directly we would face the input ID uniqueness problem, however on Filebeat it is manageable.

I would create a separate issue for migrating the container input to use `filestream` instead of `log` and link it from our overall issue to migrate everything to filestream. We can deal with this problem later.

**Comment by cmacknz** [comment]
Here's the original issue and PR for the agent dynamic provider variable substitution that we probably need to hook into:
* https://github.com/elastic/beats/issues/20781
* https://github.com/elastic/beats/pull/20839

**Comment by cmacknz** [comment]
Looking through the variable substitution we would probably need the code to treat the input configuration in the policy as if the absence of a user provider ID implies it was defined like as a template variable.

```yml
inputs:
  - type: filestream
    id: filestream-${kubernetes.container.id} # Implicit substitution if one wasn't provided
    enabled: true
    streams:
      - paths:
          - /var/log/{{local_dynamic.key}}
```

Maybe when the agent loads the agent policy for the first time in standalone mode we can check if K8s autodiscovery is in use, and then just inject the ID template variable into the policy if there isn't an ID defined already?

**Comment by belimawr** [comment]
> Which integration? Agent only supports autodiscover in standalone mode.

The [Kubernetes Container Logs](https://docs.elastic.co/integrations/kubernetes/container-logs) one. It exists on both modes. As  far as I know, and have seen, the main difference between managed by fleet and standalone modes are the options exposed to the user. They use the same codebase with different options configured. Ex. If managed by fleet, Elastic-Agent always assumes it's running inside the kubernetes cluster, while standalone exposes the option to configure the cluster access.

> Looking through the agent autodiscover provider I can see that it is dynamically generating processors with the container metadata: https://github.com/elastic/elastic-agent/blob/a18cfadcd38fef27be0307ae5307b562ceed44fc/internal/pkg/composable/providers/kubernetes/pod.go#L314

I understood that as being the [processors](url) that run on the event, not a policy processor. It adds [this processor configuration](https://github.com/elastic/elastic-agent/blob/a18cfadcd38fef27be0307ae5307b562ceed44fc/internal/pkg/composable/providers/kubernetes/pod.go#L306-L321), that leads to those fields being added to the event:
![2022-07-08_10-40](https://user-images.githubusercontent.com/333577/177953383-64ff6b9e-1949-43a7-be95-af395c6e79fe.png)


I looked at the links you posted on: https://github.com/elastic/beats/issues/31512#issuecomment-1178081467, but they only reinforced my understanding regarding the processors. We could have a f-2-f chat to clarify that ;)

**Comment by belimawr** [comment]
> Looking through the variable substitution examples we would probably need the code to add an ID template variable automatically like:
> 
> ```yaml
> inputs:
>   - type: filestream
>     id: filestream-${kubernetes.container.id} # Implicitly added if not specified by the user
>     enabled: true
>     streams:
>       - paths:
>           - /var/log/{{local_dynamic.key}}
> ```
> 
> Maybe when the agent loads the agent policy for the first time in standalone mode we can check if k8s autodiscovery is in use, and then just inject the ID template variable into the policy if there isn't an ID defined already?
> 
> Hopefully the autodiscovery variable substitution would just work without modification if we did that.

In that case of modifying the policy when it's being loaded, I believe updating the integration would be a more robust solution.

On my tests the Kubernets Container Logs integration generates this entry in the policy:
```yaml
  - id: filestream-container-logs-46cdfbd0-12ba-49b1-8006-aa501f145459
    name: kubernetes-1
    revision: 1
    type: filestream
    use_output: default
    meta:
      package:
        name: kubernetes
        version: 1.21.1
    data_stream:
      namespace: default
    streams:
      - id: >-
          filestream-kubernetes.container_logs-46cdfbd0-12ba-49b1-8006-aa501f145459
        data_stream:
          dataset: kubernetes.container_logs
          type: logs
        paths:
          - '/var/log/containers/*${kubernetes.container.id}.log'
        prospector.scanner.symlinks: true
        parsers:
          - container:
              stream: all
              format: auto
```
It's easy to know it's filestream because of `type: filestream`, but it's hard to know it's a kubernetes autodiscover. We do have `    meta.package.name: kubernetes`, but that's not reliable and is specific for this integration.

**Comment by belimawr** [comment]
PR to update the integration created: https://github.com/elastic/integrations/pull/3672

I'm still seeing log messages like
```
filestream input with ID 'kubernetes-container-logs-d9ba19b3cc48c2231bd648f3f573e984b6c332093f250a6facdb92090bfaa4b9-' already exists, this will lead to data duplication, please use a different ID
```
I believe it is due  https://github.com/elastic/beats/issues/31767. I'll keep the integrations PR as a draft until I have an answer.

**Comment by rstatsinger** [comment]
Hello all - I have a customer that is still seeing duplicate filebeat data from versionm 8.3.3 of the Elastic Agent. Here is his filebeat.yaml:

filebeat.inputs:

type: filestream
enabled: true
id: "ecs-app-logging"
paths:
C:\MVD2\Logs\ECS*.log
json.keys_under_root: true
json.overwrite_keys: true
json.add_error_key: true
json.expand_keys: true

What could be the problem here? TiA for any input

**Comment by cmacknz** [comment]
@rstatsinger looks like the same report as https://github.com/elastic/beats/issues/31239#issuecomment-1251535590, can we get a separate issue or an SDH opened for tracking this so it isn't spread across multiple other issues?

**Comment by keenborder786** [comment]
I also facing a similar error. 

The error is:

```console
{"log.level":"error","@timestamp":"2023-03-22T17:11:22.014Z","log.logger":"input","log.origin":{"file.name":"input-logfile/manager.go","file.line":182},"message":"filestream input with ID 'spark-executors-file-stream-e40cd871-dabd-46b5-a245-decac624262a' already exists, this will lead to data duplication, please use a different ID","service.name":"filebeat","ecs.version":"1.6.0"}
```
My filebeat configuration is:

```yaml
  filebeat.autodiscover:
    providers:
    - type: kubernetes
      templates:
        - condition:
            equals:
              kubernetes.namespace: "spark"
          config:
            - type: container
              paths:
              - /var/log/containers/*-${data.kubernetes.container.id}.log
              multiline.type: pattern
              multiline.pattern: '^[[:space:]]+(at|\.{3})[[:space:]]+\b|^Caused by:|^java'
              multiline.negate: false
              multiline.match: after
            - type: log
              id: spark-executors-file-stream-${data.kubernetes.node.uid}
              paths:
              - /var/log/spark/work/*/*/stdout
              - /var/log/spark/work/*/*/stderr
  processors:
    - add_cloud_metadata:
    - add_host_metadata:
  output.logstash:
    hosts: ["logstash:5044"]
```

I am using the latest version i.e 8.6.2 for filebeat. I don't understand why this issue is closed if it still has not been resolved in the latest release.
