### ISSUE TITLE
Add support for wildcard, *, for SMB Server Shares in Windows module, Perfmon Metricset

### ISSUE THREAD

**Issue by sachin-frayne** [elastic/beats#31516]
**Describe the enhancement:** Add support for wildcard, *, for SMB Server Shares in Windows module, Perfmon Metricset

**Describe a specific use case for the enhancement or feature:** When you have multiple SMB Server Shares, and you want to collect data from all of them one would assume that you can use wildcard like with other systems but and error is thrown:

```
ERROR module/wrapper.go:259 Error fetching data for metricset windows.perfmon: failed reading counters: failed collecting counter values: No data to return.
```

```
# This config works when providing only one instance "_Total"
- module: windows
  period: 60s
  metricsets:
  - perfmon
  ...
  perfmon.queries:
  - object: "SMB Server Shares"
  instance: "_Total"
  ...

# But when we change it to get all the instances, we get the errors explained above:
- module: windows
  period: 60s
  metricsets:
  - perfmon
  ...
    perfmon.queries:
    - object: "SMB Server Shares"
    instance: "*"
    ...
```

instance: "*" works for something like "LogicalDisk" but not for "SMB Server Shares" it seems.
I think that the main reason for this is that windows has a strange notation for server shares: `\\*\C$` for example.
The instances contain `*` and `\`, so I suppose this feature is currently not supported.
