### ISSUE TITLE
Prometheus module URL encoding

### ISSUE THREAD

**Issue by pjhampton** [elastic/beats#31536]
For confirmed bugs, please report:
- Version: 8.2.0
- Operating System: Mac + Azn Linux
- Discuss Forum URL: n/a
- Steps to Reproduce: 

Prometheus (and the Prometheus fleet integration) have quite a few issues which I ran into when setting up ingestion for confluent cloud:

```yml
scrape_configs:
  - job_name: Confluent Cloud
    scrape_interval: 1m
    scrape_timeout: 1m
    honor_timestamps: true
    static_configs:
      - targets:
        - api.telemetry.confluent.cloud
    scheme: https
    basic_auth:
      username: <Cloud API Key>
      password: <Cloud API Secret>
    metrics_path: /v2/metrics/cloud/export
    params:
      "resource.kafka.id":
        - AAABBBCCC
```

The primary problem seems to me that `https://api.telemetry.confluent.cloud/v2/metrics/cloud/export?resource.kafka.id=AAABBBCCC` when encoded `?` as `%3F` causing a 404. This is something I'm hoping to get a workaround for as soon as I can.
