### ISSUE TITLE
[bug?] json template can't use custom analyzer, the type is also wrong

### ISSUE THREAD

**Issue by fanybook** [elastic/beats#31600]
- Version: 7.17.3
- Operating System: centos7 arm64
- Discuss Forum URL: https://discuss.elastic.co/t/how-to-use-custome-analyzer-in-filebeats-json-template/304439
- Steps to Reproduce: 

log file: /tmp/log/123.log
```
{"level123": "error", "message123": "Stray birds of summer come to my window to sing and fly away."}
{"level123": "info", "message123": "And yellow leaves of autumn, which have no songs, flutter and fall there with a sign."}
{"level123": "warn", "message123": "O Troupe of little vagrants of the world, leave your footprints in my words."}
{"level123": "error", "message123": "The world puts off its mask of vastness to its lover."}
{"level123": "debug", "message123": "It becomes small as one song, as one kiss of the eternal."}
{"level123": "debug", "message123": "It is the tears of the earth that keep her smiles in bloom."}
```

json template file: /opt/filebeat/index/template/golang_logs_index_template.json
```json
{
  "index_patterns": ["golang_logs*"],
  "template": {
    "settings": {
      "number_of_shards": 1
    },
    "mappings": {
      "properties": {
        "message123": {
          "type": "text",
          "analyzer": "custom_analyzer"
        },
        "level123": {
          "type": "keyword"
        }
      }
    },
    "aliases": {}
  }
}
```

configure file: test01.yml
```yml
filebeat.inputs:
- type: filestream
  enabled: true
  id: "tmp-logs"
  paths:
    - /tmp/logs/*.log
  parsers:
    - ndjson:
        keys_under_root: true
        overwrite_keys: true
        add_error_key: true


setup.ilm.enabled: false
setup:template.enabled: false
setup.template.overwrite: false
setup.template.name: "golang_logs"
setup.template.pattern: "golang_logs*"

setup.template.json.enabled: true
setup.template.json.path: "/opt/filebeat/index/template/golang_logs_index_template.json"
setup.template.json.name: "golang_logs_index_template"


output.elasticsearch:
  hosts: ["172.16.100.128:9200"]
  index: "golang_logs"
  username: "elastic"
  password: "temppwd"

```

execute command: `/opt/filebeat/filebeat -e -c test01.yml`

generated golang_logs index:
```json
{
  "version": 6,
  "mapping_version": 2,
  "settings_version": 2,
  "aliases_version": 1,
  "routing_num_shards": 1024,
  "state": "open",
  "settings": {
    "index": {
      "number_of_shards": "1",
      "blocks": {
        "read_only_allow_delete": "true"
      },
      "provided_name": "golang_logs",
      "creation_date": "1652325906349",
      "number_of_replicas": "1",
      "uuid": "ep_JufAsQEOiKNL06sgqng",
      "version": {
        "created": "7080199"
      }
    }
  },
  "mappings": {
    "_doc": {
      "properties": {
        "@timestamp": {
          "type": "date"
        },
        "message123": {
          "type": "text",
          "fields": {
            "keyword": {
              "ignore_above": 256,
              "type": "keyword"
            }
          }
        },
        "log": {
          "properties": {
            "file": {
              "properties": {
                "path": {
                  "type": "text",
                  "fields": {
                    "keyword": {
                      "ignore_above": 256,
                      "type": "keyword"
                    }
                  }
                }
              }
            },
            "offset": {
              "type": "long"
            }
          }
        },
        "level123": {
          "type": "text",
          "fields": {
            "keyword": {
              "ignore_above": 256,
              "type": "keyword"
            }
          }
        }
      }
    }
  },
  "aliases": [],
  "primary_terms": {
    "0": 1
  },
  "in_sync_allocations": {
    "0": [
      "KsiQMWNIQIGn2jlJgyNbhQ"
    ]
  },
  "rollover_info": {}
}
```
