### ISSUE TITLE
[filebeat][httpjson] Add support for setting hash in request header. 

### ISSUE THREAD

**Issue by vinit-elastic** [elastic/beats#31613]
**Describe the enhancement:**
This issue here is to request support for adding the SHA256 hash of given strings and set it in the request header the current httpjson input of filebeat.

We need a function in the value template to generate the SHA256 digest of a given list of strings. Moreover, the function can be a generic hash function that can support different types of hashes for better compatibility with other APIs. 

```
- type: httpjson
  request.transforms:
    - set:
        target: header.Authorization
        value: 'Basic [[ hash "sha256" "string-1" "string-2" ]]'
```

**Describe a specific use case for the enhancement or feature:**
Here's a reference link for generating a digest for AWS Signature Version 4, 
https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html
