### ISSUE TITLE
@timestamp milliseconds is always 000

### ISSUE THREAD

**Issue by ofira87** [elastic/beats#3177]
Log events which occur one after the other (within a difference of milliseconds) sometimes displayed, in services like Elasticsearch\Kibana, in an incorrect order.
This is happening because their milliseconds value in '@timestamp' key is always zero (.000).

Looking at Event Viewer, you can see that INFO event 1035 occurred few milliseconds after INFO event 11729 (it happened twice):
![image](https://cloud.githubusercontent.com/assets/5831435/21097858/4e3444f8-c06f-11e6-89c8-c729e52a9c5d.png)

And here, looking at Kibana, you can see that because of the lake of milliseconds this events are displayed incorrectly (the first couple of 11729 and 1035 events are displayed correctly*, first 11729 and then 1035, but the other two events are not):
![image](https://cloud.githubusercontent.com/assets/5831435/21097774/e42ab6f0-c06e-11e6-8a78-94b7e9c83ae7.png)

***Please ignore the hours.**

Here's the same example logged using NXlog instead.
You can see the Event Viewer here:
![image](https://cloud.githubusercontent.com/assets/5831435/21098070/2789d0f6-c070-11e6-8209-7c68255b5939.png)

And here you can see them displayed correctly in Kibana **because** of the milliseconds value (given from the NXlog logs):
![image](https://cloud.githubusercontent.com/assets/5831435/21098240/e957dd54-c070-11e6-961b-46cd5afea44a.png)

**Comment by andrewkroh** [comment]
For bug reports please provide:

- Winlogbeat Version: 
- Operating System:

For side-by-side comparison, please provide the JSON content of the same event log record as logged by Winlogbeat and the other tool. In Kibana you can expand the event, select the JSON tab, and copy the `_source` field.

**Comment by maddin2016** [comment]
Winlogbeat set time with milliseconds. Here example from my machine `"@timestamp": "2016-12-16T07:52:45.994Z"`. Do you have any filter or logstash between metricbeat and kibana?

**Comment by ofira87** [comment]
@andrewkroh Will upload soon, both versions and source message.

@maddin2016 I'm sending the data to a service which have a built-in Logstash with specific rules for Winlogbeat messages\logs. As I said, I will take a look at the source itself.

**Comment by ofira87** [comment]
@andrewkroh
- **Winlogbeat Version:** 5.1.1 x64
- **Operating System:** Microsoft Windows Server 2012 R2 Standard x64 Version 6.3.9600

@maddin2016 The `@timestamp` value inside `_source` property is:
`"@timestamp": "2016-12-12T10:37:26.000+00:00"`
And for the second message\log:
`"@timestamp": "2016-12-12T10:39:45.000+00:00"`


As I mentioned, the logs are sent to a service, which have a built-in Logstash, called [logz.io](https://logz.io).
Here is the `winlogbeat.yml` config file (minus comments and minus the real PATH_TO_CERT/MY_CERT value):
```
winlogbeat.event_logs:
  - name: Application
    ignore_older: 72h
  - name: Security
    ignore_older: 72h
  - name: System
    ignore_older: 72h
fields:
  env: staging
  logzio_codec: json
  token: wqxpsTZkeQVLPgnzJHeqUHPFjwNUAfvh
fields_under_root: true
output.logstash:
  # The Logstash hosts
  hosts: ["listener.logz.io:5015"]
  ssl.certificate_authorities: ["C:/PATH_TO_CERT/MY_CERT.crt"]
```
