### ISSUE TITLE
[Functionbeat] Support configuration variables for logstash output codec format

### ISSUE THREAD

**Issue by ptallapureddy** [elastic/beats#31812]
**Describe the enhancement:**

Support logstash output log format type:

```
#----------------------------- Logstash output ---------------------------------
output.logstash:
  enabled: true
  hosts: ["localhost:5044"]
  codec.format: json

```

**Describe a specific use case for the enhancement or feature:**

when pushing aws cloudwatch logs to logstash which is expecting json codec format.
