### ISSUE TITLE
Introduce namespace for metricset specific config options

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#3182]
Currently all config options in metricbeat are directly under the module:

```
- module: system
  metricsets:
    - cpu
    - process
  processes: ['.*']
  cpu_ticks: false
  cgroups: false
```

`cgroups` and `processes` only applies to `process` and `cpu_ticks` only to `cpu` and `core` metricset. Instead of having these config options on the top level, I suggest to move these under the metricset namespace to make it more obvious they do not apply to all metricsets. This would look as following:

```
- module: system
  metricsets:
    - cpu
    - process
  cpu.ticks: false
  process.filter: ['.*']
  process.cgroups: false
```

The above is a little bit tricky as cgroups also applies to core. Either we could use a separate config `core.cgroups: false` or just use the one from cpu. Having a separate one has the advantage, that cgroups could be enabled for cpu but not for core in the same metricset. But this case could also be covered with defining the module twice.
