### ISSUE TITLE
The path is wrong when filebeat imports dashboard

### ISSUE THREAD

**Issue by wajika** [elastic/beats#31828]
ver: filebeat 7.15.3 and 7.16.3
**sudo /usr/bin/filebeat setup --dashboards --modules nginx**
```
Loading dashboards (Kibana must be running and reachable)
Exiting: error connecting to Kibana: fail to get the Kibana version: HTTP GET request to http://kibana:5601/kibana/s/log/api/status fails: Not Found: <nil>. Response: {"statusCode":404,"error":"Not Found","message":"Not Found
```
I can get the version after modifying the URI
`http://kibana:5601/s/log/api/status`

**Comment by wajika** [comment]
Does "space.id: log" point to the default space?

```
filebeat.inputs:
- type: log
  enabled: false
  paths:
    - /var/log/*.log

- type: filestream
  enabled: false
  paths:
    - /var/log/*.log

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 10s

setup.template.settings:
  index.number_of_shards: 3
  index.number_of_replicas: 1
  index.codec: best_compression
  #_source.enabled: false

name: es-01
tags: ["ydy_cluster", "production","elasticsearch"]
fields:
  env: production

setup.kibana:
output.elasticsearch:
  hosts: ["10.120.0.30","10.120.0.14","10.120.0.10"]

logging.level: info

monitoring:
  enabled: true
  elasticsearch:
    hosts: ["10.120.0.30","10.120.0.14","10.120.0.10"]

```

**Comment by cmacknz** [comment]
Given the Kibana section of your configuration:

```yml
setup.kibana:
  host: "kibana:5601"
  space.id: log
  protocol: "http"
  path: /kibana
```

`space.id: log` points to a space called `log`. To use the default space, omit the `space.id` option.

The `kibana` path is being prepended to the HTTP path because it is configured to do so using the `path: /kibana` option. If you remove this it should work for you. It's documented at https://www.elastic.co/guide/en/beats/filebeat/7.16/setup-kibana-endpoint.html#kibana-path-option

I don't think there's a bug here, so I'm closing this. If you think there is still an issue you can reopen it. You can also post to https://discuss.elastic.co/ if you haven't already.
