### ISSUE TITLE
Enable monitoring of Kubernetes workloads from the resource side for agent standalone

### ISSUE THREAD

**Issue by mlunadia** [elastic/beats#31872]
Also known as hints based auto-discovery for agent standalone
Picking up context from https://github.com/elastic/beats/issues/23876

We want to enable users to monitor Kubernetes workloads from the resource side for users of agent standalone.

**Acceptance criteria**
Kubernetes users can declare their workloads and include hints, similar to those described in beats documentation [metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html) and [filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover-hints.html) manifests and then expect agent whilst enrolled in standalone mode to pick these hints launch the proper config for it.

**Comment by ChrsMark** [comment]
We had an initial chat about this with @gizas and in order to start pushing this forward we first need to decide on the approach we will follow to make this feature available to our users. Keep in mind that this feature requires cross team effort from Cloudnative, Agent and Fleet UI teams. The implementation can happen from one or more teams accordingly but first we need to have a solid plan about the way forward. Once we have decided the what and the how we can create smaller, detail specific issues for the various parts of the feature's implementation. Here is a first outline of the current status of the issue and a high level proposal for its implementation across the "stack".

# Hint based autodiscovery in standalone Agent

## Related issues from the past

[1] [Hints based autodiscovery](https://github.com/elastic/beats/issues/23876)
[2] [Templates support](https://github.com/elastic/beats/issues/24054)


## Current Status

### What we have so far?

There is available the implementation to watch for Pods and collect metadata for them.
We can easily identify Pods (Nodes etc) and we can easily identify the hints out of the Resources' annotations.


### What we need

We need a mechanism to receive those hints and match them with inputs/integrations. This mechanism can either "live" in Agent to cover standalone mode or in Fleet UI OR in an external component like an additional "operator". In this proposal we only focus on standalone mode. 

### Standalone mode

The Agent needs to know how packages/inputs look like in order to match them with the hints. One way to achieve this is by using input templates. This would make the flow quite similar to Beats.



## Feature design proposal (technical/high-level)

As it was already mentioned, Agent can identify Pods (and other workloads) in Kubernetes and communicate this information to Agent's controller so as to enable and populate inputs' configuration accordingly. 
The current proposal is based in the template's support which was discussed already in the past.
The proposed way to add hint's support is the following:

1. Identify hints in Pods' annotations and emit the "hints' event" at the same time the provider emits the mappings for the composable controller at https://github.com/elastic/elastic-agent/blob/7db7406cc04d6dd8f2d47f8a37e299da4598056b/internal/pkg/composable/providers/kubernetes/pod.go#L155. We can use a different channel to emit these events or the same but this is an implementation detail to be decided later.
2. Agent's composable controller (or a new kind of controller) receives the hints and tries to utilise them in order to populate the values of the respective template which would be available in `data/templates.d`. This functionality was outlined at https://github.com/elastic/beats/issues/24054#issuecomment-784436190. We can figure out the details accordingly but this is the high level idea.
3. After the successful evaluation of the hints and the input configuration construction Agent adds the new configuration block into the local policy and the input is enabled.


### How templates are created

One important "detail" that needs to be discussed is how the templates would become available in Elastic Agent locally. At https://github.com/elastic/beats/issues/24054#issuecomment-784436190 (Part 2) it was proposed to ship the templates along with the Agent binary which implies that we would include them in the build/packaging stage after retrieving them from the Package Registry. This could work but we come with an easier solution (kudos to @gizas :D) which proposes to leave this work to our users and give them the option to download the templates from Fleet UI in the same was they do for the standalone policy. So Fleet UI can create a `templates.d.tar` on the fly using the latest available packages and then users can extract this zipped directory at `data/templates.d`. 
This gives us the opportunity to make the delivery of the templates easier using the latest versions of the available packages from Fleet UI, and at the same time we follow similar UX with the one we have for the standalone policy. It would be Fleet UI's responsibility to collect the packages and construct the templates to make them available to the users.


## User journey

Having described the high level of the technical part we need to also describe how users will us the feature. Here is an example user journey:

1. Users download Elastic Agent binary locally to run in standalone mode. The process is the same with today (https://www.elastic.co/guide/en/fleet/current/install-standalone-elastic-agent.html). 
2. In the next step users would need to create and download the policy as explained at https://www.elastic.co/guide/en/fleet/current/create-standalone-agent-policy.html
3. Final step to support to templates is that users also download the templates from Fleet UI the same way they do for step2
![](https://i.imgur.com/CkUSFLL.png)

** The UX details/wording etc can be improved but this is the high level idea.


### Proposed implementation issues

1. Implement hints' identification mechanism in k8s provider side and make hints' events available to Agent's controller/core.
2. Implement support for input templates in Agent
3. Implement hints' evaluation logic based on template's (based on item 2)
4. Implement template construction out of the packages on Fleet UI and make them available to users in the same way the standalone policy is provided


@gizas @mlunadia @ruflin let me know what you think about this and how we could move this forward.

**Comment by ruflin** [comment]
The nice part about the proposed solution is that step 1 and 2 can happen fully independent from Fleet. Also having support for input templates in Elastic Agent means it does not only support templates coming from Fleet but also users could build their own if needed. 

Also if later on we have an orchestrator solution, the templates will still be useful.

We should consider to bundle some templates like `system` by default with the Elastic Agent for convenience.

**Comment by ph** [comment]
As pointed out in https://github.com/elastic/beats/issues/24054#issuecomment-784436190, looking at the described workflow suggested in the comment.
Downloading the package or embedding will works. One thing I believe we are missing is a way to add a runtime constraint on the package itself.
IE you can only run this package with Elastic Agent version 8.5+ or 8.6 and lower.


Concerning the download from the UI we could instead make the agent policy bigger with the template embedded in it, something like this.


```yaml
inputs:
- type: filestream
- type: tcp

# Instead of looking up on disk we can look at this instead, which could be a VFS representation of the structure on disk.
template.d:
 nginx/1.8:
    ....

```

The user only have one thing to download and deploy, the yaml is bigger but this reduce the risk from having mistmatch.

**Comment by ChrsMark** [comment]
Thanks for your reviews @ruflin and @ph :)

Heads-up on this. After the initial feedback and some more brainstorming around this, it seems that for Hints' feature implementation we don't necessarily need the template support.
This implies that we can skip the no2 and no3 items from the `Proposed implementation issues` list posted above.

The rational behind a such solution is that we can just re-use the k8s provider to emit specific mappings (hints specific ones) that would then be capable to populate the proper “templates” produced by the Fleet UI with the proper conventions.

Let me put some examples together to illustrate the point:

## Updated proposal 

#### "Templates" format

We take for granted that templates are constructed by Fleet UI, using the available packages' definitions, and are placed in the `elastic-agent.yml` as @ph mentioned above.
The difference is that those "templates" would not be listed in a different level but  can be listed under `inputs` level, while being annotated with the proper hints's based `conditions`. Having these inputs/templates populated by fleet UI then Agent can just leverage the ["dynamic variable resolution"](https://www.elastic.co/guide/en/fleet/master/dynamic-input-configuration.html) capabilities and the ["kubernetes provider"](https://www.elastic.co/guide/en/fleet/master/kubernetes-provider.html) to enable those inputs/templates if the proper hints are provided.

For simplicity we can add only the latest packages in the list of templates but we can simply extend this while using the proper conditions accordingly.

Find below a "template sample":

```yml
inputs:
...
- name: templates.d/redis/0.3.6
  type: redis/metrics
  use_output: default
  # condition: "${docker.hints.redis.version|kubernetes.hints.redis.version == "0.3.6"}"
  meta:
  package:
    name: redis
    version: 0.3.6
  data_stream:
  namespace: default
  streams:
  - data_stream:
      dataset: redis.info
      type: metrics
    metricsets:
      - info
    hosts:
      - "${docker.hints.redis.info.host|kubernetes.hints.redis.info.host|'127.0.0.1:6379'}"
    idle_timeout: 20s
    maxconn: 10
    network: tcp
    period: "${docker.hints.redis.info.period|kubernetes.hints.redis.info.period|'10s'}"
    condition: "${docker.hints.redis.info.enabled|kubernetes.hints.redis.info.enabled|true}"
   - data_stream:
       dataset: redis.key
       type: metrics
    metricsets:
      - key
    hosts:
      - "${docker.hints.redis.key.host|kubernetes.hints.redis.key.host|'127.0.0.1:6379'}"
    idle_timeout: 20s
    key.patterns:
      - limit: 20
        pattern: '*'
    maxconn: 10
    network: tcp
    period: "${docker.hints.redis.key.period|kubernetes.hints.redis.key.period|'10s'}"
    condition: "${docker.hints.redis.key.enabled|kubernetes.hints.redis.key.enabled|false}"
```

For now we can follow a simple approach and support only a few "hints" similarly to what we do in [Metricbeat/Filebeat](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover-hints.html#configuration-autodiscover-hints). In the above example I only leverage "period" and "host" hints but we can extend it as much as we think.

Note that the conditions per data_stream are suffixed with an `|true` if the data_stream is enabled by default or `|false` if the data_stream is disabled by default. This gives us the option to explicitly enable/disable data_streams using the hints or enabling just the integration implying to enable the default data_streams.


#### Hints' specific mappings

Having defined the "templates" as above we can now leverage the `kubernetes` provider in order to populate those with the respective values as settings and enable them.

So in the kubernetes provider we can check for specific annotations like `co.elastic.hints/*`.

A Redis Pod would be annotated like this:
```yaml
annotations:
  co.elastic.hints/package: redis
  co.elastic.hints/data_streams: info, key
  co.elastic.hints/host: '${kubernetes.pod.ip}:6379'
  co.elastic.hints/period: 1m
```

Note that the settings can also be data_stream specific if users want it:

```yaml
annotations:
  co.elastic.hints/package: redis
  co.elastic.hints/data_streams: info, key
  co.elastic.hints/host: '${kubernetes.pod.ip}:6379'
  co.elastic.hints/info.period: 1m
  co.elastic.hints/key.period: 10m
```

If settings are not data_stream specific then common settings will be used across the data_streams.


With the above annotations the `kubernetes` provider would produce the following mapping:

```json
{
  "kubernetes": {
    "hints": {
      "redis": {
        "info": {
          "enabled": true,
          "period": "1m",
          "host": "152.10.67.976:6379"
        },
        "key": {
          "enabled": true,
          "period": "10m",
          "host": "152.10.67.976:6379"
        }
      }
    }
  }
}
```

Note that `host` field can be populated by the kubernetes provider on the fly since the kubernetes provider already holds the Pod's metadata at the same place.


Having the above mapping we can emit this at https://github.com/elastic/elastic-agent/blob/a950518c38ed69b6ce3f7216b79b785079b013b1/internal/pkg/composable/providers/kubernetes/pod.go#L155 and this would be enough to enable the respective "template" provided in the standalone configuration.

The rendered input configuration will be the following:

```yml
inputs:
...
- name: templates.d/redis/0.3.6
  type: redis/metrics
  use_output: default
  meta:
  package:
    name: redis
    version: 0.3.6
  data_stream:
  namespace: default
  streams:
  - data_stream:
      dataset: redis.info
      type: metrics
    metricsets:
      - info
    hosts:
      - "152.10.67.976:6379"
    idle_timeout: 20s
    maxconn: 10
    network: tcp
    period: 1m
   - data_stream:
       dataset: redis.key
       type: metrics
    metricsets:
      - key
    hosts:
      - "152.10.67.976:6379"
    idle_timeout: 20s
    key.patterns:
      - limit: 20
        pattern: '*'
    maxconn: 10
    network: tcp
    period: 10m
```


#### Additional considerations

1. One major issue here is how we would install the assets like dashboards and pipelines but this is an issue that is not hints specific but is generic when one run standalone agent. Nevertheless, this is mentioned and documented accordingly at https://www.elastic.co/guide/en/fleet/current/install-standalone-elastic-agent.html and https://www.elastic.co/guide/en/fleet/current/install-uninstall-integration-assets.html#install-integration-assets.
2. We should also think about if another component should be responsible for constructing the "templates". For example `elastic-package` tool could provide this functionality which would allow advanced users to use it directly and construct the templates on their ends. This would also allow `elastic-agent` to re-use the tool and construct the templates at build time in order to include them in the final distrubution. However I'm leaning towards having Fleet UI to construct these templates and embed them in the `elastic-agent.yml` policy configuration. This makes things easier and would provide a seamless UX since users are already directed to download the standalone policy through Fleet UI. But we can discuss more about this if there are different opinions.


Since we are considering the templates' construction in Fleet UI, @jen-huang could you chime in and provide feedback on this and more specifically on `"Templates" construction by Fleet UI` part?
