### ISSUE TITLE
Heartbeat not setting origin field for project browser monitor

### ISSUE THREAD

**Issue by shahzad31** [elastic/beats#31870]
While testing https://github.com/elastic/beats/pull/31688
 i found out that for project monitor heartbeat should set source field, like ui or project value.

But it's not setting that field 

Test config 

```
heartbeat.monitors:
  - data_stream:
      namespace: default
    enabled: true
    id: check-if-input-placeholder-is-correct-testing-default
    schedule: '@every 2m'
    streams:
      - data_stream:
          dataset: browser
          type: synthetics
        enabled: true
        fields:
          config_id: 81a8e5b0-e737-11ec-b5c6-8f2db8039c9e
          monitor.project.id: testing
          monitor.project.name: testing
        fields_under_root: true
        id: check-if-input-placeholder-is-correct-testing-default
        ignore_https_errors: false
        name: check-if-input-placeholder-is-correct
        namespace: default
        origin: project
        original_space: default
        schedule: '@every 2m'
        params:
          url: http://localhost:5601/vzq/app/uptime
        source.project.content: UEsDBBQACAAIALZ5yFQAAAAAAAAAAAAAAAAfAAAAZXhhbXBsZXMvdG9kb3MvYmFzaWMuam91cm5leS50c8WQy27DIBBF9/mKEeoCS65Rt43S5zdUXRM8iWkwUGach6L8e7EdRW4bdduFWcD1uTNHKdBEyPfqjTCRqkNrvf3s0DidNqhq3Co6eG6QrSGFe91Gh6Q41IHUUpM11UfoksdDxTSzbQyJ4QjnuxKIMZaA+4iG4QSrFFoQT+g0ZeAELeaz8z9SmAbNBuwK2LJDsAQxIaFnUYI8QtRrLPOZdEtwKmDxAMcZDE1SON1504COMYd15huQlwiA3mnLA6FaBw5ypFRdcsU8B07DOZJ6L3mXYYarLBM8MTSoa0ywmKJvpGjuxMCC8+5yfB7TFeOeX4PnvJMsiorDC0oxOBWXOfrvtxLrY5dbnDbYBNc3Zz0mpJQ7/kPPdJKtdt1fqsbZf5oabiuPu9tewFVrY2SN/Myc7LLjbGtSLC4K3xvN4BFrAg6wRKiDx8fvTr8AUEsHCJMhsk5MAQAA8wIAAFBLAQItAxQACAAIALZ5yFSTIbJOTAEAAPMCAAAfAAAAAAAAAAAAIACkgQAAAABleGFtcGxlcy90b2Rvcy9iYXNpYy5qb3VybmV5LnRzUEsFBgAAAAABAAEATQAAAJkBAAAAAA==
        ssl.supported_protocols:
          - TLSv1.1
          - TLSv1.2
          - TLSv1.3
        ssl.verification_mode: full
        throttling:
          download: 5
          latency: 20
          upload: 3
        type: browser
    type: browser
```

Response document
```

{
  "_index": ".ds-synthetics-browser-default-2022.06.08-000014",
  "_id": "qqwwRIEBAC_vboWNVGmv",
  "_version": 1,
  "_score": 1,
  "_source": {
    "summary": {
      "up": 0,
      "down": 1
    },
    "agent": {
      "name": "16Elastic",
      "id": "61b20795-b177-48f8-b8d6-0e429df076d2",
      "type": "heartbeat",
      "ephemeral_id": "7965aed8-0c70-463c-bc2c-c63c67a5f708",
      "version": "8.4.0"
    },
    "synthetics": {
      "journey": {
        "name": "check if input placeholder is correct",
        "id": "check if input placeholder is correct",
        "tags": null
      },
      "type": "heartbeat/summary"
    },
    "monitor": {
      "duration": {
        "us": 546352
      },
      "name": "check-if-input-placeholder-is-correct - check if input placeholder is correct",
      "project": {
        "name": "testing",
        "id": "testing"
      },
      "timespan": {
        "lt": "2022-06-08T16:42:12.543Z",
        "gte": "2022-06-08T16:40:12.543Z"
      },
      "check_group": "a9de7f42-e749-11ec-b134-acde48001122",
      "id": "check-if-input-placeholder-is-correct-testing-default-check if input placeholder is correct",
      "type": "browser",
      "status": "down"
    },
    "error": {
      "message": "error executing step: TypeError: Cannot read properties of null (reading 'getAttribute')\n",
      "type": "io"
    },
    "url": {
      "path": "/vzq/app/uptime",
      "scheme": "http",
      "port": 5601,
      "domain": "localhost",
      "full": "http://localhost:5601/vzq/app/uptime"
    },
    "observer": {
      "hostname": "16Elastic",
      "ip": [
        "fe80::aede:48ff:fe00:1122",
        "fe80::412:4b86:a387:7e94",
        "2a02:8109:89c0:357c:8ba:8b1a:21e0:5f9c",
        "2a02:8109:89c0:357c:69c9:7423:8619:42da",
        "2a02:8109:89c0:357c:8692:814b:4096:27be",
        "192.168.0.32",
        "fe80::e8df:4aff:feb3:125e",
        "fe80::e8df:4aff:feb3:125e",
        "fe80::90ed:6912:42bc:3309",
        "fe80::a081:b16d:6020:5821",
        "fe80::ce81:b1c:bd2c:69e",
        "192.168.64.1",
        "fe80::8866:5aff:fe45:ed64",
        "fd9e:f098:670d:f731:846:2f32:4566:438d"
      ],
      "mac": [
        "52:04:20:01:e4:8d",
        "56:c7:19:4f:f8:87",
        "82:ce:40:24:e0:00",
        "82:ce:40:24:e0:01",
        "82:ce:40:24:e0:04",
        "82:ce:40:24:e0:05",
        "88:66:5a:54:da:40",
        "8a:66:5a:45:ed:64",
        "9e:9a:91:f5:51:a3",
        "aa:66:5a:54:da:40",
        "ac:de:48:00:11:22",
        "ea:df:4a:b3:12:5e"
      ]
    },
    "@timestamp": "2022-06-08T16:40:11.566Z",
    "ecs": {
      "version": "8.0.0"
    },
    "config_id": "81a8e5b0-e737-11ec-b5c6-8f2db8039c9e",
    "data_stream": {
      "namespace": "default",
      "type": "synthetics",
      "dataset": "browser"
    },
    "event": {
      "agent_id_status": "auth_metadata_missing",
      "ingested": "2022-06-08T16:40:27Z",
      "type": "heartbeat/summary",
      "dataset": "browser"
    }
  },
  "fields": {
    "monitor.status": [
      "down"
    ],
    "monitor.name.text": [
      "check-if-input-placeholder-is-correct - check if input placeholder is correct"
    ],
    "monitor.timespan": [
      {
        "lt": "2022-06-08T16:42:12.543Z",
        "gte": "2022-06-08T16:40:12.543Z"
      }
    ],
    "url.scheme": [
      "http"
    ],
    "monitor.id": [
      "check-if-input-placeholder-is-correct-testing-default-check if input placeholder is correct"
    ],
    "agent.type": [
      "heartbeat"
    ],
    "monitor.name": [
      "check-if-input-placeholder-is-correct - check if input placeholder is correct"
    ],
    "summary.up": [
      0
    ],
    "url.port": [
      5601
    ],
    "agent.name": [
      "16Elastic"
    ],
    "observer.mac": [
      "52:04:20:01:e4:8d",
      "56:c7:19:4f:f8:87",
      "82:ce:40:24:e0:00",
      "82:ce:40:24:e0:01",
      "82:ce:40:24:e0:04",
      "82:ce:40:24:e0:05",
      "88:66:5a:54:da:40",
      "8a:66:5a:45:ed:64",
      "9e:9a:91:f5:51:a3",
      "aa:66:5a:54:da:40",
      "ac:de:48:00:11:22",
      "ea:df:4a:b3:12:5e"
    ],
    "event.agent_id_status": [
      "auth_metadata_missing"
    ],
    "monitor.duration.us": [
      546352
    ],
    "url.full": [
      "http://localhost:5601/vzq/app/uptime"
    ],
    "monitor.type": [
      "browser"
    ],
    "synthetics.journey.id": [
      "check if input placeholder is correct"
    ],
    "monitor.project.id": [
      "testing"
    ],
    "url.full.keyword": [
      "http://localhost:5601/vzq/app/uptime"
    ],
    "data_stream.namespace": [
      "default"
    ],
    "synthetics.journey.name": [
      "check if input placeholder is correct"
    ],
    "data_stream.type": [
      "synthetics"
    ],
    "monitor.project.name": [
      "testing"
    ],
    "observer.hostname": [
      "16Elastic"
    ],
    "url.full.text": [
      "http://localhost:5601/vzq/app/uptime"
    ],
    "synthetics.type": [
      "heartbeat/summary"
    ],
    "summary.down": [
      1
    ],
    "event.ingested": [
      "2022-06-08T16:40:27.000Z"
    ],
    "url.path": [
      "/vzq/app/uptime"
    ],
    "error.type": [
      "io"
    ],
    "@timestamp": [
      "2022-06-08T16:40:11.566Z"
    ],
    "agent.id": [
      "61b20795-b177-48f8-b8d6-0e429df076d2"
    ],
    "config_id": [
      "81a8e5b0-e737-11ec-b5c6-8f2db8039c9e"
    ],
    "ecs.version": [
      "8.0.0"
    ],
    "monitor.id.text": [
      "check-if-input-placeholder-is-correct-testing-default-check if input placeholder is correct"
    ],
    "error.message": [
      "error executing step: TypeError: Cannot read properties of null (reading 'getAttribute')\n"
    ],
    "data_stream.dataset": [
      "browser"
    ],
    "event.type": [
      "heartbeat/summary"
    ],
    "monitor.check_group": [
      "a9de7f42-e749-11ec-b134-acde48001122"
    ],
    "url.domain": [
      "localhost"
    ],
    "agent.ephemeral_id": [
      "7965aed8-0c70-463c-bc2c-c63c67a5f708"
    ],
    "agent.version": [
      "8.4.0"
    ],
    "observer.ip": [
      "fe80::aede:48ff:fe00:1122",
      "fe80::412:4b86:a387:7e94",
      "2a02:8109:89c0:357c:8ba:8b1a:21e0:5f9c",
      "2a02:8109:89c0:357c:69c9:7423:8619:42da",
      "2a02:8109:89c0:357c:8692:814b:4096:27be",
      "192.168.0.32",
      "fe80::e8df:4aff:feb3:125e",
      "fe80::e8df:4aff:feb3:125e",
      "fe80::90ed:6912:42bc:3309",
      "fe80::a081:b16d:6020:5821",
      "fe80::ce81:b1c:bd2c:69e",
      "192.168.64.1",
      "fe80::8866:5aff:fe45:ed64",
      "fd9e:f098:670d:f731:846:2f32:4566:438d"
    ],
    "event.dataset": [
      "browser"
    ]
  }
}
```
