### ISSUE TITLE
Filebeat resends whole log files causing duplicated data

### ISSUE THREAD

**Issue by alytkowski** [elastic/beats#31924]
First case:
Filebeat resends the whole log files after restarting despite the log file stating that the registry file has been loaded successfully.
Second case:
Filebeat resends the whole log file, without restarting Filebeat, if the 24h period is exceeded (no logs during last 24h), then if a new log entry is saved to the file, Filebeat resends the whole log file.

For confirmed bugs, please report:
- Version: 8.1.1
- Operating System: RHEL 7.9
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-resends-log-files-after-restart/303924/5
- Steps to Reproduce: 
1.Run Filebeat
2.Insert some example log line to an existing log file from the config directory.
3.Restart FIlebeat
4.Result: all of the files with the modification date <24h are resent to the configured output.

1.Run Filebeat
2.Insert some example log line to an existing log file from the config directory.
3.Wait for the period set in "ignore_older" to pass and insert a new line to the log file after.
4.Result: all of the files with the modification date <24h are resent to the configured output.

-Snippet of configuration
`filebeat.inputs:
- type: filestream
  enabled: true
  paths:
   - /path/to/logs/*.log
  parsers:
  - multiline:
      type: pattern
      pattern: '^[0-9]{4}[[:space:]]+[A-Z]{1}[a-z]{2}[[:space:]]+[0-9]{2}'
      negate: True
      match: after
  name: tibco_int
  tags: ["tibcoint1-logs"]
  ignore_older: 24h`

**Comment by pierrepicaud** [comment]
@kvch Hi! Could you clarify a bit about `The fix is to save the size of the file as the last offset of the file to the registry and then return from the function`? thank you!

**Comment by MADxHAWK** [comment]
``Problem seems to still exist. 
Im sending cisco logfiles to logstash using filebeat 8.3.2 built 2022-07-06 on Ubuntu 20.04
Logfiles are send to logstash over and over again. 

Im receiving logs from Cisco Devices (Switches / ASA) by syslog-ng. There is a logfile for every day with the following folder structure
```
/var/log/remotelogs/switches
+ 10.0.0.1/ 
   + 10.0.0.1-2022.06.01.log
   + [...]
   + 10.0.0.1-2022.07.19.log
+ 10.0.0.2/
   + 10.0.0.2-2022.06.01.log
   + [...]
   + 10.0.0.2-2022.07.19.log
```

my filebeat config: 

```
config:
    modules:
      path: /etc/filebeat/modules.d/*.yml
      reload:
        enabled: false
  inputs:
  - enabled: true
    id: cisco-switch
    paths:
    - /var/log/remotelogs/switches/*/*.log
    tags:
    - cisco-switch
    type: filestream
  - enabled: true
    id: cisco-asa
    paths:
    - /var/log/remotelogs/ASA/*/*.log
    tags:
    - cisco-asa
    type: filestream
logging:
  files:
    keepfiles: 5
    name: filebeat
    path: /var/log/filebeat
    permissions: 48
  level: info
  to_files: true
output:
  logstash:
    hosts:
    - xx.xx.xx.103:5044
path:
  config: /etc/filebeat
  data: /var/lib/filebeat
  home: /usr/share/filebeat
  logs: /var/log/filebeat
processors:
- add_host_metadata:
    when:
      not:
        contains:
          tags: forwarded
- add_cloud_metadata: null
- add_docker_metadata: null
- add_kubernetes_metadata: null
setup:
  kibana: null
  template:
    settings:
      index:
        number_of_shards: 1

```

i have one logfile containing only 1 line 

`Aug  5 21:45:42 xxx.xxx.60.9 snmpv3 USM user, persisting snmpEngineBoots. Please Wait...`

This logentry was created befor the clock was syncronised, thats while the date is Aug. 05.

after just on day, i had 10 pages in elasticsearch with just this on single line 
![elastic](https://user-images.githubusercontent.com/8193408/179725194-90a4311e-4461-4d21-9609-85c34fa9206a.png)
