### ISSUE TITLE
Fix appenders documentation

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/beats#31932]
Appenders [documentation](https://www.elastic.co/guide/en/beats/filebeat/8.2/configuration-autodiscover-advanced.html#_appenders) is confusing and actually not working:

1. Example mentioned in documentation doesn't work:
```
providers:
    - type: kubernetes
      templates:
        - condition:
            contains:
              kubernetes.container.image: nginx
          config:
          - module: nginx
            access:
              input:
                type: container
                paths:
                - "/var/log/containers/*-${data.kubernetes.container.id}.log"
      appenders:
        - type: config
          config:
            fields:
              type: monitoring
``` 

note: the `appenders` config is the same as in [doc](https://www.elastic.co/guide/en/beats/filebeat/8.2/configuration-autodiscover-advanced.html#_appenders).
config above leads to the error:
```
2022-06-14T19:44:53.153Z	ERROR	[autodiscover]	autodiscover/autodiscover.go:235	Auto discover config check failed for config '{
  "access": {
    "input": {
      "paths": [
        "/var/log/containers/*-30e4e3a37627f2f21472581113a9d0f69ccb25d8608135c8615e83ac2886f8cd.log"
      ],
      "type": "container"
    }
  },
  "fields": {
    "type": "monitoring"
  },
  "module": "nginx"
}', won't start runner: could not create module registry for filesets: fileset nginx/fields is configured but doesn't exist
```

2.  Working configuration:
```
filebeat.autodiscover:
      providers:
      - type: kubernetes
        hints.enabled: true
        templates:
        - condition:
            contains:
              kubernetes.container.image: nginx
          config:
          - module: nginx
            access:
              input:
                type: container
                paths:
                - "/var/log/containers/*-${data.kubernetes.container.id}.log"
        appenders:
        - type: config
          config:
            access:
              input.fields:
                type: monitoring
```

not clear here:
a. what if I have templates defined for nginx and apache (both have `access` filesets) - the same `appender` is going to be applied to both?
b. How to apply the same configuration to all filesets?
