### ISSUE TITLE
Index selector in Elasticsearch output doesn't work with mapping keys containing uppercase characters

### ISSUE THREAD

**Issue by fdartayre** [elastic/beats#31994]
Filebeat 8.2.3 / 7.17.1

The [mappings](https://www.elastic.co/guide/en/beats/filebeat/8.2/elasticsearch-output.html#indices-option-es) dictionary in index selector rules of the Elasticsearch output doesn't work with entries containing uppercase characters. 

# Steps to Reproduce

With following config:
```yaml
filebeat.inputs:
- type: stdin

setup.ilm.enabled: false
setup.template.name: my-index
setup.template.pattern: my-index-*

output.elasticsearch:
  hosts: ["https://localhost:9200"]
  username: "elastic"
  password: "<password>"

  indices:
    - index: "%{[message]}"
      mappings:
        field: "my-index-lowercase"
        Field: "my-index-uppercase"
      default: "my-index-undefined"
```
These 2 events should be sent to `my-index-lowercase` and `my-index-uppercase`:
```bash
$ echo "field\nField" | ./filebeat -e
```
But second one is sent to `my-index-undefined`:
```
GET _cat/indices/my-index-*?v
```

```
health status index              uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   my-index-undefined 6O8mHn-fREWtV7fKOJhTJg   1   1          1            0      8.2kb          8.2kb
yellow open   my-index-lowercase j7HEsfUuShK0K5lpYmIBug   1   1          1            0      8.2kb          8.2kb
```
