### ISSUE TITLE
[metricbeat] Filtering CloudWatch metrics by tag does not work

### ISSUE THREAD

**Issue by tommyers-elastic** [elastic/beats#32189]
Steps to reproduce:

In this particular instance the issue is reproduced by collecting metrics from AWS API Gateway. Add a tag to the configuration as shown below:
 
<img width="1143" alt="Screenshot 2022-07-04 at 17 09 08" src="https://user-images.githubusercontent.com/106530686/177190196-9a163c42-b72b-44a1-9838-f50aa5c48809.png">

Now configure metricbeat as documented [here](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-aws-cloudwatch.html) to only report metrics with the given tag.

```
- module: aws
  period: 5m
  metricsets:
    - cloudwatch
  metrics:   
    - namespace: AWS/ApiGateway
      resource_type: apigateway
      tags:
        - key: MetricBeatEnabled
          value: true
 ```
 
Note that no filtering is applied.
 
Further investigation here shows that applying the tag one level higher in the config structure ([e.g.](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-aws.html#_example_configuration_5)) does cause it to get picked up in the cloudwatch apigateway namespace config, but causes all metrics to be filtered out (at least for api gateway).
