### ISSUE TITLE
Filebeat not modifying registry until new file states are written.

### ISSUE THREAD

**Issue by Airn5475** [elastic/beats#3220]
Forum: https://discuss.elastic.co/t/filebeat-config-for-files-that-are-never-updated-with-new-logs/69197
Filebeat Version 5.1.1 - Windows 7

**Steps to Reproduce:**
_Example A:_
1. Add a .json file to the directory
2. Wait for the `clean_inactive` time frame to pass
3. Check the registry and verify the first file entry is still there
4. Add a second .json file to the directory
5. Notice the first entry has finally been removed and the second added

_Example B:_
1. Add a .json file to the directory
2. Add a second .json file to the directory after a bit of time has passed
3. Wait until the `clean_inactive` time frame passes for the first file
4. Verify the registry is not updated
5. Add a new line to the second file
6. Notice that Filebeat updates the registry and removes the first file entry

**filebeat.yml**
```
- input_type: log
  paths:
  - C:/Elasticsearch5/elasticsearch/input/*.json
  close_inactive: 1m
  ignore_older: 2m
  scan_frequency: 10s 
  clean_inactive: 3m
```

Is there a reason the registry is not updated to remove the entry as soon as the `clean-inactive` time period has passed?
