### ISSUE TITLE
Improve documentation about the indices

### ISSUE THREAD

**Issue by YLombardi** [elastic/beats#3227]
The documentation about the indices configuration lack information about how to use the Rules settings (condition, mapping, default) : 
https://www.elastic.co/guide/en/beats/filebeat/5.0/elasticsearch-output.html#_indices

Some information was added in this topics on Filebeat forum : 
https://discuss.elastic.co/t/set-indices-based-on-a-field-value/69579

Adding this information in the documentation will probably help users who want to use this feature.

**Comment by urso** [comment]
also improve documentation on `index` itself. `index` supports format strings.

Often we see this pattern in filebeat:

```
filebeat.prospectors:
  - ...
    fields.name: X
  - ...
    fields.name: Y
  - ...
    fields.name: Z

output.elasticsearch:
  ...
  indices:
    - index: 'X-%{yyyy.MM.dd}'
      when.equal.fields.name: X
    - index: 'Y-%{yyyy.MM.dd}'
      when.equal.fields.name: Y
    - index: 'Z-%{yyyy.MM.dd}'
      when.equal.fields.name: Z
```

Using format strings this configuration can be simplified to:

```
filebeat.prospectors:
  - ...
    fields.name: X
  - ...
    fields.name: Y
  - ...
    fields.name: Z

output.elasticsearch:
  ...
  index: '${[fields.name]}-%{yyyy.MM.dd}'
```
