### ISSUE TITLE
Filebeat 8.3.2 (build 2022-07-06) keep sending already indexed logs

### ISSUE THREAD

**Issue by MADxHAWK** [elastic/beats#32401]
``Problem seems to still exist.
Im sending cisco logfiles to logstash using filebeat 8.3.2 built 2022-07-06 on Ubuntu 20.04
Logfiles are send to logstash over and over again.

Elasticsearch showed me a log for a switch with a single line over 400 times after just a few hours. 

System A: 
V-host (4 Cores @ 2.2 GHz with 8GB RAM) running Ubuntu 20.04 with syslog-ng (receiving logs from cisco devices) and Filebeat (sending it to the ELK-Stack on System B.

System B: 
v-Host (8 Cores @2.6GHz with 32GB RAM) running Ubuntu 20.04 with ELK-Stack 8.x
Systemload is permanently over 80% and i have a constant datastream of about 3-4mbit/s from Filebeat to ELK-Stack since filebeat keeps sending all data over and over again. 

Receiving logs from Cisco Devices (Switches / ASA) by syslog-ng on System A. 
syslog-ng creates a new log every day at 00:00 UTC with the following Folder structure

/var/log/remotelogs/switches
+ 10.0.0.1/ 
   + 10.0.0.1-2022.06.01.log
   + [...]
   + 10.0.0.1-2022.07.19.log
+ 10.0.0.2/
   + 10.0.0.2-2022.06.01.log
   + [...]
   + 10.0.0.2-2022.07.19.log
+ [...]

my filebeat config:

```
config:
    modules:
      path: /etc/filebeat/modules.d/*.yml
      reload:
        enabled: false
  inputs:
  - enabled: true
    id: cisco-switch
    paths:
    - /var/log/remotelogs/switches/*/*.log
    tags:
    - cisco-switch
    type: filestream
  - enabled: true
    id: cisco-asa
    paths:
    - /var/log/remotelogs/ASA/*/*.log
    tags:
    - cisco-asa
    type: filestream
logging:
  files:
    keepfiles: 5
    name: filebeat
    path: /var/log/filebeat
    permissions: 48
  level: info
  to_files: true
output:
  logstash:
    hosts:
    - xx.xx.xx.103:5044
path:
  config: /etc/filebeat
  data: /var/lib/filebeat
  home: /usr/share/filebeat
  logs: /var/log/filebeat
processors:
- add_host_metadata:
    when:
      not:
        contains:
          tags: forwarded
- add_cloud_metadata: null
- add_docker_metadata: null
- add_kubernetes_metadata: null
setup:
  kibana: null
  template:
    settings:
      index:
        number_of_shards: 1

```

i have one logfile containing only 1 line

`Aug 5 21:45:42 xxx.xxx.60.9 snmpv3 USM user, persisting snmpEngineBoots. Please Wait...`

This logentry was created befor the clock was syncronised, thats while the date is Aug. 05.

after just 2 hours, i had over 500 entries of this line in elasticsearch of this single line
![elastic](https://user-images.githubusercontent.com/8193408/179749760-eac0ed14-f786-4f68-b7f9-2e9d2c92b027.png)

Same happend with all other logfiles. After just 1 weekend the indices took about 600GB of diskspace while the total size of all logfiles are just about 150 MB.
So filebeat keept sendeing all logfiles from 200+ cisco devices over an over again and i have every logfile line multiple times.

My Logstash config to receive logs from filebeat on the loghost. 
Input
```
input {
  beats {
    port => 5044
  }
} 
```

Cisco switch
```
filter {
	if "cisco-switch" in [tags] and "pre-processed" not in [tags] {
		mutate {
			add_tag => [ "pre-processed", "Switch", "Cisco IOS/NXOS" ]
		}
		
		grok {
			patterns_dir => ["/etc/logstash/patterns/*"]
			match => [
				"message", "%{CISCOTIMESTAMP:received} %{SYSLOGHOST:device} %{CISCOTIMESTAMPTZ1:logtime}: %%{DATA:facility}-%{INT:severity_level}-%{CISCO_REASON:mnemonic}: %{GREEDYDATA:log_message}",
				"message", "%{CISCOTIMESTAMP:received} %{SYSLOGHOST:device} %{CISCOTIMESTAMPTZ2:logtime}: %%{DATA:facility}-%{INT:severity_level}-%{CISCO_REASON:mnemonic}: %{GREEDYDATA:log_message}",
				"message", "%{CISCOTIMESTAMP:received} %{SYSLOGHOST:device} %{TZ:logtime}: %%{DATA:facility}-%{INT:severity_level}-%{CISCO_REASON:mnemonic}: %{GREEDYDATA:log_message}",
				"message", "%{CISCOTIMESTAMP:received} %{SYSLOGHOST:device} %{CISCOTIMESTAMPTZ2:logtime}: %{DATA:facility}: %{GREEDYDATA:log_message}",
				"message", "%{CISCOTIMESTAMP:logtime} %{SYSLOGHOST:device} %%{DATA:facility}-%{INT:severity_level}-%{CISCO_REASON:mnemonic}: %{GREEDYDATA:log_message}",
				"message", "%{CISCOTIMESTAMP:logtime} %{SYSLOGHOST:device} %{GREEDYDATA:log_message}"
			]
		}
		
		syslog_pri { }
		
		date {
			match => [
				"logtime",
 
				# IOS
				"MMM  d YYYY HH:mm:ss.SSS ZZZ",
				"MMM  d YYYY HH:mm:ss ZZZ",
				"MMM  d YYYY HH:mm:ss.SSS",
				"MMM dd YYYY HH:mm:ss.SSS ZZZ",
				"MMM dd YYYY HH:mm:ss ZZZ",
				"MMM dd YYYY HH:mm:ss.SSS",
				 
				# Nexus
				"YYYY MMM  d HH:mm:ss.SSS ZZZ",
				"YYYY MMM  d HH:mm:ss ZZZ",
				"YYYY MMM  d HH:mm:ss.SSS",
				"YYYY MMM dd HH:mm:ss.SSS ZZZ",
				"YYYY MMM dd HH:mm:ss ZZZ",
				"YYYY MMM dd HH:mm:ss.SSS",
				
				# Logdate without year as timestamp
				"MMM dd HH:mm:ss",
				"MMM  d HH:mm:ss",
				 
				# Hail marry
				"ISO8601"
			]
			target => "@timestamp"
		}	
	
	}
} 
```

Cisco ASA
```
filter {
	if "cisco-asa" in [tags] and "pre-processed" not in [tags] {
		mutate {
			add_tag => [ "pre-processed", "ASA" ]
		}
		
		grok {
			patterns_dir => ["/etc/logstash/patterns/*"]
			match => [
				"message", "%{CISCOTIMESTAMP:logtime} %{SYSLOGHOST:device} %%{DATA:facility}-%{INT:severity_level-}-%{CISCO_REASON:mnemonic}: %{GREEDYDATA:log_message}"
			]
		}
		
		syslog_pri { }
		
		grok {
				patterns_dir => ["/etc/logstash/patterns/*"]
				match => [
					"log_message", "%{CISCOFW106001}",
					"log_message", "%{CISCOFW106006_106007_106010}",
					"log_message", "%{CISCOFW106014}",
					"log_message", "%{CISCOFW106015}",
					"log_message", "%{CISCOFW106021}",
					"log_message", "%{CISCOFW106023}",
					"log_message", "%{CISCOFW106100}",
					"log_message", "%{CISCOFW110002}",
					"log_message", "%{CISCOFW302010}",
					"log_message", "%{CISCOFW302013_302014_302015_302016}",
					"log_message", "%{CISCOFW302020_302021}",
					"log_message", "%{CISCOFW305011}",
					"log_message", "%{CISCOFW313001_313004_313008}",
					"log_message", "%{CISCOFW313005}",
					"log_message", "%{CISCOFW402117}",
					"log_message", "%{CISCOFW402119}",
					"log_message", "%{CISCOFW419001}",
					"log_message", "%{CISCOFW419002}",
					"log_message", "%{CISCOFW500004}",
					"log_message", "%{CISCOFW602303_602304}",
					"log_message", "%{CISCOFW710001_710002_710003_710005_710006}",
					"log_message", "%{CISCOFW713172}",
					"log_message", "%{CISCOFW733100}",
					"log_message", "%{WORD:action} %{WORD:protocol} %{CISCO_REASON:reason} from %{DATA:src_interface}:%{IP:src_ip}/%{INT:src_port} to %{DATA:dst_interface}:%{IP:dst_ip}/%{INT:dst_port}; %{GREEDYDATA:dnssec_validation}",
					"log_message", "%{CISCO_ACTION:action} %{WORD:protocol} %{CISCO_REASON:reason}.*(%{IP:src_ip}).*%{IP:dst_ip} on interface %{GREEDYDATA:interface}",
					"log_message", "Connection limit exceeded %{INT:inuse_connections}/%{INT:connection_limit} for input packet from %{IP:src_ip}/%{INT:src_port} to %{IP:dst_ip}/%{INT:dst_port} on interface %{GREEDYDATA:interface}",
					"log_message", "TCP Intercept %{DATA:threat_detection} to %{IP:ext_nat_ip}/%{INT:ext_nat_port}.*(%{IP:int_nat_ip}/%{INT:int_nat_port}).*Average rate of %{INT:syn_avg_rate} SYNs/sec exceeded the threshold of %{INT:syn_threshold}.#%{INT}",
					"log_message", "Embryonic connection limit exceeded %{INT:econns}/%{INT:limit} for %{WORD:direction} packet from %{IP:src_ip}/%{INT:src_port} to %{IP:dst_ip}/%{INT:dst_port} on interface %{GREEDYDATA:interface}"
				]
			}
	
		date {
			match => [
				"logtime",
 
				# IOS
				"MMM dd HH:mm:ss",
				"MMM  d HH:mm:ss",
				"MMM  d YYYY HH:mm:ss.SSS ZZZ",
				"MMM  d YYYY HH:mm:ss ZZZ",
				"MMM  d YYYY HH:mm:ss.SSS",
				"MMM dd YYYY HH:mm:ss.SSS ZZZ",
				"MMM dd YYYY HH:mm:ss ZZZ",
				"MMM dd YYYY HH:mm:ss.SSS",
				 
				# Nexus
				"YYYY MMM  d HH:mm:ss.SSS ZZZ",
				"YYYY MMM  d HH:mm:ss ZZZ",
				"YYYY MMM  d HH:mm:ss.SSS",
				"YYYY MMM dd HH:mm:ss.SSS ZZZ",
				"YYYY MMM dd HH:mm:ss ZZZ",
				"YYYY MMM dd HH:mm:ss.SSS",
				 
				# Hail marry
				"ISO8601"
			]
			target => "@timestamp"
		}	
	
	}
}

```

Output
```
output {
	if "cisco-switch" in [tags] {
		if "_grokparsefailure" in [tags] {
			file {
				path => "/var/log/remotelogs/grokfail/grokfail-logparse.log"
			}
		}
		else {
			elasticsearch {
				hosts => ["https://localhost:9200"]
				index => "cisco-switch-%{+yyyy.MM.dd}"
				user => "elastic"
				password => "*********"
				ssl => true
				ssl_certificate_verification => false
			}
		}
	}
	
	if "cisco-asa" in [tags] {
		elasticsearch {
			hosts => ["https://localhost:9200"]
			index => "cisco-asa-%{+yyyy.MM.dd}"
			user => "elastic"
			password => "*********"
			ssl => true
			ssl_certificate_verification => false
		}
	}
	 
}

```
