### ISSUE TITLE
slower speeds after backoff occurs in Filebeat 1.3

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/beats#3241]
Versions:

- Filebeat Version: 1.3
- Logstash Version 2.1.1
- Operating System: osx 

**The same test was run under Filebeat / Logstash 5.1.1, and the same effect was *not* observed, so whatever the problem was seems to have been resolved in the new version of the stack!**

Steps to reproduce:

1. Create a file a million lines in it called `/tmp/backpressure-test/input.log`

2. Set up Filebeat to read that file

```
filebeat:
  scan_frequency: 5s
  ignore_older: 24h
  tail_files: false

  prospectors:
    -
      paths:
        - /tmp/backpressure-test/input.log
      input_type: log

output:
  logstash:
    hosts: ["127.0.0.1:8089"]
    index: filebeat

logging:
  to_files: true
  files:
    path: ./logs
    name: filebeat
    rotateeverybytes: 10485760 # = 10MB
    keepfiles: 5
  level: debug
```

3.  Set up Logstash beats input with a ruby sleep delay to cause backpressure:

```
input {
  beats {
    port => 8089
  }
}

filter {
  ruby {
      code => "sleep 22222"
   }
}

output {
  stdout {
  }
}
```

4.  Run Logstash with
```
~jay/Workspace/logstash-5.1.1/bin/logstash -f beats-input.cfg >/tmp/tmp.log
```

5.  Watch output rate with 
```
tail -f /tmp/tmp.log | pv --line-mode --rate > /dev/null
```
At this point, you should see roughly 0 eps.     Watch the filebeat log file and wait for the backoff to go to *1m0s*.

6.  Restart Logstash with the filter commented out.

7.  Run the pv command again as above, and watch the output rate .  In my test, it increased to about 500 - 1k eps.

8.  Restart Filebeat.   Rate increases to between 2k-5k eps.
