### ISSUE TITLE
httpjson url.params to dynamically set keys/values

### ISSUE THREAD

**Issue by mdavis332** [elastic/beats#32474]
**Describe the enhancement:**

I've been trying to figure out a way to dynamically set url params and their values in the httpjson `url.params` url.Values object.

**Describe a specific use case for the enhancement or feature:**

Specifically for an elastic integration, I'd like a data_stream manifest.yml to have a section sort of like this:
```yaml
- name: filters
  type: yaml
  title: Optional REST API filters
  multi: false
  required: false
  show_user: false
  description: Optional REST API filters
```

Then, in the data_stream/\<stream\>/agent/stream/httpjson.yml.hbs file, I'd like to be able to iterate all the k/v's set there and assign them to `url.params`. Something like this I imagine:

```
{{#each filters}}
- set:
  target: url.params.{{@key}}
  value: {{this}}
{{/each}
```

It seems like this isn't supported today as best I can tell.
