### ISSUE TITLE
All JSON inside message property

### ISSUE THREAD

**Issue by itayzemah** [elastic/beats#32481]
- Version: 8.3.2
- Operating System: MacOS
- Discuss Forum URL:
I want to log my NodeJS logs which written to a file.
I have configure filebeat to read those files and pass them to my self-managed elasticsearch + kibana.
All the json content is written to the _message_ property.
I want to make this json to be in the root log so i can use the keys to search etc..
Here is my filebeat.inputs in filebeat.yml file

```
filebeat.inputs:
  - type: filestream
    id: my-filestream-id
    enabled: true
    paths:
      - /MY/PATH/TO/JSON/FILE/app.json
    json.keys_under_root: true
    json.overwrite_keys: true
    json.add_error_key: true
    json.expand_keys: true

```

If I chagne the _type_ to _log_ it will work
