### ISSUE TITLE
 Why the Packetbeat does not capture http traffic behind a reverse proxy ?

### ISSUE THREAD

**Issue by ismorodin** [elastic/beats#3254]
Why packetbeat does not capture http traffic behind a reverse proxy configured as upstream with tls, but if i call http service directly then the traffic successfully registers

**Comment by ismorodin** [comment]
**packetbeat.yml**
```
interfaces:
  device: any
protocols:
  http:
    ports: [8080]
    send_request: true
    send_response: true
```
