### ISSUE TITLE
Kibana ingest pipeline overwrites root fields set in Filebeat config

### ISSUE THREAD

**Issue by tobio** [elastic/beats#32665]
Version: 8.4.0 (looks like 8.2.0+ from GH history)

Steps to Reproduce: 
1. Enable the Kibana module
2. Add `fields` which overlap with fields exported in the Kibana logs (for 8.4.0 `service.*`)
3. Configure an Elasticsearch output
4. Ingest some Kibana logs

Example Kibana module config:
```yml
  - module: kibana
    log:
      enabled: true
      var.paths:
        - /app/logs/*.log
      input:
        close_timeout: '30m'
        fields:
          service.name: 'kibana'
          cloud.availability_zone: 'danger-zone'
        fields_under_root: true
```

Expected:

Fields defined in the config file are maintained in the final ES documents

Actual:

The [ingest pipeline copies](https://github.com/elastic/beats/blob/main/filebeat/module/kibana/log/ingest/pipeline-ecs.yml#L9-L13) `json.service` into the root, overwriting the configured fields. 

The module [config](https://github.com/elastic/beats/blob/main/filebeat/module/kibana/log/config/log.yml#L8) sets `json.keys_under_root: false` only to then copy the `json.*` fields into the root in an ingest pipeline. Would it not be better to just set `json.keys_under_root: true` in the module config and remove the script processor from the ingest pipeline?
