### ISSUE TITLE
Documented filebeat_writer permissions appear to be insufficient

### ISSUE THREAD

**Issue by SpencerLN** [elastic/beats#32765]
After upgrading several Filebeat instances from `7.17.5` to `8.3.3` we observed that several instances were unable to write to Elasticsearch due to the error:
```
{\"type\":\"security_exception\",\"reason\":\"action [indices:admin/mapping/auto_put] is unauthorized for user [filebeat_writer] with roles [filebeat_writer] on indices [.ds-filebeat-8.3.3-2022.08.18-000001], this action is granted by the index privileges [auto_configure,manage,write,all]\"}, dropping event!","service.name":"filebeat","ecs.version":"1.6.0"}
```

The `filebeat_writer` role is configured as described in the [Filebeat docs](https://www.elastic.co/guide/en/beats/filebeat/current/privileges-to-publish-events.html). We noticed the issue for the `azure`, `gcp`, and `aws` modules, but others may have also been impacted. 

For confirmed bugs, please report:
- Version: 8.3.3
- Operating System: Docker
- Discuss Forum URL: N/A
- Steps to Reproduce: 
  - Create a setup user as documented in https://www.elastic.co/guide/en/beats/filebeat/current/privileges-to-setup-beats.html
  - Create a filebeat_writer user as documented in https://www.elastic.co/guide/en/beats/filebeat/current/privileges-to-publish-events.html
  - Run Filebeat using the setup user to configure Elasticsearch appropriately
  - Run Filebeat using the filebeat_writer user

Config:
```
filebeat.modules:
- module: azure
  platformlogs:
    enabled: false
  activitylogs:
    enabled: true
    var:
      eventhub: "insights-activity-logs"
      consumer_group: "$Default"
      connection_string: "${AZURE_EVENTHUB_CONNECTION_STRING}"
      storage_account: "${AZURE_STORAGEACCOUNT_NAME}"
      storage_account_key: "${AZURE_STORAGEACCOUNT_KEY}"
  auditlogs:
    enabled: true
    var:
      eventhub: "insights-logs-auditlogs"
      consumer_group: "$Default"
      connection_string: "${AZURE_EVENTHUB_CONNECTION_STRING}"
      storage_account: "${AZURE_STORAGEACCOUNT_NAME}"
      storage_account_key: "${AZURE_STORAGEACCOUNT_KEY}"
  signinlogs:
    enabled: true
    var:
      eventhub: "insights-logs-signinlogs"
      consumer_group: "$Default"
      connection_string: "${AZURE_EVENTHUB_CONNECTION_STRING}"
      storage_account: "${AZURE_STORAGEACCOUNT_NAME}"
      storage_account_key: "${AZURE_STORAGEACCOUNT_KEY}"

# Templates are installed via separate setup role
setup.template.enabled: false

output.elasticsearch:
    hosts: 'https://${ELASTICSEARCH_ADDRESS}'
    username: ${ELASTICSEARCH_USERNAME}
    password: ${ELASTICSEARCH_PASSWORD}
    ssl:
      enabled: true
      supported_protocols: TLSv1.2
```
