### ISSUE TITLE
Filbeat stops shipping journald logs when encountered "failed to read message field: bad message" error

### ISSUE THREAD

**Issue by snjoetw** [elastic/beats#32782]
Filebeat seems to stop sending `journald` logs when encountered "failed to read message field: bad message" error

journald input:
```
- type: journald
  id: appdaemon_logs
  paths:
    - /var/log/journal
  include_matches.match:
    - syslog.priority=6
```

Logs:
```json
{
	"log.level": "error",
	"@timestamp": "2022-08-23T00:31:06.768-0700",
	"log.logger": "input.journald",
	"log.origin": {
		"file.name": "compat/compat.go",
		"file.line": 124
	},
	"message": "Input 'journald' failed with: input.go:130: input appdaemon_logs failed (id=appdaemon_logs)\n\tfailed to read message field: bad message",
	"service.name": "filebeat",
	"id": "appdaemon_logs",
	"ecs.version": "1.6.0"
}
```

Filebeat 8.3.3

Similar bug is also reported in Loki, not sure if the fix is similar or not:
Bug Report: https://github.com/grafana/loki/issues/2812
PR: https://github.com/grafana/loki/pull/2928

**Comment by jsoriano** [comment]
Could be related to the issues discussed in https://github.com/elastic/beats/issues/23627

**Comment by trauta** [comment]
I'm having the same problem with filebeat `filebeat version 7.17.8 (amd64)` on `Ubuntu 20.04.5 LTS`.

Here is the `journald` input config:

```
- type: journald
  id: syslog
  seek: cursor
  fields_under_root: false
  tags:
    - journald
    - syslog
```

From the filebeat log:
```
2023-01-11T12:19:13.844+0100	ERROR	[input.journald]	compat/compat.go:124	Input 'journald' failed with: input.go:130: input syslog failed (id=syslog)
	failed to iterate journal: bad message	{"id": "syslog"}
```

After this error message the journald input completey stops, there are now new journald events transmitted.
When restarting filebeat via systemd the missing journal events get transmitted without any problems.

This is a very irritating behavior.

Is it possible to implement a fix so that in case of such an error the 'bad mesage' is skipped and the input continues to parse the other messages?
