### ISSUE TITLE
[GCP Module] Region filtering support for cloudsql metricset

### ISSUE THREAD

**Issue by llermaly** [elastic/beats#32906]
**Describe the enhancement:**

Running the following configuration will throw an error because the filter looks for zone and clousdql exposes region.

```
- module: gcp
  metricsets:
    - metrics
  region: "us-"
  project_id: "<project id>"
  credentials_file_path: "/usr/share/metricbeat/config/pkey.json"
  period: 300s
  metrics:
    - service: cloudsql
      metric_types:
        - "database/cpu/utilization"
```
The error :

> Could not read time series value: [cloudsql.googleapis.com/database/cpu/utilization](http://cloudsql.googleapis.com/database/cpu/utilization): rpc error: code = InvalidArgument desc = The supplied filter does not specify a valid combination of metric and monitored resource descriptors. The query will not return any time series.

Removing the region property fixes the issue, but we can no longer filter by project regions.

**Describe a specific use case for the enhancement or feature:**

Filtering by project region.

From @endorama 

> To support filtering by region we need to add a dedicated gcp metricset and integration data stream.
