### ISSUE TITLE
Agent V2: Automatically add agent info to Elasticsearch headers

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#32993]
The current V1 code has a `Headers()` function that returns headerdata used by elasticsearch: https://github.com/elastic/elastic-agent/blob/689aee33c923be6183267c0e45596aa8d758e6eb/internal/pkg/agent/application/info/agent_info.go#L91

This in turn is used by the `InjectHeadersRule` to add elasticsearch headers. As far as I can tell, this headers data doesn't exist in the V2 client: https://github.com/elastic/elastic-agent-client/blob/main/pkg/client/client_v2.go

I'm not sure where this data comes from in V2, but we need to add it.

**Comment by cmacknz** [comment]
Moved to Beats, and created a shipper issue as a follow up.

**Comment by fearful-symmetry** [comment]
So, after digging around, I'm still not sure how this info will get to V2 clients. That header rule implementation that @cmacknz linked to pulls the headers from the `fleet.enc` file, which I assume is just the local encrypted copy of the main elastic-agent config. It looks like the `headers` map is a key under a root `agent` map, which on a default fleet install looks like this:
```
agent:
  download:
    source_uri: 'https://artifacts.elastic.co/downloads/'
  monitoring:
    enabled: true
    use_output: default
    namespace: default
    logs: true
    metrics: true
```

Not sure how to add a `headers` field via fleet, but I assume it should be there.

Also not sure how this info will get to V2 clients, since it's not part of the `inputs` or `outputs` config in agent. Unless I'm missing something, those headers will need to get shifted around to the output or we'll need a new metadata field somewhere.
