### ISSUE TITLE
[Metricbeat] Live reloading fails to reload keystore

### ISSUE THREAD

**Issue by peterpramb** [elastic/beats#33027]
**Beat version:**
`metricbeat version 7.17.6 (amd64), libbeat 7.17.6 [121b2ab96f118e6999f0a4be8e98827a809337db built 2022-08-23 12:50:12 +0000 UTC]`

**Description of the problem:**
When adding new credentials to the keystore and then adding a new module config file referencing the new credentials to a live-reloading enabled and running `Metricbeat` instance, it fails to reload:
```
2022-09-08T21:20:19.666+0200 ERROR [reload] cfgfile/list.go:69 Unable to hash given config: missing field accessing '0.password' (source:'/path/to/metricbeat/conf/modules/elasticsearch.yml')
```
It seems that live reloading fails to take the modified keystore into account, before actually loading the new module config. This makes live reloading currently unusable with external credentials.

Note that this issue is different from similar issues mentioning that error message, as the error only appears with live reloading. When the Metricbeat instance is restarted, the configuration loads properly.

**Steps to Reproduce:**

* `conf/metricbeat.yml`:
```yaml
metricbeat.config.modules:
  path: "${APP_CONF}/modules/*.yml"
  reload.enabled: true
  reload.period: 60s
```
* Run `Metricbeat` with `APP_CONF=/path/to/metricbeat/conf`
* Add secrets:
```bash
echo "someuser" | metricbeat keystore add --stdin monitoring.es.username
echo "somepass" | metricbeat keystore add --stdin monitoring.es.password
```
* `conf/modules/elasticsearch.yml`:
```yaml
- module: elasticsearch
  xpack.enabled: true

  hosts:
  - https://es-host-name:9200/

  username: "${monitoring.es.username}"
  password: "${monitoring.es.password}"
```
