### ISSUE TITLE
[Functionbeat] decode_json_fields fails to read `@timestamp` with microsecond precision

### ISSUE THREAD

**Issue by adrian-skybaker** [elastic/beats#33113]
For example given this input with a microsecond precision timestamp:

```json
{
    "message": "{\"@timestamp\":\"2022-09-18T21:29:53.291000+0000\"}"
}
```

And this decode processor:

```yaml
timestamp.precision: microsecond
processors:
  - decode_json_fields:
      fields: [ "message" ]
      target: ""
      add_error_key: true
      overwrite_keys: true
```

You get this error from lambda invocation (version 8.4.1 on linux x64):

```json
{
    "log.level": "error",
    "@timestamp": "2022-09-18T21:22:33.110Z",
    "log.logger": "jsonhelper",
    "log.origin": {
        "file.name": "jsontransform/jsonhelper.go",
        "file.line": 73
    },
    "message": "JSON: Won't overwrite @timestamp because of parsing error: failed to parse @timestamp, unknown format",
    "service.name": "functionbeat",
    "ecs.version": "1.6.0"
}
```

I couldn't see a way to workaround this. Providing the timestamp under a different name and using `copy` fails, as it tells me to first delete the existing `@timestamp` field, which the `delete_fields` processor doesn't permit. Working around using tiebreaker sort in kibana on `event.sequence` also hit bugs in Kibana (at least in the Discover view). End result is that it's surprisingly hard for us to get logs in order in elastic. 

Raised in the forum at https://discuss.elastic.co/t/functionbeat-unable-to-extract-microsecond-timestamp-using-decode-json-fields/314494.

**Comment by ajax-shmyrko-o** [comment]
It seems that Filebeat ignores the field in case its name is literally `@timestamp`.
Here is example of my log message:
```json
{
  "@timestamp": "2023-04-14T15:08:07.243Z",
  "message": "message goes here",
  "logger_name": "my.logger.name",
  "level": "INFO",
  "application": "app",
}
```
I'm using the following config to parse time:
```yaml
- type: filestream
  id: app-log
  paths:
    - /path/to/my/logs/*-json.log
  parsers:
    - ndjson:
        add_error_key: true
  processors:
    - timestamp:
        field: @timestamp
        layouts:
          - '2006-01-02T15:04:05.999Z'
        test:
          - '2023-04-16T13:15:30.123Z'
        ignore_missing: true
```
but Filebeat just ignores `@timestamp` and adds its own time.
I was trying to rename this field using [rename processor][1], but it didn't help.

Solved by renaming the field in the application code from `@timestamp` to `timestamp`, so this works now:
```
  processors:
    - timestamp:
        field: timestamp
```

[1]: https://www.elastic.co/guide/en/beats/filebeat/7.17/rename-fields.html
