### ISSUE TITLE
Disabled synthetics agent policy continue to run with heartbeat

### ISSUE THREAD

**Issue by shahzad31** [elastic/beats#33270]
It seems like even if an agent policy is disabled, it continue to run on heartbeat

example, notice `enabled: false` flag

```
  - id: >-
      synthetics/browser-synthetics-e1a84561-a0df-49a1-b61f-0c09e0e4f25f-elastic-agent-managed-ep-default
    name: My first monitor-Test private location-default
    revision: 3
    type: synthetics/browser
    use_output: default
    meta:
      package:
        name: synthetics
        version: 0.11.0
    data_stream:
      namespace: default
    package_policy_id: e1a84561-a0df-49a1-b61f-0c09e0e4f25f-elastic-agent-managed-ep-default
    streams:
      - id: >-
          synthetics/browser-browser.screenshot-e1a84561-a0df-49a1-b61f-0c09e0e4f25f-elastic-agent-managed-ep-default
        data_stream:
          dataset: browser.screenshot
          type: synthetics
        processors:
          - add_observer_metadata:
              geo:
                name: Fleet managed
          - add_fields:
              fields:
                monitor.fleet_managed: true
              target: ''
      - id: e1a84561-a0df-49a1-b61f-0c09e0e4f25f
        name: My first monitor
        type: browser
        enabled: false
        data_stream:
          dataset: browser
          type: synthetics
        schedule: '@every 1m'
        throttling: 5d/3u/20l
        source.inline.script: |-
          step('Go to https://www.google.com', async () => {
            await page.goto('https://www.google.com');
          });
        origin: ui
        __ui:
          script_source:
            file_name: ''
            is_generated_script: false
          is_tls_enabled: true
          is_zip_url_tls_enabled: false
        processors:
          - add_observer_metadata:
              geo:
                name: Test private location
          - add_fields:
              fields:
                config_id: e1a84561-a0df-49a1-b61f-0c09e0e4f25f
                monitor.fleet_managed: true
              target: ''
        timeout: null
        screenshots: 'on'
      - id: >-
          synthetics/browser-browser.network-e1a84561-a0df-49a1-b61f-0c09e0e4f25f-elastic-agent-managed-ep-default
        data_stream:
          dataset: browser.network
          type: synthetics
        processors:
          - add_observer_metadata:
              geo:
                name: Fleet managed
          - add_fields:
              fields:
                monitor.fleet_managed: true
              target: ''
```
