### ISSUE TITLE
[Metricbeat] Possible memory leak with autodiscover

### ISSUE THREAD

**Issue by eedugon** [elastic/beats#33307]
I have setup a Metricbeat 8.4.1 Deployment with `hints based autodiscover` in `scope: cluster` mode.
The beat is not handling any metric because I don't have any `metrics` related annotation in any pod, so it shouldn't be doing much.
The memory consumption of the beat grows and grows and after a few days it reaches the 1.5GB limit that I have configured, then it's OOMKilled and restarted.

<img width="993" alt="image" src="https://user-images.githubusercontent.com/25320357/195083468-1ad93686-45af-43b4-a726-46c0afdc11c6.png">

```
   State:          Running
      Started:      Mon, 10 Oct 2022 15:01:13 +0200
    Last State:     Terminated
      Reason:       OOMKilled
      Exit Code:    137
      Started:      Fri, 07 Oct 2022 08:48:04 +0200
      Finished:     Mon, 10 Oct 2022 15:01:12 +0200
```

The configuration of the Metricbeat is:
```
    http.enabled: true
    http.port: 5066
    http.host: 0.0.0.0
    metricbeat:
      autodiscover:
        providers:
        - type: kubernetes
          scope: cluster
          node: ${NODE_NAME}
          hints.enabled: true
    processors:
    - add_cloud_metadata: {}
    - add_host_metadata: {}
```

Environment details:
- K8s version 1.23.7, deployed by Rancher on VMs in Hetzner Cloud.
- Cluster with 20 nodes, about 915 pods (majority of them Jobs & CronJobs).

```
$ kubectl get pods -A | wc
     917    5704  118110
```

### TODOS

- [x]  It seems that the number of Pods is of importance here. We need to determine the environment details and have an easy way to reproduce this environment. Maybe we can make use of https://github.com/elastic/k8s-integration-infra
- [x]  It was reported in the past that narrowing down the targeted environment of Autodiscovery provider solves the issue. @eedugon we need to verify this too here :).
- [ ]  We need to replicate the issue with a smaller code snippet if we conclude that the issue lies in the k8s library. We can use https://github.com/gizas/clientgosimulator

**Comment by ChrsMark** [comment]
I'm going to have a look.
@eedugon since you already have the environment could you try the same experiment but without hints? I would suggest trying 2 things:

1) Define a simple template instead of hints
2) Leave just the provider to be enabled without hints or templates defined:
```
    metricbeat:
      autodiscover:
        providers:
        - type: kubernetes
          scope: cluster
          node: ${NODE_NAME}
```

This would help us mark out the various layers and isolate the problem in Beats' lib.

**Comment by ChrsMark** [comment]
I have been running experiments trying to reproduce the issue. Here is what I'm using for reference:

##### Script to collect heap profiles
```bash
#!/bin/bash
sleepTime=$((60*5))
for i in $(seq 1 1 100)
do
   echo "Getting heap for $i time"
   go tool pprof -png http://localhost:5066/debug/pprof/heap > heap${i}.png
   sleep $sleepTime
done
```

##### Metricbeat's config

```yml
http.enabled: true
http.port: 5066
http.host: 0.0.0.0
http.pprof.enabled: true
metricbeat:
  autodiscover:
    providers:
      - type: kubernetes
        scope: cluster
        node: kind-control-plane
        kube_config: /home/chrismark/.kube/config
        hints.enabled: true
```

The results I see do not provide any significant indication that there is a memory leak:

[simpleConfigHints.tar.gz](https://github.com/elastic/beats/files/9765206/simpleConfigHints.tar.gz)

##### Number of Pods on the cluster

```console
kubectl get pods -A | wc
     11      82    1153
```

#### Conclusions so far and next steps

1. It seems that the number of Pods is of importance here. 
2. @eedugon I would like to verify this with you and I would be interested into collecting the heap profiles in your reproduction environment. 
3. It was reported in the past that narrowing down the targeted environment of Autodiscovery provider solves the issue. @eedugon we need to verify this with your env too :). If that's the case it means that the number of Pods is a significant factor here.

**Comment by eedugon** [comment]
@gizas , I've updated the description to include some extra details that you asked for.

@ChrsMark : I'm running the suggested tests and preparing a report of `pprofs`. Note that there's no way to remove completely `hints` __and__ `conditional templates`. We need to have at least one for the provider to run, otherwise the beat won't start. I'm running the tests towards a deployment configured now without hints and with a simple `conditional template`:

```
    metricbeat:
      autodiscover:
        providers:
        - type: kubernetes
          scope: cluster
          node: ${NODE_NAME}
          hints.enabled: false
          templates:
            - condition:
                contains:
                  kubernetes.labels.app: "fake-label"
              config:
                - module: redis
                  hosts: "${data.host}:6379"
```

I agree that the number of pods or the metadata in general looks related with the issue.

About `narrowing down the targeted pods solving the issue` I will explore further, but that probably means that if autodiscover works only in a single namespace with a few resources it might not be enough to make the issue visible (although the memory leak could still exist there). I will need to do more tests about that. Will share the results here if I find something relevant.

**Comment by eedugon** [comment]
Here you have the results of the performed tests.
The following graph shows the last 4 days of 3 running pods:

<img width="846" alt="image" src="https://user-images.githubusercontent.com/25320357/196160009-e2c2a678-3f78-4c92-9248-90d4d1bb167d.png">

Green line: Metricbeat deployment with autodiscover, without hints and with a simple / fake conditional template.
Blue line: Metricebeat deployment without autodiscover and with a static simple input (it doesn't show any memory leak)
Red line: the `client-go` shared by @gizas . The memory usage there looks pretty stable.

Here you have a report of periodic `PNG pprof` reports:
- From metricbeat with autodiscover (1 screenshot every 2 hours):
[metricbeat-heap-pngs-3days.zip](https://github.com/elastic/beats/files/9799736/metricbeat-heap-pngs-3days.zip)

- From the `client-go` pod (1 screenshot every 30 minutes):
[heap-client-go-screenshots-1.zip](https://github.com/elastic/beats/files/9799759/heap-client-go-screenshots-1.zip)
[heap-client-go-screenshots-2.zip](https://github.com/elastic/beats/files/9799760/heap-client-go-screenshots-2.zip)

The metricbeat with autodiscover memory usage looks very suspicious. Considering the cluster has `CronJobs` that create a huge amount of periodic new pods, my suspicious is that the beat is probably not releasing / clearing properly from memory the information from pods / containers that don't exist anymore, hence the memory usage increases and increases. That would explain the problem.

**Comment by ChrsMark** [comment]
Thanks for the details here @eedugon , great work!

Regarding the results, by watching some random memory footprints I see that Metricbeat indead consumes a lot of memory in the "Watch" section. See for example:
![heap24](https://user-images.githubusercontent.com/11754898/196163696-09987354-5a42-4608-8832-c89899298503.png)


At the same time the `clientgosimulator` execution does not show a similar behavior.

Taking into consideration that the memory footprints show an increasing memory usage in functions of the library could it be that we consume the library in Metricbeat/Beats in way that leads to the memory leak? At the same time the `clientgosimulator` seems to not behave similarly so @gizas since you spent some time on the `clientgosimulator`  (https://github.com/gizas/clientgosimulator/blob/main/main.go) do you see this as a possible scenario? For example in Beats  at https://github.com/elastic/elastic-agent-autodiscover/blob/main/kubernetes/watcher.go#L110-L116 we consume some fields/objects like `Store`, is this something that we don't do in `clientgosimulator`?

**Comment by eedugon** [comment]
@ChrsMark , @gizas : I updated the description of my tests, as the beat that is __not showing__ the memory leak was actually beat __with autodiscover__ but pointing only to a namespace with a fixed set of ~40 pods (without `CronJobs`).

That means that the memory leak is not `just` with autodiscover. Depending on the received pods (and probably the nature of them) we are handling them in a way that ends up causing this leak. In my opinion all points to `CronJobs` and the nature of the created pods. My environment has 110 `CronJobs` that creates every day hundreds of pods, and my high level suspicious is that we might not be releasing them from our internal register of objects we are keeping track of.

**Comment by ChrsMark** [comment]
@eedugon what are the history limits of the Jobs/Cronjobs in your case?
https://kubernetes.io/docs/tasks/job/automated-tasks-with-cron-jobs/#jobs-history-limits

**Comment by ChrsMark** [comment]
I'm also running some tests on my end. I'm using Metricbeat 8.6.0-SNAPSHOT with a minimal autodiscovery configuration:
```yml
metricbeat.autodiscover:
  providers:
    - type: kubernetes
      node: ${NODE_NAME}
      hints.enabled: true
```

I'm deploying a significant  amount of Pods on the cluster but only some of them are actually getting into "running" state since my cluster is just a one-node kind cluster and the rest of them are failing to get scheduled. In any case this scenario still manages to trigger a memory usage increase in Metricbeat. To deploy the Pods I'm using the stress-test script from https://github.com/elastic/k8s-integration-infra#put-load-on-the-cluster running `./stress_test_k8s --kubeconfig=/home/chrismark/.kube/config --deployments=100 --namespaces=10 --podlabels=4 --podannotations=4`.

After some time when the memory has been stabilized again in a higher  usage I delete all the Pods running `./stress_test_k8s --delete`.

Here is what I capture:
![memoryLeakTest](https://user-images.githubusercontent.com/11754898/196632880-93a61592-9000-4423-b60f-0964525991c8.png)

As you can see after the deletion of the Pods the memory comes back to the normal levels which indicates that there is no memory leak related to the increased amount of Pods.

This makes me think that what we observe in the reported issue is having Metricbeat to monitor an increased number of Pods over time which never goes back to normal. This is why I was asking for the history limits of the Cronjobs at https://github.com/elastic/beats/issues/33307#issuecomment-1282474001.

So @eedugon can you clarify again what is the nature of the cluster you use and what is the number of the Pods with the time being? We are interested into see the number of Pods over time and not just the number of Pods at a specific point in the timeline. If the number of Pods is increasing then it makes sense that the data we are getting are more and more and this explains the memory usage increase.

This is just a theory open for discussion and at the same time I would be more than happy to have the proper details to replicate the issue on my side too :).
