### ISSUE TITLE
[Heartbeat] SSL Verification can't be disabled on 8.5 for states ES client

### ISSUE THREAD

**Issue by lucasfcosta** [elastic/beats#33354]
**Heartbeat Version:** 8.5.0-58624073-SNAPSHOT

# Summary

It's not possible to disable SSL verification for a particular output.

I caught this in the service even though the generated configurations have `ssl.verification_mode: none` in them.

```
{"log.level":"warn","@timestamp":"2022-10-14T11:43:12.937Z","log.origin":{"file.name":"monitorstate/tracker.go","file.line":86},"message":"could not load last externally recorded state, will retry again in 1140 milliseconds: %!w(*fmt.wrapError=&{error executing state search for 1665747653: x509: certificate is valid for localhost, elasticsearch, not host.docker.internal {0xc0003d1080 host.docker.internal}})","service.name":"heartbeat","ecs.version":"1.6.0"}
```

To reproduce this error you can simply use the config below:

```yaml
output.elasticsearch:
  allow_older_versions: true
  api_key: <KEY>
  hosts:
  - https://host.docker.internal:9200/
  ssl.verification_mode: none
```
