### ISSUE TITLE
Document include_fields filter usage

### ISSUE THREAD

**Issue by robertoschwald** [elastic/beats#3340]
For confirmed bugs, please report:
- Version:  5.1.1
- Operating System: CentOS 7
- Steps to Reproduce: 

Have very hard times to get Metricbeat mysql raw filtering working. The docs even state that "filters" are obsolete and will be replaced by a new mechanism. By which?
https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-metricbeat.html

It seems the Metricbeat filtering stuff is not documented for mysql raw field usage. We tried all sorts of patterns, but it simply does not work. 

In my case, I want to filter on Innodb buffer status, and already tried many patterns, but none of them worked: 

- mysql.status.raw.Innodb_buffer_pool_pages_flushed
- Innodb_buffer_pool_pages_flushed
- status.raw.Innodb_buffer_pool_pages_flushed
- raw.Innodb_buffer_pool_pages_flushed
- mysql.status.raw.Innodb.buffer.pool.pages.flushed

.. and so on.

I even didn't find any examples on GH in any project how to filter on mysql raw status values.

**Comment by madhavajay** [comment]
I cant get any of these examples working, with either filter, or processors, surely.... something is wrong. The only thing that seems to happen is sometimes when I use filter, the entire mysql tree of data just disappears but not because I have written drop_fields fields ['mysql'] but for no obvious reason.

Every time I try these I run -configtest and get a Config OK, and I see data in Kibana, its just never filtered! This is really annoying.

What we need is just to be able to completely blacklist a whole tree and then whitelist specific metrics we want because the mysql.status.raw is too big.

```yaml
    - module: mysql
      enabled: true
      period: 1s
      metricsets: ["status"]
      processors:
        - drop_fields:
            when:
              range:
                mysql.status.aborted.clients.gte: 0
            fields: ["mysql.status.aborted.clients"]
      raw: false
      hosts: ["tcp(127.0.0.1:3306)/"]
      username: root
      password: {{ mysql_root_password }}


    - module: mysql
      enabled: true
      period: 1s
      metricsets: ["status"]
      processors:
        - include_fields:
            fields: ["mysql.status"]
        - drop_fields:
            fields: ["mysql.status.aborted", "mysql.status.binlog"]
      raw: false
      hosts: ["tcp(127.0.0.1:3306)/"]
      username: root
      password: {{ mysql_root_password }}


    - module: mysql
      enabled: true
      period: 1s
      metricsets: ["status"]
      processors:
        - drop_fields:
            fields: ["beat", "metricset"]
      raw: false
      hosts: ["tcp(127.0.0.1:3306)/"]
      username: root
      password: {{ mysql_root_password }}


    - module: mysql
      enabled: true
      period: 1s
      metricsets: ["status"]
      processors:
        - drop_fields:
            fields: ["mysql.status.raw.Access_denied_errors"]
      raw: true
      hosts: ["tcp(127.0.0.1:3306)/"]
      username: root
      password: {{ mysql_root_password }}
```

**Comment by ruflin** [comment]
Inside the modules, you must be replacing `processors` with `filters`. Then it should be working.

**Comment by madhavajay** [comment]
As I said in my original post it doesnt work with either filter, or processors, I tried all that code with both. No cheese. Can someone show a working filter for mysql.status.raw? There are too many fields so it would be nice to blacklist ALL and then whitelist only a list of desired ones.

**Comment by ruflin** [comment]
@madhavajay As the filtering happens on the module level, the filter would have to be: `fields: ["status.raw.Access_denied_errors"]` (the mysql part was removed).

**Comment by madhavajay** [comment]
Looks like it only works with ["raw.Access_denied_errors"]. I also cannot get a combination of include_fields and drop_fields to whitelist fields rather than blacklist. However this is working for me if anyone else needs this.

This will blacklist every raw field except raw.Access_denied_errors as an example.
metricbeat.yml
```
    - module: mysql
      enabled: true
      period: 5s
      metricsets: ["status"]
      raw: true
      filters:
        # blacklist all raw fields and comment the ones to keep
        - drop_fields:
            fields:
            #- raw.Access_denied_errors
            - raw.Acl_column_grants
            - raw.Acl_database_grants
            - raw.Acl_function_grants
            - raw.Acl_procedure_grants
            - raw.Acl_proxy_users
            - raw.Acl_role_grants
            - raw.Acl_roles
            - raw.Acl_table_grants
            - raw.Acl_users
            - raw.Aria_pagecache_blocks_not_flushed
            - raw.Aria_pagecache_blocks_unused
            - raw.Aria_pagecache_blocks_used
            - raw.Aria_pagecache_read_requests
            - raw.Aria_pagecache_reads
            - raw.Aria_pagecache_write_requests
            - raw.Aria_pagecache_writes
            - raw.Aria_transaction_log_syncs
            - raw.Binlog_bytes_written
            - raw.Binlog_commits
            - raw.Binlog_group_commit_trigger_count
            - raw.Binlog_group_commit_trigger_lock_wait
            - raw.Binlog_group_commit_trigger_timeout
            - raw.Binlog_group_commits
            - raw.Binlog_snapshot_file
            - raw.Binlog_snapshot_position
            - raw.Binlog_stmt_cache_disk_use
            - raw.Binlog_stmt_cache_use
            - raw.Busy_time
            - raw.Com_admin_commands
            - raw.Com_alter_db
            - raw.Com_alter_db_upgrade
            - raw.Com_alter_event
            - raw.Com_alter_function
            - raw.Com_alter_procedure
            - raw.Com_alter_server
            - raw.Com_alter_table
            - raw.Com_alter_tablespace
            - raw.Com_analyze
            - raw.Com_assign_to_keycache
            - raw.Com_begin
            - raw.Com_binlog
            - raw.Com_call_procedure
            - raw.Com_change_db
            - raw.Com_change_master
            - raw.Com_check
            - raw.Com_checksum
            - raw.Com_commit
            - raw.Com_compound_sql
            - raw.Com_create_db
            - raw.Com_create_event
            - raw.Com_create_function
            - raw.Com_create_index
            - raw.Com_create_procedure
            - raw.Com_create_role
            - raw.Com_create_server
            - raw.Com_create_table
            - raw.Com_create_temporary_table
            - raw.Com_create_trigger
            - raw.Com_create_udf
            - raw.Com_create_user
            - raw.Com_create_view
            - raw.Com_dealloc_sql
            - raw.Com_delete
            - raw.Com_delete_multi
            - raw.Com_do
            - raw.Com_drop_db
            - raw.Com_drop_event
            - raw.Com_drop_function
            - raw.Com_drop_index
            - raw.Com_drop_procedure
            - raw.Com_drop_role
            - raw.Com_drop_server
            - raw.Com_drop_table
            - raw.Com_drop_temporary_table
            - raw.Com_drop_trigger
            - raw.Com_drop_user
            - raw.Com_drop_view
            - raw.Com_empty_query
            - raw.Com_execute_sql
            - raw.Com_flush
            - raw.Com_get_diagnostics
            - raw.Com_grant
            - raw.Com_grant_role
            - raw.Com_ha_close
            - raw.Com_ha_open
            - raw.Com_ha_read
            - raw.Com_help
            - raw.Com_insert
            - raw.Com_insert_select
            - raw.Com_install_plugin
            - raw.Com_kill
            - raw.Com_load
            - raw.Com_lock_tables
            - raw.Com_optimize
            - raw.Com_preload_keys
            - raw.Com_prepare_sql
            - raw.Com_purge
            - raw.Com_purge_before_date
            - raw.Com_release_savepoint
            - raw.Com_rename_table
            - raw.Com_rename_user
            - raw.Com_repair
            - raw.Com_replace
            - raw.Com_replace_select
            - raw.Com_reset
            - raw.Com_resignal
            - raw.Com_revoke
            - raw.Com_revoke_all
            - raw.Com_revoke_role
            - raw.Com_rollback
            - raw.Com_rollback_to_savepoint
            - raw.Com_savepoint
            - raw.Com_select
            - raw.Com_set_option
            - raw.Com_show_authors
            - raw.Com_show_binlog_events
            - raw.Com_show_binlogs
            - raw.Com_show_charsets
            - raw.Com_show_collations
            - raw.Com_show_contributors
            - raw.Com_show_create_db
            - raw.Com_show_create_event
            - raw.Com_show_create_func
            - raw.Com_show_create_proc
            - raw.Com_show_create_table
            - raw.Com_show_create_trigger
            - raw.Com_show_databases
            - raw.Com_show_engine_logs
            - raw.Com_show_engine_mutex
            - raw.Com_show_engine_status
            - raw.Com_show_errors
            - raw.Com_show_events
            - raw.Com_show_explain
            - raw.Com_show_fields
            - raw.Com_show_function_status
            - raw.Com_show_generic
            - raw.Com_show_grants
            - raw.Com_show_keys
            - raw.Com_show_master_status
            - raw.Com_show_open_tables
            - raw.Com_show_plugins
            - raw.Com_show_privileges
            - raw.Com_show_procedure_status
            - raw.Com_show_processlist
            - raw.Com_show_profile
            - raw.Com_show_profiles
            - raw.Com_show_relaylog_events
            - raw.Com_show_slave_hosts
            - raw.Com_show_slave_status
            - raw.Com_show_status
            - raw.Com_show_storage_engines
            - raw.Com_show_table_status
            - raw.Com_show_tables
            - raw.Com_show_triggers
            - raw.Com_show_variables
            - raw.Com_show_warnings
            - raw.Com_shutdown
            - raw.Com_signal
            - raw.Com_start_all_slaves
            - raw.Com_start_slave
            - raw.Com_stmt_close
            - raw.Com_stmt_execute
            - raw.Com_stmt_fetch
            - raw.Com_stmt_prepare
            - raw.Com_stmt_reprepare
            - raw.Com_stmt_reset
            - raw.Com_stmt_send_long_data
            - raw.Com_stop_all_slaves
            - raw.Com_stop_slave
            - raw.Com_truncate
            - raw.Com_uninstall_plugin
            - raw.Com_unlock_tables
            - raw.Com_update
            - raw.Com_update_multi
            - raw.Com_xa_commit
            - raw.Com_xa_end
            - raw.Com_xa_prepare
            - raw.Com_xa_recover
            - raw.Com_xa_rollback
            - raw.Com_xa_start
            - raw.Compression
            - raw.Connection_errors_accept
            - raw.Connection_errors_internal
            - raw.Connection_errors_max_connections
            - raw.Connection_errors_peer_address
            - raw.Connection_errors_select
            - raw.Connection_errors_tcpwrap
            - raw.Cpu_time
            - raw.Delete_scan
            - raw.Empty_queries
            - raw.Executed_events
            - raw.Executed_triggers
            - raw.Feature_delay_key_write
            - raw.Feature_dynamic_columns
            - raw.Feature_fulltext
            - raw.Feature_gis
            - raw.Feature_locale
            - raw.Feature_subquery
            - raw.Feature_timezone
            - raw.Feature_trigger
            - raw.Feature_xml
            - raw.Handler_commit
            - raw.Handler_delete
            - raw.Handler_discover
            - raw.Handler_external_lock
            - raw.Handler_icp_attempts
            - raw.Handler_icp_match
            - raw.Handler_mrr_init
            - raw.Handler_mrr_key_refills
            - raw.Handler_mrr_rowid_refills
            - raw.Handler_prepare
            - raw.Handler_read_first
            - raw.Handler_read_key
            - raw.Handler_read_last
            - raw.Handler_read_next
            - raw.Handler_read_prev
            - raw.Handler_read_retry
            - raw.Handler_read_rnd
            - raw.Handler_read_rnd_deleted
            - raw.Handler_read_rnd_next
            - raw.Handler_rollback
            - raw.Handler_savepoint
            - raw.Handler_savepoint_rollback
            - raw.Handler_tmp_update
            - raw.Handler_tmp_write
            - raw.Handler_update
            - raw.Handler_write
            - raw.Innodb_available_undo_logs
            - raw.Innodb_background_log_sync
            - raw.Innodb_buffer_pool_bytes_data
            - raw.Innodb_buffer_pool_bytes_dirty
            - raw.Innodb_buffer_pool_dump_status
            - raw.Innodb_buffer_pool_load_status
            - raw.Innodb_buffer_pool_pages_data
            - raw.Innodb_buffer_pool_pages_dirty
            - raw.Innodb_buffer_pool_pages_flushed
            - raw.Innodb_buffer_pool_pages_free
            - raw.Innodb_buffer_pool_pages_lru_flushed
            - raw.Innodb_buffer_pool_pages_made_not_young
            - raw.Innodb_buffer_pool_pages_made_young
            - raw.Innodb_buffer_pool_pages_misc
            - raw.Innodb_buffer_pool_pages_old
            - raw.Innodb_buffer_pool_pages_total
            - raw.Innodb_buffer_pool_read_ahead
            - raw.Innodb_buffer_pool_read_ahead_evicted
            - raw.Innodb_buffer_pool_read_ahead_rnd
            - raw.Innodb_buffer_pool_read_requests
            - raw.Innodb_buffer_pool_reads
            - raw.Innodb_buffer_pool_wait_free
            - raw.Innodb_buffer_pool_write_requests
            - raw.Innodb_checkpoint_age
            - raw.Innodb_checkpoint_max_age
            - raw.Innodb_data_fsyncs
            - raw.Innodb_data_pending_fsyncs
            - raw.Innodb_data_pending_reads
            - raw.Innodb_data_pending_writes
            - raw.Innodb_data_read
            - raw.Innodb_data_reads
            - raw.Innodb_data_writes
            - raw.Innodb_data_written
            - raw.Innodb_dblwr_pages_written
            - raw.Innodb_dblwr_writes
            - raw.Innodb_deadlocks
            - raw.Innodb_defragment_compression_failures
            - raw.Innodb_defragment_count
            - raw.Innodb_defragment_failures
            - raw.Innodb_encryption_num_key_requests
            - raw.Innodb_encryption_rotation_estimated_iops
            - raw.Innodb_encryption_rotation_pages_flushed
            - raw.Innodb_encryption_rotation_pages_modified
            - raw.Innodb_encryption_rotation_pages_read_from_cache
            - raw.Innodb_encryption_rotation_pages_read_from_disk
            - raw.Innodb_have_atomic_builtins
            - raw.Innodb_have_bzip2
            - raw.Innodb_have_lz4
            - raw.Innodb_have_lzma
            - raw.Innodb_have_lzo
            - raw.Innodb_have_snappy
            - raw.Innodb_history_list_length
            - raw.Innodb_ibuf_discarded_delete_marks
            - raw.Innodb_ibuf_discarded_deletes
            - raw.Innodb_ibuf_discarded_inserts
            - raw.Innodb_ibuf_free_list
            - raw.Innodb_ibuf_merged_delete_marks
            - raw.Innodb_ibuf_merged_deletes
            - raw.Innodb_ibuf_merged_inserts
            - raw.Innodb_ibuf_merges
            - raw.Innodb_ibuf_segment_size
            - raw.Innodb_ibuf_size
            - raw.Innodb_log_waits
            - raw.Innodb_log_write_requests
            - raw.Innodb_log_writes
            - raw.Innodb_lsn_current
            - raw.Innodb_lsn_flushed
            - raw.Innodb_lsn_last_checkpoint
            - raw.Innodb_master_thread_active_loops
            - raw.Innodb_master_thread_idle_loops
            - raw.Innodb_max_trx_id
            - raw.Innodb_mem_adaptive_hash
            - raw.Innodb_mem_dictionary
            - raw.Innodb_mem_total
            - raw.Innodb_mutex_os_waits
            - raw.Innodb_mutex_spin_rounds
            - raw.Innodb_mutex_spin_waits
            - raw.Innodb_num_index_pages_written
            - raw.Innodb_num_non_index_pages_written
            - raw.Innodb_num_page_compressed_trim_op
            - raw.Innodb_num_page_compressed_trim_op_saved
            - raw.Innodb_num_pages_decrypted
            - raw.Innodb_num_pages_encrypted
            - raw.Innodb_num_pages_page_compressed
            - raw.Innodb_num_pages_page_compression_error
            - raw.Innodb_num_pages_page_decompressed
            - raw.Innodb_oldest_view_low_limit_trx_id
            - raw.Innodb_onlineddl_pct_progress
            - raw.Innodb_onlineddl_rowlog_pct_used
            - raw.Innodb_onlineddl_rowlog_rows
            - raw.Innodb_os_log_fsyncs
            - raw.Innodb_os_log_pending_fsyncs
            - raw.Innodb_os_log_pending_writes
            - raw.Innodb_os_log_written
            - raw.Innodb_page_compression_saved
            - raw.Innodb_page_compression_trim_sect1024
            - raw.Innodb_page_compression_trim_sect16384
            - raw.Innodb_page_compression_trim_sect2048
            - raw.Innodb_page_compression_trim_sect32768
            - raw.Innodb_page_compression_trim_sect4096
            - raw.Innodb_page_compression_trim_sect512
            - raw.Innodb_page_compression_trim_sect8192
            - raw.Innodb_page_size
            - raw.Innodb_pages0_read
            - raw.Innodb_pages_created
            - raw.Innodb_pages_read
            - raw.Innodb_pages_written
            - raw.Innodb_purge_trx_id
            - raw.Innodb_purge_undo_no
            - raw.Innodb_read_views_memory
            - raw.Innodb_row_lock_current_waits
            - raw.Innodb_row_lock_time
            - raw.Innodb_row_lock_time_avg
            - raw.Innodb_row_lock_time_max
            - raw.Innodb_row_lock_waits
            - raw.Innodb_rows_deleted
            - raw.Innodb_rows_inserted
            - raw.Innodb_rows_read
            - raw.Innodb_rows_updated
            - raw.Innodb_s_lock_os_waits
            - raw.Innodb_s_lock_spin_rounds
            - raw.Innodb_s_lock_spin_waits
            - raw.Innodb_scrub_background_page_reorganizations
            - raw.Innodb_scrub_background_page_split_failures_missing_index
            - raw.Innodb_scrub_background_page_split_failures_out_of_filespace
            - raw.Innodb_scrub_background_page_split_failures_underflow
            - raw.Innodb_scrub_background_page_split_failures_unknown
            - raw.Innodb_scrub_background_page_splits
            - raw.Innodb_secondary_index_triggered_cluster_reads
            - raw.Innodb_secondary_index_triggered_cluster_reads_avoided
            - raw.Innodb_system_rows_deleted
            - raw.Innodb_system_rows_inserted
            - raw.Innodb_system_rows_read
            - raw.Innodb_system_rows_updated
            - raw.Innodb_truncated_status_writes
            - raw.Innodb_x_lock_os_waits
            - raw.Innodb_x_lock_spin_rounds
            - raw.Innodb_x_lock_spin_waits
            - raw.Key_blocks_not_flushed
            - raw.Key_blocks_unused
            - raw.Key_blocks_used
            - raw.Key_blocks_warm
            - raw.Key_read_requests
            - raw.Key_reads
            - raw.Key_write_requests
            - raw.Key_writes
            - raw.Last_query_cost
            - raw.Master_gtid_wait_count
            - raw.Master_gtid_wait_time
            - raw.Master_gtid_wait_timeouts
            - raw.Max_statement_time_exceeded
            - raw.Memory_used
            - raw.Not_flushed_delayed_rows
            - raw.Open_table_definitions
            - raw.Opened_files
            - raw.Opened_plugin_libraries
            - raw.Opened_table_definitions
            - raw.Opened_views
            - raw.Performance_schema_accounts_lost
            - raw.Performance_schema_cond_classes_lost
            - raw.Performance_schema_cond_instances_lost
            - raw.Performance_schema_digest_lost
            - raw.Performance_schema_file_classes_lost
            - raw.Performance_schema_file_handles_lost
            - raw.Performance_schema_file_instances_lost
            - raw.Performance_schema_hosts_lost
            - raw.Performance_schema_locker_lost
            - raw.Performance_schema_mutex_classes_lost
            - raw.Performance_schema_mutex_instances_lost
            - raw.Performance_schema_rwlock_classes_lost
            - raw.Performance_schema_rwlock_instances_lost
            - raw.Performance_schema_session_connect_attrs_lost
            - raw.Performance_schema_socket_classes_lost
            - raw.Performance_schema_socket_instances_lost
            - raw.Performance_schema_stage_classes_lost
            - raw.Performance_schema_statement_classes_lost
            - raw.Performance_schema_table_handles_lost
            - raw.Performance_schema_table_instances_lost
            - raw.Performance_schema_thread_classes_lost
            - raw.Performance_schema_thread_instances_lost
            - raw.Performance_schema_users_lost
            - raw.Prepared_stmt_count
            - raw.Qcache_free_blocks
            - raw.Qcache_free_memory
            - raw.Qcache_hits
            - raw.Qcache_inserts
            - raw.Qcache_lowmem_prunes
            - raw.Qcache_not_cached
            - raw.Qcache_queries_in_cache
            - raw.Qcache_total_blocks
            - raw.Queries
            - raw.Questions
            - raw.Rows_read
            - raw.Rows_sent
            - raw.Rows_tmp_read
            - raw.Rpl_status
            - raw.Select_full_join
            - raw.Select_full_range_join
            - raw.Select_range
            - raw.Select_range_check
            - raw.Select_scan
            - raw.Slave_connections
            - raw.Slave_heartbeat_period
            - raw.Slave_open_temp_tables
            - raw.Slave_received_heartbeats
            - raw.Slave_retried_transactions
            - raw.Slave_running
            - raw.Slave_skipped_errors
            - raw.Slaves_connected
            - raw.Slaves_running
            - raw.Slow_launch_threads
            - raw.Slow_queries
            - raw.Sort_merge_passes
            - raw.Sort_priority_queue_sorts
            - raw.Sort_range
            - raw.Sort_rows
            - raw.Sort_scan
            - raw.Ssl_accept_renegotiates
            - raw.Ssl_accepts
            - raw.Ssl_callback_cache_hits
            - raw.Ssl_cipher
            - raw.Ssl_cipher_list
            - raw.Ssl_client_connects
            - raw.Ssl_connect_renegotiates
            - raw.Ssl_ctx_verify_depth
            - raw.Ssl_ctx_verify_mode
            - raw.Ssl_default_timeout
            - raw.Ssl_finished_accepts
            - raw.Ssl_finished_connects
            - raw.Ssl_server_not_after
            - raw.Ssl_server_not_before
            - raw.Ssl_session_cache_hits
            - raw.Ssl_session_cache_misses
            - raw.Ssl_session_cache_mode
            - raw.Ssl_session_cache_overflows
            - raw.Ssl_session_cache_size
            - raw.Ssl_session_cache_timeouts
            - raw.Ssl_sessions_reused
            - raw.Ssl_used_session_cache_entries
            - raw.Ssl_verify_depth
            - raw.Ssl_verify_mode
            - raw.Ssl_version
            - raw.Subquery_cache_hit
            - raw.Subquery_cache_miss
            - raw.Syncs
            - raw.Table_locks_immediate
            - raw.Table_locks_waited
            - raw.Tc_log_max_pages_used
            - raw.Tc_log_page_size
            - raw.Tc_log_page_waits
            - raw.Threadpool_idle_threads
            - raw.Threadpool_threads
            - raw.Update_scan
            - raw.Uptime
            - raw.Uptime_since_flush_status
            - raw.wsrep_cluster_conf_id
            - raw.wsrep_cluster_size
            - raw.wsrep_cluster_state_uuid
            - raw.wsrep_cluster_status
            - raw.wsrep_connected
            - raw.wsrep_local_bf_aborts
            - raw.wsrep_local_index
            - raw.wsrep_provider_name
            - raw.wsrep_provider_vendor
            - raw.wsrep_provider_version
            - raw.wsrep_ready
            - raw.wsrep_thread_count
      hosts: ["tcp(127.0.0.1:3306)/"]
      username: root
      password: {{ mysql_root_password }}
```

**Comment by ruflin** [comment]
@madhavajay You are right, the filtering happens on the metricset level which to be honest has some issues if multiple metricsets are used. Sorry for the false information above.

I did a quick test with combining include_fields and drop_fields which seemed to work:

```
- module: system
  metricsets:
    - cpu
  filters:
    - include_fields:
        fields: ["idle"]
    - drop_fields:
        fields: ["idle.pct"]
  cpu_ticks: true
```
The result is that I have only `cpu.idle.ticks` in my event. What combinations did you try and didn't work?
