### ISSUE TITLE
Provide examples of include_annotations and include_labels at the provider level

### ISSUE THREAD

**Issue by asmith-elastic** [elastic/beats#33446]
The filebeat auto-discover documentation provides examples of how to leverage `include_labels` and `include_annotations` at a node and namespace level by leveraging `add_resource_metadata`. Below is the example that is provided in the current documentation: 

```yaml
      add_resource_metadata:
        namespace:
          include_labels: ["namespacelabel1"]
        node:
          include_labels: ["nodelabel2"]
          include_annotations: ["nodeannotation1"]
        deployment: false
        cronjob: false
```
Ref: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover.html#_kubernetes

The documentation mentions the following statements indicating that `include_annotations` and `include_labels` can be applied at the provider level:

> If the include_annotations config is added to the provider config, then the list of annotations present in the config are added to the event.
> If the include_labels config is added to the provider config, then the list of labels present in the config will be added to the event.

When applying this at the provider level, one will need to omit the `node` or `namespace` attributes from the previous example. However, this isn't very clear in the current documentation as there are no examples of the syntax being used at a provider level. I would recommend our documentation is updated to provide additional examples similar to the following:

```yaml

providers:
  - type: kubernetes
    include_annotations:
      - nodeannotation1
    include_labels:
      - nodelabel1
```

I would also recommend that we explicitly note that wildcards are not supported at the provider level (similar to the note provided within `add_resource_metadata `).
