### ISSUE TITLE
Error with snappy in metricbeat like prometheus remote_write

### ISSUE THREAD

**Issue by b2ronn** [elastic/beats#33465]
installed elastic stack. added prometheus integration.
added prometheus policy for the agent. enabled remote_write

![image](https://user-images.githubusercontent.com/20790707/198027845-3aab5552-cfd7-4295-a00d-18c97d9c6b1f.png)
$elastic-agent inspect
```
- data_stream:
    namespace: default
  id: prometheus/metrics-prometheus-365cf203-ce75-44ab-9475-799fcff70938
  meta:
    package:
      name: prometheus
      version: 0.13.0
  name: prometheus-vmagent-apps
  revision: 4
  streams:
  - data_stream:
      dataset: prometheus.remote_write
      type: metrics
    host: 0.0.0.0
    id: prometheus/metrics-prometheus.remote_write-365cf203-ce75-44ab-9475-799fcff70938
    metricsets:
    - remote_write
    port: 9201
    rate_counters: true
    ssl.certificate: /etc/pki/server/cert.pem
    ssl.enabled: false
    ssl.key: /etc/pki/server/cert.key
    types_patterns.exclude: null
    types_patterns.include: null
    use_types: true
  type: prometheus/metrics
  use_output: default
```
I'm trying to send data from a vmagent and I'm getting an error.
```
{"log.level":"error","@timestamp":"2022-10-26T12:13:55.545Z","log.logger":"prometheus.remote_write","log.origin":{"file.name":"remote_write/remote_write.go","file.line":161},"message":"Decode error snappy: corrupt input","service.name":"metricbeat","ecs.version":"1.6.0"}
```
also
$curl -k --header "Content-Type: application/json" --request POST --data '{"labels":{"__name__":"foo"},"samples":[[1577836800000, 100]]}' "http://localhost:9201/write"
```
{"log.level":"error","@timestamp":"2022-10-26T12:35:57.19Z","log.logger":"prometheus.remote_write","log.origin":{"file.name":"remote_write/remote_write.go","file.line":161},"message":"Decode error snappy: corrupt input","service.name":"metricbeat","ecs.version":"1.6.0"}
```
$curl -k --header "Content-Type: application/json" --header "Content-Encoding: snappy" --request POST --data-binary "@data.sz" "http://localhost:9201/write"
```
{"log.level":"error","@timestamp":"2022-10-26T12:35:59.735Z","log.logger":"prometheus.remote_write","log.origin":{"file.name":"remote_write/remote_write.go","file.line":161},"message":"Decode error snappy: corrupt input","service.name":"metricbeat","ecs.version":"1.6.0"}
```
no matter which endpoint I specify("prometheus", "remote_write", "/api/v1/write"), I still get a snappy error
I see in the code
```
	reqBuf, err := snappy.Decode(nil, compressed)
```
is it mandatory to send this compressed?
What should I do if I need to send uncompressed data?

eck: 2.4.0
elastic/kibana/elastic-agent - 8.4.3
