### ISSUE TITLE
Filebeat does not read files when executed with `--once`

### ISSUE THREAD

**Issue by rdner** [elastic/beats#33718]
For example using this configuration:

```yaml
filebeat.inputs:
  - type: filestream
    id: my-filestream-id
    enabled: true
    paths:
      - "/your/path/test.ndjson"
    parsers:
      - ndjson:
          target: ""
          add_error_key: true
logging:
  level: debug

output.console:
  enabled: true
```

Outputs events to the console when executed with:

```sh
./filebeat run -e -c config.yml
```

But Filebeat shuts down before trying to read files when executed with `--once` and the same config:

```sh
./filebeat run --once -e -c config.yml
```

Looks like it's not waiting until the harvester closes the file like it's supposed to.
