### ISSUE TITLE
`include_fields` processor causes duplicate `@timestamp` field

### ISSUE THREAD

**Issue by mbrancato** [elastic/beats#33733]
The documentation says this about the `@timestamp` field and `include_fields` processor:
```
The @timestamp and type fields are always exported, even if they are not defined in the include_fields list.
```

But if `@timestamp` is in the list, it causes a duplicate field if `@timestamp` already exists.

The following simple `filebeat.yml` config can be used to reproduce this error.

```yaml
filebeat.inputs:
- type: log
  paths:
    - /test/input.json

processors:
  - include_fields:
      fields: ["@timestamp", "message"]

output.console.pretty: true
```

Example output:

```json
{
  "@timestamp": "2022-11-20T19:47:10.350Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "8.5.0"
  },
  "@timestamp": "2022-11-20T19:47:10.350Z",
  "message": "{\"test\": \"foo\"}"
}
```

Attempting to output to Elasticsearch will result in an error with the reason `Duplicate field '@timestamp'`.

May relate to #7351.
