### ISSUE TITLE
[Azure] Migrate the azure-eventhub input to the new Azure Event Hubs Client Module for Go

### ISSUE THREAD

**Issue by zmoog** [elastic/beats#33815]
## What

Azure is introducing a new BETA release of the [Azure Event Hubs Client Module for Go](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/README.md) aligned with the next-generation Azure SDK. 

They are also transitioning the Event Hub client from the independent repo [azure/azure-event-hubs-go](https://github.com/Azure/azure-event-hubs-go) to the new monorepo [azure/azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/README.md) that hosts all Azure SDK clients for Go.

## Why

Once released as GA, the new Event Hub package will be the go-to client to connect to Event Hub.

It has a new `azeventhubs.Processor` that replaces the `EventProcessorHost`. The new [Processor](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs#Processor) looks like an improved solution over the current one.

For authentication, it leverage Azure Identity credentials from [azidentity](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/azidentity#section-readme). More authentication options are available. 

## Requirements

The new Azure Event Hubs Client Module for Go requires Go 1.18 (now available on both Beats 7.x and 8.x).

## Resources:

- [Azure Event Hubs Client Module for Go](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/README.md) (BETA release)
- [Migration Guide](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/migrationguide.md)

```[tasklist]
### Tasks
- [ ] https://github.com/elastic/beats/issues/36377
- [ ] https://github.com/elastic/beats/pull/39511
- [ ] https://github.com/elastic/beats/pull/39796
```

**Comment by JulGor-elastic** [comment]
One of my customers (Repsol) is asking about integration with Azure AD when setting up integrations with Azure data sources instead of using shared secret values that may change or may be difficult to override over time. 
So integration with AAD should make it easier to manage the identities that are used to configure the different data integrations

**Comment by zmoog** [comment]
New [0.4.0 (2023-01-10) beta release](https://github.com/Azure/azure-sdk-for-go/blob/sdk/messaging/azeventhubs/v0.4.0/sdk/messaging/azeventhubs/CHANGELOG.md) for the Azure Event Hubs Go SDK.

**Comment by Martin-Kemp** [comment]
Just mentioning that this would be very useful to us. It's currently blocking us from using Beats with Eventhubs.

**Comment by zmoog** [comment]
Microsoft marked the `github.com/Azure/azure-event-hubs-go/v3` package as deprecated in the [v3.6.1](https://github.com/Azure/azure-event-hubs-go/releases/tag/v3.6.1) release.

**Comment by P1llus** [comment]
I think if there are plans to implement a "v2" of the input, either by running the old and new one side-by-side for a while, behind a config flag for example (we did this for httpjson), then there could be certain other improvements that could be implemented as well:

1. Currently we do not expose or utilize any configurations that is supported by the SDK client in terms of tweaking throughput. Unsure what this new library exposes, but things like message counts, sizes etc would be a good start.
2. S3, GCS and ABS and maybe other inputs supports the concepts of "worker counts". This has 1 single go-routine that fetches the list/available new messages, and sends each unprocessed event to a "worker" go-routine, that processes it and updates its state if necessary. This allows certain scaleability vertically and not only horizontally.

**Comment by Martin-Kemp** [comment]
I've started working on this and have managed to get it working with the new SDK.

Here's my fork: https://github.com/Martin-Kemp/beats/tree/new_azure_eventhubs_sdk

It's still very basic. I basically just replaced the SDK, deleted the `eph.go` file and replaced it with a `processor.go` with the same logic.

Needs a bit more work but I compiled it and it's working and importantly it now adds the partitionKey field to the messages which is what we need from the new SDK.

**Comment by Martin-Kemp** [comment]
I wouldn't mind a bit of help to get this over the line. I'm not a Go programmer nor am I very familiar with this repo :)

**Comment by zmoog** [comment]
Hey @Martin-Kemp! We are starting to upgrade the input to the new SDK. How is your fork doing?

**Comment by martin-neo** [comment]
Hi @zmoog, that's great news! My fork has been working mostly fine, there seems to be some disconnect issues at higher message rates but I'm yet to figure out the root cause. We were also having Azure issues at the same time so could have been that.

**Comment by Martin-Kemp** [comment]
Hi @zmoog, that's great news! My fork has been working mostly fine, there seems to be some disconnect issues at higher message rates but I'm yet to figure out the root cause. We were also having Azure issues at the same time so could have been that.

**Comment by zmoog** [comment]
It's great to hear the fork is working for you. I'll update you on this issue as we progress.

**Comment by zmoog** [comment]
Hey @Martin-Kemp, the work is progressing. I am currently working on https://github.com/elastic/beats/issues/36377 to upgrade the input to input API v2 as a preparation step. I'll open a PR for this change soon.

The current plan is to offer the legacy (v1) and modern (v2) SDKs with a configuration option.

**Comment by zmoog** [comment]
To run the azure-eventhub input in this test, we need to use the following module config:

```yaml
- module: azure
  # All logs
  activitylogs:
    enabled: true
    var:
      # eventhub name containing the activity logs, overwrite he default value if the logs are exported in a different eventhub
      eventhub: "sdh4552"
      # consumer group name that has access to the event hub, we advise creating a dedicated consumer group for the azure module
      consumer_group: "$Default"
      # the connection string required to communicate with Event Hubs, steps to generate one here https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-get-connection-string
      connection_string: "<redacted>"
      # the name of the storage account the state/offsets will be stored and updated
      storage_account: "mbrancageneral"
      # the name of the storage account container you would like to store the offset information in.
      storage_account_container: "<redacted>"
      # the storage account key, this key will be used to authorize access to data in your storage account
      # processor v1
      storage_account_key: "<redacted>"
      # processor v2
      storage_account_connection_string: "<redacted>"
      # processor version, valid values are v1 or v2
      processor_version: "v2"
```

Currently, there are two new config options to set:

```
      # processor v2
      storage_account_connection_string: "<redacted>"

      # processor version, valid values are v1 or v2
      processor_version: "v2"
```

The easy-to-use function to create a container client requires a connection string instead of a key, so I added `storage_account_connection_string` option. We'll see if it's possible to still use the `storage_account_key`.

The input can work with the legacy SDK (v1) or the modern SDK (v2). You can pick one or the other by setting `processor_version` accordingly.
