### ISSUE TITLE
Filebeat autodiscover not working

### ISSUE THREAD

**Issue by Huangvivi** [elastic/beats#33912]
```
filebeat.autodiscover:
  providers:
    - type: kubernetes
      hints.enabled: true
      templates:
      - condition:
          # equals:
          #   kubernetes.namespace: default
          not:
            contains:
              kubernetes.namespace: ["default", "elastic-system", "kubesphere-logging-system", "kubesphere-system"]
        config:
          - type: container
            paths:
              - /var/log/containers/*-${data.kubernetes.container.id}.log
# processors:
  # add_cloud_metadata:
  # add_host_metadata:
output.logstash: 
  hosts: ["logstash.default.svc.cluster.local:5044"]
```

Like above,  I can't filter the log in "default", "elastic-system", "kubesphere-logging-system", "kubesphere-system" namespace.
but, can only select log from "default" namespace by below condition
```
equals:
  kubernetes.namespace: default
```
Is there any thing wrong?  I've read the [docs](https://www.elastic.co/guide/en/beats/filebeat/current/defining-processors.html#condition-contains) many times,  but still get nothing right
