### ISSUE TITLE
[Heartbeat] Params support

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#33963]
Lightweight pushed monitors should support params using the same `${variable}` syntax beats supports. For example:

```yaml
- type: http
  name: Admin Check
  url: ...
  username: ${admin_user:admin}
  password: ${admin_password}
  params:
    admin_user: foo
    admin_password: bar
```

See [the beats docs](https://www.elastic.co/guide/en/beats/libbeat/current/config-file-format-env-vars.html) for the full spec for how beats does this.
