### ISSUE TITLE
[Filebeat] cel input - non HTTP 200 status_code causes rapid retry

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#33999]
When the CEL program returns a `state.status_code` that is non HTTP 200 then the input will repeat the request rapidly. This occurs for status codes that are outside the range that are handled by go-retryablehttp like [201, 499] except 429. If I omit the `status_code` then it basically works as expected by making a request, reporting the error, and then waiting for the next interval. So perhaps when a non-200 `status_code` is reported then the auto-generated `error.message` could include information about the status code and it would wait for the next interval?

In 6.231 sec the input made 10893 requests. That's ~1700 request per second. 😨 

```
% grep -h "HTTP request" cel.trace | wc -l
   10893
% head -1 cel.trace| jq '."@timestamp"'
"2022-12-08T10:38:10.445-0500"
% tail -1 cel.trace| jq '."@timestamp"'
"2022-12-08T10:38:16.676-0500"
```

Version: filebeat version 8.7.0 (arm64), libbeat 8.7.0 [f08eed88d58d33810e6e923c03fad9a3c87bd575 built 2022-12-08 15:32:00 +0000 UTC]

### Reproduction

```go
package main

import (
	"log"
	"net/http"
)

func main() {
	handler := func(writer http.ResponseWriter, request *http.Request) {
		http.Error(writer, "Go away", http.StatusForbidden)
	}
	log.Fatal(http.ListenAndServe("localhost:9888", http.HandlerFunc(handler)))
}
```

```yaml
---

filebeat.inputs:
  - type: cel
    interval: 1m

    resource:
      url: http://localhost:9888
      retry:
        min_wait: 10s
        max_wait: 120s
      tracer:
        filename: cel.trace

    program: |
      get('http://localhost:9888').as(resp, bytes(resp.Body).as(body, {
          "events": (resp.StatusCode == 200) ? try(body.decode_json()) : {"error": {"message": "unexpected status code " + string(resp.StatusCode)} },
          "status_code": resp.StatusCode,
          "want_more": false,
      }))

output.console.pretty: true
```
