### ISSUE TITLE
Filebeat doesn't collect logs of CronJob pods

### ISSUE THREAD

**Issue by roman-stelmakh-emesa** [elastic/beats#34045]
We experience the same issue mentioned here https://github.com/elastic/beats/issues/22718
We use the latest Filebeat **8.5.1** on AWS EKS with Amazon Linux 2 EC2 worker nodes.
Sometimes Filebeat loses CronJob Pods log mesages. 
For CronJobs that runs every minute we see only 54 message with one hour instead of 60. 
Around **9-10%** of CronJob messages are lost.
In comparison the legacy Filebeat 6.8.13 doesn't lose any message.

Filebeat version **8.5.1**. 
AWS EKS is **v1.21.14**

Filebeat configuration:
```yaml
filebeat.autodiscover:
  providers:
    - type: kubernetes
      cleanup_timeout: 24h
      add_resource_metadata:
        namespace:
          include_labels: [""]
          include_annotations: [""]
        node:
          include_labels: [""]
          include_annotations: [""]
        deployment: true
        cronjob: true
      templates:
        - config:
            - type: container
              paths:
                - /var/log/containers/*-${data.kubernetes.container.id}.log
```

Cronjob example:
```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-test
  namespace: default
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 30
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: busybox:1.28
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - date
          restartPolicy: OnFailure
```

Example of messages on Kibana.
Here you can see that messages at 15:25 and 15:30 and 15:31 are missing:
```
Dec 14, 2022 @ 15:34:04.596	cronjob-test-27850474-m6pnd	Wed Dec 14 14:34:04 UTC 2022
Dec 14, 2022 @ 15:33:04.570	cronjob-test-27850473-bxzdp	Wed Dec 14 14:33:04 UTC 2022
Dec 14, 2022 @ 15:32:04.823	cronjob-test-27850472-nrr7p	Wed Dec 14 14:32:04 UTC 2022
Dec 14, 2022 @ 15:29:03.972	cronjob-test-27850469-9gbkx	Wed Dec 14 14:29:03 UTC 2022
Dec 14, 2022 @ 15:28:03.997	cronjob-test-27850468-5l5c7	Wed Dec 14 14:28:03 UTC 2022
Dec 14, 2022 @ 15:27:03.710	cronjob-test-27850467-24g44	Wed Dec 14 14:27:03 UTC 2022
Dec 14, 2022 @ 15:26:03.730	cronjob-test-27850466-qdxk9	Wed Dec 14 14:26:03 UTC 2022
Dec 14, 2022 @ 15:24:06.376	cronjob-test-27850464-ztclr	Wed Dec 14 14:24:06 UTC 2022
Dec 14, 2022 @ 15:23:06.970	cronjob-test-27850463-f2qm6	Wed Dec 14 14:23:06 UTC 2022
```

**Comment by dezmodue** [comment]
We're running filebeat 8.5.2 on k8s and it looks like we are facing the same issue

**Comment by marcoval123** [comment]
We're running filebeat **7.10.2** n k8s and it looks like we are facing the same issue

**Comment by StephanErb** [comment]
Has anyone tried playing around with [`kube_client_options`](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-autodiscover.html) yet? 

I am wondering if this could be related to the issue here. Assuming filebeat is running on a busy node, I could totally expect it to run into the query throttle. Discovery could then be delayed so much that we never end up picking up the logs before the container is terminated again.

Never looked into it deeper, but still a hypothesis I'd like to validate one day.

**Comment by ChrsMark** [comment]
Hey folks, sorry for the late response here.
This one should be fixed by https://github.com/elastic/beats/issues/22718 already. @gizas @rameshelastic could we have someone from the team to have a look into this one? It could be a regression or another corner case. This one as well as the
https://github.com/elastic/beats/issues/22718 provide steps to reproduce the issue so it should be fairly easy to check.

**Comment by eedugon** [comment]
@StephanErb , I believe that's a nice hypothesis. I've seen a case where some `CronJob` related pods logs were not being shipped and there was no track at all of the beat even trying to harvest the log file. A delay in discovery would definitely explain the outcome.

**Comment by gizas** [comment]
cc @gsantoro

**Comment by gsantoro** [comment]
sorry for the late response. I've now assigned this issue to myself. It's now the highest priority item on my list.

**Comment by gsantoro** [comment]
I would like to start with a simplified setup so that we can exclude possible root causes:

- K8s: local cluster with Kind with 1 node. Version = v1.26.0
- Elastic: local cluster with version 8.7.0-SNAPSHOT
- Filebeat: code from main branch with the following config. to notice that autodiscover is not enabled yet.

```yaml
    - type: container
      paths:
        - /var/log/containers/*.log
      processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
```

same cronjob manifest as in https://github.com/elastic/beats/issues/22718. Only thing that changed is the apiVersion (which might have changed since then)

```yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
  namespace: kube-system
spec:
  schedule: "*/1 * * * *"
  failedJobsHistoryLimit: 10
  successfulJobsHistoryLimit: 20
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
```

This is the list of k8s events for a single run of that cronjob. The order of events is reversed (first event is the last to occurr)

```bash
│ kube-system                  12m                         Normal                  SawCompletedJob                   cronjob/hello                              1                       │
│ kube-system                  12m                         Normal                  SuccessfulCreate                  job/hello-27952816                         1                       │
│ kube-system                  12m                         Normal                  Completed                         job/hello-27952816                         1                       │
│ kube-system                  12m                         Normal                  Started                           pod/hello-27952816-p2zxj                   1                       │
│ kube-system                  12m                         Normal                  Scheduled                         pod/hello-27952816-p2zxj                   1                       │
│ kube-system                  12m                         Normal                  Created                           pod/hello-27952816-p2zxj                   1                       │
│ kube-system                  12m                         Normal                  Pulled                            pod/hello-27952816-p2zxj                   1                       │
│ kube-system                  12m                         Normal                  Pulling                           pod/hello-27952816-p2zxj                   1                       │
```

and this is a screenshot of Kibana with the list of all logs for that single pod (and all the other cronjobs run as well).

![Screenshot 2023-02-23 at 16 31 26](https://user-images.githubusercontent.com/2378291/220970160-820991f2-9146-497c-874c-2a7cd726832c.png)


So this use case confirm that:
1. logs are correctly collected by filebeat if running without autodiscover and with this combination of elastic, k8s, filebeat code
2. the k8s events progression seems correct. I can't find any errors. I agree like it was said in the comment https://github.com/elastic/beats/issues/22718#issue-748961395 that there is no `Running` event for cronjobs compared to long running jobs. But everything seems to point to the fact there is no `Running` event raised by cron jobs at all when everything is working normally.
3. there is no init cointainers in this example yet but I'll leave that out for now. We might come back to this later.

```yaml
➜ k describe cronjob hello
Name:                          hello
Namespace:                     kube-system
Labels:                        <none>
Annotations:                   <none>
Schedule:                      */1 * * * *
Concurrency Policy:            Allow
Suspend:                       False
Successful Job History Limit:  20
Failed Job History Limit:      10
Starting Deadline Seconds:     <unset>
Selector:                      <unset>
Parallelism:                   <unset>
Completions:                   <unset>
Pod Template:
  Labels:  <none>
  Containers:
   hello:
    Image:      busybox
    Port:       <none>
    Host Port:  <none>
    Args:
      /bin/sh
      -c
      date; echo Hello from the Kubernetes cluster
    Environment:     <none>
    Mounts:          <none>
  Volumes:           <none>
Last Schedule Time:  Thu, 23 Feb 2023 16:38:00 +0000
Active Jobs:         <none>
Events:
  Type    Reason            Age                   From                Message
  ----    ------            ----                  ----                -------
  Normal  SuccessfulCreate  22m                   cronjob-controller  Created job hello-27952816
  Normal  SawCompletedJob   22m                   cronjob-controller  Saw completed job: hello-27952816, status: Complete
  Normal  SuccessfulCreate  21m                   cronjob-controller  Created job hello-27952817
  Normal  SawCompletedJob   21m                   cronjob-controller  Saw completed job: hello-27952817, status: Complete
  Normal  SuccessfulCreate  20m                   cronjob-controller  Created job hello-27952818
```

I'll move now to replicate the same setup but only changing the filebeat config with autodiscover.

**Comment by gsantoro** [comment]
Here is the test with autodiscover. Everything else is the same from the previous comment

filebeat config to replace `filebeat.inputs` 

```yaml
    filebeat.autodiscover:
     providers:
       - type: kubernetes
         node: ${NODE_NAME}
         hints.enabled: true
         hints.default_config:
           type: container
           paths:
             - /var/log/containers/*${data.kubernetes.container.id}.log
```

List of completed cron jobs

```yaml
│ 6m30s            hello-27952850-gd26q                                          10.244.0.36             integrations-control-plane             Completed             0/1               │
│ 5m30s            hello-27952851-478zd                                          10.244.0.37             integrations-control-plane             Completed             0/1               │
│ 4m30s            hello-27952852-6nkr9                                          10.244.0.38             integrations-control-plane             Completed             0/1               │
│ 3m30s            hello-27952853-g6rhz                                          10.244.0.39             integrations-control-plane             Completed             0/1               │
│ 2m30s            hello-27952854-r6stl                                          10.244.0.40             integrations-control-plane             Completed             0/1               │
│ 90s              hello-27952855-cf55v                                          10.244.0.41             integrations-control-plane             Completed             0/1               │
│ 30s              hello-27952856-flk9w                                          10.244.0.42             integrations-control-plane             Completed             0/1
```

Screenshots from Kibana with logs ingested in ES

![Screenshot 2023-02-23 at 16 56 22](https://user-images.githubusercontent.com/2378291/220976451-011f739e-32bc-438e-8ef9-76eea991c68b.png)

The number of completed cronjobs matches the number of reported events in Kibana.

**Comment by gsantoro** [comment]
How to go forward:
- I'll leave the init containers out of the picture for now
- Since I haven't been able to replicate https://github.com/elastic/beats/issues/22718 with the latest version of the stack, I'll move to replicate this issue instead with tests in this order

1. Autodiscover with templates instead of hint with the following configuration

```yaml

Filebeat configuration:

filebeat.autodiscover:
  providers:
    - type: kubernetes
      cleanup_timeout: 24h
      add_resource_metadata:
        namespace:
          include_labels: [""]
          include_annotations: [""]
        node:
          include_labels: [""]
          include_annotations: [""]
        deployment: true
        cronjob: true
      templates:
        - config:
            - type: container
              paths:
                - /var/log/containers/*-${data.kubernetes.container.id}.log
```

2.  Filebeat version 8.5.1 with same config as at point 1
3. Setup in the cloud with AWS EKS is v1.21.14 with everything else from previous test the same

**Comment by gsantoro** [comment]
This works as expected too

1. Autodiscover with templates instead of hint with the following configuration

```yaml
 13m              hello-27952878-btqkg                                          10.244.0.50             integrations-control-plane             Completed             0/1               │
│ 12m              hello-27952879-4n6rt                                          10.244.0.51             integrations-control-plane             Completed             0/1               │
│ 11m              hello-27952880-f6pc2                                          10.244.0.52             integrations-control-plane             Completed             0/1               │
│ 10m              hello-27952881-d5kl9                                          10.244.0.53             integrations-control-plane             Completed             0/1               │
│ 9m34s            hello-27952882-xjpl4                                          10.244.0.54             integrations-control-plane             Completed             0/1               │
│ 8m34s            hello-27952883-whxvw                                          10.244.0.55             integrations-control-plane             Completed             0/1               │
│ 7m34s            hello-27952884-bh65s                                          10.244.0.56             integrations-control-plane             Completed             0/1               │
│ 6m34s            hello-27952885-fqfn8                                          10.244.0.57             integrations-control-plane             Completed             0/1               │
│ 5m34s            hello-27952886-7whwf                                          10.244.0.58             integrations-control-plane             Completed             0/1               │
│ 4m34s            hello-27952887-b75hs                                          10.244.0.59             integrations-control-plane             Completed             0/1               │
│ 3m34s            hello-27952888-sgv85                                          10.244.0.60             integrations-control-plane             Completed             0/1               │
│ 2m34s            hello-27952889-qqtcs                                          10.244.0.61             integrations-control-plane             Completed             0/1               │
│ 94s              hello-27952890-56hxq                                          10.244.0.62             integrations-control-plane             Completed             0/1               │
│ 34s              hello-27952891-gc9gn                                          10.244.0.63             integrations-control-plane             Completed             0/1               │
```

and the Kibana screenshot

![Screenshot 2023-02-23 at 17 30 52](https://user-images.githubusercontent.com/2378291/220984724-36581943-5a22-4d43-b32e-f1930b4d6afd.png)

**Comment by gsantoro** [comment]
2. Filebeat and elastic stack with version 8.5.1 with same config as at point 1

```yaml
7m31s        kube-system               hello-27952913-c9z55                                      10.244.0.6         integrations-control-plane        Completed         0/1           │
│ 6m31s        kube-system               hello-27952914-rcfjx                                      10.244.0.7         integrations-control-plane        Completed         0/1           │
│ 5m31s        kube-system               hello-27952915-jlvrg                                      10.244.0.8         integrations-control-plane        Completed         0/1           │
│ 4m31s        kube-system               hello-27952916-k8s9w                                      10.244.0.9         integrations-control-plane        Completed         0/1           │
│ 3m31s        kube-system               hello-27952917-59ssr                                      10.244.0.10        integrations-control-plane        Completed         0/1           │
│ 2m31s        kube-system               hello-27952918-tzwlt                                      10.244.0.11        integrations-control-plane        Completed         0/1           │
│ 91s          kube-system               hello-27952919-j79zr                                      10.244.0.12        integrations-control-plane        Completed         0/1           │
│ 31s          kube-system               hello-27952920-hqj54                                      10.244.0.13        integrations-control-plane        Completed         0/1           │
```

and the usual Kibana page with all the cronjobs properly logged

![Screenshot 2023-02-23 at 18 00 26](https://user-images.githubusercontent.com/2378291/220991349-70a7791c-b6d5-438d-86a4-d2fccccb9f5f.png)

**Comment by gsantoro** [comment]
3. same k8s version as AWS EKS is v1.21.14 but with Kind

same thing here. all pods completed

```yaml
│ 3m6s         kube-system               hello-27952933-jvjr5                                      10.244.0.6        integrations-control-plane         Completed         0/1           │
│ 2m6s         kube-system               hello-27952934-lxpxh                                      10.244.0.7        integrations-control-plane         Completed         0/1           │
│ 66s          kube-system               hello-27952935-lm5r5                                      10.244.0.8        integrations-control-plane         Completed         0/1           │
```

all pods accounted for

![Screenshot 2023-02-23 at 18 15 56](https://user-images.githubusercontent.com/2378291/220995404-75296b14-09c7-44bb-8e7a-1d648d1889d2.png)


Before I move on and start a more complicated setup with AWS EKS, I am wondering if I should pause and consider any other settings, config or setup that can still replicated locally without using AWS EKS.

Does anyone here have a better idea?

**Comment by StephanErb** [comment]
> Does anyone here have a better idea?

I still believe this is either load related or has a statistical element to it. I would try starting 50 cron jobs (on a 1-2 node cluster) and see how that behaves.

**Comment by gizas** [comment]
Ok I think that @gsantoro verified that all work in a small scale.

So lets choose one of the above tests. and run it for long time. In more details:
- Hints configuration (https://github.com/elastic/beats/issues/34045#issuecomment-1442122285) to be applied, 
- Apply 50 diffrent cronjobs (hello1, hello2, ... hello50 with difffrent echo message #33702 )
- Leave the cluster up for the whole weekend

Lets see if something happens

**Comment by gsantoro** [comment]
couple of questions:
1. if we want to leave it running at scale over the weekend I would suggest to use the cloud instead of my local laptop. I have some automation to quickly setup a GCP k8s cluster with the latest k8s version or at least the oldest version still supported by google. This might be greater than the version v1.21.14 from AWS. Is this OK?
2. I'm not 100% sure if the hints based configuration (that I normally use) or the templates configuration (from the original [message](https://github.com/elastic/beats/issues/34045#issue-1496787165)) is a relevant factor. Maybe @ChrsMark can chime in about this specific topic
3. about having 50 different cronjob, I'll write a script that match the cronjobs started in k8s to the ones ingested in ES so that we can check if there is any logs missing. I am not aware there is already anything to do this.

**Comment by gizas** [comment]
1. OK
2. The config should not be a factor. Ok choose what is closer the customer sdh
3. OK.

**Comment by StephanErb** [comment]
There is a related thread on [Filebeat autodiscover stopping too early when kubernetes pod terminates](https://discuss.elastic.co/t/filebeat-autodiscover-stopping-too-early-when-kubernetes-pod-terminates/325491) over at discuss.elstic.co. It raises the interesting questions: Could the problem be related to multiple within the same POD and how this affects the POD termination?

At least in our case we have Istio running, so the command terminating within the cronjob is never the last container to terminate in the POD. Is that maybe similar to other here also who face the problem?

**Comment by gsantoro** [comment]
hello everyone, I have just finished a performance test on the cloud. this is the environment:

- elastic stack: 8.7.0-SNAPSHOT
- K8S version: v.1.25.6
- 3 nodes k8s cluster = 3 filebeat pods
- filebeat with autodiscover

instead of a cronjob I have used the following job template since it is easier to deal with parallelism.

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: process-item-$ITEM
  namespace: kube-system
  labels:
    jobgroup: jobexample
spec:
  completions: 500
  parallelism: 50
  template:
    metadata:
      name: jobexample
      labels:
        jobgroup: jobexample
    spec:
      containers:
      - name: process-item
        image: busybox
        command: ["sh", "-c", "echo Processing item $ITEM && sleep 5"]
      restartPolicy: Never
```

where the variable `$ITEM` has been replace with values `a, b, c, d` so that I can have a total of:
- 50 parallel job x 4 (values for `$ITEM`)
- total = 2000 jobs

And this are the results:
- logs from 474 jobs were correctly ingested into Elasticsearch
- over 800 jobs were started. Some where still running (around 100) and the other already completed

![Screenshot 2023-02-27 at 13 04 08](https://user-images.githubusercontent.com/2378291/221571061-cf50964b-b809-4461-858d-5322274ab307.png)

As you can see from the previous screenshot, filebeat wasn't able to catchup with the amount of logs produced. I'll have another look with a smaller scale to check if it's just a scaling issue of filebeat or something else.
