### ISSUE TITLE
Docs discrepancy in 'Change the index name' vs filebeat.reference.yml

### ISSUE THREAD

**Issue by brsolomon-deloitte** [elastic/beats#34112]
From https://www.elastic.co/guide/en/beats/filebeat/current/change-index-name.html#change-index-name:

```yaml
output.elasticsearch.index: "customname-%{[agent.version]}"
setup.template.name: "customname"
setup.template.pattern: "customname-%{[agent.version]}"
```

From https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-reference-yml.html#filebeat-reference-yml (abridged):

```yaml
output.elasticsearch:
  index: "filebeat-%{[agent.version]}"
setup.template.name: "filebeat-%{[agent.version]}"
setup.template.pattern: "filebeat-%{[agent.version]}"
```

There is a key difference here that is not explained by the docs. In the first example, the `setup.template.name` is *not* suffixed with the agent (filebeat) version, whereas in the second case, it is. As the agent versions are upgraded over time, this causes a difference in behavior where either (scenario 1) the same-named template is overwritten or (scenario 2) a new index template is created for each version.

Is it possible these two docs sources could be reconciled?
