### ISSUE TITLE
[Heartbeat] Agent encounters error when integration policy is updated

### ISSUE THREAD

**Issue by dominiqueclarke** [elastic/beats#34162]
After updating a project monitor with a private location, Heartbeat sometimes encounters an error.
```
11:37:35.132
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Output reload is enabled, the beat will restart as needed on change of output config
11:37:35.145
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Set gc percentage to: 100
11:37:35.146
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] running under elastic-agent, per-beat lockfiles disabled
11:37:35.153
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Starting stats endpoint
11:37:35.154
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Metrics endpoint listening on: /usr/share/elastic-agent/state/data/tmp/synthetics-browser-default.sock (configured: unix:///usr/share/elastic-agent/state/data/tmp/synthetics-browser-default.sock)
11:37:35.155
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Syscall filter successfully installed
11:37:35.155
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Beat info
11:37:35.161
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Build info
11:37:35.161
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Go runtime info
11:37:35.205
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Host info
11:37:35.206
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Process info
11:37:35.229
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Setup Beat: heartbeat; Version: 8.7.0
11:37:35.230
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Output is configured through Central Management
11:37:35.235
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Beat name: a91771fdce6d
11:37:35.235
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] limiting to 2 concurrent jobs for 'browser' type
11:37:35.236
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Starting metrics logging every 30s
11:37:35.241
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] heartbeat start running.
11:37:35.241
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] heartbeat is running! Hit CTRL-C to stop it.
11:37:35.241
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Effective user/group ids: %d/%d, with groups: %v1000 1000 [0]
11:37:35.389
elastic_agent.heartbeat
[elastic_agent.heartbeat][error] Error creating runner from config: could not parse cfg for datastream error unpacking monitor plugin config: string value is not set accessing 'type'
```

The monitor ran successfully previously before being updated.

The previous policy: 

```
- id: >-
      synthetics/browser-synthetics-browser-private-push:private-default-3b5dcb60-8b84-11ed-9a83-657429dffcbe
    name: 'browser-private-push:private-default-synthetics_ci_1'
    revision: 1
    type: synthetics/browser
    use_output: default
    meta:
      package:
        name: synthetics
        version: 0.11.5
    data_stream:
      namespace: default
    package_policy_id: 'browser-private-push:private-default-3b5dcb60-8b84-11ed-9a83-657429dffcbe'
    streams:
      - id: 'browser-private-push:private-default'
        name: ci-push-e2e Browser private location
        type: browser
        enabled: true
        data_stream:
          dataset: browser
          type: synthetics
          elasticsearch:
            privileges:
              indices:
                - auto_configure
                - create_doc
                - read
        source.project.content: >-
          UEsDBBQACAAIAAAAIQAAAAAAAAAAAAAAAAARAAAAcHVzaGVkLmpvdXJuZXkudHPNlFtv2jAUx9/5FEfWHoKUS4FCt1SbpqkvlbZVWtenqRrGOQWPxI5iB1ShfPc5id0yLt2Y2NoHAufCOce/v0+iCH7IshB4H0cy19Gk5Gky5xoDOkVhbRVN5q0dYEqV5iyYsjzojc76Z6PB4HWvPzjtDU+Hb04iG4/UvdAzNL9UoDRl8wD7GDAe2WYqyks1ax6YhNYZatXhWS4LDSs3lQ9KY+5DJgXXsoAK7gqZAXm/3Yicd+yfvA6YCjyJYTwp5FJhEbBUlsnYB0EzNG7Gg7p3PRV8aFPApWg6VTF8I3VC3DjjCVVIbqHyTWFqOjLwVpAbIr55FjRTUHXh7TtYmTi4WcNSodd64Ld94dUqLyRDpUIUi/DT1efLr1dfvt/cXF5UY98WSSWjmkthxmvbhizl11gsOMOPLuaS84IvqH70myPduphiBnuZmol6w4f8pmIMbmIAjUrHQJoAsd7Kpdd0903cpFTd8+a71s8j11xMU2wMJy3xHcs1dobvknLdwA2nUkuPzLTOVRxFy+XSeKQpE6Iitnrbpep0jyE+lHlikO25BG3wH18DO8FzXYfB1m14GYIzmR2kuD3t05rbpAeOm7Lb+BG2P91FfVsRq+JmIMxo7nmuRtPKGWF9vO4frXX10rbyrzTat6JOq2Ms6X9Xa/AMYj29Ua1UJCmzrG7SCkQuatMhIxsKJJiiJf8r9zXe27R3sN7xpiJCClO6jT9yG520HhR0kqIZ+I6mCm2VdZTtCQ/DeBDEukH9+QlQSwcIFH6Ttz0CAABPCQAAUEsBAi0DFAAIAAgAAAAhABR+k7c9AgAATwkAABEAAAAAAAAAAAAgAKSBAAAAAHB1c2hlZC5qb3VybmV5LnRzUEsFBgAAAAABAAEAPwAAAHwCAAAAAA==
        filter_journeys.match: ci-push-e2e Browser private location updated
        origin: project
        processors:
          - add_fields:
              fields:
                monitor.project.id: 'push:private'
                config_id: a87edf75-5d61-4450-b18a-5cd486b60356
                monitor.project.name: 'push:private'
                monitor.fleet_managed: true
              target: ''
        params:
          cliServiceLocations: []
          privateLocations:
            - name: synthetics_ci_1
              forceUnenroll: true
              policy: Synthetics private location policy
        timeout: null
        screenshots: 'on'
        tags:
          - 'push:private:update'
        playwright_options:
          headless: true
        schedule: '@every 15m'
        throttling: 5d/3u/20l
        __ui:
          script_source:
            file_name: ''
            is_generated_script: false
          is_zip_url_tls_enabled: false
        run_from.id: synthetics_ci_1
        run_from.geo.name: synthetics_ci_1
      - id: >-
          synthetics/browser-browser.network-browser-private-push:private-default-3b5dcb60-8b84-11ed-9a83-657429dffcbe
        data_stream:
          dataset: browser.network
          type: synthetics
          elasticsearch:
            privileges:
              indices:
                - auto_configure
                - create_doc
                - read
        processors:
          - add_fields:
              fields:
                monitor.fleet_managed: true
              target: ''
      - id: >-
          synthetics/browser-browser.screenshot-browser-private-push:private-default-3b5dcb60-8b84-11ed-9a83-657429dffcbe
        data_stream:
          dataset: browser.screenshot
          type: synthetics
          elasticsearch:
            privileges:
              indices:
                - auto_configure
                - create_doc
                - read
        processors:
          - add_fields:
              fields:
                monitor.fleet_managed: true
              target: ''
```

Updated policy. Notice the name change, in case it's relevant:
```
- id: >-
      synthetics/browser-synthetics-browser-private-push:private-default-3b5dcb60-8b84-11ed-9a83-657429dffcbe
    name: 'browser-private-push:private-default-synthetics_ci_1'
    revision: 2
    type: synthetics/browser
    use_output: default
    meta:
      package:
        name: synthetics
        version: 0.11.5
    data_stream:
      namespace: default
    package_policy_id: 'browser-private-push:private-default-3b5dcb60-8b84-11ed-9a83-657429dffcbe'
    streams:
      - id: 'browser-private-push:private-default'
        name: ci-push-e2e Browser private location updated
        type: browser
        enabled: true
        data_stream:
          dataset: browser
          type: synthetics
          elasticsearch:
            privileges:
              indices:
                - auto_configure
                - create_doc
                - read
        source.project.content: >-
          UEsDBBQACAAIAAAAIQAAAAAAAAAAAAAAAAARAAAAcHVzaGVkLmpvdXJuZXkudHPNlFtv2jAUx9/5FEfWHoKUS4FCt1SbpqkvlbZVWtenqRrGOQWPxI5iB1ShfPc5id0yLt2Y2NoHAufCOce/v0+iCH7IshB4H0cy19Gk5Gky5xoDOkVhbRVN5q0dYEqV5iyYsjzojc76Z6PB4HWvPzjtDU+Hb04iG4/UvdAzNL9UoDRl8wD7GDAe2WYqyks1ax6YhNYZatXhWS4LDSs3lQ9KY+5DJgXXsoAK7gqZAXm/3Yicd+yfvA6YCjyJYTwp5FJhEbBUlsnYB0EzNG7Gg7p3PRV8aFPApWg6VTF8I3VC3DjjCVVIbqHyTWFqOjLwVpAbIr55FjRTUHXh7TtYmTi4WcNSodd64Ld94dUqLyRDpUIUi/DT1efLr1dfvt/cXF5UY98WSSWjmkthxmvbhizl11gsOMOPLuaS84IvqH70myPduphiBnuZmol6w4f8pmIMbmIAjUrHQJoAsd7Kpdd0903cpFTd8+a71s8j11xMU2wMJy3xHcs1dobvknLdwA2nUkuPzLTOVRxFy+XSeKQpE6Iitnrbpep0jyE+lHlikO25BG3wH18DO8FzXYfB1m14GYIzmR2kuD3t05rbpAeOm7Lb+BG2P91FfVsRq+JmIMxo7nmuRtPKGWF9vO4frXX10rbyrzTat6JOq2Ms6X9Xa/AMYj29Ua1UJCmzrG7SCkQuatMhIxsKJJiiJf8r9zXe27R3sN7xpiJCClO6jT9yG520HhR0kqIZ+I6mCm2VdZTtCQ/DeBDEukH9+QlQSwcIFH6Ttz0CAABPCQAAUEsBAi0DFAAIAAgAAAAhABR+k7c9AgAATwkAABEAAAAAAAAAAAAgAKSBAAAAAHB1c2hlZC5qb3VybmV5LnRzUEsFBgAAAAABAAEAPwAAAHwCAAAAAA==
        filter_journeys.match: ci-push-e2e Browser private location updated
        origin: project
        processors:
          - add_fields:
              fields:
                monitor.project.id: 'push:private'
                config_id: a87edf75-5d61-4450-b18a-5cd486b60356
                monitor.project.name: 'push:private'
                monitor.fleet_managed: true
              target: ''
        params:
          cliServiceLocations: []
          privateLocations:
            - name: synthetics_ci_1
              forceUnenroll: true
              policy: Synthetics private location policy
        timeout: null
        screenshots: 'on'
        tags:
          - 'push:private:update'
        playwright_options:
          headless: true
        schedule: '@every 3m'
        throttling: 5d/3u/20l
        __ui:
          script_source:
            file_name: ''
            is_generated_script: false
          is_zip_url_tls_enabled: false
        run_from.id: synthetics_ci_1
        run_from.geo.name: synthetics_ci_1
      - id: >-
          synthetics/browser-browser.network-browser-private-push:private-default-3b5dcb60-8b84-11ed-9a83-657429dffcbe
        data_stream:
          dataset: browser.network
          type: synthetics
          elasticsearch:
            privileges:
              indices:
                - auto_configure
                - create_doc
                - read
        processors:
          - add_fields:
              fields:
                monitor.fleet_managed: true
              target: ''
      - id: >-
          synthetics/browser-browser.screenshot-browser-private-push:private-default-3b5dcb60-8b84-11ed-9a83-657429dffcbe
        data_stream:
          dataset: browser.screenshot
          type: synthetics
          elasticsearch:
            privileges:
              indices:
                - auto_configure
                - create_doc
                - read
        processors:
          - add_fields:
              fields:
                monitor.fleet_managed: true
              target: ''
```
For confirmed bugs, please report:
- Version: 8.7.0-SNAPSHOT, 8.6.0-SNAPSHOT
