### ISSUE TITLE
Beats misreport established Kafka connection

### ISSUE THREAD

**Issue by heck-gd** [elastic/beats#34177]
When using Kafka as output, beats will claim that the connection to the broker was established, even if it is impossible because the host in question cannot be reached.

- Version: 8.4.3 (it's a long-standing bug that was also present in 7.x)
- Operating System: Windows Server 2016, Windows Server 2019 (probably all OSes though)
- Discuss Forum URL: https://discuss.elastic.co/t/bug-bug-in-logs-related-to-kafka-connection/269625 (older, went ignored, so I didn't bother with a new forum post - it's an obvious bug and I'm not the only one who noticed it)
- Steps to Reproduce: 
  1. In a VM, set up Filebeat or Winlogbeat with a Kafka output.
  2. Disconnect the VM from the virtual network ("unplug the cable") so that it definitely cannot reach any server.
  3. Start beat.
  4. Beat will lie to your face with the following log lines:
       ```json
       {"log.level":"info","@timestamp":"2023-01-03T14:06:44.119+0100","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/client_worker.go","file.line":139},"message":"Connecting to kafka(thekafkahost:theport)","service.name":"winlogbeat","ecs.version":"1.6.0"} 
      {"log.level":"info","@timestamp":"2023-01-03T14:06:44.120+0100","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/client_worker.go","file.line":147},"message":"Connection to kafka(thekafkahost:theport) established","service.name":"winlogbeat","ecs.version":"1.6.0"}
       ```

In a real-world scenario, a firewall between the two hosts that accidentally blocks the traffic has the exact same effect.

Example output configuration (as used in production, but with fake values for host/port/auth):
```yml
output.kafka:
  enabled: true

  hosts: ["thekafkahost:theport"]

  topic: mytopic

  partition.round_robin:
    reachable_only: true

  required_acks: 1
  compression: gzip
  max_message_bytes: 1000000

  ssl.enabled: true
  ssl.certificate_authorities: ["path/to/ca.pem"]
  ssl.supported_protocols: [TLSv1.3]
  ssl.verification_mode: full

  username: 'theuser'
  password: 'thepassword'
```
