### ISSUE TITLE
Beat module inconsistent index

### ISSUE THREAD

**Issue by raphaeljoie** [elastic/beats#34173]
I have a working basic working beat module configuration, using xpack
```yml
- module: beat
  metricsets:
    - stats
    - state
  period: 10s
  hosts: ['http://localhost:5003']                                                                                                                                                      
  xpack.enabled: true 
```

Values are properly sent to be stored under `.monitoring-beats-8-mb`, but if something is wrong with the host, or the host is instead set to a random value (`hosts: ['http://blabetiblou:1234'`] ) => the value is then sent to be stored under `metricbeat-8.4.3`

# Expected behaviour
index to be consistent.
* when using xpack, everything, including errors should be stored under `.monitoring-beats-8-mb`
