### ISSUE TITLE
[Filebeat] multiline doesn't work with journald input

### ISSUE THREAD

**Issue by qwinkler** [elastic/beats#34200]
Originally I created an issue on the forum, but understood, that it was a bug in filebeat.

The problem is that [`multiline`](https://www.elastic.co/guide/en/beats/filebeat/8.5/multiline-examples.html) works with `log` input, but doesn't work with the `journald` input.

I'm still using the `7.17` version, but I checked it on the newest version and the bug is still reproducible.

- Version: 8.5.3
- Operating System: Docker, host os is Debian 11
- Discuss Forum URL: https://discuss.elastic.co/t/parse-elasticsearch-json-logs-in-filebeat/322533

Steps to Reproduce:

1. Install Docker with journald logging driver:
```bash
curl -fsSL https://get.docker.com -o get-docker.sh
sudo sh get-docker.sh
sudo mkdir -p /etc/docker
printf '{"log-driver":"journald","storage-driver":"overlay2","experimental":false}' | sudo tee /etc/docker/daemon.json
sudo systemctl restart docker.service
# optional, but recommended
printf "[Journal]\nStorage=persistent\nForwardToSyslog=no\nForwardToKMsg=no\nForwardToConsole=no\nForwardToWall=yes\n" | sudo tee /etc/systemd/journald.conf
sudo systemctl restart systemd-journald
```
2. Create a new directory and a few files:
```bash
mkdir -p test && cd test
```
<details>
  <summary>docker-compose.yml</summary>

  ```yaml
  ---
  version: "2.1"
  services:
    filebeat:
      container_name: filebeat
      build: .
      volumes:
        - /var/log/journal:/var/log/journal:ro
        - /etc/machine-id:/etc/machine-id:ro
        - /etc/hostname:/etc/hostname:ro
        - ./logs:/tmp/logs
      network_mode: host
  
    ubuntu:
      container_name: ubuntu
      image: ubuntu:20.04
      volumes:
        - ./test.log:/test.log
        - ./run.sh:/run.sh
      environment:
        LOGS_FILE: /test.log
        SLEEP_TIME: 0.01s
      command: bash /run.sh
  ```
</details>

<details>
  <summary>Dockerfile</summary>

  ```Dockerfile
  FROM docker.elastic.co/beats/filebeat:8.5.3
  COPY filebeat.yml /usr/share/filebeat/filebeat.yml
  USER root
  RUN chown root:filebeat /usr/share/filebeat/filebeat.yml
  ENTRYPOINT ["/usr/local/bin/docker-entrypoint"]
  CMD ["-e"]
  ```
</details>

<details>
  <summary>filebeat.yml</summary>

  ```yaml
  filebeat.inputs:
  - type: journald
    enabled: true
    id: everything
    seek: cursor
    paths: ["/var/log/journal"]
    multiline:
      type: pattern
      pattern: '^\{'
      negate: true
      match: after

  output.file:
    enabled: true
    path: "/tmp/logs/"
    filename: filebeat.log

  logging:
    level: warning
    to_files: false
    to_syslog: false
    json: true
  ```
</details>

<details>
  <summary>run.sh</summary>

  ```bash
  #!/usr/bin/env bash
  logs_file=${LOGS_FILE}
  sleep_time=${SLEEP_TIME}

  total_lines=$(wc -l ${logs_file} | xargs | cut -d ' ' -f 1,1)
  for((i=1;i<total_lines;i++)); do
    sleep ${sleep_time}
    sed "${i}q;d" ${logs_file}
  done
  ```
</details>

<details>
  <summary>test.log</summary>

  ```log
  {"message": "xyz123"}
  {"message": "xyz124"}
  {"message": "xyz125"}
  {"message": "xyz125"}
  {"message": "xyz126" ,
  "stacktrace": ["line1",
  "line2",
  "line3"] }
  {"message": "xyz127"}
  {"message": "xyz128"}
  {"message": "xyz129"}
  {"message": "xyz130"}
  {"message": "xyz131"}
  ```
</details>

3. Run everything
```bash
# rotate previous journal
sudo journalctl --rotate
# cleanup journal
sudo journalctl --vacuum-time=1s
# return to normal state
sudo journalctl --vacuum-time=2d
# run the stack
docker-compose up --build -d
```

4. Wait when status of the container `ubuntu` will be `exited`:
```bash
docker inspect ubuntu | jq -r '.[] | .State.Status'
```

5. Check out the logs:
```bash
cat logs/filebeat* | grep "stacktrace"
```

You'll find this: `"message":"\"stacktrace\": [\"line1\","`

6. Replace a few files to test the `log` input:

<details>
  <summary>filebeat.yml</summary>

  ```yaml
  filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /tmp/ubuntu/test.log
    multiline:
      type: pattern
      pattern: '^\{'
      negate: true
      match: after

  output.file:
    enabled: true
    path: "/tmp/logs/"
    filename: filebeat.log

  logging:
    level: warning
    to_files: false
    to_syslog: false
    json: true
  ```
</details>

<details>
  <summary>docker-compose.yml</summary>

  ```yaml
  ---
  version: "2.1"
  services:
    filebeat:
      container_name: filebeat
      build: .
      volumes:
        - /var/log/journal:/var/log/journal:ro
        - /etc/machine-id:/etc/machine-id:ro
        - /etc/hostname:/etc/hostname:ro
        - ./logs:/tmp/logs
        - ./test.log:/tmp/ubuntu/test.log
      network_mode: host
  ```
</details>

7. Re-do steps 3, 4, 5. You'll find the following line in the logs:
```log
"message":"{\"message\": \"xyz126\" ,\n\"stacktrace\": [\"line1\",\n\"line2\",\n\"line3\"] }"
```

This confirms that `log` input works fine with `multiline`, while `journald` is not.

**Comment by belimawr** [comment]
The journald input uses parsers in the same way as the filestream input, you can define them following the documentation [here](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html#_parsers)

We even have a test ensuring the multiline parser works with journald input:
https://github.com/elastic/beats/blob/878f026103df1d4b8fa8a7152bc5bd14ff1278b8/filebeat/input/journald/input_parsers_test.go#L34-L62

I will close this issue for now, but if for some reason it still does not work, just re-open this issue ;)

**Comment by belimawr** [comment]
There is also an example in the reference documentation: https://github.com/elastic/beats/blob/main/filebeat/filebeat.reference.yml#L1183-L1186

**Comment by qwinkler** [comment]
@belimawr Maybe I'm doing something wrong, but it doesn't work **at all**.
Here's my new `filebeat.yml` from the example you provided and the filebeat's behavior:
```
root@9274460c556d:/usr/share/filebeat# cat filebeat.yml
filebeat.inputs:
- type: journald
  enabled: true
  id: everything
  seek: cursor
  paths: ["/var/log/journal"]
  parsers:
  - multiline:
    type: pattern
    pattern: '^\{'
    negate: true
    match: after

output.file:
  enabled: true
  path: "/tmp/logs/"
  filename: filebeat.log

logging:
  level: warning
  to_files: false
  to_syslog: false
  json: true
root@9274460c556d:/usr/share/filebeat# filebeat version
filebeat version 8.6.0 (amd64), libbeat 8.6.0 [561a3e1839f1a50ce832e8e114de399b2bee2542 built 2023-01-04 01:28:13 +0000 UTC]
root@9274460c556d:/usr/share/filebeat# filebeat -e -c filebeat.yml
{"log.level":"warn","@timestamp":"2023-01-13T15:34:31.068Z","log.origin":{"file.name":"beater/filebeat.go","file.line":164},"message":"Filebeat is unable to load the ingest pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the ingest pipelines or are using Logstash pipelines, you can ignore this warning.","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2023-01-13T15:34:31.072Z","log.origin":{"file.name":"beater/filebeat.go","file.line":290},"message":"Filebeat is unable to load the ingest pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the ingest pipelines or are using Logstash pipelines, you can ignore this warning.","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2023-01-13T15:34:31.074Z","log.logger":"input","log.origin":{"file.name":"v2/loader.go","file.line":102},"message":"EXPERIMENTAL: The journald input is experimental","service.name":"filebeat","input":"journald","stability":"Experimental","deprecated":false,"ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-01-13T15:34:31.082Z","log.origin":{"file.name":"instance/beat.go","file.line":1071},"message":"Exiting: Failed to start crawler: starting input failed: error while initializing input: error while parsing multiline parser config: unknown matcher type:  accessing 'filebeat.inputs.0.parsers.0.multiline' accessing 'filebeat.inputs.0' (source:'filebeat.yml')","service.name":"filebeat","ecs.version":"1.6.0"}
Exiting: Failed to start crawler: starting input failed: error while initializing input: error while parsing multiline parser config: unknown matcher type:  accessing 'filebeat.inputs.0.parsers.0.multiline' accessing 'filebeat.inputs.0' (source:'filebeat.yml')
root@9274460c556d:/usr/share/filebeat# filebeat -e -c filebeat.yml
{"log.level":"warn","@timestamp":"2023-01-13T15:34:33.701Z","log.origin":{"file.name":"beater/filebeat.go","file.line":164},"message":"Filebeat is unable to load the ingest pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the ingest pipelines or are using Logstash pipelines, you can ignore this warning.","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2023-01-13T15:34:33.702Z","log.origin":{"file.name":"beater/filebeat.go","file.line":290},"message":"Filebeat is unable to load the ingest pipelines for the configured modules because the Elasticsearch output is not configured/enabled. If you have already loaded the ingest pipelines or are using Logstash pipelines, you can ignore this warning.","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"warn","@timestamp":"2023-01-13T15:34:33.703Z","log.logger":"input","log.origin":{"file.name":"v2/loader.go","file.line":102},"message":"EXPERIMENTAL: The journald input is experimental","service.name":"filebeat","input":"journald","stability":"Experimental","deprecated":false,"ecs.version":"1.6.0"}
```
So, the first start wasn't successful. However, the second run was fine. First of all, what is this random behavior? Secondly, the logs directory doesn't exist and filebeat don't gives any warnings. I created a directory and there are no logs:
```
root@9274460c556d:/usr/share/filebeat# ls -l /tmp/logs/
ls: cannot access '/tmp/logs/': No such file or directory
root@9274460c556d:/usr/share/filebeat# mkdir -p /tmp/logs/
root@9274460c556d:/usr/share/filebeat# ls -la /tmp/logs/
total 8
drwxr-xr-x 2 root root 4096 Jan 13 15:36 .
drwxrwxrwt 1 root root 4096 Jan 13 15:36 ..
root@9274460c556d:/usr/share/filebeat# date
Fri Jan 13 15:39:12 UTC 2023
root@9274460c556d:/usr/share/filebeat#
```

**Comment by belimawr** [comment]
@qwinkler,

Maybe the problem is with your data so the multiline parser has not "finished" (it is still waiting for the condition to send the event be reached).

Some suggestions to help identify the problem:
## 1. Run log level debug for all loggers
You can do that by using the following logging configuration:
```yaml
logging:
  level: debug
  selectors: ["*"]
  to_files: false
  to_syslog: false
  json: true
```

## 2. Look at the test and use that file as example
One of the annoying things about testing journald is that the file is not human readable, and the file is a bit annoying to create.
So try using the file we use in our tests:  https://github.com/elastic/beats/blob/878f026103df1d4b8fa8a7152bc5bd14ff1278b8/filebeat/input/journald/testdata/input-multiline-parser.journal with the same configuration there. If that works play with the regexp option and that file to identify if it's a bug on Filebeat or just a configuration issue

## 3. Dump the contents of your file
You can use `journalctl --file=<filepath>` to "dump" the contents in a human-readable way and use something like https://regex101.com/ to validate your regexp is actually working as you expect

## Open a Discuss thread
If none of this solves your problem, please do open a Discuss thread. We keep GitHub issues only for confirmed bugs. Also on Discuss there are more people who will also be able to help you. Feel free to directly tag me on Discuss if you don't manage to solve the problem.

**Comment by lisuml** [comment]
@qwinkler : I stumbled on the similar, if not identical issue. It took me a while to debug and investigate, but it was worth it as I was able to solve my issue.

I started from filebeat 7.17.8 with the following config of mine:
```
filebeat.inputs:
- type: journald
  id: myservice
  include_matches:
    - _SYSTEMD_UNIT=myserviceservice
  multiline.type: pattern
  multiline.pattern: ^[[:space:]]
  multiline.match: after
  multiline.negate: false
  tags: [ 'myservice' ]

output.logstash:
  enabled: true
  hosts: [ 'X.X.X.X:5044' ]
```
The effect was that while logs were being delivered to my logstash and then to elasticsearch, yet multiline rules were ignored.

I then updated filebeat to 8.6.0 and hoped for the best, with no changes to my config. The effect was identical to the previous case, so I started to investigate and tried the following config:
```
filebeat.inputs:
- type: journald
  id: myservice
  include_matches:
    - _SYSTEMD_UNIT=myservice.service
  parsers:
    - multiline:
      type: pattern
      pattern: ^[[:space:]]
      match: after
      negate: false
  tags: [ 'myservice' ]

output.logstash:
  enabled: true
  hosts: [ 'X.X.X.X:5044' ]
``` 
This time the logs was not being transited to logstash and filebeat has started to behave unstable. I checked if there is any outbound traffic on port 5044 with tcpdump but there was none. Also, each time I tried to stop or restart filebeat service via systemd, it was taking long time and hitting the systemd timeout at the end.

Next try was with the following config:
```
filebeat.inputs:
- type: journald
  id: myservice
  include_matches:
    - _SYSTEMD_UNIT=myservice.service
  parsers:
    - multiline:
        type: pattern
        pattern: ^[[:space:]]
        match: after
        negate: false
  tags: [ 'myservice' ]

output.logstash:
  enabled: true
  hosts: [ 'X.X.X.X:5044' ]
```
(note additional indentation level for `type`, `pattern`, `match` and `negate` under `- multiline:` section)

This did the the trick and the logs started to flow, and multiline rules started to be considered.

So, to wrap things up:
- multiline in jounrald input plugin seems to be working only with filebeat 8
- pay attention to the indentation

And last, but not least, @belimawr : not sure if the behaviour is expected or not, but IMO, the old multiline options syntax should be respected in newer versions of filebeat or at least there should be an explicit warning/error about their deprecation. Same for having wrong indentation, which was really misleading, considering that even `filebeat test config` or debug logs didn't give a hint. Not mentioning, that even you was not able to spot the indentation issue in one of the previous @qwinkler snippet... :smirk: .
