### ISSUE TITLE
Heartbeat fails to add a new monitor if host port differs from service port

### ISSUE THREAD

**Issue by gsantoro** [elastic/beats#34214]
For confirmed bugs, please report:
- Version: 7.17 -> 8.6.0 (current main)
- Operating System: any (not relevant)
- Discuss Forum URL: https://discuss.elastic.co/t/heartbeat-auto-discovery-generates-second-monitor-which-is-always-down/315491/12 (similar issue to be solved together)
- Steps to Reproduce:  
1. heartbeat with autodiscover enabled (sample config for `heartbeat.yml`)

```yaml
heartbeat.autodiscover:
 providers:
   - type: kubernetes
     resource: pod
     scope: cluster
     node: ${NODE_NAME}
     hints.enabled: true

   - type: kubernetes
     resource: service
     scope: cluster
     node: ${NODE_NAME}
     hints.enabled: true
     output.console:
       enabled: true
       pretty: true
```

2. start a sample service like

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name:  nginx-svc
  namespace: default
  labels:
    app:  nginx-svc
spec:
  selector:
    matchLabels:
      app: nginx-svc
  replicas: 1
  template:
    metadata:
      labels:
        app:  nginx-svc
    spec:
      containers:
      - name:  nginx-svc
        image: nginx:1.23.1-alpine
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 300m
            memory: 200Mi
          limits:
            cpu: 300m
            memory: 200Mi
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: default
  annotations:
    co.elastic.monitor/1.hosts: 127.0.0.1:30000
    co.elastic.monitor/1.schedule: '@every 5s'
    co.elastic.monitor/1.type: tcp
spec:
  selector:
    app: nginx-svc
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30000
    name: main
```

3. a new monitor will be added to Kibana with no URL. This monitor will always be down.
