### ISSUE TITLE
filebeat external prospector configuration settings

### ISSUE THREAD

**Issue by urso** [elastic/beats#3430]
introducing support for prospector reloading and modules + disabling/deprecating `config_dir` support (with slightly different use-case), we should see if the use-cases can be combined.

Proposed filebeat configuration:

```
filebeat.config:
  prospectors:
    path: ...
    reload:
      enabled:
      period: 10s

  modules:
    path: ...
    ...
```

this way, (even with reloading disabled), one can still move the prospectors from a big filebeat.yml into the `filebeat.config.prospectors.path` (the original `config_dir` use case).

**Comment by ruflin** [comment]
Bringing also defaults into the game here to have all the upcoming options on the table: https://github.com/elastic/beats/pull/3073

```
filebeat.config:
  prospectors:
    path: ...
    reload:
      enabled:
      period: 10s

  modules:
    path: ...
    ...
  
  defaults:
    prospectors:
      ...
```

The above has two limitations from my point of view (which I'm totally ok with):

* You can only use reloading on all of your config files or not using it. As solution for the "constant" once, the filebeat.yml can be used.
* Defaults: Only the global default can be overwritten. Nothing "template" like that 10 prospectors of this type and 10 of this type. Not a feature we need at the moment as with reloading most config files will be auto generated anyways so this happens in the code of the user.
