### ISSUE TITLE
Beats under agent shouldn't enable debug logging if it's set in the output

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#34320]
cc @cmacknz 
Under elastic-agent, if you enable debug logging in the output section of a config like this:
```
outputs:
  default:
    log_level: debug
    type: elasticsearch
    hosts: [https://127.0.0.1:9200]
    username: elastic
    password: changeme
    shipper:
      enabled: true
```
It will enable debug logging globally in beats, presumably because we're setting the log level in beats every time we get a new unit. 

This behavior seems a bit non-intuitive. If I set the log level in the `outputs` section, I would assume that would just affect any output components, such as the shipper. I'm also not sure if this is something that should be fixed in the agent, or in beats. Should agent be more discriminating in how it forwards log level changes, or should beats ignore any log level changes on the output units? Another possibility is that beats should try to change log levels in a more granular way, but considering how global the loggers are, that might not be possible.
