### ISSUE TITLE
Replace container input with filestream input in hints' default config

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#34354]
In  filebeat's hints based autodiscovery the raw `container` input is the default configuration that will be used if there is no `module` specified in the hints. See https://github.com/elastic/beats/blob/25786cdda70b31cb1738373265bf3a0f3dec76f6/filebeat/autodiscover/builder/hints/config.go#L29. 

I think we need to adjust it properly and adopt the usage of filestreams instead, which is now the recommended log input framework.

**Comment by gizas** [comment]
We will need testing with docker and kubernetes containers (just adding it as a note)

cc @gsantoro

**Comment by ChrsMark** [comment]
> We will need testing with docker and kubernetes containers (just adding it as a note)
> 
> cc @gsantoro

@gizas do you mean that we need to cover the `docker` autodiscovery part as well? I only had the `kubernetes` autodiscovery in mind tbh but if we change the underline default config for logs then it should cover both providers. If you see at https://github.com/elastic/beats/blob/edcba336d2b4871b7bd6c081fea25fafc2eb6bd8/libbeat/autodiscover/providers/docker/docker.go#L343-L346 the Builder that is called is the same (in k8s and docker provider) so the same default config would be returned. In this regard yes we need to verify that both providers work after this change (I wouldnt expect that one of them could not work but just to be sure).

Other than this, if the `container` parser is defined with `auto` in the `format` section then the parser will be capable to handle both `cri` and `docker` format. So no big deal hear I think (again testing this would be helpful).

**Comment by gizas** [comment]
> do you mean that we need to cover the docker autodiscovery part as well?

Yes indeed. As long as this change affects both (docker and k8s autodiscovery) that is why I would like to see tests for both scenarios, to be on safe side.

And we should update our doc examples for that. It needs to be part of the goals of this story

**Comment by gsantoro** [comment]
Adding some context about the reason this was raised https://github.com/elastic/beats/issues/13140#issuecomment-1172026775

**Comment by gsantoro** [comment]
I have already run some quick tests about using `filestream` as default config with filebeat.autodiscover like the below

```yaml
    filebeat.autodiscover:
     providers:
       - type: kubernetes
         node: ${NODE_NAME}
         hints.enabled: true
         hints.default_config:
           type: filestream
           paths:
             - /var/log/containers/*${data.kubernetes.container.id}.log
           parsers:
             - container:
               stream: all
               format: auto
```

and I got the following errors

```json
{"log.level":"error","@timestamp":"2023-01-13T15:26:33.794Z","log.logger":"input","log.origin":{"file.name":"input-logfile/manager.go","file.line":182},"message":"filestream input with ID '' already exists, this will lead to data duplication, please use a different ID","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-01-13T15:26:37.520Z","log.logger":"input","log.origin":{"file.name":"input-logfile/manager.go","file.line":176},"message":"filestream input ID without ID might lead to data duplication, please add an ID and restart Filebeat","service.name":"filebeat","ecs.version":"1.6.0"}
```

If I understand correctly, @gizas was suggesting yesterday that similarly to how we have an id field at https://github.com/elastic/integrations/blob/main/packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs maybe we should have something similar in the default config. I haven't tested any of this but it is worth keeping truck of this here.

**Comment by ChrsMark** [comment]
> If I understand correctly, @gizas was suggesting yesterday that similarly to how we have an id field at https://github.com/elastic/integrations/blob/main/packages/kubernetes/data_stream/container_logs/agent/stream/stream.yml.hbs maybe we should have something similar in the default config. I haven't tested any of this but it is worth keeping truck of this here.

Yes that's a known "issue"/"feature". We will need an `id` here too I guess to fix this.

**Comment by cmacknz** [comment]
@gsantoro Yes, that is not a bug it is a misconfiguration. Every filestream input needs a unique ID field. From https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html:

> Each filestream input must have a unique ID. Omitting or changing the filestream ID may cause data duplication. Without a unique ID, filestream is unable to correctly track the state of files

Agent takes this even further and requires a unique ID for every input in the policy, not just filestream.

If we fix this problem, does it work?

**Comment by gsantoro** [comment]
> Agent takes this even further and requires a unique ID for every input in the policy, not just filestream.

> If we fix this problem, does it work?

I have no idea. That's a good question for who is picking up this ticket.

**Comment by rdner** [comment]
Please don't forget to put `take_over: true` on the `filestream` config, otherwise customers would experience data duplication.

See https://github.com/elastic/beats/pull/34292

**Comment by BenB196** [comment]
FYI, in case anyone else wants to transition to filestream for auto-discovery, here is a working config:

```yaml
filebeat.autodiscover:
  providers:
    - type: kubernetes
      node: ${NODE_NAME}
      hints:
        enabled: true
        default_config:
          type: filestream
          id: kubernetes-container-logs-${data.kubernetes.pod.name}-${data.kubernetes.container.id}
          paths:
            - /var/log/containers/*${data.kubernetes.container.id}.log
          prospector.scanner.symlinks: true: # Optional, but most people probably use symlinks
          parsers:
          - container:
              stream: all
              format: auto
```

Doesn't include the `take_over: true`, but can be added if you're using Filebeat 8.7+
