### ISSUE TITLE
Beats rendered config contains some typos/issues

### ISSUE THREAD

**Issue by belimawr** [elastic/beats#34360]
- Version: 8.6 and above
- Operating System: All

When the Elastic-Agent diagnostics is generated, the Beat will send it's 'rendered config' to be added to the diagnostics bundle, however current the generated file is not a fully working Beat config.

### 1. Deploy a standalone Elastic-Agent with a simple config:
```yaml
id: standalone-policy-hand-crafted
outputs:
  default:
    type: elasticsearch
    password: <REDACTED>
    username: elastic
    hosts:
      - 'https://es.elastic-cloud.com:443'
agent:
  download:
    sourceURI: 'https://artifacts.elastic.co/downloads/'
  monitoring:
    enabled: true
    use_output: default
    namespace: default
    logs: true
    metrics: true
inputs:
  - id: log-input-like-the-integration-input-id
    name: log-input
    type: logfile
    use_output: default
    data_stream:
      namespace: default
    streams:
      - id: log-input-like-the-integration-stream-id
        data_stream:
          dataset: generic
        paths:
          - /tmp/flog*
```

2. Start the Elastic-Agent and collect diagnostics
```
./elastic-agent &
./elastic-agent diagnostics collect
```

3. Look the Beat configuration
For the example above, extract the diagnostics bundle, and look for the file:
```
components/log-default/log-input-like-the-integration-input-id/beat-rendered-config.yml
```
 Its contents will be:
```yaml
inputs:
- data_stream:
    dataset: generic
  id: log-input-like-the-integration-stream-id
  index: logs-generic-default
  paths:
  - /tmp/flog*
  processors:
  - add_host_metadata:
      when:
        not:
          contains:
            tags: forwarded
  - add_cloud_metadata: null
  - add_docker_metadata: null
  - add_kubernetes_metadata: null
  - add_fields:
      fields:
        input_id: log-input-like-the-integration-input-id
      target: '@metadata'
  - add_fields:
      fields:
        dataset: generic
        namespace: default
        type: logs
      target: data_stream
  - add_fields:
      fields:
        dataset: generic
      target: event
  - add_fields:
      fields:
        stream_id: log-input-like-the-integration-stream-id
      target: '@metadata'
  - add_fields:
      fields:
        id: 8104514a-d3ad-49f5-af81-e268a114a461
        snapshot: false
        version: 8.7.0
      target: elastic_agent
  - add_fields:
      fields:
        id: 8104514a-d3ad-49f5-af81-e268a114a461
      target: agent
  type: log
outputs:
  elasticsearch:
    allow_older_versions: true
    bulk_max_size: 50
    hosts:
    - https://es.elastic-cloud.com:443
    password: <REDACTED>
    type: elasticsearch
    username: elastic
```

## There are two small mistakes
1. The first line should be prefixed by the Beat name:
```
filebeat.inputs:
```

Instead of:
```
inputs:
```

2. The `outputs` key should be singular `output`
