### ISSUE TITLE
Support the ingest of the source address and the source port separately

### ISSUE THREAD

**Issue by narph** [elastic/beats#34371]
Related 
https://github.com/elastic/beats/pull/9460
https://github.com/elastic/ecs/pull/247 

We have introduced `log.source.address` for TCP/UDP input which  is contains both the IP and the port like 127.0.0.1:8080.
However, neither the IP nor the port are collected separately, which means that it usually involves a dissect operation to get either the IP or the port separately for data analysis (e.g. aggregation of unique IPs).

```
- if.has_fields: [log.source.address]
    then:
      - dissect:
          field: log.source.address
          target_prefix: log.source
          tokenizer: '%{ip}:%{port}'
      - convert:
          ignore_missing: true
          fields:
            - from: log.source.port
              type: integer
```

Can we consider introducing separate fields for ip/port?
