### ISSUE TITLE
Filebeat CEL input - basic auth does not work

### ISSUE THREAD

**Issue by a03nikki** [elastic/beats#34609]
- Version:  8.6.2
- Operating System:  MacOS Venture 13.2.1
- Discuss Forum URL:
- Steps to Reproduce: 

    1. Download latest version of Filebeat, extract, and update filebeat.yml
    1. Add CEL input that points at a URL that requires username and password
       a. <https://www.elastic.co/guide/en/beats/filebeat/8.6/filebeat-input-cel.html#_auth_basic_enabled>
       b. https://github.com/elastic/beats/pull/31233
    2. Run Filebeat
        ```bash
        ./filebeat -v
        ```
    3. Review log files
    4. Search the code for the possible problem.  It _appears_ the config may not be passed on the request.
        a. https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/cel/input.go
        b. `func newClient` has logic for OAuth but not basic

<details>
<summary> metricbeat.yml </summary>

```yaml
filebeat.inputs:
- type: cel
  id: cel-1
  interval: 1m
  resource.url: https://api.ipify.org/?format=json
  resource.tracer.filename: logs/cel-1.trace.log
  program: |
    bytes(get(state.url).Body).as(body, {
        "events": [body.decode_json()]
    })
  enabled: true
- type: cel
  id: cel-2
  interval: 1m
  resource.url: https://REDACTED.es.us-east-2.aws.elastic-cloud.com/
  auth.basic.enabled: true
  auth.basic.user: REDACTED
  auth.basic.password: REDACTED
  auth.oauth2.enabled: false
  resource.tracer.filename: logs/cel-2.trace.log
  program: |
     bytes(get(state.url).Body).as(body, {
          "events": [body.decode_json()]
     })
  enabled: true


filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
setup.kibana:

cloud.id: REDACTED
cloud.auth: REDACTED

output.elasticsearch:

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~


logging.level: debug
logging.selectors: ["*"]

monitoring.enabled: true
monitoring.cluster_uuid: REDACTED
```
</details>

<details>
<summary> logs</summary>

```json
% head -n2 cel-2.trace.log
{"log.level":"debug","@timestamp":"2023-02-17T14:25:50.343-0600","message":"HTTP request","transaction.id":"907UAHJFMP21E-1","url.original":"https://REDACTED.es.us-east-2.aws.elastic-cloud.com/","url.scheme":"https","url.path":"/","url.domain":"REDACTED.es.us-east-2.aws.elastic-cloud.com","url.port":"","url.query":"","http.request.method":"GET","user_agent.original":"","http.request.body.content":"","http.request.body.bytes":0,"http.request.mime_type":"","event.original":"GET / HTTP/1.1\r\nHost: REDACTED.es.us-east-2.aws.elastic-cloud.com\r\nUser-Agent: Go-http-client/1.1\r\nAccept-Encoding: gzip\r\n\r\n","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2023-02-17T14:25:50.494-0600","message":"HTTP response","transaction.id":"907UAHJFMP21E-1","http.response.status_code":401,"http.response.body.content":"{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication credentials for REST request [/]\",\"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\",\"Bearer realm=\\\"security\\\"\",\"ApiKey\"]}}],\"type\":\"security_exception\",\"reason\":\"missing authentication credentials for REST request [/]\",\"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\",\"Bearer realm=\\\"security\\\"\",\"ApiKey\"]}},\"status\":401}","http.response.body.bytes":459,"http.response.mime_type":"application/json;charset=utf-8","event.original":"HTTP/1.1 401 Unauthorized\r\nConnection: close\r\nContent-Type: application/json;charset=utf-8\r\nDate: Fri, 17 Feb 2023 20:25:50 GMT\r\nWww-Authenticate: Basic realm=\"security\" charset=\"UTF-8\"\r\nWww-Authenticate: Bearer realm=\"security\"\r\nWww-Authenticate: ApiKey\r\nX-Cloud-Request-Id: M3_hK0hSTOCwhVTfSRbiNw\r\nX-Found-Handling-Cluster: REDACTED\r\nX-Found-Handling-Instance: instance-0000000000\r\n\r\n{\"error\":{\"root_cause\":[{\"type\":\"security_exception\",\"reason\":\"missing authentication credentials for REST request [/]\",\"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\",\"Bearer realm=\\\"security\\\"\",\"ApiKey\"]}}],\"type\":\"security_exception\",\"reason\":\"missing authentication credentials for REST request [/]\",\"header\":{\"WWW-Authenticate\":[\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\",\"Bearer realm=\\\"security\\\"\",\"ApiKey\"]}},\"status\":401}","ecs.version":"1.6.0"}
```
</details>
