### ISSUE TITLE
Filebeat CEL input - string library functions not recognized

### ISSUE THREAD

**Issue by a03nikki** [elastic/beats#34610]
For confirmed bugs, please report:
- Version:  8.6.2
- Operating System: MacOS Venture 13.2.1
- Discuss Forum URL:
- Steps to Reproduce: 

1. Download latest version of Filebeat, extract, and update filebeat.yml
2. Add CEL input that points at a URL that requires username and password
    a. <https://www.elastic.co/guide/en/beats/filebeat/8.6/filebeat-input-cel.html>
      > "Use the cel input to read messages from a file path or HTTP API with a variety of payloads using the [Common Expression Language (CEL)](https://opensource.google.com/projects/cel) and the [mito](https://pkg.go.dev/github.com/elastic/mito/lib) and [ext Strings](https://pkg.go.dev/github.com/google/cel-go@v0.12.5/ext#Strings) CEL extension libraries."
       
    b. https://github.com/elastic/beats/pull/31233
 3. Run Filebeat
     ```bash
     ./filebeat -v -e
     ```
4. Review the output
5. Search the code for the possible problem.  It _appears_ the ext library is not even included
    a. https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/cel/input.go
        i. The import includes `"github.com/google/cel-go/cel"` and `"github.com/google/cel-go/checker/decls"` but does not include `"github.com/google/cel-go/ext"`
        ii. `func newProgram(` does not include `String()` as an option similar to an [example](https://github.com/elastic/harp/blob/v0.2.10/pkg/bundle/ruleset/engine/cel/engine.go#L44) I was looking at
    b. https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/cel/input_test.go
        i. I only found references to functions in `mito` and the `cel` language standard.  I didn't find any tests that included any of the string methods.

<details>
<summary> metricbeat.yml </summary>

```yaml
filebeat.inputs:
- type: cel
  id: cel-1
  interval: 1m
  resource.url: https://api.ipify.org/?format=json
  program: |
    string(get(state.url).Body).as(body, {
        "events": [{ "message": body, "type_is_string": string(type(body) == string), "tags": body.split('i') }]
    })
  enabled: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 1
setup.kibana:

cloud.id: REDACTED
cloud.auth: REDACTED

output.elasticsearch:

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
  - add_kubernetes_metadata: ~


logging.level: debug
logging.selectors: ["*"]

monitoring.enabled: true
monitoring.cluster_uuid: REDACTED
```
</details>

<details>
<summary> logs</summary>

Before adding the `split` function

![image](https://user-images.githubusercontent.com/2642763/219810733-c12b0308-4ee5-40dd-b46c-d60566aed11b.png)

After adding the split function with `, "tags": body.split('i')`:

```json
{"log.level":"info","@timestamp":"2023-02-17T16:37:22.739-0600","log.origin":{"file.name":"instance/beat.go","file.line":491},"message":"filebeat stopped.","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2023-02-17T16:37:22.739-0600","log.origin":{"file.name":"instance/beat.go","file.line":1071},"message":"Exiting: Failed to start crawler: starting input failed: error while initializing input: failed to check program: failed compilation: ERROR: <input>:2:101: undeclared reference to 'split' (in container '')\n |     \"events\": [{ \"message\": body, \"type_is_string\": string(type(body) == string), \"tags\": body.split('i') }]\n | ....................................................................................................^ accessing 'filebeat.inputs.0' (source:'filebeat.yml')","service.name":"filebeat","ecs.version":"1.6.0"}
Exiting: Failed to start crawler: starting input failed: error while initializing input: failed to check program: failed compilation: ERROR: <input>:2:101: undeclared reference to 'split' (in container '')
 |     "events": [{ "message": body, "type_is_string": string(type(body) == string), "tags": body.split('i') }]
 | ....................................................................................................^ accessing 'filebeat.inputs.0' (source:'filebeat.yml')
```
</details>
