### ISSUE TITLE
[Filebeat][httpjson] Need to use last request body in pagination request

### ISSUE THREAD

**Issue by brijesh-elastic** [elastic/beats#34628]
While using request_body_on_pagination: true, we are not able to access the body of the last request in the `response.pagination`

**Example :**
```
request.transforms:
  - set:
      target: body.vulnerability
      value: 'modified > [[formatDate (parseDate .cursor.last_update_time) "RFC3339"]]'
response.request_body_on_pagination: true
response.pagination:
  - set:
      target: body.vulnerability
      value: '[[.last_response]]'
      fail_on_template_error: true
```

In here, we got below value of last_response object. there isn't any sub_object of last_request body.

`{"body":{"data":[{"url":"example.com"},{"url":"example.org"}],"metadata":{"cursor":null,"number":0,"size": 2,"totalResources": 81631,"totalPages": 40816
}},"header":{"Access-Control-Allow-Origin":["*"],"Content-Length":["257"],"Content-Type":["application/json; charset=utf-8"],"Date":["Tue, 21 Feb 2023 11:50:38 GMT"],"Etag":["W/\\"101-Ce6RFsRTYU4ck7k+hEQZ6mBIC8\\""],"X-Powered-By":["Express"]},"page":2,"url":"xxxxx"}`

**Describe a specific use case for the enhancement or feature:**

While creating Rapid7 InsightVM integration
https://help.rapid7.com/insightvm/en-us/api/integrations.html#operation/searchIntegrationVulnerabilities
