### ISSUE TITLE
[Filebeat][Salesforce] Enhancement to add configurable look back time

### ISSUE THREAD

**Issue by kush-elastic** [elastic/beats#34661]
**Describe the enhancement:**
Current [salesforce module](https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-module-salesforce.html) does not support to add configuration to limit historical data collection.
it will collect all the data available in the salesforce instance. it would be better to have configuration to limit number of events user wants to collect.

Latest salesforce supports up to [store 6 months of data](https://help.salesforce.com/s/articleView?id=release-notes.rn_security_em_rtem_ga.htm&release=222&type=5#:~:text=You%20can%20also%20store%20this%20event%20data%20for%20up%20to%20six%20months.).

The objective of the configuration is to:
- Have users control of how much historical data is loaded to elastic
- Avoid a situation of data explosion, by loading un-controlled duration of historical data.

**Comment by lalit-satapathy** [comment]
> it would be better to have configuration to limit

What will be the configuration parameters? Will it be based on _CreatedDate_ and _LogDate_ ?

Does Salesforce provide any way to filter based on a size limit?

**Comment by lalit-satapathy** [comment]
Can the configuration be similar to [ignore_older](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#filebeat-input-log-ignore-older) mechanism in logs or re-use that config?

**Comment by kush-elastic** [comment]
Hey @lalit-satapathy,
I looked into this and found one possible solution which can help user to provide days in number to collect data.

So basically user can provide this configuration:
Example:
```
apex-rest:
    enabled: true
    var.client_id: "3MVXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXpmL97qJSsbL9.A1Z.NekEFkCmw7B"
    var.client_secret: "9064E9XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXCB3CC9029F706C7E61"
    var.token_url: "https://login.salesforce.com/services/oauth2/token"
    var.user: "user.name@mail.com"
    var.password: "PASSWORD"
    var.url: "https://instance123-ed.develop.my.salesforce.com"
    var.number_of_days: 3
```
**var.number_of_days: 3** will collect data for the past 3 days of data.

WDYT?

**Comment by lalit-satapathy** [comment]
FYI - @ruflin

**Comment by kush-elastic** [comment]
FYI- Default will be 1 day.

**Comment by kush-elastic** [comment]
Hey @lalit-satapathy,
While working on the above solution we think of few situations that might affect users.
1. if the user configures an initial interval less than salesforce's minimum time of logfile creation time (less than 3-6 hours), they will not get any data populated as that data will be available after a few hours in salesforce itself.
2. also, it is possible that even with a better interval(more than 6 hours), there are chances that it will still not be collected properly from salesforce. as there are chances that salesforce doesn't have logs in those hours.

To solve this we thought of doing something similar to the below by storing the first evaluated time in cursor. we are trying to figure out if we can somehow do it.

Below configuration is just an example. we are still facing issues with it.
```
type: httpjson
interval: 1h
request.method: GET
auth.oauth2:
  enabled: true
  client.id: {{ .client_id }}
  client.secret: {{ .client_secret }}
  token_url: {{ .token_url }}
  user: {{ .user }}
  password: {{ .password }}
request.url: {{ .url }}/services/data/v52.0/query?q=apex+rest
request.transforms:
  - set:
      target: url.params.q
      value: "SELECT Id,CreatedDate,LogDate,LogFile FROM EventLogFile WHERE Interval = 'Hourly' AND LogDate >= [[.cursor.last_published_apex]] AND (EventType = 'ApexCallout' OR EventType = 'ApexExecution' OR EventType = 'ApexRestApi' OR EventType = 'ApexSoap' OR EventType = 'ApexTrigger' OR EventType = 'ExternalCustomApexCallout') ORDER BY LogDate ASC NULLS FIRST"
      default: SELECT Id,CreatedDate,LogDate,LogFile FROM EventLogFile WHERE Interval = 'Hourly' AND LogDate >= [[formatDate (now (parseDuration "-{{.initial_interval}}"))]] AND (EventType = 'ApexCallout' OR EventType = 'ApexExecution' OR EventType = 'ApexRestApi' OR EventType = 'ApexSoap' OR EventType = 'ApexTrigger' OR EventType = 'ExternalCustomApexCallout') ORDER BY LogDate ASC NULLS FIRST
response.transforms:
  - set:
      target: body.lastCall
      value: '[[.cursor.last_published_apex]]'
      default: '[[formatDate (now (parseDuration "-{{.initial_interval}}"))]]'
cursor:
  last_published_apex:
    value: '[[(formatDate ((parseDate .last_event.TIMESTAMP_DERIVED "RFC3339").Add (parseDuration "-1h")))]]'
    default: '[[.first_event.lastCall]]'
```
