### ISSUE TITLE
when.equals type example is missing its parent "fields"

### ISSUE THREAD

**Issue by LucaWintergerst** [elastic/beats#3474]
The example for using when.equals [here](https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html) is missing its parent "fields"

it is supposed to look like this:
```
  pipelines:
    - pipeline: critical_pipeline
      when.equals:
        fields.type: "critical"
    - pipeline: normal_pipeline
      when.equals:
        fields.type: "normal"
```

I verified this with @urso 

He also recommended that we could simplify this example to:
```
filebeat.prospectors:
- paths: ["/var/log/app/normal/*.log"]
  fields:
    type: "normal"
- paths: ["/var/log/app/critical/*.log"]
  fields:
    type: "critical"

output.elasticsearch:
  hosts: ["http://localhost:9200"]
  index: "filebeat-%{+yyyy.MM.dd}"
  pipeline: '%{[fields.type]}'
```

We should also consider adding a small section describing how to use the when.equals and when.contains, especially if we change the pipelines example with the .equals
