### ISSUE TITLE
Can't assume role in filebeat cloudwatch input when IAM policy can assume multiple roles

### ISSUE THREAD

**Issue by wangjia007bond** [elastic/beats#34749]
- Version: 7.17.5
- Team: filebeat
- Operating System: Docker
- Discuss Forum URL: https://discuss.elastic.co/t/cant-assume-role-in-filebeat-cloudwatch-input-when-iam-policy-can-assume-multiple-roles/327159
- Steps to Reproduce: 
- 
We are using filebeat 7.17.5, and we are using CloudWatch input, we want to retrieve log from another AWS account b and AWS account c.
So in filebeat AWS role, we have a policy which allow to assume roles for other two accounts.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Resource": [
                "arn:aws:iam::111111111111:role/role-a-in-account-a",
                "arn:aws:iam::222222222:role/role-b-in-account-b"
            ],
            "Effect": "Allow"
        }
    ]
}
```

but in filebeat, I found error:

```
2023-03-07T09:08:07.177Z ERROR [aws-cloudwatch] awscloudwatch/input.go:216 failed DescribeLogGroupsRequest: InvalidParameter: 1 validation error(s) found.
minimum field size of 20, AssumeRoleInput.RoleArn.
```

filebeat cloudwatch plugin works when single account in policy to assume, ie
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "sts:AssumeRole",
            "Resource": "arn:aws:iam::111111111111:role/role-a-in-account-a",
            "Effect": "Allow"
        }
    ]
}
```

does anyone facing this issue?

Cheers,

**Comment by sqrooted** [comment]
What does your filebeat config look like? Do you specify the role_arn to assume in the config?

The following setup works for me (on filebeat 8.7.0):

```yaml
filebeat.inputs:
      - type: aws-cloudwatch
        log_group_arn: arn:aws:logs:eu-west-1:ACCOUNT_B_ID:log-group:GROUPNAME:*
        role_arn: arn:aws:iam::ACCOUNT_B_ID:role/ROLENAME_IN_ACCOUNT_B
        start_position: beginning
        number_of_workers: 2
```

Filebeat is running on K8s pod, the pod is using a [serviceaccount with AWS role binding](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html), role is created in account A and in account B there's another role with trust policy in place for role A in account A to assume it. So in effect, filebeat is assuming a secondary role in account B through an initial service role in account A.

The error you're seeing seems more related to invalid value in `role_arn` in filebeat config, maybe you're not setting a full ARN (only role name) there?
