### ISSUE TITLE
Filebeat syslog guesses dates in the future, not the past

### ISSUE THREAD

**Issue by darkpixel** [elastic/beats#34779]
Today is March 8th 2023.
I have a log file that contains data back to October 2022.

When I point filebeat at it:
```
  - type: log
    paths:
      - /var/log/remote.log
    processors:
      - add_host_metadata: ~
      - add_cloud_metadata: ~
      - syslog:
          field: message
          format: auto
          ignore_missing: false
          ignore_failure: false
```

and it ingests a line like this:
```
Oct  5 16:23:18 192.168.142.100 core[651]:  core dbus_callback()
```

It guesses the date is October 5th 2023 even though we haven't reached October 5th 2023 and it's much more likely that it's data from October 5th 2022.

I'm guessing filebeat does something where it looks at the current year (2023) and just adds that on to the partial date that syslog spits out.
