### ISSUE TITLE
Processor errors can cause the Beat pipeline to enter what appears to be an infinite loop

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#34792]
This was first observed in https://github.com/elastic/beats/issues/34716, which describes a case of this problem triggered by the `attempt to use a closed processor` error. The trigger for this problem turned out to be unexpected processor reuse, but even with processor reuse the system should have remained functional and been able to publish events. The processor reuse should ideally result in a warning log instead of a complete failure.

It is not clear why the Beat was publishing the following log line up to 10K times per second:

```json
{"log.level":"error","@timestamp":"2023-03-02T11:59:42.394Z","message":"Failed to publish event: attempt to use a closed processor","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-monitoring","type":"filestream"},"log":{"source":"filestream-monitoring"},"log.logger":"publisher","log.origin":{"file.line":102,"file.name":"pipeline/client.go"},"service.name":"filebeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
```

The scope of this issue is to identify the mechanism causing the Beat to loop continuously trying to publish the failed event when a closed processor error is detected, instead of logging a warning or dropping the event and continuing normally (not all events may pass through the affected processor for example).

**Comment by cmacknz** [comment]
The error appears to be come from https://github.com/elastic/beats/blob/9cd74f90ac7a7126b66daa430f38eda0f00f0556/libbeat/publisher/pipeline/client.go#L94-L104

This doesn't look like it should do anything other than log the error.

**Comment by faec** [comment]
My guess based on what I've seen is that some early part of the pipeline got into an infinite retry loop with a closed processor or events associated with it. A reasonable way to troubleshoot might be to intentionally inject a closed processor into the pipeline and confirm that ingestion can continue with ~1 logged error per processor failure.

**Comment by rdner** [comment]
@P1llus the error reported by the logs in the description has been resolved by https://github.com/elastic/beats/pull/34761 

This issue is not about that error itself but about the behaviour of our processing pipeline when it faces an unrecoverable error. This should not cause an infinite loop.

Did I get your question right?

**Comment by rdner** [comment]
I've tried to reproduce this issue by building a custom Filebeat from 2f7ff01798d23bc5790c1a98e372bca087d502c6 with this patch:

```diff
diff --git a/libbeat/processors/safe_processor.go b/libbeat/processors/safe_processor.go
index a0bbf5824d..b32b344c0d 100644
--- a/libbeat/processors/safe_processor.go
+++ b/libbeat/processors/safe_processor.go
@@ -35,10 +35,7 @@ type SafeProcessor struct {
 
 // Run allows to run processor only when `Close` was not called prior
 func (p *SafeProcessor) Run(event *beat.Event) (*beat.Event, error) {
-	if atomic.LoadUint32(&p.closed) == 1 {
-		return nil, ErrClosed
-	}
-	return p.Processor.Run(event)
+	return nil, ErrClosed
 }
 
 // Close makes sure the underlying `Close` function is called only once.
```

And I ran this modified Filebeat under Elastic Agent with the configuration taken from [the original issue](https://github.com/elastic/beats/issues/34716):

```yaml
outputs:
  default:
    type: elasticsearch
    log_level: debug
    enabled: true
    hosts: [https://127.0.0.1:9200]
    username: "elastic"
    password: [password]
    allow_older_versions: true
    ssl:
      verification_mode: none
    shipper:
      enabled: true

inputs:
  - type: system/metrics
    id: unique-system-metrics-input
    data_stream.namespace: default
    use_output: default
    streams:
      - metricset: cpu
        data_stream.dataset: system.cpu
      - metricset: memory
        data_stream.dataset: system.memory
      - metricset: network
        data_stream.dataset: system.network
      - metricset: filesystem
        data_stream.dataset: system.filesystem
```

This is what I got in Elastic Agent logs:


https://github.com/elastic/beats/assets/887952/4579e3b9-90a9-42fb-8716-dfcf9a432fa3

The original issue description was reported as:

> Intermittently, the monitoring started by Agent enters a loop where it repeats this message ~10K times a second.

> This error is inconsistent -- on some runs it begins soon after startup, on many runs it never happens at all. When it does happen, it severely degrades or blocks other ingestion. Subsequent runs using identical configurations with identical binaries are still inconsistent as to whether this bug occurs.

I've failed to reproduce this behaviour, it seems like Filebeat logs a few errors, waits for some time (~10 seconds in my case) and retries but never goes into the described infinite loop.

Just in case I added a test in this PR https://github.com/elastic/beats/pull/37491
