### ISSUE TITLE
Winlogbeat and Kafka output failures

### ISSUE THREAD

**Issue by a-rnam** [elastic/beats#34821]
Hi,

I've problem with shipping logs to Kafka. Just after restarting Winlogbeat service the service sends some logs but later it stucks on retry attempts:

![image](https://user-images.githubusercontent.com/127849782/224987650-9858fe0e-bdf2-4772-b509-27d0dae30d1e.png)

The config is:

```
output.kafka:
  hosts: [#####]
  client_id: #####
  topic: '%{[topic]}'
  version: 2.0.0
  worker: 1
  bulk_max_size: 1000000
  bulk_flush_frequency: 0
  required_acks: 1
  compression: none
  max_message_bytes: 1000000
```

How can this issue be resolved?
