### ISSUE TITLE
[Filebeat][Httpjson] Httpjson pagination is failing if chain call ids are getting fetched on Splitted events

### ISSUE THREAD

**Issue by kush-elastic** [elastic/beats#34839]
Httpjson Pagination is not working for the following conditions,
1. if split is on where ids from the chain are collected.

example:

```
response.split:
  target: body.records
response.pagination:
  - set:
      target: url.value
      value: '[[if (ne .last_response.body.done true)]]{{ .url }}[[.last_response.body.nextRecordsUrl]][[end]]'
      fail_on_template_error: true
chain:
  - step:
      request.url: {{ .url }}/services/data/v52.0/sobjects/EventLogFile/$.records[:].Id/LogFile
      request.method: GET
      replace: $.records[:].Id
```

first response:
```
{
    "nextRecordsUrl": "/link2",
    "records": [
         {
             "Id": 1,
             "CreatedDate": "date",
         }
    ]
}
```

- Related #34661
- Related https://github.com/elastic/sdh-beats/issues/2720
