### ISSUE TITLE
input.filestream spams info log with "Reader was closed"

### ISSUE THREAD

**Issue by stucky101** [elastic/beats#35022]
Hey there
I was asked to file an issue regarding this discussion:

https://discuss.elastic.co/t/filebeat-10000s-of-messages-reader-was-closed-closing-011-flooding-log/329088

Filebeat agent version 8.6.2

Simple config example
```
logging.level: info
logging.to_syslog: true

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

filebeat.inputs:
- type: filestream
  id: log
  enabled: true
  paths:
    - /log/**/*

output.logstash:
  hosts: ["beats-host.domain.com:5044"]
  ssl.enabled: true

processors:
  - add_fields:
      target: "@socat"
      fields:
        token: "1234zxc"
```

thx

**Comment by andrewkroh** [comment]
This is the relevant code. This appears to be related to the normal operation of the input. I think this should be a debug message. The log line would also be more useful if it indicated the reason why the reader was closed (e.g. inactivity timeout, etc).

https://github.com/elastic/beats/blob/df59745ee01a9ffd86387160c0d63a7a4b5d8f5c/filebeat/input/filestream/input.go#L321

**Comment by cmacknz** [comment]
@belimawr @rdner can this log message be improved or the frequency reduced?

**Comment by belimawr** [comment]
It's not logged that often, it is only logged when the reader for a file is closed, unless they have tens of thousands files being read and then closed that message should not be logged that often. The whole log line they posted is also a bit odd

I'll take a quick look into that, trying to reproduce it.


@stucky101, could you check how many files you have on `/log/**/*`?

**Comment by belimawr** [comment]
I ran a very quick test, one interesting thing I noticed is that many fields from our log entries are not available when we log to syslog :scream: 

Here is the syslog and stderr log for the same `Reader was closed` message:
```
# Syslog
Apr 05 08:32:43 millennium-falcon filebeat[33284]: 2024-04-05T08:32:43.611+0200 INFO [input.filestream] map[file.line:321 file.name:filestream/input.go] Reader was closed. Closing.        {"ecs.version": "1.6.0"}

# Stderr/File
{"log.level":"info","@timestamp":"2024-04-05T08:30:33.856+0200","log.logger":"input.filestream","log.origin":{"file.name":"filestream/input.go","file.line":321},"message":"Reader was closed. Closing.","service.name":"filebeat","id":"filestream-id","source_file":"filestream::filestream-id::native::4307-34","path":"/tmp/logs/log.log","state-id":"native::4307-34","ecs.version":"1.6.0"}
```

The default for `close.on_state_change.inactive` is `5m`, there are also other things that will close the reader like the file being removed.

The `#011` string seems to be added  by your syslog, the output from my `journalctl -f` used spaces to separate the log from the ECS version.

Could you give us some more information about your system?
1. Which distro are you using?
2. Does it use systemd?
3. How are you reading the syslog?
4. As I asked on my last comment, how many files does the glob `/log/**/*` resolve to?
5. Are all those files actively being updated?
6. What is the throughput of your Filebeat (just a rough estimation)?

**Comment by belimawr** [comment]
Here is the config I used to test, the main difference is the close inactive set to `10s` and some registry/queue tuning to send events as soon as they're read.

```yaml
filebeat.inputs:
  - type: filestream
    id: filestream-id
    enabled: true
    paths:
      - /tmp/logs/*
    close.on_state_change.inactive: 10s
processors:
  - add_fields:
      target: "@socat"
      fields:
        token: "1234zxc"

filebeat.registry:
  cleanup_interval: 5s
  flush: 1s

queue.mem:
  events: 32
  flush.min_events: 8
  flush.timeout: 0.1s

output.file:
  path: ${path.home}
  filename: "output-file"
  rotate_every_kb: 1000000

logging:
  level: info
  to_syslog: true
  metrics:
    enabled: false
```
