### ISSUE TITLE
[Heartbeat] Synthetics args should filter out all dev related flags

### ISSUE THREAD

**Issue by vigneshshanmugam** [elastic/beats#35050]
### Summary

Browser monitors in Heartbeat has the feature where additional CLI flags can be passed to take advantage of the Synthetics agent capabilities via `synthetics_args` config. 
```yml
- type: browser
  id: test
  name: Test args
  schedule: '@every 1m'
  synthetics_args: --capability metrics 
  ...
```

### Proposal

Allow only non development related flags and blacklist to avoid flags like `--pause-on-error`, `--quiet-exit-code`,`--dry-run`, `--out-fd`, etc when the project is originated from the `UI`. Its still useful during the development purposes which is why we can discard these flags only for UI based monitors.
