### ISSUE TITLE
Add parse_aws_vpc_flow_log into aws-cloudwatch input

### ISSUE THREAD

**Issue by chyeyun** [elastic/beats#35077]
We are collecting vpc flow logs in Cloudwatch. That's why we are using aws-cloudwatch input to collect vpc flow logs through filebeat.
https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-aws-cloudwatch.html

Then, We tried to apply `parse_aws_vpc_flow_log` option in aws-cloudwatch input, but it didn't work. The 'message' field were not decoding. I think this option might be applied only in aws module.
https://www.elastic.co/guide/en/fleet/current/processor-parse-aws-vpc-flow-log.html#processor-parse-aws-vpc-flow-log
https://github.com/elastic/beats/pull/33699/files#diff-e94d67a97d5bf32554e4cef9d4d2ba5c281597c2fdf93ae46fd4fb4dbdf25624R90

Therefore, We would like to use `parse_aws_vpc_flow_log` option not only in aws module but also in aws-cloudwatch input . 
Is it possible to add that option to the aws-cloudwatch input?

**Comment by andrewkroh** [comment]
`parse_aws_vpc_flow_log` is implemented as a [processor](https://www.elastic.co/guide/en/beats/filebeat/current/defining-processors.html). Therefore, it is available to be used with all Filebeat inputs.

```yaml
filebeat.inputs:
- type: <any>
  
  processors:
    - parse_aws_vpc_flow_log:
        format: version account-id interface-id srcaddr dstaddr srcport dstport protocol packets bytes start end action log-status
        field: message
```
