### ISSUE TITLE
Add `default_field` option to `setup.template.append_fields`

### ISSUE THREAD

**Issue by n0othing** [elastic/beats#35070]
**Describe the enhancement:**

Similar to https://github.com/elastic/beats/pull/14341.

Today only `text` and `keyword` fields added via `setup.template.append_fields` are added to `settings.index.query.default_field` in the final Beat template. It'd be helpful to have a `default_fields: true|false` switch to add other data types. For example:

```YAML
setup.template.append_fields:
- name: account_number
  type: long
  default_field: true
```
