### ISSUE TITLE
Better handle unexpected types when using "conditions" on Beats

### ISSUE THREAD

**Issue by belimawr** [elastic/beats#35112]
When using templates with conditions on kubernetes autodiscovery like this:
```yaml
          templates:
            - condition:
                contains:
                  kubernetes.labels.app: elasticsearch
```

And the pod contains labels where `app` is an object like this:
```
Labels:           app.foo=elasticsearch
                  common.k8s.elastic.co/type=elasticsearch
```

Metricbeat will issue a log warning:
```
{"log.level":"warn","@timestamp":"2023-04-11T08:12:04.232Z","log.logger":"conditions","log.origin":{"file.name":"conditions/matcher.go","file.line":96},"message":"unexpected type mapstr.M in contains condition as it accepts only strings.","service.name":"metricbeat","ecs.version":"1.6.0"}
```
This comes from the following method:
https://github.com/elastic/beats/blob/1a647f4fad31a99523435adabee4825bfb581e90/libbeat/conditions/matcher.go#L72-L107

We should better handle `mapstr.M` to avoid issuing the log warn. Either we look into the object for the data or we just don't match due the type mismatch. Either way, there is no need for a log warn here.

We should keep logging on the `default` branch, but on debug level and add more information to it, like the name of the field.

Here is a more detailed Metricbeat config to reproduce the issue. For the pod, just set a label like `app.foo=elasticsearch`, then once Metricbeat is running you'll see the log warn.

```yaml 
   metricbeat.autodiscover:
      providers:
        - type: kubernetes
          scope: cluster 
          hints.enabled: true
          templates:
            - condition:
                contains:
                  kubernetes.labels.app: elasticsearch
              config:
                - module: elasticsearch
                  metricsets: # the metricsets are not really relevant as long as at leas one is enabled
                    - cluster_stats
                    - index
                    - index_summary
                    - node_stats
                    - node
                    - pending_tasks
                  period: 10s
                  scope: cluster
                  hosts: "https://elasticsearch:9200"
                  username: "elastic"
                  password: "foobar"
```
