### ISSUE TITLE
Fail to start Filebeat with couldn't unpack memory queue config

### ISSUE THREAD

**Issue by alexsapran** [elastic/beats#35198]
For confirmed bugs, please report:
- Version: main
- Operating System:  macOS
- Steps to Reproduce: 

With the following configuration if you start Filebeat you will see the following error

```yml
filebeat.inputs:
  - type: filestream
    id: my-filestream-id
    paths:
    - /var/log/*.log

output.console:
  pretty: true

monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["xxxxxxxx"]
  username: "elastic"
  password: "changeme"
```

Starting Filebeat with the above `./filebeat -c will_fail.yml` will result into the following error

```
Exiting: couldn't unpack memory queue config: requires value >= 32 accessing 'mem.events'
```
