### ISSUE TITLE
[Filebeat] `include_message` parser does not work with the filestream input

### ISSUE THREAD

**Issue by herrBez** [elastic/beats#35440]
## Metadata
- Version: 8.7.1
- Operating System:  Ubuntu 20.04.5 LTS
- Discuss Forum URL: N/A

## Steps to Reproduce: 

Configure the following input:
```yml
- type: filestream
  paths:
    - /tmp/test.log

  parsers:
  - include_message:
      patterns: ["^A", "^B"]
```

Filebeat will exit with the following error: `Exiting: Failed to start crawler: creating input reloader failed: include_message: no such parser accessing '0' (source:'/tmp/test.log')`

## Probable Cause

By looking at the [source](https://github.com/elastic/beats/blob/v8.7.1/libbeat/reader/parser/parser.go) code it seems that the include_message parser is not included in the `NewConfig` method as it has been done for the `Create` method.

## Definition of done ##

Target: 8.8.1
- [ ] `include_message` parser should be working as expected (include message matching the pattern)
- [ ] Filebeat in standalone and with Agent are able to start and be healthy when `include_message` is used
- [ ] Tests are in place to confirm that those behavior are working as expected
