### ISSUE TITLE
[Response required] Filebeat fails on reading message from Azure Event hub.

### ISSUE THREAD

**Issue by arnitolog** [elastic/beats#35515]
Hello, 
I'm using filebeat-oss v8.7.1 to read application Gateway logs from Azure Event Hub. And it started to fail because of the error below: 

```
{"log.level":"error","@timestamp":"2023-05-19T14:41:22.376Z","log.logger":"input.kafka.kafka input","log.origin":{"file.name":"kafka/input.go","file.line":420},"message":"Kafka desirializing multiple messages using the group object records","service.name":"filebeat","id":"CCDCBE01A5B7BCCD","hosts":["event-hub.servicebus.windows.net:9093"],"error":{"message":"invalid character '\\x1c' in string literal"},"ecs.version":"1.6.0"}
```

here is what I have as input:
```
    - type: kafka
      hosts: ["$eventhubhost"]
      topics: ["app-gateway"]
      group_id: "filebeat"
      fields:
        ProductComponents: application-gateway
      fields_under_root: true
      username: "$ConnectionString"
      password: "$password"
      ssl.enabled: true
      version: '1.0.0'
      expand_event_list_from_field: "records"
```

is it possible to configure the input to ignore the message in case of a serialization error?
