### ISSUE TITLE
[Beats][GCS Input] Enhancement to add support for .1 extension file.

### ISSUE THREAD

**Issue by piyush-elastic** [elastic/beats#35560]
While configuring `Goggle Cloud Storage` input in `Filebeat` to unzip `gzip` folder and fetch data from `.1` extension file,  we are getting the below error:

`{"@timestamp":"2023-05-24T10:09:08.931Z","@metadata":{"beat":"filebeat","type":"_doc","version":"8.6.0","_id":"ec-32653-s1/cloud_funnel/2023/05/24/account_id=139xxxxxxxxxxx4369781/2023-05-24T08-45-00Z.1.gz-worker-2"},"event":{"kind":"publish_error"},"message":"job with jobId ec-32653-s1/cloud_funnel/2023/05/24/account_id=139xxxxxxxxxxx4369781/2023-05-24T08-45-00Z.1.gz-worker-2 encountered an error : content-type application/octet-stream not supported","input":{"type":"gcs"},"ecs":{"version":"8.0.0"},"host":{"name":"localhost.localdomain"},"agent":{"name":"localhost.localdomain","type":"filebeat","version":"8.6.0","ephemeral_id":"8db0b41d-xxxx-4455-xxxx-1969b2612281","id":"aca45c75-xxxx-xxxx-832d-4266ec7aebd7"}}`

Find `Filebeat` configuration code as below:
```
filebeat.inputs:
- type: gcs
  id: my-gcs-id
  enabled: true
  project_id: ec-33646
  auth.credentials_file.path: "/root/beats/x-pack/filebeat/gcs-service-key.json"
  buckets:
  - name: ec-32653
    max_workers: 5
    poll: true
    poll_interval: 15s
    bucket_timeout: 60s
output.file:
  path: "/root/beats/x-pack/filebeat/"
  filename: "s1_cloud_Funnel_logs"
````
  
  As mentioned in [documentation](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-gcs.html#filebeat-input-gcs), `Goggle Cloud Storage` input supports only `json` and `ndjson` format.
