### ISSUE TITLE
panic from replace processor

### ISSUE THREAD

**Issue by morganchristiansson** [elastic/beats#35671]
- Filebeat version: 7.8.1
- Operating System: Linux (ECK)

Using replace processor from tcp input:
```
    filebeat:
      inputs:
        - type: tcp
          host: 0.0.0.0:9000
          id: tcp
          processors:
            - rename:
                fields:
                  - from: message
                    to: jenkins
            - decode_json_fields:
                fields: ["jenkins"]
                target: "jenkins"
            - replace:
                fields:
                  - field: jenkins.message
                    pattern: '^\[\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}.\d{3}Z\] '
                    replacement: ""
                ignore_missing: true
                fail_on_error: false
```

I'm trying to strip the timestamp prefix from lines like these (jenkins.message field):
```
[2023-06-04T14:13:14.966Z] {:time=>2023-05-30 20:00:00 UTC, :value=>7590, :area_id=>33}
```

Getting this error and filebeat is dropping the event.
```
{
	"log.level": "error",
	"@timestamp": "2023-06-04T14:23:55.336Z",
	"log.logger": "tcp",
	"log.origin": {
		"file.name": "logp/logger.go",
		"file.line": 218
	},
	"message": "Panic in connection handler. Recovering, but please report this.{panic 26 0  interface conversion: interface {} is []interface {}, not string} {stack 15 0 github.com/elastic/elastic-agent-libs/logp.(*Logger).Recover\n\tgithub.com/elastic/elastic-agent-libs@v0.3.3/logp/logger.go:218\nruntime.gopanic\n\truntime/panic.go:884\nruntime.panicdottypeE\n\truntime/iface.go:262\ngithub.com/elastic/beats/v7/libbeat/processors/actions.(*replaceString).replaceField\n\tgithub.com/elastic/beats/v7/libbeat/processors/actions/replace.go:114\ngithub.com/elastic/beats/v7/libbeat/processors/actions.(*replaceString).Run\n\tgithub.com/elastic/beats/v7/libbeat/processors/actions/replace.go:87\ngithub.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Run\n\tgithub.com/elastic/beats/v7/libbeat/publisher/processing/processors.go:129\ngithub.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Run\n\tgithub.com/elastic/beats/v7/libbeat/publisher/processing/processors.go:129\ngithub.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).publish\n\tgithub.com/elastic/beats/v7/libbeat/publisher/pipeline/client.go:97\ngithub.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).Publish\n\tgithub.com/elastic/beats/v7/libbeat/publisher/pipeline/client.go:76\ngithub.com/elastic/beats/v7/filebeat/beater.(*countingClient).Publish\n\tgithub.com/elastic/beats/v7/filebeat/beater/channels.go:136\ngithub.com/elastic/beats/v7/filebeat/input/tcp.(*server).Run.func1\n\tgithub.com/elastic/beats/v7/filebeat/input/tcp/input.go:138\ngithub.com/elastic/beats/v7/filebeat/inputsource/common/streaming.SplitHandlerFactory.func1.1\n\tgithub.com/elastic/beats/v7/filebeat/inputsource/common/streaming/handler.go:82\ngithub.com/elastic/beats/v7/filebeat/inputsource/common/streaming.(*Listener).handleConnection\n\tgithub.com/elastic/beats/v7/filebeat/inputsource/common/streaming/listener.go:202\ngithub.com/elastic/beats/v7/filebeat/inputsource/common/streaming.(*Listener).run.func2\n\tgithub.com/elastic/beats/v7/filebeat/inputsource/common/streaming/listener.go:175 <nil>}",
	"service.name": "filebeat",
	"address": "0.0.0.0:9000",
	"remote_address": "192.168.1.124:3195",
	"ecs.version": "1.6.0"
}
```
```
Panic in connection handler. Recovering, but please report this.{panic 26 0  interface conversion: interface {} is []interface {}, not string} {stack 15 0 github.com/elastic/elastic-agent-libs/logp.(*Logger).Recover
        github.com/elastic/elastic-agent-libs@v0.3.3/logp/logger.go:218
runtime.gopanic
        runtime/panic.go:884
runtime.panicdottypeE
        runtime/iface.go:262
github.com/elastic/beats/v7/libbeat/processors/actions.(*replaceString).replaceField
        github.com/elastic/beats/v7/libbeat/processors/actions/replace.go:114
github.com/elastic/beats/v7/libbeat/processors/actions.(*replaceString).Run
        github.com/elastic/beats/v7/libbeat/processors/actions/replace.go:87
github.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Run
        github.com/elastic/beats/v7/libbeat/publisher/processing/processors.go:129
github.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Run
        github.com/elastic/beats/v7/libbeat/publisher/processing/processors.go:129
github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).publish
        github.com/elastic/beats/v7/libbeat/publisher/pipeline/client.go:97
github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).Publish
        github.com/elastic/beats/v7/libbeat/publisher/pipeline/client.go:76
github.com/elastic/beats/v7/filebeat/beater.(*countingClient).Publish
        github.com/elastic/beats/v7/filebeat/beater/channels.go:136
github.com/elastic/beats/v7/filebeat/input/tcp.(*server).Run.func1
        github.com/elastic/beats/v7/filebeat/input/tcp/input.go:138
github.com/elastic/beats/v7/filebeat/inputsource/common/streaming.SplitHandlerFactory.func1.1
        github.com/elastic/beats/v7/filebeat/inputsource/common/streaming/handler.go:82
github.com/elastic/beats/v7/filebeat/inputsource/common/streaming.(*Listener).handleConnection
        github.com/elastic/beats/v7/filebeat/inputsource/common/streaming/listener.go:202
github.com/elastic/beats/v7/filebeat/inputsource/common/streaming.(*Listener).run.func2
        github.com/elastic/beats/v7/filebeat/inputsource/common/streaming/listener.go:175 <nil>}
```

Not obvious why it's panicking. I've triple checked regex and processor syntax.
