### ISSUE TITLE
Filebeat ignores additional config files on syntax error

### ISSUE THREAD

**Issue by breml** [elastic/beats#3572]
If additional config files are defined with `filebeat.config_dir` and thous config files do have yaml syntax errors, these errors are silently ignored and filebeat is started normally. This is also true, if `-configtest` is used.

Version: current master

Steps to reproduce:

Have a filebeat.yml with `filebeat.config_dir: /tmp/filebeat` set.
Have an additional config file `/tmp/filebeat/syntax_error.yml` with content:

```
filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/*.log
  exclude_files: [".gz\$"]
```

(the syntax error is in the last line, `\$` is not a valid escape character.)
