### ISSUE TITLE
[Beats] Hints autodiscovery support with Filestream input

### ISSUE THREAD

**Issue by gizas** [elastic/beats#35984]
**Describe the enhancement:**
The [filestream input](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html) is the suggested input type for log processing with filebeat.

The hints autodiscovery is based on container input type (see [code here](https://github.com/elastic/beats/blob/25786cdda70b31cb1738373265bf3a0f3dec76f6/filebeat/autodiscover/builder/hints/config.go#L29)) . So by default logs will be retrieved from the container using the container input. 

So with this enhancement request we would like users to define hints based autodiscovery with filestream input type and to be able:
1. To use the existing `co.elastic.logs/*` annotations in the hints annotations of the application pods and
2. The annotations configure the relevant parsers of the filestream input

**Describe a specific use case for the enhancement or feature:**

Filebeat configuration:
```yaml
filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: filestream
            prospector.scanner.symlinks: true
            id: filestream-kubernetes-pod-${data.kubernetes.container.id}
            take_over: true
            paths:
            - /var/log/containers/*-${data.kubernetes.container.id}.log
            parsers:
            - container: ~
```
See above that `type: filestream`

The user will define in the pod:
```yaml
annotations:
        co.elastic.logs/json.add_error_key: "true"
        co.elastic.logs/json.expand_keys: "true"
        co.elastic.logs/json.ignore_decoding_error: "true"
        co.elastic.logs/json.keys_under_root: "true"
        co.elastic.logs/json.message_key: "message"
```

And those will produce the following block:
```yaml
parsers:
   - ndjson: 
         ignore_decoding_error: "true"
         expand_keys: "true"
         keys_under_root: "true"
         message_key: "message"
```

So overall configuration of filebeat should transform to:

```yaml
filebeat.autodiscover:
      providers:
        - type: kubernetes
          node: ${NODE_NAME}
          hints.enabled: true
          hints.default_config:
            type: filestream
            prospector.scanner.symlinks: true
            id: filestream-kubernetes-pod-${data.kubernetes.container.id}
            take_over: true
            paths:
            - /var/log/containers/*-${data.kubernetes.container.id}.log
            parsers:
            - container: ~
            - ndjson: 
                ignore_decoding_error: "true"
                expand_keys: "true"
                keys_under_root: "true"
                message_key: "message"
```

**Same logic needs to be supported for rest of parsers**

This was also previously discussed at https://github.com/elastic/beats/issues/34354. Check also that one for additional context.
