### ISSUE TITLE
NUL terminator byte breaks fortinet firewall module

### ISSUE THREAD

**Issue by efd6** [elastic/beats#36026]
When an appliance sends NUL-terminated syslog lines via TCP, we end up with a NUL in the event.original and in the last structured data field as it's rendered into the document. The Fortinet Fortigate integration approaches this by [`gsub`ing the NUL away](https://github.com/elastic/integrations/blob/91f0919751a21ad5d0e839d7e6f07c53db3ce8cb/packages/fortinet_fortigate/data_stream/log/elasticsearch/ingest_pipeline/default.yml#L27-L30)
```
  - gsub:
      field: syslog5424_sd
      pattern: "\u0000"
      replacement: ""
```
The same should happen in the filebeat module.
