### ISSUE TITLE
output.kafka erroniously logs established connections

### ISSUE THREAD

**Issue by wcallgair** [elastic/beats#36062]
While troubleshooting a configuration error I noticed the kafka output was logging `Connection to kafka established` when connecting to a kafka host with the incorrect port defined.

Upon further testing in QA this established message will appear with any port as long as the dns entry resolves.

For example: 
`{"log.level":"info","@timestamp":"2023-07-13T18:17:09.975Z","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/client_worker.go","file.line":137},"message":"Connecting to kafka(kafka.example.com:5555)","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2023-07-13T18:17:09.975Z","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/client_worker.go","file.line":145},"message":"Connection to kafka(kafka.example.com:5555) established","service.name":"filebeat","ecs.version":"1.6.0"}
`

Version:  filebeat version 8.8.2 (amd64), libbeat 8.8.2
Operating System: centos 8.x
Steps to Reproduce: 
- Set output.kafka.host to any valid dns entry
- Set output.kafka.hos to any port (in my example 5555)
- Restart filebeatt

Example config:

```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/boot
    - /var/log/cron
    - /var/log/dmesg
    - /var/log/firewalld
    - /var/log/grubby
    - /var/log/maillog
    - /var/log/secure
    - /var/log/messages
  fields:
    kafka_topic: "beats-systemlogs"

output.kafka:
  enabled: true
  hosts: ["kafka.example.com:5555"]
  topic: '%{[fields.kafka_topic]}'
  compression: gzip

http.enabled: true
logging.metrics.enabled: false
logging.level: info
logging.to_files: true
logging.files:
  rotateonstartup: false
  path: /var/log/filebeat
  name: info
  keepfiles: 0
  permissions: 0644
```
