### ISSUE TITLE
[Metricbeat][mongodb module]: 'replstatus' causing increased mongo disk space usage

### ISSUE THREAD

**Issue by michaljrk** [elastic/beats#36110]
After mongodb replica upgrade to v6  in our Kubernetes cluster, we have noticed a significant disk space usage increase on one of the nodes in a short time. Further investigation revealed that there are multiple `extsort-doc-group.XX` file generated in in mongodb `<data_dir>/_tmp` subdirectory. 

The files were gone after mongo container restart, but few minutes later they were eating up ~30GB again.
Luckily, I came across this [mongo forum thread ](https://www.mongodb.com/community/forums/t/issue-when-upgrading-mongodb-4-4-8-to-6-0-4/215424/4) where someone pointed out it was metricbeat causing the issue. And it is confirmed, after removing `- replstatus` from `metricsets` config, the issue no longer appears.

**- Version:** ` metricbeat:8.6.2`
**- Operating System:**  `ECK stack on 1.21 k8s cluster, host: Ubuntu 20.04`
**- Steps to Reproduce:**  
Point metricbeat mongodb module against mongo v6 replicaset cluster with `replstatus` metric in the config:
```
....
  config:
    metricbeat:
      modules:
      - module: mongodb
        metricsets:
          - status
          - replstatus
          - dbstats
        hosts:
          - host-0.mongo.default.svc.cluster.local:27017
        period: 30s
 ....
 ```
after few minutes, mogodb `_tmp` subdirectory should be filled up with multiple `extsort-doc-group.XX` files consuming significant amount of space (might depend on the db data size probably).
