### ISSUE TITLE
Azure Monitor Integration Stopped working After Upgrade 8.8.1 to 8.9

### ISSUE THREAD

**Issue by jigar82** [elastic/beats#36170]
- Version: 8.9.0
- Operating System: 
- Discuss Forum URL:
- Steps to Reproduce: 

1) Upgrade Elastic Agent from 8.8.1 to 8.9.0 
2) Azure monitor integration failing , there are many error but below 400 error could be an issue
3) Below message is for Load balancer but it was reported that  azure db , azure appservices and azure lb metrics are also not coming and there can be more, 

```
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadRequest
--------------------------------------------------------------------------------
{
  "code": "BadRequest",
  "message": "Received invalid query parameter: [api-version, 2018-01-01],[metricnamespace, ], TraceId: {c8013967-5348-4563-9c76-c87af720b35e} for request: subscriptions/subc/resourceGroups/rgroup1/providers/Microsoft.Network/loadBalancers/lb/providers/Microsoft.Insights/metricDefinitions"
} 
```

**Comment by endorama** [comment]
This issue is the counterpart of https://github.com/elastic/beats/issues/36181

In `8.8.1` the configuration mentioned in the linked issue (reported here):

```yaml
  - ignore_unsupported: true
    metrics:
    - name:
      - '*'
    namespace: Microsoft.Web/sites # wrong indentation, should be within the metric
    resource_query: resourceType eq 'Microsoft.Web/sites'
```

was not triggering any error (even if data collection was still negatively affected).  
Since `8.9.0` this configuration triggers a `400` error. We tracked changes in the Azure SDK in 8.9.0 (see https://github.com/elastic/beats/pull/33585) as probable cause for this issue

Note that it happens only with **an invalid configuration** which is now correctly reported as error.

I'm closing this issue, please keep track of the linked issue for further enhancements.
