### ISSUE TITLE
[Azure] Metricbeat fails with error 400 Bad Request when collecting logs using the `azure.monitor` metricset

### ISSUE THREAD

**Issue by zmoog** [elastic/beats#36181]
Collecting metrics using the `azure.monitor` fails in Metricbeat and Agent version 8.9.0 with the following error:

```
Error fetching data for metricset azure.monitor: no metric definitions were found for resource /subscriptions/<REDACTED>/providers/Microsoft.Insights/metricDefinitions
--------------------------------------------------------------------------------
RESPONSE 400: 400 Bad Request
ERROR CODE: BadRequest
--------------------------------------------------------------------------------
{
  \"code\": \"BadRequest\",
  \"message\": \"Received invalid query parameter: [api-version, 2018-01-01],[metricnamespace, ], TraceId: {c8013967-5348-4563-9c76-c87af720b35e} for request: subscriptions/<REDACTED>/providers/Microsoft.Insights/metricDefinitions\"
}
--------------------------------------------------------------------------------
```

For confirmed bugs, please report:
- Version: 8.9.0
- Operating System: Linux

## Steps to Reproduce

Enable the Azure module or an Agent integration using the following custom configuration:

```yaml
  - ignore_unsupported: true
    metrics:
    - name:
      - '*'
    namespace: Microsoft.Web/sites
    resource_query: resourceType eq 'Microsoft.Web/sites'
```

With this configuration, Metricbeat 8.9.0 fails while it is trying to fetch the metrics definitions. However, Metricbeat 8.8.1 reports no error and it able to collect metrics.
