### ISSUE TITLE
[filebeat ASA Module] outbound traffic log is parsed in reverse for the source and destination IP

### ISSUE THREAD

**Issue by Keunwool** [elastic/beats#36206]
Hi.

I am collecting logs using the cisco asa module, and the outbound traffic log is parsed in reverse for the source and destination IP.

eg) DNS query traffic

![image](https://github.com/elastic/beats/assets/12420202/a28be540-1aa1-4c78-80f7-5138db3d3061)

elasticsearch 8.8.1
kibana 8.8.1
filebeat 8.8.2

/modules.d/cisco.yml

```
- module: cisco
  asa:
    enabled: true

    var.syslog_host: 0.0.0.0
    #var.internal_zones: [ "Internal" ]
    #var.external_zones: [ "External" ]
    #var.timezone_offset: UTC
```

discuss.elastic.co
[https://discuss.elastic.co/t/filebeat-asa-module-outbound-traffic-log-is-parsed-in-reverse-for-the-source-and-destination-ip/339269/1](url)
