### ISSUE TITLE
`take_over: true` is ignored when using input configuration from external files

### ISSUE THREAD

**Issue by rdner** [elastic/beats#36378]
If inputs are set via the external file configuration using: https://www.elastic.co/guide/en/beats/filebeat/8.9/filebeat-configuration-reloading.html#load-input-config the `take_over` parameter is ignored and log inputs won't migrate to filestream causing data duplication and reset offsets for each affected file.

This happens because the take-over configuration is initialised only from the `filebeat.inputs` section and does not take into account external files:

https://github.com/elastic/beats/blob/eca0a0bb71d89b639f9026f7fda2373f7bbb7704/filebeat/input/filestream/takeover/takeover.go#L144-L171

**Comment by fixed77** [comment]
filebeat 8.15.0. problem returned

**Comment by nix-power** [comment]
I confirm: 8.15.0 problem exists. using filebeat in the container.

**Comment by nix-power** [comment]
@rdner - can this one be reopened please ?

**Comment by rdner** [comment]
@fixed77 @nix-power do you mean your use-case worked before 8.15.0 and with the 8.15.0 release it broke again? I don't recall any change in 8.15.0 that could affect this functionality.

Can you post an example of your configuration files that can verify the bug is back? Thanks in advance.

**Comment by nix-power** [comment]
Hi, thanks for the reploy. 
I did not try this feature in the previous versions, i try to migrate from `8.4.1` to `8.15.0` and eventually to use the change to migrate from the `log` to the `filestream`  input. The following configuration is not working, and events are duplicated. But i don't thinks it is related ti this specific bug
```
 filebeat.inputs:
      - type: filestream
        enabled: true
        id: myapp-log-filestream
        take_over: true
        fields_under_root: true
        fields:
          SUB_SYSTEM: 'myapp_log'
        paths:
          - 'path/to/app_log'
        close_inactive: 2m
        ignore_older: 5m
        prospector.scanner.symlinks: true
        parsers:
          - multiline:
              pattern: '^\[?[0-9]{1,}[[:space:]]'
              negate: true
              match: after
```

filebeat is running in the docker container, and the configuration file `filebeat.yml` mounted to /usr/share/filebeat/filebeat.yml inside the container.

**Comment by fixed77** [comment]
filebeat 8.15.0
there is a working filebit with the configuration:

filebeat.yml:
```
#=========================== Filebeat inputs =============================
filebeat.config:
  inputs:
    enabled: true
    path: inputs.d/*.yml
    reload.enabled: false
    reload.period: 60s
    clean_removed: false
    close_removed: false
    clean_renamed: false
    close_renamed: false
    close_timeout: 1h
```

inputs.d/nginx.yml
```
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
```

let's try switching to filestream. change inputs.d/nginx.yml to:
```
- type: filestream
  id: fs-nginx-accesslog
  take_over: true
  enabled: true
  paths:
    - /var/log/nginx/access.log
```
and restart filebeat.
data is duplicated and there is no mention of take_over in the logs.

if all input files move to the main filebeat.yml config, then everything goes well
