### ISSUE TITLE
[Logging Plugin / dockerlogbeat] No ability to specify tags to apply to fowarded logs

### ISSUE THREAD

**Issue by bplies-ATX** [elastic/beats#36421]
**Describe the enhancement:**
https://www.elastic.co/guide/en/beats/loggingplugin/current/log-driver-configuration.html provides no means of supplying tags that should be used to decorate log events shipped to Elasticsearch.

By contrast, Elastic Agent ([docs](https://www.elastic.co/guide/en/fleet/current/filter-agent-list-by-tags.html#add-tags-at-enrollment)) allows:
```
docker run \
  --env FLEET_ENROLL=1 \
  --env FLEET_URL=<Fleet Server host URL> \
  --env FLEET_ENROLLMENT_TOKEN=<enrollment token> \
  --env ELASTIC_AGENT_TAGS=docker,dev
  --rm docker.elastic.co/beats/elastic-agent:8.9.1
```

**Describe a specific use case for the enhancement or feature:**
In situations where one has multiple, named instances within an environment it isn't currently possible to identify their logs using their common identifier.  For example if a QA environment has numbered stacks: `qa1`, `qa2`, .... `qa100` there isn't a way to convey that identifier to the Logging Plugin.  Without this information one must know or be able to find some other identifier such as a hostname or IP which isn't as descriptive.

```
version: '2.3'
services:
  some_service:
    image: "IMAGE_URL"
    logging:
      driver: "elastic/elastic-logging-plugin:8.9.1"
      options:
        host: "${elasticsearch_endpoint}"
        user: "user"
        password: "password"
        index: "someindex" # Can this even be a datastream??
       # That's pretty much the limit of the useful things one can customize
```

Contrast that with a competitor's
```
version: '2.3'
services:
  some_service:
    image: "IMAGE_URL"
    logging:
      driver: "sumologic"
      options:
        sumo-url: "${sumo_endpoint}"
        sumo-batch-size: "1000000"
        sumo-queue-size: "100"
        sumo-sending-interval: "500ms"
        sumo-compress: "true"
        sumo-compress-level: "3"
        sumo-source-host: "${moniker}-${server_number}"
        sumo-source-name: "${moniker}-${server_number}-some_service"
        tag: "${moniker}-${server_number}-some_service"
```
