### ISSUE TITLE
add_process_metadata - process.env enrichment not working

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#36469]
When `restricted_fields: true` is enabled then the `process.env.*` fields should be populated. But that is not working.

```
    - add_process_metadata:
        match_pids: [process.pid]
        overwrite_keys: true
        ignore_missing: true
        cgroup_prefixes: []
        cgroup_regex: '([0-9a-f]{64})(\.scope)?$'
        restricted_fields: true
```

The code that collects the metadata does not fetch any environment variables.

https://github.com/elastic/beats/blob/16e2989a001afcd5b094e9b5ff0b7540da618eb5/libbeat/processors/add_process_metadata/gosysinfo_provider.go#L51-L61
