### ISSUE TITLE
Filebeat 8.9.2 defender_atp module triggers AADSTS901002: The 'resource' request parameter is not supported.

### ISSUE THREAD

**Issue by ict-one-nl** [elastic/beats#36555]
Filebeat 8.9.2 docker container

Error:
`{"log.level":"error","@timestamp":"2023-09-11T14:57:30.894Z","log.logger":"input.httpjson-cursor","log.origin":{"file.name":"httpjson/input.go","file.line":172},"message":"Error while processing http request: failed to execute rf.collectResponse: failed to execute http client.Do: failed to execute http client.Do: failed to read http.response.body: Get \"https://api.securitycenter.windows.com/api/alerts?%24expand=evidence&%24filter=lastUpdateTime+gt+2023-09-11T14%3A52%3A30.7822429Z\": oauth2: cannot fetch token: 400 Bad Request\nResponse: {\"error\":\"invalid_request\",\"error_description\":\"AADSTS901002: The 'resource' request parameter is not supported.\\r\\nTrace ID: b9cb83b0-a8d3-4063-9096-5b6028f1cc00\\r\\nCorrelation ID: xxxx\\r\\nTimestamp: 2023-09-11 14:57:30Z\",\"error_codes\":[901002],\"timestamp\":\"2023-09-11 14:57:30Z\",\"trace_id\":\"xxxx\",\"correlation_id\":\"xxxxx\"}","service.name":"filebeat","id":"FDB7E76E5E8E50F7","input_source":"https://api.securitycenter.windows.com/api/alerts","input_url":"https://api.securitycenter.windows.com/api/alerts","ecs.version":"1.6.0"`

Config:
```
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

logging.level: error
logging.to_stderr: true

filebeat.modules:
- module: microsoft
  defender_atp:
    enabled: true
    var.oauth2.client.id: "xxxxx"
    var.oauth2.client.secret: "xxxxx"
    var.oauth2.token_url: "https://login.microsoftonline.com/xxxxx/oauth2/v2.0/token"


# output.console:
#   pretty: true

output.kafka:
  hosts: ["kafka-1:9091", "kafka-2:9092", "kafka-3:9093"]
  topic: "microsoft-defender-atp"
  client_id: "microsoft-defender-atp"
  required_acks: 1
  compression: none

```

AzureAD config:

![image](https://github.com/elastic/beats/assets/2643715/cb32b618-43f4-46a8-93ae-a34e9892302f)
