### ISSUE TITLE
[new processor idea] MAC vendor / OUI lookup

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#36560]
**Describe the enhancement:**

Create a processor to enrich events containing MAC addresses with the associated vendor name.

```yaml
processors
  - mac_vendor: # Or perhaps oui_lookup.
      field: source.mac
      target_field: source.Mac_vendor
      ignore_missing: true
```

**Describe a specific use case for the enhancement or feature:**

When reviewing network data, particularly DHCP, it can be useful to know the hardware vendor. It's another clue that can be used when trying to understand the behavior of a device.

### Related info

- example lookup behavior - https://www.wireshark.org/tools/oui-lookup.html
- authoritative into - https://standards.ieee.org/faqs/regauth/
- oui data sources - https://gitlab.com/wireshark/wireshark/-/blob/18f47c198866dc87d91f2116d254838661192b6c/tools/make-manuf.py#L225-230
- It would be useful to identify these ranges as a "Locally Administered Address". Apple and other vendors use these ranges for randomized addresses. https://serverfault.com/questions/40712/what-range-of-mac-addresses-can-i-safely-use-for-my-virtual-machines
- possible implementation algorithm for longest prefix matching - https://github.com/torvalds/linux/blob/0bb80ecc33a8fb5a682236443c1e740d5c917d1d/kernel/bpf/lpm_trie.c
