### ISSUE TITLE
[filebeat][httpjson] - Read access to [.url.params.*] object from config

### ISSUE THREAD

**Issue by ShourieG** [elastic/beats#36568]
Currently httpjson provides write only access to [.url.params.*] for setting attributes via the config. In certain scenarios we me need to access currently set attributes in the url query param in successive query param attribute. 
Such an use case is evident from this PR: https://github.com/elastic/integrations/pull/7726. Currently we require work arounds to this in certain scenarios which are not ideal. 

A sample example to demonstrate such a use case: 

```yml
filebeat.inputs:
- type: httpjson
  interval: {{interval}}
  request.method: GET
  request.url: http://{{host}}/some/api
  request.transforms:
    - set:
        target: url.params.start
        value: '[[formatDate (parseTimestamp (.cursor.last_execution_datetime).Unix) ]]'
        default: '[[formatDate (((now).Add (parseDuration "-1m")).Add (parseDuration "-1h"))]]'
    - set:
        target: url.params.end
        value: '[[formatDate (parseTimestamp (((.url.params.Get "start").Unix).Add (parseDuration "1h"))) ]]'
        default: '[[formatDate (parseTimestamp (((.url.params.Get "start").Unix).Add (parseDuration "1h"))) ]]'
```
Here the **"end"** query params are calculated based on the **"start"** query param. In this scenario having read access to **"start"** makes life much easier and also avoids re-calculation of **"now"** which might slightly differ from the value of **"now"** used in **"start"**
