### ISSUE TITLE
Why can’t I use a self-named index name?

### ISSUE THREAD

**Issue by mark8s** [elastic/beats#36654]
Hello everyone, I have a question.

I use filebeat to collect container logs on virtual machines. The installation method is binary installation. The download resource address is: https://www.elastic.co/cn/downloads/past-releases/filebeat-8-5-1.

After I installed it, the service started normally.
```
[root@iZa0z0138bbwc0i7be7ymbZ system]# sudo systemctl status filebeat
● filebeat.service - filebeat server daemon
   Loaded: loaded (/usr/lib/systemd/system/filebeat.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2023-09-22 17:35:23 CST; 3min 32s ago
 Main PID: 69444 (filebeat)
    Tasks: 10
   Memory: 185.4M
   CGroup: /system.slice/filebeat.service
           └─69444 /root/filebeat/filebeat -c /root/filebeat/filebeat.yml

Sep 22 17:35:23 iZa0z0138bbwc0i7be7ymbZ systemd[1]: Started filebeat server daemon.
```

My config file looks roughly like this:

```
filebeat.inputs:
- type: log
  paths:
  - /var/lib/docker/containers/*/*.log

output.elasticsearch:
  hosts: ["10.x.x.x:9200"] 
  username: "elastic"
  password: ""
  index: "vm-%{+yyyy.MM.dd}"

setup.ilm.enabled: false
setup.template.enabled: false
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 1
```

But I feel there is a problem. It does not generate the index name according to my index definition, but it generates it automatically. The log index name format I expected was vm-2023.09.22 but what it generated was .ds-vm-2023.09.22-2023.09.22-000001 .

```
# GET _cat/indices?v 
green  open   .ds-vm-2023.09.22-2023.09.22-000001 CjPFIr3-QRenp3-fWn2t5w   1   1     254113            0     78.7mb           39mb
```

I clearly configured `setup.ilm.enabled: false`, why didn’t it take effect? ? ? ?

Anyone know why?
