### ISSUE TITLE
Suspect Redis connection pool configuration issue causing discrepancy between maximum connection settings and actual results

### ISSUE THREAD

**Issue by wang-qijia** [elastic/beats#36678]
Description:
I am experiencing an issue with the maximum connection settings in Redis not matching the expected behavior. I suspect that there might be a problem with the Redis connection pool configuration.

Specifically, I am using Filebeat to collect Redis slow logs, but the maximum number of connections that are being established does not align with the settings I have configured. This has led me to suspect that there might be an issue with the connection pool parameters for Redis.

Could someone please help me troubleshoot this issue? I would like to understand if my Redis connection pool configuration is incorrect or if there are any other potential reasons for this discrepancy.

Thank you!

**Comment by shmsr** [comment]
@wang-qijia Thank you for opening an issue. Could you please elaborate and could you also please send the configuration?

**Comment by wang-qijia** [comment]
```yml
filebeat.inputs:
- type: redis
  hosts: ["localhost:6379"]
  timeout: 1
  scan_frequency: 2
  maxconn: 1


output.console:
  pretty: true
```
Maximum number of connections : https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-redis.html#redis-maxconn
