### ISSUE TITLE
does filebeat azure blob storage input support azure china of v8.10.2

### ISSUE THREAD

**Issue by troyqu** [elastic/beats#36789]
Hey

i`m using filebeat v8.10.2 to collect the file in azure blob storage, but i use azure china portal. i has followed the doc as bleow url to config the input and output. but no index was created and no data write into es. so i just wonder if filebeat only supports azure global.

```yml
filebeat.inputs:
- type: azure-blob-storage
  id: /subscriptions/7b43196xxxxxxd327cc80cd/resourceGroups/xu-rm/providers/Microsoft.Storage/storageAccounts/xxxxxageaccount
  enabled: true
  account_name: xxxxxageaccount
  auth.connection_string.uri: DefaultEndpointsProtocol=https;AccountName=xxxxxageaccount;AccountKey=7NrRzxxxxxxuq8p4g==;EndpointSuffix=core.chinacloudapi.cn
  storage_url: https://xxxxxageaccount.blob.core.chinacloudapi.cn
  containers:
  - name: troyjf
    max_workers: 3
    poll: true
    poll_interval: 10s
  - name: $logs
    max_workers: 3
    poll: true
    poll_interval: 10s

output.elasticsearch:
  hosts: ['http://docker-es:9200']
  username: 'elastic'
  password: 'elastic'
  allow_older_versions: true
```
