### ISSUE TITLE
[Metricbeat] Kafka module giving mbeans field

### ISSUE THREAD

**Issue by witdagostinho** [elastic/beats#36909]
Using native kafka module for metricbeat, not all metrics are parsed correctly into elasticsearch and some metrics are missing.

- Beat: Metricbeat
- Version: 8.10.4
- Operating System: CentOS Linux
- Kafka version:  "kafka_2.13-2.5.0.jar"
- Jolokia version: "jolokia-jvm-1.7.2.jar"

Module config
```
- module: kafka
  enabled: true
  metricsets:
        - broker
  period: 10s
  hosts: ["localhost:8778"]
```

Metrics in Kibana
![image](https://github.com/elastic/beats/assets/148462333/e371c1e5-b4dc-4fb6-9434-82128353178d)

Mbeans list
[mbeans.json](https://github.com/elastic/beats/files/13043432/mbeans.json)
