### ISSUE TITLE
[Windows integration] DFS counter collection seems to stop after virtual disk service restarts

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#37094]
For confirmed bugs, please report:
- Version: 8.9.2
- Operating System:  Windows
- Discuss Forum URL:
- Steps to Reproduce: 
1. Enable the `windows` module with the following configuration containing a DFS counter:
   ```yaml
   metricsets:
   - perfmon
   perfmon.group_measurements_by_instance: false
   perfmon.ignore_non_existent_counters: true
   perfmon.queries:
   - counters:
     - field: total_files_received
       format: long
       name: Total Files Received
     - field: staging_space_in_use
       format: long
       name: Staging Space In Use
     instance:
     - '*'
     object: DFS Replicated Folders
   perfmon.refresh_wildcard_counters: true
   period: 10s
   ```   
2.  Ensure that data for this counter is being collected as expected.
3. Restart the [Virtual Disk Service](https://learn.microsoft.com/en-us/windows/win32/vds/virtual-disk-service-portal).
- Observed behavior: Data for the DFS counter stops being collected.
- Expected behavior: Data continues to be collected.

- Additional information: 
  - Non-DFS counters, e.g. CPU, are unaffected by this bug.  Data for these counters continues to be collected.
  - SolarWinds is able to continue to collect such DFS counter data even after the VDS service restart.
