### ISSUE TITLE
Missing datasets that are relying on kube-state-metrics in case custom resource state metrics are enabled

### ISSUE THREAD

**Issue by tetianakravchenko** [elastic/beats#37198]
Missing some datasets in case custom resource state metrics are enabled https://github.com/kubernetes/kube-state-metrics/blob/main/docs/customresourcestate-metrics.md

How to reproduce:
0. Other versions > 8.7 likely have the same issue
```
elastic-package-0.89.2 stack up -d -v --version 8.7.1
```
1. install cert-manager:
kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.12.4/cert-manager.yaml

2. create a testing issuer:
```
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-test
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: test-selfsigned
  namespace: cert-manager-test
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - example.com
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
``` 
apply above.
3. edit the KSM setup:
```
args:
  - --custom-resource-state-config
  - |
    spec:
      resources:
        - groupVersionKind:
            group: cert-manager.io
            version: "v1"
            kind: Issuer
          metrics:
            - name: certman_issuers_info
              each:
                type: Info
                info:
                  path: [status]
                  labelsFromPath:
                    ref: []
  - --custom-resource-state-only=true # optional to report only custom metrics
```
4. edit KMS cluster role:
```
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  verbs:
  - list
  - watch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
```

5. deploy metricbeat

The issue: out of all state_* datasets - there are only 2 available (deployment, daemonset and cronjob - but in this setup I do not have cronjob installed)
<img width="2513" alt="Screenshot 2023-11-24 at 15 29 08" src="https://github.com/elastic/beats/assets/28299531/c079b31b-86a7-43d9-8794-606e92552000">

**Comment by tetianakravchenko** [comment]
at this point - https://github.com/elastic/beats/blob/main/metricbeat/helper/kubernetes/state_metricset.go#L113C2-L113C10
there is returned only the metrics that are coming before the custom metric (`kube_customresource_certman_issuers_info`) - like kube_deployment_*, kube_endpoint_*, etc

**Comment by tetianakravchenko** [comment]
the problem - `info` metric type is not actually parsed correctly
<img width="2477" alt="Screenshot 2023-11-27 at 13 15 17" src="https://github.com/elastic/beats/assets/28299531/482d4ec2-c496-415c-9454-f36235562832">

few issues with it:
1. the issue is not handled correctly - missing error message and we silently just break iteration over the metrics - https://github.com/elastic/beats/blob/296183ca0d11960ee4e839b4bc4ba2a8949c86d8/metricbeat/helper/prometheus/textparse.go#L497-L500
2. missing tests for `info` metrics
3. the content type is a plain text:
```
"text/plain; version=0.0.4; charset=utf-8"
```
the error regarding the invalid type is coming from here - https://github.com/prometheus/prometheus/blob/965e603fa792bca0900ac76eb45ae84c81af1cdf/model/textparse/promparse.go#L306-L320, there is no such type as `info`
`info` type only exists in openmetrics parser https://github.com/prometheus/prometheus/blob/965e603fa792bca0900ac76eb45ae84c81af1cdf/model/textparse/openmetricsparse.go#L273-L292
4. it might be another problem that the old version of prometheus is used - https://github.com/elastic/beats/blob/296183ca0d11960ee4e839b4bc4ba2a8949c86d8/go.mod#L135

**Comment by gsantoro** [comment]
If I understand correctly the CertManager here is only needed to test what happens when configuring KSM with a custom resource, right?

**Comment by gsantoro** [comment]
For future reference:
- you need to have a config for kube-state-metrics like the following

```
    - module: kubernetes
      hosts: ["kube-state-metrics:8080"]
      period: 10s
      add_metadata: true
      metricsets:
        - state_namespace
        - state_node
        - state_deployment
        - state_daemonset
        - state_pod
        - state_container
```

otherwise you won't see any state_* metricsets
