### ISSUE TITLE
Filebeat agent in K8S cluster can't pass logs from two different paths

### ISSUE THREAD

**Issue by SharonDiskin** [elastic/beats#37264]
I am trying to configure the filebeat agent on the k8s cluster to ship all the logs to elastic from two different paths:
1. /var/logs/containers/*.log
2. /var/logs/agents/*.log

I tried writing the config files but the logs are passing only from /var/logs/containers/*.log

this is the full config file:

```
       filebeat.autodiscover:
         providers:
          - type: kubernetes
            hints.enabled: true
            hints.default_config:
              enabled: false
              type: container
              paths:
                - /var/log/containers/*.log  # CRI path
                - /var/log/agents/*.log

      output.elasticsearch:
        protocol: http
        hosts: ["elasticsearch:9200"]
        compression_level: 1
        indices:
        - index: "agent-logs"
          when:
           contains:
            log.file.path: "agents"
        - index: "container-logs"
          when:
           contains:
            log.file.path: "containers"
```

I also tried this config, but when I run this config I only get agent logs:

```
      filebeat.autodiscover:
        providers:
          - type: kubernetes
            hints.enabled: true
            hints.default_config:
              enabled: false
              type: container
              paths:
                - /var/log/containers/*.log
      filebeat.inputs:
       - type: filestream
         id: agent-filestream
         paths:
          - "/var/log/agents/*.log"

      output.elasticsearch:
        protocol: http
        hosts: ["elasticsearch:9200"]
        compression_level: 1
        indices:
        - index: "container-logs"
          when:
           contains:
            log.file.path: "containers"
        - index: "agent-logs"
          when:
           contains:
            log.file.path: "agents"
```

please help!
thank you
