### ISSUE TITLE
[beat] Using Logstash output causes cluster UUID to be missing in state metricset

### ISSUE THREAD

**Issue by miltonhultgren** [elastic/beats#37414]
### Summary
When using Metricbeat's Beat module to monitor a beat, such as Filebeat, and that Beat doesn't use the Elasticsearch output (such as using the Logstash output) then the beat isn't able to get the cluster UUID directly from Elasticsearch.
Instead it relies on the setting `monitoring.cluster_uuid` to be set.

However, there is a bug in the `state` metricset where this config setting isn't being read properly, which results in the cluster UUID being empty on the documents sent to Logstash (which results in the Standalone cluster being showed in the Stack Monitoring UI). This bug does **not** affect the `stats` metricset.

### Workaround
Add this to the Metricbeat config:
```
processors:
  - copy_fields:
      fields:
        - from: beat.state.cluster.uuid
          to: beat.elasticsearch.cluster.id
      fail_on_error: false
      ignore_missing: true
```

Or use an equivalent Ingest Pipeline `set` processor:
```
{
  "set": {
    "field": "beat.elasticsearch.cluster.id",
    "copy_from": "beat.state.cluster.uuid"
  }
}
```

### Replication

- Start Elasticsearch
- Start Kibana
- Start Logstash with the below config [1]
- Setup the Filebeat data stream by running `./filebeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["localhost:9200"]' -E 'output.elasticsearch.username=elastic' -E 'output.elasticsearch.password=changeme'`
- Start Filebeat with the below config [2] (using the cluster UUID from step 1)
- Start Metricbeat with the below config [3]
- Observe in the Stack Monitoring UI that you have two clusters (the normal one and the Standalone cluster)

[1]:
```
input {
  beats {
    port => 5044
    ssl => false
  }
}
output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    user => elastic
    password => changeme
    action => "create"
    index => "%{[@metadata][beat]}-%{[@metadata][version]}"
  }
}
```

[2]:
```
http.enabled: true
http.port: 5067

monitoring.cluster_uuid: <<CLUSTER_UUID>>

filebeat.modules:
  - module: elasticsearch
    server:
      enabled: true
      var.paths:
        - <<ES_LOGS_PATH>>/logs/*.log
        - <<ES_LOGS_PATH>>/logs/*_server.json

output.logstash:
  hosts: [ "localhost:5044" ]
```

[3]:
```
metricbeat.modules:
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts:
      - "localhost:9200"
    username: "elastic"
    password: "changeme"

  - module: logstash
    xpack.enabled: true
    period: 10s
    hosts: [ "localhost:9600" ]

  - module: beat
    xpack.enabled: true
    period: 10s
    hosts:
      - "http://localhost:5067"

output.elasticsearch:
  hosts: [ "localhost:9200" ]
  username: "elastic"
  password: "changeme"
```
