### ISSUE TITLE
The "formatDate" on httpjson is not working on multiple version (7.17.0-8.11.3)

### ISSUE THREAD

**Issue by nitzango** [elastic/beats#37479]
Hi team,

I'm trying to pull data from an API that expect UNIX time as a query parameter (e.g. oldest event to pull).
While setting `'[[ formatDate (now (parseDuration "-4h")) ]]'` as the default for the first time run, it seems like the actual parameter is not transformed to UNIX as stays normal timestamp (I used ngrok to debug):
```
latest=Thu+Dec+21+09%3A30%3A28+UTC+2023
```
I tried to use the following filebeat config:
```
filebeat.inputs:
  - type: httpjson
    config_version: 2
    interval: 10m

    request.method: POST
    request.url: https://url.goes.here

    request.transforms:
    - set:
        target: header.Authorization
        value: "Bearer 123456"
    - set:
        target: header.Accept
        value: "application/json"
    - set:
        target: url.params.latest
        value: '[[.cursor.last_event_time]]'
        default: '[[ formatDate (now (parseDuration "-4h")) ]]'
```

For confirmed bugs, please report:
- Version: multiple version (7.17.0-8.11.3)
- Operating System:  Docker on macOS + Kubernetes
- Steps to Reproduce: Use the config above
