### ISSUE TITLE
httpjson: Chain request tracer filename sanitization

### ISSUE THREAD

**Issue by kcreddy** [elastic/beats#37551]
Currently, for each chain step request, we can add request tracer enabled by following config:
```
- step:
      request.url: {{hostname}}/assets/export/$.export_uuid/chunks/$.chunks_available[:]
      request.method: GET
      request.tracer.filename: "../../logs/httpjson/http-request-trace-*.ndjson"
```
But, the filename sanitization only occurs on the base/parent tracer as per https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/httpjson/input.go#L122-L125. 

Use file sanitization on chain request/response tracer.
