### ISSUE TITLE
 Azure Resource Metrics missing metrics after upgrade from 8.11.1 to 8.11.3

### ISSUE THREAD

**Issue by zmoog** [elastic/beats#37642]
The Azure Monitor metricset does not correctly store metrics using the `max` and `min` aggregation types in Elasticsearch. 

For confirmed bugs, please report:
- Version: 8.11.2, 8.11.3, 8.11.4, and 8.12.0
- Operating System: any

## Steps to Reproduce

Set up the Azure Monitor metricset with the following Metricbeat module configuration:

```
- module: azure
  metricsets:
  - monitor
  enabled: true
  period: 300s
  client_id: '...'
  client_secret: '...'
  tenant_id: '...'
  subscription_id: '...'
  refresh_list_interval: 600s
  resources:
  - resource_query: resourceType eq 'Microsoft.Cache/redis'
     metrics:
      - dimensions:
          - name: ShardId
            value: '*'
          - name: Port
            value: '*'
          - name: Primary
            value: '*'
        ignore_unsupported: true
        name:
          - allcachehits
          - allcachemisses
          - allcacheRead
          - allcacheWrite
          - allconnectedclients
          - allevictedkeys
          - allexpiredkeys
          - allgetcommands
          - alloperationsPerSecond
          - allpercentprocessortime
          - allserverLoad
          - allsetcommands
          - alltotalcommandsprocessed
          - alltotalkeys
          - allusedmemory
          - allusedmemorypercentage
          - allusedmemoryRss
          - ConnectedClientsUsingAADToken
        namespace: Microsoft.Cache/redis
        timegrain: PT1M
```

Run the metricset to collect some metrics.

The collected documents do not contain metrics having `min` and `max` aggregation types.
