### ISSUE TITLE
Beats panic if there are more than 32767 pipeline clients

### ISSUE THREAD

**Issue by belimawr** [elastic/beats#38197]
This has been tested with Filebeat but the bug is on libbeat, so it's likely affecting all beats. The OS tested was Linux but the issue is not dependant on OS.

#  Description
When Filebeat, using the filestream input, (other inputs are likely affected as well, the log input is **not** affected) is configured to harvest more than 32767 files at once it will panic. This happens because for each file, two elements are added to a slice of channels by [`Pipeline.runSitnalPropagation`](https://github.com/elastic/beats/blob/ae312c5b288c8377ed1a87adda80e153c363cea5/libbeat/publisher/pipeline/pipeline.go#L314), once this slice reaches 65536 elements, a `reflect.Select` on this slice will cause Filebeat to panic. The panic happens here: https://github.com/elastic/beats/blob/ae312c5b288c8377ed1a87adda80e153c363cea5/libbeat/publisher/pipeline/pipeline.go#L324.

For every new client this infinite for loop adds two elements to the slice of channels https://github.com/elastic/beats/blob/ae312c5b288c8377ed1a87adda80e153c363cea5/libbeat/publisher/pipeline/pipeline.go#L332-L346

Once the slice contains 65536 or more, then Filebeat panics with a message/stacktrace like this
```
panic: reflect.Select: too many cases (max 65536)
goroutine 277 [running]:
reflect.Select({0xc26e47e000?, 0xc360100000?, 0xc024488f10?})
reflect/value.go:2873 +0x79a
github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*Pipeline).runSignalPropagation(0xc02f6b47b8?)
github.com/elastic/beats/v7/libbeat/publisher/pipeline/pipeline.go:330 +0x1d8
created by github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*Pipeline).registerSignalPropagation.func1
github.com/elastic/beats/v7/libbeat/publisher/pipeline/pipeline.go:315 +0x97
```

# How to reproduce

The easiest way to reproduce this issue is to create 33000 small log files, then start Filebeat to harvest them. While testing I faced some issues/OS limitations when trying to have all files being constantly updated.

You can use anything to generate the files, I used the following shell script and [flog](https://github.com/mingrammer/flog)

```sh
#!/bin/bash

for i in $(seq 1 $1)
do
    path=$(printf "/tmp/log%010d.log\n" $i)
    flog -s 1 -n 100 > $path
    echo $path
done
```
Save it as `gen-logs.sh`, make it executable and run `./gen-logs.sh 33000`.

Use the file output for the simplicity and easy to validate all logs have been ingested. The output and logging configuration ensure there will be a single log file and single output file.
```yaml
filebeat.inputs:
  - type: filestream
    id: my-unique-id-per-filebeat-process
    paths:
      - /tmp/log*.log
    #harvester_limit: 32000

output:
  file:
    enabled: true
    path: ${path.home}/output
    filename: out
    rotate_every_kb: 100000000
    rotate_on_startup: false

logging:
  level: debug
  selectors:
    - crawler
    - file_watcher
    - input
    - input.filestream
    - input.harvester
    - registrar
    - scanner
    - service
  files:
    rotateeverybytes: 10485760000
    rotateonstartup: false
```
Start Filebeat and wait until it panics.

If you uncomment the `#harvester_limit: 32000` Filebeat will work without issues and ingest all files. If using the script provided, there should be 3300000 events in the output file, you can verify that with:
```
wc -l output/*
```

# Workaround
One workaround is to set the `harvester_limit` to a number smaller than 32000 if using a single input. If using multiple affected inputs all inputs should have limits to the number of pipeline clients they create in a way that for a running Filebeat process there will never be more than 32000 pipeline clients running concurrently.

For the filestream input, here is an example configuration:
```yaml
filebeat.inputs:
  - type: filestream
    id: my-unique-id-per-filebeat-process
    paths:
      - /tmp/log*.log
    harvester_limit: 32000
```
