### ISSUE TITLE
Investigate number of debug messages of add_kubernetes_metadata processor

### ISSUE THREAD

**Issue by gizas** [elastic/beats#38529]
Filebeat in logging debug mode was reported that returns erroneous number of debug messages. 
Investigate why we report so many messages and see if we can remove some of them

- Filebeat Input: input.filestream
- Beats version reported: 7.17.0

Filebeat sample config:
```yaml
filebeat.config:
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    filebeat.inputs:
    - file_identity.fingerprint: null
      id: cinit-app-filebeat-containers
      type: filestream
      prospector.scanner:
        check_interval: 2s
        fingerprint:
          enabled: true
          length: 512
          offset: 0
        symlinks: true
      paths:
      - /var/log/containers/dtp-log-gen*.log
      parsers:
      - container:
          format: cri
          stream: all 
```
