### ISSUE TITLE
Polling behavior with Cloudwatch metrics not matching expectations

### ISSUE THREAD

**Issue by jkomara** [elastic/beats#38555]
I have been working with @kaiyan-sheng on importing AWS MSK metrics with elastic agent. I am using the [elastic-agent standalone deployment template](https://github.com/elastic/elastic-agent/blob/main/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml) for kubernetes to deploy elastic-agent using a standalone configuration generated by the [AWS MSK Integration](https://github.com/elastic/integrations/pull/9133). This was initially set up to poll every minute by setting `period` to `1m`. The cost that was incurred for this frequency was high so the `period` was set to `5m` and `data_granularity` was set to `1m`. When I checked back in on the usage report, the number of metrics being requests and the frequency of the GetMetricData (GMD) API calls had not changed. You could see that it was still being requested every `1m`.

I ran through a few iterations to try to see if I could get it to behave as I would expect. I set the polling period to `10m` and the `data_granularity` to `1m`.

![image](https://github.com/elastic/beats/assets/5845335/568d6821-8dc5-4f9e-b70d-33c97dbad11f)

In the image above you can see up until 16:44 that GMD and the ListMetrics API were being hit every minute. My expectation would be that you would see them being hit every 10 minutes. You can see a break in the graph. That is where I updated the `data_granularity` to `2m`. When polling resumes at 16:46 you can see that the APIs are still being hit every minute.

I then updated the `data_granularity` to `5m` and saw the behavior that I was expecting.

![image](https://github.com/elastic/beats/assets/5845335/30f87c53-ce71-4fe3-a56c-a52f0b09a369)

In this image you can see that GMD is being hit every 10 minutes as expected and I verified that I have datapoints in my ES cluster as expected. I am waiting on the usage and cost data to populate in AWS Cost Explorer so that I can see how many metrics were fetched and the cost associated with them. I can add that here when it is ready if that helps at all. I have included the configuration that I am using. The only change I am making is updating the `period` or the `data_granularity`.

- Version: elastic-agent 8.12.2
- Docker Container: docker.elastic.co/beats/elastic-agent:8.12.2

<details>
  <summary>Input Config</summary>

  ```yaml
    inputs:
      - id: aws/metrics-kafka-UUID
        name: aws-1
        revision: 1
        type: aws/metrics
        use_output: default
        meta:
          package:
            name: aws
            version: 2.13.0
        data_stream:
          namespace: default
        package_policy_id: UUID
        streams:
          - id: aws/metrics-aws.kafka_metrics-UUID
            data_stream:
              dataset: aws.kafka_metrics
              type: metrics
            metricsets:
              - cloudwatch
            period: 10m
            data_granularity: 5m
            access_key_id: ***
            secret_access_key: ***
            regions:
              - eu-west-1
            latency: 5m
            tags_filter: null
            metrics:
              - name:
                  - BytesInPerSec
                  - BytesOutPerSec
                  - EstimatedMaxTimeLag
                  - FetchMessageConversionsPerSec
                  - MaxOffsetLag
                  - MessagesInPerSec
                  - ProduceMessageConversionsPerSec
                  - SumOffsetLag
                namespace: AWS/Kafka
                resource_type: kafka
                statistic:
                  - Sum
```
</details>
