### ISSUE TITLE
[Filebeat] Netflow data indexing failures after upgrading to 8.13

### ISSUE THREAD

**Issue by etigervaise** [elastic/beats#38703]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: Filebeat 8.13.0 and 8.13.1
- Operating System: Debian and Ubuntu
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-netflow-module-reject-document-with-status-400/356561
- Steps to Reproduce: 
1 - Install Elasticsearch.
2 - Install and configure kibana.
3 - Install and configure filebeat to accept netflow. In my case, i've used this configuration:
```yml
# Module: netflow
# Docs: https://www.elastic.co/guide/en/beats/filebeat/main/filebeat-module-netflow.html

- module: netflow
  log:
    enabled: true
    var:
      netflow_host: 0.0.0.0
      netflow_port: 2055
      # internal_networks specifies which networks are considered internal or private
      # you can specify either a CIDR block or any of the special named ranges listed
      # at: https://www.elastic.co/guide/en/beats/filebeat/current/defining-processors.html#condition-network
      internal_networks:
        - private
```
4 - Send netflow to filebeat. For debugging, I have used the following project: [https://github.com/nerdalert/nflow-generator/tree/master](https://github.com/nerdalert/nflow-generator/tree/master)
5 - Notice the following warning:
```
Apr 02 13:57:11 tv filebeat[597]: {"log.level":"warn","@timestamp":"2024-04-02T13:57:11.590Z","log.logger":"elasticsearch","log.origin":{"function":"github.com/elastic/beats/v7/libbeat/outputs/elasticsearch.(*Client).bulkCollectPublishFails","file.name":"elasticsearch/client.go","file.line":454},"message":"Cannot index event (status=400): dropping event! Enable debug logs to view the event and cause.","service.name":"filebeat","ecs.version":"1.6.0"}
```

Note that this is following the breaking change https://github.com/elastic/beats/pull/37901
