### ISSUE TITLE
systemd input plugin is missing while building on a docker container

### ISSUE THREAD

**Issue by isshwar** [elastic/beats#39020]
Hi,

I have an automated pipeline to build fluent-bit in a docker container. but the build is missing systemd input pluging. Below is the script on gitlab pipeline that I use to build the binary

````yaml
image: debian:buster-slim
  script:
    - apt-get update -y && apt-get install -y build-essential cmake flex bison libyaml-cpp-dev git wget libssl-dev libyaml-dev curl
    - wget https://github.com/fluent/fluent-bit/archive/refs/tags/v${FLUENT_BIT_VERSION}.tar.gz
    - tar -xvzf v${FLUENT_BIT_VERSION}.tar.gz
    - cd fluent-bit-${FLUENT_BIT_VERSION}/build && cmake .. && make
    - mv ${CI_PROJECT_DIR}/fluent-bit-${FLUENT_BIT_VERSION}/build/bin/fluent-bit ${CI_PROJECT_DIR}/habitat/fluent-bit
    - echo "${FLUENT_BIT_VERSION}" > ${CI_PROJECT_DIR}/habitat/pkg_version.txt
````

Any help is appreciated

Thanks
