### ISSUE TITLE
Auditd fileset breaks the system module on macOS

### ISSUE THREAD

**Issue by tsg** [elastic/beats#3918]
The auditd fileset has no paths defined for macOS. Unfortunately, because all filesets are enabled by default, it means that the system module doesn't work on macOS.

This is the relevant portion of the manifest file:

```
var:
  - name: paths
    default:
      - /var/log/audit/audit.log*
    os.darwin: [""]
    os.windows: []
```

An easy solution would be to replace `os.darwin: []` with `os.darwin: [""]`, which would mean that the fileset is silently ignored on macOS, but I see that and `auditd` daemon does seem to exist on macOS as well. 

@andrewkroh Would it make sense to support the macOS' `auditd`?
