### ISSUE TITLE
Azure Monitor metricset only collect one aggregation type at a time

### ISSUE THREAD

**Issue by zmoog** [elastic/beats#39192]
- Version: 8.13.2
- Operating System: any
- Steps to Reproduce: 

A user reported the Azure Monitor metricset is collecting only one aggregation type despite setting up a configuration for three (Maximum, Minimum, Avergate).

The following two configuration variants for `Microsoft.EventHub/Namespaces` only return one metric instead of the expected three.

```yaml
- module: azure
  metricsets:
    - monitor
  enabled: true
  period: 60s
  client_id: '<redacted>'
  client_secret: '<redacted>'
  tenant_id: '<redacted>'
  subscription_id: '<redacted>'
  refresh_list_interval: 600s
  resources:
  - metrics:
    - aggregations:
        - Maximum
      ignore_unsupported: true
      name:
        - ActiveConnections
      namespace: Microsoft.EventHub/Namespaces
    - aggregations:
        - Minimum
      ignore_unsupported: true
      name:
        - ActiveConnections
      namespace: Microsoft.EventHub/Namespaces
    - aggregations:
        - Average
      ignore_unsupported: true
      name:
        - ActiveConnections
      namespace: Microsoft.EventHub/Namespaces
```

```yaml
- module: azure
  metricsets:
    - monitor
  enabled: true
  period: 60s
  client_id: '<redacted>'
  client_secret: '<redacted>'
  tenant_id: '<redacted>'
  subscription_id: '<redacted>'
  refresh_list_interval: 600s
  resources:
  - metrics:
      namespace: Microsoft.EventHub/Namespaces
      aggregations:
        - Average
        - Maximum
        - Minimum
      ignore_unsupported: true
      timegrain: PT1M
```
