### ISSUE TITLE
[Metricbeat] Statsd Module does not support Graphite series 1.1.0+

### ISSUE THREAD

**Issue by tehbooom** [elastic/beats#39473]
When using the Metricbeat statsd module to ingest Envoy statistics I am unable to use the [Graphite Statsd extension](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/stat_sinks/graphite_statsd/v3/graphite_statsd.proto#extension-envoy-stat-sinks-graphite-statsd). 

Using the [Statsd Sink ](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/metrics/v3/stats.proto#extension-envoy-stat-sinks-statsd) does work however but for more efficeint parsing it would be best to use Graphite.

Here is an example output for the Graphiite Statsd extension

```
envoy.listener.ssl.ocsp_staple_omitted;envoy.listener_address=0.0.0.0_9001:0|c
```

The statsd module is splitting on `,` while Graphite supports `;` seen [here](https://graphite.readthedocs.io/en/latest/tags.html#carbon)

The [`parseSingle`](https://github.com/elastic/beats/blob/13aed9f010453e05783ca3b318651ec2949030c4/x-pack/metricbeat/module/statsd/server/data.go#L76) function is only splitting on `,` as mentioned before and would be great if we could also support `;`

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 
  - Envoy: 1.20.1
  - Metricbeat: 8.13.2
- Operating System: MacOS 14.4.1
- Discuss Forum URL: N/A
- Steps to Reproduce: 

1. Add the graphite statsd config to envoy

```yaml
stats_sinks:
  - name: graphite_statsd
    typed_config:
      "@type": type.googleapis.com/envoy.extensions.stat_sinks.graphite_statsd.v3.GraphiteStatsdSink
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 8125
```

2. Enable statsd metricbeat module

```yaml
- module: statsd
  host: "localhost"
  metricsets: ["server"]
  port: "8125"
  enabled: true
```

3. Run envoy and metricbeat
4. Result is the following

![ES event](https://github.com/elastic/beats/assets/57996746/afb9df3f-ad59-41af-8886-04e729b13191)
