### ISSUE TITLE
Document headers and ssl for metricsets

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#3948]
In https://github.com/elastic/beats/pull/3945 customer headers, auth and ssl was introduced for all http metricsets. The following must be done:

* Add documentation for it
* Add it to the full config

Potentially also find a way on how to test it.

**Comment by joegallo** [comment]
One quick things that's not 100% clear to me:

For elasticsearch.output, I would specify:

```
    hosts: ["somehost"]
    username: "someusername"
    password: "somepassword"
    headers:
      SomeHeader: SomeValue
```

But it looks like perhaps the username and password auth for metricsets has been implemented purely as additional headers only? So no username/password -- just have to gen up an Authorization header myself. Is that correct or did I misunderstand?

If I did understand correctly, I guess this comment in then an enhancement request to handle username and passwords specially. (That might be pie in the sky, though, but it doesn't hurt to ask. :D)
