### ISSUE TITLE
golangci-lint action incorrectly abuses GOOS to get cross-platform linting

### ISSUE THREAD

**Issue by efd6** [elastic/beats#39589]
The current golangci-lint action configuration [uses GOOS to try to lint on platforms other than the OS that the builder is running on](https://github.com/elastic/beats/blob/35c6b264836fadacfb4d716073b76274b3cb5c0a/.github/workflows/golangci-lint.yml#L15-L22).

```
    strategy:
      matrix:
        include:
          - GOOS: windows
          - GOOS: linux
          - GOOS: darwin
    name: lint
    runs-on: ubuntu-latest
```
This has the effect that when the analyser runs it may be in a situation where it cannot get all the required type information to be able to complete the analysis. Unfortunately, in this situation it does not simply fail, but emits incorrect linter advice that people then try to fix.

The situation where this most commonly will happen is when the build includes Cgo dependencies, as beats do.

The correct approach would be to use the [Multiple OS Support](https://github.com/golangci/golangci-lint-action/?tab=readme-ov-file#multiple-os-support) provided by the action.
