### ISSUE TITLE
Ignore_older concept is not working

### ISSUE THREAD

**Issue by Micheal-Madhan** [elastic/beats#39752]
Hi,

ignore_older concept is not working in our use case.

Please find the below our use case :

We took a backup of the Elasticsearch folder installed on your Windows server at 10 AM on May 15, 2024.
Elasticsearch (ES), Filebeat, and Logstash continued to work and push data to ES until 12 AM on May 15, 2024.
At 12 AM, we deleted the entire ES folder.
We restored the backup of ES that was taken at 10 AM on May 15, 2024.
After refreshing the backup ES, we could see the data saved until 10 AM on May 15, 2024.
The Filebeat log file contains monitor and harvested information until 12 PM.
we require to retrieve the missing data between 10 AM and 12 PM.
We set ignore_older: 2h in the Filebeat configuration (filebeat.yml).
However, after restarting Filebeat and Logstash, it is not pushing the missing data, and there are no errors in the log file; only monitor entries are present.
Can you please provide your suggestion on this issue?

shared the filebeat.yml file for your reference.

=========================== Filebeat inputs =============================

filebeat.inputs:
- type: log
  enabled: true
  paths:
  - C:\LIMSAudit\AuditTextFilePath\\specimen-*.json
  fields: {log_type: specimen}
  ignore_older: 2h
  
- type: log
  enabled: true
  paths:
  - C:\LIMSAudit\AuditTextFilePath\\useractivity-*.json
  fields: {log_type: useractivity}
  ignore_older: 2h

type: log
  enabled: true
  paths:
  - C:\LIMSAudit\AuditTextFilePath\\order-*.json
  fields: {log_type: order}
  ignore_older: 2h
  
- type: log
  enabled: true
  paths:
  - C:\LIMSAudit\AuditTextFilePath\\profile-*.json
  fields: {log_type: profile}
  ignore_older: 2h
  
  I am unsure why Filebeat is not considering the ignore_older value. We need your guidance to solve this problem.

I appreciate any help you can provide.
  
```[tasklist]
### Tasks
- [ ] https://github.com/elastic/beats/pull/39751
- [ ] https://github.com/elastic/beats/pull/39750
```

**Comment by darwinSK** [comment]
The `ignore_older` setting in Filebeat is not functioning as expected. Here's an analysis and some suggestions to troubleshoot and resolve the issue:

### Understanding the Problem
1. **Backup and Restore Timeline**:
   - Backup taken at 10 AM on May 15, 2024.
   - Elasticsearch, Filebeat, and Logstash worked until 12 PM on May 15, 2024.
   - At 12 PM, the Elasticsearch folder was deleted.
   - Backup restored showing data until 10 AM on May 15, 2024.
   - Missing data from 10 AM to 12 PM needs to be retrieved.

2. **Filebeat Configuration**:
   - `ignore_older: 2h` is set in the Filebeat configuration for various log files.
   - After restarting Filebeat and Logstash, the missing data is not being pushed.

### Potential Issues and Solutions
1. **Filebeat Registry**:
   - Filebeat keeps track of the state of files it has read in a registry file. When you restored from a backup, the registry file may have information that prevents Filebeat from re-reading the logs from 10 AM to 12 PM.
   - **Solution**: Clear the Filebeat registry file. The location of this file can vary, but it's usually located in the `data` directory of your Filebeat installation. Look for a file named `registry` or similar and delete it. This will force Filebeat to reprocess all logs from the beginning.

2. **Ignore_older Setting**:
   - `ignore_older` specifies that Filebeat should ignore files older than the specified duration. Given your timeline, if logs are more than 2 hours old, they might be ignored.
   - **Solution**: Ensure that the logs are not older than the specified duration. Since you want to capture logs from a specific timeframe, you might need to adjust the `ignore_older` setting or temporarily disable it to allow Filebeat to process older logs.

3. **Log File Modifications**:
   - Ensure that the log files have not been modified in a way that makes them appear older than they are.
   - **Solution**: Check the timestamps on your log files and make sure they reflect the correct time period. Touching the files to update their modified times might help if the timestamps are incorrect.

### Updated Filebeat Configuration
While the configuration you shared looks mostly correct, here are a few tweaks and suggestions to ensure it's set up properly:

```yaml
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - C:\LIMSAudit\AuditTextFilePath\specimen-*.json
  fields: {log_type: specimen}
  ignore_older: 2h

- type: log
  enabled: true
  paths:
    - C:\LIMSAudit\AuditTextFilePath\useractivity-*.json
  fields: {log_type: useractivity}
  ignore_older: 2h

- type: log
  enabled: true
  paths:
    - C:\LIMSAudit\AuditTextFilePath\order-*.json
  fields: {log_type: order}
  ignore_older: 2h

- type: log
  enabled: true
  paths:
    - C:\LIMSAudit\AuditTextFilePath\profile-*.json
  fields: {log_type: profile}
  ignore_older: 2h
```

### Steps to Resolve
1. Stop Filebeat.
2. Clear the Filebeat registry file.
3. Adjust or disable the `ignore_older` setting temporarily.
4. Start Filebeat.
5. Monitor the Filebeat logs to ensure it's processing the expected files.

By following these steps, you should be able to retrieve the missing data from your log files. If issues persist, further investigation into Filebeat logs and Elasticsearch health might be necessary.

**Comment by Micheal-Madhan** [comment]
Thanks for the quick reply, but I am only able to monitor the file, not harvest it.

**Comment by darwinSK** [comment]
If Filebeat is only monitoring files but not harvesting them, there could be several reasons for this behavior. Let's explore the common causes and their solutions:

### Common Issues and Solutions

1. **Filebeat Registry Not Reset**:
   - The registry file keeps track of the last read position in each file. If this file isn't reset, Filebeat may think it has already read all the logs.
   - **Solution**: Ensure you have deleted the registry file correctly. It is usually found in the `data` directory of the Filebeat installation. The exact path depends on your setup. On Windows, it might be something like `C:\ProgramData\filebeat\data\registry`. Delete or move this file and restart Filebeat.

2. **File Modification Time**:
   - If the files have timestamps older than the `ignore_older` value, Filebeat will ignore them.
   - **Solution**: Temporarily remove the `ignore_older` setting to see if Filebeat starts harvesting the files. You can re-add it later with an appropriate value.

3. **Filebeat Configuration Issues**:
   - There could be syntax errors or misconfigurations in the Filebeat configuration file.
   - **Solution**: Double-check your `filebeat.yml` for any syntax issues or misconfigurations. You can use YAML validators online to check the syntax.

4. **Permissions**:
   - Filebeat might not have the necessary permissions to read the files.
   - **Solution**: Ensure Filebeat has the correct permissions to read the log files. This includes checking the file system permissions and ensuring Filebeat is running with the necessary privileges.

5. **Logs Location**:
   - Ensure the paths specified in the Filebeat configuration match the actual paths of the log files.
   - **Solution**: Verify that the log files exist in the specified paths and are being updated as expected.

### Steps to Troubleshoot

1. **Stop Filebeat**:
   - Stop the Filebeat service to ensure no processes are running.

2. **Clear the Registry File**:
   - Locate and delete the registry file. For Windows, it might be in `C:\ProgramData\filebeat\data\registry`.

3. **Modify the Configuration File**:
   - Remove or adjust the `ignore_older` setting temporarily:

   ```yaml
   filebeat.inputs:
   - type: log
     enabled: true
     paths:
       - C:\LIMSAudit\AuditTextFilePath\specimen-*.json
     fields: {log_type: specimen}

   - type: log
     enabled: true
     paths:
       - C:\LIMSAudit\AuditTextFilePath\useractivity-*.json
     fields: {log_type: useractivity}

   - type: log
     enabled: true
     paths:
       - C:\LIMSAudit\AuditTextFilePath\order-*.json
     fields: {log_type: order}

   - type: log
     enabled: true
     paths:
       - C:\LIMSAudit\AuditTextFilePath\profile-*.json
     fields: {log_type: profile}
   ```

4. **Start Filebeat**:
   - Start Filebeat and check the logs to see if it starts harvesting the files. Look for log entries indicating that files are being read and data is being sent.

5. **Monitor Filebeat Logs**:
   - Filebeat logs can provide insight into what is happening. Look for any warnings or errors that might indicate why files are not being harvested.

### Sample Commands for Windows

1. **Stop Filebeat**:
   ```powershell
   Stop-Service filebeat
   ```

2. **Delete Registry File**:
   ```powershell
   Remove-Item 'C:\ProgramData\filebeat\data\registry' -Force
   ```

3. **Start Filebeat**:
   ```powershell
   Start-Service filebeat
   ```

4. **Check Filebeat Logs**:
   - The logs are usually located in `C:\ProgramData\filebeat\logs`. Check the latest log file for entries related to harvesting.

### Conclusion

By following these steps, you should be able to troubleshoot and resolve the issue of Filebeat only monitoring but not harvesting files. If the problem persists, consider increasing the logging level in Filebeat for more detailed output, which can help pinpoint the issue further.
