### ISSUE TITLE
[Metricbeat] Logstash modules with xpack.enabled: true will not be able to set their customer data stream.

### ISSUE THREAD

**Issue by Camilleli** [elastic/beats#39808]
- Version: 8.10 to 8.13
- Operating System: linux / official docker image
- Steps to Reproduce: 

Metricbeat.yaml:
```yaml

metricbeat.modules:
- module: logstash
  period: 60s
  hosts: ["192.168.50.46:9600"]
  xpack.enabled: true

- module: system
  enabled: false

logging.level: debug
setup.template.name: ".monitoring-test-logstash-8-mb"
setup.template.pattern: ".monitoring-test-logstash-8-mb*"
# setup.template.enabled: true
setup.ilm.enabled: false

output.elasticsearch:
  hosts: ['xxxx']
  username: elastic
  password: xxx
  index: ".monitoring-test-logstash-8-mb"

```

Given the specified configuration```xpack.enabled: true```, if ```metricbeat.config.modules.path:``` is not configured, ingestion will default to the ```.monitoring-logstash-8-mb``` index, despite the ability to set up custom index templates and data streams.

I tried to find some logs related to it. Even with debug mode, I have no luck finding logs related.

It only complain when I try to run [```metricbeat modules disable logstash```](https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-logstash.html#_usage_for_stack_monitoring)
```Error in modules manager: modules management requires 'metricbeat.config.modules.path' setting```
