### ISSUE TITLE
filebeat add_kubernetes_metadata but log messages not kubernetes metadata info

### ISSUE THREAD

**Issue by wangchao732** [elastic/beats#40017]
filebeat version :  7.17.22
kafka version: 3.0

```
filebeat.inputs:
- type: container
  id: my-filestream-k8s
  enabled: true
  paths:
    - /var/log/containers/*.log
  fields:
    source: k8slog
  processors:
    - add_kubernetes_metadata:
        in_cluster: true
        kube_config: ~/.kube/config
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
setup.template.settings:
  index.number_of_shards: 1
  index.number_of_replicas: 0
  index.codec: best_compression
              
output.kafka:
  when.contains:
    fields.source: "k8slog"
  hosts: ["192.168.11.xxx:9092"]
  topic: "k8slogs-msg"
setup.template.name: "default-template"
setup.template.pattern: "default-*"
setup.ilm.enabled: false
logging.level: info
```

consummer kafka topic k8slogs-msg

> {"@timestamp":"2024-06-26T04:20:28.244Z","@metadata":{"beat":"filebeat","type":"_doc","version":"7.17.22"},"stream":"stdout","message"n-1.alertmanager-operated.kubesphere-monitoring-system.svc.cluster.local. udp 106 false 512\" NOERROR qr,aa,rd 210 0.000205798s","inpu":{"version":"1.12.0"},"host":{"name":"bj11-bcld-k8s01.bcld.com"},"agent":{"hostname":"bj11-bcld-k8s01.bcld.com","ephemeral_id":"7c154-9230-b3ea23d6c86a","name":"bj11-bcld-k8s01.bcld.com","type":"filebeat","version":"7.17.22"},"log":{"file":{"path":"/var/log/containera896e560413bfff4cb0d9447cb0aff21b152fa7f900e600b4484e7.log"},"offset":27752328}}
{"@timestamp":"2024-06-26T04:20:28.245Z","@metadata":{"beat":"filebeat","type":"_doc","version":"7.17.22"},"message":"[INFO] 10.10.4.6perated.kubesphere-monitoring-system.svc.cluster.local. udp 106 false 512\" NOERROR qr,aa,rd 210 0.000162891s","input":{"type":"contaieat","version":"7.17.22","hostname":"bj11-bcld-k8s01.bcld.com","ephemeral_id":"7c154198-9a8f-4524-9683-ef124849c76b","id":"0128ce3c-39om"},"ecs":{"version":"1.12.0"},"host":{"name":"bj11-bcld-k8s01.bcld.com"},"log":{"offset":27752581,"file":{"path":"/var/log/containera896e560413bfff4cb0d9447cb0aff21b152fa7f900e600b4484e7.log"}},"stream":"stdout"}

---
Edited by @VihasMakwana - formatted for readability.
