### ISSUE TITLE
Syslog processor more strict than syslog input

### ISSUE THREAD

**Issue by Poulpatine** [elastic/beats#40105]
### Problem
I'm trying to gather logs from Netgear switches using Syslog.
The idea is to configure all the switches to send logs via Syslog to a single filebeat instance and this filebeat instance is then sending the logs to an Elasticsearch instance.

I've been able fairly easily to achieve this setup with a syslog input configuration but I've seen in the documentation that Syslog input is deprecated and must be replaced by UDP input / Syslog processor.

The problem is that my message is not correctly parsed by Syslog processor.

For this syslog message:
`<14> Jun 27 12:00:32 172.32.32.50-1 General[-1248711972]: <mark>main_login.c</mark>(763) 1771 %% HTTP Session 5 initiated for connection from 10.20.0.132`

I have this error.message:
`syslog failed to process field "message": parsing error at position 5: unexpected EOF`

The same message is correctly parsed by syslog input.

### How to reproduce
- Version: 8.9.0 and 8.14.1
- Operating System: Debian 12
- Discuss Forum URL: https://discuss.elastic.co/t/syslog-processor-more-strict-than-syslog-input/362146/1
- Steps to Reproduce: 
  * Install filebeat
  * Configure /etc/filebeat/filebeat.yml :
 

```
# https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-container.html
filebeat.inputs:
- type: udp
  host: "0.0.0.0:9002"
  processors:
  - syslog:
      field: message
      format: rfc3164
      timezone: Europe/Paris
      ignore_failure: true

output.console:
  pretty: true
```

  * Launch filebeat and receive logs from your devices (Netgear switch in my occasion)
