### ISSUE TITLE
[tcp/udp] Add a configuration option for network type

### ISSUE THREAD

**Issue by taylor-swanson** [elastic/beats#40407]
## Overview

Go provides an argument to the Listen function (likewise for ListenTCP and ListenUDP) to specify the type of network (IPv4, IPv6, or both/auto) to be used when creating the listener. The network type for the TCP and UDP inputs are `tcp` and `udp`, respectively, and there is currently no way to override this value. Certain situations may require locking down the type of network being used (such as providing a hostname or using `localhost`).

The TCP input would accept these values for the network type:
- `tcp` (default)
- `tcp4`
- `tcp6`

The UDP input would accept these values for the network type:
- `udp` (default)
- `udp4`
- `udp6`

## Examples

```
filebeat.inputs:
- type: tcp
  max_message_size: 10MiB
  host: "localhost:9000"
  network: tcp4
```

```
filebeat.inputs:
- type: udp
  max_message_size: 10KiB
  host: "localhost:8080"
  network: udp4
```

## Acceptance Criteria

- When no option is provided, the default value (`udp` or `tcp`) is used
- When an option is provided, it must be a valid value, all other values must raise an error
- The option/default is applied to the listener and can be verified in netstat (or equivalent) output
- Documentation added for new config fields
