### ISSUE TITLE
[Journald] Document the parsers

### ISSUE THREAD

**Issue by belimawr** [elastic/beats#40478]
The Journald input supports the same parsers as the Filestream input, here is an example:
```yaml
filebeat.inputs:
  - type: journald
    id: PR-testing
    parsers:
      - multiline:
          type: count
          count_lines: 3
```

However this is not documented. We need to add documentation and examples both in our public documentation and configuration files.
