### ISSUE TITLE
[add_Kubernetes_metadata processor] Implement a new matcher for pattern matching

### ISSUE THREAD

**Issue by gizas** [elastic/beats#40495]
**Describe the enhancement:**
The [add_kubernete_metadata](https://www.elastic.co/guide/en/beats/metricbeat/current/add-kubernetes-metadata.html) processor will support a new grok [matcher](https://www.elastic.co/guide/en/beats/metricbeat/current/add-kubernetes-metadata.html#_matchers) in order to enhance the system metrics with kubernetes metadata.

The user will define the field and then  matching pattern that the processor will need to finally construct the final key to match the container.id. The matching pattern implementation is left to be decided. It can be grok or regex

An eg can be:

```yaml

matchers:
      - fields:
          lookup_fields: ['system.container.id']
          pattern: '%{WORD:cri}-%{WORD:containerd}-%{WORD:containerid}'


```

**Describe a specific use case for the enhancement or feature:**

https://github.com/elastic/ingest-dev/issues/3428
Needed for the metadata enrichment of system process metricsets

**Comment by swiatekm** [comment]
My preference would be to use regex capture groups for this, as it's a more widely known mechanism than grok. The configuration would look like the following:

```
matchers:
      - fields:
          lookup_fields: ['system.container.id']
          regex_pattern: 'cri-containerd-(?P<key>)`'
```
