### ISSUE TITLE
[Azure] azure-eventhub input fails to start on Windows due to "Error creating runner from config: Error creating input. No such input type exist: 'azure-eventhub'" error

### ISSUE THREAD

**Issue by zmoog** [elastic/beats#40608]
- Version: 8.15.0
- Operating System: Windows
- Discuss Forum URL: https://www.reddit.com/r/elasticsearch/comments/1ezts9b/comment/ljp8l8u/
- Steps to Reproduce: 

```yaml
- module: azure
  # All logs
  activitylogs:
    enabled: true
    var:
      # eventhub name containing the activity logs, overwrite he default value if the logs are exported in a different eventhub
      eventhub: "activitylogs"
      # consumer group name that has access to the event hub, we advise creating a dedicated consumer group for the azure module
      consumer_group: "$Default"
      # the connection string required to communicate with Event Hubs, steps to generate one here https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-get-connection-string
      connection_string: "<redacted>"
      # the name of the storage account the state/offsets will be stored and updated
      storage_account: "mbrancageneral"
      # the name of the storage account container you would like to store the offset information in.
      storage_account_container: "<redacted>"
      # the storage account key, this key will be used to authorize access to data in your storage account
      storage_account_key: "<redacted>"
```

Filebeat 8.15.0 on Windows fails to run the `azure-eventhub` input with the following error:

```json
{
  "log.level": "error",
  "@timestamp": "2024-08-24T13:16:00.930Z",
  "message": "Error creating runner from config: Error creating input. No such input type exist: 'azure-eventhub'",
  "component": {
    "binary": "filebeat",
    "dataset": "elastic_agent.filebeat",
    "id": "azure-eventhub-default",
    "type": "azure-eventhub"
  },
  "log": {
    "source": "azure-eventhub-default"
  },
  "log.origin": {
    "file.line": 139,
    "file.name": "cfgfile/list.go",
    "function": "github.com/elastic/beats/v7/libbeat/cfgfile.(*RunnerList).Reload"
  },
  "service.name": "filebeat",
  "ecs.version": "1.6.0",
  "log.logger": "centralmgmt"
}

```
