### ISSUE TITLE
Fleet with kubernetes integration ignore ssl.validation_mode on kubelet

### ISSUE THREAD

**Issue by julien-maurel** [elastic/beats#40875]
Hi
I don't know if it's an issue on beats, on plugin, on fleet, so I create issue here, let me know if it's not the good repo :)

- Version: 8.15.1
- Operating System: Linux
- Discuss Forum URL: https://discuss.elastic.co/t/fleet-with-kubernetes-integration-ignore-ssl-validation-mode-on-kubelet/366682
- Steps to Reproduce: 

  - Agent managed by fleet with kubernetes integration (v1.67.0) on its policy
  - On integration configuration, set ssl validation mode to none
  ![Image](https://github.com/user-attachments/assets/c5654412-13f5-46e6-9f17-0cf42e1084d3)
  - Apply and check configuration from kibana/fleet, no ssl verification mode and agent report logs `x509: certificate signed by unknown authority`...
```
      - id: >-
          kubernetes/metrics-kubernetes.container-xxxxx
        data_stream:
          dataset: kubernetes.container
          type: metrics
        metricsets:
          - system
        add_metadata: true
        hosts:
          - 'https://${env.NODE_NAME}:10250'
        period: 30s
```
