### ISSUE TITLE
CPU metrics are incorrect on Windows machines with more than 64 cores

### ISSUE THREAD

**Issue by faec** [elastic/beats#40926]
On Windows, Metricbeat measures CPU use via the Windows API call `GetSystemTimes`. Each metrics interval, it fetches the CPU numbers, and compares them to the previous measurement to determine CPU load during that interval. On most systems this includes CPU time ["including all threads in all processes, on all processors"](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getsystemtimes). However, on systems with more than 64 cores, it returns only the data for the [current processor group](https://learn.microsoft.com/en-us/windows/win32/procthread/processor-groups) of up to 64 cores.

This has two consequences on high-core machines:
- Reported CPU metrics include only CPU cores in the same processor group as the Metricbeat process.
- When the Windows scheduler moves Metricbeat from one processor group to another (which is unpredictable but happens regularly), `GetSystemTimes` returns data from a different set of cores. If the new processor group has a lower CPU total than the previous one, Metricbeat will report negative numbers for some CPU metrics.

The most visible symptom is occasional negative numbers in CPU-related metrics, especially coming in pairs of two adjacent data points.

This seems to apply to ~all Metricbeat versions, and all versions of Windows that support more than 64 CPU cores.

**Comment by nimarezainia** [comment]
fyi @flexitrev

**Comment by gabriellandau** [comment]
> However, on systems with more than 64 cores, it returns only the data for the current processor group of up to 64 cores.

Is this documented anywhere?  I don't see it in the `GetSystemTimes` docs.

My reading of [this MS doc](https://learn.microsoft.com/en-us/windows/win32/procthread/processor-groups) suggests our threads can switch between processor groups.  Here's python pseudocode to do this.  I don't have a >64T system to test with.

```py 

global last_system_times = {}


def get_cpu_time_deltas():
    idle_time_delta, kernel_time_delta, user_time_delta = 0, 0, 0
    
    # Backup original affinity
    GetThreadGroupAffinity(GetCurrentThread(), &saved_group_affinity)

    # Enumerate each NUMA node
    for node in range(GetNumaHighestNodeNumber()):
        # Enumerate all the processor groups for this NUMA node
        for group_affinity in GetNumaNodeProcessorMask2(node):
        
            # Switch to this processor group
            SetThreadGroupAffinity(GetCurrentThread(), &group_affinity)
            
            # Retrieve metrics for this processor group
            GetSystemTimes(&idle, &kernel, &user)
            
            # Retrieve old values
            if group_affinity.group in last_system_times:
                last_idle, last_kernel, last_user = last_system_times[group_affinity.group]
                
                # Compute deltas
                idle_time_delta += (idle - last_idle)
                kernel_time_delta += (kernel - last_kernel)
                user_time_delta += (user - last_user)
            
            # Store latest values
            last_system_times[group_affinity.group] = (idle, kernel, user)
            
    # Restore original affinity
    SetThreadGroupAffinity(GetCurrentThread(), &saved_group_affinity)
    
    return idle_time_delta, kernel_time_delta, user_time_delta
```

**Comment by VihasMakwana** [comment]
@cmacknz @flexitrev @pierrehilbert 

I ran two instances of the `metricbeat` binary on my personal Windows machine (with 8 cores): one with performance counters enabled and the other with performance counters disabled (using the latest build from the `main` branch). 
Here are the results:

**_The left side of the dashboard is one with performance counters and right side is latest build from `main`_**
- Average CPU usage of my system:
![Image](https://github.com/user-attachments/assets/c7dbdf43-5f2a-40ff-b61c-b9eef8a45bd8)
- Idle CPU % (per core)
![Image](https://github.com/user-attachments/assets/872823ea-76b3-4eb8-a43c-afe0a12c22e6)
- System CPU % (per core)
![Image](https://github.com/user-attachments/assets/39ba9d42-b3cd-47e2-a2c7-05b9364b30ac)
- User CPU % (per core)
![Image](https://github.com/user-attachments/assets/e7f1aae5-7025-4b8e-9eba-54062ad08dc8)

There is a clear correlation between the two sets of data, with the values being identical across both versions.

**Comment by VihasMakwana** [comment]
@pierrehilbert I think I know why. When I started two `metricbeat` binaries, there was a time difference, and the CPU data collection interval was set to 5 seconds. As a result, the two Metricbeat instances likely didn’t capture the CPU times at the exact same moment.

Let me retest it for 30 mins and reduce the interval to `1s` and compare the results.

**Comment by VihasMakwana** [comment]
> Did you check directly in ES values to compare them?
Yes.

**Comment by VihasMakwana** [comment]
@pierrehilbert updated results. I ran two binaries at the exact same time (almost)
![Image](https://github.com/user-attachments/assets/6d7e42fa-446e-4668-8c24-76f81ff0b7bb)
![Image](https://github.com/user-attachments/assets/45fb2e0f-d71e-4b4c-a455-dbd25cdc6ca8)
![Image](https://github.com/user-attachments/assets/3a793da9-47dd-4351-ac72-8cae468e4599)

The results are better than before. What do you think?

**Comment by flexitrev** [comment]
I don't see any performance impact that would worry me. This means if performance counters give us better, more reliable data there is no reason we shouldn't use them.

**Comment by cmacknz** [comment]
Agreed, this looks similar at a high level.

**Comment by cmacknz** [comment]
Since this change looks like it is happening in elastic-agent-system-metrics, which has no mechanism to tie things to a stack release, I would like some way for us to switch between both methods to exist. One that ideally we can expose in the configuration of the system/metrics input.

This will let us update to the latest version of elastic-agent-system-metrics everywhere (because of a CVE related dependency update for example) without worry of also changing underlying behavior, and it will give us a way to easily switch back to the old way immediately if there is some unexpected problem to work around.

Let's avoid the problems we had with turning off the introduction of the degraded state in system metrics, and build a proper feature flag for this from the beginning.

**Comment by VihasMakwana** [comment]
> Since this change looks like it is happening in elastic-agent-system-metrics, which has no mechanism to tie things to a stack release, I would like some way for us to switch between both methods to exist. One that ideally we can expose in the configuration of the system/metrics input.
> 
> This will let us update to the latest version of elastic-agent-system-metrics everywhere (because of a CVE related dependency update for example) without worry of also changing underlying behavior, and it will give us a way to easily switch back to the old way immediately if there is some unexpected problem to work around.
> 
> Let's avoid the problems we had with turning off the introduction of the degraded state in system metrics, and build a proper feature flag for this from the beginning.
> 

I implemented a similar thing initially. Something like following:
- Use Performance counter by default.
- If any errors are encountered, fallback to current implementation.

But your point makes more sense. A flag would be much more preferable.

**Comment by flexitrev** [comment]
I realize I jumped the gun on saying anything about performance here, since the binaries were being run at the same time, and measuring the same thing (thanks @strawgate). What I'd like to make sure is that we are not introducing a performance impact. Can we benchmark the two different approaches?

**Comment by VihasMakwana** [comment]
We're not introducing any performance impact.
The memory usage by `metricbeat` running under `elastic-agent` stays constant. Nothing really stands out between the two versions.

Here's the result of running the `metricbeat` binaries on 180 core machine.
![Image](https://github.com/user-attachments/assets/52cd8ca1-7b15-4350-9bb1-5b9ffd3d7f77)

_**The left side of the dashboard is one with performance counters and right side is latest build from main**_


The number on the right side only reports CPUs from current processor group while the right side of the dashboard utilises performance counters and reports metrics for each core installed on the system/

---

Total CPU usage for both metricbeats:
<p align="center">
<img src="https://github.com/user-attachments/assets/a345d8e1-7b0d-4013-b856-570fd8a4899c">
</p>

The one on the left side is accurate with `Task Manager` and it uses performance counters. 

<p align="center">
<img src="https://github.com/user-attachments/assets/45f8c0e3-ffb2-45b8-b132-092d141665f3" height="500">
</p>

**Comment by VihasMakwana** [comment]
We're not introducing any performance impact.
The memory usage by `metricbeat` running under `elastic-agent` stays constant. Nothing really stands out between the two versions.

The CPU usage by metricbeat stays the same, before and after my implmentation. Here's the graph.
![Image](https://github.com/user-attachments/assets/35a78ac4-ccf4-42db-9f1b-af9061c36ffa)

The "dip" in the graph is when I turned off the agent, so no data was reported during that time, so you can ignore that.
The CPU usage to the left of dip is with `8.17.0-SNAPSHOT` version elastic-agent and right side is with my implementation of performance counters.

**Comment by VihasMakwana** [comment]
Reopening until verified once more.

**Comment by bojian-ben-li** [comment]
Hi team, could you please help check and confirm from which release the fix of this bug will be available?
We have an user have upgraded to 8.16.2 and 8.17.0 but issue persist.

I see these 3 PRs merged on Dec 18 2024.
[[8.x](backport #41965) [system/cpu][system/core] - New config for using performance counters #42024](https://github.com/elastic/beats/pull/42024)
[[8.16](backport #41965) [system/cpu][system/core] - New config for using performance counters #42067](https://github.com/elastic/beats/pull/42067)
[[8.17](backport #41965) [system/cpu][system/core] - New config for using performance counters #42068](https://github.com/elastic/beats/pull/42068) 

Could you please check and confirm the fix is not available in 8.16.2 and 8.17.0, but will be available in the next release which will be 8.16.3 and 8.17.1? Thank you.

**Comment by vishal-jogi** [comment]
Hello @VihasMakwana ,

Could you please check and get back.

Thank you!

**Comment by VihasMakwana** [comment]
@vishal-jogi @bojian-ben-li yes, you're correct.

It will be released in 8.16.3 and 8.17.1

**Comment by vishal-jogi** [comment]
@VihasMakwana Thanks for the confirmation.

I assume the public release dates for these 2 versions are 21 Jan 2025, just checking if it is still valid.

Regards,
Vishal

**Comment by VihasMakwana** [comment]
Yes. That's valid

**Comment by vishal-jogi** [comment]
Hello @VihasMakwana ,

Thanks for the confirmation!

**Comment by apmartins85** [comment]
Hi folks,

Just reporting that version `8.17.1` still have the issue! 
I have tested and the issue is still there!

**Comment by VihasMakwana** [comment]
@apmartins85 can you share your config?

**Comment by apmartins85** [comment]
Hi @VihasMakwana 
I removed a couple of things that it doesn't matter. I have a case in fight inside elasticsearch.

```
metricbeat.modules:

#-------------------------------- System Module --------------------------------
- module: system
  period: 30s
  metricsets:
    - cpu
    - memory
    - network
    - process_summary
  enabled: true
  cpu.metrics:
    - normalized_percentages
    - percentages
- module: system
  period: 60s
  metricsets:
    - filesystem
    - fsstat
  filesystem.ignore_types: [sysfs, rootfs, ramfs, bdev, proc, cgroup, cpuset, tmpfs, devtmpfs, debugfs, securityfs, sockfs, dax, bpf, pipefs, configfs, devpts, hugetlbfs, autofs, pstore, mqueue, binfmt_misc]


- module: beat
  metricsets:
    - stats
    - state
  xpack.enabled: true
  period: 10s
  hosts: ["http://localhost:5066"]


metricbeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

#================================ Processors =====================================

# Configure processors to enhance or manipulate events generated by the beat.

processors:
  - add_host_metadata: ~
  - add_cloud_metadata:
      timeout: 10s
```

**Comment by VihasMakwana** [comment]
@apmartins85 you need to enable a config to solve this issue. Let me share the config.

**Comment by VihasMakwana** [comment]
@apmartins85 here it is:

https://github.com/elastic/beats/blob/424070e87d831d2d66a7514e1c1120ad540a86db/metricbeat/metricbeat.reference.yml#L145-L148

Your updated config would look like:


```yaml
metricbeat.modules:

#-------------------------------- System Module --------------------------------
- module: system
  period: 30s
  use_performance_counters: true
  metricsets:
    - cpu
    - memory
    - network
    - process_summary
  enabled: true
  cpu.metrics:
    - normalized_percentages
    - percentages
- module: system
  period: 60s
  metricsets:
    - filesystem
    - fsstat
  filesystem.ignore_types: [sysfs, rootfs, ramfs, bdev, proc, cgroup, cpuset, tmpfs, devtmpfs, debugfs, securityfs, sockfs, dax, bpf, pipefs, configfs, devpts, hugetlbfs, autofs, pstore, mqueue, binfmt_misc]

```

**Comment by nimarezainia** [comment]
@VihasMakwana i don;t see a documentation issue, please let's document this command if not already done so. thank you. cc: @kilfoyle

**Comment by VihasMakwana** [comment]
Sure Nima. I'll open up an issue.

**Comment by vishal-jogi** [comment]
Hello @VihasMakwana ,

Thanks for your response.

I received the confirmation from customer that it is working fine after enabling - `use_performance_counters: true`.

They have a follow up question:

What occurs if they set this variable to true for VMs with fewer than 64 cores on Windows and Linux? It's essential to understand, as they have over **1000** deployed VMs, some exceeding 64 cores, but the majority have fewer on both Windows and Linux.

Kindly advice, thank you!

**Comment by VihasMakwana** [comment]
@vishal-jogi I'm working on a creating a doc, but here is answer to your question:

> What occurs if they set this variable to true for VMs with fewer than 64 cores on Windows and Linux?
   
- This variable has no effect on non-windows OS'. So, if they use it on linux then it would behave the same way it did before.
- If they use this on machine with fewer than 64 cores on Windows, it would again behave in the same way as before.

Previous version of metricbeat worked fine only on machines with less than 64 cores whereas `8.17.1` will work fine on all the machines regardless of number of cores.
I hope that helps you.

**Comment by vishal-jogi** [comment]
@VihasMakwana Thank you so much for quick assistance.

Will reach out to customer and update you.

**Comment by apmartins85** [comment]
Thanks @VihasMakwana @vishal-jogi 
I truly appreciate your time and your help!

**Comment by apmartins85** [comment]
Folks, just a dummy question:
If you are saying that `use_performance_counters` set to true will not affect any other `VM flavor` or `OS`, why the default value is false?

**Comment by VihasMakwana** [comment]
@apmartins85 We would break things if performance counters are disabled on windows OS (can happen) or if a user doesn't have permissions to read performance counter data (can happen if user is non-root).
We initially enabled it but it broke [our CI](https://github.com/elastic/beats/pull/42041/).

**Comment by VihasMakwana** [comment]
There's no reason to disable them by default If performance counters always succeeded, which unfortunately is not the case :(

**Comment by apmartins85** [comment]
Hi Folks, 
seems like we are facing the same issue with metric/field `system.process.cpu.total.norm.pct` and/or `process.cpu.pct`

ex:

<img width="743" alt="Image" src="https://github.com/user-attachments/assets/fff10031-88bd-4b56-a375-0317d8ffb5b8" />

metricbeat version: `8.17.1`
use_performance_counters was set to `true`

**Comment by VihasMakwana** [comment]
@apmartins85 what are the system configurations?

**Comment by VihasMakwana** [comment]
@apmartins85 I think we're confusing the above document with `system.cpu` metricset.

The one that you shared is for per-process metrics.
But this is issue was about overall system CPU usage i.e. `system.cpu` metricset (not `system.process` metricset).

What you encounter is another bug (??)

**Comment by apmartins85** [comment]
Yes, as I said, I am not sure if there is a relationship between what was fixed and this "new" issue. The common point is we are capturing `cpu`, but for a process.

**Comment by apmartins85** [comment]
this is the module related to service
```
- module: windows
  metricsets: ["service"]
  period: 60s
  processors:
  - drop_event:
      when:
        and:
          - not:
              regexp:
                windows.service.name: '^(blabla.*|WinDefend)$'
          - not:
              regexp:
                windows.service.name: '^(?i)blablaAgent*'
```
metricset is the same

```
- module: system
  period: 30s
  metricsets:
    - cpu
    - memory
    - network
    - process_summary
  enabled: true
  cpu.metrics:
    - normalized_percentages
    - percentages
  use_performance_counters: true
```
