### ISSUE TITLE
ERR Connect failed with: tls: failed to parse certificate from server: asn1: structure error: base 128 integer too large 

### ISSUE THREAD

**Issue by geekpete** [elastic/beats#4093]
- Version: 5.1.1 (potentially all current versions though across all beats, since it apears to be a golang upstream bug)
- Operating System: RHEL 7.2
- Steps to Reproduce: 

A bug identified in Golang seems to be that if particular fields in a certificate is a numeric value that is too large (ObjectIdentifier) then golang is unable to parse it as it cannot store it in the specified data type
https://github.com/golang/go/issues/19933
`encoding/asn1: ObjectIdentifier + crypto/x509.ParseCertificate does not support int > 28 bits`

Basically Golang can't load the certificate so if a user of filebeat tries to use such a certificate they get this error:
`ERR Connect failed with: tls: failed to parse certificate from server: asn1: structure error: base 128 integer too large`

Since this bug in Golang was identified/fixed not very long ago (12 days), it's probably best to come up with a workaround as soon as possible as upgrading the version of Golang might be hard depending on your circumstances and the patched versions of Golang might take a while to filter into default distributions/installations.

Some details from the Golang ticket:
- Minimum reproducer: https://play.golang.org/p/wITjVuO0-F
- The following test cert can also reproduce the problem: `https://www.viathinksoft.de/~daniel-marschall/asn.1/oid-sizecheck/oid_size_test.pem`

Example configuration for filebeat:

```
output.logstash:
  enabled: true
  hosts: ["node1:5044","node2:5044","node3:5044"]
  loadbalance: true
  index: 'whatever_index'
  ssl.enabled: true 
  ssl.certificate_authorities: ["/etc/filebeat/ssl/ca.crt"]
  ssl.certificate: "/etc/filebeat/ssl/client.crt"
  ssl.key: "/etc/filebeat/ssl/client.crt"
```
