### ISSUE TITLE
Exceptions and High CPU on Packetbeat 1.0.0 GA for Redis traffic

### ISSUE THREAD

**Issue by chiriaev** [elastic/beats#410]
Guys, Hi. Submitting an exception I am getting at least once per second. My configuration below. 

Packetbeat takes a lot of CPU... My Redis traffic is intense but not out of the ordinary.

Thanks in advance.

Regards, Andrei
```
---
  logging: {}
  shipper: {}
  interfaces:
    device: any
  output:
    elasticsearch:
      username: username
      hosts:
        - "host:9200"
      password: password
  protocols:
    redis:
      ports:
        - 6379
    dns:
      include_additionals: true
      include_authorities: true
      ports:
        - 53
    http:
      ports:
        - 8002
```
```
Dec  1 19:01:48 c068amw /usr/bin/packetbeat[14563]: log.go:114: Stacktrace: /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/elastic/libbeat/logp/log.go:114 (0x48c3f6)#012/usr/local/go/src/runtime/asm_amd64.s:437 (0x47d72e)#012/usr/local/go/src/runtime/panic.go:423 (0x44d329)#012/usr/local/go/src/runtime/panic.go:42 (0x44b9e9)#012/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x46228a)#012/go/src/github.com/elastic/packetbeat/protos/redis/redis.go:579 (0x51b542)#012/go/src/github.com/elastic/packetbeat/protos/tcp/tcp.go:87 (0x5208d3)#012/go/src/github.com/elastic/packetbeat/protos/tcp/tcp.go:173 (0x521a0d)#012/go/src/github.com/elastic/packetbeat/decoder/decoder.go:136 (0x6c7481)#012/go/src/github.com/elastic/packetbeat/sniffer/sniffer.go:352 (0x532fe9)#012/go/src/github.com/elastic/packetbeat/packetbeat.go:212 (0x422f2b)#012/usr/local/go/src/runtime/asm_amd64.s:1696 (0x47fa71)
Dec  1 19:01:48 c068amw /usr/bin/packetbeat[14563]: log.go:113: ParseRedis exception. Recovering, but please report this: runtime error: invalid memory address or nil pointer dereference.
```
