### ISSUE TITLE
Setting `publisher_pipeline.disable_host: true` has no effect

### ISSUE THREAD

**Issue by chrisberkhout** [elastic/beats#41046]
The `publisher_pipeline.disable_host` option is [documented](https://github.com/elastic/beats/blob/98d34a88a0add89902a526acaf01835cd191e0e9/filebeat/docs/inputs/input-common-options.asciidoc?plain=1#L106-L109) as:

> #### `publisher_pipeline.disable_host`
> 
> By default, all events contain `host.name`. This option can be set to `true` to disable the addition of this field to all events. The default value is `false`.

The setting is applied [in `libbeat/publisher/processing/default.go`](https://github.com/elastic/beats/blob/98d34a88a0add89902a526acaf01835cd191e0e9/libbeat/publisher/processing/default.go#L302-L306).

However, with `publisher_pipeline.disable_host: true` set, `host.*` fields will still be added, unless the `forwarded` tag is also set.

I suspect this is because there is a separate default processor to add host metadata when tags don't contain `forwarded`.

The documentation above, and [some logic](https://github.com/elastic/beats/blob/98d34a88a0add89902a526acaf01835cd191e0e9/libbeat/publisher/processing/default.go#L149C8-L156), refers only to `host.name`, but without the `forwarded` tag a range of fields will be set. For example:

```json
    "host": {
      "hostname": "docker-fleet-agent",
      "os": {
        "kernel": "6.10.9-arch1-2",
        "codename": "focal",
        "name": "Ubuntu",
        "type": "linux",
        "family": "debian",
        "version": "20.04.6 LTS (Focal Fossa)",
        "platform": "ubuntu"
      },
      "containerized": false,
      "ip": [
        "172.18.0.7"
      ],
      "name": "docker-fleet-agent",
      "id": "d7b94aeb4f9141eaa5f345ec31e65c86",
      "mac": [
        "02-42-AC-12-00-07"
      ],
      "architecture": "x86_64"
    },
```

It would be good to remove the `host.name` and `publisher_pipeline.disable_host: true` logic and documentation, and document the `host.*` default processor behavior.

An integration that demonstrates the effect of these settings can be generated with [this script](https://gist.github.com/chrisberkhout/2868d582cb998a72e3161fd57260e1c3).

**Comment by taylor-swanson** [comment]
To add to this, I've observed another strange behavior.

While true that adding `forwarded` to the list of tags will prevent `host.*` fields from being added, if you add an `append` processor that adds fields to tags, `host.*` fields will be added regardless of if `forwarded` is part of the tag list.

Scenarios tested (this was done using a Custom TCP integration):

- Default TCP integration settings: (`host.*` fields added, this is expected)
- Added `forwarded` tag using TCP integration settings: (NO `host.*` fields added, this is expected)
- Added append processor that adds an unrelated tag, the `forwarded` tag is still present from before. (`host.*` fields added, this is NOT expected)

With that final test case, here is the list of tags in the indexed document:

```yaml
[cisco_ise, forwarded]
```

Here is the rendered configuration for the stream from the agent policy:

```yaml
- id: tcp-tcp-2d21df58-7339-4419-bb1a-5d2fbe75efad
  name: tcp-1
  revision: 3
  type: tcp
  use_output: 35856fb2-d4f6-4fe5-ac91-4745ac5a40f7
  meta:
    package:
      name: tcp
      version: 1.19.1
  data_stream:
    namespace: default
  package_policy_id: 2d21df58-7339-4419-bb1a-5d2fbe75efad
  streams:
    - id: tcp-tcp.generic-2d21df58-7339-4419-bb1a-5d2fbe75efad
      data_stream:
        dataset: tcp.generic
      host: 'localhost:9002'
      ssl: null
      tags:
        - forwarded
      publisher_pipeline.disable_host: true
      processors:
        - append:
            target_field: tags
            values:
              - cisco_ise
```

**Comment by chrisberkhout** [comment]
@jlind23 Still planning this?

**Comment by pierrehilbert** [comment]
Hello @chrisberkhout 
We are still planning to fix this but because of competing priorities, we still don't have someone investigating here.
TBH, I don't expect this to move before at least 2w.

**Comment by belimawr** [comment]
I've been testing this and here are my findings:
- `publisher_pipeline.disable_host: true` works as expected for a standalone Filebeat and Filebeat running under Elastic Agent
- Elastic Agent adds a set of default processors on every Beat it runs, those processors are:
    ```
    processors:
      - add_host_metadata:
          when:
            not:
              contains:
                tags: forwarded
      - add_cloud_metadata: ~
      - add_docker_metadata: ~
      - add_kubernetes_metadata: ~
    ```

The `add_host_metadata` processor also sets `host.*` fields, so to completely disable host information when using Elastic Agent, you need something like this in the configuration:
```yaml
inputs:
- id: ea-id
  type: logfile
  use_output: default
  data_stream:
    namespace: default
  streams:
  - id: stream-id
    data_stream:
      dataset: generic
      type: logs
    paths:
      - /var/logs/*.log
    tags:
      - forwarded
      - foo-bar
    publisher_pipeline.disable_host: true
```

Not that both, the `forwarded` tag and `publisher_pipeline.disable_host: true` are added.

---
**The problem with the `append` processor**

I tried the configuration suggested by @taylor-swanson and indeed using the append processor breaks everything. Upon some debugging I can see that after the append processor runs the tags fields is as follows:

Processor configuration:
```yaml
      processors:
        - append:
            target_field: tags
            values:
              - foo_bar
```
Tags in the event:
```json
  "tags": [
    [
      "forwarded",
      "another-tag-from-the-tags-field"
    ],
    "foo_bar"
  ]
```

Because `forwarded` is not at the root of the `tags` array, the condition from `add_host_metadata` does not detect it, therefore the processor still runs.

Interestingly by the time the event gets ingested by Elasticsearch, all those elements are merged into a single array, so the tags field looks like: `["forwarded", "another-tag-from-the-tags-field", "foo_bar"]`.

If tags need to be added with a processor, the `add_tags` processor is the best choice:
```
    processors:
      - add_tags:
          tags: ["foo"]
```

I briefly tested the processor, and the final `tags` array is in the correct format.

---
I believe the correct fix is for Elastic Agent to document the processors that are added by default (currently they're not mentioned in the [docs](https://www.elastic.co/docs/reference/fleet/agent-processors)) and allow those processors to be configured, or at least disabled.
