### ISSUE TITLE
Kafka output plugin to support kafka rack awareness

### ISSUE THREAD

**Issue by kimxogus** [elastic/beats#41594]
**Describe the enhancement:**

As described in https://github.com/elastic/beats/issues/9675 , beats doesn't support kafka rack awareness feature yet.
Rack awareness will help to reduce cross-zone network traffics so that we can reduce network cost and latancies.

**Describe a specific use case for the enhancement or feature:**

```yaml
        output.kafka:
          hosts: [...]
          topic: ...
          client_id: ...
          client_rack: "${AZ_ID}"
```
