### ISSUE TITLE
[Filebeat][input/aws-s3]: backup_to_bucket_arn and delete_after_backup do not work

### ISSUE THREAD

**Issue by constanca-m** [elastic/beats#41784]
`backup_to_bucket_arn` and `delete_after_backup` options do not work. The filebeat keeps processing files from the `bucket_arn` over and over again, and they are never deleted and placed in `delete_after_backup` bucket.

This was tested with version `8.15.3`.

### Example

Filebeat configuration:

```yaml
    filebeat.inputs:
      - type: aws-s3
        enabled: true
        session_token: x
        access_key_id: x
        secret_access_key: x
        bucket_arn: arn:aws:s3:::constanca-test-s3-backup
        backup_to_bucket_arn: arn:aws:s3:::constanca-test-s3-backup-delete
        delete_after_backup: true
        number_of_workers: 5
        bucket_list_interval: 20s
        expand_event_list_from_field: Records
```

Logs that prove filebeat finds the files:

```
{"log.level":"debug","@timestamp":"2024-11-26T08:44:57.564Z","log.logger":"input.aws-s3.s3","log.origin":{"function":"github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*s3ObjectProcessor).ProcessS3Object","file.name":"awss3/s3_objects.go","file.line":129},"message":"Begin S3 object processing.","service.name":"filebeat","id":"6F32504842815259","bucket_arn":"constanca-test-s3-backup","object_key":"export.ndjson","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2024-11-26T08:44:57.564Z","log.logger":"input.aws-s3.s3","log.origin":{"function":"github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*s3ObjectProcessor).ProcessS3Object","file.name":"awss3/s3_objects.go","file.line":129},"message":"Begin S3 object processing.","service.name":"filebeat","id":"6F32504842815259","bucket_arn":"constanca-test-s3-backup","object_key":"gopher.png","ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2024-11-26T08:44:57.673Z","log.logger":"input.aws-s3.s3","log.origin":{"function":"github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*s3ObjectProcessor).ProcessS3Object.func1","file.name":"awss3/s3_objects.go","file.line":137},"message":"End S3 object processing.","service.name":"filebeat","id":"6F32504842815259","bucket_arn":"constanca-test-s3-backup","object_key":"export.ndjson","elapsed_time_ns":108787233,"ecs.version":"1.6.0"}
{"log.level":"debug","@timestamp":"2024-11-26T08:44:57.775Z","log.logger":"input.aws-s3.s3","log.origin":{"function":"github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*s3ObjectProcessor).ProcessS3Object.func1","file.name":"awss3/s3_objects.go","file.line":137},"message":"End S3 object processing.","service.name":"filebeat","id":"6F32504842815259","bucket_arn":"constanca-test-s3-backup","object_key":"gopher.png","elapsed_time_ns":210936613,"ecs.version":"1.6.0"}
```

However, the file remains in `bucket_arn`:
![Image](https://github.com/user-attachments/assets/55a11cd7-7581-4921-9393-866bf02ead55)

And `backup_to_bucket_arn` remains empty:
![Image](https://github.com/user-attachments/assets/3a53e42e-7dfd-41cb-acc0-0657dbe178b9)

**Comment by kaiyan-sheng** [comment]
The fix is added back in PR: https://github.com/elastic/beats/pull/41071 
But seems like the fix has been removed by a later on PR: https://github.com/elastic/beats/pull/40699

We should add the feature back and add tests to make sure the regression does not happen again.

**Comment by pitrson** [comment]
Hi there!

This doesn't seem to be fixed or reappeared again in newer versions.
filebeat version: 9.1.3
input plugin: aws-s3
s3: minio
config:

```
      filebeat.inputs:
        - type: aws-s3
          non_aws_bucket_name: inventory
          path_style: true
          number_of_workers: 5
          bucket_list_interval: 60s
          access_key_id: x
          secret_access_key: x
          endpoint: <minio S3>
          decoding.codec.parquet.enabled: true
          ignore_older: 168h
          backup_to_bucket_prefix: processed/
          non_aws_backup_to_bucket_name: inventory-backup
          delete_after_backup: true
```

It's clearly visible that filebeat fully processes the object, although it is not backed up nor deleted after processing.
registry log:

```
{"k":"filebeat::aws-s3::state::xxx/2025-09-17T11-20Z/files/b91d4a19-fa2e-4f42-a4c6-8f4dfa08e6dc.parquet\"ebafc416eb526599fa6d7832cc60d0c5-4\"2025-09-17 11:20:36.991 +0000 UTC","v":{"etag":"\"ebafc416eb526599fa6d7832cc60d0c5-4\"","last_modified":[281471672743360,1758108036],"stored":true,"failed":false,"bucket":"inventory","key":"xxx.parquet"}}
```

tracing the S3 calls from filebeat to S3 shows, that there's no call related to moving the objects nor deleting the objects made.
