### ISSUE TITLE
Move all modules to using filestream

### ISSUE THREAD

**Issue by rdner** [elastic/beats#41861]
**Describe the enhancement:**

We currently have a lot of modules that are still using the `log` input type (deprecated since 7.16.0) with unstable file identification that, due to file rotation, leads to parsing errors (e.g. multiline grok or JSON parser), data duplication and even possible data loss.

* OSS Filebeat – [25 files](https://github.com/search?q=repo%3Aelastic%2Fbeats+%22type%3A+log%22+path%3A%2F%5Efilebeat%5C%2Fmodule%5C%2F%2F&type=code)
* X-Pack Filebeat – [97 files](https://github.com/search?q=repo%3Aelastic%2Fbeats+%22type%3A+log%22+path%3A%2F%5Ex-pack%5C%2Ffilebeat%5C%2Fmodule%5C%2F%2F&type=code)

**Describe a specific use case for the enhancement or feature:**

We should migrate all of the above mentioned modules to using `type: filestream` + `fingerprint` file identity.

For example, [this Elasticsearch GC module](https://github.com/elastic/beats/blob/v8.15.2/filebeat/module/elasticsearch/gc/config/gc.yml) would change from:

```yaml
type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$"]
exclude_lines: ["^(OpenJDK|Java HotSpot).* Server VM ", "^CommandLine flags: ", "^Memory: ", "^{"] # exclude JVM8 banner and JSON
multiline:
  pattern: '^(\[?[0-9]{4}-[0-9]{2}-[0-9]{2}|{)'
  negate: true
  match: after
processors:
  - add_fields:
      target: ''
      fields:
        ecs.version: 1.12.0
```

to

```yaml
type: filestream
id: <some-globally-unique-id>
take_over: true
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$"]
exclude_lines: ["^(OpenJDK|Java HotSpot).* Server VM ", "^CommandLine flags: ", "^Memory: ", "^{"] # exclude JVM8 banner and JSON
multiline:
  pattern: '^(\[?[0-9]{4}-[0-9]{2}-[0-9]{2}|{)'
  negate: true
  match: after
processors:
  - add_fields:
      target: ''
      fields:
        ecs.version: 1.12.0
```

```diff
1c1,8
< type: log
---
> type: filestream
> id: <some-globally-unique-id>
> take_over: true
```

The main challenge here is to introduce the ability to set a unique ID to each module. We can use a default value unique to each module but if we allow users to run multiple modules of the same type, their filestream inputs must have unique identifiers.

### Useful links

* `take_over` https://www.elastic.co/guide/en/beats/filebeat/8.16/filebeat-input-filestream.html#filebeat-input-filestream-take-over
* `prospector.scanner.fingerprint` https://www.elastic.co/guide/en/beats/filebeat/8.16/filebeat-input-filestream.html#filebeat-input-filestream-scan-fingerprint
* `file_identity` https://www.elastic.co/guide/en/beats/filebeat/8.16/filebeat-input-filestream.html#_file_identity_2
