### ISSUE TITLE
Investigate if it is possible to prevent inputs with non-unique IDs from being templated by autodiscovery

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#41881]
- Relates https://github.com/elastic/beats/issues/40540
- Relates https://github.com/elastic/beats/pull/41731

When using an autodiscovery provider with Filebeat, investigate what happens when the variable substitution would result in two filestream inputs with a non-unique ID. If Filebeat allows the creation of multiple filestream inputs with the same ID, propose a way to prevent this from happening.

Elastic Agent forces the IDs to be unique when using the local dynamic provider, below is a simple example of an agent policy creating this situation. If the `my_file` variable is omitted, only a single input is created. Creating inputs with the same ID is impossible in Elastic Agent and we want the same behaviour in Filebeat.

For an example of the problem this is trying to prevent, a common mistake was setting the input ID on Kubernetes to `kubernetes-container-logs-${kubernetes.pod.name}` when an input per running container is used instead of the unique `kubernetes-container-logs-${kubernetes.pod.name}-${kubernetes.container.id}`

```yaml
outputs:
  default:
    type: elasticsearch
    hosts: [127.0.0.1:9200]
    api_key: "example-key"
    preset: balanced

inputs:
  - type: filestream
    id: ${local_dynamic.my_var}
    data_stream:
      dataset: generic
    paths:
      - /var/log/${local_dynamic.my_file}
  
providers:
 local_dynamic:
   enabled: true
   items:
     - vars:
         my_var: A
         my_file: a.log
     - vars:
         my_var: A
         my_file: b.log
     - vars:
         my_var: A
         my_file: c.log
```

This results in the following running inputs:

```
./elastic-agent status --output=full
┌─ fleet
│  └─ status: (STOPPED) Not enrolled into Fleet
└─ elastic-agent
   ├─ status: (HEALTHY) Running
   ├─ info
   │  ├─ id: 88d066e9-f099-4769-9416-f20f1792d081
   │  ├─ version: 8.15.2
   │  └─ commit: 621bbc685c2de8a2ad2c7c7f7cc1eb5fcf77d6d4
   ├─ filestream-default
   │  ├─ status: (HEALTHY) Healthy: communicating with pid '96292'
   │  ├─ filestream-default
   │  │  ├─ status: (HEALTHY) Healthy
   │  │  └─ type: OUTPUT
   │  ├─ filestream-default-A-local_dynamic-0
   │  │  ├─ status: (HEALTHY) Healthy
   │  │  └─ type: INPUT
   │  ├─ filestream-default-A-local_dynamic-1
   │  │  ├─ status: (HEALTHY) Healthy
   │  │  └─ type: INPUT
   │  └─ filestream-default-A-local_dynamic-2
   │     ├─ status: (HEALTHY) Healthy
   │     └─ type: INPUT
```

**Comment by belimawr** [comment]
I've been looking on how the Elastic-Agent implements ID uniqueness for its inputs. Every provider has to add or update its variables into the `dynamicProviderState` via the `AddOrUpdate` method. This method requires an ID, that should be unique. Later when the coordinator render the inputs, it generates the final input ID by concatenating the current input ID (after rendering) with the provider name and the ID the provider gave to its set of variables.

Example:

```
inputs:
  - type: filestream
    id: user-defined-ID-${local_dynamic.my_var}
    data_stream:
      dataset: generic
    paths:
      - /var/log/foo.log
  
providers:
 local_dynamic:
   enabled: true
   items:
     - vars:
         my_var: A
```
The local provider used the index in the `items` array as its ID, so once the input is rendered we have:
```
id: user-defined-ID-A
```
This gets concatenated with the provider's name and the ID it gave to the variables (`0` in this case), which leaves us with the final ID:
```
user-defined-ID-A-local_dynamic-0
```

For other providers like Kubernetes or Docker, they use an UID of the element being discovered, which is always unique.

I believe we can implement a similar logic into Beats autodiscover: whenever it renders a template, the provider will provide an unique ID alongside each set of variables, whenever they're used to render an input template, this appended at the end of the input ID together with the provider name. If there was no ID defined in the input template, it's considered as being an empty string and added to the final configuration.

It is important to keep in mind this will be a breaking change for the Filestream input because the final ID will be different than what is defined in the autodiscovery configuration, which will have the side effect of re-ingesting some files when upgrading from 8.x to 9.x.
