### ISSUE TITLE
Log files are rotated on startup when interval is configured and rotateonstartup is disabled

### ISSUE THREAD

**Issue by nicholasberlin** [elastic/beats#41894]
With the following logging configuration
```
logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/packetbeat/logs
  name: packetbeat
  interval: 24h
  keepfiles: 14
  permissions: 0640
  rotateonstartup: false
  rotateeverybytes: 1048576000
  suffix: date
```
The expected behavior is for the log files to rotate daily as long as the size does not go over 1GB. However, despite `rotateonstartup: false`, the logs rotate on next startup.

Version: 8.15.4
Operating System: Linux
Steps to reproduce:
```
% sudo ./packetbeat      
^C                                                                                                                                                                                                     
% ls /tmp/packetbeat/logs
packetbeat-20241126-1.ndjson    packetbeat-20241126.ndjson
% sudo ./packetbeat      
^C                                                                                                                                                                                                     
% ls /tmp/packetbeat/logs
packetbeat-20241126-1.ndjson    packetbeat-20241126-2.ndjson    packetbeat-20241126.ndjson
```
