### ISSUE TITLE
Metricbeat complains about lack of platinum license on standard install

### ISSUE THREAD

**Issue by piotrp** [elastic/beats#41953]
When `xpack.enabled: true` is used with the Elasticsearch module on a non-platinum cluster I get the message about `ccr` metricset, repeated every minute:

```
the CCR feature is available with a platinum or enterprise Elasticsearch license. You currently have a basic license. Either upgrade your license or remove the ccr metricset from your Elasticsearch module configuration.
```

I didn't have any metricsets manually configured, so I followed this advice and listed all of them execept for `ccr`, and I still got this warning.

Metricbeat 8.16.1, installed from official deb repository.

Configuration:

```yaml
name: "nodename"

metricbeat.modules:
  - module: system
    enabled: false
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts:
      - "http://127.0.0.1:9200"

output.elasticsearch:
    hosts: [ "http://127.0.0.1:9200" ]
```

There was a previous issue (#24059) that got closed without any solution, so feel free to reopen it and close mine.
