### ISSUE TITLE
Support filebeat kafka output's MSK IAM Auth

### ISSUE THREAD

**Issue by kimxogus** [elastic/beats#42248]
**Describe the enhancement:**
Filebeat's kafka output to support msk iam authentication.

**Describe a specific use case for the enhancement or feature:**
Maybe config like this
```yaml
output.kafka:
  hosts: ...msk-broker-hosts...
  auth: 
    method: iam
```
