### ISSUE TITLE
metricbeat runs happily for a while and then starts getting 401 errors when fetching metrics

### ISSUE THREAD

**Issue by danfinn** [elastic/beats#42307]
version 8.14.0 on k8s installed via helm as a daemonset on Azure AKS

We noticed recently that some of our clusters are missing metrics.  It appears that metricbeat is getting a 401 from the k8s API (I think that is where the query goes to anyways) but the strange thing is that this doesn't happen right away.  If I restart the pods, they will run for some amount of time, for example an hour, and then they will start showing the following error:

```
{"log.level":"error","@timestamp":"2025-01-14T19:51:34.027Z","log.origin":{"function":"github.com/elastic/beats/v7/metricbeat/mb/module.(*metricSetWrapper).fetch","file.name":"module/wrapper.go","file.line":256},"message":"Error fetching data for metricset kubernetes.volume: error doing HTTP request to fetch 'volume' Metricset data: HTTP error 401 in : 401 Unauthorized","service.name":"metricbeat","ecs.version":"1.6.0"}
```

This has been in place and working for quite some time.  We have both linux and windows nodes that metricbeat runs on and both are seeing this error.

metricbeat config:

```
  metricbeat.yml: |
    setup:
      template:
        enabled: false
        #name: "${INDEX_TEMPLATE_NAME}"
        #pattern: "*-*-*-metrics-*"
        #fields: "fields.yml"
        #settings:
          #index.number_of_shards: 1
          #index.number_of_replicas: 1
          #index.lifecycle.name: "bmap_obsv_ilm_policy"
      ilm:
        enabled: true
      kibana:
        host: "${KIBANA_HOST:kibana.example.com:5601}"
        protocol: "${KIBANA_PROTOCOL:https}"
        ssl.verification_mode: "${KIBANA_VERIFYSSL:none}"
        username: "${KIBANA_USERNAME:kibana}"
        password: "${KIBANA_PASSWORD:welcome1}"

    logging:
      level: "${LOG_LEVEL:warning}"
      to_stderr: true
      json: true

    metricbeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true

    output.elasticsearch:
      hosts: "[${ELASTICSEARCH_HOST}:9200]"
      protocol: "${ELASTICSEARCH_PROTOCOL:https}"
      username: "${ELASTICSEARCH_USERNAME:elastic}"
      ssl.verification_mode: "${ELASTICSEARCH_VERIFYSSL:none}"
      password: "${ELASTICSEARCH_PASSWORD:welcome1}"
      index: "${INDEX_NAME}-%{[agent.version]}-%{+yyyy.MM.dd}"
      allow_older_versions: true

    processors:
       - drop_event.when:
           or:
           - equals:
               kubernetes.namespace: "azure-sql-exporter"
           - equals:
               kubernetes.namespace: "azure-sql-operator-system"
           - equals:
               kubernetes.namespace: "akv2k8s"
           - equals:
               kubernetes.namespace: "monitoring"
           - equals:
               kubernetes.namespace: "deploys"
           - equals:
               kubernetes.namespace: "tigera-operator"
           - equals:
               kubernetes.namespace: "calico-system"
           - equals:
               kubernetes.namespace: "kube-system"
           - equals:
               kubernetes.namespace: "kube-public"
           - equals:
               kubernetes.namespace: "kube-node-lease"
           - equals:
               kubernetes.namespace: "gatekeeper-system"
           - equals:
               kubernetes.namespace: "ots"
           - equals:
               kubernetes.namespace: "grafana"

    metricbeat.modules:
    - module: kubernetes
      metricsets:
        - container
        - node
        - pod
        - system
        - volume
      period: 1m
      host: "${NODE_NAME}"
      hosts: ["https://${NODE_NAME}:10250"]
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      ssl.verification_mode: "none"
      processors:
      - add_kubernetes_metadata: ~

    - module: kubernetes
      enabled: true
      metricsets:
        - event

    - module: system
      period: 1m
      metricsets:
        - filesystem
        - fsstat
      processors:
      - drop_event.when.regexp:
          system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

    - module: system
      period: 1m
      metricsets:
        - core
        - cpu
        - diskio
        - load
        - memory
        - network
        - process
        - process_summary
      processes: ['.*']
      process.include_top_n:
        by_cpu: 5
        by_memory: 5
```
