### ISSUE TITLE
Allow changing filestream IDs without duplication by providing the previous ID values

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#42472]
**Describe the enhancement:**

This relates to the discussion in https://github.com/elastic/elastic-agent/pull/6583#discussion_r1934067325 where we believe we should change the default container input ID. We need a way to do this without duplicating data when this happens. One way to solve this is to simply tell the filestream input what ID it should take over from.

**Describe a specific use case for the enhancement or feature:**

Provide a way to list previous filestream input IDs such that it will start from where it left off even if the ID changes. For example:

```yaml
id: container-log-${kubernetes.namespace}-${kubernetes.pod.name}-${kubernetes.container.id}
previous_ids:
 - container-log-${kubernetes.pod.name}-${kubernetes.container.id}
```
