### ISSUE TITLE
[fbreceiver] Default Processors are not being applied

### ISSUE THREAD

**Issue by khushijain21** [elastic/beats#42631]
When fbreceiver is created, it adds default processor to the settings here. https://github.com/elastic/beats/blob/95b5dce16c07df1c2f1aa88dc4aa507441504e78/x-pack/filebeat/fbreceiver/factory.go#L40

Expected:
It is expected that all documents ingested have `host` related fields added to it. According to this ref here https://www.elastic.co/guide/en/beats/filebeat/current/add-host-metadata.html

Got:
Except for `host.name`, no other fields are part of the ingested doc. 

When we explicitly set the default processor in the config file. It correctly adds all `host` related fields. 

### How to test this locally
1. `cd x-pack/filebeat`
2. `mage docker:composeUp`
3. Change `filebeat-otel.yml` to following config 

```
filebeat.inputs:
  - type: filestream
    id: filestream-input-id
    enabled: true
    paths:
      - ./test.log

output:
  elasticsearch:
    hosts: ["http://localhost:9200"]
    username: admin
    password: testing

setup.kibana:
  host: http://localhost:5601
  username: admin
  password: testing
```

4. Start filebeat in otel mode 
```
./filebeat otel 
```

Check the document ingested

5. Add processors and run with the same command again. 
```
processors:
  - add_host_metadata:
      when:
        not:
          contains:
            tags: forwarded
```

6. The host related parameters are correctly set
