### ISSUE TITLE
Metricbeat (Module - Jolokia): No result querying space separated mbeans

### ISSUE THREAD

**Issue by thmshmm** [elastic/beats#4265]
- Versions: Metricbeat 5.4.0, Jolokia 1.3.6
- OS: RHEL7

Steps to reproduce (metricbeat.yml):
```
- module: jolokia
  metricset: ["jmx"]
  hosts: ["localhost:1234"]
  namespace: "xyz"
  jmx.mappings:
    - mbean: 'java.lang:type=GarbageCollector,name=PS MarkSweep'
      attributes:
        - attr: LastGcInfo
          field: last_gc_info
```

This configuration snippet generates no output. Mbeans without space separation work as expected. Can someone confirm this?

**Comment by thmshmm** [comment]
Found a solution. While Jolokia does not care about the structure of the mbean name, Metricbeat does so.

For example both Jolokia queries work:
```
/jolokia/read/java.lang:type=GarbageCollector,name=PS%20MarkSweep
/jolokia/read/java.lang:name=PS%20MarkSweep,type=GarbageCollector
```
while for Metricbeat only this works:
```
- module: jolokia
  metricset: ["jmx"]
  hosts: ["localhost:1234"]
  namespace: "xyz"
  jmx.mappings:
    - mbean: 'java.lang:name=PS MarkSweep,type=GarbageCollector'
      attributes:
        - attr: LastGcInfo
          field: last_gc_info
```
The right order always seems to be the one from the JSON result from Jolokia.
