### ISSUE TITLE
Document authentication/SSL support for http, jolokia and other metricbeats

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#4268]
Metricbeat modules like http and jolokia actually already support authentication in the product today.   This means that we have some stale documentation to update :)

* https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-metricset-jolokia-jmx.html#_limitations (For Jolokia, it still talks about not having authentication support as a limitation)
* Documentation for both modules do not provide info on how users will pass in authentication information.  If this is done via passing in authorization information in the request headers, it will be nice to provide an example
  * https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-jolokia.html
  * https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-http.html
* While we are at it, if these modules also support SSL configuration, it will be helpful to document the available configuration settings as well.

**Comment by ppf2** [comment]
Example configuration for authentication in metricbeat modules.  
Authentication info can be provided either directly in the URL, or as separate settings.

```
metricbeat.modules:
- module: x
  hosts: ['https://me:secret@localhost']
- module: x
  hosts: ['https://localhost']
  username: me
  password: secret
```

Example configuration for SSL in metricset modules:

```
metricbeat.modules:
- module: x
  hosts: ['https://me:secret@localhost']
  ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]
```
