### ISSUE TITLE
Winblogbeat with `winlogbeat.event_logs.no_more_events` configured to `stop` should flush the event queue

### ISSUE THREAD

**Issue by 0xThiebaut** [elastic/beats#42693]
It is common to rely on Winlogbeat to convert Windows event logs into JSON files through `winlogbeat.exe run`. However, the implicit behavior of the `winlogbeat.event_logs.no_more_events` setting leads to the last batch of queued events not being outputted.

The beneath configuration can typically be used to convert a Windows event log to JSON files and gracefully terminate once the file has been processed (`no_more_events: stop`).

```yaml
winlogbeat.event_logs:
  - name: 'C:\Users\User\Downloads\Security.evtx'
    include_xml: true
    no_more_events: stop
output.file:
  enabled: true
  path: 'C:\Users\User\Downloads'
  filename: "Security"
  rotate_every_kb: 100000
  number_of_files: 1024
logging.to_stderr: true
```

However, due to the usage of queues, the above configuration will not output the last batch of the queue. While a workaround can be to set `winlogbeat.shutdown_timeout` (which defaults to `0`) to the value of `queue.mem.flush.timeout` (which defaults to `10s`), the `no_more_events: stop` configuration should not result in events being dropped. Instead, `no_more_events: stop` should ensure the buffer is flushed before terminating.

The issue can easily be reproduced by using the above configuration to convert a recently cleared Windows security log (hence only containing a single event `1102`), resulting in no JSON file being created as the `queue.mem.flush.min_events` threshold is not reached.
