### ISSUE TITLE
Beat Stats incorrectly reporting CPU Usage

### ISSUE THREAD

**Issue by strawgate** [elastic/beats#42818]
When running Filebeat in a background job under Bash
`filebeat -e -c filebeat.yml & > /dev/null`

```
filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - ./sample.log
    
output.elasticsearch:
  hosts: ["http://localhost:9200"]

http.enabled: true
http.port: 5070
http.pprof.enabled: true
http.host: 0.0.0.0
```

When collecting the stats from the process on macos

<img width="335" alt="Image" src="https://github.com/user-attachments/assets/22e33a71-f1ae-4253-be8e-56982524052e" />

the stats appears to be showing the cpu total for the parent pid, in this case bash, instead of for itself:
<img width="510" alt="Image" src="https://github.com/user-attachments/assets/a5fc6252-238d-41fe-98a6-9ff0e28fcb53" />
