### ISSUE TITLE
Missing input ID warning is emitted for all inputs when using autodiscover

### ISSUE THREAD

**Issue by belimawr** [elastic/beats#42969]
The missing input ID warning meant for the Filestream input is being emitted to all inputs without an ID whenever autodiscover is used.

This is just a log warning, the input is started as expected.

- Version: 8.16.1, 8.17.0, 
- Operating System: All
- Discuss Forum URL: https://discuss.elastic.co/t/warning-is-observed-huge-number-of-times-input-v2-factory-checkconfig-failed-to-clone-config-before-checking-it-original-config-will-be-checked-it-might-trigger-an-input-duplication-warning-failed-to-get-id-missing-field-accessing-id/374722

## Steps to Reproduce: 
1. Start Filebeat with the following configuration
    ```yaml
    filebeat.autodiscover.providers:
      - type: docker
        hints.enabled: true
        hints.default_config:
          type: log
          paths:
            - /tmp/flog.log
          fields:
            foo: ${data.container.id}
    
    queue.mem:
      flush.timeout: 0
    
    output.discard:
      enabled: true
    ```
2. You will see the following warning log
```json
{
  "log.level": "warn",
  "@timestamp": "2025-02-28T16:36:19.405-0500",
  "log.logger": "input",
  "log.origin": {
    "function": "github.com/elastic/beats/v7/filebeat/input/v2/compat.(*factory).CheckConfig",
    "file.name": "compat/compat.go",
    "file.line": 81
  },
  "message": "input V2 factory.CheckConfig failed to clone config before checking it. Original config will be checked, it might trigger an input duplication warning: failed to get 'id': missing field accessing 'id'",
  "service.name": "filebeat",
  "original_config": "{\n  \"fields\": {\n    \"foo\": \"d5062d3af164a2a57d0e9bed5c201dc7a7e0f6814a59665b0973d8fba35fe432\"\n  },\n  \"paths\": [\n    \"/tmp/flog.log\"\n  ],\n  \"type\": \"log\"\n}",
  "ecs.version": "1.6.0"
}
```

## Workaround
While this is just a log warning and the input is still started as expected. The log warning can be ignored or if you want to suppress it, just add and ID to every input. For the example reproducing it will look like:
```yaml
filebeat.autodiscover.providers:
  - type: docker
    hints.enabled: true
    hints.default_config:
      type: log
      id: foo-bar-${data.container.id}
      paths:
        - /tmp/flog.log
      fields:
        foo: ${data.container.id}

queue.mem:
  flush.timeout: 0

output.discard:
  enabled: true

```

**Comment by cbeaujoin-stellar** [comment]
Hello,

I have the same kind of issues with:
```
filebeat.autodiscover:
  providers:
    - hints.default_config:
        type: filestream
        id: "${data.container.id}"
        paths:
          - /var/lib/docker/containers/${data.container.id}/*.log
      hints.enabled: true
      type: docker
```

Using hint in the compose file:

```
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/module: elasticsearch
```

I have to select only one fileset otherwise, I have this issue that seems to be linked:
```
      co.elastic.logs/fileset: server
```

Logs:

```
{"log.level":"error","@timestamp":"2025-03-17T11:28:59.045Z","log.logger":"input","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*InputManager).Create","file.name":"input-logfile/manager.go","file.line":174},"message":"filestream input with ID 'f3a08f3a07d4bb613aa9bbdf9f2954b53f4d8a10ede1fc9422888f00bda4ac75' already exists, this will lead to data duplication, please use a different ID. Metrics collection has been disabled on this input.","service.name":"filebeat","ecs.version":"1.6.0"}
2025-03-17T11:28:59.045496113Z {"log.level":"error","@timestamp":"2025-03-17T11:28:59.045Z","log.logger":"input","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*InputManager).Create","file.name":"input-logfile/manager.go","file.line":174},"message":"filestream input with ID 'f3a08f3a07d4bb613aa9bbdf9f2954b53f4d8a10ede1fc9422888f00bda4ac75' already exists, this will lead to data duplication, please use a different ID. Metrics collection has been disabled on this input.","service.name":"filebeat","ecs.version":"1.6.0"}
2025-03-17T11:28:59.045596611Z {"log.level":"error","@timestamp":"2025-03-17T11:28:59.045Z","log.logger":"input","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*InputManager).Create","file.name":"input-logfile/manager.go","file.line":174},"message":"filestream input with ID 'f3a08f3a07d4bb613aa9bbdf9f2954b53f4d8a10ede1fc9422888f00bda4ac75' already exists, this will lead to data duplication, please use a different ID. Metrics collection has been disabled on this input.","service.name":"filebeat","ecs.version":"1.6.0"}
2025-03-17T11:28:59.045714643Z {"log.level":"error","@timestamp":"2025-03-17T11:28:59.045Z","log.logger":"input","log.origin":{"function":"github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*InputManager).Create","file.name":"input-logfile/manager.go","file.line":174},"message":"filestream input with ID 'f3a08f3a07d4bb613aa9bbdf9f2954b53f4d8a10ede1fc9422888f00bda4ac75' already exists, this will lead to data duplication, please use a different ID. Metrics collection has been disabled on this input.","service.name":"filebeat","ecs.version":"1.6.0"}
```

If I remove `id: "${data.container.id}"`, I got the same logs + the warning log:
```
"input V2 factory.CheckConfig failed to clone config before checking it. Original config will be checked, it might trigger an input duplication warning: failed to get 'id': missing field accessing 'id'",
```

Fixing this warning should solve the others.

**Comment by cbeaujoin-stellar** [comment]
@belimawr 
```
# Version of Elastic products
STACK_VERSION=8.17.3
```

**Comment by belimawr** [comment]
@AndersonQ, https://github.com/elastic/beats/pull/35134 was supposed to fix this issue, right?

**Comment by AndersonQ** [comment]
> [@AndersonQ](https://github.com/AndersonQ), [#35134](https://github.com/elastic/beats/pull/35134) was supposed to fix this issue, right?

yes, unless there is another thing causing `filestream input with ID 'ID' already exists` log to be emitted.

**Comment by cbeaujoin-stellar** [comment]
Should we be able to specify the filestream input id per fileset ?

Or maybe just makes it unique, currently it seems to be based on the :
```
    - hints.default_config:
        type: filestream
        id: "${data.container.id}"
```

id could be "${data.container.id}" + "fileset name" (or id, or whatever could be unique in your existing fileset data structure.

**Comment by belimawr** [comment]
`"${data.container.id}"` is unique, unless you have another configuration also starting Filestream inputs with this ID.

Could you post here your full input/autodiscovery configuration?

**Comment by cbeaujoin-stellar** [comment]
Sure:

```
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.autodiscover:
  providers:
    - hints.default_config:
        type: filestream
        id: "${data.container.id}"
        paths:
          - /var/lib/docker/containers/${data.container.id}/*.log
      hints.enabled: true
      type: docker


output.elasticsearch:
  hosts: [ "https://elk-dev-monitoring-01:9200" ]
  username: "filebeat_monitoring"
  password: "${FILEBEAT_MONITORING_USER_PASSWORD}"
  ssl.enabled: true
  ssl.certificate_authorities: [ "config/certs/ca.crt" ]
  ssl.verification_mode: "full"

setup.dashboards.enabled: true

setup.kibana:
  host: "https://elk-dev-monitoring-kibana:5601"
  ssl.enabled: true
  ssl.certificate_authorities: [ "config/certs/ca.crt" ]
  ssl.verification_mode: "full"
  username: 'filebeat_setup_user'
  password: "${FILEBEAT_SETUP_USER_PASSWORD}"

setup.ilm.enabled: false

#=============================X-Pack Monitoring==============================
# This self enables monitoring of this beat so you don't need the beats-xpack
monitoring:
  enabled: true
  cluster_uuid: ${CLUSTER_UUID}
  elasticsearch:
    hosts: [ "https://elk-dev-monitoring-01:9200" ]
    username: "remote_monitoring_user"
    password: "${REMOTE_MONITORING_USER_PASSWORD}"
    ssl.enabled: true
    ssl.certificate_authorities: [ "config/certs/ca.crt" ]
    ssl.verification_mode: "full"
```

**Comment by AndersonQ** [comment]
@cbeaujoin-stellar is there any module enabled? you have 
```
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
```

but you didn't mention if there is any enabled, and if so, you didn't post them

**Comment by p4block** [comment]
We're also getting this warning spam.
We run this beat (probably very improvable) config:
```
---
apiVersion: v1
kind: Secret
metadata:
  name: filebeat-config
  namespace: elastic-stack
stringData:
  beat.yml: |-
    logging:
      level: warning
    filebeat:
      autodiscover:
        providers:
          - type: kubernetes
            templates:
              - condition.and:
                 - not.equals:
                    kubernetes.container.name: oauth2-proxy
                 - not.equals:
                    kubernetes.container.name: helper
                 - not.equals:
                    kubernetes.namespace: kube-system
                 - not.equals:
                    kubernetes.namespace: argocd
                config:
                  - type: container
                    paths:
                      - /var/log/containers/*${data.kubernetes.container.id}.log
    processors:
    - drop_event:
        when:
          and:
            - contains:
                kubernetes.container.name: mongodb
            - contains:
                message: ',"s":"I"'
    - drop_event:
        when:
          and:
            - contains:
                kubernetes.namespace: public-ingress-nginx
            - contains:
                kubernetes.container.name: controller
            - not:
                regexp:
                  message: '^{"datetime":'
    - add_host_metadata:
        netinfo.enabled: false
    - add_tags:
        tags: [kubernetes]
    setup:
      dashboards:
        enabled: false
      template:
        settings:
          index.number_of_shards: 1
          index.number_of_replicas: 0
    output.elasticsearch:
      pipeline: parse-json
      indices:
        - index: "k8s-%{[kubernetes][container][name]}-%{+YYYY.MM.ww}-%{[stream]}"
          when.has_fields: ['kubernetes.namespace']
        - index: "k8s-unclassified-%{+YYYY.MM.ww}-%{[stream]}"
```

**Comment by cbeaujoin-stellar** [comment]
Any update ?

**Comment by belimawr** [comment]
> Any update ?

Not yet, but we're aware of it. I'll try to get it prioritised soon, however I cannot make any promises.

**Comment by cbeaujoin** [comment]
Hello, it's been long time, any update ?

**Comment by cbeaujoin** [comment]
Hello @belimawr ,

With:

```
# Version of Elastic products
STACK_VERSION=9.1.5
```

Using hints without specifying a single fileset:

```
  elk-dev-01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_DEV_VERSION}
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/module: elasticsearch
```
```
  elk-dev-kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_DEV_VERSION}
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/module: kibana
```
```
  elk-dev-logstash:
    restart: unless-stopped
    image: docker.elastic.co/logstash/logstash:${STACK_DEV_VERSION}
    labels:
      co.elastic.logs/enabled: true
      co.elastic.logs/module: logstash
```

It still not working.

Here are the logs:

```
Enabled modules/filesets: elasticsearch (slowlog), elasticsearch (audit), elasticsearch (deprecation), elasticsearch (gc), elasticsearch (server) | log.level=info @timestamp=2025-10-14T08:57:31.999Z log.logger=modules log.origin={"function":"github.com/elastic/beats/v7/filebeat/fileset.newModuleRegistry","file.name":"fileset/modules.go","file.line":135} service.name=filebeat ecs.version=1.6.0

Enabled modules/filesets: logstash (log), logstash (slowlog) | log.level=info @timestamp=2025-10-14T08:57:32.002Z log.logger=modules log.origin={"function":"github.com/elastic/beats/v7/filebeat/fileset.newModuleRegistry","file.name":"fileset/modules.go","file.line":135} service.name=filebeat ecs.version=1.6.0

Enabled modules/filesets: kibana (log), kibana (audit) | log.level=info @timestamp=2025-10-14T08:57:32.003Z log.logger=modules log.origin={"function":"github.com/elastic/beats/v7/filebeat/fileset.newModuleRegistry","file.name":"fileset/modules.go","file.line":135} service.name=filebeat ecs.version=1.6.0

Enabled modules/filesets: elasticsearch (gc), elasticsearch (server), elasticsearch (slowlog), elasticsearch (audit), elasticsearch (deprecation) | log.level=info @timestamp=2025-10-14T08:57:32.998Z log.logger=modules log.origin={"function":"github.com/elastic/beats/v7/filebeat/fileset.newModuleRegistry","file.name":"fileset/modules.go","file.line":135} service.name=filebeat ecs.version=1.6.0
```

For the 3 modules I have an error as they have multiple fileset:

```
filestream input ID 'b8b0bf8ca375d0d34f2913cbaa0a1a52ae063706ea55835094337361fb7e3ab2' is duplicated: input will NOT start | log.level=error @timestamp=2025-10-14T08:57:33.000Z log.logger=input log.origin={"function":"github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*InputManager).Create","file.name":"input-logfile/manager.go","file.line":193} service.name=filebeat input.cfg={
  "_fileset_name": "server",
  "_module_name": "elasticsearch",
  "exclude_files": [
    ".gz$",
    "_slowlog.log$",
    "_access.log$",
    "_deprecation.log$",
    "gc.log$",
    "_audit.log$"
  ],
  "id": "b8b0bf8ca375d0d34f2913cbaa0a1a52ae063706ea55835094337361fb7e3ab2",
  "multiline": {
    "match": "after",
    "negate": true,
    "pattern": "^(\\[[0-9]{4}-[0-9]{2}-[0-9]{2}|{)"
  },
  "parsers": [
    {
      "container": {
        "format": "auto",
        "stream": "all"
      }
    }
  ],
  "path": {
    "config": "/usr/share/filebeat",
    "data": "/usr/share/filebeat/data",
    "home": "/usr/share/filebeat",
    "logs": "/usr/share/filebeat/logs"
  },
  "paths": [
    "/var/lib/docker/containers/b8b0bf8ca375d0d34f2913cbaa0a1a52ae063706ea55835094337361fb7e3ab2/*.log"
  ],
  "pipeline": "filebeat-9.1.5-elasticsearch-server-pipeline",
  "processors": [
    {
      "add_locale": {
        "when": {
          "not": {
            "regexp": {
              "message": "^{"
            }
          }
        }
      }
    },
    {
      "add_fields": {
        "fields": {
          "ecs": {
            "version": "1.12.0"
          }
        },
        "target": ""
      }
    }
  ],
  "type": "filestream"
} ecs.version=1.6.0

Error creating runner from config: failed to create input: ErrNonReloadable: filestream input with ID 'b8b0bf8ca375d0d34f2913cbaa0a1a52ae063706ea55835094337361fb7e3ab2' already exists, this will lead to data duplication, please use a different ID | log.level=error @timestamp=2025-10-14T08:57:33.000Z log.logger=autodiscover.autodiscover.cfgfile log.origin={"function":"github.com/elastic/beats/v7/libbeat/cfgfile.(*RunnerList).Reload","file.name":"cfgfile/list.go","file.line":136} service.name=filebeat ecs.version=1.6.0

Enabled modules/filesets: logstash (log), logstash (slowlog) | log.level=info @timestamp=2025-10-14T08:57:33.001Z log.logger=modules log.origin={"function":"github.com/elastic/beats/v7/filebeat/fileset.newModuleRegistry","file.name":"fileset/modules.go","file.line":135} service.name=filebeat ecs.version=1.6.0

filestream input ID '99b490f9d3b69b97f2c2bdea8aafbaef035a32154f561d43c3c6edb6aae69f6a' is duplicated: input will NOT start | log.level=error @timestamp=2025-10-14T08:57:33.001Z log.logger=input log.origin={"function":"github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*InputManager).Create","file.name":"input-logfile/manager.go","file.line":193} service.name=filebeat input.cfg={
  "_fileset_name": "slowlog",
  "_module_name": "logstash",
  "exclude_files": [
    ".gz$"
  ],
  "id": "99b490f9d3b69b97f2c2bdea8aafbaef035a32154f561d43c3c6edb6aae69f6a",
  "parsers": [
    {
      "container": {
        "format": "auto",
        "stream": "all"
      }
    }
  ],
  "path": {
    "config": "/usr/share/filebeat",
    "data": "/usr/share/filebeat/data",
    "home": "/usr/share/filebeat",
    "logs": "/usr/share/filebeat/logs"
  },
  "paths": [
    "/var/lib/docker/containers/99b490f9d3b69b97f2c2bdea8aafbaef035a32154f561d43c3c6edb6aae69f6a/*.log"
  ],
  "pipeline": "filebeat-9.1.5-logstash-slowlog-pipeline",
  "processors": [
    {
      "add_locale": {
        "when": {
          "not": {
            "regexp": {
              "message": "^{"
            }
          }
        }
      }
    },
    {
      "add_fields": {
        "fields": {
          "ecs": {
            "version": "1.12.0"
          }
        },
        "target": ""
      }
    }
  ],
  "type": "filestream"
} ecs.version=1.6.0

Error creating runner from config: failed to create input: ErrNonReloadable: filestream input with ID '99b490f9d3b69b97f2c2bdea8aafbaef035a32154f561d43c3c6edb6aae69f6a' already exists, this will lead to data duplication, please use a different ID | log.level=error @timestamp=2025-10-14T08:57:33.001Z log.logger=autodiscover.autodiscover.cfgfile log.origin={"function":"github.com/elastic/beats/v7/libbeat/cfgfile.(*RunnerList).Reload","file.name":"cfgfile/list.go","file.line":136} service.name=filebeat ecs.version=1.6.0

Enabled modules/filesets: kibana (log), kibana (audit) | log.level=info @timestamp=2025-10-14T08:57:33.002Z log.logger=modules log.origin={"function":"github.com/elastic/beats/v7/filebeat/fileset.newModuleRegistry","file.name":"fileset/modules.go","file.line":135} service.name=filebeat ecs.version=1.6.0

filestream input ID '18e80d93d56da6f47beb03fb7a37da146d9c9220c355b4c54180b8d349888453' is duplicated: input will NOT start | log.level=error @timestamp=2025-10-14T08:57:33.002Z log.logger=input log.origin={"function":"github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*InputManager).Create","file.name":"input-logfile/manager.go","file.line":193} service.name=filebeat input.cfg={
  "_fileset_name": "audit",
  "_module_name": "kibana",
  "exclude_files": [
    ".gz$"
  ],
  "id": "18e80d93d56da6f47beb03fb7a37da146d9c9220c355b4c54180b8d349888453",
  "json": {
    "add_error_key": true,
    "keys_under_root": false
  },
  "parsers": [
    {
      "container": {
        "format": "auto",
        "stream": "all"
      }
    }
  ],
  "path": {
    "config": "/usr/share/filebeat",
    "data": "/usr/share/filebeat/data",
    "home": "/usr/share/filebeat",
    "logs": "/usr/share/filebeat/logs"
  },
  "paths": [
    "/var/lib/docker/containers/18e80d93d56da6f47beb03fb7a37da146d9c9220c355b4c54180b8d349888453/*.log"
  ],
  "pipeline": "filebeat-9.1.5-kibana-audit-pipeline",
  "processors": [
    {
      "add_locale": null
    },
    {
      "add_fields": {
        "fields": {
          "ecs": {
            "version": "1.12.0"
          }
        },
        "target": "",
        "when": {
          "and": [
            {
              "not": {
                "has_fields": [
                  "ecs.version"
                ]
              }
            },
            {
              "not": {
                "has_fields": [
                  "json.ecs.version"
                ]
              }
            }
          ]
        }
      }
    }
  ],
  "type": "filestream"
} ecs.version=1.6.0

Error creating runner from config: failed to create input: ErrNonReloadable: filestream input with ID '18e80d93d56da6f47beb03fb7a37da146d9c9220c355b4c54180b8d349888453' already exists, this will lead to data duplication, please use a different ID | log.level=error @timestamp=2025-10-14T08:57:33.002Z log.logger=autodiscover.autodiscover.cfgfile log.origin={"function":"github.com/elastic/beats/v7/libbeat/cfgfile.(*RunnerList).Reload","file.name":"cfgfile/list.go","file.line":136} service.name=filebeat ecs.version=1.6.0

all new inputs failed to start with a non-retriable error | log.level=error @timestamp=2025-10-14T08:57:33.002Z log.logger=autodiscover log.origin={"function":"github.com/elastic/beats/v7/libbeat/autodiscover.(*Autodiscover).worker","file.name":"autodiscover/autodiscover.go","file.line":176} service.name=filebeat error={"message":"Error creating runner from config: failed to create input: ErrNonReloadable: filestream input with ID 'b8b0bf8ca375d0d34f2913cbaa0a1a52ae063706ea55835094337361fb7e3ab2' already exists, this will lead to data duplication, please use a different ID\nError creating runner from config: failed to create input: ErrNonReloadable: filestream input with ID '99b490f9d3b69b97f2c2bdea8aafbaef035a32154f561d43c3c6edb6aae69f6a' already exists, this will lead to data duplication, please use a different ID\nError creating runner from config: failed to create input: ErrNonReloadable: filestream input with ID '18e80d93d56da6f47beb03fb7a37da146d9c9220c355b4c54180b8d349888453' already exists, this will lead to data duplication, please use a different ID"} ecs.version=1.6.0
```

It should definitively generate a distinct Id per Fileset of a given module.

A few ideas:
- How autodiscover manage docker:
https://github.com/elastic/elastic-agent-autodiscover/blob/main/docker/watcher.go

- How ConfigId is managed in filebeat:
https://github.com/elastic/beats/blob/9d3347c61365941e10fa49ce8dfbb7aa9b53aa51/filebeat/input/v2/compat/compat.go#L182

```go
	if tmp.ID != "" {
		// Check if this is a module configuration (& use autodiscover with docker ?)
		moduleName, _ := config.String("_module_name", -1)
		filesetName, _ := config.String("_fileset_name", -1)
  		if moduleName == "" || filesetName == "" {
    			return tmp.ID, nil
 		}
		data := containerID + ":" + moduleName + ":" + filesetName
		hash := sha256.Sum256([]byte(data))
		return fmt.Sprintf("%16X", hash[:16]), nil
	}


```

- Filebeat elasticsearch module config use log type, not filestream:
https://github.com/elastic/beats/blob/9d3347c61365941e10fa49ce8dfbb7aa9b53aa51/filebeat/module/elasticsearch/server/config/log.yml

**Comment by belimawr** [comment]
@cbeaujoin-stellar, thanks for reporting this, I'll definitely take a look at this. I believe you're facing a different issue than the OP.

It seems some modules are not playing well with autodiscover/Filestream and the enforcement of not starting inputs with duplicated IDs.

To correctly reproduce this, could you provide me your Filebeat autodiscover configuration?

**Comment by cbeaujoin** [comment]
@belimawr 

```yaml
filebeat.autodiscover:
  providers:
    - hints.default_config:
        type: filestream
        id: "${data.container.id}"
        paths:
          - /var/lib/docker/containers/${data.container.id}/*.log
      hints.enabled: true
      type: docker
```
