### ISSUE TITLE
Beats silently fails to start any input if there is an error when parsing the units sent by Elastic-Agent (emtpy `inputs` in `beat-rendered-config.yaml`)

### ISSUE THREAD

**Issue by belimawr** [elastic/beats#43118]
When running under Elastic-Agent, if at least one unit has got an invalid configuration the Beat will silently fail without starting any input or producing any error log. During policy changes, it will log the received units, however they will never be started.

One of the symptoms is an empty inputs array in the `beat-rendered-config.yaml` in the Elastic-Agent diagnostics:
```yaml
inputs: []
```

[`generateBeatConfig`](https://github.com/elastic/beats/blob/acce29cf2ece29964466a46048d5966a1e8c0662/x-pack/libbeat/management/generate.go#L277) returns an error that [`reloadInputs`](https://github.com/elastic/beats/blob/acce29cf2ece29964466a46048d5966a1e8c0662/x-pack/libbeat/management/managerV2.go#L791) correctly wraps, however it is not correctly handled by [`reload`](https://github.com/elastic/beats/blob/acce29cf2ece29964466a46048d5966a1e8c0662/x-pack/libbeat/management/managerV2.go#L579)

When `reload` receives an error from `reloadInputs`, it will check if it is a list of errors, if it is, it correctly handles them, if it is not, then no error is handled and the code proceeds as if `reloadInputs` had succeeded.
 
https://github.com/elastic/beats/blob/acce29cf2ece29964466a46048d5966a1e8c0662/x-pack/libbeat/management/managerV2.go#L683-L703

This can be easily reproduced by adding the following (invalid) input configuration to an Elastic-Agent policy:
```yaml
  - id: logfile-sample-2a176a73-63a4-448a-b208-bea77259a9ba
    name: threat_map-1
    revision: 1
    type: logfile
    use_output: default
    meta:
      package:
        name: threat_map
        version: 0.2.0
    data_stream:
      namespace: default
    package_policy_id: 2a176a73-63a4-448a-b208-bea77259a9ba
```

The Threat Map integration is currently generating this input, there is  an open issue about it: https://github.com/elastic/integrations/issues/13017
