### ISSUE TITLE
ssl.verification_mode not working on golang module

### ISSUE THREAD

**Issue by alex-spicer** [elastic/beats#4321]
- Version: 6.0.0-alpha1-SNAPSHOT
- Operating System: docker alpine
- Steps to Reproduce: enable golang module with ssl.verification_mode: none. Try to communicate via SSL to a service. Seems none is ignored and full is used failing due to self-signed!

metricbeat.yml

```

- module: golang
  metricsets: ["expvar","heap"]
  enabled: true
  period: 10s
  hosts: ["sim-service:9007"]
  heap.path: "/debug/vars"
  expvar:
    namespace: "example"
    path: "/debug/vars"

  protocol: "https"

  ssl.enabled: true
  ssl.verification_mode: none
```
