### ISSUE TITLE
[Filebeat][Entity Analytics] Add option of $expand query parameter for azure-ad provider

### ISSUE THREAD

**Issue by navnit-elastic** [elastic/beats#43324]
**Describe the enhancement:**

This is an enhancement request for the [Azure Active Directory (azure-ad)](https://www.elastic.co/docs/reference/beats/filebeat/filebeat-input-entity-analytics#provider-azure-ad) provider.
Currently, the entity analytics input type in Filebeat supports the `$select` query parameter, which allows us to extend the default properties. However, it does not provide a way to query [relationships](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#relationships) (such as `manager` or `directReports`) that are accessible through the `$expand` query parameter.
For example, There is no way to execute the below  request:
`GET https://graph.microsoft.com/v1.0/users?$expand=manager($select=id,displayName)&$select=id,displayName`

**Describe a specific use case for the enhancement or feature:**

A specific use case for this enhancement would be to retrieve user's profile information along with their manager’s details in a single query.
**Related issue:** https://github.com/elastic/integrations/issues/10321

**Comment by navnit-elastic** [comment]
Me and @brijesh-elastic have done some analysis on this and suggesting below approach to add support for `$expand` query parameter.

We need to implement `$expand` parameter for `users`, `devices` and `groups` collections to allow users query related collections in Microsoft's' graph API.

**Configuration Options**

Below are the configuration options will be added:

- **expand.users.<users_relationship>**: Provides an option to fetch [users relationships](https://learn.microsoft.com/en-us/graph/api/resources/user?view=graph-rest-1.0#relationships).
- **expand.groups.<groups_relationship>**: Provides an option to fetch [groups relationships](https://learn.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0#relationships).
- **expand.devices.<devices_relationship>**: Provides an option to fetch [devices relationships](https://learn.microsoft.com/en-us/graph/api/resources/device?view=graph-rest-1.0#relationships).

**Example Configuration**

```yml
filebeat.inputs:
- type: entity-analytics
  ...
  expand:
    users: # https://graph.microsoft.com/v1.0/users?$expand=manager($select=displayName,id),directReports($select=id)
      manager: ["displayName", "id"]
      directReports: ["id"]
    groups:
      members: ["displayName", "id"] # https://graph.microsoft.com/v1.0/groups?$expand=members($select=displayName,id)
```

**Default Relationship Properties**

Passing empty list of fields for a relationship returns a default properties of a related collection (default properties for related collections need to be finalized).
- Example: `expand.users.manager: []` returns manager collection's default properties along with users properties.

> Note: A user requesting resources should have permissions to retrieve specified related collections, if the user doesn't have sufficient permissions than the API returns an error.

**Subsequent changes to the integrations**
- There is no need to change the integration code as long as it provides an option for [`custom_options`](https://github.com/elastic/integrations/blob/main/packages/entityanalytics_entra_id/data_stream/entity/manifest.yml#L81).

We’d love to hear your thoughts! Please feel free to share any feedback or suggestions you may have.
Thanks!
