### ISSUE TITLE
HTTP task list in metricbeat/heartbeat

### ISSUE THREAD

**Issue by urso** [elastic/beats#4349]
The metricbeat http module to scrap metrics and heartbeat http monitor to check a services availability/health (e.g. by JSON response), sometimes have to cope with weird/legacy environments. E.g. in authentication token in cookie or json response, that can only be retrieved from an HTML login page.
In addition, metricbeat might be required to head to a multitude of pages after the login page, to scrap stats from these multiple sources.

Proposal: have the http module/monitor a configurable task list, e.g.

```
- type: http
  hosts: ["http://host1:80", "http://host2:8080"]
  tasks:
    - path: login
      method: POST
      parameters:
        username: <username>
        password: <pass>
    - path: stats
       method: GET
```

For the lifetime of a task-list, will the http module/monitor keep an cookie-store. This allows the login page to store the authentication in a cookie + reuse the cookie in subsequent requests without any required configurations.

In addition to cookies, one can capture a json response in a in a dictionary (`common.MapStr`), for passing more parameters (or building a json-body).

e.g.

```
tasks:
- path: login
  body.json:
    username: <username>
    password: <password>
  response.json.key: login # <- store json response with `login` key in response dictionary
- path: stats
  parameters:
    token: '%{[login.token]}'
```
