### ISSUE TITLE
Test compatibility of v3 Prometheus modules with v2 Prometheus server side

### ISSUE THREAD

**Issue by ishleenk17** [elastic/beats#43583]

**Comment by devamanv** [comment]
Tested the following scenarios so far:
- Prometeheus server with v3 and Prometheus metricset with v2 and query enabled
  The setup was as follows:
   - Prometheus server v3
   - metricbeat v2 i.e. no dependencies updated
   - Node exporter as a scrape target 

- Prometeheus server with v2 and Prometheus metricset with v3 and query enabled
  The setup was as follows:
   - Prometheus server v2
   - metricbeat v3 i.e. dependencies updated by changing the prometheus from v0.54.1 to 0.300.1
   - Node exporter as a scrape target, with the following query `rate(node_cpu_seconds_total{mode="system"}[1m])`

Used the following config for both cases:
```yaml
 - module: prometheus
   period: 10s
   hosts: ["localhost:9090"]
   metricsets: ["query"]
   queries:
    - name: "The average network traffic received, per second, over the last minute (in bytes)"
      path: "/api/v1/query"
      params:
        query: 'rate(node_network_receive_bytes_total[1m])'
```

In both cases, Metricbeat was able to fetch the metrics just fine, and didn't observe any errors or breaking changes.
Please note this is just a simple run of the scenarios, and is by no means an exhaustive set of tests. I will continue to add a few more. 
@ishleenk17 @tommyers-elastic Please suggest if you have some ideas or pointers that must be tested.
