### ISSUE TITLE
[Filestream] Take over and file identity migration can skip rotated log files

### ISSUE THREAD

**Issue by belimawr** [elastic/beats#43650]
At the moment of writing this only applies to the unreleased versions:
- 8.18 and 9.x for the file identity migration
- 9.1.x and `main` for the Take over

If a file is moved while Filebeat is offline and file identity needs to be migrated, the file will be re-ingested. 

For the take over mode, the issue is the same, but the "original" file was ingested by the log input, it got moved while Filebeat was offline and once Filebeat restarts with the Filestream take over mode, the "new" file does not have its state migrated because its path has changed.

> [!WARNING]
>  There is a similar issue that causes data re-ingestion because of the store cleanup: https://github.com/elastic/beats/issues/43649. Because the order of operations when the Filestream input is starting, the store clean up bug removes the state before the file identity migration run.

So to reproduce this bug the store clean up needs to be disabled `clean_removed: false`.

## Steps to reproduce from `main`

1. Create a log file with at least 1kb of data: `docker run -it --rm mingrammer/flog -b 1024 > /tmp/flog.log`
2. Start filebeat with the following configuration

    <details><summary>filebeat.yml</summary>
    <p>
    
    ```yaml
    filebeat.inputs:
     - type: filestream
       id: oops-I-re-ingested-a-file
       paths:
         - /tmp/*.log
       file_identity.native: ~
       clean_removed: false
    
    output.console:
      enabled: true
      pretty: true
    ```
    
    </p>
    </details> 

3. Wait until all data has been ingested
4. Stop Filebeat
5. Move `/tmp/foo.log` to `/tmp/foo-1.log`: `mv /tmp/flog.log /tmp/flog-1.log`
6. Update the configuration file (remove the `file_identity` setting as `fingerprint` is the new default for `main`)

    <details><summary>filebeat.yml</summary>
    <p>
    
    ```yaml
    filebeat.inputs:
     - type: filestream
       id: oops-I-re-ingested-a-file
       paths:
         - /tmp/*.log
       #file_identity.native: ~
       clean_removed: false
    
    output.console:
      enabled: true
      pretty: true
    ```
    
    </p>
    </details> 

8. Start Filebeat
9. The file will be fully re-ingested

## The cause

The problem comes from checking the the path in the resource metadata with the current files found by the file watcher, specifically this four lines of code:
https://github.com/elastic/beats/blob/8920a05987a2ea5703d50f92d8d0bebfe9e65e32/filebeat/input/filestream/prospector.go#L143-L146

Removing this check and relying on the file identity check should be enough to solve the problem.
