### ISSUE TITLE
TCP/UDP inputs should allow more concurrency under load

### ISSUE THREAD

**Issue by faec** [elastic/beats#43674]
The TCP/UDP inputs run a server that reads and publishes events from hosts that connect. While multiple hosts can connect at once and run in parallel, there are two factors that limit the throughput from a connected host:
- The work of publishing events is all done sequentially in the same goroutine as the network reader. This means that integrations and configurations that define processors are pausing their network connections to run them, even if the overall system load is low.
- Regardless of the number of connections, all publish calls happen through the same pipeline client. This means that there is only one set of processors for all incoming client data, and those processors can only handle one event at a time.

These factors mean that the input itself can be the bottleneck for high-throughput clients, causing dropped events even when the overall CPU load is moderate and the queue and output are keeping up fine.

The inputs should instead perform the work of publishing on a different goroutine than reading network data, and should use a pool of clients to allow processors to handle multiple events in parallel.

**Comment by defutek-tj** [comment]
@cmacknz - any update on this? This is an issue for a large customer.

**Comment by cmacknz** [comment]
Sorry, we haven't been able to prioritize this yet.

**Comment by faec** [comment]
Edited the issue to reflect that it applies to the UDP input too (this comes up e.g. with the `panw` integration which can involve very high event volume).

**Comment by adcleared** [comment]
+1
I've had to hack around udp listener limitations even where output latency is tiny, Logstash gives options which improves this but aside from tuning rx_rmem_max, there's little that can currently be done on the Filebeat side...

**Comment by nimarezainia** [comment]
@faec @cmacknz are there any workarounds that would avoid the event drops?

I do think that we need to address the lack of concurrency as described by @faec but my immediate short-term concern is around dropping the events. I fear that splitting the ingress goroutine from the publishing one, whilst promising, will allow us to handle a higher throughput but we may still hit a limit.

**Comment by cmacknz** [comment]
The way the input is implemented now cannot maximize use of the CPU of the machine it runs on. 

The only mitigation I could think of would be to run multiple agents or beats behind a load balancer to horizontally scale out. That would be the infrastructure version of what the code should be doing. I expect horizontal scaling will always achieve higher throughput even after the optimization we need to do because it parallelizes the output in addition to the input pipeline.

**Comment by nimarezainia** [comment]
Load balancer and/or a message queue have been recommended. Clearly there's a going to be a high ingress rate at which an atomic unit (in this case Filebeat)  just won't be able to handle - no matter how we change the architecture of the product (unless we insert a message bus inside the beat itself).

If this is happening over TCP, could we not tweak the window available to throttle the ingress traffic? if this is possible then we can figure out what our supported max throughput can be (we can improve on that by making some architecture changes as suggested here)  and ensure that nothing is dropped if the rate goes above this point. 

If the user wants to avoid drops, then they should move away from using UDP.

**Comment by belimawr** [comment]
After running many benchmarks, reviewing the code from my
[PR](https://github.com/elastic/beats/pull/45124) adding concurrency (specifically the version from [243c4fe60](https://github.com/belimawr/beats/tree/243c4fe60c91467ea00361f3233c1bd241ad0528)),
I make some interesting discoveries.

All those analysis were made using the TCP input.

In the latest released version of Filebeat, the bottleneck is either
the output or the input itself (reading from network), this is also
true for the concurrent version. When using the discard output, it is
clear the input itself is the bottleneck.

This becomes clear when looking at the goroutine blocking profile and
the goroutine analysis from the trace, the publishing goroutines spend
most of their time waiting for events to be read from the network.

<img width="2200" height="1929" alt="Image" src="https://github.com/user-attachments/assets/58138b53-821c-4ae3-b308-4a2c72c67822" />
<img width="3605" height="708" alt="Image" src="https://github.com/user-attachments/assets/b3b0dfac-84c7-4ad3-a4c9-c0a1142ec4a6" />

Once a really slow processor is added, then the gains of having the
processors (which are part of the publish call) in different
goroutines and scaling them becomes clearly noticeable.

To simulate this scenario I used the script processor calculating
Fibonacci recursively:

```yaml
      - script:
          lang: javascript
          source: >
            function fib(n) {
              if (n < 2) {
                return n;
              }
              else {
                return fib(n - 1) + fib(n - 2);
              }
            }
            function process(event) {
              event.Put("test", fib(16))
            }
```

Those are the goroutine blocking profile and
the goroutine analysis from the trace with the slow
script processor:

<img width="3020" height="1837" alt="Image" src="https://github.com/user-attachments/assets/9e4535b5-a817-495a-89ef-0c8555f70073" />
<img width="3399" height="712" alt="Image" src="https://github.com/user-attachments/assets/e20439b1-fc5b-49ac-a3eb-5741a498a99b" />

With the slow script processor, we can see a clear gain in performance
when using multiple goroutines to run the publish call.

## Benchmark results

**Suit name**
 - `Single goroutine` is the latest released version. It does not support any concurrency on the input
 - `Concurrent version` is my [PR](https://github.com/belimawr/beats/tree/243c4fe60c91467ea00361f3233c1bd241ad0528)'s version

**Benchmark name:** Is auto generated by bench builder, the only variation is the number of workers. `0` means the latest release (v9.1.0`) that ignores the workers setting.

All versions/benchmarks were run with the same configuration, the only variation is the number of workers.

Configurations used

<details><summary>filebeat.yml with syslog processor</summary>
<p>

```yaml
filebeat:
    inputs:
        - data_stream:
            dataset: tcp.generic
          host: localhost:4044
          id: tcp-1-workers
          index: logs-tcp.generic-default
          number_of_workers: 1 # That's the only effective change among benchmarks/versions
          processors:
            - add_fields:
                fields:
                    input_id: tcp-1-workers-preset-throughput
                target: '@metadata'
            - add_fields:
                fields:
                    dataset: tcp.generic
                    namespace: default
                    type: logs
                target: data_stream
            - add_fields:
                fields:
                    dataset: tcp.generic
                target: event
            - add_fields:
                fields:
                    stream_id: tcp-tcp.generic
                target: '@metadata'
            - add_fields:
                fields:
                    id: b51bc1c7-2d5c-4526-b9bf-616de0dc5a63
                    snapshot: false
                    version: 9.2.0
                target: elastic_agent
            - add_fields:
                fields:
                    id: b51bc1c7-2d5c-4526-b9bf-616de0dc5a63
                target: agent
            - syslog:
                field: message
                tag: syslog
          type: tcp
http.enabled: true
http.host: localhost
http.pprof.enabled: true
logging.info: info
logging.to_files: false
logging.to_stderr: true
name: 1-workers-preset-throughput
output:
    discard:
        enabled: true
```

</p>
</details> 

<details><summary>filebeat.yml with script processor</summary>
<p>

```yaml
filebeat:
    inputs:
        - data_stream:
            dataset: tcp.generic
          host: localhost:4044
          id: tcp-1-workers
          index: logs-tcp.generic-default
          number_of_workers: 1 # That's the only effective change among benchmarks/versions
          processors:
            - add_fields:
                fields:
                    input_id: tcp-1-workers-preset-throughput
                target: '@metadata'
            - add_fields:
                fields:
                    dataset: tcp.generic
                    namespace: default
                    type: logs
                target: data_stream
            - add_fields:
                fields:
                    dataset: tcp.generic
                target: event
            - add_fields:
                fields:
                    stream_id: tcp-tcp.generic
                target: '@metadata'
            - add_fields:
                fields:
                    id: b51bc1c7-2d5c-4526-b9bf-616de0dc5a63
                    snapshot: false
                    version: 9.2.0
                target: elastic_agent
            - add_fields:
                fields:
                    id: b51bc1c7-2d5c-4526-b9bf-616de0dc5a63
                target: agent
            - script:
                lang: javascript
                source: |
                    function fib(n) {
                      if (n < 2) {
                        return n;
                      }
                      else {
                        return fib(n - 1) + fib(n - 2);
                      }
                    } function process(event) {
                      event.Put("test", fib(16))
                    }
          type: tcp
http.enabled: true
http.host: localhost
http.pprof.enabled: true
logging.info: info
logging.to_files: false
logging.to_stderr: true
name: 1-workers-preset-throughput
output:
    discard:
        enabled: true
```

</p>
</details> 

```
+--------------------------------------+--------------------+------------------------------+---------+-----------------+-------------+
| RACE ID                              | SUITE NAME         | BENCHMARK NAME               | VERSION | DURATION (SEC)  | EPS         |
+--------------------------------------+--------------------+------------------------------+---------+-----------------+-------------+
| d08273a1-e4de-42a8-9717-b055e25c3372 | Single goroutine   | 0-workers-throughput         | 9.1.0   | 3m8.261661079s  | 2656.000000 |
| ebb5e053-4ba0-4afd-8cda-4291c3c4aace | Concurrent version | 1-workers-preset-throughput  | 9.2.0   | 3m11.264531666s | 2614.000000 |
| baaf7f03-237d-4101-b395-4eb2f6aaa884 | Concurrent version | 4-workers-preset-throughput  | 9.2.0   | 1m14.192704498s | 6739.000000 |
| 6b9db306-284c-49c3-a040-af8c0b2e3377 | Concurrent version | 8-workers-preset-throughput  | 9.2.0   | 56.044595021s   | 8921.000000 |
| c2f98bb5-d480-4f3b-8913-6b42104cf76e | Concurrent version | 16-workers-preset-throughput | 9.2.0   | 59.140696792s   | 8454.000000 |
+--------------------------------------+--------------------+------------------------------+---------+-----------------+-------------+
```

The time benchbuilder took to write the events to the network
connection, for each run is:

```
[d08273a1::filebeat::0-workers-throughput]         - 2025/07/29 11:28:19 Streamer completed sending events 500000 took 3m7.460732778s with avg speed 2667.225251
[ebb5e053::filebeat::1-workers-preset-throughput]  - 2025/07/29 11:31:53 Streamer completed sending events 500000 took 3m10.59331749s with avg speed 2623.386835
[baaf7f03::filebeat::4-workers-preset-throughput]  - 2025/07/29 11:33:30 Streamer completed sending events 500000 took 1m13.845074415s with avg speed 6770.932306
[6b9db306::filebeat::8-workers-preset-throughput]  - 2025/07/29 11:34:44 Streamer completed sending events 500000 took 51.243569948s with avg speed 9757.321758
[c2f98bb5::filebeat::16-workers-preset-throughput] - 2025/07/29 11:36:09 Streamer completed sending events 500000 took 56.685431643s with avg speed 8820.608497
```

The dataset was generated using [`flog`](https://github.com/mingrammer/flog), the format is `rfc5424`,
each entry is about 2.5kb, the test file contains 500 000 entries and
12Gb of data.
