### ISSUE TITLE
Use file path instead of inode as identifier in the registry

### ISSUE THREAD

**Issue by pvledoux** [elastic/beats#4368]
Referencing the following issue:
https://discuss.elastic.co/t/some-lines-sent-to-logstash-are-truncated/79900/12

It will be great if we could use the file path instead of the inode in the registry for files that are not updated or renamed.
This could be configured per prospector like so:

```
filebeat:
  prospectors:

      - paths:
          - /var/data/logs/*.log
        document_type: log
        registry_identifier: path
```
It would be particularly useful when you import lot of old logs and delete the files immediately when filebeat as finished.
