### ISSUE TITLE
[azure monitor] wildcard metric names (`metrics: [*]`) issues

### ISSUE THREAD

**Issue by zmoog** [elastic/beats#43885]
At least one user reported issue while collecting metrics with the Azure Monitor metricset when the config includes `metrics: [*]` and no timegrain.

For example, a user reported the following config as non working:

```yaml
# ❌
- module: azure  
  metricsets:  
    - monitor  
  enabled: true  
  period: 60s  
  client_id: '${AZURE_CLIENT_ID:""}'
  client_secret: '${AZURE_CLIENT_SECRET:""}'
  tenant_id: '${AZURE_TENANT_ID:""}'
  subscription_id: '${AZURE_SUBSCRIPTION_ID:""}'
  refresh_list_interval: 600s  
  resources:  
  - resource_query: "resourceType eq 'Microsoft.DBforPostgreSQL/flexibleServers'"
    metrics:  
    - name: ["*"]
      namespace: "Microsoft.DBforPostgreSQL/flexibleServers"
```

Instead, when they used the following config with explicit metric names, it worked:

```yaml
# ✅
- module: azure  
  metricsets:  
    - monitor  
  enabled: true  
  period: 60s  
  client_id: '${AZURE_CLIENT_ID:""}'
  client_secret: '${AZURE_CLIENT_SECRET:""}'
  tenant_id: '${AZURE_TENANT_ID:""}'
  subscription_id: '${AZURE_SUBSCRIPTION_ID:""}'
  refresh_list_interval: 600s  
  resources:  
  - resource_query: "resourceType eq 'Microsoft.DBforPostgreSQL/flexibleServers'"
    metrics:  
    - name: ["is_db_alive","active_connections","maximum_used_transactionIDs","connections_succeeded","cpu_percent","deadlocks","iops","memory_percent","read_throughput","storage_percent"]
      namespace: "Microsoft.DBforPostgreSQL/flexibleServers"
```

**Comment by zmoog** [comment]
## Situation

With metrics config like the following:

```yaml
  resources:  
  - resource_query: "resourceType eq 'Microsoft.DBforPostgreSQL/flexibleServers'"
    metrics:  
    - name: ["*"]
      namespace: "Microsoft.DBforPostgreSQL/flexibleServers"
```

The timegrain in the first collection is empty — currently, it comes from the metrics config in the YAML:

![Image](https://github.com/user-attachments/assets/01947d79-ef0e-452e-a5bc-c46252221d57)

After the metricset gets the first result from the API response, the metricset stores the default timegrain Azure applies when for an empty timegrain in the API request.

https://github.com/elastic/beats/blob/3af6b7ce13ca470e910da15f2188a4eec1ea306f/x-pack/metricbeat/module/azure/client.go#L284-L286

If all the metrics have the same timegrain—as the metric names in the following snippet—then the API request succeedes:

```yaml
  resources:  
  - resource_query: "resourceType eq 'Microsoft.DBforPostgreSQL/flexibleServers'"
    metrics:  
    - name: ["is_db_alive","active_connections","maximum_used_transactionIDs","connections_succeeded","cpu_percent","deadlocks","iops","memory_percent","read_throughput","storage_percent"]
      namespace: "Microsoft.DBforPostgreSQL/flexibleServers"
```

## Problem

However, by using `metrics.name: [*]` there is a high chance to select metric names with incompatible timegrain, causing failures in the API requests.

## Solution

- [ ] Try to provide a default timegrain using the metric definition to avoid using empty timegrain.

### provide default timegrain

For example, at line 76 we should pick a default time grain when there isn't one in the metric config:

https://github.com/elastic/beats/blob/3af6b7ce13ca470e910da15f2188a4eec1ea306f/x-pack/metricbeat/module/azure/monitor/client_helper.go#L71-L77
