### ISSUE TITLE
[beats receivers] Eliminate the need for the otelconsumer output and queue

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#44105]
This is a follow up from https://github.com/elastic/beats/pull/44009#issuecomment-2835352895 which identifies that we need more concurrent uses of the ConsumeLogs() function in the existing otelconsumer output.

A valid collector configuration today looks like and includes an `output` key that creates an instance of the [otelconsumer output](https://github.com/elastic/beats/blob/647c299bbbf65356e87c9a90942c6200ef59698e/libbeat/outputs/otelconsumer/otelconsumer.go#L87) and requires the entire Beat pipeline including the queue to be duplicated inside the receiver.

```yaml
  filebeatreceiver:
    filebeat:
      inputs:
        - type: benchmark
          enabled: true
          count: 1
          message: {{.Message}}
    output:
      otelconsumer:
    logging:
      level: info
      selectors:
        - '*'
    path.home: /tmp
exporters:
  file/no_rotation:
    path: /tmp/output
service:
  pipelines:
    logs:
      receivers: [filebeatreceiver]
      exporters: [file/no_rotation]
```

Evaluate if the otelconsumer output and the Beat internal queue can be removed. The largest impact is expected to be on the flow of acknowledgements through the Beat which need to remain correct after this change. The format conversions done by the otelconsumer output will need to remain in the Beat, perhaps as part of the pipeline [publish client](https://github.com/elastic/beats/blob/647c299bbbf65356e87c9a90942c6200ef59698e/libbeat/publisher/pipeline/client.go#L118-L123).
