### ISSUE TITLE
Filebeat: panic: name processing_time already used

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#44230]
This was detected in the ECK integration tests and initially reported internally.

```
panic: name processing_time already used

goroutine 1330 [running]:
github.com/elastic/elastic-agent-libs/monitoring.panicErr(...)
	github.com/elastic/elastic-agent-libs@v0.19.1/monitoring/registry.go:257
github.com/elastic/elastic-agent-libs/monitoring.(*Registry).Add(0xc002623240, {0x5586601e40dc?, 0x1?}, {0x558661e94f60, 0xc001be5180}, 0xdc?)
	github.com/elastic/elastic-agent-libs@v0.19.1/monitoring/registry.go:155 +0xca
github.com/elastic/elastic-agent-libs/monitoring.(*Registry).NewRegistry(0xc002623240, {0x5586601e40dc, 0xf}, {0xc0021837d8?, 0x1?, 0x1?})
	github.com/elastic/elastic-agent-libs@v0.19.1/monitoring/registry.go:94 +0x155
github.com/elastic/elastic-agent-libs/monitoring/adapter.NewGoMetrics(0xc002183820?, {0x5586601e40dc?, 0xa?}, {0xc002183920, 0x1, 0x1})
	github.com/elastic/elastic-agent-libs@v0.19.1/monitoring/adapter/go-metrics.go:70 +0x45
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.NewMetrics(0xc002623240)
	github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile/metrics.go:72 +0x425
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*managedInput).Run(_, {0xc002569670, {0xc0020507e0, 0x83}, {0xc0020507e0, 0x83}, {0x5586601cb50d, 0xa}, {{0x5586601c3537, 0x8}, ...}, ...}, ...)
	github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile/input.go:67 +0x1ae
github.com/elastic/beats/v7/filebeat/input/v2/compat.(*runner).Start.func1()
	github.com/elastic/beats/v7/filebeat/input/v2/compat/compat.go:164 +0x523
created by github.com/elastic/beats/v7/filebeat/input/v2/compat.(*runner).Start in goroutine 181
	github.com/elastic/beats/v7/filebeat/input/v2/compat/compat.go:135 +0xb9
panic: name processing_time already used

goroutine 1280 [running]:
github.com/elastic/elastic-agent-libs/monitoring.panicErr(...)
	github.com/elastic/elastic-agent-libs@v0.19.1/monitoring/registry.go:257
github.com/elastic/elastic-agent-libs/monitoring.(*Registry).Add(0xc002623240, {0x5586601e40dc?, 0x1?}, {0x558661e94f60, 0xc0026232c0}, 0xdc?)
	github.com/elastic/elastic-agent-libs@v0.19.1/monitoring/registry.go:155 +0xca
github.com/elastic/elastic-agent-libs/monitoring.(*Registry).NewRegistry(0xc002623240, {0x5586601e40dc, 0xf}, {0xc00232d7d8?, 0x1?, 0x1?})
	github.com/elastic/elastic-agent-libs@v0.19.1/monitoring/registry.go:94 +0x155
github.com/elastic/elastic-agent-libs/monitoring/adapter.NewGoMetrics(0xc00232d820?, {0x5586601e40dc?, 0xa?}, {0xc00232d920, 0x1, 0x1})
	github.com/elastic/elastic-agent-libs@v0.19.1/monitoring/adapter/go-metrics.go:70 +0x45
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.NewMetrics(0xc002623240)
	github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile/metrics.go:72 +0x425
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*managedInput).Run(_, {0xc0025564e0, {0xc002050240, 0x83}, {0xc002050240, 0x83}, {0x5586601cb50d, 0xa}, {{0x5586601c3537, 0x8}, ...}, ...}, ...)
	github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile/input.go:67 +0x1ae
github.com/elastic/beats/v7/filebeat/input/v2/compat.(*runner).Start.func1()
	github.com/elastic/beats/v7/filebeat/input/v2/compat/compat.go:164 +0x523
created by github.com/elastic/beats/v7/filebeat/input/v2/compat.(*runner).Start in goroutine 181
	github.com/elastic/beats/v7/filebeat/input/v2/compat/compat.go:135 +0xb9
panic: name processing_time already used

goroutine 1281 [running]:
github.com/elastic/elastic-agent-libs/monitoring.panicErr(...)
	github.com/elastic/elastic-agent-libs@v0.19.1/monitoring/registry.go:257
github.com/elastic/elastic-agent-libs/monitoring.(*Registry).Add(0xc002623240, {0x5586601e40dc?, 0x1?}, {0x558661e94f60, 0xc000273d00}, 0xdc?)
	github.com/elastic/elastic-agent-libs@v0.19.1/monitoring/registry.go:155 +0xca
github.com/elastic/elastic-agent-libs/monitoring.(*Registry).NewRegistry(0xc002623240, {0x5586601e40dc, 0xf}, {0xc00220f7d8?, 0x1?, 0x1?})
	github.com/elastic/elastic-agent-libs@v0.19.1/monitoring/registry.go:94 +0x155
github.com/elastic/elastic-agent-libs/monitoring/adapter.NewGoMetrics(0xc00220f820?, {0x5586601e40dc?, 0xa?}, {0xc00220f920, 0x1, 0x1})
	github.com/elastic/elastic-agent-libs@v0.19.1/monitoring/adapter/go-metrics.go:70 +0x45
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.NewMetrics(0xc002623240)
	github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile/metrics.go:72 +0x425
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.(*managedInput).Run(_, {0xc002557d70, {0xc002050510, 0x83}, {0xc002050510, 0x83}, {0x5586601cb50d, 0xa}, {{0x5586601c3537, 0x8}, ...}, ...}, ...)
	github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile/input.go:67 +0x1ae
github.com/elastic/beats/v7/filebeat/input/v2/compat.(*runner).Start.func1()
	github.com/elastic/beats/v7/filebeat/input/v2/compat/compat.go:164 +0x523
created by github.com/elastic/beats/v7/filebeat/input/v2/compat.(*runner).Start in goroutine 181
	github.com/elastic/beats/v7/filebeat/input/v2/compat/compat.go:135 +0xb9
==== END logs for e2e-tigiq-mercury/test-fb-default-cfg-xr8c-beat-filebeat-fldw8 ====
```

**Comment by cmacknz** [comment]
Adding the configuration that can be used to reproduce this from the ECK integration tests:

```yaml
name: configref-test-agent
filebeat:
  autodiscover:
    providers:
    - hints:
        default_config:
          paths:
          - /var/log/containers/*${data.kubernetes.container.id}.log
          type: filestream
          id: kubernetes-container-logs-${data.kubernetes.pod.name}-${data.kubernetes.container.id}
          parsers:
          - container: ~
          prospector:
            scanner:
              fingerprint.enabled: true
              symlinks: true
          file_identity.fingerprint: ~
        enabled: true
      host: ${NODE_NAME}
      type: kubernetes
processors:
- add_cloud_metadata: {}
- add_host_metadata: {}
```
