### ISSUE TITLE
[bug] Number of filebeat inputs enabled is incorrectly logged

### ISSUE THREAD

**Issue by khushijain21** [elastic/beats#44287]
Steps to reproduce

1. Start agent with 
```
agent.grpc:
  port: 6794
inputs:
   - type: filestream
     id: your-input-id
     streams:
       - id: your-filestream-stream-id
         data_stream:
           dataset: generic
         paths:
           - /var/log/*.log    
outputs:
  default:
    type: elasticsearch
    hosts: ["XXX"]
    preset: "balanced"
    username: "elastic"
    password: "XXX"
agent.monitoring:
   enabled: false
```

Even when filestream input is enabled, the logs show "Enabled Inputs: 0". 

```json
{"log.level":"info",
"@timestamp":"2025-05-08T12:21:41.959+0530",
"message":"Loading Inputs: 0",
"component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-default","type":"filestream"},
"log":{"source":"filestream-default"},
"ecs.version":"1.6.0","log.logger":"crawler","log.origin":{"file.line":72,"file.name":"beater/crawler.go","function":"github.com/elastic/beats/v7/filebeat/beater.(*crawler).Start"},"service.name":"filebeat","ecs.version":"1.6.0"}


{"log.level":"info",
"@timestamp":"2025-05-08T12:21:41.959+0530",
"message":"Loading and starting Inputs completed. Enabled inputs: 0",
"component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-default","type":"filestream"},"log":{"source":"filestream-default"},
"log.origin":{"file.line":107,"file.name":"beater/crawler.go","function":"github.com/elastic/beats/v7/filebeat/beater.(*crawler).Start"},"service.name":"filebeat","ecs.version":"1.6.0","log.logger":"crawler","ecs.version":"1.6.0"}
```

Reason:

This is because filebeat [crawler](https://github.com/elastic/beats/blob/main/filebeat/beater/crawler.go#L72) (in managed mode) is started with an empty config first.
