### ISSUE TITLE
Add documentation for HTTP Basic Auth in Metricbeat Modules

### ISSUE THREAD

**Issue by xeraa** [elastic/beats#4457]
For example in the JMX module basic auth is supported with `username` and `password`, but it's not included in the documentation or examples:

```
- module: jolokia
  metricsets: ["jmx"]
  hosts: ["localhost:8080"]
  username: admin
  password: secret
  namespace: "metrics"
  jmx.mappings:
    ...
```
