### ISSUE TITLE
[Beat receivers] x-pack metricbeat modules cannot be found

### ISSUE THREAD

**Issue by cmacknz** [elastic/beats#44698]
The following collector configuration fails to find any metricsets:

```yaml
receivers:
  metricbeatreceiver:
    metricbeat:
      modules:
        - module: autoops_es
          hosts: ["http://localhost:9200/"]
          period: 10s
          metricsets:
            - license
            - node_stats
            - cat_shards
            - cluster_settings
            - cluster_health
            - tasks_management
    output:
      otelconsumer:
    logging:
      level: info
    telemetry_types: ["logs"]

exporters:
  otlp:
    headers:
      Authorization: "AutoOpsToken ${env:TOKEN}"
    endpoint: localhost:4317  # Use DNS name, IP, or service name if in Kubernetes
    tls:
      insecure: true          # Disable TLS for internal networks (or use certs if needed)

service:
  pipelines:
    logs:
      receivers: [metricbeatreceiver]
      exporters: [otlp]
  telemetry:
    metrics:
      readers:
        - pull:
            exporter:
              prometheus:
                host: localhost
                port: 9999
```

This fails with an error:

```
failed to build pipelines: failed to create "metricbeatreceiver" receiver for data type "logs": error creating metricbeatreceiver: error getting metricbeat creator:metricset 'autoops_es/license' not found
metricset 'autoops_es/node_stats' not found
metricset 'autoops_es/cat_shards' not found
metricset 'autoops_es/cluster_settings' not found
metricset 'autoops_es/cluster_health' not found
metricset 'autoops_es/tasks_management' not found
```
