### ISSUE TITLE
Enable filebeat prospector default options

### ISSUE THREAD

**Issue by lagrianitis** [elastic/beats#4489]
- Beat: Filebeat
- Version: 5.4.1
- Operating System: Centos 6
Hello!
I have several filebeat (5.4.1) prospectors and I want to use the same options depending the environment my beats will run (DTAP).
Is it possible to set the options as defaults for all prospectors and then overwrite them under prospector?
Example...
I currently have: 

```
filebeat:
    prospectors:
        -
          paths:
            - "/var/log/nginx/*access*log"
          exclude_files: ['.gz$', '.xz$']
          tail_files: true
          close_inactive: 1m
          close_removed: true
          ignore_older: 60m
          clean_inactive: 61m
          clean_removed: true
          scan_frequency: 10s
          input_type: log
          document_type: nginx_access
          tags: ["nginx", "access_log", "plain"]
        -
          paths:
            - "/var/log/nginx/*error*log"
          exclude_files: ['.gz$', '.xz$']
          tail_files: true
          close_inactive: 1m
          close_removed: true
          ignore_older: 60m
          clean_inactive: 61m
          clean_removed: true
          scan_frequency: 10s
          input_type: log
          document_type: nginx_error
          tags: ["nginx", "error_log", "plain"]
```

What I'd like to implement is something like:

```
filebeat:
   prospectors:
       defaults:
            exclude_files: ['.gz$', '.xz$']
            tail_files: true
            close_inactive: 1m 
            close_removed: true
            ignore_older: 60m
            clean_inactive: 61m
            clean_removed: true
            scan_frequency: 10s
            input_type: log
      -
            paths:
                - "/var/log/nginx/*access*log"
            exclude_files: ['.swp$']
            tail_files: false
            document_type: nginx_access
            tags: ["nginx", "access_log", "plain"]
      -
            paths:
                - "/var/log/nginx/*error*log"
            document_type: nginx_error
            scan_frequency: 5s
            tags: ["nginx", "error_log", "plain"]
```
As you can see in my current configuration I have to maintain the same options in all prospectors.
