### ISSUE TITLE
Filebeat can`t use multiline

### ISSUE THREAD

**Issue by damingupup** [elastic/beats#44954]
filebeat version:9.0.2
filebeat config:
```
logging:
  level: debug
  to_files: true
  files:
    path: /tmp/filebeat
    name: filebeat-debug.log
  selectors: ["*"]  
filebeat.inputs:
- type: filestream
  id: db_servers
  paths:
    - /var/log/test02/*.log
  fields:
    log_source: "test02"
  multiline:
    pattern: '^May 27 16:08:54 mx22-test-74-53 qa_53-logic1\[587\]: \[m22\]'
    negate: true
    match: after
    skip_newline: true
output.logstash:
  hosts: ["graylog:5044"]  
```
test log :
`May 27 16:08:54 mx22-test-74-53 qa_53-logic1[587]: [m22][484912][2025-05-27 16:08:54,744][logicSrv.20501][INFO]: server patch or code  index=-1
May 27 16:08:54 mx22-test-74-53 qa_53-logic1[587]: hello world
May 27 16:08:54 mx22-test-74-53 qa_53-logic1[587]: [m22][484912][2025-05-27 16:08:54,744][logicSrv.20501][INFO]: server patch or code  index=-12`
filebeat log:
`{"log.level":"debug","@timestamp":"2025-06-21T17:47:45.234Z","log.logger":"logstash","log.origin":{"function":"github.com/elastic/beats/v7/libbeat/outputs/logstash.(*asyncClient).Publish","file.name":"logstash/async.go","file.line":174},"message":"3 events out of 3 events sent to logstash host graylog:5044. Continue sending","service.name":"filebeat","ecs.version":"1.6.0"}
`
I can`t find any log about multiline,but filebeat has successfully sent three separate logs to graylog

![Image](https://github.com/user-attachments/assets/b813c4d4-a88b-4bb0-a40a-f3d77df44034)
Team:Filebeat
