### ISSUE TITLE
[OTel] Unset / blank environment variables are misinterpreted as objects

### ISSUE THREAD

**Issue by pickypg** [elastic/beats#45102]
When trying to create a configuration that can be overridden with environment variables, I ran into an issue where the `OTel` `envprovider` is breaking the configuration for unset or blank environment variables that are strings.

<details>
<summary>Example otel config (`es.yml`)</summary>

```yml
receivers:
  metricbeatreceiver:
    metricbeat:
      modules:
        - module: elasticsearch
          hosts: "http://localhost:9200"
          # Auth should only specify either API Key or Username/Password
          # api_key: ${env:MY_ES_API_KEY:-}
          username: ${env:MY_ES_USERNAME:-}
          password: ${env:MY_ES_PASSWORD:-}
          period: 10s
          metricsets:
            - node_stats
    output:
      otelconsumer:
    telemetry_types: ["logs"]

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 1

service:
  pipelines:
    logs:
      receivers: [metricbeatreceiver]
      exporters: [debug]
```
</details>

```
./elastic-agent otel --config es.yml
```

This also fails for the same reason if you set the variables to blank:

```
MY_ES_USERNAME="" MY_ES_PASSWORD="" ./elastic-agent otel --config es.yml
```

Both cases will result in failure that looks like:

> failed to build pipelines: failed to create "metricbeatreceiver" receiver for data type "logs": error creating metricbeatreceiver: error getting metricbeat creator:host parsing failed for elasticsearch-node_stats: 'username' config for module elasticsearch is not a string

This starts successfully if you set them to any value (auth will only succeed if you set it to a valid value of course):

```
MY_ES_USERNAME=x MY_ES_PASSWORD=x ./elastic-agent otel --config es.yml
```

This does not fail because of some weird parsing issue -- instead, the blank variety of values are being provided to the underlying config objects as a struct defined in OTel that looks like a `map` (I forced the Beat to print the value):

```
map[original: value:<nil>]
```

While unclear at first, the `original` field's value is the blank string `""`. This "map" clearly comes from:

https://github.com/open-telemetry/opentelemetry-collector/blob/a33fdf3cb7547ce4c825a17d742703e65af7f053/confmap/expand.go#L177-L182

which is the eventual result of:

https://github.com/open-telemetry/opentelemetry-collector/blob/a33fdf3cb7547ce4c825a17d742703e65af7f053/confmap/provider/envprovider/provider.go#L67

This is mostly reproducable with a simple Go test as long as you have `confmap` from OTel (exists in both the Beats and Agent codebases):

```go
func TestRetrieveValue(t *testing.T) {
	expected := "" // test fails with ""
        // expected := "xyz" // test passes with "xyz"

	value, err := confmap.NewRetrievedFromYAML([]byte(expected))

	require.NoError(t, err)

	str, err := value.AsString()

	require.NoError(t, err)
	require.Equal(t, str, expected)

	conf, err := value.AsRaw()

	require.NoError(t, err)
	require.Equal(t, conf, expected) // when expected is "", conf is nil
}
```

**Comment by cmacknz** [comment]
Assuming I'm following correctly that this reproduces with just `confmap`, this should be filed upstream as a bug against https://github.com/open-telemetry/opentelemetry-collector/tree/main/confmap

**Comment by pickypg** [comment]
I can give this a shot in standard OTel and see what it does. Either way, I'll report back here.

**Comment by pickypg** [comment]
I fired up a very simple configuration that would flag this issue with the otel_contrib distro and it did **not** happen.

```
./otelcol-contrib --config otel.yml
```

```yml
# otel.yml
receivers:
  elasticsearch:
    metrics:
      elasticsearch.node.fs.disk.available:
        enabled: false
    nodes: ["_local"]
    skip_cluster_metrics: true
    endpoint: http://localhost:9200
    username: ${env:ES_USER:-}
    password: ${env:ES_PASS:-}
    collection_interval: 10s

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 1

service:
  pipelines:
    metrics:
      receivers: [elasticsearch]
      exporters: [debug]
```

It's fine whether I provide the environment variable or not. It's also fine if I remove the blank default (`${env:ES_USER}` instead of `${env:ES_USER:-}`).

So I am not sure where the handling difference appears relative to our usage, but even though we're using the same provider, I am guessing whatever populates the `component.Config` objects handles the `confmap`.
