### ISSUE TITLE
[ECK Filebeat] Harvesting with autodiscover works in 8.5.3 but not with >8.6.0

### ISSUE THREAD

**Issue by tmsdce** [elastic/beats#45156]
Hi,

Filebeat is deployed using the `Beats` CRD provided by the ECK operator. The following configuration works with version `8.5.3` but not with newer versions (>`8.6.0`)

```
filebeat:
  autodiscover:
    providers:
      - hints:
        default_config:
          enabled: false
        node: ${NODE_NAME}
        templates:
        - condition:
          or:
            - equals:
              kubernetes:
                labels:
                  my_custom_label/key: myvalue
            - equals:
              kubernetes:
                labels:
                  my_other_custom_label/key: myothervalue
          config:
          - paths:
            - /var/log/containers/*${data.kubernetes.container.id}.log
            type: container
        type: kubernetes
output:
  logstash:
    hosts:
      - myhost:5044
    ssl:
      certificate: /etc/filebeat/tls/logstash/tls.crt
      certificate_authorities:
        - /etc/filebeat/tls/logstash/ca.crt
      key: /etc/filebeat/tls/logstash/tls.key
processors:
  - add_fields:
      fields:
        host:
          name: ${NODE_NAME}
      target: ""
```

- When using version `8.5.3`, filebeat logs shows harvester started for various containers logs matched by the specified labels in template conditions:
```
{"log.level":"info","@timestamp":"2024-06-19T15:59:06.441Z","log.logger":"input.harvester","log.origin":{"file.name":"log/harvester.go","file.line":310},"message":"Harvester started for paths: [/var/log/containers/*afec2ad8cb5b6ceb0b25bf4f83cb20e8857981055b58f0c9eb257fea65eb5dc3.log]","service.name":"filebeat","input_id":"e1521747-6813-4bb5-bcaf-0788f4518a9a","source_file":"/var/log/containers/mycontainer-afec2ad8cb5b6ceb0b25bf4f83cb20e8857981055b58f0c9eb257fea65eb5dc3.log","state_id":"native::131125-2080","finished":false,"os_id":"131125-2080","harvester_id":"f2e3bbae-8093-4112-ab17-1d586df03b3e","ecs.version":"1.6.0"}
```
- When using version `8.6.0` or newer (I also tried with the latest version `8.14.1`), no harvester ever starts. The only thing I get is this kind of logs, showing no files detected for harvesting:
```
{"log.level":"info","@timestamp":"2024-06-19T16:15:16.684Z","log.logger":"monitoring","log.origin":{"file.name":"log/log.go","file.line":187},"message":"Non-zero metrics in the last 30s","service.name":"filebeat","monitoring":{"metrics":{"beat":{"cgroup":{"memory":{"mem":{"usage":{"bytes":36306944}}}},"cpu":{"system":{"ticks":30},"total":{"ticks":160,"value":160},"user":{"ticks":130}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":10},"info":{"ephemeral_id":"8f0245c4-d538-4767-ad8d-435ae999318a","uptime":{"ms":60054},"version":"8.6.0"},"memstats":{"gc_next":20095496,"memory_alloc":12040824,"memory_total":56438680,"rss":110301184},"runtime":{"goroutines":54}},"filebeat":{"events":{"active":0},"harvester":{"open_files":0,"running":0}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"active":0}},"pipeline":{"clients":0,"events":{"active":0}}},"registrar":{"states":{"current":0}},"system":{"load":{"1":0.06,"15":0.1,"5":0.1,"norm":{"1":0.01,"15":0.0167,"5":0.0167}}}},"ecs.version":"1.6.0"}}
```

It's as if the configuration was not loaded at all with >8.6.0.

Maybe I'm missing a configuration for versions >8.6.0 but I can't find which one. In the release notes between 8.5.3 and 8.6.0, I don't see a relevant change.

**Comment by belimawr** [comment]
I started looking into this and I managed to reproduce and understand the case described by @space4yyy (https://github.com/elastic/beats/issues/45156#issuecomment-3029148401).

The key thing to reproduce is to use the default configuration for hints:
```yaml
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
```

So, whenever Filebeat finds a new container it will use the default template that is hardcoded and changed from `v8.11.4` to `v8.12.0`. The change was introduced by https://github.com/elastic/beats/pull/36950.

In [`v8.11.4` it was](https://github.com/elastic/beats/blob/61337102fc51ca447027380b50596966ba88b82b/filebeat/autodiscover/builder/hints/config.go#L27-L41):
```go
func defaultConfig() config {
	defaultCfgRaw := map[string]interface{}{
		"type": "container",
		"paths": []string{
			// To be able to use this builder with CRI-O replace paths with:
			// /var/log/pods/${data.kubernetes.pod.uid}/${data.kubernetes.container.name}/*.log
			"/var/lib/docker/containers/${data.container.id}/*-json.log",
		},
	}
	defaultCfg, _ := conf.NewConfigFrom(defaultCfgRaw)
	return config{
		Key:           "logs",
		DefaultConfig: defaultCfg,
	}
}
```

And it [changed in `v8.12.0`](https://github.com/elastic/beats/blob/27c592782c25906c968a41f0a6d8b1955790c8c5/filebeat/autodiscover/builder/hints/config.go#L29-L57) to:
```go
func defaultConfig() config {
	defaultCfgRaw := map[string]interface{}{
		"type": "filestream",
		"id":   "kubernetes-container-logs-${data.kubernetes.container.id}",
		"prospector": map[string]interface{}{
			"scanner": map[string]interface{}{
				"fingerprint.enabled": true,
				"symlinks":            true,
			},
		},
		"file_identity.fingerprint": nil,
		"parsers": []interface{}{
			map[string]interface{}{
				"container": map[string]interface{}{
					"stream": "all",
					"format": "auto",
				},
			},
		},
		"paths": []string{
			"/var/log/containers/*-${data.kubernetes.container.id}.log",
		},
	}
	defaultCfg, _ := conf.NewConfigFrom(defaultCfgRaw)
	return config{
		Key:           "logs",
		DefaultConfig: defaultCfg,
	}
}
```

There are two key changes there:
- The input changed from `container` to `filestream`. On its own this does not prevent data to be ingested in the new version. However this will cause all existing files to be re-ingested because the input changed.
- The paths and id fields now use `${data.kubernetes.container.id}`, however `data.kubernetes` is only present when using Kubernetes autodiscover. This breaks rendering the template for Docker. No inputs are started, no data is ingested.

If the debug logs are enabled we can see the log:
```
{"log.level":"debug","@timestamp":"2025-08-08T16:15:11.212Z","log.logger":"autodiscover","log.origin":{"function":"github.com/elastic/beats/v7/libbeat/autodiscover/template.ApplyConfigTemplate","file.name":"template/config.go","file.line":157},"message":"Configuration template cannot be resolved: field 'data.kubernetes.container.id' not available in event or environment accessing 'paths'","service.name":"filebeat","ecs.version":"1.6.0"}
```

The core of the problem is that hints has a single default template hardcoded to all autodiscover providers.

The workaround is to define a new default template for the hints configuration that matches your provider/environment, for Docker you can use:
```yaml
filebeat.autodiscover.providers:
  - type: docker
    hints.enabled: true
    hints.default_config:
      type: filestream
      id: container-${data.container.id}
      prospector.scanner.symlinks: true
      prospector.scanner.fingerprint.enabled: true
      file_identity.fingerprint: ~
      parsers:
        - container: ~
      paths:
        - /var/lib/docker/containers/${data.container.id}/*.log
```

**Comment by belimawr** [comment]
I created a new issue focusing on the root cause, the template change: https://github.com/elastic/beats/issues/45864.

@tmsdce I'm still puzzled why you faced issues with > 8.6.0... I tested 8.5.3 and 8.6.0 and they both work.

One thing I noticed in your configuration is a indentation error in the processors part, you used:
```yaml
processors:
  - add_fields:
    fields:
      host:
        name: ${NODE_NAME}
    target: ""
```

But it should be:
```yaml
processors:
  - add_fields:
      fields:
        host:
          name: ${NODE_NAME}
      target: ""

```
