### ISSUE TITLE
Filebeat Status Fialed. Please help

### ISSUE THREAD

**Issue by manojkal** [elastic/beats#4539]
[Host1@CentOS2 filebeat]$  service filebeat status
● filebeat.service - filebeat
   Loaded: loaded (/usr/lib/systemd/system/filebeat.service; disabled; vendor preset: disabled)
   Active: failed (Result: start-limit) since Tue 2017-06-20 10:14:05 PDT; 762ms ago
     Docs: https://www.elastic.co/guide/en/beats/filebeat/current/index.html
  Process: 3742 ExecStart=/usr/share/filebeat/bin/filebeat -c /etc/filebeat/filebeat.yml -path.home /usr/share/filebeat -path.config /etc/filebeat -path.data /var/lib/filebeat -path.logs /var/log/filebeat (code=exited, status=1/FAILURE)
 Main PID: 3742 (code=exited, status=1/FAILURE)

Jun 20 10:14:04 CentOS2 systemd[1]: filebeat.service: main process exited, code=exited, status=1/FAILURE
Jun 20 10:14:04 CentOS2 systemd[1]: Unit filebeat.service entered failed state.
Jun 20 10:14:04 CentOS2 systemd[1]: filebeat.service failed.
Jun 20 10:14:05 CentOS2 systemd[1]: filebeat.service holdoff time over, scheduling restart.
Jun 20 10:14:05 CentOS2 systemd[1]: start request repeated too quickly for filebeat.service
Jun 20 10:14:05 CentOS2 systemd[1]: Failed to start filebeat.
Jun 20 10:14:05 CentOS2 systemd[1]: Unit filebeat.service entered failed state.

Filebeat.yml:
```
filebeat:

  prospectors:

    - input_type: log
      paths:
        - /var/log/*.log

registry_file: /var/lib/filebeat/registry

output.elasticsearch:
  hosts: ["10.8.20.138:80/es"]

output:
  logstash:
    hosts:
      - ["10.8.20.138:5044"]
```
