### ISSUE TITLE
Improve / fix processor condition documentation

### ISSUE THREAD

**Issue by xeraa** [elastic/beats#4548]
- Version: (Packet) Beat 5.4.2
- Operating System: Ubuntu 16.04
- Steps to Reproduce: Start the Beat with the following configuration options

I tried to add a conditional OR in the processors:

```yml
- drop_event:
  when:
    or:
      # Exclude traces from Zipkin
      - contains:
        path: "/api/v"
      # Pinging metrics
      - equals:
        path: "/metrics"
      # Pinging health
      - equals:
        path: "/health"
```
Failed with `CRIT Exiting: error initializing processors: each processor needs to have exactly one action, but found 2 actions`

```yml
- drop_event:
    when:
      or:
        # Exclude traces from Zipkin
        - contains:
          path: "/api/v"
        # Exclude pinging metrics
        - equals:
          path: "/metrics"
        # Exclude pinging health
        - equals:
          path: "/health"
```
Failed with `CRIT Exiting: error initializing processors: missing condition`

```yml
- drop_event:
    when:
      or:
        # Exclude traces from Zipkin
        - contains.path: "/api/v"
        # Exclude pinging metrics
        - equals.path: "/metrics"
        # Exclude pinging health
        - equals.path: "/health"
```
Works, but this doesn't follow the [documentation](https://www.elastic.co/guide/en/beats/packetbeat/current/configuration-processors.html#condition-or), which lists:

```yml
or:
  - equals:
      http.response.code: 304
  - equals:
      http.response.code: 404
```

**Comment by xeraa** [comment]
Turns out it's a case of bad intendation and should be 

```yml
- drop_event:
    when:
      or:
        # Exclude traces from Zipkin
        - contains:
            path: "/api/v"
        # Exclude pinging metrics
        - equals:
            path: "/metrics"
        # Exclude pinging health
        - equals:
            path: "/health"
```

Docs are correct
