### ISSUE TITLE
Filebeat has huge memory usage

### ISSUE THREAD

**Issue by aparkhomenko** [elastic/beats#4555]
Hi all.

I use Filebeat 5.3.1 and CentOS 6.9. I have some services that produce a lot logs (~50GB per day) and as I saw for huge log files Filebeat used a lot memory. For example in one instance for process one file it used 10-12 gb. I tried to understand where is the problem and do some debug:

- 2148.14MB 51.30% 51.30%  2148.14MB 51.30%  github.com/elastic/beats/libbeat/common/streambuf.(*Buffer).doAppend
- 1326.37MB 31.68% 82.98%  1326.37MB 31.68%  bytes.makeSlice
- 348.75MB  8.33% 91.31%  2843.76MB 67.92%  github.com/elastic/beats/filebeat/harvester.(*Harvester).Harvest
- 346.86MB  8.28% 99.59%  2495.01MB 59.59%  github.com/elastic/beats/filebeat/harvester/reader.(*Line).advance
         0     0% 99.59%   284.52MB  6.80%  bytes.(*Buffer).WriteByte

~346MB it was size of my example log file. As I understood from source code Filebeat do a lot copies of my data and keep it to internal buffers but the memory increase up more than x6

I tried to use more fresh version and this case still alive.

Could you please help me to understand what I'm doing wrong or maybe it's a bug? )

PS: I don't use async options.

**Comment by Amar-Chaudhari** [comment]
@aparkhomenko 
Could you post your config file ?
I have tested Filebeats with ~7000 logs/sec including filtering and multi-line matching and never the MEM > 100 MB

**Comment by aparkhomenko** [comment]
Hi @Amar-Chaudhari 

Nothing special in my config file:

filebeat.prospectors:
- input_type: log
  paths:
  - "/var/log/test.log"
filebeat.registry_file: /var/lib/filebeat/registry
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  rotateeverybytes: 10485760 # = 10MB
  keepfiles: 3

But each line in log file has big size, for example one line in that file can be near 2MB
So, unfortunately, for ~346MB file I have:

wc -l /var/log/test.log
182 /var/log/test.log

**Comment by myoung34** [comment]
Any updates? Im seeing this on boxes that dont do much (NAT) that can grow up to almost 1GB memory on 5.6.2

```
filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/messages
    - /var/log/secure
    - /var/log/cron
    - /var/log/dmesg
    - /var/log/audit/audit.log
  fields.class: "syslog"
- type: log
  enabled: true
  paths:
    - /opt/threatstack/cloudsight/logs/*.log
  exclude_files: ['tsaudit.log$']
  fields.class: "threatstack"
- type: log
  enabled: true
  paths:
    - /var/log/amazon/ssm/*.log
    - /var/log/xray/*.log
    - /var/log/boot.log
    - /var/log/cfn*.log
    - /var/log/cloud-init*.log
  fields.class: "aws"
- type: log
  enabled: true
  paths:
    - /var/log/filebeat/filebeat
  fields.class: "filebeat"
- type: log
  enabled: true
  paths:
    - /var/log/metricbeat/metricbeat
  fields.class: "metricbeat"
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.codec: best_compression
  _source.enabled: false
tags: ["nat"]
fields:
  env: "operations"
  ec2.tags.environment: "${ENVIRONMENT}"
  ec2.tags.managed_by: "${MANAGED_BY}"
  ec2.tags.name: "${NAME}"
processors:
- add_cloud_metadata:
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_PORT:9200}"]
  protocol: "https"
  username: "${ELASTICSEARCH_USER:elastic}"
  password: "${ELASTICSEARCH_PASSWORD:changeme}"
  index: "%{[fields.class]}-%{+yyyy.MM.dd}"
```

**Comment by ruflin** [comment]
Please have a look at the following FAQ about Golang: https://golang.org/doc/faq#Why_does_my_Go_process_use_so_much_virtual_memory 

Could you figure out if the value you are reporting is virtual memory or actual memory? Could you also share some logs?

**Comment by bramford** [comment]
We're also seeing very large amounts of memory usage (~1G) after running for a few days:
```
root@myhost# top -n 1 | grep filebeat
25053 root      20   0 1764956 860556      0 S   0.0 22.6  70:38.00 filebeat
```

We are using the _experimental_ docker autodiscover which I assume could be the cause:
```
filebeat.autodiscover:
  providers:
  - templates:
    - condition:
        regexp: {docker.container.image: .*}
      config:
      - container.ids: ['${data.docker.container.id}']
        type: docker
    type: docker

processors:
- add_docker_metadata:
    host: unix:///var/run/docker.sock
    match_fields: [system.process.cgroup.id]

filebeat:
  prospectors: [{"type": "docker", "containers.ids": ["*"]}]

output:
  logstash:
    hosts: ["logstash.host:5044"]

logging:
  level: info
  to_files: true
  to_syslog: true
```
