### ISSUE TITLE
loading dashboards script is looking for fields.yml in wrong dir

### ISSUE THREAD

**Issue by LeeDr** [elastic/beats#4625]
- Version: master 6.0.0-alpha3 (unified snapshot from Jul 5, 2017 12:56 PM)
- Operating System: Ubuntu
- Steps to Reproduce: 
 1. install metricbeat as a service (or any beat I think)
 2. configure for your elasticsearch cluster and kibana instance
 3. try to load the dashboards
 `/usr/share/metricbeat/bin/metricbeat setup -e -c /etc/metricbeat/metricbeat.yml`

Expected result: dashboards load
Actual result: I get the error below;

`Exiting: Error loading Elasticsearch template: error creating template from file /usr/share/metricbeat/bin/fields.yml: open /usr/share/metricbeat/bin/fields.yml: no such file or directory`

`fields.yml` isn't in `/usr/share/metricbeat/bin/`.  It's in `/etc/metricbeat/`.

I worked-around the problem by copying fields.yml from /etc/metricbeat/ to /usr/share/metricbeat/bin/

**Comment by LeeDr** [comment]
my metricbeat.yml (minus comments);
```
metricbeat.config.modules:
  path: ${path.config}/conf.d/*.yml
  reload.period: 10s
  reload.enabled: false
metricbeat.max_start_delay: 10s
metricbeat.modules:
- module: system
  metricsets:
  enabled: true
  period: 10s
  processes: ['.*']
- module: elasticsearch
  metricsets: ["node", "node_stats"]
  enabled: false
  period: 10s
  hosts: ["localhost:9200"]
- module: kibana
  metricsets: ["status"]
  enabled: false
  period: 10s
  hosts: ["localhost:5601"]
output.elasticsearch:
  hosts: ["localhost:9200"]
  protocol: https
  username: "beats_internal"
  password: "changeme"
  ssl.enabled: true
  ssl.certificate_authorities: ["/etc/elasticsearch/x-pack/ca.crt"]
  ssl.certificate: /etc/elasticsearch/x-pack/elasticsearch.crt
  ssl.key: /etc/elasticsearch/x-pack/elasticsearch.key
  ssl.enabled: true
  ssl.certificate_authorities: ["/etc/elasticsearch/x-pack/ca.crt"]
  ssl.certificate: /etc/elasticsearch/x-pack/elasticsearch.crt
  ssl.key: /etc/elasticsearch/x-pack/elasticsearch.key
setup.dashboards.snapshot: true
setup.dashboards.snapshot: true
setup.kibana:
  protocol: https
  username: "elastic"
  password: "changeit"
  ssl.enabled: true
  ssl.certificate_authorities: ["/etc/elasticsearch/x-pack/ca.crt"]
  ssl.certificate: /etc/elasticsearch/x-pack/elasticsearch.crt
  ssl.key: /etc/elasticsearch/x-pack/elasticsearch.key
logging.to_files: true
logging.files:
```
