### ISSUE TITLE
Remove output.elasticsearch.template.* examples from doc

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#4633]
In the 6.0 Alpha2 doc:

https://www.elastic.co/guide/en/beats/filebeat/master/elasticsearch-output.html#elasticsearch-output

```
output.elasticsearch:
  hosts: ["http://localhost:9200"]
  template.enabled: true
...
```

It still references the template options that are under output.elasticsearch.

These are now specified at the root level under setup.*:
https://www.elastic.co/guide/en/beats/filebeat/master/configuration-template.html, eg.
setup.template.enabled: false

So the example syntax in the elasticsearch output section should be removed.
