### ISSUE TITLE
Mysql connections count off by millions

### ISSUE THREAD

**Issue by mrminecart** [elastic/beats#4812]
All other metrics are correct but for some reason, active mysql connections is huge:
![image](https://user-images.githubusercontent.com/2838108/28865467-f8cf7d74-7767-11e7-848f-1de8012b7416.png)

We currently (according to the AWS RDS panel) have 5 connections open.

**Version**
MySQL 5.6.34 (AWS) -> metricbeat 5.4.1 -> logstash 5.4.2

**Config**
```
metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - filesystem
    - memory
    - network
    - process
  enabled: true
  period: 30s
  processes: ['.*']
  cpu_ticks: false

- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 30s

- module: mysql
  metricsets: ["status"]
  enabled: true
  period: 30s
  hosts: ["${MYSQL_USER}:${MYSQL_PASS}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/"]

output.logstash:
  hosts: ["127.0.0.1:3005"]

#output.console.pretty: true
```

Let me know if there is anything else you need!

Cheers
