### ISSUE TITLE
Add ability to configure JSON key for filebeat

### ISSUE THREAD

**Issue by denderello** [elastic/beats#4817]
I got a usecase where I would like to use the JSON parsing feature of filebeat together with structuring the document under the `json` key. However there is no configuration option to change the key name from `json` to something else (e.g. `vault`).

Would you be open to add a configuration option for the key? If so I would volunteer to add this feature.

**Comment by andrewkroh** [comment]
You can use the more flexible [decode_json_fields](https://www.elastic.co/guide/en/beats/filebeat/5.5/decode-json-fields.html) processor.

```
processors:
- decode_json_fields:
    fields: [message]
    target: vault
````
