### ISSUE TITLE
filebeat kubernetes module not picking up initContainers metadata

### ISSUE THREAD

**Issue by djschny** [elastic/beats#4825]
* Version: 6.0.0-alpha2
* Operating System: GKE container OS

In Kubernetes you Init Containers can be specified for a Deployment. Unfortunately it appears that the kubernetes metadata fields are not showing up for logs from an init-container in a pod. The logs from the main app container (in this case Nginx) are being populated fine. See the following screenshot for an example. The sleep and terminating log messages were from an init container.

![image](https://user-images.githubusercontent.com/129643/28925644-6ea54fe4-7833-11e7-917f-8d3eff509ee5.png)

Originally reported / discussed below:

https://discuss.elastic.co/t/kubernetes-metadata-not-showing-up-for-init-containers/95620

Below can be used to reproduce.

```
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.13.1
        ports:
        - containerPort: 80
      initContainers:
      - name: slowness
        image: busybox
        command: ['sh', '-c', 'echo "Sleeping 10 sceonds..." && sleep 10'] 
```
