### ISSUE TITLE
Beats Pipeline Routing

### ISSUE THREAD

**Issue by rossedman** [elastic/beats#4830]
- Version: 5.5.0

When trying to route to pipelines the `when.equals` statement never qualifies. The example in the documentation does not work. I have tried multiple variations of this, has anyone else encountered problems with this?

```
    filebeat.prospectors:
    - paths:
      - "/var/log/containers/*_default_services*.log"
      symlinks: true
      json.message_key: log
      json.keys_under_root: true
      json.add_error_key: true
      multiline.pattern: '^\s'
      multiline.match: after
      document_type: services
      fields:
        host.region: {{ location }}
        host.resource-group: {{ resource_group }}
        host.environment: {{ environment }}
        host.name: ${FILEBEAT_HOST}
        type: "services"
      fields_under_root: true

    output.elasticsearch:
      hosts: ["http://{{ elasticsearch_service_name }}:{{ elasticsearch_service_port }}"]
      username: "{{ elasticsearch_username }}"
      password: "{{ elasticsearch_password }}"
      timeout: 15
      index: "logs-{{ environment }}-%{+yyyy.MM.dd}"
      pipeline: kubelogs
      pipelines:
        - pipeline: springlogs
           when.equals:
             fields.type: "services"
```
