### ISSUE TITLE
Problem with aggregation of Performance Counters within same category

### ISSUE THREAD

**Issue by githubmui** [elastic/beats#4944]
- Version:    6.0.0.beta1
- Beat: MetricBeat
- Operating System:   Windows 7
- Module: Windows
- Steps to reproduce: Configure some performance counters from category memory

```
- module: windows
  metricsets: ["perfmon"]
  period: 10s
  perfmon.counters:

    - instance_label: "memory.instance"
      instance_name: ""
      measurement_label: "memory.AB"
      query: '\Memory\Available Bytes'  
      
    - instance_label: "memory.instance"
      instance_name: ""
      measurement_label: "memory.CB"
      query: '\Memory\Committed Bytes'  

    - instance_label: "memory.instance"
      instance_name: ""
      measurement_label: "memory.PS"
      query: '\Memory\Pages/sec'  
```
- Observed result: Every performance counter will be output as a separate JSON record.
- Expected result: All counter values with same "measurement_label"-namespace, with same instance_label and same instance_name will be aggregated to one single JSON record, like ...

```
{
  "@timestamp": "2017-08-18T03:38:45.395Z",
  "@metadata": {
    "beat": "metricbeat",
    "type": "doc"
  },
  "metricset": {
    "name": "perfmon",
    "rtt": 1000,
    "module": "windows"
  },
  "windows": {
    "perfmon": {
      "memory": {
        "instance": "",
        "AB": 10,
        "CB": 1.356897670,
        "PS": 9.2346e+10,      
      }
    }
  },
  "beat": {
    "name": "WINHOST",
    "hostname": "WINHOST",
    "version": "6.0.0-beta1"
  }
}
```
