### ISSUE TITLE
Possible Memory Leak

### ISSUE THREAD

**Issue by githubmui** [elastic/beats#5009]
There seems to be a memory leak related to following Metricbeat configuration:

- Version: "6.0.0-beta1"
- OS: Windows7
- Beat: Metricbeat
- Module: Windows

```
output.console:
  enabled: true
  pretty: false

- module: windows
  metricsets: ["perfmon"]
  period: 1s  
  perfmon.counters:
    - alias: "process"
      instance_label: "process.instance"
      instance_name: ""
      measurement_label: "process.handle_count"
      query: '\Process(*)\Handle Count'
```

![image](https://user-images.githubusercontent.com/17704200/29700791-c77e2f24-8967-11e7-90d4-4206aa32a1dd.png)

With file output it seems to be the same.

**Comment by andrewkroh** [comment]
Thanks for the report @githubmui. I'll see if I can reproduce it and track down the leak.

FYI: @maddin2016

**Comment by andrewkroh** [comment]
@githubmui How long did you let it run in order to get to 106.9 MB? Also what's the timespan covered in your graph?

**Comment by githubmui** [comment]
From vertical line to vertical line it's 10s. Increasing rate seems to be about 20kb per second.
Start memory is about 100MB and after 2 hours it's about 230MB.

![image](https://user-images.githubusercontent.com/17704200/29750188-abfc636c-8b3b-11e7-8745-8d756ffa081a.png)

**Comment by maddin2016** [comment]
Thanks @andrewkroh. I will try to reproduce

**Comment by andrewkroh** [comment]
I did a test over the weekend and I didn't see the leak. I ran two instances of Metricbeat both using the config below. One was the 64-bit 6.0.0-beta1 release and the other was from the master branch.

I ran my tests on Windows 2012 R2. I used a third metricbeat instance to collect process memory and golang heap metrics.

```
metricbeat.modules:
- module: windows
  metricsets: [perfmon]
  period: 250ms
  perfmon.counters:
  - alias: "process"
    instance_label: "process.instance"
    instance_name: ""
    measurement_label: "process.handle_count"
    query: '\Process(*)\Handle Count'
  - alias: "procesor.name.stats"
    instance_label: "processor.name"
    instance_name: "Total"
    measurement_label: "processor.time.total.pct"
    query: '\Processor Information(_Total)\% Processor Time'
  - alias: "diskio.name.stats"
    instance_label: "diskio.name"
    measurement_label: "diskio.write.bytes"
    query: '\PhysicalDisk(*)\Disk Writes/sec'
    format: "long"

output.console.enabled: true

logging.level: info
```

Kibana showing the memory usage over time (I started the 6.0.0-beta midway through the weekend after master wasn't showing a leak). The Golang Heap metrics are from the process running the master branch build.
<img width="1157" alt="kibana" src="https://user-images.githubusercontent.com/4565752/29773522-da122562-8bcb-11e7-91e2-5eefe2d70570.png">

Sysinternals from master:
<img width="428" alt="metricbeat-master" src="https://user-images.githubusercontent.com/4565752/29773525-de5ac7aa-8bcb-11e7-9603-a7e6b72c3292.png">

Sysinternals from 6.0.0-beta1:
<img width="427" alt="metricbeat-6 0 0-beta1" src="https://user-images.githubusercontent.com/4565752/29773527-e212809a-8bcb-11e7-87f3-fe9eb3958821.png">
