### ISSUE TITLE
heartbeat fails silently on urls with no protocol

### ISSUE THREAD

**Issue by kurtado** [elastic/beats#5293]
Version: 6.0.0-rc1 of heartbeat and elasticsearch.
OS: Ubuntu 16.04.3

Maybe not a bug per se, but maybe the user experience could be improved here...

If the user omits the protocol string (e.g. `http://`), the config checker returns `OK`, but heartbeat will silently fail to collect data for that host, and any others in that `urls` list.

here is a sample config (note the second http, with `www.yahoo.com` configured w/o protocol string)

```
heartbeat.monitors:                                                                         
- type: http                                                                                
  urls: ["http://www.elastic.co"]                                                           
  schedule: '@every 10s'                                                                    
  # Total test connection and data exchange timeout                                         
  #timeout: 16s                                                                                                                                 
                                                                                            
- type: http                                                                                
  urls: ["http://www.google.com","www.yahoo.com"]                                                                   
  schedule: '@every 10s'                                                                    
  # Total test connection and data exchange timeout                                         
  #timeout: 16s
```
config checks out OK:
```
ubuntu@ip-172-31-30-125:~/heartbeat$ ./heartbeat test config                              
Config OK                                                                                   
ubuntu@ip-172-31-30-125:~/heartbeat$
```

But heartbeat will not collect data for either google or yahoo (elastic.co is fine)

`-d` is also silent
```
ubuntu@ip-172-31-30-125:~/heartbeat$ ./heartbeat -d "*"
(no output :)
```

Seems like 1) the config test should warn that one of the URLs is not valid, 2) running in `-d "*"` mode should complain, or 3) at least google should work, even if yahoo doesn't.
