### ISSUE TITLE
Filebeat crashes on fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by Shemeikka** [elastic/beats#5304]
Hi,

I'm running Filebeat in docker container and after some time, filebeat crashed with fatal error: concurrent map read and map write.

I had about 20 docker containers running on localhost with filebeat and logstash. Filebeat forwarded all container logs to logstash which outputs those to a file in container's name.

Both filebeat and logstash only log to a file.

Log can be found: https://gist.github.com/Shemeikka/b690f43ec446445281fa011eeec9d658

Filebeat image: docker.elastic.co/beats/filebeat:6.0.0-beta2

Filebeat config:

```
filebeat.prospectors:
- type: log
  paths:    
    - /var/lib/docker/containers/*/*.log
  json.message_key: log
  json.keys_under_root: true
  fields:    
    document_type: docker_log
  processors:
  - add_docker_metadata: ~

  multiline.pattern: '^connect: |^send: |^reply: |^data: '
  multiline.negate: false
  multiline.match: after

logging.level: info
logging.to_files: true
logging.to_syslog: false
logging.files:
  path: /var/log/
  name: filebeat.log
  keepfiles: 7
  rotateeverybytes: 104857600

fields_under_root: true
```
