### ISSUE TITLE
Add exclude_files option to file integrity module

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#5342]
An `exclude_files` configuration option should be added to the file integrity module in Auditbeat to ignore files that match any of the regular expressions specified in the list.

For example:

```
auditbeat.modules:
- module: audit
  metricsets: [file]
  file.paths:
  - /bin
  - /usr/bin
  - /usr/local/bin
  file.exclude_files: ['\.DS_Store$', '\.swp$']
```

Naming wise I'm debating between `file.exclude` and `file.exclude_files`. The latter is consistent with [Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#exclude-files).
