### ISSUE TITLE
[FEATURE] Add common API for state storage with configurable storage backends

### ISSUE THREAD

**Issue by dustin-decker** [elastic/beats#5375]
ref discussion: https://discuss.elastic.co/t/adding-state-storage-backend-options-to-the-libbeat-framework/101080/4

**Two reasons we need this in libbeat:**
1. Right now it is up to the developer of each beat to implement state storage, if it's needed.
2. When run on systems without local storage, this may require implementing external storage for state such as consul, etcd, a database, or elasticsearch. This is a very common scenario if you want to run in a container scheduler environment (Swarm, Mesos, Kubernetes...)

**What it could look like**
For the developer's perspective, there is now a `io.ReadWriter` that you can read and write `[]byte` blobs too. That's all you need to worry about as a developer.

For the user, when configuring any beat they can use a standard format:
```
state:
  storage_driver: local
  storage_opts:
    path: /var/lib/gsuitebeat/state
```
or
```
state:
  storage_driver: etcd
  storage_opts:
    address:   "127.0.0.1:8500"
    token: "3940uf3ij32094j43"
    key: "co.elastic.gsuitebeat.state"
```

**Some design considerations**
- Offer atomic and configurable buffered read/write operations depending on storage driver

I'll try to do at least a POC when I find time, but i'm open to someone else taking a stab at it.
