### ISSUE TITLE
Heartbeat to lookup status url

### ISSUE THREAD

**Issue by yasvanth** [elastic/beats#5405]
Hi Team,
I am testing Heartbeat module to look for the status url of a service. For instance: my application runs behind apache so I create a apache web page which checks whether the application is running or not:
<pre>
https://example.org/status
</pre>
 The above url return 
<pre>
Application: running
</pre>
If my application is not running, The status page returns
<pre>
Application: not running
</pre>

Can I use an heartbeat to check the status value "running" to make sure my application is running. 

Thanks,
Yash

**Comment by andrewkroh** [comment]
Yes, Heartbeat can be used to check that the page's body includes `Application: running`. For example:

```
heartbeat.monitors:
- type: http
  schedule: '@every 60s'
  urls: ["https://example.org/status"]
  check.response:
    status: 200
    body: 'Application: running'
```

References:
- https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-heartbeat-options.html#monitor-http-check
