### ISSUE TITLE
field keys with dots get nested

### ISSUE THREAD

**Issue by vjsamuel** [elastic/beats#5471]
Currently if i write a config file like:

```
fields:
  kubernetes:
    labels:
      kubernetes.io/app: foo
```

The output would be:

```
{
  "kubernetes": {
    "labels": {
      "kubernetes": {
        "io/app": "foo"
      }
  }
}
```

The ideal output would be:
```
{
  "kubernetes": {
    "labels": {
      "kubernetes.io/app": "foo"
    }
  }
}
```
Dot keys in fields should be carried forward as is. Can we please have this?
