### ISSUE TITLE
Why doesn't Filebeat exclude_files work correctly?

### ISSUE THREAD

**Issue by pietervogelaar** [elastic/beats#5493]
I have the following configuration:

```
filebeat:
  prospectors:
    - input_type: log
      paths:
        - /var/log/tomcat/*.log
        - /var/log/tomcats/*/*.log
      encoding: plain
      exclude_files:
        - ^catalina
        - ^localhost
        - ^localhost_access
        - ^manager
        - ^host-manager
        - ^gc
        - ^stacktrace
        - \.txt$
        - \.gz$
      document_type: tomcat-webapp
```

But `gc.log` for example is still being picked up. Why is this configuration not working?
