### ISSUE TITLE
null value fields are dropped from JSON decoding

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/beats#5522]
- Filebeat 5.6.1 under OSX

Given a file like this:

```
{"test-null": null, "@timestamp":"2016-11-01T14:39:36.322", "type": 42,  "level":"INFO", "message":"test"}
```

With the following FB config:

```
filebeat.registry_file: /tmp/reg
filebeat.prospectors:

- paths:
    - /path/to/json-data.json
  json.keys_under_root: false
  close_eof: true

output.elasticsearch:
  hosts: ["http://localhost:9200"]

logging.level: debug
```

The `test-null` field is dropped before being sent to ES:

```
 {
        "_index": "filebeat-2017.11.06",
        "_type": "doc",
        "_id": "AV-SYVk_9oC3GfO5heZP",
        "_score": 1,
        "_source": {
          "@timestamp": "2017-11-06T17:29:29.150Z",
          ...
          "input_type": "log",
          "json": {
            "@timestamp": "2016-11-01T14:39:36.322",
            "level": "INFO",
            "message": "test",
            "type": 42
          },
          "offset": 1075,
          "source": "/path/to/json-data.json",
          "type": "log"
        }
      }
```

While hoping to make use of Elasticsearch's [null_value](https://www.elastic.co/guide/en/elasticsearch/reference/current/null-value.html) mapping parameter.
