### ISSUE TITLE
Proposal docker prospector with processor and default behaviour

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#5661]
Currently an example config for the docker prospector looks as following:

```
 - type: docker
   paths:
     - /var/lib/docker/containers/*/*.log
   processors:
   - add_docker_metadata: ~
```

If someone wants to get all logs, I suggest the following should be possible:

```
- type: docker
```
It would set automatically the above as the default path to be harvested. Currently a "no paths defined" error pops up. 

The `add_docker_metadata` should be enabled by default. There must be a config option to disable it if not wanted.

@exekias WDYT?
