### ISSUE TITLE
packetbeat requires "index" setting when using logstash output

### ISSUE THREAD

**Issue by djschny** [elastic/beats#574]
It appears currently when using logstash output, there is an `index` setting. This seems very odd, as just because you're shipping to Logstash, does not mean Elasticsearch is involved. For example I could ship to Logstash and then from there ship to S3 or any other similar kind of store and never involve Elasticsearch. Making tight coupling between Elasticsearch and Packetbeat should be removed.

https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-configuration.html#logstash-output

```
output:
  logstash:
    hosts: ["localhost:5044"]

    # index configures '@metadata.beat' field to be used by Logstash for
    # indexing. The default index name depends on the each beat.
    # For Packetbeat, the default is set to packetbeat, for Topbeat to
    # topbeat and for Filebeat to filebeat.
    index: packetbeat
```

My suggestion instead would be to remove this setting and then offer up a generic way to apply tags and metadata. For example:
- metadata.beat_type_field - The name of the field to use to store the type of beat. Defaults to `beats.type`
- metadata.beat_type_value - The value for the beat type field. Defaults to `packetbeat`
