### ISSUE TITLE
Winlogbeat Registry File (.winlogbeat.yml) not properly tracking event logs

### ISSUE THREAD

**Issue by krasekhi** [elastic/beats#5813]
For confirmed bugs, please report:
- Version: Winlogbeat 6.0.0
- Operating System: Windows 10
- Steps to Reproduce: Install Agent

**6.0.0**
```
update_time: 2017-12-05T15:16:38.2530588Z
event_logs:
- name: wineventlog
  record_number: 528669
  timestamp: 2017-12-05T15:16:31.1188124Z
```
**5.5.2**
```
update_time: 2017-12-05T15:16:07.841893Z
event_logs:
- name: Application
  record_number: 250502
  timestamp: 2017-12-05T15:16:02.6721303Z
- name: Microsoft-Windows-Diagnostics-Performance/Operational
  record_number: 204
  timestamp: 2017-11-28T00:27:30.1588877Z
- name: System
  record_number: 137622
  timestamp: 2017-12-05T15:08:40.0562157Z
```

Reference : https://discuss.elastic.co/t/winlogbeat-6-0-0-registry-file/110384
