### ISSUE TITLE
filebeat cannot work if glob pattern involves too many dirs/files

### ISSUE THREAD

**Issue by kingluo** [elastic/beats#5843]
- Version:  filebeat-6.0.0-x86_64.rpm
- Operating System: centos6.5
- Steps to Reproduce: 

`filebeat.yml`:

```yml
- type: log

  # Change to true to enable this prospector configuration.
  enabled: true
  close_removed: false
  #close_timeout: 30s
  close_inactive: 10s
  scan_frequency: 3s
  tail_files: true

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /var/foobar/foo/*/*.log
```

There is 7000 subdirs under `/var/foobar/foo/`, and 10000 files per subdir.

The filebeat keeps running with high cpu (I run it for half an hour) and do not catch any files for input and could not even be killed!
If I remove the first `*`, e.g. `/var/foobar/foo/d1/*.log`, then it works after busy running a while.
