### ISSUE TITLE
Missing cgroup fields on hardened Debian 8 machines leads to errors

### ISSUE THREAD

**Issue by liar666** [elastic/beats#5854]
Hi,

NOTE: I'm posting this (duplicate) here as requested by: https://github.com/elastic/beats-docker/issues/27#issuecomment-350710865

I'm running MetricBeat as explained here: https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html#monitoring-host

On a (hardened) Debian 8 machine from OVH French provided.

In MetricBeats' log I get a lot of errors like the following:
`WARN Can not index event (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse [system.process.cgroup.memory.memsw.limit.bytes]","caused_by":{"type":"json_parse_exception","reason":"Numeric value (18446744073709551615) out of range of long (-9223372036854775808 - 9223372036854775807)
`
Same error occurs for:
```
system.process.cgroup.memory.kmem_tcp.limit.bytes
system.process.cgroup.memory.memsw.limit.bytes
system.process.cgroup.memory.stats.hierarchical_memory_limit.bytes

```
For confirmed bugs, please report:

    Beat Version: MetricBeat 6.0.0 & 6.0.1
    Operating System: Debian 8 / Linux xxx 3.14.32-xxxx-grs-ipv6-64 #1 SMP Tue Jun 30 18:50:21 CEST 2015 x86_64 GNU/Linux
    Docker Version: 1.6.2
    Steps to Reproduce:

    run with
    host$docker run --name "MBeats"
    --volume=/proc:/hostfs/proc:ro \
    --volume=/sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro \
    --volume=/:/hostfs:ro \
    --net=host
    docker.elastic.co/beats/metricbeat:6.0.1 -system.hostfs=/hostfs
    Log into guest
    host$docker exec -it "MBeats" /bin/bash
    Watch logs
    guest$ tail -f logs/metricbeat

**Comment by liar666** [comment]
By the way, on the same "hardened" server, I've just activated the 'docker' module. I now also have the following errors:

```
2017-12-11T13:34:20Z ERR  Error on field 'user': Missing field: user, Error: Key `CPUUser` not found
2017-12-11T13:34:20Z ERR  Error on field 'system': Missing field: system, Error: Key `CPUSystem` not found
2017-12-11T13:34:20Z ERR  Error on field 'children_user': Missing field: children_user, Error: Key `CPUChildrenUser` not found
2017-12-11T13:34:20Z ERR  Error on field 'children_system': Missing field: children_system, Error: Key `CPUChildrenSystem` not found
2017-12-11T13:34:20Z ERR  Error on field 'server_uptime': Missing field: server_uptime, Error: Key `ServerUptimeSeconds` not found

```

**Comment by exekias** [comment]
Hi @liar666, could you give us some details on that "hardening" applied to this server, it looks like it's limiting the results on some fields

**Comment by liar666** [comment]
Hi,

As I said, the machine is a server from the OVH (http://ovh.net/) French provider.

The product is a Kimsufi server, with an installed image identified as "Debian 8.7 stable (Jessie) (oldstable)".

The only element I can see that might be blocking MBeat is the "grs" in the "uname" I've provided, which probably refers to https://www.grsecurity.net/ . That's what I meant by "Hardened".

**Comment by pmoust** [comment]
Can confirm the same. And yes, it is a security feature.

**Comment by ruflin** [comment]
@pmoust Are the fields which are removed user define or is that a standard set. Asking myself if we should just make the above fields optional? The part I worry is that if these fields are missing also our Dashboards break.

**Comment by excalq** [comment]
We're experiencing the same issue, and this is on a hardened Debian-based server AMI, provided by a security vendor. Anyway, here's the method I used for dropping these problematic fields when this occurs:

Note this is adapted from https://discuss.elastic.co/t/metricbeat-5-2-2-configtest-fails-to-find-templates/85449/12, but updated for a Metricbeat v6 config, which changes `filters` to `processors` and requires absolute  field prefixes (`cgroup.xyz` becomes `system.process.cgroup.xyz`):

```
- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
  [...]
  processors:
  - drop_fields:
      fields: ['system.process.cgroup.memory.kmem.limit.bytes']
      when.range:
        system.process.cgroup.memory.kmem.limit.bytes.gte: 9223372036854775808
  - drop_fields:
      fields: ['system.process.cgroup.memory.kmem_tcp.limit.bytes']
      when.range:
        system.process.cgroup.memory.kmem_tcp.limit.bytes.gte: 9223372036854775808
  - drop_fields:
      fields: ['system.process.cgroup.memory.mem.limit.bytes']
      when.range:
        system.process.cgroup.memory.mem.limit.bytes.gte: 9223372036854775808
  - drop_fields:
      fields: ['system.process.cgroup.memory.memsw.limit.bytes']
      when.range:
        system.process.cgroup.memory.memsw.limit.bytes.gte: 9223372036854775808
  - drop_fields:
      fields: ['system.process.cgroup.memory.stats.hierarchical_memory_limit.bytes']
      when.range:
        system.process.cgroup.memory.stats.hierarchical_memory_limit.bytes.gte: 9223372036854775808
```

**Comment by Constantin07** [comment]
I'm experiencing the same issue with metricbeat 6.2.3 and Eslasticsearch 6.2.3 even on non-hardened Ubuntu 16.04 Linux.
Is the above workaround a temporary solution or it should be a proper permanent fix ?

**Comment by ruflin** [comment]
@Constantin07 I think the above should be a temporary workaround and we want to have proper fix long term. It could also be a simple config option that automatically drops the above fields.

For your case it's interesting that these values are missing but you are not on a hardened system. Is this a stock Ubuntu image? How does your setup look like?

**Comment by Constantin07** [comment]
@ruflin Yes, stock Ubuntu image but it also happens on CoreOS Linux (different versions).

metricbeat.yml:
```yml
metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: true
  reload.period: 10s

name: metricbeat

fields:
  environment: ${env:?You need to set the env environment variable}

processors:
- add_cloud_metadata: ~

logging.files:
  rotateeverybytes: 5242880
  keepfiles: 2

output.logstash:
  hosts: ["logstash.****:5044"]
```

system.yml:
```yml
- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    #- core
    - diskio
    #- socket
  processes: ['.*']
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
```

docker.yml:
```yml
- module: docker
  period: 10s
  metricsets:
    - container
    - cpu
    - diskio
    - image
    - info
    - memory
    - network
    - healthcheck
  hosts: ["unix:///var/run/docker.sock"]
```

and here are the messages I get in logstash:
```
[2018-03-29T09:34:13,578][WARN ][logstash.outputs.elasticsearch] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"metricbeat-6.2.3-2018.03.29", :_type=>"doc", :_routing=>nil, :pipeline=>""}, #<LogStash::Event:0x76292ff5>], :response=>{"index"=>{"_index"=>"metricbeat-6.2.3-2018.03.29", "_type"=>"doc", "_id"=>"z-cbcWIBOyQ4MNMLjGQu", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [system.process.cgroup.memory.kmem.limit.bytes]", "caused_by"=>{"type"=>"i_o_exception", "reason"=>"Numeric value (18446744073709551615) out of range of long (-9223372036854775808 - 9223372036854775807)
at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@3464d418; line: 1, column: 613]"}}}}}
```

In metricbeat index template `system.process.cgroup.memory.kmem.limit.bytes` is defined as Number.
