### ISSUE TITLE
Filebeat6.1.0 autodiscover container - ability to discover containers using container name

### ISSUE THREAD

**Issue by asafs133** [elastic/beats#5941]
Hello team,

I'm working with the new feature of container type (which included in Filebeat 6.1.0), and currently, you allow to discover containers using containers.ids only.

In a situation that I don't know what are my containers id's, for example in AWS ECS, the containers are created dynamically, and it's very difficult to resolve the containers ids.

It could be wonderful if you enable us to resolve the containers by container name.
For example, the containers names are generated by a pattern that I set up in the ECS configuration, so if the container pattern name is: tomcat_conatiner_xx and I have tomcat_conatiner_01, tomcat_conatiner_02, it is requested that you allow us to set up the following syntax in filebeat.yml:

```
- type: docker
  # Change to true to enable this prospector configuration.
  enabled: true
  containers.names:
    - 'tomcat_conatiner_*'
  processors:
  - add_docker_metadata: ~
```

It would be a very good improvement for automation environment like AWS ECS.

Thanks!

**Comment by ruflin** [comment]
I think the feature you are looking for is autodiscovery: https://www.elastic.co/guide/en/beats/filebeat/6.1/configuration-autodiscover.html Closing this issue as I think it solves your problem, if not please reopen.

**Comment by asafs133** [comment]
Hi Ruflin,
Thanks for a quick answer.

I tried to configure the auto discover option without success.
When I'm working with the "filebeat.autodiscover" should I need to add the "filebeat.prospectors" block too?

Currently, this is my configuration without filebeat.prospectors:

```
filebeat.autodiscover:
  # List of enabled autodiscover providers
  providers:
    - type: docker
      templates:
        - condition:
            equals.docker.container.image: wildfly_image
          config:
            - type: log
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
      processors:
      - add_docker_metadata: ~

      fields:
        environment: WF-Prod
      fields_under_root: true

      multiline.pattern: '^[[:space:]]+|]$'
      multiline.match: after
```

As you can see, because of the "filebeat.prospectors" has been omitted, I had to add the processors, fields & multiline options under the "filebeat.autodiscover". Is it the right thing to do?

Thanks.

**Comment by ruflin** [comment]
You have to add the options under `config` namespace as this from what the config will be built.

As far as I remember the processor is for the above case not needed as it will be already enabled by default. But @exekias may confirm.

**Comment by asafs133** [comment]
You're right,
The issue was the indentation, and "add_docker_metadata" should be omitted.
Working configuration is below:

```
filebeat.autodiscover:
  # List of enabled autodiscover providers
  providers:
    - type: docker
      templates:
        - condition:
            equals.docker.container.image: full_image_path/image_name:version
          config:
            - type: log
              paths:
                - /var/lib/docker/containers/${data.docker.container.id}/*.log
              fields:
                environment: Development
              fields_under_root: true

              multiline.pattern: '^[[:space:]]+|]$'
              multiline.match: after
```

Thanks a lot!
