### ISSUE TITLE
Changes no longer detected in files that have been rotated and ignore_older kicks in before the next change

### ISSUE THREAD

**Issue by pghalliday** [elastic/beats#596]
Raised this yesterday here: https://github.com/elastic/filebeat/issues/320
Today I realised that the project has moved.

---

Using the following configuration and Filebeat v1.0.1 on Ubuntu 14.04

```
filebeat:
  prospectors:
    - paths:
        - "/var/log/test/*.log"
      ignore_older: 30s
      scan_frequency: 5s

  registry_file: /var/lib/filebeat/registry

output:
  logstash:
    hosts: ["logstash.myserver.com:5044"]

shipper:

logging:
  level: debug
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat.log
    rotateeverybytes: 10485760 # = 10MB
```

Changes to files are not detected when rotating files then waiting 30s before adding another line. ie:

1. `mkdir -p /var/log/test`
1. Start Filebeat with no log files in /var/log/test/
1. `cd /var/log/test`
1. `echo "hello" >> hello.log`
1. Line is picked up and published
1. Wait 30s for ignore_older to kick in
1. `echo "hello" >> hello.log`
1. Line is picked up and published
1. `mv hello.log hello.log.1 && echo "hello" >> hello.log`
1. Line is picked up and published
1. `mv hello.log hello.log.1 && touch hello.log`
1. Wait 30s for ignore_older to kick in
1. `echo "hello" >> hello.log`
1. Line is **NOT** picked up and published

There are no additional errors in the debug, just lots of this:

```
2015-12-28T14:50:51Z DBG  Start next scan
2015-12-28T14:50:51Z DBG  scan path /var/log/test/*.log
2015-12-28T14:50:51Z DBG  Check file for harvesting: /var/log/test/hello.log
2015-12-28T14:50:51Z DBG  Update existing file for harvesting: /var/log/test/hello.log
2015-12-28T14:50:51Z DBG  Not harvesting, file didn't change: /var/log/test/hello.log
2015-12-28T14:50:55Z DBG  Flushing spooler because of timemout. Events flushed: 0
```

Filebeat seems to continue and in more realistic scenarios, other prospectors continue working and publishing logs.
