### ISSUE TITLE
add_kubernetes_metadata processor is skipping records

### ISSUE THREAD

**Issue by felipejfc** [elastic/beats#6042]
- Version: 6.1.1
- Operating System: minikube
- Steps to Reproduce: deploy filebeat into minikube with the following config:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  filebeat.yml: |-
    filebeat.config:
      prospectors:
        path: ${path.config}/prospectors.d/*.yml
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    setup.template:
      name: "template-stash-filebeat"
      pattern: "kstash-*"
    output.elasticsearch:
      index: "kstash-%{[kubernetes.namespace]}-%{+yyyy.MM.dd}"
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-prospectors
  namespace: kube-system
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: filebeat
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.1.1
        args: [
          "-c", "/etc/filebeat.yml",
          "-d", "publish",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-stag.xxxxx.com
        - name: ELASTICSEARCH_PORT
          value: "9200"
        securityContext:
          runAsUser: 0
        resources: {}
        #  limits:
        #    memory: 200Mi
        #  requests:
        #    cpu: 100m
        #    memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: prospectors
          mountPath: /usr/share/filebeat/prospectors.d
          readOnly: true
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: prospectors
        configMap:
          defaultMode: 0600
          name: filebeat-prospectors
      - name: data
        emptyDir: {}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
---
```

I'm trying filebeat in minikube and hit this problem, it seems that docker prospector/kubernetes_add_metadata is not adding the metadata to some records:

```
filebeat-4q2x2 filebeat 2018/01/09 22:33:22.608847 processor.go:275: DBG [publish] Publish event: {
filebeat-4q2x2 filebeat   "@timestamp": "2017-12-18T20:27:56.029Z",
filebeat-4q2x2 filebeat   "@metadata": {
filebeat-4q2x2 filebeat     "beat": "filebeat",
filebeat-4q2x2 filebeat     "type": "doc",
filebeat-4q2x2 filebeat     "version": "6.1.1"
filebeat-4q2x2 filebeat   },
filebeat-4q2x2 filebeat   "beat": {
filebeat-4q2x2 filebeat     "name": "filebeat-4q2x2",
filebeat-4q2x2 filebeat     "hostname": "filebeat-4q2x2",
filebeat-4q2x2 filebeat     "version": "6.1.1"
filebeat-4q2x2 filebeat   },
filebeat-4q2x2 filebeat   "offset": 49589,
filebeat-4q2x2 filebeat   "stream": "stdout",
filebeat-4q2x2 filebeat   "message": "2017/12/18 20:27:56 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.",
filebeat-4q2x2 filebeat   "source": "/var/lib/docker/containers/7874a93a424f7358babb07dfe1b412041fbc8bdc42aa0a4927330bca52d22e18/7874a93a424f7358babb07dfe1b412041fbc8bdc42aa0a4927330bca52d22e18-json.log",
filebeat-4q2x2 filebeat   "prospector": {
filebeat-4q2x2 filebeat     "type": "docker"
filebeat-4q2x2 filebeat   }
```

this logs comes from a container that is running inside kubernetes and I have docker prospector with the following config:
```
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
```

some other events are being updated with kubernetes metadata:

```
filebeat-4q2x2 filebeat 2018/01/09 22:33:22.608682 processor.go:275: DBG [publish] Publish event: {
filebeat-4q2x2 filebeat   "@timestamp": "2018-01-08T19:23:09.797Z",
filebeat-4q2x2 filebeat   "@metadata": {
filebeat-4q2x2 filebeat     "beat": "filebeat",
filebeat-4q2x2 filebeat     "type": "doc",
filebeat-4q2x2 filebeat     "version": "6.1.1"
filebeat-4q2x2 filebeat   },
filebeat-4q2x2 filebeat   "beat": {
filebeat-4q2x2 filebeat     "version": "6.1.1",
filebeat-4q2x2 filebeat     "name": "filebeat-4q2x2",
filebeat-4q2x2 filebeat     "hostname": "filebeat-4q2x2"
filebeat-4q2x2 filebeat   },
filebeat-4q2x2 filebeat   "offset": 31227,
filebeat-4q2x2 filebeat   "stream": "stdout",
filebeat-4q2x2 filebeat   "message": "INFO: == Kubernetes addon reconcile completed at 2018-01-08T19:23:09+0000 ==",
filebeat-4q2x2 filebeat   "source": "/var/lib/docker/containers/c7abd804756ada3a1c9e3b13aa1ce6076e86a042048692792f3222045016c13a/c7abd804756ada3a1c9e3b13aa1ce6076e86a042048692792f3222045016c13a-json.log",
filebeat-4q2x2 filebeat   "prospector": {
filebeat-4q2x2 filebeat     "type": "docker"
filebeat-4q2x2 filebeat   },
filebeat-4q2x2 filebeat   "kubernetes": {
filebeat-4q2x2 filebeat     "namespace": "kube-system",
filebeat-4q2x2 filebeat     "labels": {
filebeat-4q2x2 filebeat       "component": "kube-addon-manager",
filebeat-4q2x2 filebeat       "kubernetes.io/minikube-addons": "addon-manager",
filebeat-4q2x2 filebeat       "version": "v6.4"
filebeat-4q2x2 filebeat     },
filebeat-4q2x2 filebeat     "container": {
filebeat-4q2x2 filebeat       "name": "kube-addon-manager"
filebeat-4q2x2 filebeat     },
filebeat-4q2x2 filebeat     "pod": {
filebeat-4q2x2 filebeat       "name": "kube-addon-manager-minikube"
filebeat-4q2x2 filebeat     }
filebeat-4q2x2 filebeat   }
```
