### ISSUE TITLE
SSL docs should mention modules and show an example config

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#6054]
Currently the documentation about SSL does not mention modules or show an example of how to specify SSL settings when you are using modules, so it's hard for users to know where to define the SSL settings in their module configs. 

Here's a Kubernetes module example (I haven't verified that this config works, but it was used as an example in a discussion about this doc issue.)

````
metricbeat.modules:
# Node metrics, from kubelet:
- module: kubernetes
  metricsets:
    - node
    - system
    - pod
    - container
    - volume
  period: 10s
  hosts: ["localhost:10255"]
  ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]
  ssl.certificate: "/etc/pki/client/cert.pem"
  ssl.key: "/etc/pki/client/cert.key"
````
