### ISSUE TITLE
[Feature Request] add_docker_metadata should accept short ids for containers

### ISSUE THREAD

**Issue by chrisregnier** [elastic/beats#6092]
I have a case where I'm trying to write out structured data to a log file in a container on a shared tmpfs volume with the filebeat container, and I'd like to attach the docker metadata. I'm writing the logs into the path /logs/${HOSTNAME}/*.log, in order to extract the container id, since docker will set the hostname to the short id of the container, so the short id is fairly accessible without having to jump through a lot of extra hoops. Unfortunately, when I tried using the add_docker_metadata.match_source option to pull out the id, it wouldn't match, and upon further investigation it looks like it will only match the long ids.

Since the short id is easily accessible from within a container, I think it would be useful to match against it. Is this something that's possible?

**Comment by ruflin** [comment]
@exekias Do have this data available in our meta information?
@chrisregnier Is the short id just the first x chars of the full id?

**Comment by andrewkroh** [comment]
The short ID is a truncated version of the container ID so the processor does have the information. It would just need to do a prefix match.

**Comment by chrisregnier** [comment]
As andrewkroh mentioned, yes the short id is the the first 12 characters.
This would be fantastic, thanks!

**Comment by ripcurld0** [comment]
Hi @chrisregnier 
Can you elaborate more how you configurations look like.
Are you running filebeats within a container?
How does your filebeat configurations look like? (just the relevant part that read Docker logs)
How did you setup the tmpfs for each container?

Thanks.

**Comment by chrisregnier** [comment]
Here's roughly what I was going for

- Java app that logs to json files at `/logs/${HOSTNAME}/*.log`
 - slf4j logger config is pulling HOSTNAME from available environment vars

compose file:
```
services:
  java_app:
    build: ./java_app
    volumes:
      - logs:/logs     # shared volume with logs
  log_extractor:
    image: docker.elastic.co/beats/filebeat:6.1.1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - logs:/java_logs     # shared volume with logs
      - filebeat.yml: /usr/share/filebeat/filebeat.yml  # config file added in image somehow
volumes:
  logs:
```

And the log extractor filebeats.yml
```
filebeat.prospectors:
  - type: log
    paths:
      - '/java_logs/*/*.log'

    json.message_key: log
    json.add_error_key: true
    json.keys_under_root: true

    processors:
      # Add docker information
      - add_docker_metadata: 
          match_source: true
          # tries to match the container id from 2nd param in path
          match_source_index: 1

output.elasticsearch:
  hosts: ['${ELASTIC_HOST}']
```

So the logs here are accessed over a shared volume, and the config here probably only works well in single node systems (which is what I've got). I suspect if you want to scale up then you'd need to be careful about how the volume is setup and shared. Basically I just want a local host shared volume.
