### ISSUE TITLE
Monitoring event includes zeros for every output message metrics for ES

### ISSUE THREAD

**Issue by kvch** [elastic/beats#6135]
Beats is not able to track messages sent to each output.
@urso discovered the following problem with monitoring and I was able to reproduce it with 6.0, 6.1 and master.

## Version
6.0, 6.1, 6.2

## OS
Debian

## Steps to reproduce
Configuration:
```
filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/*.log

output.elasticsearch:
  hosts: ["localhost:9200"]

xpack.monitoring:
  enabled: true
```
After sending the events to ES the following partial monitoring is event is sent with the key `libbeat`:
```
"libbeat": {
  "config": {
    "module": {
      "stops": 0,
      "running": 0,
      "starts": 0
    },
    "reloads": 1
  },
  "output": {
    "read": {
      "bytes": 42405,
      "errors": 0
    },
    "type": "elasticsearch",
    "events": {
      "acked": 0,
      "failed": 0,
      "dropped": 0,
      "duplicates": 0,
      "active": 0,
      "batches": 0,
      "total": 0
    },
    "write": {
      "bytes": 1123916,
      "errors": 0
    }
  },
  "pipeline": {
    "events": {
      "failed": 0,
      "dropped": 0,
      "retry": 50,
      "active": 0,
      "total": 3198,
      "filtered": 4,
      "published": 3194
    },
    "queue": {
      "acked": 3194
    },
    "clients": 1
  }
}
```
`event["libbeat"]["pipeline"]["events"]` seems to be correctly displaying the total number of messages processed and sent. However, `event["libbeat"]["output"]["events"]` reports zero for all metrics for events going to ES. As only ES is configured as output, the two numbers have to be the same.
