### ISSUE TITLE
Improve documentation for output.kafka.topics

### ISSUE THREAD

**Issue by inqueue** [elastic/beats#6142]
Can the [documentation](https://www.elastic.co/guide/en/beats/filebeat/master/kafka-output.html#_literal_topics_literal) for `output.kafka.topics` provide one or two examples on how to use conditional selector rules for topic selection? The documentation explains that it can be done just not how to do it.

**Comment by urso** [comment]
For reference see [elasticsearch output indices settings](https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html#_literal_indices_literal). Just replace "index" with "topic" and "indices" with "topics".

e.g.:

```
output.kafka:
  hosts: ["http://localhost:9200"]
  topic: "logs-%{[beat.version]}" 
  topics:
    - topic: "critical-%{[beat.version]}"
      when.contains:
        message: "CRITICAL"
    - topic: "error-%{[beat.version]}"
      when.contains:
        message: "ERR"
```

`topic`: uses format strings and can reference any field in the event. If referenced field is missing from the event, topic will be empty -> event not indexible
