### ISSUE TITLE
Metricbeats sending doc type as "doc" rather than "metricsets"

### ISSUE THREAD

**Issue by Swashy** [elastic/beats#6185]
Appears to have started after Metricbeat 5.6.3, upgrading to 6.1.1 and 6.1.2 has broken my pipeline.

[Official documentation states](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-common.html) that "type" is always set to "metricsets", but I'm not seeing the same.

My Elasticsearch cluster began silently dropping Metricbeats input, and after investigating it looks like it may be due to the doc type changing.

**metricbeat version 5.6.3 output:**
```
2018-01-25T19:23:18Z DBG  Publish: {
  "@timestamp": "2018-01-25T19:23:18.779Z",
  "beat": {
    "hostname": "production.website",
    "name": "production.website",
    "version": "5.6.3"
  },
  "metricset": {
    "host": "127.0.0.1",
    "module": "nginx",
    "name": "stubstatus",
    "rtt": 2376
  },
  "nginx": {
    "stubstatus": {
      "accepts": 71566347,
      "active": 2127,
      "current": 105108684,
      "dropped": 0,
      "handled": 71566347,
      "hostname": "127.0.0.1",
      "reading": 0,
      "requests": 105108684,
      "waiting": 2072,
      "writing": 68
    }
  },
  "tags": [
    "metricbeat"
  ],
  "type": "metricsets"
}
```

**Metricbeats 6.1.1 output:**
```
2018-01-25T12:33:37-07:00 DBG  [publish] Publish event: {
  "@timestamp": "2018-01-25T19:33:37.834Z",
  "@metadata": {
    "beat": "metricbeat",
    "type": "doc",
    "version": "6.1.1"
  },
  "metricset": {
    "module": "nginx",
    "name": "stubstatus",
    "host": "127.0.0.1",
    "rtt": 1245
  },
  "nginx": {
    "stubstatus": {
      "current": 0,
      "reading": 0,
      "hostname": "127.0.0.1",
      "active": 48,
      "waiting": 43,
      "dropped": 0,
      "accepts": 1461558,
      "handled": 1461558,
      "writing": 5,
      "requests": 4894122
    }
  },
  "tags": [
    "metricbeat"
  ],
  "beat": {
    "hostname": "website",
    "version": "6.1.1",
    "name": "production.website"
  }
}
```

Attempting to set the exported field does not seem to work.

```
2018-01-25T12:42:49-07:00 DBG  [memqueue] ackloop:  done send ack
2018-01-25T12:42:51-07:00 DBG  [publish] Publish event: {
  "@timestamp": "2018-01-25T19:42:51.499Z",
  "@metadata": {
    "beat": "metricbeat",
    "type": "doc",
    "version": "6.1.1"
  },
```

**Full config.** I have confirmed that logstash isn't doing any mangling, I can see the json flowing into my elastic cluster via tcpdump.

```
logging.level: debug
tags: ["metricbeat"]
type: "metricsets"
type: metricsets

metricbeat.modules:

- module: php_fpm
  metricsets: ["pool"]
  enabled: true
  period: 5s
  status_path: "/fpm-status"
  hosts: ["127.0.0.1"]

- module: nginx
  metricsets: ["stubstatus"]
  period: 5s
  hosts: ["http://127.0.0.1"]
  server_status_path: "nginx_status"

output.logstash:
  hosts: ["xxxxx", "xxxxxxx"]
  loadbalance: true
  index: "metricbeat-%{+yyyy.MM.dd}"
  ssl.certificate_authorities: ["/etc/metricbeat/root.crt"]
  ssl.certificate: "/etc/metricbeat/client.crt"
  ssl.key: "/etc/metricbeat/client.key"
  ssl.verification_mode: "none"
  port: 64002
  slow_start: true
  pipelining: 1
  workers: 1
  bulk_max_size: 100
```
