### ISSUE TITLE
Cant index FileBeats data through Logstash due to "source" field mapping problem with ES template

### ISSUE THREAD

**Issue by sempervictus** [elastic/beats#6206]
Beats, ES, LS, and Kibana 6.1.2 in use on ubuntu 14
Filebeat -> Logstash -> ES is failing with:
```
 "caused_by"=>{"type"=>"mapper_parsing_exception", "reason"=>"Mapping definition for [source] has unsupported parameters:  [properties : {outer_ipv6_location={type=geo_point}, port={ignore_above=1024, type=keyword}, stats={properties={net_bytes_total={type=long}, net_packets_total={type=long}}}, ipv6={ignore_above=1024, type=keyword}, ip={ignore_above=1024, type=keyword}, outer_ip={ignore_above=1024, type=keyword}, outer_ipv6={ignore_above=1024, type=keyword}, ip_location={type=geo_point}, ipv6_location={type=geo_point}, mac={ignore_above=1024, type=keyword}, outer_ip_location={type=geo_point}}]"}}}}}
```
The messages look like this:
```
{
    "prospector" => {
        "type" => "log"
    },
      "@version" => "1",
          "host" => "svl-elk00-local",
    "@timestamp" => 2018-01-28T08:08:45.333Z,
       "fileset" => {
          "name" => "auth",
        "module" => "system"
    },
       "message" => "Jan 28 08:08:45 ubuntu1404-64 su[1505]: pam_unix(su:session): session closed for user root",
        "offset" => 18061,
          "beat" => {
            "name" => "svl-elk00-local",
        "hostname" => "svl-elk00-local",
         "version" => "6.1.2"
    },
          "tags" => [
        [0] "beats_input_codec_plain_applied"
    ],
        "source" => "/var/log/auth.log"
}
```
The FB config is:
```
cat /etc/filebeat/filebeat.yml 
---
filebeat.config.modules.path: "${path.config}/modules.d/*.yml"
filebeat.config.modules.reload.enabled: false
filebeat.modules:
-   module: system
    syslog:
    -   enabled: true
    auth:
    -   enabled: false
filebeat.prospectors:
-   input_type: log
    paths:
    - "/var/log/*log"
    - "/var/log/dmesg"
    - "/var/log/secure"
    enabled: false
    fields_under_root: false
output.logstash:
    ssl.enabled: true
    ssl.verification_mode: none
    hosts: "127.0.0.1:9778"
```

Metricbeat on the same setup works, mostly, but kibana in those dashboards complains about
```
Saved "field" parameter is now invalid. Please select a new field.
Visualize: "field" is a required parameter
```
The ES templates were loaded via _filebeat setup --template_, also tried manually doing it by having FB export and pushing via curl (after setting everything up clean):
```
curl -s -XPUT -H 'Content-Type: application/json' localhost:9200/_template/filebeat-6.1.2 -d"$(  /usr/share/filebeat/bin/filebeat export template --path.config /etc/filebeat)"
```
All produce the same result - LS cant index filebeats data into ES.
Am i doing something very wrong, or is this a side effect of the push to try and have beats speak directly to ES? Exposing elasticsearch to every potential beats collector sounds about as safe as streaking through Kabul, and we use LS for a ton of other data types, so i'd like to figure out a way to keep running what appears to be (according to the docs) a supported data pipeline once we move to 6. Thanks.
