### ISSUE TITLE
Packetbeat:  cyclic reference detected for key: 'path.logs' 

### ISSUE THREAD

**Issue by ph** [elastic/beats#6214]
```json
{
  "level": "error",
  "timestamp": "2018-01-29T15:57:07.020-0500",
  "caller": "instance/beat.go:667",
  "message": "Exiting: error initializing publisher: cyclic reference detected for key: 'path.logs' accessing 'output.file.path' (source:'packetbeat.yml')"
}
```

```yaml
packetbeat.interfaces.device: en0

packetbeat.protocols:
- type: http
  ports: [80]

output.file:
  path: '${path.logs}'
  filename: output.json

logging:
  level: info
  json: true
  files:
    name: packetbeat.json
```
This same config works in 6.1.2.

Reported by @andrewkroh
