### ISSUE TITLE
Include process information per docker container

### ISSUE THREAD

**Issue by graphaelli** [elastic/beats#6223]
I'm interested in auditing the processes running within containers, mostly to find those running as root.  Would metricbeat be interested in extending the docker module to include that?  If so, would that live under the `container` metricset or on its own?  Any other guidance would be greatly appreciated.

**Comment by ruflin** [comment]
I wonder if this is a metricset or more a processor that adds meta data to the event. @andrewkroh might have some more thoughts here.

**Comment by andrewkroh** [comment]
> I'm interested in auditing the processes running within containers, mostly to find those running as root.

That are multiple ways of getting this information.

1. Use Metricbeat's system.process metricset with cgroup information enabled (which is on by default). This tells you about every process, gives the cgroup ID (which is the container ID), and tells you who the process is running as on the host.
1. Do everything from the previous and enable the `add_docker_metadata` process which can enrich events based on the cgroup ID or based on the [PID](https://github.com/elastic/beats/pull/6100). This will give you additional information about the container associated with the process.
1. Use Auditbeat to monitor execve syscalls and enable the `add_docker_metadata` processor with default config.
  ```
  # 6.2+ config example
  auditbeat.modules:
  - module: auditd
    audit_rules: |
      ## Executions.
      -a always,exit -F arch=b64 -S execve,execveat -k exec
    processors:
    - add_docker_metadata: ~
  ```
