### ISSUE TITLE
Metricbeat HTTP JSON doesn't seem to work with query string in the path parameter

### ISSUE THREAD

**Issue by mirosval** [elastic/beats#6276]
I'm on Metricbeat 6.1, when I try this configuration:

```yaml
- module: http
  metricsets: ["json"]
  period: 10s
  hosts: ["localhost:$SERVICE_ADMIN_PORT"]
  namespace: "finatra"
  path: "/admin/metrics.json?filtered=true"
```

I get the following in Kibana:

```
error.message |   | unexpected end of JSON input
```

However with this configuration it works:

```yaml
- module: http
  metricsets: ["json"]
  period: 10s
  hosts: ["localhost:$SERVICE_ADMIN_PORT"]
  namespace: "finatra"
  path: "/admin/metrics.json"
```

Judging from a quick look at the Metricbeat HTTP module implementation it seems that the query string should be constructed separately from the path, but this is not handled in the HTTP module, so I guess the `?` just gets escaped and then Finatra gets a wrong URL? In any case no query parameter is documented in the Metricbeat HTTP module documentation.
