### ISSUE TITLE
Xpack monitoring need better logging when credentials are invalid

### ISSUE THREAD

**Issue by kovyrin** [elastic/beats#6327]
Hello,

We at Swiftype have file beat deployed to ship logs to logstash. This means there is no elasticsearch output configured. Now we are trying to add xpack monitoring to filebeat and it doesn't seem to work in our configuration.

The logs don't have any error messages, the monitoring index in ES does not exist.

## Versions
* OS: CentOS 6
* Filebeat: 6.2.0
* Logstash: 6.2.0
* ES: 6.1.3

## Configuration file
```yaml
#================================ General =====================================

name: app01.dal05

#=========================== Filebeat prospectors =============================

filebeat.prospectors:
- type: log
  enabled: true
  json.message_key:
  json.keys_under_root: true
  json.overwrite_keys: true # get timestamp from the log, etc
  paths:
    - /u/apps/*/current/log/logstash/*.log

  fields:
    type: application

  tags: [ "app", "ruby", "index-in-logs-cluster" ]

#============================= Filebeat modules ===============================

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

#================================ Outputs =====================================

output.logstash:
  # The Logstash hosts
  hosts: [ "logstash01.dal05.swiftype.net:5044" ]

  # List of root certificates for HTTPS server verifications
  ssl.certificate_authorities: [ "/etc/pki/tls/certs/ca-bundle.crt" ]

  # Certificate for SSL client authentication
  ssl.certificate: "/etc/filebeat/ssl/logstash-dal05.crt"

  # Client Certificate Key
  ssl.key: "/etc/filebeat/ssl/logstash-dal05.key"

#================================ Logging =====================================

# Sets log level. The default log level is info.
# Available log levels are: error, warning, info, debug
logging.level: debug

# At debug level, you can selectively enable logging only for some components.
# To enable all selectors use ["*"]. Examples of other selectors are "beat",
# "publish", "service".
logging.selectors: [ "beat", "service" ]

#============================== Xpack Monitoring ===============================
# filebeat can export internal metrics to a central Elasticsearch monitoring
# cluster.  This requires xpack monitoring to be enabled in Elasticsearch.  The
# reporting is disabled by default.

# Set to true to enable the monitoring reporter.
xpack.monitoring.enabled: true

# Uncomment to send the metrics to Elasticsearch. Most settings from the
# Elasticsearch output are accepted here as well. Any setting that is not set is
# automatically inherited from the Elasticsearch output configuration, so if you
# have the Elasticsearch output configured, you can simply uncomment the
# following line.
xpack.monitoring.elasticsearch:
  hosts: [ "https://fde30f99ef8b4a8d97b30c04d2f2f047.ece.dal05.swiftype.net:9243" ]
  username: "beats-monitoring"
  password: "xxxxxxxxxx"
```

## ES User Info

The `beats-monitoring` user in ES is a new user with a `superuser` role attached to it (we've started with `logstash_system`, but eventually ended up here with no useful results.
