### ISSUE TITLE
Feedback when module configuration file is invalid

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#6366]
If there is an invalid metricbeat module config file (in the example below, the metricbeat.modules line is not necessary), metricbeat will read the configuration but will not throw any errors/warnings at runtime.

```
metricbeat.modules:
- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
```

All you get are (successful) messages related to loading of the docker.yml file, but it doesn't actually go start the Wrapper for the docker module to actually run it (silently fails the configuration).
