### ISSUE TITLE
Filebeat 6.2.1 in Kubernetes Segfaults

### ISSUE THREAD

**Issue by towolf** [elastic/beats#6372]
I was tailing the log of Filebeat because I saw that my Filebeat daemonset pods kept restarting.

This is the traceback:
```
2018-02-13T16:32:02.764Z	INFO	log/harvester.go:216	Harvester started for file: /var/lib/docker/containers/ab013b90ca95cb1a0d848ce537844044d7a05de434c1dd44199edcf36e99cb51/ab013b90ca95cb1a0d848ce537844044d7a05de434c1dd44199edcf36e99cb51-json.log
2018-02-13T16:32:02.764Z	ERROR	log/harvester.go:243	Read line error: decoding docker JSON: json: cannot unmarshal number into Go value of type reader.dockerLog; File: %!(EXTRA string=/var/lib/docker/containers/ab013b90ca95cb1a0d848ce537844044d7a05de434c1dd44199edcf36e99cb51/ab013b90ca95cb1a0d848ce537844044d7a05de434c1dd44199edcf36e99cb51-json.log)
2018-02-13T16:32:07.990Z	INFO	[monitoring]	log/log.go:124	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":21760,"time":21760},"total":{"ticks":187170,"time":187172,"value":187170},"user":{"ticks":165410,"time":165412}},"info":{"ephemeral_id":"a0c1894e-0350-4d21-9f37-2df11e200e28","uptime":{"ms":11221079}},"memstats":{"gc_next":10567776,"memory_alloc":6966536,"memory_total":14985033360}},"filebeat":{"events":{"active":-6,"added":84,"done":90},"harvester":{"closed":3,"open_files":4,"running":4,"started":3}},"libbeat":{"config":{"module":{"running":1}},"output":{"events":{"acked":84,"batches":14,"total":84},"read":{"bytes":84},"write":{"bytes":13896}},"pipeline":{"clients":2,"events":{"active":1,"filtered":6,"published":78,"total":84},"queue":{"acked":84}}},"registrar":{"states":{"current":38,"update":90},"writes":18},"system":{"load":{"1":0.07,"15":1.5,"5":0.89,"norm":{"1":0.0088,"15":0.1875,"5":0.1113}}}}}}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x158 pc=0x13dd6fa]

goroutine 49 [running]:
github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata.(*ContainerIndexer).GetIndexes(0xc420428080, 0x0, 0xc42041d710, 0xc420436960, 0xc420436960)
	/go/src/github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata/indexers.go:161 +0x3a
github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata.(*Indexers).GetIndexes(0xc42041d710, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata/indexers.go:76 +0x230
github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata.(*kubernetesAnnotator).removePod(0xc4201e2070, 0x0)
	/go/src/github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata/kubernetes.go:188 +0x3d
github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata.(*kubernetesAnnotator).(github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata.removePod)-fm(0x0)
	/go/src/github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata/kubernetes.go:159 +0x34
github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata.processEvent(0xc420469ed0, 0xc4201154d0)
	/go/src/github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata/kubernetes.go:175 +0x78
github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata.(*kubernetesAnnotator).worker(0xc4201e2070)
	/go/src/github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata/kubernetes.go:159 +0x26f
created by github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata.newKubernetesAnnotator
	/go/src/github.com/elastic/beats/libbeat/processors/add_kubernetes_metadata/kubernetes.go:113 +0x9f7
```

For confirmed bugs, please report:
- Version: 

`docker.elastic.co/beats/filebeat:6.2.1`

- Operating System: 

Kubernetes 1.9.1 on amd64

- Steps to Reproduce: 

Not sure

**Comment by towolf** [comment]
My config:
```
apiVersion: v1
items:
- apiVersion: v1
  data:
    filebeat.yml: |-
      filebeat.config:
        prospectors:
          # Mounted `filebeat-prospectors` configmap:
          path: ${path.config}/prospectors.d/*.yml
          # Reload prospectors configs as they change:
          reload.enabled: false
        modules:
          path: ${path.config}/modules.d/*.yml
          # Reload module configs as they change:
          reload.enabled: false

      fields_under_root: true

      processors:

      output.logstash:
        enabled: true
        hosts: ["loghost.kube-system.svc:5000"]
        timeout: 15

      # output.console:
      #   enabled: true
      #   pretty: true
```

and

```
- apiVersion: v1
  data:
    kubernetes.yml: |-
      - type: docker
        containers.ids:
        - "*"
        fields:
          cluster: k8s-aix01
        processors:
          - add_kubernetes_metadata:
              in_cluster: true
          - decode_json_fields:
              fields: ["message"]
              process_array: false
              max_depth: 1
              target: ""
              overwrite_keys: false
```
