### ISSUE TITLE
Mapping error with Docker Swarm labels

### ISSUE THREAD

**Issue by exekias** [elastic/beats#6421]
Both when using `add_docker_metadata` and Docker autodiscover provider with Docker Swarm, in some cases we see mapping issues due to this labels set:

```
  "com.docker.swarm.task": "",
  "com.docker.swarm.task.id": "xxxxx",
  "com.docker.swarm.task.name": "xxxxx"
```

We should offer a way to "dedot" label names, or have an alternative way to detect the situation and avoid mapping errors.

Reference in discuss: https://discuss.elastic.co/t/using-autodiscover-feature-for-docker-does-not-work-when-running-in-swarm-mode/120342

Current workaround is to use `drop_field` processor like this:

```
processors:
  - drop_fields:
      fields:
        - "docker.containers.labels.com.docker.swarm.task"
```
