### ISSUE TITLE
auditbeat auditd failure receiving events

### ISSUE THREAD

**Issue by gwsales** [elastic/beats#6477]
Still getting an error when starting auditbeat with default settings:

Closed issue:    #6091 

`2018-02-26T12:40:42.736-0600    ERROR   [auditd]        auditd/audit_linux.go:110       Failure receiving audit events  {"error": "failed to set audit PID. An audit process is already running (PID 670)"}`

```
auditbeat.modules:

- module: auditd
  audit_rules: |
    -a always,exit -F arch=b64 -S execve,execveat -k exec
```

**Comment by gwsales** [comment]
```/usr/share/auditbeat/bin/auditbeat version
auditbeat version 6.2.2 (amd64), libbeat 6.2.2
```

Config: 
Note: Removed unused sections and most comments, I'll upload the whole file if needed, but it's just defaults with some things disabled.
```


#==========================  Modules configuration =============================
auditbeat.modules:

- module: auditd
  audit_rules: |

    ## Executions.
    -a always,exit -F arch=b64 -S execve,execveat -k exec

#================================ Outputs =====================================

#------------------------------- File output -----------------------------------
output.file:
  # Boolean flag to enable or disable the output module.
  enabled: true

  # Path to the directory where to save the generated files. The option is
  # mandatory.
  path: "/var/log/auditbeat"

  # Name of the generated files. The default is `beatname` and it generates
  # files: `beatname`, `beatname.1`, `beatname.2`, etc.
  filename: output.json

  # Maximum size in kilobytes of each file. When this size is reached, and on
  # every beatname restart, the files are rotated. The default value is 10240
  # kB.
  rotate_every_kb: 10000

  # Maximum number of files under path. When this number of files is reached,
  # the oldest file is deleted and the rest are shifted from last to first. The
  # default is 7 files.
  number_of_files: 7

  # Permissions to use for file creation. The default is 0600.
  permissions: 0600
```

**Comment by andrewkroh** [comment]
> An audit process is already running (PID 670)

You need to stop the other audit process (which has PID 670) before Auditbeat can take control of the unicast audit socket. See https://www.elastic.co/guide/en/beats/auditbeat/current/auditbeat-module-auditd.html for some more details.

**Comment by gwsales** [comment]
Looking through the docs I missed the kernel version with multicast as an option. 

```
2018-02-27T10:22:58.493-0600    INFO    [auditd]        auditd/audit_linux.go:65        auditd module is running as euid=0 on kernel=3.10.0-693.17.1.el7.x86_64
2018-02-27T10:22:58.494-0600    ERROR   [auditd]        auditd/audit_linux.go:634       socket_type is set to multicast but based on the kernel version, multicast audit subscriptions are not supported. Remove the socket_type option to have auditbeat select the most suitable subscription method.
2018-02-27T10:22:58.496-0600    ERROR   instance/beat.go:667    Exiting: 1 error: 1 error: failed to create audit client: multicast socket_type not available
```

Is there a way to read the auditd logs and do the translations for uid's and json output like auditbeats? I haven't seen anything in filebeats that looks like it would be able to do this. I unfortunately need to run auditd for compliance and wanted to run auditbeats to get critical events in a better parsed format for the security teams.

**Comment by andrewkroh** [comment]
> Is there a way to read the auditd logs and do the translations for uid's and json output like auditbeats? 

No, Auditbeat is not able to read log files. Though I do think having an option in Filebeat to process those auditd logs using the same code that Auditbeat uses would be nice to have. It would be like running `sudo cat /var/log/audit/audit.log | auparse -format=json -i` where `auparse` is the tool from our [go-libaudit](https://github.com/elastic/go-libaudit#installation-and-usage) library.

> I unfortunately need to run auditd for compliance and wanted to run auditbeats to get critical events in a better parsed format for the security teams.

You could let Auditbeat be your primary user-space audit daemon and stop auditd. You would need to copy over your existing auditd rules into the auditbeat.yml config file so that it can manage the installation of the same ruleset.

**Comment by gwsales** [comment]
Thanks for the info, how would I go about requesting that auditd log enhancement to filebeat?

**Comment by andrewkroh** [comment]
You can open a new issue in this repo for the feature request. I think what we need is a auditd [prospector type](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#_literal_type_literal) in Filebeat that uses go-libaudit to do the parsing/enriching.

We have an auditd module in Filebeat, but it's not as powerful as what we have in go-libaudit. It simply parses individual auditd lines, but does not group related messages or enrich the data.

**Comment by mdnfiras** [comment]
we encountered this in version 7.16.1 on GKE
based on [this comment](https://github.com/elastic/beats/issues/8523#issuecomment-451064990) we were able to work around this by adding the following init container to auditbeat daemonset:
```yaml
      initContainers:
      - name: systemctl
        image: centos:7.9.2009
        command:
        - /bin/sh
        - "-c"
        - |
          systemctl stop systemd-journald-audit.socket
          systemctl mask systemd-journald-audit.socket
          systemctl restart systemd-journald
          exit $?
        env:
          - name: SYSTEMD_IGNORE_CHROOT
            value: "1"
        securityContext:
          runAsUser: 0
          capabilities:
            add:
              - 'SYS_ADMIN'
        resources:
          limits:
            cpu: 10m
            memory: 10Mi
          requests:
            cpu: 5m
            memory: 8Mi
        volumeMounts:
          - name: run
            mountPath: /run
```
and the volume:
```yaml
      volumes:
      - name: run
        hostPath:
          path: /run
```
