### ISSUE TITLE
Default filebeat.yml should include output.elasticsearch.index

### ISSUE THREAD

**Issue by cawoodm** [elastic/beats#6495]
It's always mystified me why the default filebeat.yml includes so many commented out options most people will never need but the one option everyone needs is not there at all: output.elasticsearch.index

```yml
output.elasticsearch:
  hosts: ["localhost:9200"]
  index: "myindex"
```

Must be an oversight but it's a real stumbling block when starting with FileBeats.
