### ISSUE TITLE
Generated Beats based on Metricbeat don't support "test config"

### ISSUE THREAD

**Issue by martinhynar** [elastic/beats#6550]
I have fork of metricbeat with my custom module and I need to run it on latest OEL 6 where init.d is still in use. After packing my custombeat into rpm and installing it on target machine I see that beat service remains in foreground and after CTRL+C it, the service is actually started.

From init.d script I can see that there is `test` fired before actual service is started. This test is the one that keeps running and holds terminal.
My configuration is not using remote output, only file. See bellow. Still, the test config is not finishing.

```
logging:
  level: info
  metrics:
    enabled: false
  to_syslog: true

output:
  file:
      path: "/tmp"
      filename: metricbeat
```

Same package and same configuration installed on OEL 7 with systemd starts just fine.

For confirmed bugs, please report:
- Version: Using beats tag 6.2.2
- Operating System: OEL 6.9
