### ISSUE TITLE
filebeat output to kafka failed

### ISSUE THREAD

**Issue by yayuntian** [elastic/beats#6575]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version:  filebeat version 6.2.2 (amd64), libbeat 6.2.2
- Operating System:  Docker container  Alpine Linux 3.6
- Steps to Reproduce: 

prospectors file
```
- type: log
  enabled: true
  paths:
      - /host/data/docker/containers/35bce9b62edbe914bbd5eeb0b4048608596e8f664ddb8650bfab7102d6f5ac40/35bce9b62edbe914bbd5eeb0b4048608596e8f664ddb8650bfab7102d6f5ac40-json.log*
  scan_frequency: 10s

  multiline.pattern: '^[[:space:]]'
  multiline.negate: false
  multiline.match: after

  json.keys_under_root: true
  json.message_key: message

 #fields_under_root: true
  fields:

      topic: frontend
      docker_container: ycs_frontend.1.2ufegsozyzuwl2l9ozlxn9sl9
      docker_node: z30pauq4b2qnm122ipbxx1w49
      docker_service: ycs_frontend
      docker_service_id: mlndoqme12skvcwuzix8on2d9
      docker_stack: ycs
      docker_task: ycs_frontend.1.2ufegsozyzuwl2l9ozlxn9sl9

  tail_files: false
  close_inactive: 2h
  close_eof: false
  close_removed: true
  clean_removed: true
  close_renamed: false
```

filebeat.yml config

```
/etc/filebeat # cat filebeat.yml 
path.config: /etc/filebeat
path.logs: /var/log/filebeat
path.data: /var/lib/filebeat/data
filebeat.registry_file: /var/lib/filebeat/registry
filebeat.shutdown_timeout: 0
logging.level: info
logging.metrics.enabled: true

setup.template.name: "ycs-log"
setup.template.pattern: "ycs-log-*"
filebeat.config.prospectors:
    enabled: true
    path: /etc/filebeat/prospectors.d/*.yml
    reload.enabled: true
    reload.period: 10s

output.kafka:
    hosts: ["192.168.1.103:9092"]
    topic: '%{[fields.topic]}'
```

when add `fields_under_root: true` then can't output to kafka , not found topic  frontend。but remove it，so i see topic in kafka。 not any error or warning logs in /var/log/filebeat/filebeat
