### ISSUE TITLE
Filebeat reload not working

### ISSUE THREAD

**Issue by cawoodm** [elastic/beats#6578]
Filebeat 6.2.2 Windows 2012 Server.

When testing changes in filebeat we often leave the live filebeat running and run a new filebeat "dev" process (with corresponding dev logstash instance on a different port). We then run filebeat dev pointing to logstash dev as follows:

```
filebeat.exe -c filebeat.dev.yml -e
```
However, in this constellation, Filebeat is not recognizing changes to it's config (filebeat.dev.yml) while running and reloading it.

filebeat.dev.yml:
```
filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - D:\tmp\log\access*.log

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false
  reload.period: 3s

output.logstash:
  hosts: ["localhost:5045"]

```

To be precise, when we change the path of the prospector and wait 3s or more, it does not pick up that there was a change and start parsing the files.

**Comment by ruflin** [comment]
Reloading only works for the paths defined under `filebeat.config.*`. The base `filebeat.yml` will never be reloaded. Is that what you are asking for?

**Comment by cawoodm** [comment]
Yeah... perhaps I'm confused. FileBeat ships without a config/ subdirectory and I therefore never used one but have my filebeat.yml next to my filebeat.exe.

Looking in filebeat.xml I see the following:

```
filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false
  reload.period: 3s
```

Are you saying I just need to change this line?
```
path: ./*.yml
```

What exactly does `${path.config}` mean and where is it defined?
