### ISSUE TITLE
[Metricbeat] Grouping Windows Perfmon Metrics in Events

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#6584]
The perfmon metricset generates one event per counter instance. It would be nice to offer more flexibility in grouping related metrics into a single event.

Having a single event per metric was the simplest implementation that would allow similar metrics to be grouped and visualized (e.g. visualize disk write times for each disk instance on the same graph).

It would be nice to be able to group all metrics related to an instance of an object (e.g. all metrics for C:\ or all metrics for processor 0). Here are some examples that show my idea.

```yaml
metricbeat.modules:
- module: windows
  metricsets: [perfmon]
  perfmon.queries:
  - object: '\Processor'
    namespace: processor
    instance: *
    counters:
    - name: '% User Time'
      label: time.user.pct
    - name: '% Processor Time'
      label: time.processor.pct
    - name: '% Interrupt Time'
      label: time.interrupt.pct

  - object: '\UDPv4'
    namespace: udpv4
    counters:
    - name: 'Datagrams Received/sec'
      label: packets.received.per_sec
    - name: 'Datagrams Received Errors'
      label: packets.received.errors
    - name: 'Datagrams No Port/sec'
      label: packets.received.no_port_per_sec
    - name: 'Datagrams Sent/sec'
      label: packets.sent.per_sec
    - name: 'Datagrams/sec'
      label: packets.per_sec
```

The first query uses a Performance Data Helper (PDH) path of `\Processor(*)\<counter name>`. And would produce an event like

```json
{
  "windows": {
    "perfmon": {
      "processor": {
        "instance": "_Total",
        "time": {
          "user": {
            "pct": 1.2
          },
          "processor": {
            "pct": 10.1
          },
          "interrupt": {
            "pct": 0.5
          }
        }
      }
    }
  }
}
```

The second query uses a PDH path of `\UDPv4\<counter name>` (it has no instance) and produces an event like

```json
{
  "windows": {
    "perfmon": {
      "udpv4": {
        "packets": {
          "received": {
            "per_sec": 18,
            "errors": 1,
            "no_port_per_sec": 11
          },
          "sent": {
            "per_sec": 12
          },
          "per_sec": 32
        }
      }
    }
  }
}
```

This would also resolve #6528.

#### Related Info

- Working with Performance Counters: https://technet.microsoft.com/en-us/library/bb734903.aspx?f=255&MSPPError=-2147217396

**Comment by ruflin** [comment]
I really like this idea that we allow the user to build his own events. Reminds me also of https://github.com/elastic/beats/pull/6462 where this could also be a potential solution (@jsoriano ).

**Comment by andrewkroh** [comment]
Related #4944.

**Comment by willemdh** [comment]
We'd love to see this functionality. The way the perfmon module works atm is not very efficient and generates a huge amount of documents with very little information. For example try gather some diskio related counters:

```
    - instance_label: "diskio.name"
      measurement_label: "diskio.writes"
      query: '\LogicalDisk(*)\Disk Writes/sec'
      format: "long"
    - instance_label: "diskio.name"
      measurement_label: "diskio.write.time.pct"
      query: '\LogicalDisk(*)\% Disk Write Time'
    - instance_label: "diskio.name"
      measurement_label: "diskio.bytesperwrite.avg"
      query: '\LogicalDisk(*)\Avg. Disk Bytes/Write'
      format: "long"
```

Please note this is only a subset of all counters that would be required to get a total view of diskio on WIndows servers. But seeing as the diskio system metricset for Windows, which is based on WMI is not very good at all, we are kind of forced to use the perfmon metricset, which is also not very usable on a larger scale.. See also https://github.com/elastic/beats/issues/3798

Imho diskio is one of the most important metricsets and should get some extra attention from Elastic asap, as at the moment the quality of the options we have (for Windows) is not up to the same standard as several free alternative monitoring solutions..

**Comment by willemdh** [comment]
@ruflin @andrewkroh 

Just wanted to add that I have a feeling that the millions of documents the perfmon module is generating results in very slow recovery of metricbeat indices. I added the diskio metrics from my previous post on +- 600 servers and have seen a significant detoriation of performance during recovery. (it could of course be related to other things in my cluster, but still wanted to mention this, maybe other customers are seeing the same)

**Comment by martinscholz83** [comment]
Hey @andrewkroh, is someone working on this topic?

**Comment by ruflin** [comment]
AFAIK nobody is working on it at the moment.

**Comment by martinscholz83** [comment]
Ok. I like the idea to group events in a namespace. If ok then i would open a PR.

**Comment by ruflin** [comment]
Of course, that would be great.

**Comment by martinscholz83** [comment]
@andrewkroh, if you want to collect for multiple instances you want to do it this way?
```
metricbeat.modules:
- module: windows
  metricsets: [perfmon]
  perfmon.queries:
  - object: '\Processor'
    namespace: processor
    - instance: 0
      counters:
      - name: '% User Time'
        label: time.user.pct      
      - name: '% Interrupt Time'
        label: time.interrupt.pct
    - instance: 1
      counters:
      - name: '% Processor Time'
        label: time.processor.pct

  - object: '\UDPv4'
    namespace: udpv4
    counters:
    - name: 'Datagrams Received/sec'
      label: packets.received.per_sec
    - name: 'Datagrams Received Errors'
      label: packets.received.errors
    - name: 'Datagrams No Port/sec'
      label: packets.received.no_port_per_sec
    - name: 'Datagrams Sent/sec'
      label: packets.sent.per_sec
    - name: 'Datagrams/sec'
      label: packets.per_sec
```

**Comment by willemdh** [comment]
Maybe while this is being rewritten, we should consider a perfmon ecs object? It would be nice if there is some sort of convention for perfmon data, so that everyone is using the same field names?

**Comment by ruflin** [comment]
@willemdh Not sure if ECS should have something specific to perfmon. Perfmon can use ECS fields but there are lots of metrics which I would not expect to be in ECS in perfmon. This is not only related to perfmon but metrics in general.

**Comment by andrewkroh** [comment]
> @andrewkroh, if you want to collect for multiple instances you want to do it this way?

To avoid duplication of the `counters` configuration I think `instance` should be able to accept a single string or a list.

```
metricbeat.modules:
- module: windows
  metricsets: [perfmon]
  perfmon.queries:
  - object: '\Processor'
    namespace: processor
    - instance: [0, 1]       # Allow both a string or []string.
      counters:
      - name: '% User Time'
        label: time.user.pct      
      - name: '% Interrupt Time'
        label: time.interrupt.pct
```
