### ISSUE TITLE
filebeats truncates log messages after 16k

### ISSUE THREAD

**Issue by bitsofinfo** [elastic/beats#6605]
```
# filebeat 6.2.2
filebeat.prospectors:
-
  paths: [ "/var/lib/docker/containers/*/*-json.log" ]
  harvester_buffer_size: 65536
  json.message_key: log
  json.keys_under_root: true
  json.add_error_key: true
  fields_under_root: true
  processors:
    - add_docker_metadata: ~

harvester_buffer_size: 65536

output.file:
  path: "/tmp/filebeat"
  filename: filebeat
```

- The docker container outputs a single line in valid json (about 18k)
- The value of the "log" message key is also a single line in valid json
- The message seems to be cut off at about 16k or a bit above (depends if you count the backslashes for escaping)
- A second message gets created with the remaining part of the message including full decoration (docker meta data, additional fields etc)
- Looks like filebeat splits the message into 2 separate ones
- harvester_buffer_size has no effect
- removing the json.* options has no effect

**How to reproduce:**

use my config, start a container and run the following:

```
#!/bin/bash
key="somerandomkey_"
value="somerandomvalue_"
echo -n '{'
for i in $(seq 420); do
  echo -n "\"${key}${i}\":\"${value}${i}\","
done
echo '"lastkey":"end"}'
```

This produces a valid json output. For me it cuts off at "somerand" and a new message continues with "omkey_396".

We also tried the following and it does not fix the issue: (as well as with and without the `harvester_buffer_size` option.)

```
filebeat.prospectors:
- type: docker
  containers.ids:
    - "*"
  processors:
    - add_docker_metadata: ~
```

@paltryeffort https://discuss.elastic.co/t/filebeat-splits-message-after-16k/123718/4
