### ISSUE TITLE
[Heartbeat] Crashing on concurrent map write

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#6616]
Heartbeat is crashing after ~20 minutes with fatal map errors ("concurrent map writes" or "concurrent map iteration and map write").

For confirmed bugs, please report:
- Version: 6.1.3
- Operating System: RHEL7 x86_64
- Discuss: https://discuss.elastic.co/t/heartbeat-fatal-error-concurrent-map-iteration-and-map-write/124716
- Stack Trace: See Discuss.
- Steps to Reproduce: Using the config below, the user is observing crashes periodically (like every 20 minutes).

```
heartbeat.monitors:

- type: tcp
  hosts: ["s1234", "s1234", "s1234", "s1234", "s1234", "s1234"]
  ports: [5555,9000]
  schedule: '@every 180s'
  timeout: 30s

- type: tcp
  hosts: ["s1234", "s12345"]
  ports: [12503]
  schedule: '@every 180s'
  timeout: 30s

#================================ General =====================================
# The name of the shipper that publishes the network data. It can be used to group
hostname: smonitor

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["localhost:5045"]
```
