### ISSUE TITLE
Variable extrapolation in configuration doesn't work in sub config.

### ISSUE THREAD

**Issue by ph** [elastic/beats#6660]
orignally reported in discuss at: https://discuss.elastic.co/t/environment-variables-not-replaced-in-external-configuration-file/124690

- Version:  6.3.0 and 6.2.2
- Operating System: 
- Steps to Reproduce: 

Make theses changes to you YAML configuration
```yaml
# filebeat.yml
custom.testing: ${CUSTOM_TESTING_ENV}
 filebeat.config.prospectors:
      enabled: true
     path: test.yml
```

```yaml
# test.yml
- type: log
  enabled: true
  paths:
    - "/tmp/${custom.testing}"

```

**Results into:** Exiting: missing field accessing '0.paths.0'

Same problem if you using an environment variable directly in the sub configuration it won't get replaced.
