### ISSUE TITLE
Filebeat autodiscover should not stop docker prospectors until it reads all lines

### ISSUE THREAD

**Issue by vbohata** [elastic/beats#6694]
I am using filebeat with autodiscover feature to read docker logs. When I stop and remove docker container, the prospector stops so it does not process latest logs from the container. I think it should reflect close_removed, so in case docker json log is missing it should still process remaining lines from its opened file descriptor. I am using filebeat 6.2.3.

So when autodiscover closes the prospector, it should check 2 conditions:
 1. Does docker container exists?
 2. Are all opened log files for this prospector already read?

```
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            and:
              - regexp:
                  docker.container.name: "^somename-.+"
              - not:
                  equals:
                    docker.container.id: "d2b3a6101c8f4644449cfcbc31f3057080e186bdbe7aad6a8d2a0982234bb852"
          config:
            - type: docker
              containers:
                ids:
                  - "${data.docker.container.id}"
                path: "/var/lib/docker/containers"
              close_inactive: 1h
              close_removed: false
              clean_removed: false
```
