### ISSUE TITLE
Auditbeat // Windows // File Integrity // recursive: true doesn't work

### ISSUE THREAD

**Issue by omarix** [elastic/beats#6796]
Hi, 
Could you help me to solve an issue I faced when turning recursive mode to true, the auditbeat does not report any event.

Version: auditbeat 6.2.3
OS: win10 32bit

Here the config:
```
auditbeat.modules:


- module: file_integrity
  paths:
  - C:/windows
  - C:/windows/system32
  - C:/Program Files
  - C:/Users
  recursive: true
  hash_types: [sha256]
```
Thanks in advance
