### ISSUE TITLE
[packetbeat] postgresql module failing at catching all queries

### ISSUE THREAD

**Issue by philippkahr** [elastic/beats#6850]
Hallo,

I already opened up a ticket on the elastic forum, sadly no one answered me there. I am currently using packetbeat 6.2.3 and I have this bug that it won't catch all queries send to the pqsql server.

Basically, my pqsql server writes about 250.000 lines per second into a log file. The packetbeat module with pqsql is only able to catch a few 100 lines per second. The pqsql server is running on localhost also all queries are sent to this server from localhost, so everything should be visible to packetbeat. 

Any idea how I can further debug this, so I can give you more information?

When running packetbeat with verbose output activated I do not see any `errors / warnings` except for those.: 

> 2018-04-11T08:28:20.572+0200	WARN	pgsql/parse.go:501	Pgsql parser expected data message, but received command of type 110
> 2018-04-11T08:28:30.193+0200	ERROR	pgsql/parse.go:531	Pgsql invalid column_length=4294967295, buffer_length=13, i=8
> 2018-04-11T08:28:30.262+0200	ERROR	pgsql/parse.go:531	Pgsql invalid column_length=4294967295, buffer_length=28, i=8
> 2018-04-11T08:28:32.742+0200	ERROR	pgsql/parse.go:531	Pgsql invalid column_length=4294967295, buffer_length=138, i=3
> 2018-04-11T08:28:33.424+0200	WARN	pgsql/parse.go:501	Pgsql parser expected data message, but received command of type 110
> 2018-04-11T08:28:33.425+0200	WARN	pgsql/parse.go:501	Pgsql parser expected data message, but received command of type 110
> 2018-04-11T08:28:34.192+0200	ERROR	pgsql/parse.go:531	Pgsql invalid column_length=4294967295, buffer_length=150, i=3
> 2018-04-11T08:28:36.205+0200	WARN	pgsql/parse.go:501	Pgsql parser expected data message, but received command of type 110
> 2018-04-11T08:28:39.486+0200	ERROR	pgsql/parse.go:531	Pgsql invalid column_length=4294967295, buffer_length=22, i=4
> 2018-04-11T08:28:39.488+0200	ERROR	pgsql/parse.go:531	Pgsql invalid column_length=4294967295, buffer_length=60, i=4
> 2018-04-11T08:28:39.491+0200	ERROR	pgsql/parse.go:531	Pgsql invalid column_length=4294967295, buffer_length=60, i=4
> 2018-04-11T08:28:39.492+0200	ERROR	pgsql/parse.go:531	Pgsql invalid column_length=4294967295, buffer_length=60, i=4

Here is my packetbeat config.

```
packetbeat.flows:
  period: 10s
  timeout: 30s
packetbeat.interfaces.device: any
packetbeat.protocols.dns:
  include_additionals: true
  include_authorities: true
  ports:
  - 53
packetbeat.protocols.http:
  ports:
  - 80
  - 8080
  - 8000
  - 5000
  - 8002
packetbeat.protocols.icmp:
  enabled: true
packetbeat.protocols.pgsql:
  ports:
  - 5432
packetbeat.protocols.tls:
  ports:
  - 8443
  - 443
setup.kibana:
  host: http://IPOFKIBANA:5601
setup.template.settings:
  index.number_of_shards: 1
logging.to_files: false
output.elasticsearch:
  hosts:
  - IPOFELASTIC:9200
```

For confirmed bugs, please report:
- Version: 6.2.3
- Operating System: Debian 9
- Steps to Reproduce: 

fyi: https://discuss.elastic.co/t/packetbeat-postgresql/127577

EDIT 1.:) just some visual stuff and typos.
