### ISSUE TITLE
Cannot Load Dashboards

### ISSUE THREAD

**Issue by mmethe** [elastic/beats#6922]
Windows 2008 R2 winlogbeat 6.2.4 installed.

winlogbeat.yml:
```
winlogbeat.event_logs:
  - name: Application
  - name: Security
  - name: System

output.logstash:
  hosts: ["brt1-elk02:5044"]
  
tags: ["dc"]

setup.kibana:
host: "brt1-elk02"
username: "elastic"
password: "********"

setup.dashboards.enabled: true
setup.dashboards.always_kibana: true
setup.dashboards.url: http://brt1-elk02
```
ELK 6.2.4 on centos 7. Kibana behind nginx.  nginx listens on 80 and forwards to 5601.  This works fine, except for below issue.

Issue:
When I run 'winlogbeat.exe setup --dashboards' I get:
```
PS C:\Program Files\winlogbeat> .\winlogbeat.exe setup --dashboards
Exiting: Error importing Kibana dashboards: fail to create the Kibana loader: Error creating Kibana client: fail to get
the Kibana version:HTTP GET request to /api/status fails: fail to execute the HTTP GET request: Get http://localhost:560
1/api/status: dial tcp [::1]:5601: connectex: No connection could be made because the target machine actively refused it
.. Response: .
```
