### ISSUE TITLE
setup.dashboard.index should respect `elasticsearch.output.index`

### ISSUE THREAD

**Issue by jordansissel** [elastic/beats#6926]
Tested on auditbeat 6.2.4

When setting `elasticsearch.output.index`, the default `setup.dashboard.index` pattern that gets used is still `auditbeat-*`.

Here's the scenario I went through:

When changing the index name:

```
output.elasticsearch:
  index: "foo"
```

Beats setup will tell me:

> Exiting: setup.template.name and setup.template.pattern have to be set if index name is modified.

So I follow the instructions:

```
setup:
  template.name: "auditbeat"
  template.pattern: "*-auditbeat-*"
```

Then run setup again:

```
# auditbeat setup -c /tmp/auditbeat.yml -e
...
2018-04-23T23:10:09.706Z        INFO    instance/beat.go:583    Kibana dashboards successfully loaded.
```

However, when viewing the dashboards, all the dashboards/visuals appear to point at `auditbeat-*` instead of my configured `*-auditbeat-*`.

To work around this, I added:

```
setup:
  template.name: "auditbeat"
  template.pattern: "*-auditbeat-*"
  template.enabled: true
  dashboards.index: "*-auditbeat-*"   # this is required.
```
