### ISSUE TITLE
Changing the kibana index pattern doesn't work for TSVB visualisations

### ISSUE THREAD

**Issue by tsg** [elastic/beats#6935]
As discovered by @jordansissel, the `setup.dashboards.index` option, which can be used to adjust the index pattern in the dashboards that we create, doesn't apply to TSVB visualisations.

We have code to replace the index pattern in searches, but I don't see anything specific to TSVB.

To reproduce:

* auditbeat.yml:

```
setup:
  template.name: "auditbeat"
  template.pattern: "*-auditbeat-*"
  template.enabled: true
  dashboards.index: "*-auditbeat-*"
```

* Run: `auditbeat setup -c /tmp/auditbeat.yml -e`

* Check the Panel Options of a TSVB vis:

![image 2](https://user-images.githubusercontent.com/101817/39212301-9d3e6c36-480e-11e8-8e84-9dfe472f9cae.png)
