### ISSUE TITLE
File Output for beats

### ISSUE THREAD

**Issue by StevieSun** [elastic/beats#6952]
When using the file output for metricbeat/heartbeat, running on Windows 10,  the actual write happens only when I manually open the file (to view it) or stop metricbeat/heartbeat itself. The file size is always 0kb untill then.

Example:
For the below config
```
heartbeat.monitors:
- type: http
  urls: ["sample.url"]
  schedule: '@every 10s'
output.file:
  path: D:\ELK\heatbeat_output
  filename: heartbeat
```
   
In Linux i can validate that the write happens every 10s. But in Windows, the write doesn't happen every 10s.
Not sure if it is the Windows OS which is trying to write in batches or beats itself is doing it. 

Is there a way to fix this. 
Any help is appreciated. Thanks!
