### ISSUE TITLE
Filebeat docker log enrichment& forwarding docker ee 17.06.2-ee-8

### ISSUE THREAD

**Issue by SbiCA** [elastic/beats#6989]
For confirmed bugs, please report:
- Version: 6.2.4
- Operating System: Windows Server 2016 Version 1607 (OS Build 14393.2068) 

- Steps to Reproduce:

1.  Install filebeat on docker host (windows server)
2. adjust beat configuration 
```yml
output.logstash:
  hosts: ["logstash:5044"]
filebeat.prospectors:
- type: log
  paths:
    - C:/ProgramData/docker/containers/*/*.log
  json.message_key: log
  json.keys_under_root: true
  processors:
  - add_docker_metadata:
      host: "tcp://172.30.128.1:2375"       
  document_type: log
  fields_under_root: true
  fields:
    environment: docker
    type: docker
```
3. Start filebeat service

**Expected result:**
Filebeat sends enriched docker logs to logstash configured.

**Actual result:**
2018-05-02T14:21:48.735+0200   ERROR  instance/beat.go:667      Exiting: Error in initing prospector: Error response from daemon: client version 1.22 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version
