### ISSUE TITLE
Debug logging on per prospector configuration that is being used by filebeat

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#7066]
yaml files are sensitive to indentations.  Sometimes users end up putting a prospector configuration at the end (after all the type: log blocks), thinking that it will get applied to all prospectors.

Using max_bytes as an example, in this case:

```
- type: log
  paths:
    - <some_path>
  ...
  ...
  multiline.timeout: 60s

- type: log
  paths:
    - <some_path_2>
  ...
  ...
  multiline.timeout: 60s
  
  # Exclude lines. A list of regular expressions to match. It drops the lines that are
  # matching any regular expression from the list.
  #exclude_lines: ['^DBG']

  # Include lines. A list of regular expressions to match. It exports the lines that are
  # matching any regular expression from the list.
  #include_lines: ['^ERR', '^WARN']

  # Exclude files. A list of regular expressions to match. Filebeat drops the files that
  # are matching any regular expression from the list. By default, no files are dropped.
  #exclude_files: ['.gz$']

  # Optional additional fields. These fields can be freely picked
  # to add additional information to the crawled log files for filtering
  #fields:
  #  level: debug
  #  review: 1

  # Maximum number of bytes a single log event can have
  # All bytes after max_bytes are discarded and not sent. The default is 10MB.
  # This is especially useful for multiline log messages which can get large.
  max_bytes: 20971520
```

Where max_bytes is listed all the way down after a bunch of comments.  But in reality, because of the 2 spaces before max_bytes, the setting ends up being picked up by the last input.

It will be helpful from a troubleshooting point of view if filebeat can write out the per prospector configurations that it ends up using at the debug logging level.  This way, it is easy to tell which options each prospector is using.  `filebeat export config` only shows how it is interpreting the configuration passed to filebeat, not the actual configuration options that it is using in realtime.
