### ISSUE TITLE
The "add_kubernetes_metadata" processor can't get meta when the pod use hostNetwork

### ISSUE THREAD

**Issue by lastboy1228** [elastic/beats#7070]
- Version: 
  filebeat:6.2.4
  kubernetes:1.9.6

Filebeat also can't  attach meta data to logs of those pods with "hostPort" specified.
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-prospectors
  namespace: kube-system
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  kubernetes.yml: |-
    - type: log
      paths:
        - /var/lib/docker/containers/*/*.log
      tail_files: true
      stream: all
      fields_under_root: true
      fields:
        type: kubernetes
      json:
        keys_under_root: true
        message_key: log
        add_error_key: true
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
            namespace: \${POD_NAMESPACE}
EOF
```

**Comment by jsoriano** [comment]
Related with #6708

**Comment by exekias** [comment]
Hi @lastboy1228,

When using `hostNetwork` add_kubernetes_metadata fails to discover its own node name, you need to manually pass it, try with:
```
        - add_kubernetes_metadata:
            in_cluster: true
            host: ${HOSTNAME}
            namespace: \${POD_NAMESPACE}
```

This was improved for 6.3, and it will work both with and without `hostNetwork` without any special settings.

Please give that a try and close this issue if fixed. Also please open a new one for the other issue if it persist.
