### ISSUE TITLE
how drop some fields with mysql module using filebeat

### ISSUE THREAD

**Issue by pcleon** [elastic/beats#7089]
i want to drop some fields in filebeat.yml when load mysql module, just like  mysql.slowlog.id, but it doesn't affect when i use
```
processors:
- include_fields:
    fields: ["mysql.slow"]
- drop_fields:
    fields: ["mysql.slow.id"]
```
or
```
processors:
- include_fields:
    fields: ["mysql"]
- drop_fields:
    fields: ["mysql.slow.id"]
```
or
```
processors:
- drop_fields:
    fields: ["mysql.slowlog.id"]
```
how could i make it work?
