### ISSUE TITLE
Autodiscovery uses events with no host

### ISSUE THREAD

**Issue by gingerwizard** [elastic/beats#7193]
- Version:  Mericbeat 6.2.4
- Operating System: Linux - k8 GCP
- Steps to Reproduce: 

This issue occurs whenever the a configuration attempts to utilise meta data from autodiscovery in k8 - tested in GCP only. This has manifested itself for Kafka and Redis modules.

Example configuration:

```
            - condition:
                and:
                  - contains:
                      kubernetes.labels.app: redis
              config:
                - module: redis
                  period: 10s
                  metricsets: ["info", "keyspace"]
                  hosts: ["${data.host}:${data.port}"]
```

Whilst autodiscovery works, metricbeat will utilise events that contain no host information - this seems to occur when metricbeat is running and a new system is added to the cluster. The result is a "poller" is started with no host information e.g.

```
2018-04-12T11:27:44.533Z    ERROR    redis/redis.go:45    Error retrieving INFO stats: dial tcp :6379: getsockopt: connection refused

```
OR 

```
2018-04-12T13:20:38.727Z	ERROR	redis/redis.go:45	Error retrieving INFO stats: dial tcp: missing address

```

Workaround:
```
            - condition:
                and:
                  - contains:
                      kubernetes.labels.app: redis
                  - regexp:
                      host: ".+"
              config:
                - module: redis
                  period: 10s
                  metricsets: ["info", "keyspace"]
                  hosts: ["${data.host}:${data.port}"]
```

discussed with @exekias
