### ISSUE TITLE
filebeat lost log data

### ISSUE THREAD

**Issue by onehandofLM** [elastic/beats#7219]
sorry about that I couldn't register an account in https://discuss.elastic.co/c/beats(May China area will appear this issue). So I put my issue here directly.

issue:
Now at product env. When I restart es（filebeat is still running）,  I will meet an issue that filebeat doesn't send the log info to es. one single log is too long may cause this issue?

the filebeat.yml 
```
- type: log
 ignore_older: 48h
 close_inactive: 2h
 close_timeout: 10m
 clean_inactive: 72h

output.elasticsearch:
 max_retries: 2
 timeout: 300
```

For confirmed bugs, please report:
- Version:  filebeat 6.2.3
- Operating System:  CentOS release 6.8
- Discuss Forum URL: 
- Steps to Reproduce:
