### ISSUE TITLE
Metricbeat kibana module uses `enabled: default` instead of `enabled: true`

### ISSUE THREAD

**Issue by dadoonet** [elastic/beats#7364]
- Version: 6.3.0

In Metricbeat, kibana module is defined as in the `metricbeat.reference.yml`:

```yml
#------------------------------- Kibana Module -------------------------------
- module: kibana
  metricsets: ["status"]
  period: 10s
  hosts: ["localhost:5601"]
  enabled: default
```

When using this, it fails at startup with:

```
2018-06-19T10:39:10.622Z	ERROR	instance/beat.go:691	Exiting: 1 error: can not convert 'string' into 'bool' accessing 'metricbeat.modules.3.enabled' (source:'/etc/metricbeat/metricbeat.yml')
```

`enabled` should be `true` instead.

See also:

* https://github.com/elastic/beats/commit/c5b2e4e32209ebaab547337a7f064e10b77c6f37#r29415090
* https://github.com/elastic/beats/commit/c5b2e4e32209ebaab547337a7f064e10b77c6f37#r29415098

Doc link: https://www.elastic.co/guide/en/beats/metricbeat/6.3/metricbeat-reference-yml.html

I did not check the other beats though.
