### ISSUE TITLE
filebeat json log input changed in master?

### ISSUE THREAD

**Issue by graphaelli** [elastic/beats#7382]
While upgrading filebeat to master, ran into an issue collecting logs from docker containers with filebeat.  All log lines are rejected with:

```
{"type":"mapper_parsing_exception","reason":"object mapping for [log] tried to parse field [log] as object, but found a concrete value"}
```

`docker-compose.yml` contains:
```
filebeat:
  command: filebeat -e --strict.perms=false
  depends_on:
    elasticsearch: {condition: service_healthy}
    kibana: {condition: service_healthy}
  image: docker.elastic.co/beats/filebeat:7.0.0-alpha1-SNAPSHOT
  logging:
    driver: json-file
    options: {max-file: '5', max-size: 2m}
  user: root
  volumes: ['./filebeat.yml:/usr/share/filebeat/filebeat.yml', '/var/lib/docker/containers:/var/lib/docker/containers']
```

and `filebeat.yml` is:
```
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression
  index.number_of_replicas: 0

setup.dashboards.enabled: true

setup.kibana:
  host: "kibana:5601"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

filebeat.prospectors:
  - type: log
    paths:
     - '/var/lib/docker/containers/*/*.log'
    json.message_key: log
    json.overwrite_keys: true
    json.keys_under_root: true
    json.add_error_key: true
```

I've run filebeat containers running 6.2.5-SNAPSHOT, 6.3.0 release, and 6.4.0-SNAPSHOT (`filebeat version 6.4.0 (amd64), libbeat 6.4.0 [575c6758d3ef0b33d4b1af54f35cadbc87fda08e built 2018-06-20 06:00:39 +0000 UTC]`) side by side with this 7.0.0-alpha1-SNAPSHOT and they are able to process the same logs.
