### ISSUE TITLE
to_syslog Configuration

### ISSUE THREAD

**Issue by dentrinh** [elastic/beats#744]
Hi,

I have enabled to_syslog in the filebeat.yml and do not have a -e command line option, but I see nothing in system.log.  I am on a Mac OS X.  What needs to be done so I can see filebeat logging output to syslog?

Thanks,

Dennis

**Comment by andrewkroh** [comment]
Without seeing your full config my guess is that you need to set the [`level`](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-configuration-details.html#_level) higher than `error`.

For future questions, please post at https://discuss.elastic.co/c/beats and provide your [beat version and config](https://discuss.elastic.co/t/beats-how-to-report-an-issue/38301).

**Comment by dentrinh** [comment]
I will be sure to post at the discussion link next time.
I can get output in stderr with -e and I can configure output to file, but I don't see anything in the system.log and I have the logging level set to "debug".
Do I need to configure the syslog.conf to listen to a specific facility and priority?

Filebeat Version: filebeat version 1.0.1 (amd64)
Operating System: Mac OS X 10.11.2
Configuration:
```
############################# Filebeat ######################################
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    -
      paths:
      input_type: stdin
    -
     type: stdin
     paths:
       - "-"
############################# Output ##########################################
output:
  ### Logstash as output
  logstash:
    # The Logstash hosts
    hosts: ["localhost:5044"]

    # Number of workers per Logstash host.
    worker: 1
############################# Shipper #########################################
shipper:
logging:
  to_syslog: true
  files:
    rotateeverybytes: 10485760 # = 10MB
  level: debug
```
