### ISSUE TITLE
[Filebeat] When convert_timezone and prospector.processors are together, it throws an error and cannot start

### ISSUE THREAD

**Issue by marcinpm** [elastic/beats#7482]
- Version: Filebeat 6.2.4
- Operating System: Linux (e.g. Centos 6.9)

**Steps to Reproduce:** 

Based on the following config, it looks like `var.convert_timezone: true` is somehow problematic for `prospector.processors`

```
[root@testhost filebeat]# cat /etc/filebeat/modules.d/system.yml
- module: system
  # Syslog
  syslog:
    enabled: true
    var.paths: ["/var/log/test.log"]
#   var.convert_timezone: true
    prospector.processors:
      - drop_event.when.not.regexp.message: "some_test_hostname"

  auth:
    enabled: true
    var.paths: ["/var/log/auth.log"]
#   var.convert_timezone: true
    prospector.processors:
      - drop_event.when.not.regexp.message: "some_test_hostname"
```

Whenever I uncomment the `var.convert_timezone` bit, then Filebeat is unable to start and throws an error:

`2018-06-28T12:04:03.719+0200 ERROR instance/beat.go:667 Exiting: each processor needs to have exactly one action, but found 2 actions`

It seems to be a bug with config merging in Filebeat.

**Workaround:**

Update the config as below to avoid the errors:

```
prospector.processors:
  1.drop_event.when.not.regexp.message: "some_test_hostname"
```
