### ISSUE TITLE
problem with metricbeat system.filesystem.mount_point field data

### ISSUE THREAD

**Issue by sgreszcz** [elastic/beats#7512]
- Version: metricbeat 6.3
- Operating System: Ubuntu 16.04 LTS
- Discuss Forum URL: https://discuss.elastic.co/t/configuring-system-filesystem-to-show-useful-mount-stats/136914/7
- Steps to Reproduce: metricbeats.yml

```
metricbeat.modules:
- module: system
  enabled: true
  period: 1m
  metricsets:
    - filesystem
    - fsstat
```

metricbeats seems to be finding the correct system.filesystem.device_name (/dev/sda1, /dev/sdb1, /dev/mapper for boot) from the Ubuntu host system.

<img width="619" alt="screen shot 2018-07-04 at 17 54 52" src="https://user-images.githubusercontent.com/22910494/42288807-54488ac4-7fb4-11e8-8d38-28e442ac863b.png">

But it isn't finding the respective Ubuntu system mount points with system.filesystem.mount_point (/, /data, /boot)

<img width="645" alt="screen shot 2018-07-04 at 17 55 14" src="https://user-images.githubusercontent.com/22910494/42288815-629a7574-7fb4-11e8-836d-62271f263183.png">

Ubuntu df -h:

```
/dev/mapper/cdc--alln--stg--vg-root   16G  9.6G  4.9G  67% /
/dev/sdb1                            197G   13G  175G   7% /data
/dev/sda1                            472M  204M  244M  46% /boot
```

Default Kibana disk usage visualisation (uses system.filesystem.mount_point, and sometimes shows 0% when updating - other times with correct percentage label).

<img width="1620" alt="screen shot 2018-07-04 at 13 16 33" src="https://user-images.githubusercontent.com/22910494/42288930-c57a5a24-7fb4-11e8-8552-47625f77f9ad.png">

Same system being monitored with telegraf/influxdb/cronograf out of the box:

<img width="495" alt="screen shot 2018-07-04 at 13 19 08" src="https://user-images.githubusercontent.com/22910494/42288969-fbe221e6-7fb4-11e8-84b4-0eb9f7649937.png">

**Comment by andrewkroh** [comment]
> Same system being monitored with telegraf/influxdb/cronograf out of the box:

I'm curious if those were also executed inside of a Docker container?

> But it isn't finding the respective Ubuntu system mount points with system.filesystem.mount_point (/, /data, /boot)

I think they are present in the data, but the mount_point is prefixed with `/hostfs` because that is how they appear inside of Docker. One solution would be to strip the `/hostfs` prefix whenever `--system.hostfs=/hostfs` is used.

**Comment by andrewkroh** [comment]
It would be interesting to compare the /etc/mtab from the host and from inside the container. This is where Metricbeat determines what is mounted.

**Comment by jsoriano** [comment]
> I think they are present in the data, but the mount_point is prefixed with `/hostfs` because that is how they appear inside of Docker. One solution would be to strip the `/hostfs` prefix whenever `--system.hostfs=/hostfs` is used.

I agree, in that case we could strip this preffix. Other option we could explore is to use `/hostfs/proc/mounts` if available instead of `/etc/mtab`.

**Comment by bbolyasov** [comment]
Have similar problem.
Metricbeat 7.13.3 installed be rpm

My system.yml:

```
# Module: system
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/7.13/metricbeat-module-system.html

- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - socket_summary
    #- entropy
    #- core
    - diskio
    #- socket
    - service
    #- users
  process.include_top_n:
    by_cpu: 5      # include top 5 processes by CPU
    by_memory: 5   # include top 5 processes by memory
  # Configure the mount point of the host’s filesystem for use in monitoring a host from within a container
  #system.hostfs: "/hostfs"

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  filesystem.ignore_types: [nfs]

- module: system
  period: 15m
  metricsets:
    - uptime

#- module: system
#  period: 5m
#  metricsets:
#    - raid
#  raid.mount_point: '/'
```

but I still getting only root mountpoint in Kibana:
![image](https://user-images.githubusercontent.com/54394143/125469871-150b6ef0-4097-4a35-959a-ebffe6ffb4e5.png)
