### ISSUE TITLE
How to inspect docker with metricbeat in docker

### ISSUE THREAD

**Issue by crazychl** [elastic/beats#7526]
#### I want to inspect docker containers with metricbeat in docker ,and it works when I put metricbeat on host ,but i want to put it into docker, and I volume /var/run/docker.sock inside , I got the `permission denied ` error, following is my `docker-compose.yml`:
```shell
version: '2'
services:
    metricbeat:
        image: 'docker.elastic.co/beats/metricbeat:6.3.0'
        #build:
        #    context: "."
        #    dockerfile: "Dockerfile"
        volumes:
            - /var/run:/var/run:rw
            - /:/rootfs:ro
            - /sys:/sys:ro
            - /var/lib/docker:/var/lib/docker:ro
            - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
            - ./docker.yml:/usr/share/metricbeat/modules.d/docker.yml

```
Thank you!

**Comment by andrewkroh** [comment]
You need to check who owns `/var/run/docker.sock`? And who is Metricbeat running as?

One solution is to run Metricbeat as root then for sure it will be able to access `/var/run/docker.sock`.

```
version: '2'
services:
    metricbeat:
        image: 'docker.elastic.co/beats/metricbeat:6.3.0'
        user: root
        ...
```

Please open any future questions at https://discuss.elastic.co/c/beats.
