### ISSUE TITLE
Fields from different prospectors can't be defined in a common namespace

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#7528]
For confirmed bugs, please report:
- Version: 6.3.1
- Operating System: -
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-field-name-collision-with-external-prospectors/138809
- Steps to Reproduce: 

Defining fields at the global level, nested into a namespace (test_namespace):
```
filebeat:
  registry_file: /var/lib/filebeat/registry
  config.prospectors:
    enabled: true
    path: /etc/filebeat/conf.d/*.yml
fields:
  test_namespace.fqdn: civet.fqdn.xxxx
fields_under_root: true
output:
[...]
```

and adding more fields to this namespace in a prospector:
```
- paths:
    - /var/log/auth.log
  type: log
  fields:
    test_namespace.container: syslog
  fields_under_root: true
```

Results in only the fields from the prospectors being present, completely replacing those at the global level:
```
{
  "@timestamp": "2018-07-06T12:48:41.783Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "doc",
    "version": "7.0.0-alpha1"
  },
  "prospector": {
    "type": "log"
  },
  "beat": {
    "hostname": "Adrian-Elastic.local",
    "version": "7.0.0-alpha1",
    "name": "Adrian-Elastic.local"
  },
  "host": {
    "name": "Adrian-Elastic.local"
  },
  "offset": 19644,
  "message": "Oct 11 20:12:03 CCIOReporterFormatter::addRegistryChildToChannelDictionary streams 62",
  "source": "/var/log/corecaptured.log",
  "input": {
    "type": "log"
  },
  "test_namespace": {
    "container": "syslog"
  }
}
```
