### ISSUE TITLE
filebeat, elasticsearch, docker logging loop

### ISSUE THREAD

**Issue by superdump** [elastic/beats#760]
How can one avoid an infinite logging loop when using filebeat in a docker container to watch docker container logs and ship then off to elasticsearch? An example configuration:

```
filebeat:
  prospectors:
    -
      paths:
        - /var/lib/docker/containers/*/*.log
      encoding: utf-8
      input_type: log

output:
  elasticsearch:
    hosts: ["http://100.100.100.100:9200"]
```

filebeat and elasticsearch are both running in docker containers and writing their output also to some file that would be matched by filebeat. How can this be avoided?

If it helps to find a solution, there is a file called config.json in the same directory as the log file that contains information that can identify that that log file pertains to filebeat or elasticsearch.
