### ISSUE TITLE
[Auditbeat] - Add include_paths for file_integrity config

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#7707]
It would be useful with the recursive monitoring feature to have an `include_paths` option. `exclude_paths` is already supported.

For example:

```
auditbeat.modules:
- module: file_integrity
  paths: [/home]
  recursive: true
  include_paths:
  - `.ssh/`
```

glob support could be an alternative.

```
auditbeat.modules:
- module: file_integrity
  paths:
  - /home/*/.ssh
  recursive: true
```
