### ISSUE TITLE
Filebeat close_timeout fails to work

### ISSUE THREAD

**Issue by danielkasen** [elastic/beats#7762]
Hello All,
We had a cluster issue last night and usually filebeat would handle this gracefully and respect the close_timeout we set to avoid open file handlers keeping files open. But for some reason this appears to have failed and continues to keep the 1 log file open from the time of the event. It's almost as though the thread got into a locked state and cannot be killed. Even though the logging pipeline is still working correctly, we are also seeing this error in the filebeat logs:

```{"level":"error","timestamp":"2018-07-26T16:13:13.709Z","caller":"pipeline/output.go:92","message":"Failed to publish events: 504 Gateway Time-out: <html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n"}
{"level":"error","timestamp":"2018-07-26T16:13:33.619Z","caller":"elasticsearch/client.go:299","message":"Failed to perform any bulk index operations: 504 Gateway Time-out: <html>\r\n<head><title>504 Gateway Time-out</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>504 Gateway Time-out</h1></center>\r\n</body>\r\n</html>\r\n"}
```

config:
```
- module: test
  app:
    enabled: true
    input:
      fields_under_root: true
      fields:
        class: test
      close_timeout: 10m
      close_inactive: 1m
```
