### ISSUE TITLE
Feature - Reverse DNS Enrichment

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats#7770]
As a user I would like to be able to resolve IP addresses in events to hostnames by using reverse DNS lookups (query PTR records). My hosts send data directly to Elastic Cloud. Many (but not all) of the IP addresses in my events are private IP addresses that are only resolvable via internal DNS servers (so the enrichment cannot be done in Elastic Cloud).

Ideally I'd like it to be possible to only enrich events associated with my private network. So a condition that works on IP ranges would be nice, but I could also use a regex (less ideal) to an IP prefix.

```yaml
processors:
# When destination.ip is in a private network (RFC 1918 or RFC 4193).
- dns:
    reverse:
      - destination.ip: destination.hostname
    when.network:
      destination.ip: private

# Enrich ip and client_ip for all DNS events.
- dns:
    reverse:
      - ip: hostname
      - client_ip: client_hostname
    when.equals:
      type: dns
```
