### ISSUE TITLE
filebeat: all time high CPU (99.9%)

### ISSUE THREAD

**Issue by iyaozhen** [elastic/beats#781]
I run filebeat in CentOS 4. I find filebeat use high CPU:

![image](https://cloud.githubusercontent.com/assets/4395553/12448124/f7356284-bfae-11e5-88e2-81af69c4fecf.png)

This is normal ?

My config:
```
paths:
        # gateway0-10
        - /home/work/gateway*/nohup.out
        encoding: utf-8
        ignore_older: 24h
        scan_frequency: 0s
        tail_files: true
        backoff: 1s
        max_backoff: 10s

logstash:
    hosts: ["10.202.123.19:5044", "10.202.123.46:5044"]
    worker: 16
    loadbalance: true
```

At last, Thx filebeat and Its developer, It makes my job easier.
