### ISSUE TITLE
Traefik frontend_name is missing

### ISSUE THREAD

**Issue by iwex** [elastic/beats#8015]
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

For confirmed bugs, please report:
- Version: filebeat:6.3.2
- Operating System: docker container (ubuntu 18.04)
- Discuss Forum URL: https://discuss.elastic.co/t/traefik-logs/145072/2
- Steps to Reproduce: 

Add logging for traefik (v. 1.6.5) with this `filebeat.yaml`
```yaml
filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false
 
setup.template.settings:
  index.number_of_shards: 3
 
setup.kibana:
  host: "kibana:5601"
 
  output.elasticsearch:
    hosts: ["elasticsearch:9200"]
 
  setup.template.fields: "${path.config}/fields.yml"
 
  tags: ["traefik"]
```
And there is no `traefil.access.frontend_name` in ElasticSearch records.
