### ISSUE TITLE
[Feature request] Add selectable fields for add_docker_metadata processor

### ISSUE THREAD

**Issue by caub** [elastic/beats#8049]
It would be great to be able to select which fields we want from `add_docker_metadata` prospector

I'm doing currently:

```yml
processors:
  - add_docker_metadata: ~
  - drop_fields:
      fields: ["input.type", "prospector.type", "docker.container.id", "docker.container.labels.com.docker.stack.namespace", "docker.container.labels.com.docker.swarm.node.id", "docker.container.labels.com.docker.swarm.service.id", "docker.container.labels.com.docker.swarm.service.name", "docker.container.labels.com.docker.swarm.task.id", "docker.container.labels.com.docker.swarm.task.name", "docker.container.labels.com.docker.swarm.task.value"]

```

What I'd like is:

```yml
processors:
  - add_docker_metadata:
      fields: ["docker.container.image", "docker.container.name"]
```

discuss link: https://discuss.elastic.co/t/add-docker-metadata-filter-desired-fields/145502
