### ISSUE TITLE
Cannot load beats dashboards in darwin 

### ISSUE THREAD

**Issue by bhavyarm** [elastic/beats#8051]
- Version:  6.4.0 BC6
- Operating System:  darwin_x_86_64

Please note this is fine on linux and windows

- Steps to Reproduce: 
1. Go to staging and download default distros for ES/Kibana and metricbeat ( I tried it with both metricbeat and packetbeat)
2. Try to install the dashboards using the command in staging
3. Dashboards installation fails with:
```
Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing URL/file: Failed to unzip the archive: /var/folders/74/7821tshd4l36nh47qw_q76r40000gp/T/tmp188011220/beats-dashboards-6.4.0.zip: open /var/folders/74/7821tshd4l36nh47qw_q76r40000gp/T/tmp188011220/beats-dashboards-6.4.0/.build_hash.txt: no such file or directory
```

**Comment by LeeDr** [comment]
I used the same BC6 and it all worked for me but I used a slightly different command.  I used;

`/Users/vagrant//metricbeat/metricbeat setup -e -c /Users/vagrant//metricbeat/metricbeat.yml`

And all my Kibana saved objects got loaded successfully.  I have security enabled.  Here's that metricbeat.yml file;

```
metricbeat.config.modules:
  path: ${path.config}/conf.d/*.yml
  reload.period: 10s
  reload.enabled: false
metricbeat.max_start_delay: 10s
metricbeat.modules:
- module: system
  enabled: true
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
  processes: ['.*']
- module: system
  enabled: true
  period: 1m
  metricsets:
    - filesystem
    - fsstat
- module: elasticsearch
  metricsets: ["node", "node_stats"]
  enabled: false
  period: 10s
  hosts: ["localhost:9200"]
- module: kibana
  metricsets: ["status"]
  enabled: false
  period: 10s
  hosts: ["localhost:5601"]

output.elasticsearch:
  hosts: ["localhost:9200"]
  protocol: https
  username: "beats_internal"
  password: "changeme"
  ssl.enabled: true
  ssl.certificate_authorities: ["/Users/vagrant//metricbeat/ca.crt"]
  ssl.certificate: /Users/vagrant//metricbeat/elasticsearch.crt
  ssl.key: /Users/vagrant//metricbeat/elasticsearch.key

#setup.dashboards.snapshot: true

setup.kibana:
  protocol: https
  host: localhost:5601
  username: "kibana"
  password: "changeit"
  ssl.enabled: true
  ssl.certificate_authorities: ["/Users/vagrant//metricbeat/ca.crt"]
  ssl.certificate: /Users/vagrant//metricbeat/elasticsearch.crt
  ssl.key: /Users/vagrant//metricbeat/elasticsearch.key
logging.to_files: true
logging.files:
xpack.monitoring:
  enabled: true
  elasticsearch:
    url: "https://localhost:9200"
    username: elastic
    password: changeit
```

packetbeat also worked for me;
`/Users/vagrant//packetbeat/packetbeat setup -e -c /Users/vagrant//packetbeat/packetbeat.yml`

I had an error on filebeat, but apparently it's because I'm using the kibana server user.  (I tried switching the setup.kibana username/password to the elastic superuser and then I didn't have this error);
```
2018-08-22T16:02:20.872Z	ERROR	instance/beat.go:743	Exiting: 1 error: Error setting up ML for apache2: 10 errors: [security_exception] action [cluster:admin/xpack/ml/datafeeds/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/datafeeds/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/datafeeds/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/datafeeds/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/datafeeds/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/job/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/job/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/job/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/job/put] is unauthorized for user [kibana]; [security_exception] action [cluster:admin/xpack/ml/job/put] is unauthorized for user [kibana]
```
