### ISSUE TITLE
Events don't get dropped after max_retries

### ISSUE THREAD

**Issue by blanche** [elastic/beats#818]
Using a logstash output for a single host with max_retries set to > 0, filebeat does not drop the events but tries to reconnect to logstash, restarting the max_retry/backoff mechanism

the documentation on max_retries specifies, that events should be dropped after max_retries

```
The number of times to try a particular Logstash send attempt.
If the send operation doesn’t succeed after the specified number of retries, the events are dropped
```

im using v1.0.1

```
filebeat:
  prospectors:
    -
      paths:
        - /path/to/file.txt
        

output:
  logstash:
    hosts: ["host:1234"]
    max_retries: 3
    timeout: 5
```
