### ISSUE TITLE
[Winlogbeat] Add setting to load event_logs configuration from files

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#8281]
Add setting to load winlogbeat event_logs configuration from files, in a similar fashion to `filebeat.config.modules.path` or `metricbeat.config.modules.path`. So when using configuration management tools specific event logs configuration can be deployed to specific servers while sharing the same general settings.

The configuration could then be something like this:
```
winlogbeat.config.event_logs:
  path: ${path.config}/event_logs.d/*.yml
  reload.enabled: false
  #reload.period: 10s
```
