### ISSUE TITLE
[Heartbeat]: Cloud provider target autodiscovery

### ISSUE THREAD

**Issue by pmoust** [elastic/beats#8282]
Proposing to add target autodiscovery using Cloud Providers' APIs for Heartbeat monitors.

Example configuration

* `monitors.autodiscovery.provider` (ex `aws`, `gcp`, `azure` etc)
* `monitors.autodiscovery.resource` (ex `ec2`, `elb`, `gcs`, `nlb` etc)
* `monitors.autodiscovery.credentials` (fields vary per provider, ex. for `aws` type it would be something like `secret_access_key`, `access_key_id` etc, env vars taking precedence)
* `monitors.autodiscovery.credentials.path` (where applicable, i.e. gcp json token blob)
* `monitors.autodiscovery.filters` (accepting multiple filters, haven't given much thought to notation. Filters would all need to match or use a notation like the event post-processor (?))
* `monitors.autodiscovery.interval` (how often the autodiscovery mechanism will get triggered, in seconds)
* `monitors.hosts` accepting patterns based on autodiscovery results

```yaml
heatbeat.monitors:
   - type: http
     schedule: '*/5 * * * * * *'
    
     autodiscovery.provider: "aws"
     autodiscovery.resource: "ec2"
     autodiscovery.credentials.secret_access_key: "F0000000000000000000000000000000"
     autodiscovery.credentials.access_key_id: "BAAAAAAAAAAR"

     autodiscovery.interval: 60
     
     autodiscovery.filters: 
       - name: "filter by tag"
         type: "tag"
         key: "environment"
         value: "production"
       - name: "exclude us-west-1"
         type: "region"
         value: "! us-west-1"
       - name: "Target the haproxy security group"
         type: "security_group"
         value: "haproxy"

     hosts: ["http://${autodiscovered.private_ipv4}:80/status"]
```
