### ISSUE TITLE
Support Field Reference in the Logstash index option

### ISSUE THREAD

**Issue by ph** [elastic/beats#8296]
The Logstash output allow you to specify an 'index' option, when you set this value it will replace the value of @metadata.beat to the configured value and you can use that for the index. The problem is the field doesn't support field reference to dynamically set the value of the field like the elasticsearch output instead it will be the exact string configured in the output.

```
    "@metadata" => {
              "type" => "doc",
        "ip_address" => "127.0.0.1",
              "beat" => "hello-%{[beat.version]}-%{+yyyy.MM.dd}",
           "version" => "7.0.0-alpha1"
    },
```
Filebeat configuration used to generate the above:

```yaml
output.logstash:
  enabled: true
  # The Logstash hosts
  hosts: ["localhost:5044"]
  index: "hello-%{[beat.version]}-%{+yyyy.MM.dd}"
  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"
```
