### ISSUE TITLE
I can't start the Auditbeat service

### ISSUE THREAD

**Issue by jesslh** [elastic/beats#8382]
I'm not able to start the service Auditbeat due to the following error:

2018-09-19T17:38:58.767-0500	ERROR	instance/beat.go:743	Exiting: 1 error: 1 error: failed to unpack the auditd config: 1 error: failed loading rules: 1 error: at /etc/auditbeat/audit.rules.d/sample-rules-linux-32bit.conf:5: failed to interpret rule '-a always,exit -F arch=b32 -S accept,bind,connect -F key=external-access': failed to add syscall 'accept': unknown syscall 'accept' for arch i386 accessing 'auditbeat.modules.0' (source:'/etc/auditbeat/auditbeat.yml')

- The SO is a CentOS 7 with auditd enable. 
Linux 3.10.0-862.11.6.el7.x86_64 #1 SMP Tue Aug 14 21:49:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

Auditbeat.yml config is the following:
```
auditbeat.modules:
- module: audits
  socket_type: multicast
  audit_rule_files: [ '${path.config}/audit.rules.d/*.conf' ]
  audit_rules: |
       -w /etc/passwd -p wa -k identity
       -w /etc/passwd -p wa -k passwd_changes
- module: file_integrity
  paths:
  - /bin
  - /usr/bin
  - /sbin
  - /usr/sbin
  - /etc

setup.template.settings:
  index.number_of_shards: 3

setup.kibana.host: "10.19.249.31:5601"

output.elasticsearch:
  hosts: ["10.19.249.31:9200"]
```
