### ISSUE TITLE
Config reload docs should show inputs.d directory rather than configs/*.yml

### ISSUE THREAD

**Issue by dedemorton** [elastic/beats#8417]
To be consistent with the filebeat.reference.yml file, the documentation about [loading external files](https://www.elastic.co/guide/en/beats/filebeat/6.4/filebeat-configuration-reloading.html#filebeat-configuration-reloading) should show the `inputs.d/*.yml` rather than `configs/*yml`

````
filebeat.config:
  inputs:
    enabled: false
    path: inputs.d/*.yml
````
