### ISSUE TITLE
Filebeat CPU shoots 100 times when sending to kafka topic using a dynamic field

### ISSUE THREAD

**Issue by krunalvora** [elastic/beats#8418]
- Filebeat Version: 6.2.4
   Kafka version: 0.1.1

- Operating System: 
   Running filebeat as a daemonset using the docker image for filebeat.

- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-cpu-shoots-100-times-when-sending-to-kafka-topic-using-a-field/146898

- Steps to Reproduce: 

Run filebeat as a Daemonset in a Kubernetes cluster collecting logs from the `/var/lib/docker/container/` mountpath and publishing them to Kafka outside the k8s cluster.
Using the filebeat config output like:
```
    output.kafka:
      hosts:
      - <kafka>:9092
      topic: 'topic'
```
the CPU usage of filebeat pods is around ~15m.

But when trying to dynamically set the topic using the fields of the event:
```
    output.kafka:
      hosts:
      - <kafka>:9092
      topic: 'topic-%{[kubernetes.namespace]}'
```
the CPU shoots to >2000mi and the logs stop flowing to kafka within a minute.

As per the discussion in the Elastic forum, this looks like a bug. 
Is there any logical explanation about the rise of the CPU usage because of dynamic topic setting in Filebeat output?

**Comment by jsoriano** [comment]
@krunalvora I wonder if this can be related to events not containing the `kubernetes.namespace`. Can you check the logs for messages like `Dropping event: no topic could be selected`, or any other error that you don't see when using a fixed topic?

In any case, could you try this configuration and check if cpu usage also increases?
```
    output.kafka:
      hosts:
      - <kafka>:9092
      topics:
      - topic: 'topic-%{[kubernetes.namespace]}'
        default: 'topic'
```
Thanks!

**Comment by tinder-krunalvora** [comment]
@jsoriano 
We should have the kubernetes namespace for each event because we add that data through filebeat processors inside the prospector.

```
- type: log
  paths:
    - /var/lib/docker/containers/*/*.log
  json.message_key: log
  json.keys_under_root: true
  json.add_error_key: true
  multiline.pattern: '^\s'
  multiline.match: after
  output.console.pretty: true
  processors:
    - add_kubernetes_metadata:
        in_cluster: true
        namespace: ${POD_NAMESPACE}
    - decode_json_fields:
        max_depth: 2
        target: ""
        fields: ["log"]
```

I will give your suggestion a try though and let you know!
