### ISSUE TITLE
unclear how to get autodiscover with docker hints working

### ISSUE THREAD

**Issue by mathroc** [elastic/beats#8484]
Hi,

I'm running the elastic stack on a docker swarm, my metricbeats configuration looks like this:

```yaml
name: ${NODE_NAME}

setup.kibana:
  host: "kibana:5601"

setup.dashboards.enabled: true

xpack.monitoring.enabled: true

logging.level: ${LOGGING_LEVEL:warning}

output.elasticsearch:
  hosts: ["elasticsearch:9200"]

metricbeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: "elasticsearch"
          config:
            - module: elasticsearch
              metricsets: ["node", "node_stats"]
              period: 10s
              hosts: ["${data.host}:9200"]
    - type: docker
      templates:
        - condition:
            contains:
              docker.container.image: "kibana"
          config:
            - module: kibana
              metricsets: ["status"]
              period: 10s
              hosts: ["${data.host}:5601"]
              basepath: ""
```

autodiscover without using hints (for elasticsearch and kibana) is working, however, I'm trying to add metrics for nginx on a container without using autodiscover (because some config will change for each container)

here is my stack configuration for the container I want to monitor:

```yaml
version: "3.7"

services:
  site:
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHA}
    deploy:
      mode: global
      placement:
        constraints:
          - node.labels.services == public
      labels:
        traefik.backend: fhyve.ch
        traefik.network: "web"
        traefik.port: "80"
        traefik.enable: "true"
        traefik.frontend.rule: Host:www.fhyve.ch,fhyve.ch
        co.elastic.metrics/module: nginx
        co.elastic.metrics/metricsets: stubstatus
        co.elastic.metrics/hosts: '$${data.host}:8080' # there's 2 & to escape it inside a docker compose file
        co.elastic.metrics/period: 10s
    networks:
      - web
      - metrics

networks:
  web:
    name: web
    external: true
  metrics:
    name: metrics
    external: true
```

but the container does not get detected by metricbeats afaict, even with logging set to debug, the only line about hints I see says "WARN    [cfgwarn]       hints/metrics.go:59     BETA: The hints builder is beta"

for elasticsearch & kibana I can see logs like:

> DEBUG   [autodiscover]  cfgfile/list.go:109     Starting runner: kibana [metricsets=1]

but there's none for nginx, should there be one when it's autodiscovered with hints ?

one odd thing, in the metricbeat docker debug logs, I see this:

```
2018-09-28T12:52:15.744457224Z monitoring_metricbeat.0.25syau5t3wmv@hyve-00    | 2018-09-28T12:52:15.743Z       DEBUG   [docker]        docker/watcher.go:239   Got a new docker event: {start 967131c514ffb7a1045322ba7d0a996cf61108fb6a731b244371560358439f98 registry.texthtml.net/fhyve/prod/fhyve.ch:8a6330ce6b7fad4d5e1abdc3bd3350e878b6240d@sha256:5b8fb24566726404edcfbd5d15f822aec4206d07c0f1c890e8a820c91587884d container start {967131c514ffb7a1045322ba7d0a996cf61108fb6a731b244371560358439f98 map[com.docker.swarm.task.id:ptoe1xmbr3ug16uk2rp37s5dn com.docker.swarm.task.name:fhyve_ch_site.eq4s1dj4cno0pfaobmm8ec82b.ptoe1xmbr3ug16uk2rp37s5dn com.docker.stack.namespace:fhyve_ch com.docker.swarm.node.id:eq4s1dj4cno0pfaobmm8ec82b com.docker.swarm.service.id:sem5b4lcs9190ymv2j25x3hbn com.docker.swarm.task: com.docker.swarm.service.name:fhyve_ch_site image:registry.texthtml.net/fhyve/prod/fhyve.ch:8a6330ce6b7fad4d5e1abdc3bd3350e878b6240d@sha256:5b8fb24566726404edcfbd5d15f822aec4206d07c0f1c890e8a820c91587884d maintainer:NGINX Docker Maintainers <docker-maint@nginx.com> name:fhyve_ch_site.eq4s1dj4cno0pfaobmm8ec82b.ptoe1xmbr3ug16uk2rp37s5dn]} local 1538139135 1538139135742961324}
```

the labels are absent from the event, however if I look into the metricbeat index, the labels are present:

```json
{
  "_index": "metricbeat-6.4.0-2018.09.28",
  "_type": "doc",
  "_id": "0PxHIGYB7D_koGAEgy7V",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2018-09-28T13:04:08.693Z",
    "docker": {
      "container": {
        "id": "f009a5ad8c68a90b6e923b71efd4fa675a255f4c3e26e0d1b18042657cea5aa8",
        "image": "registry.texthtml.net/fhyve/prod/fhyve.ch:38d0a204a2313e6598ac0b26ca04364daeee5870@sha256:e0d990bbe432e0e4504d3fd198d1ce24edd21d1644e91331b6280fa48ddc76be",
        "name": "fhyve_ch_site.eq4s1dj4cno0pfaobmm8ec82b.m0ubj2okt30lxvvy7q8gtn6e3",
        "ip_addresses": [
          "10.0.1.41",
          "10.0.25.28"
        ],
        "size": {
          "root_fs": 0,
          "rw": 0
        },
        "command": "nginx -g 'daemon off;'",
        "status": "Up 59 seconds",
        "created": "2018-09-28T13:03:04.000Z",
        "labels": {
          "co_elastic_metrics_metricsets": "stubstatus",
          "com_docker_swarm_task_id": "m0ubj2okt30lxvvy7q8gtn6e3",
          "com_docker_swarm_task_name": "fhyve_ch_site.eq4s1dj4cno0pfaobmm8ec82b.m0ubj2okt30lxvvy7q8gtn6e3",
          "maintainer": "NGINX Docker Maintainers <docker-maint@nginx.com>",
          "co_elastic_metrics_period": "10s",
          "co_elastic_metrics_enabled": "true",
          "com_docker_swarm_task": "",
          "com_docker_stack_namespace": "fhyve_ch",
          "com_docker_swarm_service_name": "fhyve_ch_site",
          "com_docker_swarm_node_id": "eq4s1dj4cno0pfaobmm8ec82b",
          "co_elastic_metrics_module": "nginx",
          "com_docker_swarm_service_id": "sem5b4lcs9190ymv2j25x3hbn",
          "co_elastic_metrics_hosts": "${data.host}:8080"
        }
      }
    },
    "metricset": {
      "module": "docker",
      "host": "/var/run/docker.sock",
      "rtt": 6308,
      "name": "container"
    },
    "beat": {
      "name": "hyve-00",
      "hostname": "d94e912054b2",
      "version": "6.4.0"
    },
    "host": {
      "name": "hyve-00"
    }
  },
  "fields": {
    "docker.container.created": [
      "2018-09-28T13:03:04.000Z"
    ],
    "@timestamp": [
      "2018-09-28T13:04:08.693Z"
    ]
  },
  "highlight": {
    "metricset.module": [
      "@kibana-highlighted-field@docker@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1538139848693
  ]
}
```
