### ISSUE TITLE
docker autodiscover hints & networks

### ISSUE THREAD

**Issue by mathroc** [elastic/beats#8498]
Hi,

I'm configuring my servers monitoring with metricbeat, and I have an issue: I'm using docker autodiscover hints to find containers to monitor, eg:

```yaml

  traefik:
    image: traefik:1.6.6
    # some config unrelated to this issue skipped
    deploy:
      mode: global
    labels:
      co.elastic.metrics/module: traefik
      co.elastic.metrics/metricsets: health
      co.elastic.metrics/hosts: '$${data.host}:8080'
      co.elastic.metrics/period: 10s
    networks:
      - web
      - default
      - metrics

networks:
  default:
  web:
    name: web
    driver: overlay
    attachable: true
  metrics:
    name: metrics
    external: true
```

here metrics is the network metricbeat is attached to, the traefik containers has multiple IPs for the multiple networks it's attached to, so `${data.host}` get one of the IP (first? random?) but it's not the correct one. that means metricbeat is not able to query the traefik API, and I have this message instead of the metrics in the metricbeat index: 

> "failed to sample health: error making http request: Get http://10.0.24.31:8080/health: dial tcp 10.0.24.31:8080: connect: network is unreachable"

10.0.24 is the IP of traefik but for another container

traefik itself deals with this problem when using autodiscover by adding a label to specify wich network to use (in the exemple I have above, I use the "web" network to let traefik communicate with other containers so I add the label `traefik.docker.network: web`)

I think a similar label should be added to metricbeat, here I would like to add `co.elastic.metrics/network: metrics`

an alternative would be to add all IPs inside the autodiscover event data, so that I could use this label instead for the hosts: `co.elastic.metrics/hosts: '${data.networks.metrics.ip}:8080'`

**Comment by exekias** [comment]
Thank you for opening this @mathroc, I agree we can and should provide more tools to let you choose the network. we can probably provide `networks.yournetwork.host` field in the autodiscover event

**Comment by mathroc** [comment]
if I have the time to install golang and setup a dev environment for this I'll give it a try, but if someone already know how to write go, please don't wait for me :angel: 

looks like it should be done here in `emitContainer` https://github.com/elastic/beats/blob/master/libbeat/autodiscover/providers/docker/docker.go#L118

**Comment by dzurikmiroslav** [comment]
Maybe this problem solve not using directly IP address of container `${data.host}` but add variable  `${data.hostname}` for network alias/hostname for example `da098a22d0b6` which is same on all networks.

**Comment by demisolutions** [comment]
Same problem in FileBeat.

We use docker autodiscover feature for redis:

```
filebeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true
      hints.default_config.enabled: true
      templates:
        - condition:
            contains:
              docker.container.image: redis
          config:
            - module: redis
              log:
                enabled: true
                input:
                  type: docker
                  containers.ids:
                    - "${data.docker.container.id}"
              slowlog:
                enabled: true
                var.hosts: ["${data.host}:${data.port}"]
```

Log part is working great, but slowlog keeps returning errors like: 

` Error running input: error receiving slowlog data: dial tcp 10.0.11.84:6379: connect: connection timed out`

When I check redis container, I can see it has different IP for each network:

backend: `10.0.11.84`
elastic: `10.0.2.196`

Filebeat container is connected to elastic network only and cannot access `10.0.11.84` IP because it is on different network.

So a solution like @mathroc suggested would be great!
