### ISSUE TITLE
Auditbeat fails on Google Container-OS >=69 / GKE >=1.10

### ISSUE THREAD

**Issue by jordansissel** [elastic/beats#8523]
Testing fails with auditbeat 6.4.1 on Google Container OS (COS) version 69

Symptom: auditbeat is unable to receive any audit logs

Possibly relevant log message:
```
2018-09-19T22:48:31.893Z        ERROR   [auditd]        auditd/audit_linux.go:153       Failure receiving audit events  {"error": "failed to set audit PID. An audit process is already running (PID 91)"}
```

`auditbeat show auditd-status` output:

```
$ docker run -it --cap-add=AUDIT_CONTROL --cap-add=AUDIT_READ --pid=host docker.elastic.co/beats/auditbeat:6.4.1 show auditd-status 
enabled 1
failure 0
pid 91
rate_limit 0
backlog_limit 8192
lost 0
backlog 0
backlog_wait_time 0
features 0x3f

$ ps -fp 91
UID          PID    PPID  C STIME TTY          TIME CMD
root          91       1  0 Sep20 ?        00:02:29 /usr/lib/systemd/systemd-journald
```

Background: We are using Google's Kubernetes Engine (GKE) and have currently deployed GKE 1.9.7 where we run auditbeat as a daemonset. This configuration works well! However, when testing GKE 1.10.7, we noticed that auditbeat is unable to collect audit logs. Testing in isolation, GKE 1.9.7 uses COS 65 where auditbeat works; GKE 1.10.7 uses COS 69 where auditbeat fails.

I compared systemd-journald configuration on COS 65 (where it works) and COS 69 (where it fails) and was unable to find anything indicative.

**Comment by jordansissel** [comment]
I've been working with Google's support team on troubleshooting this and have no answers at this time. However, we have a possible workaround which is to completely disable journald's audit system (keeping in mind, this is only necessary on COS 69, not COS 65):

```
systemctl stop systemd-journald-audit.socket
systemctl mask systemd-journald-audit.socket
systemctl restart systemd-journald
```

**Comment by jordansissel** [comment]
On COS 70 this problem still exists, and I consider it a breaking change with Google's OS. In the meantime, here is a workaround I have tested successfully:

```
systemctl stop systemd-journald-audit.socket
systemctl mask systemd-journald-audit.socket
systemctl restart systemd-journald
```

With a test configuration:

```
auditbeat.modules:
- module: auditd
  audit_rules: |
    -a always,exit -F arch=b64 -S execve -S execveat -S exit -S exit_group -S fork -S clone -S vfork -S accept -S accept4 -S connect -S bind -S listen


output.console:
```


Then running auditbeat is successful:

```
$ docker run -it --cap-add=AUDIT_CONTROL --cap-add=AUDIT_READ --pid=host -v $PWD/auditbeat.yml:/usr/share/auditbeat/auditbeat.yml docker.elastic.co/beats/auditbeat:6.4.1
...
2018-12-05T00:10:33.381Z        INFO    [auditd]        auditd/audit_linux.go:104       auditd module is running as euid=0 on kernel=4.14.67+
2018-12-05T00:10:33.432Z        INFO    [auditd]        auditd/audit_linux.go:131       socket_type=unicast will be used.
2018-12-05T00:10:43.809Z        INFO    instance/beat.go:367    auditbeat start running.
..
2018-12-05T00:10:50.338Z        INFO    [auditd]        auditd/audit_linux.go:241       Deleted 2 pre-existing audit rules.
2018-12-05T00:10:50.338Z        INFO    [auditd]        auditd/audit_linux.go:260       Successfully added 2 of 2 audit rules.
2018-12-05T00:10:50.389Z        INFO    [auditd]        auditd/audit_linux.go:284       audit status from kernel at start       {"audit_status": {"Mask":0,"Enabled":1,"Failure":0,"PID":0,"RateLimit":0,"BacklogLimit":8192,"Lost":0,"Backlog":
4,"FeatureBitmap":63,"BacklogWaitTime":0}}
2018-12-05T00:10:50.389Z        INFO    [auditd]        auditd/audit_linux.go:308       Setting kernel backlog wait time to prevent backpressure propagating to the kernel.
...

**Comment by jordansissel** [comment]
I'm content to close this as it is seems to be an undocumented breaking change in Google Container OS and not necessarily a bug in auditbeat. As noted above, disabling `systemd-journald-audit.socket` works around this problem on Google COS 69 and 70.

If I hear any news from Google's team about this change, I'll try to keep this ticket updated for posterity.

**Comment by jordansissel** [comment]
The [proposed workaround](https://github.com/elastic/beats/issues/8523#issuecomment-444308774) doesn't work. `systemctl stop ...` simply emits an error when invoked from a container on Kubernetes:

```
Running in chroot, ignoring request.
```

Same error with `systemctl restart ...`

If I try to do directly what systemctl is probably doing, it also fails, but for a different reason:

```
          # simulate: systemctl mask systemd-journald-audit.socket                                                       
          ln -sf /dev/null /host/etc/systemd/system/systemd-journald-audit.socket                                        
          # Try to restart systemd-journald without invoking `systemctl`                                                 
          # simulate; systemctl restart systemd-journald
          pkill -u root -f systemd-journald -HUP
```

The above successfully restarts systemd-journald, but it doesn't clean up the audit pid. Running auditbeat after the above (which is executed in an initContainer on Kubernetes), results in this:

```
Failure receiving audit events  {"error": "failed to set audit PID. An audit process is already running (PID 113)"}
```

However, pid 113 was the original systemd-journald process that has since been restarted by the initContainer:

```
sh-4.2# auditbeat show status
enabled 1
failure 0
pid 113
rate_limit 0
backlog_limit 8192
lost 0
backlog 4
backlog_wait_time 0
features 0x3f
sh-4.2# ps -p 113
    PID TTY          TIME CMD

sh-4.2# ps -fp $(pgrep -f systemd-journald)
UID          PID    PPID  C STIME TTY          TIME CMD
root      108936       1  0 05:56 ?        00:00:05 /usr/lib/systemd/systemd-journald
```

Any ideas on what to do for the next step?

The constraints here are that Google provides the OS, and as such, I am not doing any configuration management on the host OS, so it's difficult to figure out a solution for this.

**Comment by jordansissel** [comment]
After asking some friends in hangops and looking at the systemd source code, I found this: https://github.com/systemd/systemd/blob/042cad5737917e6964ddddba72b8fcc0cb890877/src/basic/virt.c#L607

Running this works:

```
          export SYSTEMD_IGNORE_CHROOT=1
          systemctl stop systemd-journald-audit.socket
          systemctl mask systemd-journald-audit.socket
          systemctl restart systemd-journald
```

Also notable, in Kubernetes, one must mount `hostPath` volumes: /sys/fs/cgroup, /run, and /etc (perhaps not all 3 are required, but it works for me)

**Comment by mdnfiras** [comment]
based on the comment of @jordansissel i was able to work around this by adding the following init container to `auditbeat` daemonset:
```yaml
      initContainers:
      - name: systemctl
        image: centos:7
        command:
        - /bin/sh
        - "-c"
        - |
          systemctl stop systemd-journald-audit.socket
          systemctl mask systemd-journald-audit.socket
          systemctl restart systemd-journald
          exit $?
        env:
          - name: SYSTEMD_IGNORE_CHROOT
            value: "1"
        securityContext:
          runAsUser: 0
          capabilities:
            add:
              - 'SYS_ADMIN'
        resources:
          limits:
            cpu: 10m
            memory: 10Mi
          requests:
            cpu: 5m
            memory: 8Mi
        volumeMounts:
          - name: run
            mountPath: /run
```
and the volume:
```yaml
      volumes:
      - name: run
        hostPath:
          path: /run
```
it will ensure every new node has the right configuration for auditbeat to work properly
