### ISSUE TITLE
Move a complete fields tree to another level

### ISSUE THREAD

**Issue by tchiotludo** [elastic/beats#8669]
A nice feature will be to allow to move a whole subset of fields to another level 
Example, move `docker.container.label.org.myorg.*` to root level without using this syntax for all the fields  :
```yaml
  - rename:
      fields:
        - from: "docker.container.labels.org.myorg.logindex"
          to: "logindex"
      ignore_missing: true
      fail_on_error: false
```

An example can be : 
```yaml
  - move:
      fields:
        - from: "docker.container.labels.org.myorg.*" # wildcard
          from: "docker.container.labels.org.myorg.label" # a label 
          from: "^docker.container.labels.org.myorg.label.(test|others)$" # a regexp 
          to: "app"
          to: "." # for root
      ignore_missing: true
      fail_on_error: false
```
