### ISSUE TITLE
(Feature request) Filebeat event type comparison (autodiscover)

### ISSUE THREAD

**Issue by havlan** [elastic/beats#8764]
[Use case discussed on forums](https://discuss.elastic.co/t/filebeat-rename-processor-with-conditions/153371/2)
This is sort of a special use case which involves using Filebeat autodiscover running as a daemonset in Kubernetes. Our use case is to do some logic based solely on event values coming from pods/containers. When having a sidecar container setup we lack the possibility to match an annotation with the name of the container. This is useful for us since we are relying on logstash to parse the events coming from each container. (I know hints parses) We rely on getting a field with the correct type for logstash to correctly parse it down the road.

Example of desired functionality:
```
processors:
- rename:
    fields:
      - from: "kubernetes.labels.myapp-service"
        to: "_service"
      - from: "kubernetes.labels.myapp-token"
        to: "_token"
      - from: "kubernetes.annotations.myapp/sidecar.type"
        to: "type"
    when:
      equals:
        'kubernetes.annotations.myapp/sidecar.source': 'kubernetes.container.name'

- rename:
    fields:
      - from: "kubernetes.labels.myapp-service"
        to: "_service"
      - from: "kubernetes.labels.myapp-token"
        to: "_token"
      - from: "kubernetes.labels.myapp-type"
        to: "type"
    when:
      or:
        - not.has_fields: ['kubernetes.annotations.myapp/sidecar']
        - not.equals:
          kubernetes.annotations.myapp/sidecar: true
```

Comparing event fields can enhance Filebeats ability to account for different sidecar cases to use in container environments.

If this is possible somehow, it would be nice if someone would explain it for me.

**Comment by exekias** [comment]
Hi @havlan, thank you for opening this enhancement request.

I'm wondering if this could be possible using autodiscover, take into account that processors can be configured there too:

Disclaimer: I haven't tested this, but:

```
filebeat.autodiscover:
  providers:
    - type: kubernetes
      templates:
        - condition.has_fields: ["kubernetes.annotations.myapp/sidecar.source"]
          config:
            - type: docker
              containers.ids: ["${data.kubernetes.container.id}"]
              processors:
                - rename:
                    fields:
                      ...
                  when.equals:
                    'kubernetes.annotations.myapp/sidecar.source': "${data.kubernetes.container.name}"
```
