### ISSUE TITLE
Enhancement: Filebeat exclude lines before parsing JSON

### ISSUE THREAD

**Issue by OffColour** [elastic/beats#8775]
Currently, exclude_lines only works with JSON fields that are at the root. This makes it difficult to structure the JSON neatly if the check to exclude sits on a sub value or the data has to get shipped to logstash before being dropped.

Either parsing the JSON after the exclude or being able to exclude on sub values would be a great enhancement.

**Comment by andrewkroh** [comment]
I think you could use [decode_json_fields](https://www.elastic.co/guide/en/beats/filebeat/current/decode-json-fields.html) to accomplish this. It would allow the JSON decoding to happen after filtering.
```
filebeat.inputs:
  - paths: [mydata.json]
    processors:
      - drop_event.when.contains.message: "DEBUG" # Or use exclude_lines.
      - decode_json_fields:
          fields: [message]
          target: json
```
