### ISSUE TITLE
Filebeat not resuming after EOF

### ISSUE THREAD

**Issue by matejzero** [elastic/beats#878]
Hello,

I'm having troubles with filebeat not resuming after EOF. My filebeat is sending logs to 2 logstash nodes in loadbalance mode. Every day at random time, it stops sending with EOF error in log file:
```
2016-01-27T17:15:01+01:00 INFO Events sent: 918
2016-01-27T17:15:01+01:00 INFO Registry file updated. 491 states written.
2016-01-27T17:15:06+01:00 INFO Events sent: 490
2016-01-27T17:15:06+01:00 INFO Registry file updated. 491 states written.
2016-01-27T17:15:18+01:00 INFO Error publishing events (retrying): EOF
2016-01-27T17:15:19+01:00 INFO Events sent: 865
2016-01-27T17:15:19+01:00 INFO Registry file updated. 491 states written.
2016-01-28T00:00:05+01:00 INFO Harvester started for file: /logs/server1/httpd/20160128-httpd_access.log
2016-01-28T00:00:05+01:00 INFO Harvester started for file: /logs/server2/radius/20160128-radius.log
```

If I look at logstash logs, I see this
```
{:timestamp=>"2016-01-27T16:04:26.772000+0100", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn}
{:timestamp=>"2016-01-27T17:15:18.720000+0100", :message=>"CircuitBreaker::rescuing exceptions", :name=>"Beats input", :exception=>LogStash::Inputs::Beats::InsertingToQueueTakeTooLong, :level=>:warn}
{:timestamp=>"2016-01-27T17:15:18.720000+0100", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecting new connection until the pipeline recover.", :exception=>LogStash::Inputs::BeatsSupport::CircuitBreaker::HalfOpenBreaker, :level=>:warn}
{:timestamp=>"2016-01-27T17:15:18.815000+0100", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn}
{:timestamp=>"2016-01-27T17:15:18.816000+0100", :message=>"CircuitBreaker::Open", :name=>"Beats input", :level=>:warn}
{:timestamp=>"2016-01-27T17:15:18.817000+0100", :message=>"Beats input: The circuit breaker has detected a slowdown or stall in the pipeline, the input is closing the current connection and rejecting new connection until the pipeline recover.", :exception=>LogStash::Inputs::BeatsSupport::CircuitBreaker::OpenBreaker, :level=>:warn}
{:timestamp=>"2016-01-27T17:15:19.316000+0100", :message=>"Beats input: the pipeline is blocked, temporary refusing new connection.", :reconnect_backoff_sleep=>0.5, :level=>:warn}
```

Pipeline blocked logs continue for another 20s and then they stop. Logstash is still reading logs from redis, but filebeat never resumes. The only way to get logs flowing again is to restart filebeat.

Shouldn't filebeat resume sending of logs? At least that is the idea a got on filebeat irc channel.

**Comment by urso** [comment]
which filebeat version are you using?

Can you share your filebeat configuration?

Can you run filebeat in debug mode by running filebeat with `-v -d '*'`?

**Comment by matejzero** [comment]
Yea, sorry for lack of information.

Filebeat version: 1.0.1

Configuration:
```yaml
################### Filebeat Configuration #########################

filebeat:
  prospectors:
    -
      #
      # HTTP apache log files
      #
      paths:
        - "/logs/httpd/201601/*httpd_access.log"
      input_type: log
      fields:
        syslog_format: true
        http_proto: "http"
      fields_under_root: true
      document_type: httpd
    -
      #
      # HTTPS apache log files
      #
      paths:
        - "/logs/httpd/201601/*httpd_ssl_access.log"
      input_type: log
      fields:
        syslog_format: true
        http_proto: "https"
      fields_under_root: true
      document_type: httpd
    -
      #
      # Dovecot log files
      #
      paths:
        - "/logs/mail/201601/*mail.log"
      input_type: log
      fields:
        syslog_format: true
      fields_under_root: true
      document_type: dovecot
    -
      #
      # Postfix log files
      #
      paths:
        - "/logs/mail/201601/*mail.log"
      input_type: log
      fields:
        syslog_format: true
      fields_under_root: true
      document_type: postfix
    -
      #
      # Radius log files
      #
      paths:
        - "/logs/radius/201601/*radius.log"
      input_type: log
      fields:
        syslog_format: true
      fields_under_root: true
      document_type: radiusd
    -
      #
      # dhcpd log files
      #
      paths:
        - "/logs/dhcpd/201601/*dhcpd.log"
      input_type: log
      fields:
        syslog_format: true
      fields_under_root: true
      document_type: dhcpd

  registry_file: /var/lib/filebeat/registry
  spool_size: 4096
  #config_dir:

output:
  logstash:
    hosts: [ "logstash2:5055", "logstash1:5055" ]
    worker: 2
    loadbalance: true
    tls:
      certificate_authorities: ["/etc/pki/tls/certs/filebeat.crt"]
      certificate: "/etc/pki/tls/certs/filebeat.crt"
      certificate_key: "/etc/pki/tls/private/filebeat.key"

      # Controls whether the client verifies server certificates and host name.
      # If insecure is set to true, all server host names and certificates will be
      # accepted. In this mode TLS based connections are susceptible to
      # man-in-the-middle attacks. Use only for testing.
      #insecure: true

  # Debug output
  file:
    path: "/tmp/filebeat"
    filename: filebeat
    rotate_every_kb: 10000
    number_of_files: 2

shipper:
  name: filebeat

logging:
  to_syslog: false
  to_files: true
  files:
    path: /var/log/beats
    name: filebeat.log
    rotateeverybytes: 10485760 # = 10MB
    keepfiles: 5
  # Other available selectors are beat, publish, service
  #selectors: [ ]
  # Available log levels are: critical, error, warning, info, debug
  level: info
```

I did run it in debug mode (level: debug in config file) and what I see in logs is a bunch of:
```
2016-01-27T08:41:27+01:00 DBG  Try to publish %!s(int=200) events to logstash with window size %!s(int=1)
2016-01-27T08:41:27+01:00 DBG  %!s(int=0) events out of %!s(int=200) events sent to logstash. Continue sending ...
```

I can also run `-v -d '*'` as well if that will give any other data?

Matej

**Comment by urso** [comment]
window size becomes 1, if it filebeat failed too send over 'long' period of time. We probe logstash being operative by sending only 1 event in this case and waiting for an ACK. Which obviously failed (0 events out of 200 sent).

 Does this repeat or will filebeat stop at some point logging these messages? There should be some info messages regarding EOF in between, right?

**Comment by urso** [comment]
@matejzero there's an issue in 1.0.1 the window size not growing anymore once reached a size of 1 potentially affecting throughput. Maybe you want to test 1.1 build. 

```
output:
  logstash:
    hosts: [ "logstash2:5055", "logstash1:5055" ]
    worker: 2
    loadbalance: true
    tls:
      certificate_authorities: ["/etc/pki/tls/certs/filebeat.crt"]
      certificate: "/etc/pki/tls/certs/filebeat.crt"
      certificate_key: "/etc/pki/tls/private/filebeat.key"
```

This config generates 4 output workers (2 workers per logstash). The certificate and certificate_key options are not required, due to logstash not yet support client authentication.
