### ISSUE TITLE
[Filebeat] mongodb module events are not displayed in kibana

### ISSUE THREAD

**Issue by dennybaa** [elastic/beats#8843]
platform: kubernetes
filebeat version: 6.4.2

Mongodb events are successfully published into elasticsearch. Though kibana shows none of them, btw redis events of the redis module which is enabled side by side are showed without issues. Any idea why?
cc: @ruflin 

Details bellow

config
```yaml
  filebeat.autodiscover:
    providers:
    - type: kubernetes
      hints.enabled: false

      ## mongodb logs
      templates:
      - condition:
          equals:
            kubernetes.labels.app: mongodb
        config:
        - module: mongodb
          log:
            input:
              type: docker
              containers.ids:
                - "${data.kubernetes.container.id}"
```

mongodb event picked out from the database:
```json
      {
        "_index": "filebeat-6.4.2-2018.10.31",
        "_type": "doc",
        "_id": "rAiMyWYBHnEClVTknbhw",
        "_score": 2.706123,
        "_source": {
          "kubernetes": {
            "container": {
              "name": "my-db-mongodb"
            },
            "node": {
              "name": "ip-123-45-67-89.eu-central-1.compute.internal"
            },
            "pod": {
              "name": "my-db-mongodb-574c8b7bfd-qcmx9"
            },
            "namespace": "default",
            "replicaset": {
              "name": "my-db-mongodb-574c8b7bfd"
            },
            "labels": {
              "app": "mongodb",
              "release": "my-db",
              "pod-template-hash": "1307463698",
              "chart": "mongodb-4.2.1"
            }
          },
          "offset": 5091956,
          "prospector": {
            "type": "docker"
          },
          "read_timestamp": "2018-10-31T09:55:21.474Z",
          "source": "/var/lib/docker/containers/c980dae5eebc130f026121d001dbd54c9e9befa54263642f90db09a3f39f6fbc/c980dae5eebc130f026121d001dbd54c9e9befa54263642f90db09a3f39f6fbc-json.log",
          "fileset": {
            "module": "mongodb",
            "name": "log"
          },
          "input": {
            "type": "docker"
          },
          "@timestamp": "2018-01-31T09:55:21.473Z",
          "stream": "stdout",
          "meta": {
            "cloud": {
              "machine_type": "t2.medium",
              "availability_zone": "eu-central-1b",
              "instance_id": "i-0549d49e9af50cda7",
              "provider": "ec2",
              "region": "eu-central-1"
            }
          },
          "beat": {
            "hostname": "logs-fb-filebeat-64cq4",
            "name": "logs-fb-filebeat-64cq4",
            "version": "6.4.2"
          },
          "host": {
            "name": "logs-fb-filebeat-64cq4"
          },
          "mongodb": {
            "log": {
              "severity": "I",
              "component": "NETWORK",
              "context": "listener",
              "message": "connection accepted from 127.0.0.1:34914 #56171 (35 connections now open)"
            }
          }
        }
      }
```
