### ISSUE TITLE
Add path attribute for jolokia module

### ISSUE THREAD

**Issue by jguay** [elastic/beats#8964]
https://jolokia.org/reference/html/protocol.html#read
see 6.2.1.2 Post read request
Request is to implement the key path.

Here is an example. This snippet returns 55 metrics :

```
             jmx.mappings:
               - mbean: 'java.lang:name=PS MarkSweep,type=GarbageCollector'
                 attributes:
                   - attr: "LastGcInfo"
                     field: GC.MarkSweep
 ````

But if we only want only this metric memoryUsageAfterGc.Metaspace.used. If the path argument would be implemented, it gives :
```
                   - attr: "CollectionCount"
                     field: GC.MarkSweep.CollectionCount
                     path: "memoryUsageAfterGc/Metaspace/used"
```

or I want only all memoryUsageAfterGc.Metaspace
```
                  - attr: "CollectionCount"
                     field: GC.MarkSweep.CollectionCount
                     path: "memoryUsageAfterGc/Metaspace"
```

or I want only all used metric

```
                   - attr: "CollectionCount"
                     field: GC.MarkSweep.CollectionCount
                     path: "*/*/used"
```
