### ISSUE TITLE
Numeric value out of range of type long

### ISSUE THREAD

**Issue by aleph-zero** [elastic/beats#8975]
For confirmed bugs, please report:
- Version:  6.5.0 BC4
- Operating System: MacOS Mojave
- Discuss Forum URL:
- Steps to Reproduce: 

This is my **modules.d/system.yml**

```yaml
- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - core
    - diskio
    #- socket
  process.include_top_n:
    enabled: true
    by_cpu: 15      # include top 5 processes by CPU
    by_memory: 15   # include top 5 processes by memory

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  processors:
  - drop_event.when.regexp:
      system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'

- module: system
  period: 15m
  metricsets:
    - uptime
```

The error message I get when I run **./metricbeat -c metricbeat.yml -e**:

> 2018-11-07T11:14:21.885-0800	WARN	elasticsearch/client.go:520	Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Time{wall:0xbef0ec43324d8f05, ext:3134510882, loc:(*time.Location)(0x65f6de0)}, Meta:common.MapStr(nil), Fields:common.MapStr{"metricset":common.MapStr{"rtt":84, "name":"fsstat", "module":"system"}, "system":common.MapStr{"fsstat":common.MapStr{"total_size":common.MapStr{"used":0x4f69d22400, "total":0x15d3864d400, "free":0x10dce92b000}, "count":6, "total_files":0x80000000000002b5}}, "beat":common.MapStr{"name":"yorkie.local", "hostname":"yorkie.local", "version":"6.5.0"}, "host":common.MapStr{"architecture":"x86_64", "os":common.MapStr{"platform":"darwin", "version":"10.14", "family":"darwin", "build":"18A391"}, "name":"yorkie.local"}}, Private:interface {}(nil)}, Flags:0x0} (status=400): {"type":"mapper_parsing_exception","reason":"failed to parse field [system.fsstat.total_files] of type [long]","caused_by":{"type":"json_parse_exception","reason":"Numeric value (9223372036854776501) out of range of long (-9223372036854775808 - 9223372036854775807)\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@5db995e; line: 1, column: 240]"}}
