### ISSUE TITLE
Metricbeat etcd module can’t work with etcd v3.3.8 (https) 

### ISSUE THREAD

**Issue by opsnull** [elastic/beats#8986]
- Version: metricbeat 6.4.3
- Operating System: CentOS 7.5
- Discuss Forum URL: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-module-etcd.html
- Steps to Reproduce: 

metricbet config:
```
metricbeat.modules:
- module: etcd
  metricsets: ["leader", "self", "store"]
  period: 10s
  hosts: ["https://172.27.128.71:2379"]
  ssl:
    certificate: "/etc/cert/client.pem"
    key: "/etc/cert/client-key.pem"
    certificate_authorities: ["/etc/cert/ca.pem"]
    verification_mode: "none"

```

![image](https://user-images.githubusercontent.com/433567/48183551-041f5180-e36a-11e8-9b73-9b4aa26764e5.png)
