### ISSUE TITLE
filebeat 6.3.0 output to multiple topics

### ISSUE THREAD

**Issue by mingziV5** [elastic/beats#9008]
I need input multiple log to multiple kafka topics but  the filebeat log output:
`kafka/client.go:113 Dropping event: no topic could be selected`
my filebeat.yml :
```
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /data0/a-*.log
  fileds:
    log_topics: java_a

- type: log
  enabled: true
  paths:
    - /data0/b-*.log
  fileds:
    log_topics: java_b

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.kafka:
  enabled: true
  hosts: ["kafka1:9092","kakfa2:9092"]
  topics:
  - topic: '%{[fileds.log_topics]}'
  max_message_bytes: 2000000
```
The Kafka has created topis
I have no idea with this problem
