### ISSUE TITLE
Filebeat: 1.1+ multiline consistently fails to detect multi line events

### ISSUE THREAD

**Issue by grumpydude** [elastic/beats#902]
I've been trialling filebeat 1.1 (latest snapshot) on Ubuntu (12.04) and have tested the latest nightly for 1.2 (2016-02-01T21:10:52.000Z), and I find that it fails to detect certain log events consistently. For example, here is an event (sanitized) that generates a failure:

```
2016-02-02 02:11:01 :: DEBUG :: task :: Writing out statsd: 'server.web.curl.GET:44.512|ms
server.web.memcache.set:1|c
server.web.mysql.1:1|c
server.web.mysql.4:1|c' in /var/www/application/library/StatsD.php:304 (StatsD::sendAsUDP())
```

It consistently splits the events into the following:

> DEBUG :: task :: Writing out statsd: 'server.web.curl.GET:44.512|ms
> server.web.memcache.set:1|c
> server.web.mysql.1:1|c

and 

> server.web.mysql.4:1|c' in /var/www/application/library/StatsD.php:304 (StatsD::sendAsUDP())

This isn't the only event that fails, but it is a good example of one. 

Here's my filebeat config:

```
filebeat:
  registry_file: /var/lib/filebeat/registry
  config_dir: /etc/filebeat/conf.d

output:
  logstash:
    hosts: ["logstash1.host.com:3334", "logstash2.host.com:3334", "logstash3.host.com:3334"]
    loadbalance: true
```

Here's my prospector config:

```
filebeat:
  prospectors:
    -
      paths:
        - /var/log/system.log
      ignore_older: 2h
      fields_under_root: true
      fields:
        type: syslog
    -
      paths:
        - /var/log/web.log
      ignore_older: 1h
      fields_under_root: true
      fields:
        type: web
      multiline:
        pattern: "^[[:space:]]|^[[:alpha:]]|^[[:punct:]]"
        negate: false
        match: after
```

Note that I've tried the negate set to true (with a different regex "^[0-9]{4}-") and the same behaviour is seen.

Any ideas?
