### ISSUE TITLE
AWS ELB discovery provider.

### ISSUE THREAD

**Issue by andrewvc** [elastic/beats#9043]
I’m now thinking that the ELB autodiscovery approach I took in elastic/beats#8680 is wrong. We should still have an ELB autodiscovery provider, but it should only provide the ELB metadata, and not the exact ports. We should use a custom `aws_elb` monitor that is keyed off the ARN:

1. Fetches the latest metadata about the ELB
2. Runs a separate check for each open port on that ELB, automatically determining if it should do an HTTP or TCP check. It would also run a check on the ELB response's `state` field looking for issues with the ELB state.
3. Attaches the ELB metadata to each event

So, you’d use the autodiscovery provider, but only to create a template that would look like:

```
heartbeat.autodiscover:
  providers:
    - type: aws
      templates:
        - condition:
            contains:
              data.service: "elbv2"
          config:
            - type: aws
              arns: ["${data.arn}"]
              schedule: "@every 10s"
              timeout: 1s
```

For a TCP load balancer ports 22 and 52 open this would yield four checks:

1. A check for the ELB state field (it should be 'active')
2. A TCP check for port 22
3. A TCP check for port 52

One challenge this presents is how to key this stuff for a GUI. We currently have a semi-natural primary key of `(monitor.id, monitor.ip)`, but this change would actually need that to be a tuple of the ARN + a sub-check. This dovetails with elastic/beats#8862 which proposes adding a synthetic PK for all heartbeat monitors. I think where we're heading is we need to mirror the internal structure of heartbeat and have a notion of a parent task with multiple children. In other words, for 7.0 we'd use `monitor.id` as the 'parent' task for grouping a check, and have some second field like `monitor.task_id`, be used for subtasks. This would be more generic than the `monitor.ip` check which is specifically tied to DNS A records. 

CC: @jk @Dov @ruflin @exekias @tsg
