### ISSUE TITLE
upgrade filebeat 6.5.0 not work elk

### ISSUE THREAD

**Issue by luisgarcia1010** [elastic/beats#9101]
on the server was version 6.4.3 with configuration
```
filebeat.inputs:
- type: docker
  containers.ids:
    - "*"

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

setup.template.settings:
  index.number_of_shards: 3

output.logstash:
   hosts: ["logstash_server:5044"]
```

Everything worked, yesterday it was updated to 6.5.0 and today there is no data in elk, what could be the problem?
