### ISSUE TITLE
Ability to use kubernetes hints and custom metricsets

### ISSUE THREAD

**Issue by jguay** [elastic/beats#9123]
**Describe the enhancement:**
With the current implementation user must choose between pre-defined module setup and his custom setup defined in the raw hint.

It would be nice if the following could be implemented: 

 
```
metricbeat.autodiscover:
 providers:
   - type: kubernetes
     hints.enabled: true
     hints.combination.enabled: true
```
 

"hints.combination.enabled: true" would mean if a module has multiple metricset defined, metricbeat processes metricset(s) defined in metricbeat config, then it processes metricset(s) defined in the raw hint.
**Describe a specific use case for the enhancement or feature:**
Users want to :
- subscribe to pre-defined collections
- and add their own custom metric
