### ISSUE TITLE
kubernetes_metadata metadata does not work on windows

### ISSUE THREAD

**Issue by zentron** [elastic/beats#9196]
Version: 6.5.1

[Due to a trailing `/`](https://github.com/elastic/beats/blob/99824df163863478d27688206e18ec27bc1b3ac5/filebeat/processor/add_kubernetes_metadata/matchers.go#L62) that is placed at the end of the `LogPath`, the containerId is unable to be retrieved from the log path. 

```
2018-11-21T12:08:59.849Z        DEBUG   [kubernetes]    add_kubernetes_metadata/matchers.go:82  Incoming source value: C:\containerLogs\95357c516f55177400115df7d530626af3fb304709d52766ea4cc3989525d95f\95357c516f55177400115df7d530626af3fb304709d52766ea4cc3989525d95f-json.log
2018-11-21T12:08:59.849Z        DEBUG   [kubernetes]    add_kubernetes_metadata/matchers.go:85  Error extracting container id - source value does not contain matcher's logs_path 'C:\containerLogs/'.
```

Note the `/` at the end of the `C:\containerLogs` 
config:
```yaml
    filebeat.prospectors:
      - type: log
        paths:
          - "C:\\containerLogs\\*\\*.log"
        json.message_key: log
        json.keys_under_root: true
        processors:
          - add_kubernetes_metadata:
              in_cluster: true
              default_matchers.enabled: false
              matchers:
              - logs_path:
                  logs_path: "C:\\containerLogs"
```

Where log path on windows host is mounted in k8s by
```yaml
  - name: dockercontainers
    hostPath:
      path: "C:/ProgramData/Docker/containers"
```

the path should probably either be used un-modified by the user, or else using platform detection the appropriate seperator should be used.
