### ISSUE TITLE
TLS settings are not carried over when using a proxy_url over HTTP to connect to an HTTPS hosts.

### ISSUE THREAD

**Issue by ph** [elastic/beats#9240]
They are two modes of operation when working with TLS with a proxy server:

1. You connect to **HTTPS** to the proxy server and the proxy will be in intercept mode. (It can read the traffic)
2. You connect to **HTTP** to the proxy server after you make a **CONNECT** call to the other server and TLS will be added on top of that, this make the proxy server acts like a tunner. So the communication is encrypted from the original client to the server.

When you configure beat to use TLS and set a `proxy_url` (or via the environment variable), It will make a plain text connection to the server and will try to connect to the remote host and add the **TLS** layer on top of the communication. The problem is the configured CA will not be used to authenticate the remote server and the handshake will fails with a bad certificate.

```yaml
output:
  elasticsearch:
    protocol: https
    ssl:
      certificate_authorities: /usr/share/filebeat/logs/ca.crt
    hosts:
    - https://es0:9200
    username: elastic
    password: changeme
    proxy_url: http://proxy0:3128
````

Looking at the code in libbeat we are using the DialTLS options to create a client that will setup the TLS information.

https://github.com/elastic/beats/blob/a07884eceeeb0353e678696e6dabc8edc2eaf2b3/libbeat/outputs/elasticsearch/client.go#L204-L211

Looking at the code in the [standard library](
https://github.com/golang/go/blob/c64848595be16db1679932b134e682ad0b1f6b1e/src/net/http/transport.go#L153-L162) we have the following comment explaining that this field will not be used when you are proxying HTTPS calls, this is why the configured CA is not used when doing the handshake.

```
// DialTLS specifies an optional dial function for creating
// TLS connections for non-proxied HTTPS requests.
```

From what I understand we should instead use the **TLSClientConfig** instead to make sure that our options are used.

```golang
	// TLSClientConfig specifies the TLS configuration to use with
	// tls.Client.
	// If nil, the default configuration is used.
	// If non-nil, HTTP/2 support may not be enabled by default.
        TLSClientConfig *tls.Config
```

### Possible workaround

I haven't tested it but adding the CA to the system CA should work, because it will use the default configuration when not **TLSClientConfig** is given.

### Next Steps

We can supply the TLSClientConfig option with the configured settings, the thing is we do a few more things using callbacks when we use the **DialTLS**

- check for TLS version
- set timeout for the handshake

So I have to check if we can keep the same behavior when using proxy_url, Maybe using the following options.
```golang
    // GetConfigForClient, if not nil, is called after a ClientHello is
    // received from a client. It may return a non-nil Config in order to
    // change the Config that will be used to handle this connection. If
    // the returned Config is nil, the original Config will be used. The
    // Config returned by this callback may not be subsequently modified.
    //
    // If GetConfigForClient is nil, the Config passed to Server() will be
    // used for all connections.
    //
    // Uniquely for the fields in the returned Config, session ticket keys
    // will be duplicated from the original Config if not set.
    // Specifically, if SetSessionTicketKeys was called on the original
    // config but not on the returned config then the ticket keys from the
    // original config will be copied into the new config before use.
    // Otherwise, if SessionTicketKey was set in the original config but
    // not in the returned config then it will be copied into the returned
    // config before use. If neither of those cases applies then the key
    // material from the returned config will be used for session tickets.
    GetConfigForClient func(*ClientHelloInfo) (*Config, error) // Go 1.8

    // VerifyPeerCertificate, if not nil, is called after normal
    // certificate verification by either a TLS client or server. It
    // receives the raw ASN.1 certificates provided by the peer and also
    // any verified chains that normal processing found. If it returns a
    // non-nil error, the handshake is aborted and that error results.
    //
    // If normal verification fails then the handshake will abort before
    // considering this callback. If normal verification is disabled by
    // setting InsecureSkipVerify, or (for a server) when ClientAuth is
    // RequestClientCert or RequireAnyClientCert, then this callback will
    // be considered but the verifiedChains argument will always be nil.
    VerifyPeerCertificate func(rawCerts [][]byte, verifiedChains [][]*x509.Certificate) error // Go 1.8
```

**Comment by silh** [comment]
Is there any progress with this? We have a problem setting journalbeat in our environment due to this problem. For now we just modified the code to use TLSClientConfig.

**Comment by rpasche** [comment]
+1

**Comment by belimawr** [comment]
I did some testing today and this issue seems to be solved already. A while ago there was a big refactoring on Libbeat TLS code and now it keeps the TLS configuration when using a proxy. I tested with `v7.17.0` and `v8.0.0-rc2`.

Here is the config I used:
```yaml
filebeat.inputs:
- type: filestream
  enabled: true
  paths:
    - /tmp/flog/*.log

output.elasticsearch:
  hosts: ["localhost:9200"]
  protocol: "https"
  proxy_url: "http://localhost:8888"
  ssl:
    enabled: true
    ca_trusted_fingerprint: "some fingerprint from 8.0"
    certificate_authorities:
      - ./charles.pem # Proxy CA Cert
      - ./esCA.pem # ES CA cert from 8.0, needed for v7.17.0
  username: "elastic"
  password: "changeme"
```

Both cases I tested connecting to ES `8.0.0-rc2`

For simplicity I tested using the `test output` command, but it should make no difference from running filebeat.
