### ISSUE TITLE
Kubernetes metricbeat deploy config files don't allow to specify elastic ssl config

### ISSUE THREAD

**Issue by david-maumenee** [elastic/beats#9264]
**Describe the enhancement:**
Current version of the deployment config for Kubernetes https://github.com/elastic/beats/tree/master/deploy/kubernetes/metricbeat doesn't allow to specify SSL settings as describe at https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html

Exemple :
```yaml
output.elasticsearch.ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]
output.elasticsearch.ssl.certificate: "/etc/pki/client/cert.pem"
output.elasticsearch.ssl.key: "/etc/pki/client/cert.key"
```

It could be done by using a secret and mounting volume from this secrete

**Describe a specific use case for the enhancement or feature:**
Output the metric to a secure elasticsearch that need a certificate and key to allow connection
