### ISSUE TITLE
logstash module's `format: json` not make effect and json pipeline not matched

### ISSUE THREAD

**Issue by youzipi** [elastic/beats#9394]
- Version: 6.5.1
- Operating System: OSX 10.11.6 
- Discuss Forum URL:https://discuss.elastic.co/t/hout-to-config-filebeat-6-5-1-logstash-modules-json-decode/159329
- Steps to Reproduce: 
# 1. `format: json` not worked.
I use `logstash module` to tranfer my application's log to ELK.
but the message is not decoded correctly. 
I got the error:
![image](https://user-images.githubusercontent.com/5629307/49500089-c818d700-f8aa-11e8-9407-329a1869c69b.png)

```yaml
// ./modules.d/logstash.yml
- module: logstash
  # logs
  log:
    enabled: true
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths: ["my-log-dir/*.log"]
    format: json
```
## 1.1
first i exec `./filebeat setup`,it do not create logstash pipeline.
## 1.2
then i use setup with `--modules=logstash`, it create the `plain` pipeline.
![image](https://user-images.githubusercontent.com/5629307/49500793-7709e280-f8ac-11e8-806c-ff0f6cbea22e.png)

![pipeline-list](https://user-images.githubusercontent.com/5629307/49500673-33af7400-f8ac-11e8-900f-060f4a813aad.png)
I modified `format: json` to `var.format: json`, nothing changed. 
I tried to delete the old logstash pipeline, use `var.format: json` setup again , I still get the `plain` pipeline.

I finally hacked the `module/logstash/log/manifest.yml` to change the default format value to `json`
to setup the json pipeline.
# 2 the `pipeline-json.json` do not match `net.logstash.logback.encoder.LogstashEncoder`

I use the `logstash-logback-encoder` to write my log to local file and then filebeat send them to elk.
its maven location:
```xml
        <dependency>
            <groupId>net.logstash.logback</groupId>
            <artifactId>logstash-logback-encoder</artifactId>
            <version>5.1</version>
        </dependency>
```
app's logback config.
```xml
// spring-logback.xml
    <appender name="STASH" class="ch.qos.logback.core.rolling.RollingFileAppender">
        <file>logback/center.log</file>
        <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
            <fileNamePattern>logback/center.%d{yyyy-MM-dd}.log</fileNamePattern>
            <maxHistory>7</maxHistory>
        </rollingPolicy>
        <encoder class="net.logstash.logback.encoder.LogstashEncoder"/>
    </appender>
```
its message body not match the file:`module/logstash/log/ingest/pipeline-json.json`.
It do not contains an `timeMillis` fields.
the message body is in the above kibana screenshot.
As the pipeline convert `timeMillis` to the `@timestamp`,so I cannot use the default `Time Filter field name` 's `@timestamp` to filter my log.

Q1:
**Can anyone tell me where the default pipeline from 
or how can I use  custom pipeline for specific module from filebeat side?**
Q2:
**I cloned the source code, but i donot find how the module config parsed.**

**Comment by weltenwort** [comment]
The documentation example was incorrect for a while. The setting is called `var.format` instead of just `format`:

```yaml
// ./modules.d/logstash.yml
- module: logstash
  # logs
  log:
    enabled: true
    # Set custom paths for the log files. If left empty,
    # Filebeat will choose the paths depending on your OS.
    var.paths: ["my-log-dir/*.log"]
    var.format: json
```
