### ISSUE TITLE
Kafka output config through Central Management is missing topic name

### ISSUE THREAD

**Issue by zofog** [elastic/beats#9695]
When adding a Kafka output config, I can add the hostname but not the Kafka topic name. The config is downloaded successfully by the beat but the logs show an error due to the missing topic config.

In the management.yml
```

configok: false
configs:
- type: metricbeat.modules
  blocks:
  - raw:
      module: system
      period: 10s
- type: output
  blocks:
  - raw:
      kafka:
        hosts:
          - myserver:9092
      output: kafka
```

In the Metricbeat log:

2018-11-29T15:03:50.940-0700	WARN	[cfgwarn]	management/manager.go:100	BETA: Central management is enabled
2018-11-29T15:03:50.940-0700	INFO	[centralmgmt]	management/manager.go:101	Starting central management service
2018-11-29T15:03:50.940-0700	INFO	[monitoring]	log/log.go:117	Starting metrics logging every 30s
2018-11-29T15:03:51.934-0700	INFO	[centralmgmt]	management/manager.go:176	New configurations retrieved
2018-11-29T15:03:51.934-0700	INFO	[centralmgmt]	management/manager.go:213	Applying settings for metricbeat.modules
2018-11-29T15:03:51.942-0700	INFO	[centralmgmt]	management/manager.go:213	Applying settings for output
2018-11-29T15:03:51.943-0700	ERROR	[centralmgmt]	management/manager.go:234	**missing required 'topic' or 'topics' in kafka**
2018-11-29T15:03:51.943-0700	INFO	management/manager.go:205	Failed to apply settings, reporting error on next fetch
2018-11-29T15:03:51.943-0700	INFO	[centralmgmt]	management/manager.go:149	Storing new state
