### ISSUE TITLE
Improve Prometheus integration documentation

### ISSUE THREAD

**Issue by tbragin** [elastic/beats#9792]
Current docs on the Metricbeat Prometheus module are reference-style and quite minimal. The following blog expands on the way one can use this module and how it compares to other methods of integrating with Prometheus:
https://discuss.elastic.co/t/dec-23rd-2018-en-observability-querying-metrics-from-prometheus/161609

We should consider improving the docs, or linking to this blog.

cc: @roncohen @ruflin

**Comment by hodgesds** [comment]
Can you also include that exporting beat metrics to Prometheus is not supported.

**Comment by exekias** [comment]
Docs have improved after https://github.com/elastic/beats/pull/9948: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-metricset-prometheus-collector.html.

@tbragin do you think this is enough or we should keep this issue?

**Comment by tbragin** [comment]
We are in the process of converting the discuss blog to a blog on elastic.co. How do folks feel about linking the reference-style Prometheus documentation to that blog? Also, do we feel we should evolve our modules documentation in general to include richer information, outside simply how to configure it? Perhaps I'll add a discuss label to this.

**Comment by tbragin** [comment]
cc: @makwarth @alvarolobato

**Comment by ruflin** [comment]
+1 on having links to prometheus docs. I think it's important to link to the reference docs.

++ on having richer module docs. All information a users needs to learn more about the module, how it works etc. should be there.

**Comment by makwarth** [comment]
++ absolutely. We probably need an owner per module that takes care of the Kibana and Elastic.co documentation

**Comment by DanRoscigno** [comment]
I have to test this, but I think the first YAML excerpt on the docs would be better like so (I was confused by the port 9090 on localhost because the example is supposed to be about grabbing from an exporter, not from the Prometheus server):

```
- module: prometheus
  period: 10s
  hosts:
    - nodehost:9100 <---- the existing port 9090 in the docs is confusing, as that is the Prometheus server port.  9100 is the default Node exporter port
    - haproxyhost:9101
    - mysqlhost:9104
  metrics_path: /metrics
```
