### ISSUE TITLE
max_depth nested json not working

### ISSUE THREAD

**Issue by azhurbilo** [elastic/beats#9834]
max_depth nested json not working as expected

- Version: 6.1.2: 
- Operating System: Ubuntu 16.04.2 LTS (Xenial Xerus): 

Config "test.yml"
```
name: "host-01"
queue:
  mem:
    events: 16384
    # batch of events to the outputs. "0" ensures events are immediately available to be sent to the outputs.
    flush.min_events: 0


filebeat:
  prospectors:
    - type: log
      paths:
       - '/tmp/test.log'
      json:
        # key on which to apply the line filtering and multiline settings
        message_key: log
        keys_under_root: true
        add_error_key: true
      processors:
      - decode_json_fields:
          fields: ["log"]
          process_array: false
          max_depth: 1
          overwrite_keys: false
          when:
            regexp:
               log: '^\{.*\}$'

output:
  console:
    pretty: true
```

- Steps to Reproduce: 
1. run filebeat `filebeat -c test.yml`
2. in other tab run `echo '{"log":"{ \"status\": { \"foo\": { \"bar\": 1 } }, \"bytes_sent\": \"0\", \"gzip_ratio\": \"-\", \"hostname\": \"cb7b5441f0da\" }\n","stream":"stdout","time":"2018-12-29T11:25:36.130729806Z"}'  >> /tmp/test.log`
3. check output of filebeat result

Expected result: "status" filed not parsed deeper because of `max_depth: 1`

Actual result:

```
{
  "@timestamp": "2018-12-29T13:05:38.661Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "doc",
    "version": "6.1.2"
  },
  "source": "/tmp/test.log",
  "offset": 7080,
  "log": {
    "status": {
      "foo": {
        "bar": 1
      }
    },
    "bytes_sent": "0",
    "gzip_ratio": "-",
    "hostname": "cb7b5441f0da"
  },
  "stream": "stdout",
  "time": "2018-12-29T11:25:36.130729806Z",
  "prospector": {
    "type": "log"
  },
  "beat": {
    "hostname": "host-01",
    "version": "6.1.2",
    "name": "host-01"
  }
}
```
