### ISSUE TITLE
metricbeat - multiple elasticsearch hosts via environment variable

### ISSUE THREAD

**Issue by gentunian** [elastic/beats#9837]
# Bug report
[Using a list via environment variable](https://www.elastic.co/guide/en/beats/metricbeat/6.5/using-environ-vars.html) (for multiple elasticsearch hosts) it's producing wrong arguments for metricbeat output.

Relevant `docker-compose.yml` part:
```YAML
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.5.4
    networks:
      - esnet
    environment:
      - ELASTICSEARCH_HOSTS="elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200"
    volumes:
      - /mnt/metricbeats/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro
```

`metricbeat.yml` fille:
```YAML
metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
#  Won't work for env ELASTICSEARCH_HOSTS="url1:9200,url2:9200"
#  hosts: '${ELASTICSEARCH_HOSTS}'
#
# Below line is working OK
  hosts: ["elasticsearch-node1:9200","elasticsearch-node2:9200", "elasticsearch-node3:9200"]
```

Error log:
```
2018-12-31T15:22:04.518Z	ERROR	pipeline/output.go:100	Failed to connect to backoff(elasticsearch(http://[elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200]:9200)): Get http://[elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200]:9200: lookup elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200: no such host
2018-12-31T15:22:04.518Z	INFO	pipeline/output.go:93	Attempting to reconnect to backoff(elasticsearch(http://[elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200]:9200)) with 13 reconnect attempt(s)
2018-12-31T15:22:04.518Z	WARN	transport/tcp.go:53	DNS lookup failure "elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200": lookup elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200: no such host

```

For confirmed bugs, please report:
- Version: 6.5.4
- Operating System: official docker image running on ubuntu 16.04 host

# Steps to Reproduce

1. create this `docker-compose.yml` file:
```YAML
version: '3'

services:

  # elasticsearch node 1
  elasticsearch-node1:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    networks:
      - esnet
    environment:
      - cluster.name=my.cluster
      - node.name=es1
      - network.host=_eth0:ipv4_,_eth1:ipv4_,_local_
      - transport.host=_eth0:ipv4_,_eth1:ipv4_,_local_
      - transport.bind_host=_eth0:ipv4_,_eth1:ipv4_,_local_
      - transport.tcp.port=9300
      - indices.recovery.max_bytes_per_sec=20mb
      - gateway.expected_nodes=3
      - cluster.routing.allocation.node_concurrent_recoveries=1
      - discovery.zen.minimum_master_nodes=2
      - discovery.zen.ping.unicast.hosts=elasticsearch-node2,elasticsearch-node3

  # elasticsearch node 2
  elasticsearch-node2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    networks:
      - esnet
    environment:
      - cluster.name=my.cluster
      - node.name=es2
      - network.host=_eth0:ipv4_,_local_
      - transport.host=_eth0:ipv4_,_local_
      - transport.bind_host=_eth0:ipv4_,_local_
      - transport.tcp.port=9300
      - indices.recovery.max_bytes_per_sec=20mb
      - gateway.expected_nodes=3
      - cluster.routing.allocation.node_concurrent_recoveries=1
      - discovery.zen.minimum_master_nodes=2
      - discovery.zen.ping.unicast.hosts=elasticsearch-node1,elasticsearch-node3

  # elasticsearch node 3
  elasticsearch-node3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.4
    networks:
      - esnet
    environment:
      - cluster.name=my.cluster
      - node.name=es3
      - network.host=_eth0:ipv4_,_local_
      - transport.host=_eth0:ipv4_,_local_
      - transport.bind_host=_eth0:ipv4_,_local_
      - transport.tcp.port=9300
      - indices.recovery.max_bytes_per_sec=20mb
      - gateway.expected_nodes=3
      - cluster.routing.allocation.node_concurrent_recoveries=1
      - discovery.zen.minimum_master_nodes=2
      - discovery.zen.ping.unicast.hosts=elasticsearch-node1,elasticsearch-node2

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.5.4
    user: root
    networks: 
      - esnet
    environment:
      - ELASTICSEARCH_HOSTS="elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/metricbeats/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  esnet:
```

2. Create this `metricbeat.yml` file:
```YAML
metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    # Reload module configs as they change:
    reload.enabled: false

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    #- "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

processors:
  - add_cloud_metadata: ~

output.elasticsearch:
# Won't work for ELASTICSEARCH_HOSTS="url1:9200,url2:9200"
  hosts: '${ELASTICSEARCH_HOSTS}'
```
3. Run: `docker stack deploy -c docker-compose.yml bug`
4. Check the logs: `docker service logs -f bug_metricbeat` for error like:
```
2018-12-31T15:48:33.616Z	INFO	pipeline/output.go:95	Connecting to backoff(elasticsearch(http://[elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200]:9200))
2018-12-31T15:48:33.616Z	WARN	transport/tcp.go:53	DNS lookup failure "elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200": lookup elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200: no such host
2018-12-31T15:48:34.617Z	ERROR	pipeline/output.go:100	Failed to connect to backoff(elasticsearch(http://[elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200]:9200)): Get http://[elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200]:9200: lookup elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200: no such host
```

**Comment by jsoriano** [comment]
Hi @gentunian,

I have tried (with a simpler scenario), and I couldn't reproduce the issue.
Could you check if the file inside the container still has the environment variable? The environment variable has to be there and is interpreted by metricbeat in runtime.

I am running the metricbeat docker directly with `docker run`:
```
docker run -it --rm \
    -e ELASTICSEARCH_HOSTS=elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200 \
    -v $PWD/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml \
    docker.elastic.co/beats/metricbeat:6.5.4 \
    metricbeat run -e --strict.perms=fals
```
Using for `metricbeat.yml` the one in the description.

And metricbeat fails because I am not mounting the docker socket, but the option is being correctly parsed:
```
2019-01-03T17:44:02.567Z	INFO	elasticsearch/client.go:163	Elasticsearch url: http://elasticsearch-node1:9200
2019-01-03T17:44:02.567Z	INFO	elasticsearch/client.go:163	Elasticsearch url: http://elasticsearch-node2:9200
2019-01-03T17:44:02.567Z	INFO	elasticsearch/client.go:163	Elasticsearch url: http://elasticsearch-node3:9200
```

**Comment by jsoriano** [comment]
@gentunian please, for unconfirmed bugs or questions about configuration, use http://discuss.elastic.co.

I am going to close this till we can confirm that it is actually a bug in beats.

**Comment by jsoriano** [comment]
Umm, actually I can reproduce the issue with this reduced docker-compose.yml too, not sure what is the difference with the `docker run`.
```
version: '3'
  
services:
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:6.5.4
    environment:
      - ELASTICSEARCH_HOSTS="elasticsearch-node1:9200,elasticsearch-node2:9200,elasticsearch-node3:9200"
    volumes:
      - ./metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
```
