### ISSUE TITLE
Unable to metricbeat elasticsearch when xpack.watcher disabled

### ISSUE THREAD

**Issue by erik-stephens** [elastic/beats#9875]
For confirmed bugs, please report:
- Version: 6.5.3 & 6.5.4
- Operating System: ubuntu xenial
- Discuss Forum URL: https://discuss.elastic.co/t/error-when-elasticsearch-xpack-watcher-enabled-false/161595
- Steps to Reproduce: 

I get this error when trying to ship xpack.enabled:true node_stats to an elasticsearch monitoring cluster:

> 2018-12-19T14:42:05.741Z	ERROR	node_stats/data_xpack.go:208	failure to apply node schema: 1 error: key thread_pool.watcher not found

Setting `xpack.watcher.enabled:true` in elasticsearch cluster config works around that issue. Should I be able to collect node_stats when watcher is disabled?  Thanks!

My modules.d/elasticsearch.yml:
```
- module: elasticsearch
  metricsets:
    - node_stats
  period: 10s
  hosts:
    - "http://127.0.0.1:9200"
  xpack.enabled: true
```
