### ISSUE TITLE
Broken: Multiline json with "log" as message key(6.5+)

### ISSUE THREAD

**Issue by fayizk1** [elastic/beats#9877]
Hello,

We are running filebeat on our kubernetes cluster to ship the pod's logs. Our log format is json and using the multiline module.

**Here is the config**

```
filebeat.prospectors:
- type: log
  fields:
    k8s_env: ${K8S_ENV}
    k8s_cluster: ${K8S_CLUSTER}
    k8s_node_ip: ${K8S_NODE_IP}
    type: k8s-${K8S_ENV:qa}
  fields_under_root: true
  paths:
    - "/var/log/containers/*.log"
  exclude_files:
    - ".*filebeat.*"
    - ".*kube-system.*"
  symlinks: true
  json.message_key: log
  json.keys_under_root: true
  json.add_error_key: true
  multiline.pattern: '^\s'
  multiline.match: after
```

**log format**

```
{"log":"18:30:49.288 [task-xxx-8] [] []\n","stream":"stdout","time":"2019-01-03T18:30:49.289325478Z"}
{"log":"        INFO  x.x.i.xx.xxx - xxxxxx xx xxxx xx xxxx xxx [xxx xx xxxx] \n","stream":"stdout","time":"2019-01-03T18:30:49.289352375Z"}
```

A few days ago we upgraded the filebeat to 6.5(`filebeat version 6.5.3 (amd64), libbeat 6.5.3` ) and started to see logstash indexing errors. Upon verifying the filebeat changes, we found that there is a new field introduced in 6.5 which overwrites multiline message when message key name is "log"(`json.message_key: log`).
 
**commit reference:** https://github.com/elastic/beats/commit/4d3ccd64df7892d23246f8f6b0390a5c938b0214#diff-f2fcf2d9efeb0d21038407c0e99b931eR277

### Sample log outputs

**V6.5.3** (Broken)
```
{"@timestamp":"2019-01-03T17:49:47.610Z","@metadata":{"beat":"filebeat","type":"doc","version":"6.5.3"},"time":"2018-12-03T11:31:09.555022726Z","source":"/var/log/container/multilinefile.log","offset":369647,"k8s_cluster":"xxx","k8s_node_ip":"xx.xx.xx.xx","k8s_env":"xxx-xx","prospector":{"type":"log"},"input":{"type":"log"},"type":"xx-xx-xx","beat":{"name":"filebeat-kwfqs","hostname":"filebeat-kwfqs","version":"6.5.3"},"host":{"name":"filebeat-kwfqs"},"log":{"flags":["multiline"]},"stream":"stdout"}
```

**V6.4.3** (Working)
```
{"@timestamp":"2019-01-03T19:16:49.905Z","@metadata":{"beat":"filebeat","type":"doc","version":"6.4.3"},"k8s_node_ip":"xxxxx","type":"xxxxxx","beat":{"version":"6.4.3","name":"filebeat-kwfqs","hostname":"filebeat-kwfqs"},"host":{"name":"filebeat-kwfqs"},"source":"/var/log/container/multilinefile.log","log":"11:46:48.409 [xx-xx-xx-exec-7] [] [xxxxx.xxxx]\n        INFO  xx.xx.xx.xx.s.xx - xx xxxx xxx(xxxx=xxx, xxx=xxx, xxx=xxx, xx=xxx, xxxx=xxxxx) xxx=xxx.xxxxxxx","time":"2018-12-03T11:46:48.409411503Z","k8s_env":"ccccc","k8s_cluster":"ccccc","prospector":{"type":"log"},"offset":393932,"stream":"stdout","input":{"type":"log"}}
```

For confirmed bugs, please report:
- Version: filebeat version 6.5.3 (amd64), libbeat 6.5.3
- Operating System: Linux 4.14.65
