### ISSUE TITLE
Heatbeat config test does not check auto-reloadable monitors

### ISSUE THREAD

**Issue by vbohata** [elastic/beats#9912]
I tried to create invalid monitor file in monitors.d directory. When running hearbeat, it logs error about configuration issue but "test config" command passes config as OK. Configuration test command should test all the configs.

```
heartbeat.config.monitors:
  # Directory + glob pattern to search for configuration files - NOT BEING CHECK BY test config
  path: monitors.d/*.yml
  # If enabled, heartbeat will periodically check the config.monitors path for changes
  reload.enabled: true
  # How often to check for changes
  reload.period: 1s
```
