### ISSUE TITLE
Make `convert_timezone` option available in all filesets by default

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#9993]
Some of the log message read by the Filebeat modules do not contain the time zone. To convert the time to UTC and have the same timestamps for all events the `date` processor in Elasticsearch is used: https://www.elastic.co/guide/en/elasticsearch/reference/master/date-processor.html

To make this processor available as an option each fileset has to implement the following options:

Update the module manifest.yml with the `convert_timezone` option:

```
  - name: convert_timezone
    default: false
    # if ES < 6.1.0, this flag switches to false automatically when evaluating the
    # pipeline
    min_elasticsearch_version:
      version: 6.1.0
      value: false
```

Update the pipeline with a date processor and introduce the optional time zone conversion:
```
{
    "date": {
        "field": "logstash.log.timestamp",
        "target_field": "@timestamp",
        "formats": [
          "ISO8601"
      ],
      {< if .convert_timezone >}"timezone": "{{ event.timezone }}",{< end >}
      "ignore_failure": true
    }
}
```

Instead of introducing this to each fileset it would be nice that by default this is available in all filesets. This would reduce the changes we have to make to all the existing filesets and when introducing new filesets it would automatically be part of it.

For the filesets that do not need it, it would still be there but not be used.
